<?php
trait game_description_ebet_bbin {

	public function sync_game_description_ebet_bbin(){
		$cnt=0;
		$cntInsert = 0;
		$cntUpdate = 0;

		$db_true = 1;
		$db_false = 0;
		$api_id = EBET_BBIN_API;
		$now = $this->utils->getNowForMysql();
		$game_type_id = $this->get_game_type_ids_opus();

		$game_type_code_bb_lottery = "ebet_bbin_bb_lottery";
		$game_type_code_bb_sport = "ebet_bbin_bb_sport";
		$game_type_code_feature_games = "ebet_bbin_feature_games";
		$game_type_code_large_machine = "ebet_bbin_large_machine";
		$game_type_code_scatch_card = "ebet_bbin_scatch_card";
		$game_type_code_slot_game = "ebet_bbin_slot_game";
        $game_type_code_table_game = "ebet_bbin_table_game";
		$game_type_code_bb_livecasino = "game_type_code_bb_livecasino";
		$game_type_code_unknown = "ebet_bbin_unknown";


		// sync game type first
		// use game_type_code as key
		$game_types = [
			$game_type_code_bb_lottery => [
				'game_platform_id' => $api_id,
				'game_type' => '_json:{"1":"BB Lotterry","2":"BB Lotterry","3":"BB Lotterry","4":"BB Lotterry"}',
				'game_type_lang' => '_json:{"1":"BB Lotterry","2":"BB Lotterry","3":"BB Lotterry","4":"BB Lotterry"}',
				"game_type_code" => $game_type_code_bb_lottery,
				'flag_show_in_site' => $db_true,
				'auto_add_new_game' => $db_true,
				'auto_add_to_cashback' => $db_true,
				'status'=>$db_true,
				'updated_at'=>$now,
			],
			$game_type_code_bb_sport => [
				'game_platform_id' => $api_id,
				'game_type' => '_json:{"1":"BB Sport","2":"BB Sport","3":"BB Sport","4":"BB Sport"}',
				'game_type_lang' => '_json:{"1":"BB Sport","2":"BB Sport","3":"BB Sport","4":"BB Sport"}',
				"game_type_code" => $game_type_code_bb_sport,
				'flag_show_in_site' => $db_true,
				'auto_add_new_game' => $db_true,
				'auto_add_to_cashback' => $db_true,
				'status'=>$db_true,
				'updated_at'=>$now,
			],
			$game_type_code_feature_games => [
				'game_platform_id' => $api_id,
				'game_type' => '_json:{"1":"Feature Games","2":"Feature Games","3":"Feature Games","4":"Feature Games"}',
				'game_type_lang' => '_json:{"1":"Feature Games","2":"Feature Games","3":"Feature Games","4":"Feature Games"}',
				"game_type_code" => $game_type_code_feature_games,
				'flag_show_in_site' => $db_true,
				'auto_add_new_game' => $db_true,
				'auto_add_to_cashback' => $db_true,
				'status'=>$db_true,
				'updated_at'=>$now,
			],
			$game_type_code_large_machine => [
				'game_platform_id' => $api_id,
				'game_type' => '_json:{"1":"Large Machine","2":"Large Machine","3":"Large Machine","4":"Large Machine"}',
				'game_type_lang' => '_json:{"1":"Large Machine","2":"Large Machine","3":"Large Machine","4":"Large Machine"}',
				"game_type_code" => $game_type_code_large_machine,
				'flag_show_in_site' => $db_true,
				'auto_add_new_game' => $db_true,
				'auto_add_to_cashback' => $db_true,
				'status'=>$db_true,
				'updated_at'=>$now,
			],
			$game_type_code_scatch_card =>[
				'game_platform_id' => $api_id,
				'game_type' => '_json:{"1":"Scratch Card","2":"Scratch Card","3":"Scratch Card","4":"Scratch Card"}',
				'game_type_lang' => '_json:{"1":"Scratch Card","2":"Scratch Card","3":"Scratch Card","4":"Scratch Card"}',
				"game_type_code" => $game_type_code_scatch_card,
				'flag_show_in_site' => $db_true,
				'auto_add_new_game' => $db_true,
				'auto_add_to_cashback' => $db_true,
				'status'=>$db_true,
				'updated_at'=>$now,
			],
			$game_type_code_slot_game => [
				'game_platform_id' => $api_id,
				'game_type' => '_json:{"1":"Slot Game","2":"Slot Game","3":"Slot Game","4":"Slot Game"}',
				'game_type_lang' => '_json:{"1":"Slot Game","2":"Slot Game","3":"Slot Game","4":"Slot Game"}',
				"game_type_code" => $game_type_code_slot_game,
				'flag_show_in_site' => $db_true,
				'auto_add_new_game' => $db_true,
				'auto_add_to_cashback' => $db_true,
				'status'=>$db_true,
				'updated_at'=>$now,
			],
            $game_type_code_table_game => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Table Game","2":"Table Game","3":"Table Game","4":"Table Game"}',
                'game_type_lang' => '_json:{"1":"Table Game","2":"Table Game","3":"Table Game","4":"Table Game"}',
                "game_type_code" => $game_type_code_table_game,
                'flag_show_in_site' => $db_true,
                'auto_add_new_game' => $db_true,
                'auto_add_to_cashback' => $db_true,
                'status'=>$db_true,
                'updated_at'=>$now,
            ],
			$game_type_code_bb_livecasino => [
				'game_platform_id' => $api_id,
				'game_type' => '_json:{"1":"BB Casino live","2":"BB Casino live","3":"BB Casino live","4":"BB Casino live"}',
				'game_type_lang' => '_json:{"1":"BB Casino live","2":"BB Casino live","3":"BB Casino live","4":"BB Casino live"}',
				"game_type_code" => $game_type_code_bb_livecasino,
				'flag_show_in_site' => $db_true,
				'auto_add_new_game' => $db_true,
				'auto_add_to_cashback' => $db_true,
				'status'=>$db_true,
				'updated_at'=>$now,
			],
			$game_type_code_unknown => [
				'game_platform_id' => $api_id,
				'game_type' => '_json:{"1":"Unknown","2":"不明类型","3":"Unknown","4":"Unknown"}',
				'game_type_lang' => '_json:{"1":"Unknown","2":"不明类型","3":"Unknown","4":"Unknown"}',
				"game_type_code" => $game_type_code_unknown,
				'flag_show_in_site' => $db_true,
				'auto_add_new_game' => $db_true,
				'auto_add_to_cashback' => $db_true,
				'status'=>$db_true,
				'updated_at'=>$now,
			],
		];


		$this->load->model(['game_type_model']);
		//this code is checking the game type table with game
		//also insertion of new game type based on game_type_code
		// 'game_type_id' => $gameTypeCodeMaps[$game_type_code_table_game],
		$gameTypeCodeMaps=$this->game_type_model->syncGameTypes($game_types);
		// echo "<pre>";
		// print_r($gameTypeCodeMaps);
		// die();
		$this->utils->debug_log('gameTypeCodeMaps', $gameTypeCodeMaps);

		$game_descriptions = array(
			#====================================Jackpot=========================================
            [
                'game_name' => '_json:{"1":"JACKPOT","2":"JACKPOT","3":"JACKPOT", "4":"JACKPOT"}',
                'game_code' => '5888',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' =>
                'external_game_id' => '5888',
                'english_name' => 'JACKPOT',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            #====================================BB Lottery=========================================
            [
                'game_name' => '_json:{"1":"六合彩","2":"六合彩","3":"六合彩", "4":"六合彩"}',
                'game_code' => 'LT',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => BB Lottery
                'external_game_id' => 'LT',
                'english_name' => '六合彩',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"3D 彩","2":"3D 彩","3":"3D 彩", "4":"3D 彩"}',
                'game_code' => 'BJ3D',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => BB Lottery
                'external_game_id' => 'BJ3D',
                'english_name' => '3D 彩',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"排列三","2":"排列三","3":"排列三", "4":"排列三"}',
                'game_code' => 'PL3D',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => BB Lottery
                'external_game_id' => 'PL3D',
                'english_name' => '排列三',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"BB 雷電 PK","2":"BB 雷電 PK","3":"BB 雷電 PK", "4":"BB 雷電 PK"}',
                'game_code' => 'RDPK',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => BB Lottery
                'external_game_id' => 'RDPK',
                'english_name' => 'BB 雷電 PK',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"梯子遊戲","2":"梯子遊戲","3":"梯子遊戲", "4":"梯子遊戲"}',
                'game_code' => 'LDDR',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => BB Lottery
                'external_game_id' => 'LDDR',
                'english_name' => '梯子遊戲',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"BB PK3","2":"BB PK3","3":"BB PK3", "4":"BB PK3"}',
                'game_code' => 'BBPK',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => BB Lottery
                'external_game_id' => 'BBPK',
                'english_name' => 'BB PK3',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"BB3D","2":"BB3D","3":"BB3D", "4":"BB3D"}',
                'game_code' => 'BB3D',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => BB Lottery
                'external_game_id' => 'BB3D',
                'english_name' => 'BB3D',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"BB 快樂彩","2":"BB 快樂彩","3":"BB 快樂彩", "4":"BB 快樂彩"}',
                'game_code' => 'BBKN',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => BB Lottery
                'external_game_id' => 'BBKN',
                'english_name' => 'BB 快樂彩',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"BB 滾球王","2":"BB 滾球王","3":"BB 滾球王", "4":"BB 滾球王"}',
                'game_code' => 'BBRB',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => BB Lottery
                'external_game_id' => 'BBRB',
                'english_name' => 'BB 滾球王',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"BB 百家彩票-A","2":"BB 百家彩票-A","3":"BB 百家彩票-A", "4":"BB 百家彩票-A"}',
                'game_code' => 'BCRA',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => BB Lottery
                'external_game_id' => 'BCRA',
                'english_name' => 'BB 百家彩票-A',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"BB 百家彩票-B","2":"BB 百家彩票-B","3":"BB 百家彩票-B", "4":"BB 百家彩票-B"}',
                'game_code' => 'BCRB',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => BB Lottery
                'external_game_id' => 'BCRB',
                'english_name' => 'BB 百家彩票-B',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"BB 百家彩票-C","2":"BB 百家彩票-C","3":"BB 百家彩票-C", "4":"BB 百家彩票-C"}',
                'game_code' => 'BCRC',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => BB Lottery
                'external_game_id' => 'BCRC',
                'english_name' => 'BB 百家彩票-C',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"BB 百家彩票-D","2":"BB 百家彩票-D","3":"BB 百家彩票-D", "4":"BB 百家彩票-D"}',
                'game_code' => 'BCRD',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => BB Lottery
                'external_game_id' => 'BCRD',
                'english_name' => 'BB 百家彩票-D',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"BB 百家彩票-E","2":"BB 百家彩票-E","3":"BB 百家彩票-E", "4":"BB 百家彩票-E"}',
                'game_code' => 'BCRE',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => BB Lottery
                'external_game_id' => 'BCRE',
                'english_name' => 'BB 百家彩票-E',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"上海時時樂","2":"上海時時樂","3":"上海時時樂", "4":"上海時時樂"}',
                'game_code' => 'SH3D',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => BB Lottery
                'external_game_id' => 'SH3D',
                'english_name' => '上海時時樂',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"重慶時時彩","2":"重慶時時彩","3":"重慶時時彩", "4":"重慶時時彩"}',
                'game_code' => 'CQSC',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => BB Lottery
                'external_game_id' => 'CQSC',
                'english_name' => '重慶時時彩',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"天津時時彩","2":"天津時時彩","3":"天津時時彩", "4":"天津時時彩"}',
                'game_code' => 'TJSC',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => BB Lottery
                'external_game_id' => 'TJSC',
                'english_name' => '天津時時彩',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"新疆時時彩","2":"新疆時時彩","3":"新疆時時彩", "4":"新疆時時彩"}',
                'game_code' => 'XJSC',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => BB Lottery
                'external_game_id' => 'XJSC',
                'english_name' => '新疆時時彩',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"重慶幸運農場","2":"重慶幸運農場","3":"重慶幸運農場", "4":"重慶幸運農場"}',
                'game_code' => 'CQSF',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => BB Lottery
                'external_game_id' => 'CQSF',
                'english_name' => '重慶幸運農場',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"廣西十分彩","2":"廣西十分彩","3":"廣西十分彩", "4":"廣西十分彩"}',
                'game_code' => 'GXSF',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => BB Lottery
                'external_game_id' => 'GXSF',
                'english_name' => '廣西十分彩',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"天津十分彩","2":"天津十分彩","3":"天津十分彩", "4":"天津十分彩"}',
                'game_code' => 'TJSF',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => BB Lottery
                'external_game_id' => 'TJSF',
                'english_name' => '天津十分彩',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"北京 PK 拾","2":"北京 PK 拾","3":"北京 PK 拾", "4":"北京 PK 拾"}',
                'game_code' => 'BJPK',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => BB Lottery
                'external_game_id' => 'BJPK',
                'english_name' => '北京 PK 拾',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"BB 競速快樂彩","2":"BB 競速快樂彩","3":"BB 競速快樂彩", "4":"BB 競速快樂彩"}',
                'game_code' => 'BBQK',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => BB Lottery
                'external_game_id' => 'BBQK',
                'english_name' => 'BB 競速快樂彩',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"北京快樂 8","2":"北京快樂 8","3":"北京快樂 8", "4":"北京快樂 8"}',
                'game_code' => 'BJKN',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => BB Lottery
                'external_game_id' => 'BJKN',
                'english_name' => '北京快樂 8',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"加拿大卑斯","2":"加拿大卑斯","3":"加拿大卑斯", "4":"加拿大卑斯"}',
                'game_code' => 'CAKN',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => BB Lottery
                'external_game_id' => 'CAKN',
                'english_name' => '加拿大卑斯',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"廣東 11 選 5","2":"廣東 11 選 5","3":"廣東 11 選 5", "4":"廣東 11 選 5"}',
                'game_code' => 'GDE5',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => BB Lottery
                'external_game_id' => 'GDE5',
                'english_name' => '廣東 11 選 5',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"江西 11 選 5","2":"江西 11 選 5","3":"江西 11 選 5", "4":"江西 11 選 5"}',
                'game_code' => 'JXE5',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => BB Lottery
                'external_game_id' => 'JXE5',
                'english_name' => '江西 11 選 5',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"山東十一運奪金","2":"山東十一運奪金","3":"山東十一運奪金", "4":"山東十一運奪金"}',
                'game_code' => 'SDE5',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => BB Lottery
                'external_game_id' => 'SDE5',
                'english_name' => '山東十一運奪金',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"BB 幸運熊貓","2":"BB 幸運熊貓","3":"BB 幸運熊貓", "4":"BB 幸運熊貓"}',
                'game_code' => 'LKPA',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => BB Lottery
                'external_game_id' => 'LKPA',
                'english_name' => 'BB 幸運熊貓',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"BB 射龍門","2":"BB 射龍門","3":"BB 射龍門", "4":"BB 射龍門"}',
                'game_code' => 'BBLM',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => BB Lottery
                'external_game_id' => 'BBLM',
                'english_name' => 'BB 射龍門',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"重慶百變王牌","2":"重慶百變王牌","3":"重慶百變王牌", "4":"重慶百變王牌"}',
                'game_code' => 'CQWC',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => BB Lottery
                'external_game_id' => 'CQWC',
                'english_name' => '重慶百變王牌',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"江蘇快 3","2":"江蘇快 3","3":"江蘇快 3", "4":"江蘇快 3"}',
                'game_code' => 'JSQ3',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => BB Lottery
                'external_game_id' => 'JSQ3',
                'english_name' => '江蘇快 3',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"安徽快 3","2":"安徽快 3","3":"安徽快 3", "4":"安徽快 3"}',
                'game_code' => 'AHQ3',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => BB Lottery
                'external_game_id' => 'AHQ3',
                'english_name' => '安徽快 3',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            #====================================BB Sport=========================================
            [
                'game_name' => '_json:{"1":"Football","2":"Football","3":"Football", "4":"Football"}',
                'game_code' => 'FT',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_sport],
                // 'game_type' => BB Sport
                'external_game_id' => 'FT',
                'english_name' => 'Football',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"BasketBall","2":"BasketBall","3":"BasketBall", "4":"BasketBall"}',
                'game_code' => 'BK',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_sport],
                // 'game_type' => BB Sport
                'external_game_id' => 'BK',
                'english_name' => 'BasketBall',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"American style football","2":"American style football","3":"American style football", "4":"American style football"}',
                'game_code' => 'FB',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_sport],
                // 'game_type' => BB Sport
                'external_game_id' => 'FB',
                'english_name' => 'American style football',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Ice ball","2":"Ice ball","3":"Ice ball", "4":"Ice ball"}',
                'game_code' => 'IH',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_sport],
                // 'game_type' => BB Sport
                'external_game_id' => 'IH',
                'english_name' => 'Ice ball',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Baseball","2":"Baseball","3":"Baseball", "4":"Baseball"}',
                'game_code' => 'BS',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_sport],
                // 'game_type' => BB Sport
                'external_game_id' => 'BS',
                'english_name' => 'Baseball',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Tennis","2":"Tennis","3":"Tennis", "4":"Tennis"}',
                'game_code' => 'TN',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_sport],
                // 'game_type' => BB Sport
                'external_game_id' => 'TN',
                'english_name' => 'Tennis',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Others","2":"Others","3":"Others", "4":"Others"}',
                'game_code' => 'F1',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_sport],
                // 'game_type' => BB Sport
                'external_game_id' => 'F1',
                'english_name' => 'Others',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Championship","2":"Championship","3":"Championship", "4":"Championship"}',
                'game_code' => 'SP',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_sport],
                // 'game_type' => BB Sport
                'external_game_id' => 'SP',
                'english_name' => 'Championship',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Mixed Pass","2":"Mixed Pass","3":"Mixed Pass", "4":"Mixed Pass"}',
                'game_code' => 'CB',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_sport],
                // 'game_type' => BB Sport
                'external_game_id' => 'CB',
                'english_name' => 'Mixed Pass',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            #====================================Featured Games=========================================
            [
                'game_name' => '_json:{"1":"Chain of arms","2":"連環奪寶 ","3":"Chain of arms", "4":"Chain of arms"}',
                'game_code' => '5901',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_feature_games],
                // 'game_type' => Featured Games
                'external_game_id' => '5901',
                'english_name' => 'Chain of arms',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Candy party","2":"糖果派對 ","3":"Candy party", "4":"Candy party"}',
                'game_code' => '5902',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_feature_games],
                // 'game_type' => Featured Games
                'external_game_id' => '5902',
                'english_name' => 'Candy party',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Qin Huang secret treasure","2":"秦皇祕寶 ","3":"Qin Huang secret treasure", "4":"Qin Huang secret treasure"}',
                'game_code' => '5903',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_feature_games],
                // 'game_type' => Featured Games
                'external_game_id' => '5903',
                'english_name' => 'Qin Huang secret treasure',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Stream bombs","2":"蒸氣炸彈 ","3":"Stream bombs", "4":"Stream bombs"}',
                'game_code' => '5904',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_feature_games],
                // 'game_type' => Featured Games
                'external_game_id' => '5904',
                'english_name' => 'Stream bombs',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Mahjong with environmental protection","2":"麻將連環寶 ","3":"Mahjong with environmental protection", "4":"Mahjong with environmental protection"}',
                'game_code' => '5905',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_feature_games],
                // 'game_type' => Featured Games
                'external_game_id' => '5905',
                'english_name' => 'Mahjong with environmental protection',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Fun billiards","2":"趣味台球 ","3":"Fun billiards", "4":"Fun billiards"}',
                'game_code' => '5907',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_feature_games],
                // 'game_type' => Featured Games
                'external_game_id' => '5907',
                'english_name' => 'Fun billiards',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            #====================================Large machine=========================================
            [
                'game_name' => '_json:{"1":"5PK Ace 5PK","2":"王牌 ","3":"5PK Ace 5PK", "4":"5PK Ace 5PK"}',
                'game_code' => '5034',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_large_machine],
                // 'game_type' => Large machine
                'external_game_id' => '5034',
                'english_name' => '5PK Ace 5PK',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Caribbean Poker","2":"加勒比撲克 ","3":"Caribbean Poker", "4":"Caribbean Poker"}',
                'game_code' => '5035',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_large_machine],
                // 'game_type' => Large machine
                'external_game_id' => '5035',
                'english_name' => 'Caribbean Poker',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Gold wheel","2":"黃金大轉輪 ","3":"Gold wheel", "4":"Gold wheel"}',
                'game_code' => '5070',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_large_machine],
                // 'game_type' => Large machine
                'external_game_id' => '5070',
                'english_name' => 'Gold wheel',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Baccarat wheel","2":"百家樂大轉輪 ","3":"Baccarat wheel", "4":"Baccarat wheel"}',
                'game_code' => '5073',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_large_machine],
                // 'game_type' => Large machine
                'external_game_id' => '5073',
                'english_name' => 'Baccarat wheel',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Digital wheel","2":"數字大轉輪 ","3":"Digital wheel", "4":"Digital wheel"}',
                'game_code' => '5076',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_large_machine],
                // 'game_type' => Large machine
                'external_game_id' => '5076',
                'english_name' => 'Digital wheel',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Fruit turner","2":"水果大轉輪 ","3":"Fruit turner", "4":"Fruit turner"}',
                'game_code' => '5077',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_large_machine],
                // 'game_type' => Large machine
                'external_game_id' => '5077',
                'english_name' => 'Fruit turner',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Chess big turn","2":"象棋大轉輪 ","3":"Chess big turn", "4":"Chess big turn"}',
                'game_code' => '5078',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_large_machine],
                // 'game_type' => Large machine
                'external_game_id' => '5078',
                'english_name' => 'Chess big turn',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"3D digital wheel","2":"3D 數字大轉輪 ","3":"3D digital wheel", "4":"3D digital wheel"}',
                'game_code' => '5079',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_large_machine],
                // 'game_type' => Large machine
                'external_game_id' => '5079',
                'english_name' => '3D digital wheel',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Lotto wheel","2":"樂透轉輪 ","3":"Lotto wheel", "4":"Lotto wheel"}',
                'game_code' => '5080',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_large_machine],
                // 'game_type' => Large machine
                'external_game_id' => '5080',
                'english_name' => 'Lotto wheel',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Diamond train","2":"鑽石列車 ","3":"Diamond train", "4":"Diamond train"}',
                'game_code' => '5083',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_large_machine],
                // 'game_type' => Large machine
                'external_game_id' => '5083',
                'english_name' => 'Diamond train',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Sacred legend","2":"聖獸傳說 ","3":"Sacred legend", "4":"Sacred legend"}',
                'game_code' => '5084',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_large_machine],
                // 'game_type' => Large machine
                'external_game_id' => '5084',
                'english_name' => 'Sacred legend',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            #====================================Scratch Card=========================================
            [
                'game_name' => '_json:{"1":"lianliankan","2":"連連看 ","3":"lianliankan", "4":"lianliankan"}',
                'game_code' => '5701',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_scatch_card],
                // 'game_type' => Scratch Card
                'external_game_id' => '5701',
                'english_name' => 'lianliankan',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Well developed","2":"發達囉 ","3":"Well developed", "4":"Well developed"}',
                'game_code' => '5703',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_scatch_card],
                // 'game_type' => Scratch Card
                'external_game_id' => '5703',
                'english_name' => 'Well developed',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"bullfighting","2":"鬥牛 ","3":"bullfighting", "4":"bullfighting"}',
                'game_code' => '5704',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_scatch_card],
                // 'game_type' => Scratch Card
                'external_game_id' => '5704',
                'english_name' => 'bullfighting',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Treasure bowl","2":"聚寶盆 ","3":"Treasure bowl", "4":"Treasure bowl"}',
                'game_code' => '5705',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_scatch_card],
                // 'game_type' => Scratch Card
                'external_game_id' => '5705',
                'english_name' => 'Treasure bowl',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Passionate chocolate","2":"濃情巧克力 ","3":"Passionate chocolate", "4":"Passionate chocolate"}',
                'game_code' => '5706',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_scatch_card],
                // 'game_type' => Scratch Card
                'external_game_id' => '5706',
                'english_name' => 'Passionate chocolate',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Leopard","2":"金錢豹 ","3":"Leopard", "4":"Leopard"}',
                'game_code' => '5707',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_scatch_card],
                // 'game_type' => Scratch Card
                'external_game_id' => '5707',
                'english_name' => 'Leopard',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            #====================================Slot Game=========================================
            [
                'game_name' => '_json:{"1":"Star wars ","2":"惑星戰記","3":"Star wars ", "4":"Star wars "}',
                'game_code' => '5005',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5005',
                'english_name' => 'Star wars ',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Staronic","2":"Staronic","3":"Staronic", "4":"Staronic"}',
                'game_code' => '5006',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5006',
                'english_name' => 'Staronic',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Sparkling fruit plate ","2":"激爆水果盤","3":"Sparkling fruit plate ", "4":"Sparkling fruit plate "}',
                'game_code' => '5007',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5007',
                'english_name' => 'Sparkling fruit plate ',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Monkey climbing trees","2":" 猴子爬樹","3":"Monkey climbing trees", "4":"Monkey climbing trees"}',
                'game_code' => '5008',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5008',
                'english_name' => 'Monkey climbing trees',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"King Kong climbing the floor ","2":"金剛爬樓","3":"King Kong climbing the floor ", "4":"King Kong climbing the floor "}',
                'game_code' => '5009',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5009',
                'english_name' => 'King Kong climbing the floor ',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Alien warfare","2":"外星戰記 ","3":"Alien warfare", "4":"Alien warfare"}',
                'game_code' => '5010',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5010',
                'english_name' => 'Alien warfare',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":" Tradition","2":"傳統","3":" Tradition", "4":" Tradition"}',
                'game_code' => '5013',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5013',
                'english_name' => ' Tradition',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":" Jungle","2":"叢林","3":" Jungle", "4":" Jungle"}',
                'game_code' => '5014',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5014',
                'english_name' => ' Jungle',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"FIFA2010","2":"FIFA2010","3":"FIFA2010", "4":"FIFA2010"}',
                'game_code' => '5015',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5015',
                'english_name' => 'FIFA2010',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Prehistoric jungle adventure","2":"史前叢林冒險 ","3":"Prehistoric jungle adventure", "4":"Prehistoric jungle adventure"}',
                'game_code' => '5016',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5016',
                'english_name' => 'Prehistoric jungle adventure',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Star Wars","2":"星際大戰 ","3":"Star Wars", "4":"Star Wars"}',
                'game_code' => '5017',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5017',
                'english_name' => 'Star Wars',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":" Qi Tian Da Sheng","2":"齊天大聖","3":" Qi Tian Da Sheng", "4":" Qi Tian Da Sheng"}',
                'game_code' => '5018',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5018',
                'english_name' => ' Qi Tian Da Sheng',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Fruit paradise","2":"水果樂園 ","3":"Fruit paradise", "4":"Fruit paradise"}',
                'game_code' => '5019',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5019',
                'english_name' => 'Fruit paradise',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Fighting Sea White Snake","2":"法海鬥白蛇 ","3":"Fighting Sea White Snake", "4":"Fighting Sea White Snake"}',
                'game_code' => '5025',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5025',
                'english_name' => 'Fighting Sea White Snake',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"2012 倫敦奧運","2":"2012 倫敦奧運","3":"2012 倫敦奧運", "4":"2012 倫敦奧運"}',
                'game_code' => '5026',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5026',
                'english_name' => '2012 倫敦奧運',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Kung fu Dragon","2":"Kung fu Dragon","3":"Kung fu Dragon", "4":"Kung fu Dragon"}',
                'game_code' => '5027',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5027',
                'english_name' => 'Kung fu Dragon',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Mid-Autumn Moon Party","2":"中秋月光派對","3":"Mid-Autumn Moon Party", "4":"Mid-Autumn Moon Party"}',
                'game_code' => '5028',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5028',
                'english_name' => 'Mid-Autumn Moon Party',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Christmas party","2":"聖誕派對 ","3":"Christmas party", "4":"Christmas party"}',
                'game_code' => '5029',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5029',
                'english_name' => 'Christmas party',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Lucky god of wealth","2":"幸運財神","3":"Lucky god of wealth", "4":"Lucky god of wealth"}',
                'game_code' => '5030',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5030',
                'english_name' => 'Lucky god of wealth',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Fish and shrimp","2":"魚蝦蟹 ","3":"Fish and shrimp", "4":"Fish and shrimp"}',
                'game_code' => '5039',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5039',
                'english_name' => 'Fish and shrimp',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Wild two king","2":"百搭二王","3":"Wild two king", "4":"Wild two king"}',
                'game_code' => '5040',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5040',
                'english_name' => 'Wild two king',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"7PK","2":"7PK","3":"7PK", "4":"7PK"}',
                'game_code' => '5041',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5041',
                'english_name' => '7PK',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Alien battlefield","2":"異星戰場 ","3":"Alien battlefield", "4":"Alien battlefield"}',
                'game_code' => '5042',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5042',
                'english_name' => 'Alien battlefield',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Diamond fruit plate","2":"鑽石水果盤 ","3":"Diamond fruit plate", "4":"Diamond fruit plate"}',
                'game_code' => '5043',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5043',
                'english_name' => 'Diamond fruit plate',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Spy crisis","2":"特務危機","3":"Spy crisis", "4":"Spy crisis"}',
                'game_code' => '5048',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5048',
                'english_name' => 'Spy crisis',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Jade futon","2":"玉蒲團 ","3":"Jade futon", "4":"Jade futon"}',
                'game_code' => '5049',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5049',
                'english_name' => 'Jade futon',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Burst dice","2":"爆骰 ","3":"Burst dice", "4":"Burst dice"}',
                'game_code' => '5054',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5054',
                'english_name' => 'Burst dice',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"明星 97 Star 97","2":"明星 97 Star 97","3":"明星 97 Star 97", "4":"明星 97 Star 97"}',
                'game_code' => '5057',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5057',
                'english_name' => '明星 97 Star 97',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Crazy fruit plate","2":"瘋狂水果盤 ","3":"Crazy fruit plate", "4":"Crazy fruit plate"}',
                'game_code' => '5058',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5058',
                'english_name' => 'Crazy fruit plate',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Animal Wonders Five","2":"動物奇觀五 ","3":"Animal Wonders Five", "4":"Animal Wonders Five"}',
                'game_code' => '5060',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5060',
                'english_name' => 'Animal Wonders Five',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"超級 7 Super 7","2":"超級 7 Super 7","3":"超級 7 Super 7", "4":"超級 7 Super 7"}',
                'game_code' => '5061',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5061',
                'english_name' => '超級 7 Super 7',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Dragon in the embarrassing way","2":"龍在囧途 ","3":"Dragon in the embarrassing way", "4":"Dragon in the embarrassing way"}',
                'game_code' => '5062',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5062',
                'english_name' => 'Dragon in the embarrassing way',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Fruit pull","2":"水果拉霸 ","3":"Fruit pull", "4":"Fruit pull"}',
                'game_code' => '5063',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5063',
                'english_name' => 'Fruit pull',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Poker pull","2":"撲克拉霸 ","3":"Poker pull", "4":"Poker pull"}',
                'game_code' => '5064',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5064',
                'english_name' => 'Poker pull',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Cheese bar","2":"筒子拉霸 ","3":"Cheese bar", "4":"Cheese bar"}',
                'game_code' => '5065',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5065',
                'english_name' => 'Cheese bar',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Football pull","2":"足球拉霸 ","3":"Football pull", "4":"Football pull"}',
                'game_code' => '5066',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5066',
                'english_name' => 'Football pull',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Westward Journey","2":"大話西遊 ","3":"Westward Journey", "4":"Westward Journey"}',
                'game_code' => '5067',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5067',
                'english_name' => 'Westward Journey',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Cool circus","2":"酷搜馬戲團 ","3":"Cool circus", "4":"Cool circus"}',
                'game_code' => '5068',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5068',
                'english_name' => 'Cool circus',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Fruit ring","2":"水果擂台 ","3":"Fruit ring", "4":"Fruit ring"}',
                'game_code' => '5069',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5069',
                'english_name' => 'Fruit ring',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Golden Rooster Annunciation","2":"金雞報喜 ","3":"Golden Rooster Annunciation", "4":"Golden Rooster Annunciation"}',
                'game_code' => '5090',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5090',
                'english_name' => 'Golden Rooster Annunciation',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Three Kingdom Pull","2":"三國拉霸 ","3":"Three Kingdom Pull", "4":"Three Kingdom Pull"}',
                'game_code' => '5091',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5091',
                'english_name' => 'Three Kingdom Pull',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Gods list","2":"封神榜 ","3":"Gods list", "4":"Gods list"}',
                'game_code' => '5092',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5092',
                'english_name' => 'Gods list',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Jin Ping Mei","2":"金瓶梅 ","3":"Jin Ping Mei", "4":"Jin Ping Mei"}',
                'game_code' => '5093',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5093',
                'english_name' => 'Jin Ping Mei',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Jin Ping Mei 2","2":"金瓶梅 2 ","3":"Jin Ping Mei 2", "4":"Jin Ping Mei 2"}',
                'game_code' => '5094',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5094',
                'english_name' => 'Jin Ping Mei 2',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"cockfighting","2":"鬥雞 ","3":"cockfighting", "4":"cockfighting"}',
                'game_code' => '5095',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5095',
                'english_name' => 'cockfighting',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Three Kingdom","2":"三國 ","3":"Three Kingdom", "4":"Three Kingdom"}',
                'game_code' => '5106',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5106',
                'english_name' => 'Three Kingdom',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Flaming Mountain","2":"火燄山 ","3":"Flaming Mountain", "4":"Flaming Mountain"}',
                'game_code' => '5201',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5201',
                'english_name' => 'Flaming Mountain',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Moonlight box","2":"月光寶盒 ","3":"Moonlight box", "4":"Moonlight box"}',
                'game_code' => '5202',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5202',
                'english_name' => 'Moonlight box',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":" Love you a million years","2":"愛你一萬年","3":" Love you a million years", "4":" Love you a million years"}',
                'game_code' => '5203',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5203',
                'english_name' => ' Love you a million years',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"2014 FIFA","2":"2014 FIFA","3":"2014 FIFA", "4":"2014 FIFA"}',
                'game_code' => '5204',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5204',
                'english_name' => '2014 FIFA',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Night market life","2":"夜市人生 ","3":"Night market life", "4":"Night market life"}',
                'game_code' => '5402',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5402',
                'english_name' => 'Night market life',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Beach Volleyball","2":"沙灘排球 ","3":"Beach Volleyball", "4":"Beach Volleyball"}',
                'game_code' => '5404',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5404',
                'english_name' => 'Beach Volleyball',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Shenzhou 27","2":"神舟 27 ","3":"Shenzhou 27", "4":"Shenzhou 27"}',
                'game_code' => '5406',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5406',
                'english_name' => 'Shenzhou 27',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"big red cap and little wolf","2":"大紅帽與小野狼 ","3":"big red cap and little wolf", "4":"big red cap and little wolf"}',
                'game_code' => '5407',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5407',
                'english_name' => 'big red cap and little wolf',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Unceasingly adventure","2":"秘境冒險 ","3":"Unceasingly adventure", "4":"Unceasingly adventure"}',
                'game_code' => '5601',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5601',
                'english_name' => 'Unceasingly adventure',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Dolphin World","2":"海豚世界 ","3":"Dolphin World", "4":"Dolphin World"}',
                'game_code' => '5801',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5801',
                'english_name' => 'Dolphin World',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Achilles","2":"阿基里斯 ","3":"Achilles", "4":"Achilles"}',
                'game_code' => '5802',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5802',
                'english_name' => 'Achilles',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Aztec Treasure","2":"阿兹特克寶藏 ","3":"Aztec Treasure", "4":"Aztec Treasure"}',
                'game_code' => '5803',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5803',
                'english_name' => 'Aztec Treasure',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Superstar","2":"大明星","3":"Superstar", "4":"Superstar"}',
                'game_code' => '5804',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5804',
                'english_name' => 'Superstar',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Caesar Empire","2":"凱薩帝國 ","3":"Caesar Empire", "4":"Caesar Empire"}',
                'game_code' => '5805',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5805',
                'english_name' => 'Caesar Empire',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Fantasy garden","2":"奇幻花園 ","3":"Fantasy garden", "4":"Fantasy garden"}',
                'game_code' => '5806',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5806',
                'english_name' => 'Fantasy garden',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Ronin warrior","2":"浪人武士 ","3":"Ronin warrior", "4":"Ronin warrior"}',
                'game_code' => '5808',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5808',
                'english_name' => 'Ronin warrior',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Air combat hero","2":"空戰英豪 ","3":"Air combat hero", "4":"Air combat hero"}',
                'game_code' => '5809',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5809',
                'english_name' => 'Air combat hero',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Sailig times","2":"航海時代 ","3":"Sailig times", "4":"Sailig times"}',
                'game_code' => '5810',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5810',
                'english_name' => 'Sailig times',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Carnival night","2":"狂歡夜 ","3":"Carnival night", "4":"Carnival night"}',
                'game_code' => '5811',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5811',
                'english_name' => 'Carnival night',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"International football","2":"國際足球 ","3":"International football", "4":"International football"}',
                'game_code' => '5821',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5821',
                'english_name' => 'International football',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Made a fortune","2":"發大財 ","3":"Made a fortune", "4":"Made a fortune"}',
                'game_code' => '5823',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5823',
                'english_name' => 'Made a fortune',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Legend of the dragon","2":"惡龍傳說 ","3":"Legend of the dragon", "4":"Legend of the dragon"}',
                'game_code' => '5824',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5824',
                'english_name' => 'Legend of the dragon',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Jinlian","2":"金蓮 ","3":"Jinlian", "4":"Jinlian"}',
                'game_code' => '5825',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5825',
                'english_name' => 'Jinlian',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Gold miners","2":"金礦工 ","3":"Gold miners", "4":"Gold miners"}',
                'game_code' => '5826',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5826',
                'english_name' => 'Gold miners',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Old captain","2":"老船長 ","3":"Old captain", "4":"Old captain"}',
                'game_code' => '5827',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5827',
                'english_name' => 'Old captain',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Tyrannosaurus rex","2":"霸王龍 ","3":"Tyrannosaurus rex", "4":"Tyrannosaurus rex"}',
                'game_code' => '5828',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5828',
                'english_name' => 'Tyrannosaurus rex',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"golf tour","2":"高球之旅","3":"golf tour", "4":"golf tour"}',
                'game_code' => '5831',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5831',
                'english_name' => 'golf tour',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"High speed truck","2":"高速卡車 ","3":"High speed truck", "4":"High speed truck"}',
                'game_code' => '5832',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5832',
                'english_name' => 'High speed truck',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Silencer warrior","2":"沉默武士 ","3":"Silencer warrior", "4":"Silencer warrior"}',
                'game_code' => '5833',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5833',
                'english_name' => 'Silencer warrior',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Hi Blessing year","2":"喜福牛年 ","3":"Hi Blessing year", "4":"Hi Blessing year"}',
                'game_code' => '5835',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5835',
                'english_name' => 'Hi Blessing year',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Tornado","2":"龍捲風 ","3":"Tornado", "4":"Tornado"}',
                'game_code' => '5836',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5836',
                'english_name' => 'Tornado',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Hi Blessing monkey year","2":"喜福猴年 ","3":"Hi Blessing monkey year", "4":"Hi Blessing monkey year"}',
                'game_code' => '5837',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slot_game],
                // 'game_type' => Slot Game
                'external_game_id' => '5837',
                'english_name' => 'Hi Blessing monkey year',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            #====================================Table Game=========================================
            [
                'game_name' => '_json:{"1":"明星 97II Star 9711","2":"明星 97II Star 9711","3":"明星 97II Star 9711", "4":"明星 97II Star 9711"}',
                'game_code' => '5044',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_table_game],
                // 'game_type' => Table Game
                'external_game_id' => '5044',
                'english_name' => '明星 97II Star 9711',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Big fight","2":"鬥大 ","3":"Big fight", "4":"Big fight"}',
                'game_code' => '5088',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_table_game],
                // 'game_type' => Table Game
                'external_game_id' => '5088',
                'english_name' => 'Big fight',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Red dog","2":"紅狗 ","3":"Red dog", "4":"Red dog"}',
                'game_code' => '5089',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_table_game],
                // 'game_type' => Table Game
                'external_game_id' => '5089',
                'english_name' => 'Red dog',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"European roulette","2":"歐式輪盤 ","3":"European roulette", "4":"European roulette"}',
                'game_code' => '5105',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_table_game],
                // 'game_type' => Table Game
                'external_game_id' => '5105',
                'english_name' => 'European roulette',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"American roulette","2":"美式輪盤 ","3":"American roulette", "4":"American roulette"}',
                'game_code' => '5107',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_table_game],
                // 'game_type' => Table Game
                'external_game_id' => '5107',
                'english_name' => 'American roulette',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Gold wheel","2":"彩金輪盤 ","3":"Gold wheel", "4":"Gold wheel"}',
                'game_code' => '5108',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_table_game],
                // 'game_type' => Table Game
                'external_game_id' => '5108',
                'english_name' => 'Gold wheel',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"French roulette","2":"法式輪盤 ","3":"French roulette", "4":"French roulette"}',
                'game_code' => '5109',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_table_game],
                // 'game_type' => Table Game
                'external_game_id' => '5109',
                'english_name' => 'French roulette',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Classic Blackjack","2":"經典 21 點 ","3":"Classic Blackjack", "4":"Classic Blackjack"}',
                'game_code' => '5115',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_table_game],
                // 'game_type' => Table Game
                'external_game_id' => '5115',
                'english_name' => 'Classic Blackjack',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Spain at 21 o’clock","2":"西班牙 21 點 ","3":"Spain at 21 o’clock", "4":"Spain at 21 o’clock"}',
                'game_code' => '5116',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_table_game],
                // 'game_type' => Table Game
                'external_game_id' => '5116',
                'english_name' => 'Spain at 21 o’clock',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Vegas 16 points","2":"維加斯 21 點 ","3":"Vegas 16 points", "4":"Vegas 16 points"}',
                'game_code' => '5117',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_table_game],
                // 'game_type' => Table Game
                'external_game_id' => '5117',
                'english_name' => 'Vegas 16 points',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Bonus of 21 points","2":"獎金 21 點 ","3":"Bonus of 21 points", "4":"Bonus of 21 points"}',
                'game_code' => '5118',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_table_game],
                // 'game_type' => Table Game
                'external_game_id' => '5118',
                'english_name' => 'Bonus of 21 points',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Royal Texas Hold’em Poker","2":"皇家德州撲克 ","3":"Royal Texas Hold’em Poker", "4":"Royal Texas Hold’em Poker"}',
                'game_code' => '5131',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_table_game],
                // 'game_type' => Table Game
                'external_game_id' => '5131',
                'english_name' => 'Royal Texas Hold’em Poker',
                'game_platform_id' => $api_id,
                'status'=> $db_true,
                'flag_show_in_site'=>$db_true,
                'updated_at'=>$now,
            ],
            #================================================== BB live Casino ========================================
            [
                'game_name' => '_json:{"1":"Baccarat","2":"百家樂 ","3":"Baccarat", "4":"Baccarat"}',
                'game_code' => '3001',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_livecasino],
                // 'game_type' => Table Game
                'external_game_id' => '3001',
                'english_name' => 'Baccarat',
                'game_platform_id' => $api_id,
                'status'=> $db_true,
                'flag_show_in_site'=>$db_true,
                'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Twenty Bars","2":"二八槓 ","3":"Twenty Bars", "4":"Twenty Bars"}',
                'game_code' => '3002',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_livecasino],
                // 'game_type' => Table Game
                'external_game_id' => '3002',
                'english_name' => 'Twenty Bars',
                'game_platform_id' => $api_id,
                'status'=> $db_true,
                'flag_show_in_site'=>$db_true,
                'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Dragon Tiger","2":"龍虎鬥 ","3":"Dragon Tiger", "4":"Dragon Tiger"}',
                'game_code' => '3003',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_livecasino],
                // 'game_type' => Table Game
                'external_game_id' => '3003',
                'english_name' => 'Dragon Tiger',
                'game_platform_id' => $api_id,
                'status'=> $db_true,
                'flag_show_in_site'=>$db_true,
                'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"三公","2":"三公 ","3":"三公", "4":"三公"}',
                'game_code' => '3005',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_livecasino],
                // 'game_type' => Table Game
                'external_game_id' => '3005',
                'english_name' => '三公',
                'game_platform_id' => $api_id,
                'status'=> $db_true,
                'flag_show_in_site'=>$db_true,
                'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"溫州牌九","2":"溫州牌九 ","3":"溫州牌九", "4":"溫州牌九"}',
                'game_code' => '3006',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_livecasino],
                // 'game_type' => Table Game
                'external_game_id' => '3006',
                'english_name' => '溫州牌九',
                'game_platform_id' => $api_id,
                'status'=> $db_true,
                'flag_show_in_site'=>$db_true,
                'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Routette","2":"輪盤 ","3":"輪盤", "4":"輪盤"}',
                'game_code' => '3007',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_livecasino],
                // 'game_type' => Table Game
                'external_game_id' => '3007',
                'english_name' => 'Routette',
                'game_platform_id' => $api_id,
                'status'=> $db_true,
                'flag_show_in_site'=>$db_true,
                'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Sicbo","2":"骰寶 ","3":"骰寶", "4":"骰寶"}',
                'game_code' => '3008',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_livecasino],
                // 'game_type' => Table Game
                'external_game_id' => '3008',
                'english_name' => 'Sicbo',
                'game_platform_id' => $api_id,
                'status'=> $db_true,
                'flag_show_in_site'=>$db_true,
                'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"Texas Poker","2":"德州撲克 ","3":"德州撲克", "4":"德州撲克"}',
                'game_code' => '3010',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_livecasino],
                // 'game_type' => Table Game
                'external_game_id' => '3010',
                'english_name' => 'Texas Poker',
                'game_platform_id' => $api_id,
                'status'=> $db_true,
                'flag_show_in_site'=>$db_true,
                'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"色碟","2":"色碟 ","3":"色碟", "4":"色碟"}',
                'game_code' => '3011',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_livecasino],
                // 'game_type' => Table Game
                'external_game_id' => '3011',
                'english_name' => '色碟',
                'game_platform_id' => $api_id,
                'status'=> $db_true,
                'flag_show_in_site'=>$db_true,
                'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"cow cow","2":"牛牛 ","3":"牛牛", "4":"牛牛"}',
                'game_code' => '3012',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_livecasino],
                // 'game_type' => Table Game
                'external_game_id' => '3012',
                'english_name' => 'cow cow',
                'game_platform_id' => $api_id,
                'status'=> $db_true,
                'flag_show_in_site'=>$db_true,
                'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"無限21 點","2":"無限21 點","3":"無限21 點", "4":"無限21 點"}',
                'game_code' => '3014',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_livecasino],
                // 'game_type' => Table Game
                'external_game_id' => '3014',
                'english_name' => '無限21 點',
                'game_platform_id' => $api_id,
                'status'=> $db_true,
                'flag_show_in_site'=>$db_true,
                'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"番攤","2":"番攤","3":"番攤", "4":"番攤"}',
                'game_code' => '3015',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_livecasino],
                // 'game_type' => Table Game
                'external_game_id' => '3015',
                'english_name' => '番攤',
                'game_platform_id' => $api_id,
                'status'=> $db_true,
                'flag_show_in_site'=>$db_true,
                'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"魚蝦蟹","2":"魚蝦蟹","3":"魚蝦蟹", "4":"魚蝦蟹"}',
                'game_code' => '3016',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_livecasino],
                // 'game_type' => Table Game
                'external_game_id' => '3016',
                'english_name' => '魚蝦蟹',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],

            #================================================== Unknown Game ========================================
            [
                'game_name' => '_json:{"1":"Unknown","2":"不明类型","3":"Unknown","4":"Unknown"}',
                'game_code' => 'unknown',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_unknown],
                // 'game_type' => Table Game
                'external_game_id' => 'unknown',
                'english_name' => 'Unknown',
                'game_platform_id' => $api_id,
				'status'=> $db_true,
				'flag_show_in_site'=>$db_true,
				'updated_at'=>$now,
            ],

            #====================================End Game list=========================================
            #===================================== NEW Game5/25/2017 ===========================================
            [
                'game_name' => '_json:{"1":"Classic Ladder","2":"经典梯子","3":"Classic Ladder", "4":"Classic Ladder"}',
                'game_code' => 'LDRS',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => Table Game
                'external_game_id' => 'LDRS',
                'english_name' => 'Classic Ladder',
                'game_platform_id' => $api_id,
                'status'=> $db_true,
                'flag_show_in_site'=>$db_true,
                'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"BB Mark Six Bingo","2":"BB 六合彩","3":"BB Mark Six Bingo", "4":"BB Mark Six Bingo"}',
                'game_code' => 'BBLT',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_bb_lottery],
                // 'game_type' => Table Game
                'external_game_id' => 'BBLT',
                'english_name' => 'BB Mark Six Bingo',
                'game_platform_id' => $api_id,
                'status'=> $db_true,
                'flag_show_in_site'=>$db_true,
                'updated_at'=>$now,
            ],
            #====================================End new Game =========================================

		);

		$this->load->model(['game_description_model']);

		$success=$this->game_description_model->syncGameDescription($game_descriptions);

		return $success;
	}

}
