<?php
trait game_description_onesgame {

    public function sync_game_description_onesgame(){
        $api_id= ONESGAME_API;
        $this->sync_onesgame($api_id);
    }

    public function sync_onesgame($api_id){
        $db_true=1;
        $db_false=0;
        $now=$this->utils->getNowForMysql();

        $game_type_code_arcade               = SYNC::TAG_CODE_ARCADE;
        $game_type_code_slots                = SYNC::TAG_CODE_SLOT;
        $game_type_code_table_and_cards_game = SYNC::TAG_CODE_TABLE_AND_CARDS;
        $game_type_code_unknown              = SYNC::TAG_CODE_UNKNOWN_GAME;

        $game_types = [
            $game_type_code_arcade => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Arcade","2":"街机游戏","3":"Arcade","4":"Arcade","5":"Arcade"}',
                "game_type_code" => $game_type_code_arcade,
                'game_tag_code' => SYNC::TAG_CODE_ARCADE
            ],
            $game_type_code_slots => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Slots","2":"老虎机","3":"Slots","4":"Slots","5":"Slots"}',
                "game_type_code" => $game_type_code_slots,
                'game_tag_code' => SYNC::TAG_CODE_SLOT
            ],
            $game_type_code_table_and_cards_game => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Table and Cards","2":"赌桌游戏","3":"Table and Cards","4":"Table and Cards","5":"Table and Cards"}',
                "game_type_code" => $game_type_code_table_and_cards_game,
                'game_tag_code' => SYNC::TAG_CODE_TABLE_AND_CARDS
            ],
            $game_type_code_unknown => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                "game_type_code" => $game_type_code_unknown,
                'flag_show_in_site' => $db_false,
                'game_tag_code' => SYNC::TAG_CODE_UNKNOWN_GAME
            ]
        ];

        echo "<pre>";
        $this->load->model(['game_type_model']);
        $gameTypeCodeMaps=$this->game_type_model->syncGameTypes($game_types);

        $this->utils->debug_log('gameTypeCodeMaps', $gameTypeCodeMaps);

        $game_descriptions=[
            //==================== desktop games ======================
                        [
                'game_name' => '_json:{"1":"Monkey King","2":"胜者为王","3":"Monkey King","4":"Monkey King","5":"Monkey King"}',
                'game_code' => 'GS7_AC001',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => 'AC001',
                'english_name' => 'Monkey King',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_arcade],
            ],
            [
                'game_name' => '_json:{"1":"Jacks or Better","2":"杰克高手","3":"Jacks or Better","4":"Jacks or Better","5":"Jacks or Better"}',
                'game_code' => 'GS11_AC002',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => 'AC002',
                'english_name' => 'Jacks or Better',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_arcade],
            ],
            [
                'game_name' => '_json:{"1":"Joker Poker","2":"王牌扑克","3":"Joker Poker","4":"Joker Poker","5":"Joker Poker"}',
                'game_code' => 'GS11_AC003',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => 'AC003',
                'english_name' => 'Joker Poker',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_arcade],
            ],
            [
                'game_name' => '_json:{"1":"Bruce the Legend","2":"传说之龙","3":"Bruce the Legend","4":"Bruce the Legend","5":"Bruce the Legend"}',
                'game_code' => 'GS49_4400',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '4400',
                'english_name' => 'Bruce the Legend',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Outlawed Gunslinger","2":"流亡神枪手","3":"Outlawed Gunslinger","4":"Outlawed Gunslinger","5":"Outlawed Gunslinger"}',
                'game_code' => 'GS48_4300',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '4300',
                'english_name' => 'Outlawed Gunslinger',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Clover\'s Tales","2":"四叶草","3":"Clover\'s Tales","4":"Clover\'s Tales","5":"Clover\'s Tales"}',
                'game_code' => 'GS47_4200',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '4200',
                'english_name' => 'Clover\'s Tales',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Samurai Sensei","2":"武士宗师","3":"Samurai Sensei","4":"Samurai Sensei","5":"Samurai Sensei"}',
                'game_code' => 'GS46_4100',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '4100',
                'english_name' => 'Samurai Sensei',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Dr Eerie\'s Experiment","2":"诡异博士","3":"Dr Eerie\'s Experiment","4":"Dr Eerie\'s Experiment","5":"Dr Eerie\'s Experiment"}',
                'game_code' => 'GS44_4000',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '4000',
                'english_name' => 'Dr Eerie\'s Experiment',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Age of Golden Ape","2":"金猿时代","3":"Age of Golden Ape","4":"Age of Golden Ape","5":"Age of Golden Ape"}',
                'game_code' => 'GS43_3900',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '3900',
                'english_name' => 'Age of Golden Ape',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"The Majestic Taj","2":"雄伟的泰姬陵","3":"The Majestic Taj","4":"The Majestic Taj","5":"The Majestic Taj"}',
                'game_code' => 'GS42_3800',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '3800',
                'english_name' => 'The Majestic Taj',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Sparta\'s Legacy","2":"斯巴达传奇","3":"Sparta\'s Legacy","4":"Sparta\'s Legacy","5":"Sparta\'s Legacy"}',
                'game_code' => 'GS41_3700',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '3700',
                'english_name' => 'Sparta\'s Legacy',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Little Fantail","2":"小扇尾","3":"Little Fantail","4":"Little Fantail","5":"Little Fantail"}',
                'game_code' => 'GS40_3600',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '3600',
                'english_name' => 'Little Fantail',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"The Mu Lan","2":"花木兰","3":"The Mu Lan","4":"The Mu Lan","5":"The Mu Lan"}',
                'game_code' => 'GS39_3500',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '3500',
                'english_name' => 'The Mu Lan',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Spirit Bear","2":"熊灵","3":"Spirit Bear","4":"Spirit Bear","5":"Spirit Bear"}',
                'game_code' => 'GS38_3400',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '3400',
                'english_name' => 'Spirit Bear',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"The Mythical Unicorn","2":"麒麟传奇","3":"The Mythical Unicorn","4":"The Mythical Unicorn","5":"The Mythical Unicorn"}',
                'game_code' => 'GS37_3300',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '3300',
                'english_name' => 'The Mythical Unicorn',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Guardians of Flower","2":"百花天使","3":"Guardians of Flower","4":"Guardians of Flower","5":"Guardians of Flower"}',
                'game_code' => 'GS36_3200',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '3200',
                'english_name' => 'Guardians of Flower',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"The Sacred Elements","2":"玛雅五行传","3":"The Sacred Elements","4":"The Sacred Elements","5":"The Sacred Elements"}',
                'game_code' => 'GS35_3100',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '3100',
                'english_name' => 'The Sacred Elements',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Great Abundance","2":"財源滾滾 ","3":"Great Abundance","4":"Great Abundance","5":"Great Abundance"}',
                'game_code' => 'GS34_3000',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '3000',
                'english_name' => 'Great Abundance',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Legend of the White Snake","2":"白蛇传","3":"Legend of the White Snake","4":"Legend of the White Snake","5":"Legend of the White Snake"}',
                'game_code' => 'GS33_2900',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '2900',
                'english_name' => 'Legend of the White Snake',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"3x Dragon Supreme","2":"3x神龙至尊","3":"3x Dragon Supreme","4":"3x Dragon Supreme","5":"3x Dragon Supreme"}',
                'game_code' => 'GS32_2800',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '2800',
                'english_name' => '3x Dragon Supreme',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Black and White","2":"黑与白","3":"Black and White","4":"Black and White","5":"Black and White"}',
                'game_code' => 'GS31_2700',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '2700',
                'english_name' => 'Black and White',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Justice Bao","2":"包大人","3":"Justice Bao","4":"Justice Bao","5":"Justice Bao"}',
                'game_code' => 'GS30_2600',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '2600',
                'english_name' => 'Justice Bao',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Southern Fortune Lion","2":"福狮高照","3":"Southern Fortune Lion","4":"Southern Fortune Lion","5":"Southern Fortune Lion"}',
                'game_code' => 'GS29_2500',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '2500',
                'english_name' => 'Southern Fortune Lion',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Panthera Pardus","2":"金钱豹","3":"Panthera Pardus","4":"Panthera Pardus","5":"Panthera Pardus"}',
                'game_code' => 'GS28_2400',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '2400',
                'english_name' => 'Panthera Pardus',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Treasures In Varna","2":"瓦尔纳珍宝","3":"Treasures In Varna","4":"Treasures In Varna","5":"Treasures In Varna"}',
                'game_code' => 'GS27_2300',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '2300',
                'english_name' => 'Treasures In Varna',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Paris of the East","2":"东方巴黎","3":"Paris of the East","4":"Paris of the East","5":"Paris of the East"}',
                'game_code' => 'GS26_2200',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '2200',
                'english_name' => 'Paris of the East',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Pig Of Fury","2":"猪武门","3":"Pig Of Fury","4":"Pig Of Fury","5":"Pig Of Fury"}',
                'game_code' => 'GS25_2100',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '2100',
                'english_name' => 'Pig Of Fury',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Resurrection of Dragons","2":"神龙再世","3":"Resurrection of Dragons","4":"Resurrection of Dragons","5":"Resurrection of Dragons"}',
                'game_code' => 'GS24_2000',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '2000',
                'english_name' => 'Resurrection of Dragons',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Rhino Crash","2":"犀牛之怒","3":"Rhino Crash","4":"Rhino Crash","5":"Rhino Crash"}',
                'game_code' => 'GS23_1900',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '1900',
                'english_name' => 'Rhino Crash',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Gummy Wonderland","2":"梦幻糖果屋","3":"Gummy Wonderland","4":"Gummy Wonderland","5":"Gummy Wonderland"}',
                'game_code' => 'GS22_1800',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '1800',
                'english_name' => 'Gummy Wonderland',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Golden Harvest","2":"大丰收","3":"Golden Harvest","4":"Golden Harvest","5":"Golden Harvest"}',
                'game_code' => 'GS21_1700',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '1700',
                'english_name' => 'Golden Harvest',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Imperial Chaise","2":"皇贵妃","3":"Imperial Chaise","4":"Imperial Chaise","5":"Imperial Chaise"}',
                'game_code' => 'GS20_1600',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '1600',
                'english_name' => 'Imperial Chaise',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Fairy Moon Goddess","2":"月娘传奇","3":"Fairy Moon Goddess","4":"Fairy Moon Goddess","5":"Fairy Moon Goddess"}',
                'game_code' => 'GS19_1500',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '1500',
                'english_name' => 'Fairy Moon Goddess',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Wilds Of Africa","2":"狂野非洲","3":"Wilds Of Africa","4":"Wilds Of Africa","5":"Wilds Of Africa"}',
                'game_code' => 'GS18_1400',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '1400',
                'english_name' => 'Wilds Of Africa',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Tank Attack","2":"进击的坦克","3":"Tank Attack","4":"Tank Attack","5":"Tank Attack"}',
                'game_code' => 'GS17_1300',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '1300',
                'english_name' => 'Tank Attack',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Ocean Trouble","2":"海洋危机","3":"Ocean Trouble","4":"Ocean Trouble","5":"Ocean Trouble"}',
                'game_code' => 'GS16_1200',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '1200',
                'english_name' => 'Ocean Trouble',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Phantom Island","2":"幽灵幻岛","3":"Phantom Island","4":"Phantom Island","5":"Phantom Island"}',
                'game_code' => 'GS15_1100',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '1100',
                'english_name' => 'Phantom Island',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Evil King OX","2":"牛魔王","3":"Evil King OX","4":"Evil King OX","5":"Evil King OX"}',
                'game_code' => 'GS14_1000',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '1000',
                'english_name' => 'Evil King OX',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Samurai Heroes","2":"武士英雄","3":"Samurai Heroes","4":"Samurai Heroes","5":"Samurai Heroes"}',
                'game_code' => 'GS13_900',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '900',
                'english_name' => 'Samurai Heroes',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Lucky Fortune","2":"迎财神","3":"Lucky Fortune","4":"Lucky Fortune","5":"Lucky Fortune"}',
                'game_code' => 'GS12_800',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '800',
                'english_name' => 'Lucky Fortune',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"The Lost Gems","2":"失落的宝石","3":"The Lost Gems","4":"The Lost Gems","5":"The Lost Gems"}',
                'game_code' => 'GS10_700',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '700',
                'english_name' => 'The Lost Gems',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Fu Lai","2":"福来","3":"Fu Lai","4":"Fu Lai","5":"Fu Lai"}',
                'game_code' => 'GS9_600',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '600',
                'english_name' => 'Fu Lai',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Zeus D\'Mighty","2":"宙斯神威","3":"Zeus D\'Mighty","4":"Zeus D\'Mighty","5":"Zeus D\'Mighty"}',
                'game_code' => 'GS8_500',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '500',
                'english_name' => 'Zeus D\'Mighty',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Jingle Winnings","2":"圣诞叮铃","3":"Jingle Winnings","4":"Jingle Winnings","5":"Jingle Winnings"}',
                'game_code' => 'GS6_400',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '400',
                'english_name' => 'Jingle Winnings',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"3 Tigers","2":"三虎雄威","3":"3 Tigers","4":"3 Tigers","5":"3 Tigers"}',
                'game_code' => 'GS5_304',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '304',
                'english_name' => '3 Tigers',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Phantom Cash","2":"尸金魅影","3":"Phantom Cash","4":"Phantom Cash","5":"Phantom Cash"}',
                'game_code' => 'GS5_303',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '303',
                'english_name' => 'Phantom Cash',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Go Bananas","2":"冲刺吧！香蕉","3":"Go Bananas","4":"Go Bananas","5":"Go Bananas"}',
                'game_code' => 'GS5_300',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '300',
                'english_name' => 'Go Bananas',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Tornado Farm Escape","2":"飓风: 农场大逃脱","3":"Tornado Farm Escape","4":"Tornado Farm Escape","5":"Tornado Farm Escape"}',
                'game_code' => 'GS5_301',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '301',
                'english_name' => 'Tornado Farm Escape',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Shoot","2":"热血大射门","3":"Shoot","4":"Shoot","5":"Shoot"}',
                'game_code' => 'GS5_302',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '302',
                'english_name' => 'Shoot',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Chinese New Year","2":"春喜临门","3":"Chinese New Year","4":"Chinese New Year","5":"Chinese New Year"}',
                'game_code' => 'GS4_200',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '200',
                'english_name' => 'Chinese New Year',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Lucky Angler","2":"幸运垂钓者","3":"Lucky Angler","4":"Lucky Angler","5":"Lucky Angler"}',
                'game_code' => 'GS4_201',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '201',
                'english_name' => 'Lucky Angler',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Santa’s Surprise","2":"圣诞老人的惊喜","3":"Santa’s Surprise","4":"Santa’s Surprise","5":"Santa’s Surprise"}',
                'game_code' => 'GS3_100',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '100',
                'english_name' => 'Santa’s Surprise',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Georgie Porgie","2":"乔治与珀治","3":"Georgie Porgie","4":"Georgie Porgie","5":"Georgie Porgie"}',
                'game_code' => 'GS3_101',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '101',
                'english_name' => 'Georgie Porgie',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Jack and Jill","2":"杰克和吉尔","3":"Jack and Jill","4":"Jack and Jill","5":"Jack and Jill"}',
                'game_code' => 'GS3_102',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '102',
                'english_name' => 'Jack and Jill',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Wild Birthday Blast","2":"动物派对","3":"Wild Birthday Blast","4":"Wild Birthday Blast","5":"Wild Birthday Blast"}',
                'game_code' => 'GS3_103',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '103',
                'english_name' => 'Wild Birthday Blast',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Karate Pig","2":"功夫小胖猪","3":"Karate Pig","4":"Karate Pig","5":"Karate Pig"}',
                'game_code' => 'GS3_104',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '104',
                'english_name' => 'Karate Pig',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Throne of Egypt","2":"埃及王朝","3":"Throne of Egypt","4":"Throne of Egypt","5":"Throne of Egypt"}',
                'game_code' => 'GS3_105',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '105',
                'english_name' => 'Throne of Egypt',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Dolphin Quest","2":"寻访海豚","3":"Dolphin Quest","4":"Dolphin Quest","5":"Dolphin Quest"}',
                'game_code' => 'GS3_106',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '106',
                'english_name' => 'Dolphin Quest',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Fish Party","2":"海底派对","3":"Fish Party","4":"Fish Party","5":"Fish Party"}',
                'game_code' => 'GS3_107',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '107',
                'english_name' => 'Fish Party',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Wild Turkey","2":"野生火鸡","3":"Wild Turkey","4":"Wild Turkey","5":"Wild Turkey"}',
                'game_code' => 'GS1_0',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '0',
                'english_name' => 'Wild Turkey',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Jungle Games","2":"森林游戏","3":"Jungle Games","4":"Jungle Games","5":"Jungle Games"}',
                'game_code' => 'GS1_1',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '1',
                'english_name' => 'Jungle Games',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Subtopia","2":"深海潜艇","3":"Subtopia","4":"Subtopia","5":"Subtopia"}',
                'game_code' => 'GS1_2',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '2',
                'english_name' => 'Subtopia',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Fisticuffs","2":"互殴","3":"Fisticuffs","4":"Fisticuffs","5":"Fisticuffs"}',
                'game_code' => 'GS1_3',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '3',
                'english_name' => 'Fisticuffs',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"SouthPark","2":"南方公园","3":"SouthPark","4":"SouthPark","5":"SouthPark"}',
                'game_code' => 'GS1_4',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '4',
                'english_name' => 'SouthPark',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Trolls","2":"洞穴巨人","3":"Trolls","4":"Trolls","5":"Trolls"}',
                'game_code' => 'GS1_5',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '5',
                'english_name' => 'Trolls',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Egyptian Heroes","2":"埃及英雄","3":"Egyptian Heroes","4":"Egyptian Heroes","5":"Egyptian Heroes"}',
                'game_code' => 'GS1_6',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '6',
                'english_name' => 'Egyptian Heroes',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Flowers","2":"百花齐放","3":"Flowers","4":"Flowers","5":"Flowers"}',
                'game_code' => 'GS1_7',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => '7',
                'english_name' => 'Flowers',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Sic Bo","2":"骰宝","3":"Sic Bo","4":"Sic Bo","5":"Sic Bo"}',
                'game_code' => 'GS2_SicBo',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => 'SicBo',
                'english_name' => 'Sic Bo',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_table_and_cards_game],
            ],
            [
                'game_name' => '_json:{"1":"Roulette","2":"轮盘","3":"Roulette","4":"Roulette","5":"Roulette"}',
                'game_code' => 'GS2_Roulette',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => 'Roulette',
                'english_name' => 'Roulette',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_table_and_cards_game],
            ],
            [
                'game_name' => '_json:{"1":"Baccarat","2":"百家乐","3":"Baccarat","4":"Baccarat","5":"Baccarat"}',
                'game_code' => 'GS2_Baccarat',
                'html_five_enabled' => $db_false,
                'game_platform_id' => $api_id,
                'external_game_id' => 'Baccarat',
                'english_name' => 'Baccarat',
                'flash_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_table_and_cards_game],
            ],
            [
                'game_name' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                'game_code' => 'unknown',
                'game_platform_id' => $api_id,
                'external_game_id' => 'unknown',
                'english_name' => 'Unknown',
                'status' => $db_true,
                'flag_show_in_site' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_unknown],
            ],

        ];
        // $this->load->model(['game_description_model']);

        // $success=$this->game_description_model->syncGameDescription($game_descriptions);

        $cntInsert = 0;
        $cntupdate = 0;

        foreach ($game_descriptions as $game_list) {

            $game_list['game_platform_id'] = $api_id;

            $game_code_exist = $this->db->select('COUNT(id) as count')
                                ->where('game_code', $game_list['game_code'])
                                ->where('game_platform_id', $api_id)
                                ->get('game_description')
                                ->row();

            if( $game_code_exist->count <= 0 ){
                echo "==============================================>Insert<===========================================";
                $game_list['created_on']= $now;
                $this->db->insert('game_description', $game_list);
                $cntInsert++;
            }else{
                echo "==============================================>Update<===========================================";
                $game_list['updated_at']= $now;
                $this->db->where('game_code', $game_list['game_code']);
                $this->db->where('game_platform_id', $api_id);
                $this->db->update('game_description', $game_list);
                $cntupdate++;
            }
            echo "<pre>";
            print_r($game_list);

        }
        echo "Total Inserted Games:" . $cntInsert;echo "<br>";
        echo "Total Updated Games:" . $cntupdate;

        // return $success;
    }

}
