<?php
trait game_description_tianhao {

    public function sync_game_description_tianhao(){
        $cnt=0;
        $cntInsert = 0;
        $cntUpdate = 0;

        $db_true = 1;
        $db_false = 0;
        $api_id = TIANHAO_API;
        $now = $this->utils->getNowForMysql();

        $game_type_code_default = SYNC::TAG_CODE_TABLE_GAMES;
        $game_type_code_unknown = SYNC::TAG_CODE_UNKNOWN_GAME;

        // sync game type first
        // use game_type_code as key
        $game_types = [
            $game_type_code_default => [
                'game_platform_id'     => $api_id,
                'game_type'            => '_json:{"1":"Tianhao Chess","2":"天豪棋牌","3":"Tianhao Chess","4":"Tianhao Chess","5":"Tianhao Chess"}',
                'game_type_lang'       => '_json:{"1":"Tianhao Chess","2":"天豪棋牌","3":"Tianhao Chess","4":"Tianhao Chess","5":"Tianhao Chess"}',
                'game_type_code'       => $game_type_code_default,
                'game_tag_code'        => $game_type_code_default,
            ],
            $game_type_code_unknown => [
                'game_platform_id'     => $api_id,
                'game_type'            => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                'game_type_lang'       => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                "game_type_code"       => $game_type_code_unknown,
                "game_tag_code"        => $game_type_code_unknown,
            ],

        ];

        $this->load->model(['game_type_model']);
        $gameTypeCodeMaps=$this->game_type_model->syncGameTypes($game_types);
        $this->utils->debug_log('gameTypeCodeMaps', $gameTypeCodeMaps);

        $game_descriptions = array(
            [
                'game_name'         => '_json:{"1":"港式五张","2":"港式五张"}',
                'game_code'         => '1001',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1001',
                'english_name'      => '港式五张',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"赢三张","2":"赢三张"}',
                'game_code'         => '1002',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1002',
                'english_name'      => '赢三张',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"生肖转转","2":"生肖转转"}',
                'game_code'         => '1003',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1003',
                'english_name'      => '生肖转转',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"碰碰车","2":"碰碰车"}',
                'game_code'         => '1004',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1004',
                'english_name'      => '碰碰车',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"刮刮看","2":"刮刮看"}',
                'game_code'         => '1005',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1005',
                'english_name'      => '刮刮看',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"斗地主","2":"斗地主"}',
                'game_code'         => '1006',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1006',
                'english_name'      => '斗地主',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"千变双扣","2":"千变双扣"}',
                'game_code'         => '1007',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1007',
                'english_name'      => '千变双扣',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"乐清麻将","2":"乐清麻将"}',
                'game_code'         => '1008',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1008',
                'english_name'      => '乐清麻将',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"牛牛","2":"牛牛"}',
                'game_code'         => '1009',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1009',
                'english_name'      => '牛牛',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"十三张","2":"十三张"}',
                'game_code'         => '1010',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1010',
                'english_name'      => '十三张',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"老虎鸡","2":"老虎鸡"}',
                'game_code'         => '1011',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1011',
                'english_name'      => '老虎鸡',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"翻翻看","2":"翻翻看"}',
                'game_code'         => '1012',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1012',
                'english_name'      => '翻翻看',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"新两张","2":"新两张"}',
                'game_code'         => '1013',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1013',
                'english_name'      => '新两张',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"火拼双扣","2":"火拼双扣"}',
                'game_code'         => '1014',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1014',
                'english_name'      => '火拼双扣',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"百变牛牛","2":"百变牛牛"}',
                'game_code'         => '1015',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1015',
                'english_name'      => '百变牛牛',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"火拼麻将","2":"火拼麻将"}',
                'game_code'         => '1016',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1016',
                'english_name'      => '火拼麻将',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"火拼斗地主","2":"火拼斗地主"}',
                'game_code'         => '1017',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1017',
                'english_name'      => '火拼斗地主',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"德州扑克","2":"德州扑克"}',
                'game_code'         => '1018',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1018',
                'english_name'      => '德州扑克',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"飞行棋","2":"飞行棋"}',
                'game_code'         => '1019',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1019',
                'english_name'      => '飞行棋',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"中国象棋","2":"中国象棋"}',
                'game_code'         => '1020',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1020',
                'english_name'      => '中国象棋',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"二人麻将","2":"二人麻将"}',
                'game_code'         => '1021',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1021',
                'english_name'      => '二人麻将',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"二人牛牛","2":"二人牛牛"}',
                'game_code'         => '1022',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1022',
                'english_name'      => '二人牛牛',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"大话骰","2":"大话骰"}',
                'game_code'         => '1023',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1023',
                'english_name'      => '大话骰',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"捕鱼","2":"捕鱼"}',
                'game_code'         => '1024',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1024',
                'english_name'      => '捕鱼',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"超级牛牛","2":"超级牛牛"}',
                'game_code'         => '1025',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1025',
                'english_name'      => '超级牛牛',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"新二人麻将","2":"新二人麻将"}',
                'game_code'         => '1026',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1026',
                'english_name'      => '新二人麻将',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"百人两张","2":"百人两张"}',
                'game_code'         => '1027',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1027',
                'english_name'      => '百人两张',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"新十三张","2":"新十三张"}',
                'game_code'         => '1028',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1028',
                'english_name'      => '新十三张',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"30秒","2":"30秒"}',
                'game_code'         => '1029',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1029',
                'english_name'      => '30秒',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"生肖转盘","2":"生肖转盘"}',
                'game_code'         => '1030',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1030',
                'english_name'      => '生肖转盘',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"斗牛","2":"斗牛"}',
                'game_code'         => '1031',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1031',
                'english_name'      => '斗牛',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"掼蛋","2":"掼蛋"}',
                'game_code'         => '1032',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1032',
                'english_name'      => '掼蛋',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"金蝉捕鱼","2":"金蝉捕鱼"}',
                'game_code'         => '1033',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1033',
                'english_name'      => '金蝉捕鱼',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"二人对战牛牛","2":"二人对战牛牛"}',
                'game_code'         => '1034',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1034',
                'english_name'      => '二人对战牛牛',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"拍拍乐","2":"拍拍乐"}',
                'game_code'         => '1035',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1035',
                'english_name'      => '拍拍乐',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"通比牛牛","2":"通比牛牛"}',
                'game_code'         => '1036',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1036',
                'english_name'      => '通比牛牛',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"激情牛牛","2":"激情牛牛"}',
                'game_code'         => '1037',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1037',
                'english_name'      => '激情牛牛',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"火拼两张","2":"火拼两张"}',
                'game_code'         => '1038',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1038',
                'english_name'      => '火拼两张',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"大圣捕鱼","2":"大圣捕鱼"}',
                'game_code'         => '1039',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1039',
                'english_name'      => '大圣捕鱼',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"车马炮","2":"车马炮"}',
                'game_code'         => '1040',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1040',
                'english_name'      => '车马炮',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"专业德州","2":"专业德州"}',
                'game_code'         => '1041',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1041',
                'english_name'      => '专业德州',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"四人牛牛","2":"四人牛牛"}',
                'game_code'         => '1042',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1042',
                'english_name'      => '四人牛牛',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"二人五张","2":"二人五张"}',
                'game_code'         => '1043',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1043',
                'english_name'      => '二人五张',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"富锦麻将","2":"富锦麻将"}',
                'game_code'         => '1044',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1044',
                'english_name'      => '富锦麻将',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"虎虎生威","2":"虎虎生威"}',
                'game_code'         => '1045',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1045',
                'english_name'      => '虎虎生威',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"李逵劈鱼","2":"李逵劈鱼"}',
                'game_code'         => '1046',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1046',
                'english_name'      => '李逵劈鱼',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"龙虎斗","2":"龙虎斗"}',
                'game_code'         => '1047',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1047',
                'english_name'      => '龙虎斗',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"天地至尊","2":"天地至尊"}',
                'game_code'         => '1048',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1048',
                'english_name'      => '天地至尊',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"哪吒闹海","2":"哪吒闹海"}',
                'game_code'         => '1049',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1049',
                'english_name'      => '哪吒闹海',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"二人梭哈","2":"二人梭哈"}',
                'game_code'         => '1050',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1050',
                'english_name'      => '二人梭哈',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"明星斗牛","2":"明星斗牛"}',
                'game_code'         => '1051',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1051',
                'english_name'      => '明星斗牛',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"水浒传","2":"水浒传"}',
                'game_code'         => '1052',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1052',
                'english_name'      => '水浒传',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"小九","2":"小九"}',
                'game_code'         => '1053',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1053',
                'english_name'      => '小九',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"真人百家乐","2":"真人百家乐"}',
                'game_code'         => '1054',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1054',
                'english_name'      => '真人百家乐',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"看牌牛牛","2":"看牌牛牛"}',
                'game_code'         => '1055',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1055',
                'english_name'      => '看牌牛牛',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"百倍对战牛牛","2":"百倍对战牛牛"}',
                'game_code'         => '1056',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1056',
                'english_name'      => '百倍对战牛牛',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"龙虎30秒","2":"龙虎30秒"}',
                'game_code'         => '1057',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1057',
                'english_name'      => '龙虎30秒',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"龙虎30秒16人","2":"龙虎30秒16人"}',
                'game_code'         => '1058',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1058',
                'english_name'      => '龙虎30秒16人',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"16人小九","2":"16人小九"}',
                'game_code'         => '1059',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1059',
                'english_name'      => '16人小九',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"飞腾五张大奖赛","2":"飞腾五张大奖赛"}',
                'game_code'         => '1060',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1060',
                'english_name'      => '飞腾五张大奖赛',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"飞腾五张周日赛","2":"飞腾五张周日赛"}',
                'game_code'         => '1061',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1061',
                'english_name'      => '飞腾五张周日赛',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"通比五张","2":"通比五张"}',
                'game_code'         => '1062',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1062',
                'english_name'      => '通比五张',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"通比骰王","2":"通比骰王"}',
                'game_code'         => '1063',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1063',
                'english_name'      => '通比骰王',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"通比捕鱼","2":"通比捕鱼"}',
                'game_code'         => '1064',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1064',
                'english_name'      => '通比捕鱼',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"四人拼十比赛","2":"四人拼十比赛"}',
                'game_code'         => '1065',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1065',
                'english_name'      => '四人拼十比赛',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"转账房间","2":"转账房间"}',
                'game_code'         => '1066',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1066',
                'english_name'      => '转账房间',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"超级疯狂捕鱼","2":"超级疯狂捕鱼"}',
                'game_code'         => '1067',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1067',
                'english_name'      => '超级疯狂捕鱼',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"心跳牛牛","2":"心跳牛牛"}',
                'game_code'         => '1069',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1069',
                'english_name'      => '心跳牛牛',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"二人斗地主","2":"二人斗地主"}',
                'game_code'         => '1070',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1070',
                'english_name'      => '二人斗地主',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"飞腾牛神","2":"飞腾牛神"}',
                'game_code'         => '1071',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1071',
                'english_name'      => '飞腾牛神',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"会员牛场","2":"会员牛场"}',
                'game_code'         => '1075',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1075',
                'english_name'      => '会员牛场',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"极速豪车","2":"极速豪车"}',
                'game_code'         => '1077',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1077',
                'english_name'      => '极速豪车',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"新水浒后传","2":"新水浒后传"}',
                'game_code'         => '1078',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1078',
                'english_name'      => '新水浒后传',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"快速七张麻将","2":"快速七张麻将"}',
                'game_code'         => '1080',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1080',
                'english_name'      => '快速七张麻将',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"四川麻将血流成河","2":"四川麻将血流成河"}',
                'game_code'         => '1081',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1081',
                'english_name'      => '四川麻将血流成河',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"四川麻将血战到底","2":"四川麻将血战到底"}',
                'game_code'         => '1082',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1082',
                'english_name'      => '四川麻将血战到底',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"通比斗三张","2":"通比斗三张"}',
                'game_code'         => '1091',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1091',
                'english_name'      => '通比斗三张',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"16人通比斗三张","2":"16人通比斗三张"}',
                'game_code'         => '1092',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1092',
                'english_name'      => '16人通比斗三张',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"将相和","2":"将相和"}',
                'game_code'         => '1093',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1093',
                'english_name'      => '将相和',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"大闹天宫","2":"大闹天宫"}',
                'game_code'         => '1096',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1096',
                'english_name'      => '大闹天宫',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"四人五张","2":"四人五张"}',
                'game_code'         => '1097',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1097',
                'english_name'      => '四人五张',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"决战牛牛","2":"决战牛牛"}',
                'game_code'         => '1098',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1098',
                'english_name'      => '决战牛牛',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"3D斗地主","2":"3D斗地主"}',
                'game_code'         => '1099',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1099',
                'english_name'      => '3D斗地主',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"老虎机","2":"老虎机"}',
                'game_code'         => '1101',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1101',
                'english_name'      => '老虎机',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"大闹天宫二之牛魔王篇","2":"大闹天宫二之牛魔王篇"}',
                'game_code'         => '1102',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1102',
                'english_name'      => '大闹天宫二之牛魔王篇',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"疯狂捕鱼2D","2":"疯狂捕鱼2D"}',
                'game_code'         => '1105',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1105',
                'english_name'      => '疯狂捕鱼2D',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"大闹天宫牛魔王篇2","2":"大闹天宫牛魔王篇2"}',
                'game_code'         => '1108',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1108',
                'english_name'      => '大闹天宫牛魔王篇2',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"21点","2":"21点"}',
                'game_code'         => '1121',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1121',
                'english_name'      => '21点',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"一元夺宝","2":"一元夺宝"}',
                'game_code'         => '1200',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1200',
                'english_name'      => '一元夺宝',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"百人跑马","2":"百人跑马"}',
                'game_code'         => '1301',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1301',
                'english_name'      => '百人跑马',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"包房四人牛牛","2":"包房四人牛牛"}',
                'game_code'         => '1400',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1400',
                'english_name'      => '包房四人牛牛',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"包房二人对战牛牛","2":"包房二人对战牛牛"}',
                'game_code'         => '1401',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1401',
                'english_name'      => '包房二人对战牛牛',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"包房通比牛牛","2":"包房通比牛牛"}',
                'game_code'         => '1402',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1402',
                'english_name'      => '包房通比牛牛',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"包房16人通比斗三张","2":"包房16人通比斗三张"}',
                'game_code'         => '1403',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1403',
                'english_name'      => '包房16人通比斗三张',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"血流成河包房 ","2":"血流成河包房 "}',
                'game_code'         => '1405',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1405',
                'english_name'      => '血流成河包房 ',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"血战到底包房","2":"血战到底包房"}',
                'game_code'         => '1404',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1404',
                'english_name'      => '血战到底包房',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"包房快7麻将","2":"包房快7麻将"}',
                'game_code'         => '1406',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1406',
                'english_name'      => '包房快7麻将',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"包房四人五张","2":"包房四人五张"}',
                'game_code'         => '1408',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1408',
                'english_name'      => '包房四人五张',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"包房斗地主","2":"包房斗地主"}',
                'game_code'         => '1409',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1409',
                'english_name'      => '包房斗地主',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"包房千变双扣","2":"包房千变双扣"}',
                'game_code'         => '1410',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1410',
                'english_name'      => '包房千变双扣',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"包房德州扑克","2":"包房德州扑克"}',
                'game_code'         => '1419',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1419',
                'english_name'      => '包房德州扑克',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"疯狂通比斗牛","2":"疯狂通比斗牛"}',
                'game_code'         => '1609',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1609',
                'english_name'      => '疯狂通比斗牛',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name'         => '_json:{"1":"二八杠","2":"二八杠"}',
                'game_code'         => '1741',
                'game_platform_id'  => $api_id,
                'external_game_id'  => '1741',
                'english_name'      => '二八杠',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_default],
                'mobile_enabled' => $db_true,
                'enabled_on_ios' => $db_true,
                'enabled_on_android' => $db_true,
            ],
            [
                'game_name' => '_json:{"1":"unknown","2":"不明","3":"unknown","4":"unknown","5":"unknown"}',
                'game_code' => 'unknown',
                'game_platform_id' => $api_id,
                'external_game_id' => 'unknown',
                'english_name' => 'unknown',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_unknown],
            ],
        );

        $this->load->model(['game_description_model']);

        $success=$this->game_description_model->syncGameDescription($game_descriptions);

        return $success;
    }

}
