<?php
trait game_description_jumb {

    public function sync_game_description_jumb_t1(){
        $api_id = T1JUMB_API;
        $this->jumb_game_list($api_id);
    }

    public function sync_game_description_jumb(){
        $api_id = JUMB_GAMING_API;
        $this->jumb_game_list($api_id);
    }

    public function jumb_game_list($api_id){
        $cnt=0;
        $db_true = 1;
        $db_false = 0;
        $now = $this->utils->getNowForMysql();

        $game_type_code_slots = SYNC::TAG_CODE_SLOT;
        $game_type_code_unknown = SYNC::TAG_CODE_UNKNOWN_GAME;
        $game_type_code_fishing_game = SYNC::TAG_CODE_FISHING_GAME;
        $game_type_code_lottery = SYNC::TAG_CODE_LOTTERY;
        $game_type_code_arcade = SYNC::TAG_CODE_ARCADE;

        $game_types = [
            $game_type_code_slots => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Slot Game","2":"老虎機","3":"Slot Game","4":"Slot Game","5":"Slot Game"}',
                'game_type_lang' => '_json:{"1":"Slot Game","2":"老虎機","3":"Slot Game","4":"Slot Game","5":"Slot Game"}',
                'game_type_code' => $game_type_code_slots,
                'updated_at' => $now,
                'game_tag_code' => $game_type_code_slots,
            ],
            $game_type_code_fishing_game => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Fishing Game","2":"捕鱼王","3":"Fishing Game","4":"Fishing Game","5":"Fishing Game"}',
                'game_type_lang' => '_json:{"1":"Fishing Game","2":"捕鱼王","3":"Fishing Game","4":"Fishing Game","5":"Fishing Game"}',
                'game_type_code' => $game_type_code_fishing_game,
                'updated_at' => $now,
                'game_tag_code' => $game_type_code_fishing_game,
            ],
            // $game_type_code_others => [
            //     'game_platform_id' => $api_id,
            //     'game_type' => '_json:{"1":"Others","2":"骰宝","3":"Others","4":"Others"}',
            //     'game_type_lang' => '_json:{"1":"Others","2":"骰宝","3":"Others","4":"Others"}',
            //     "game_type_code" => $game_type_code_others,
            //     'updated_at'=>$now,
            //     "game_tag_code" => $game_type_code_others,
            // ],
            $game_type_code_arcade => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Arcade","2":"街机游戏","3":"Arcade","4":"Arcade","5":"Arcade"}',
                'game_type_lang' => '_json:{"1":"Arcade","2":"街机游戏","3":"Arcade","4":"Arcade","5":"Arcade"}',
                "game_type_code" => $game_type_code_arcade,
                'updated_at'=> $now,
                "game_tag_code" => $game_type_code_arcade,
            ],

            $game_type_code_lottery => [
                 'game_platform_id' => $api_id,
                 'game_type' => '_json:{"1":"Lottery","2":"彩票游戏","3":"Lottery","4":"Lottery"}',
                 'game_type_lang' => '_json:{"1":"Lottery","2":"彩票游戏","3":"Lottery","4":"Lottery"}',
                 "game_type_code" => $game_type_code_lottery,
                 'updated_at'=>$now,
                 'game_tag_code' => $game_type_code_lottery
            ],

            $game_type_code_unknown => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                'game_type_lang' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                "game_type_code" => $game_type_code_unknown,
                'updated_at'=>$now,
                'game_tag_code' => $game_type_code_unknown,
            ],
        ];


        $this->load->model(['game_type_model']);
        $gameTypeCodeMaps=$this->game_type_model->syncGameTypes($game_types);
        // echo "<pre>";
        // print_r($gameTypeCodeMaps);
        // die();
        $this->utils->debug_log('gameTypeCodeMaps', $gameTypeCodeMaps);

        $game_descriptions = array(
            # ================================================================ Jumb Game list ============================================================
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_unknown],
                'game_name' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                'game_code' => 'unknown',
                'dlc_enabled' => $db_true,
                'mobile_enabled' => $db_true,
                'flag_show_in_site' => $db_false,
                'english_name' => 'Unknown',
                'external_game_id' => 'unknown',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_arcade],
                'game_name' => '_json:{"1":"Classic Mario","2":"小玛莉","3":"Classic Mario","4":"Classic Mario","5":"Classic Mario"}',
                'game_code' => '9001',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Classic Mario',
                'external_game_id' => '9001',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_arcade],
                'game_name' => '_json:{"1":"Happy New Year","2":"新年快乐","3":"Happy New Year","4":"Happy New Year","5":"Happy New Year"}',
                'game_code' => '9002',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Happy New Year',
                'external_game_id' => '9002',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_arcade],
                'game_name' => '_json:{"1":"Birds and Animals","2":"飞禽走兽","3":"Birds and Animals","4":"Birds and Animals","5":"Birds and Animals"}',
                'game_code' => '9003',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Birds and Animals',
                'external_game_id' => '9003',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_arcade],
                'game_name' => '_json:{"1":"Beer Tycoon","2":"啤酒大亨","3":"Beer Tycoon","4":"Beer Tycoon","5":"Beer Tycoon"}',
                'game_code' => '9004',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Beer Tycoon',
                'external_game_id' => '9004',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_arcade],
                'game_name' => '_json:{"1":"Huaguoshan Legends","2":"花果山传奇","3":"Huaguoshan Legends","4":"Huaguoshan Legends","5":"Huaguoshan Legends"}',
                'game_code' => '9006',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Huaguoshan Legends',
                'external_game_id' => '9006',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_arcade],
                'game_name' => '_json:{"1":"Super Super Fruit","2":"超激发水果盘","3":"Super Super Fruit","4":"Super Super Fruit","5":"Super Super Fruit"}',
                'game_code' => '9007',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Super Super Fruit',
                'external_game_id' => '9007',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_fishing_game],
                'game_name' => '_json:{"1":"Dragon Fishing","2":"龙王捕鱼","3":"Dragon Fishing","4":"Dragon Fishing","5":"Dragon Fishing"}',
                'game_code' => '7001',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Dragon Fishing',
                'external_game_id' => '7001',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_fishing_game],
                'game_name' => '_json:{"1":"Dragon Fishing II","2":"龙王捕鱼2","3":"Dragon Fishing II","4":"Dragon Fishing II","5":"Dragon Fishing II"}',
                'game_code' => '7002',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Dragon Fishing II',
                'external_game_id' => '7002',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_fishing_game],
                'game_name' => '_json:{"1":"Cai Shen Fishing","2":"财神捕鱼","3":"Cai Shen Fishing","4":"Cai Shen Fishing","5":"Cai Shen Fishing"}',
                'game_code' => '7003',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Cai Shen Fishing',
                'external_game_id' => '7003',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Lucky Dragon","2":"幸运龙","3":"Lucky Dragon","4":"Lucky Dragon","5":"Lucky Dragon"}',
                'game_code' => '8001',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Lucky Dragon',
                'external_game_id' => '8001',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Flirting Scholar Tang","2":"唐伯虎点秋香","3":"Flirting Scholar Tang","4":"Flirting Scholar Tang","5":"Flirting Scholar Tang"}',
                'game_code' => '8002',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Flirting Scholar Tang',
                'external_game_id' => '8002',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Winning Mask","2":"变脸","3":"Winning Mask","4":"Winning Mask","5":"Winning Mask"}',
                'game_code' => '8003',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Winning Mask',
                'external_game_id' => '8003',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Wukong","2":"悟空","3":"Wukong","4":"Wukong","5":"Wukong"}',
                'game_code' => '8004',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Wukong',
                'external_game_id' => '8004',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Llama Adventure","2":"骆马大冒险","3":"Llama Adventure","4":"Llama Adventure","5":"Llama Adventure"}',
                'game_code' => '8005',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Llama Adventure',
                'external_game_id' => '8005',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Formosa Bear","2":"台湾黑熊","3":"Formosa Bear","4":"Formosa Bear","5":"Formosa Bear"}',
                'game_code' => '8006',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Formosa Bear',
                'external_game_id' => '8006',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Lucky Qilin","2":"幸运麟","3":"Lucky Qilin","4":"Lucky Qilin","5":"Lucky Qilin"}',
                'game_code' => '8007',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Lucky Qilin',
                'external_game_id' => '8007',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Lucky Lion","2":"招财狮","3":"Lucky Lion","4":"Lucky Lion","5":"Lucky Lion"}',
                'game_code' => '8014',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Lucky Lion',
                'external_game_id' => '8014',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Moonlight Treasure","2":"月光秘宝","3":"Moonlight Treasure","4":"Moonlight Treasure","5":"Moonlight Treasure"}',
                'game_code' => '8015',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Moonlight Treasure',
                'external_game_id' => '8015',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Coffeeholics","2":"上班族狂想曲","3":"Coffeeholics","4":"Coffeeholics","5":"Coffeeholics"}',
                'game_code' => '8016',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Coffeeholics',
                'external_game_id' => '8016',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"New Year","2":"过新年","3":"New Year","4":"New Year","5":"New Year"}',
                'game_code' => '8017',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'New Year',
                'external_game_id' => '8017',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Napoleon","2":"拿破仑","3":"Napoleon","4":"Napoleon","5":"Napoleon"}',
                'game_code' => '8018',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Napoleon',
                'external_game_id' => '8018',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Four Treasures","2":"文房四宝","3":"Four Treasures","4":"Four Treasures","5":"Four Treasures"}',
                'game_code' => '8019',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Four Treasures',
                'external_game_id' => '8019',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Open Sesame","2":"芝麻开门","3":"Open Sesame","4":"Open Sesame","5":"Open Sesame"}',
                'game_code' => '8020',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Open Sesame',
                'external_game_id' => '8020',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Banana Saga","2":"黄金香蕉帝国","3":"Banana Saga","4":"Banana Saga","5":"Banana Saga"}',
                'game_code' => '8021',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Banana Saga',
                'external_game_id' => '8021',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Mahjong","2":"麻雀无双","3":"Mahjong","4":"Mahjong","5":"Mahjong"}',
                'game_code' => '8022',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Mahjong',
                'external_game_id' => '8022',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Olympian Temple","2":"奥林匹亚神庙","3":"Olympian Temple","4":"Olympian Temple","5":"Olympian Temple"}',
                'game_code' => '8023',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Olympian Temple',
                'external_game_id' => '8023',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Dancing Papa","2":"热舞教父","3":"Dancing Papa","4":"Dancing Papa","5":"Dancing Papa"}',
                'game_code' => '8026',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Dancing Papa',
                'external_game_id' => '8026',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Chef-Doeuvre","2":"料理厨王","3":"Chef-Doeuvre","4":"Chef-Doeuvre","5":"Chef-Doeuvre"}',
                'game_code' => '8027',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Chef-Doeuvre',
                'external_game_id' => '8027',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Lucky Miner","2":"幸运淘金鼠","3":"Lucky Miner","4":"Lucky Miner","5":"Lucky Miner"}',
                'game_code' => '8028',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Lucky Miner',
                'external_game_id' => '8028',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Candy Land","2":"奇幻糖果岛","3":"Candy Land","4":"Candy Land","5":"Candy Land"}',
                'game_code' => '8029',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Candy Land',
                'external_game_id' => '8029',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Crazy Scientist","2":"疯狂科学家","3":"Crazy Scientist","4":"Crazy Scientist","5":"Crazy Scientist"}',
                'game_code' => '8030',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Crazy Scientist',
                'external_game_id' => '8030',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Super Dumpling","2":"金饺子","3":"Super Dumpling","4":"Super Dumpling","5":"Super Dumpling"}',
                'game_code' => '8031',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Super Dumpling',
                'external_game_id' => '8031',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Cash Man","2":"金钱侠","3":"Cash Man","4":"Cash Man","5":"Cash Man"}',
                'game_code' => '8034',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Cash Man',
                'external_game_id' => '8034',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Lucky Phoenix","2":"幸运凤","3":"Lucky Phoenix","4":"Lucky Phoenix","5":"Lucky Phoenix"}',
                'game_code' => '8035',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Lucky Phoenix',
                'external_game_id' => '8035',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Dragon King","2":"龙王","3":"Dragon King","4":"Dragon King","5":"Dragon King"}',
                'game_code' => '8036',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Dragon King',
                'external_game_id' => '8036',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Magic Show","2":"魔术秀","3":"Magic Show","4":"Magic Show","5":"Magic Show"}',
                'game_code' => '8037',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Magic Show',
                'external_game_id' => '8037',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Wild Beauty","2":"江山美人","3":"Wild Beauty","4":"Wild Beauty","5":"Wild Beauty"}',
                'game_code' => '8044',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Wild Beauty',
                'external_game_id' => '8044',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Guan Yu","2":"关公","3":"Guan Yu","4":"Guan Yu","5":"Guan Yu"}',
                'game_code' => '8046',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Guan Yu',
                'external_game_id' => '8046',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Cock Fight","2":"斗鸡","3":"Cock Fight","4":"Cock Fight","5":"Cock Fight"}',
                'game_code' => '14001',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Cock Fight',
                'external_game_id' => '14001',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Maya Run","2":"玛雅大冒险","3":"Maya Run","4":"Maya Run","5":"Maya Run"}',
                'game_code' => '14002',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Maya Run',
                'external_game_id' => '14002',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Panda Panda","2":"屌丝熊猫","3":"Panda Panda","4":"Panda Panda","5":"Panda Panda"}',
                'game_code' => '14003',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Panda Panda',
                'external_game_id' => '14003',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Zelda","2":"塞尔达传说","3":"Zelda","4":"Zelda","5":"Zelda"}',
                'game_code' => '14004',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Zelda',
                'external_game_id' => '14004',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Mr. Bao","2":"包大人","3":"Mr. Bao","4":"Mr. Bao","5":"Mr. Bao"}',
                'game_code' => '14005',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Mr. Bao',
                'external_game_id' => '14005',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Billionaire","2":"亿万富翁","3":"Billionaire","4":"Billionaire","5":"Billionaire"}',
                'game_code' => '14006',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Billionaire',
                'external_game_id' => '14006',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"One Punch Man","2":"一拳超人","3":"One Punch Man","4":"One Punch Man","5":"One Punch Man"}',
                'game_code' => '14007',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'One Punch Man',
                'external_game_id' => '14007',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Dragon Warrior","2":"神龙大侠","3":"Dragon Warrior","4":"Dragon Warrior","5":"Dragon Warrior"}',
                'game_code' => '14008',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Dragon Warrior',
                'external_game_id' => '14008',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Dragpn","2":"飞龙在天","3":"Dragpn","4":"Dragpn","5":"Dragpn"}',
                'game_code' => '14010',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Dragpn',
                'external_game_id' => '14010',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Guardians of The Galaxy","2":"银河护卫队","3":"Guardians of The Galaxy","4":"Guardians of The Galaxy","5":"Guardians of The Galaxy"}',
                'game_code' => '14011',
                'dlc_enabled' => $db_true,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Guardians of The Galaxy',
                'external_game_id' => '14011',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Street Fighter","2":"街头霸王","3":"Street Fighter","4":"Street Fighter","5":"Street Fighter"}',
                'game_code' => '14012',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Street Fighter',
                'external_game_id' => '14012',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Star Wars","2":"星球大战","3":"Star Wars","4":"Star Wars","5":"Star Wars"}',
                'game_code' => '14015',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Star Wars',
                'external_game_id' => '14015',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Kingsman","2":"王牌特工","3":"Kingsman","4":"Kingsman","5":"Kingsman"}',
                'game_code' => '14016',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Kingsman',
                'external_game_id' => '14016',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"War of Beauty","2":"少女前线","3":"War of Beauty","4":"War of Beauty","5":"War of Beauty"}',
                'game_code' => '14017',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'War of Beauty',
                'external_game_id' => '14017',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Gems Gems","2":"宝石物语","3":"Gems Gems","4":"Gems Gems","5":"Gems Gems"}',
                'game_code' => '14019',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Gems Gems',
                'external_game_id' => '14019',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Rolling In Money","2":"钱滚钱","3":"Rolling In Money","4":"Rolling In Money","5":"Rolling In Money"}',
                'game_code' => '14021',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Rolling In Money',
                'external_game_id' => '14021',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Mining Upstart","2":"采矿土豪","3":"Mining Upstart","4":"Mining Upstart","5":"Mining Upstart"}',
                'game_code' => '14022',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Mining Upstart',
                'external_game_id' => '14022',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Rooster In Love","2":"金鸡报囍","3":"Rooster In Love","4":"Rooster In Love","5":"Rooster In Love"}',
                'game_code' => '15001',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Rooster In Love',
                'external_game_id' => '15001',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Monkey King","2":"齐天大圣","3":"Monkey King","4":"Monkey King","5":"Monkey King"}',
                'game_code' => '15002',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Monkey King',
                'external_game_id' => '15002',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"King of Sicbo","2":"骰宝无双","3":"King of Sicbo","4":"King of Sicbo","5":"King of Sicbo"}',
                'game_code' => '15003',
                'dlc_enabled' => $db_true,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'King of Sicbo',
                'external_game_id' => '15003',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Fire Bull","2":"火牛阵","3":"Fire Bull","4":"Fire Bull","5":"Fire Bull"}',
                'game_code' => '15004',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Fire Bull',
                'external_game_id' => '15004',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Inca Empire","2":"印加帝国","3":"Inca Empire","4":"Inca Empire","5":"Inca Empire"}',
                'game_code' => '15006',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Inca Empire',
                'external_game_id' => '15006',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Ninja Rush","2":"忍者大进击","3":"Ninja Rush","4":"Ninja Rush","5":"Ninja Rush"}',
                'game_code' => '15009',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Ninja Rush',
                'external_game_id' => '15009',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Chef Panda","2":"熊猫厨王","3":"Chef Panda","4":"Chef Panda","5":"Chef Panda"}',
                'game_code' => '15010',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Chef Panda',
                'external_game_id' => '15010',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Crystal Realm","2":"水晶王国","3":"Crystal Realm","4":"Crystal Realm","5":"Crystal Realm"}',
                'game_code' => '8024',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Crystal Realm',
                'external_game_id' => '8024',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Burglar","2":"神偷妙贼","3":"Burglar","4":"Burglar","5":"Burglar"}',
                'game_code' => '8025',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Burglar',
                'external_game_id' => '8025',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Winning Mask Live","2":"直播变脸","3":"Winning Mask Live","4":"Winning Mask Live","5":"Winning Mask Live"}',
                'game_code' => '8999',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Winning Mask Live',
                'external_game_id' => '8999',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"China Rouge","2":"春宵苦短","3":"China Rouge","4":"China Rouge","5":"China Rouge"}',
                'game_code' => '14013',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'China Rouge',
                'external_game_id' => '14013',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Daji","2":"妲己","3":"Daji","4":"Daji","5":"Daji"}',
                'game_code' => '14018',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Daji',
                'external_game_id' => '14018',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Cury Magician","2":"魔法乳神","3":"Cury Magician","4":"Cury Magician","5":"Cury Magician"}',
                'game_code' => '14020',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Cury Magician',
                'external_game_id' => '14020',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Poker King","2":"赌王扑克","3":"Poker King","4":"Poker King","5":"Poker King"}',
                'game_code' => '14023',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Poker King',
                'external_game_id' => '14023',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Lucky Racing","2":"幸运赛车","3":"Lucky Racing","4":"Lucky Racing","5":"Lucky Racing"}',
                'game_code' => '14025',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Lucky Racing',
                'external_game_id' => '14025',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Sun Archer","2":"后羿","3":"Sun Archer","4":"Sun Archer","5":"Sun Archer"}',
                'game_code' => '15011',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Sun Archer',
                'external_game_id' => '15011',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Mystery of Nine Tales","2":"九尾狐","3":"Mystery of Nine Tales","4":"Mystery of Nine Tales","5":"Mystery of Nine Tales"}',
                'game_code' => '15013',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Mystery of Nine Tales',
                'external_game_id' => '15013',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Fa Da Cai","2":"发大财","3":"Fa Da Cai","4":"Fa Da Cai","5":"Fa Da Cai"}',
                'game_code' => '14026',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Fa Da Cai',
                'external_game_id' => '14026',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Legendary 5","2":"五福臨門","3":"Legendary 5","4":"Legendary 5","5":"Legendary 5"}',
                'game_code' => '15012',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Legendary 5',
                'external_game_id' => '15012',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"Cai Shen Bingo","2":"財神賓果","3":"Cai Shen Bingo","4":"Cai Shen Bingo","5":"Cai Shen Bingo"}',
                'game_code' => '12001',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Cai Shen Bingo',
                'external_game_id' => '12001',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"Gold Rooster Lottery","2":"金雞福彩","3":"Gold Rooster Lottery","4":"Gold Rooster Lottery","5":"Gold Rooster Lottery"}',
                'game_code' => '12002',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Gold Rooster Lottery',
                'external_game_id' => '12002',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"Happy Lottery","2":"快樂六星彩","3":"Happy Lottery","4":"Happy Lottery","5":"Happy Lottery"}',
                'game_code' => '12003',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Happy Lottery',
                'external_game_id' => '12003',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            #====================================End Game list=========================================
        );

        $this->load->model(['game_description_model']);

        $success=$this->game_description_model->syncGameDescription($game_descriptions);

        return $success;
    }

}