<?php
trait game_description_opus_sportsbook {

    public function sync_game_description_ebet_opus(){
        $api_id = EBET_OPUS_API;
        $this->opus_sportsbook_game_list($api_id);
    }

    public function sync_game_description_opus_sportsbook(){
        $api_id=OPUS_SPORTSBOOK_API;
        $this->opus_sportsbook_game_list($api_id);
    }

    public function opus_sportsbook_game_list($api_id){

        // $cnt=0;
        $success=true;

        $db_true=1;
        $db_false=0;
        $now=$this->utils->getNowForMysql();

        $game_type_code_sports      = SYNC::TAG_CODE_SPORTS;
        $game_type_code_unknown     = SYNC::TAG_CODE_UNKNOWN_GAME;

        //sync game type first
        //use game_type_code as key
        $game_types = [
            $game_type_code_sports => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Sports","2":"体育", "3":"Sports", "4":"Sports","5":"Sports"}',
                'game_type_lang' => '_json:{"1":"Sports","2":"体育", "3":"Sports", "4":"Sports","5":"Sports"}',
                'game_type_code' => $game_type_code_sports,
                'game_tag_code' => $game_type_code_sports,
            ],
            $game_type_code_unknown => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Opus Sports Unknown","2":"opus体育未知游戏","3":"Opus Sports Unknown","4":"Opus Sports Unknown","5":"Opus Sports Unknown"}',
                'game_type_lang' => '_json:{"1":"Opus Sports Unknown","2":"opus体育未知游戏","3":"Opus Sports Unknown","4":"Opus Sports Unknown","5":"Opus Sports Unknown"}',
                'game_type_code' => $game_type_code_unknown,
                'game_tag_code' => $game_type_code_unknown,
            ],
        ];

        $this->load->model(['game_type_model']);
        $gameTypeCodeMaps=$this->game_type_model->syncGameTypes($game_types);

        $this->utils->debug_log('gameTypeCodeMaps', $gameTypeCodeMaps);

        if(empty($gameTypeCodeMaps)){
            return false;
        }

        $game_descriptions = [
           [
                'game_name' => '_json:{"1":"Soccer","2":"Soccer","3":"Soccer","4":"Soccer","5":"Soccer"}',
                'game_code' => '10',
                'game_platform_id' => $api_id,
                'external_game_id' => '10',
                'english_name' => 'Soccer',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"Tennis","2":"Tennis","3":"Tennis","4":"Tennis","5":"Tennis"}',
                'game_code' => '11',
                'game_platform_id' => $api_id,
                'external_game_id' => '11',
                'english_name' => 'Tennis',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"Basketball","2":"Basketball","3":"Basketball","4":"Basketball","5":"Basketball"}',
                'game_code' => '12',
                'game_platform_id' => $api_id,
                'external_game_id' => '12',
                'english_name' => 'Basketball',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"Handball","2":"Handball","3":"Handball","4":"Handball","5":"Handball"}',
                'game_code' => '15',
                'game_platform_id' => $api_id,
                'external_game_id' => '15',
                'english_name' => 'Handball',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"Volleyball","2":"Volleyball","3":"Volleyball","4":"Volleyball","5":"Volleyball"}',
                'game_code' => '16',
                'game_platform_id' => $api_id,
                'external_game_id' => '16',
                'english_name' => 'Volleyball',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"Baseball","2":"Baseball","3":"Baseball","4":"Baseball","5":"Baseball"}',
                'game_code' => '18',
                'game_platform_id' => $api_id,
                'external_game_id' => '18',
                'english_name' => 'Baseball',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"Golf","2":"Golf","3":"Golf","4":"Golf","5":"Golf"}',
                'game_code' => '19',
                'game_platform_id' => $api_id,
                'external_game_id' => '19',
                'english_name' => 'Golf',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"Cycling","2":"Cycling","3":"Cycling","4":"Cycling","5":"Cycling"}',
                'game_code' => '20',
                'game_platform_id' => $api_id,
                'external_game_id' => '20',
                'english_name' => 'Cycling',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"Boxing","2":"Boxing","3":"Boxing","4":"Boxing","5":"Boxing"}',
                'game_code' => '21',
                'game_platform_id' => $api_id,
                'external_game_id' => '21',
                'english_name' => 'Boxing',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"Cricket","2":"Cricket","3":"Cricket","4":"Cricket","5":"Cricket"}',
                'game_code' => '22',
                'game_platform_id' => $api_id,
                'external_game_id' => '22',
                'english_name' => 'Cricket',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"Ice Hockey","2":"Ice Hockey","3":"Ice Hockey","4":"Ice Hockey","5":"Ice Hockey"}',
                'game_code' => '26',
                'game_platform_id' => $api_id,
                'external_game_id' => '26',
                'english_name' => 'Ice Hockey',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"Badminton","2":"Badminton","3":"Badminton","4":"Badminton","5":"Badminton"}',
                'game_code' => '32',
                'game_platform_id' => $api_id,
                'external_game_id' => '32',
                'english_name' => 'Badminton',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"Football","2":"Football","3":"Football","4":"Football","5":"Football"}',
                'game_code' => '34',
                'game_platform_id' => $api_id,
                'external_game_id' => '34',
                'english_name' => 'Football',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"Table Tennis","2":"Table Tennis","3":"Table Tennis","4":"Table Tennis","5":"Table Tennis"}',
                'game_code' => '35',
                'game_platform_id' => $api_id,
                'external_game_id' => '35',
                'english_name' => 'Table Tennis',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"Beach Soccer","2":"Beach Soccer","3":"Beach Soccer","4":"Beach Soccer","5":"Beach Soccer"}',
                'game_code' => '36',
                'game_platform_id' => $api_id,
                'external_game_id' => '36',
                'english_name' => 'Beach Soccer',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"Futsal","2":"Futsal","3":"Futsal","4":"Futsal","5":"Futsal"}',
                'game_code' => '37',
                'game_platform_id' => $api_id,
                'external_game_id' => '37',
                'english_name' => 'Futsal',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"Pool/Snooker","2":"Pool/Snooker","3":"Pool/Snooker","4":"Pool/Snooker","5":"Pool/Snooker"}',
                'game_code' => '38',
                'game_platform_id' => $api_id,
                'external_game_id' => '38',
                'english_name' => 'Pool/Snooker',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"Rugby","2":"Rugby","3":"Rugby","4":"Rugby","5":"Rugby"}',
                'game_code' => '39',
                'game_platform_id' => $api_id,
                'external_game_id' => '39',
                'english_name' => 'Rugby',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"MotorSport","2":"MotorSport","3":"MotorSport","4":"MotorSport","5":"MotorSport"}',
                'game_code' => '40',
                'game_platform_id' => $api_id,
                'external_game_id' => '40',
                'english_name' => 'MotorSport',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"Darts","2":"Darts","3":"Darts","4":"Darts","5":"Darts"}',
                'game_code' => '41',
                'game_platform_id' => $api_id,
                'external_game_id' => '41',
                'english_name' => 'Darts',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"Athletics","2":"Athletics","3":"Athletics","4":"Athletics","5":"Athletics"}',
                'game_code' => '42',
                'game_platform_id' => $api_id,
                'external_game_id' => '42',
                'english_name' => 'Athletics',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"Enterainment","2":"Enterainment","3":"Enterainment","4":"Enterainment","5":"Enterainment"}',
                'game_code' => '43',
                'game_platform_id' => $api_id,
                'external_game_id' => '43',
                'english_name' => 'Enterainment',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"Financial","2":"Financial","3":"Financial","4":"Financial","5":"Financial"}',
                'game_code' => '44',
                'game_platform_id' => $api_id,
                'external_game_id' => '44',
                'english_name' => 'Financial',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"Field Hockey","2":"Field Hockey","3":"Field Hockey","4":"Field Hockey","5":"Field Hockey"}',
                'game_code' => '45',
                'game_platform_id' => $api_id,
                'external_game_id' => '45',
                'english_name' => 'Field Hockey',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"Water Polo","2":"Water Polo","3":"Water Polo","4":"Water Polo","5":"Water Polo"}',
                'game_code' => '46',
                'game_platform_id' => $api_id,
                'external_game_id' => '46',
                'english_name' => 'Water Polo',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"Winter Sports","2":"Winter Sports","3":"Winter Sports","4":"Winter Sports","5":"Winter Sports"}',
                'game_code' => '47',
                'game_platform_id' => $api_id,
                'external_game_id' => '47',
                'english_name' => 'Winter Sports',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"Olympic","2":"Olympic","3":"Olympic","4":"Olympic","5":"Olympic"}',
                'game_code' => '48',
                'game_platform_id' => $api_id,
                'external_game_id' => '48',
                'english_name' => 'Olympic',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"Squash","2":"Squash","3":"Squash","4":"Squash","5":"Squash"}',
                'game_code' => '49',
                'game_platform_id' => $api_id,
                'external_game_id' => '49',
                'english_name' => 'Squash',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"Lacrosse","2":"Lacrosse","3":"Lacrosse","4":"Lacrosse","5":"Lacrosse"}',
                'game_code' => '50',
                'game_platform_id' => $api_id,
                'external_game_id' => '50',
                'english_name' => 'Lacrosse',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"Mixed Martial Arts","2":"Mixed Martial Arts","3":"Mixed Martial Arts","4":"Mixed Martial Arts","5":"Mixed Martial Arts"}',
                'game_code' => '51',
                'game_platform_id' => $api_id,
                'external_game_id' => '51',
                'english_name' => 'Mixed Martial Arts',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"E-Sport","2":"E-Sport","3":"E-Sport","4":"E-Sport","5":"E-Sport"}',
                'game_code' => '52',
                'game_platform_id' => $api_id,
                'external_game_id' => '52',
                'english_name' => 'E-Sport',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"Netball","2":"Netball","3":"Netball","4":"Netball","5":"Netball"}',
                'game_code' => '53',
                'game_platform_id' => $api_id,
                'external_game_id' => '53',
                'english_name' => 'Netball',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"Diving","2":"Diving","3":"Diving","4":"Diving","5":"Diving"}',
                'game_code' => '54',
                'game_platform_id' => $api_id,
                'external_game_id' => '54',
                'english_name' => 'Diving',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"Swimming","2":"Swimming","3":"Swimming","4":"Swimming","5":"Swimming"}',
                'game_code' => '55',
                'game_platform_id' => $api_id,
                'external_game_id' => '55',
                'english_name' => 'Swimming',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"Muay Thai","2":"Muay Thai","3":"Muay Thai","4":"Muay Thai","5":"Muay Thai"}',
                'game_code' => '56',
                'game_platform_id' => $api_id,
                'external_game_id' => '56',
                'english_name' => 'Muay Thai',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"Others","2":"Others","3":"Others","4":"Others","5":"Others"}',
                'game_code' => '97',
                'game_platform_id' => $api_id,
                'external_game_id' => '97',
                'english_name' => 'Others',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
            ],
            [
                'game_name' => '_json:{"1":"UNKNOWN GAME","2":"不明游戏","3":"UNKNOWN GAME","4":"UNKNOWN GAME","5":"UNKNOWN GAME"}',
                'game_code' => 'unknown',
                'game_platform_id' => $api_id,
                'external_game_id' => 'unknown',
                'english_name' => 'UNKNOWN GAME',
                'status' => $db_true,
                'flag_show_in_site' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_unknown],
            ],
        ];

        $this->load->model(['game_description_model']);

        $success=$this->game_description_model->syncGameDescription($game_descriptions);

        return $success;
    }

}
