<?php
trait game_description_yoplay {

    public function sync_game_description_yoplay(){
        $api_id = YOPLAY_API;
        $this->yoplay_game_list($api_id);

    }

    public function sync_game_description_yoplay_t1(){
        $api_id = T1YOPLAY_API;
        $this->yoplay_game_list($api_id);

    }

    public function yoplay_game_list($api_id){

        $db_true = 1;
        $db_false = 0;
        $now = $this->utils->getNowForMysql();

        $game_type_code_slots= SYNC::TAG_CODE_SLOT;
        $game_type_code_unknown = SYNC::TAG_CODE_UNKNOWN_GAME;

        // sync game type first
        // use game_type_code as key
        $game_types = [
            $game_type_code_slots=> [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Slot","2":"老虎机游戏","3":"Slot","4":"Slot","5":"Slot"}',
                'game_type_lang' => '_json:{"1":"Slot","2":"老虎机游戏","3":"Slot","4":"Slot","5":"Slot"}',
                'game_type_code' => $game_type_code_slots,
                'flag_show_in_site' => $db_true,
                'auto_add_new_game' => $db_true,
                'auto_add_to_cashback' => $db_true,
                'status' => $db_true,
                'updated_at' => $now,
                'game_tag_code' => SYNC::TAG_CODE_SLOT
            ],
            $game_type_code_unknown => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                'game_type_lang' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                "game_type_code" => $game_type_code_unknown,
                'flag_show_in_site' => $db_true,
                'auto_add_new_game' => $db_true,
                'auto_add_to_cashback' => $db_true,
                'status'=>$db_true,
                'updated_at'=>$now,
                'game_tag_code' => SYNC::TAG_CODE_UNKNOWN_GAME
            ],
        ];


        $this->load->model(['game_type_model']);
        $gameTypeCodeMaps=$this->game_type_model->syncGameTypes($game_types);

        $this->utils->debug_log('gameTypeCodeMaps', $gameTypeCodeMaps);

        $game_descriptions = array(
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_unknown],
                'game_name' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                'game_code' => 'unknown',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_false,
                'flag_show_in_site' => $db_false,
                'html_five_enabled' => $db_false,
                'english_name' => 'Unknown',
                'external_game_id' => 'unknown',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_false,
                'enabled_on_ios' => $db_false,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Forest Dance","2":"森林舞会单人版","3":"Forest Dance","4":"Forest Dance","5":"Forest Dance"}',
                'game_code' => 'YFD',
                'attributes' => '{"game_launch_code":"YP801"}',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Forest Dance',
                'external_game_id' => 'YFD',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"BenzBMW","2":"奔驰宝马单人版","3":"BenzBMW","4":"BenzBMW","5":"BenzBMW"}',
                'game_code' => 'YBEN',
                'attributes' => '{"game_launch_code":"YP802"}',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'BenzBMW',
                'external_game_id' => 'YBEN',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Run Horse","2":"极速赛马","3":"Run Horse","4":"Run Horse","5":"Run Horse"}',
                'game_code' => 'YHR',
                'attributes' => '{"game_launch_code":"YP803"}',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Run Horse',
                'external_game_id' => 'YHR',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Guess","2":"猜猜乐","3":"Guess","4":"Guess","5":"Guess"}',
                'game_code' => 'YGS',
                'attributes' => '{"game_launch_code":"YP804"}',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Guess',
                'external_game_id' => 'YGS',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Fruit Slot","2":"水果拉霸","3":"Fruit Slot","4":"Fruit Slot","5":"Fruit Slot"}',
                'game_code' => 'YFR',
                'attributes' => '{"game_launch_code":"YP805"}',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Fruit Slot',
                'external_game_id' => 'YFR',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Texas Cowboy","2":"水果拉霸","3":"Texas Cowboy","4":"Texas Cowboy","5":"Texas Cowboy"}',
                'game_code' => 'YDZ',
                'attributes' => '{"game_launch_code":"YP806"}',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Texas Cowboy',
                'external_game_id' => 'YDZ',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Birds & Beasts","2":"飞禽走兽","3":"Birds & Beasts","4":"Birds & Beasts","5":"Birds & Beasts"}',
                'game_code' => 'YBIR',
                'attributes' => '{"game_launch_code":"YP807"}',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Birds & Beasts',
                'external_game_id' => 'YBIR',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Fruit Party","2":"水果派对","3":"Fruit Party","4":"Fruit Party","5":"Fruit Party"}',
                'game_code' => 'YFP',
                'attributes' => '{"game_launch_code":"YP808"}',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Fruit Party',
                'external_game_id' => 'YFP',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Forest Dance Multiplayer","2":"森林舞会多人版","3":"Forest Dance Multiplayer","4":"Forest Dance Multiplayer","5":"Forest Dance Multiplayer"}',
                'game_code' => 'YMFD',
                'attributes' => '{"game_launch_code":"YP810"}',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Forest Dance Multiplayer',
                'external_game_id' => 'YMFD',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Fruit Slot Multiplayer","2":"水果拉霸多人版","3":"Fruit Slot Multiplayer","4":"Fruit Slot Multiplayer","5":"Fruit Slot Multiplayer"}',
                'game_code' => 'YMFR',
                'attributes' => '{"game_launch_code":"YP813"}',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Forest Slot Multiplayer',
                'external_game_id' => 'YMFR',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Yo Bull","2":"百人牛牛","3":"Yo Bull","4":"Yo Bull","5":"Yo Bull"}',
                'game_code' => 'YMBN',
                'attributes' => '{"game_launch_code":"YP817"}',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Yo Bull',
                'external_game_id' => 'YMBN',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Treasure Fruit slot","2":"多寶水果拉霸","3":"Treasure Fruit slot","4":"Treasure Fruit slot","5":"Treasure Fruit slot"}',
                'game_code' => 'YGFS',
                'attributes' => '{"game_launch_code":"YP818"}',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Treasure Fruit slot',
                'external_game_id' => 'YGFS',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Birds and Beasts Multiplayer","2":"飛禽走獸多人版","3":"Birds and Beasts Multiplayer","4":"Birds and Beasts Multiplayer","5":"Birds and Beasts Multiplayer"}',
                'game_code' => 'YMBI',
                'attributes' => '{"game_launch_code":"YP814"}',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Birds and Beasts Multiplayer',
                'external_game_id' => 'YMBI',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Bull Battle","2":"牛牛對戰","3":"Bull Battle","4":"Bull Battle","5":"Bull Battle"}',
                'game_code' => 'YMBA',
                'attributes' => '{"game_launch_code":"YP821"}',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Bull Battle',
                'external_game_id' => 'YMBA',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Benz and BMW multiplayer Mode","2":"奔馳寶馬多人版","3":"Benz and BMW multiplayer Mode","4":"Benz and BMW multiplayer Mode","5":"Benz and BMW multiplayer Mode"}',
                'game_code' => 'YMBZ',
                'attributes' => '{"game_launch_code":"YP811"}',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Benz and BMW multiplayer Mode',
                'external_game_id' => 'YMBZ',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Carnival Animal","2":"奔馳寶馬多人版","3":"Carnival Animal","4":"Carnival Animal","5":"Carnival Animal"}',
                'game_code' => 'YMAC',
                'attributes' => '{"game_launch_code":"YP823"}',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Carnival Animal',
                'external_game_id' => 'YMAC',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Guess Multiplayer","2":"猜猜乐多人版","3":"Guess Multiplayer","4":"Guess Multiplayer","5":"Guess Multiplayer"}',
                'game_code' => 'YMGS',
                'attributes' => '{"game_launch_code":"YMGS"}',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'status' => $db_false,
                'flag_show_in_site' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Guess Multiplayer',
                'external_game_id' => 'YMGS',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Western Journey","2":"西游争霸","3":"Western Journey","4":"Western Journey","5":"Western Journey"}',
                'game_code' => 'YMJW',
                'attributes' => '{"game_launch_code":"YP824"}',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Western Journey',
                'external_game_id' => 'YMJW',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Double Win 3 Cards","2":"翻倍炸金花","3":"Double Win 3 Cards","4":"Double Win 3 Cards","5":"Double Win 3 Cards"}',
                'game_code' => 'YMJH',
                'attributes' => '{"game_launch_code":"YP822"}',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Double Win 3 Cards',
                'external_game_id' => 'YMJH',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Yoplay Plaza","2":"yoplay大厅","3":"Yoplay Plaza","4":"Yoplay Plaza","5":"Yoplay Plaza"}',
                'game_code' => 'YPLA',
                'attributes' => '{"game_launch_code":"YP800"}',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Yoplay Plaza',
                'external_game_id' => 'YPLA',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Jackpot Fruit Slot","2":"彩金水果拉霸","3":"Jackpot Fruit Slot","4":"Jackpot Fruit Slot","5":"Jackpot Fruit Slot"}',
                'game_code' => 'YJFS',
                'attributes' => '{"game_launch_code":"YP820"}',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Jackpot Fruit Slot',
                'external_game_id' => 'YJFS',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Battle Field","2":"刺激战场","3":"Battle Field","4":"Battle Field","5":"Battle Field"}',
                'game_code' => 'YMBF',
                'attributes' => '{"game_launch_code":"YMBF"}',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Battle Field',
                'external_game_id' => 'YMBF',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"San Gong","2":"斗三公","3":"San Gong","4":"San Gong","5":"San Gong"}',
                'game_code' => 'YMSG',
                'attributes' => '{"game_launch_code":"YP825"}',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'San Gong',
                'external_game_id' => 'YMSG',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Double Jokers","2":"红黑梅方","3":"Double Jokers","4":"Double Jokers","5":"Double Jokers"}',
                'game_code' => 'YMJJ',
                'attributes' => '{"game_launch_code":"YP828"}',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Double Jokers',
                'external_game_id' => 'YMJJ',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Treasure World","2":"彩金宝藏世界","3":"Treasure World","4":"Treasure World","5":"Treasure World"}',
                'game_code' => 'YJTW',
                'attributes' => '{"game_launch_code":"YP828"}',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Treasure World',
                'external_game_id' => 'YJTW',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Crazy Texas","2":"疯狂德州","3":"Crazy Texas","4":"Crazy Texas","5":"Crazy Texas"}',
                'game_code' => 'YMD2',
                'attributes' => '{"game_launch_code":"YP830"}',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Crazy Texas',
                'external_game_id' => 'YMD2',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
         #====================================End Game list=========================================
        );

        $this->load->model(['game_description_model']);

        $success=$this->game_description_model->syncGameDescription($game_descriptions);

        return $success;
    }

}