<?php
trait game_description_genesism4 {

    public function sync_game_description_genesism4(&$cnt=0){

        // $cnt=0;

        $success=true;

        $api_id=GENESISM4_GAME_API;
        $db_true=1;
        $db_false=0;
        $now=$this->utils->getNowForMysql();

        $game_type_code_slots       = SYNC::TAG_CODE_SLOT;
        $game_type_code_unknown     = SYNC::TAG_CODE_UNKNOWN_GAME;
        $game_type_code_fishing_game = SYNC::TAG_CODE_FISHING_GAME;

        //sync game type first
        //use game_type_code as key
        $game_types = [
            $game_type_code_slots => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Slots","2":"老虎机","3":"Slots","4":"Slots","5":"Slots"}',
                'game_type_lang' => '_json:{"1":"Slots","2":"老虎机","3":"Slots","4":"Slots","5":"Slots"}',
                "game_type_code" => $game_type_code_slots,
                "game_tag_code" => $game_type_code_slots,
                'updated_at'=>$now,
            ],
            $game_type_code_fishing_game => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Fishing Game","2":"Fishing Game","3":"Fishing Game","4":"Fishing Game","5":"Fishing Game"}',
                'game_type_lang' => '_json:{"1":"Fishing Game","2":"Fishing Game","3":"Fishing Game","4":"Fishing Game","5":"Fishing Game"}',
                'game_type_code' => $game_type_code_fishing_game,
                'updated_at' => $now,
                'game_tag_code' => $game_type_code_fishing_game
            ],
            $game_type_code_unknown => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                'game_type_lang' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                "game_type_code" => $game_type_code_unknown,
                "game_tag_code" => $game_type_code_unknown,
                'updated_at'=>$now,
            ]
        ];

        $this->load->model(['game_type_model']);
        $gameTypeCodeMaps=$this->game_type_model->syncGameTypes($game_types);

        $this->utils->debug_log('gameTypeCodeMaps', $gameTypeCodeMaps);

        if(empty($gameTypeCodeMaps)){
            return false;
        }

        $game_descriptions = [

            #=========================================== Game List ========================================
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_fishing_game],
                    "game_name" => '_json:{"1":"Sea Raider","2":"寻宝捕鱼王","3":"Sea Raider","4":"Sea Raider","5":"Sea Raider"}',
                    "game_code" => 'M4-0075;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Sea Raider',
                    "external_game_id" => 'M4-0075;V:1',
            ],
            [

                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Reptile Riches","2":"冷血之财","3":"Reptile Riches","4":"Reptile Riches","5":"Reptile Riches"}',
                    "game_code" => 'DINO_M4_V4_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Reptile Riches',
                    "external_game_id" => 'DINO_M4_V4_RECORDER;V:1',
            ],
            [

                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"More Cheese Please","2":"奶酪大冒险","3":"More Cheese Please","4":"More Cheese Please","5":"More Cheese Please"}',
                    "game_code" => 'MORE_CHEESE_GAME1_M4_V1_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'More Cheese Please',
                    "external_game_id" => 'MORE_CHEESE_GAME1_M4_V1_RECORDER;V:1',
            ],
            [

                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Belle’s Bandits","2":"女匪争夺战","3":"Belle’s Bandits","4":"Belle’s Bandits","5":"Belle’s Bandits"}',
                    "game_code" => 'DINO_M4_V3_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Belle’s Bandits',
                    "external_game_id" => 'DINO_M4_V3_RECORDER;V:1',
            ],
            [

                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Fa Fa Fa","2":"发发发","3":"Fa Fa Fa","4":"Fa Fa Fa","5":"Fa Fa Fa"}',
                    "game_code" => 'M4-0086;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Fa Fa Fa',
                    "external_game_id" => 'M4-0086;V:1',
            ],
            [

                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Mysterious Gems","2":"顯者之石","3":"Mysterious Gems","4":"Mysterious Gems","5":"Mysterious Gems"}',
                    "game_code" => 'M4-0070;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Mysterious Gems',
                    "external_game_id" => 'M4-0070;V:1',
            ],
            [

                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Cool As Ice","2":"冰上世界","3":"Cool As Ice","4":"Cool As Ice","5":"Cool As Ice"}',
                    "game_code" => 'CAI_M4_V2_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Cool As Ice',
                    "external_game_id" => 'CAI_M4_V2_RECORDER;V:1',
            ],
            [

                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Super Wilds","2":"狂野英雄","3":"Super Wilds","4":"Super Wilds","5":"Super Wilds"}',
                    "game_code" => 'SW_M4_V1_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Super Wilds',
                    "external_game_id" => 'SW_M4_V1_RECORDER;V:1',
            ],
            [

                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Prime Time Combat Kings","2":"综合格斗王","3":"Prime Time Combat Kings","4":"Prime Time Combat Kings","5":"Prime Time Combat Kings"}',
                    "game_code" => 'M4-0073;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Prime Time Combat Kings',
                    "external_game_id" => 'M4-0073;V:1',
            ],
            [

                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Crosstown Chicken","2":"小鸡哔哔哔","3":"Crosstown Chicken","4":"Crosstown Chicken","5":"Crosstown Chicken"}',
                    "game_code" => 'M4-0060;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Crosstown Chicken',
                    "external_game_id" => 'M4-0060;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Schlagermillions","2":"百万金曲大赛","3":"Schlagermillions","4":"Schlagermillions","5":"Schlagermillions"}',
                    "game_code" => 'M4-0056;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Schlagermillions',
                    "external_game_id" => 'M4-0056;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Leprechaun Legends","2":"妖精传奇","3":"Leprechaun Legends","4":"Leprechaun Legends","5":"Leprechaun Legends"}',
                    "game_code" => 'LEPR_LEGENDS_V1_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Leprechaun Legends',
                    "external_game_id" => 'LEPR_LEGENDS_V1_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Machu Picchu Gold","2":"马丘比丘寻宝记","3":"Machu Picchu Gold","4":"Machu Picchu Gold","5":"Machu Picchu Gold"}',
                    "game_code" => 'ROBYN_FT_V4_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Machu Picchu Gold',
                    "external_game_id" => 'ROBYN_FT_V4_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Game of Swords","2":"神剑对决","3":"Game of Swords","4":"Game of Swords","5":"Game of Swords"}',
                    "game_code" => 'GOS_M4_V2_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Game of Swords',
                    "external_game_id" => 'GOS_M4_V2_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Pillaging Pirates","2":"海盗掠夺战","3":"Pillaging Pirates","4":"Pillaging Pirates","5":"Pillaging Pirates"}',
                    "game_code" => 'WHITE_BUFFALO_M4_GAME3_V1_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Pillaging Pirates',
                    "external_game_id" => 'WHITE_BUFFALO_M4_GAME3_V1_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Night of Sevens","2":"七夕情緣","3":"Night of Sevens","4":"Night of Sevens","5":"Night of Sevens"}',
                    "game_code" => 'M4-0077;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Night of Sevens',
                    "external_game_id" => 'M4-0077;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"River Dragons","2":"河龙传说","3":"River Dragons","4":"River Dragons","5":"River Dragons"}',
                    "game_code" => 'RIVER_DRAGON_V1_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'River Dragons',
                    "external_game_id" => 'RIVER_DRAGON_V1_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Bier Fest","2":"啤酒盛宴","3":"Bier Fest","4":"Bier Fest","5":"Bier Fest"}',
                    "game_code" => 'BF_M4_V2_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Bier Fest',
                    "external_game_id" => 'BF_M4_V2_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Jazzy Christmas","2":"絕世聖誕夜","3":"Jazzy Christmas","4":"Jazzy Christmas","5":"Jazzy Christmas"}',
                    "game_code" => 'M4-0080;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Jazzy Christmas',
                    "external_game_id" => 'M4-0080;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Journey to the West","2":"西遊降魔傳","3":"Journey to the West","4":"Journey to the West","5":"Journey to the West"}',
                    "game_code" => 'M4-0067;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Journey to the West',
                    "external_game_id" => 'M4-0067;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Wild Space","2":"太空之轮","3":"Wild Space","4":"Wild Space","5":"Wild Space"}',
                    "game_code" => 'WILD_SPACE_V1_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Wild Space',
                    "external_game_id" => 'WILD_SPACE_V1_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Mystic Monkeys","2":"神秘猴城","3":"Mystic Monkeys","4":"Mystic Monkeys","5":"Mystic Monkeys"}',
                    "game_code" => 'MYSTICMONK_M4_V1_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Mystic Monkeys',
                    "external_game_id" => 'MYSTICMONK_M4_V1_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Sugar Smash","2":"糖果粉碎大战","3":"Sugar Smash","4":"Sugar Smash","5":"Sugar Smash"}',
                    "game_code" => 'SUGAR_SMASH_V1_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Sugar Smash',
                    "external_game_id" => 'SUGAR_SMASH_V1_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Today’s Weather","2":"今日气象","3":"Today’s Weather","4":"Today’s Weather","5":"Today’s Weather"}',
                    "game_code" => 'TW_M4_V1_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Today’s Weather',
                    "external_game_id" => 'TW_M4_V1_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Year of the Rooster ","2":"金鸡报喜","3":"Year of the Rooster ","4":"Year of the Rooster ","5":"Year of the Rooster "}',
                    "game_code" => 'ROOSTER_ZODIAC_M4_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Year of the Rooster ',
                    "external_game_id" => 'ROOSTER_ZODIAC_M4_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Mirror Magic","2":"魔镜魔镜","3":"Mirror Magic","4":"Mirror Magic","5":"Mirror Magic"}',
                    "game_code" => 'MIRROR_MAGIC_M4_V1_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Mirror Magic',
                    "external_game_id" => 'MIRROR_MAGIC_M4_V1_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Thunderbird Spirit","2":"雷鸟传说","3":"Thunderbird Spirit","4":"Thunderbird Spirit","5":"Thunderbird Spirit"}',
                    "game_code" => 'NECKER_ISLAND_GAME2_V1_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Thunderbird Spirit',
                    "external_game_id" => 'NECKER_ISLAND_GAME2_V1_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Riches In The Rough","2":"钻石暴富王","3":"Riches In The Rough","4":"Riches In The Rough","5":"Riches In The Rough"}',
                    "game_code" => 'REPTILE_RICHES_M4_V1_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Riches In The Rough',
                    "external_game_id" => 'REPTILE_RICHES_M4_V1_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Munchies","2":"贪吃玛吉斯","3":"Munchies","4":"Munchies","5":"Munchies"}',
                    "game_code" => 'M4-0074;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Munchies',
                    "external_game_id" => 'M4-0074;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Olympus","2":"奥林匹斯","3":"Olympus","4":"Olympus","5":"Olympus"}',
                    "game_code" => 'M4-0071;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Olympus',
                    "external_game_id" => 'M4-0071;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Temple Of Luxor","2":"卢克索神庙","3":"Temple Of Luxor","4":"Temple Of Luxor","5":"Temple Of Luxor"}',
                    "game_code" => 'LUXOR_M4_V1_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Temple Of Luxor',
                    "external_game_id" => 'LUXOR_M4_V1_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Clash Of Queens","2":"女王争霸","3":"Clash Of Queens","4":"Clash Of Queens","5":"Clash Of Queens"}',
                    "game_code" => 'CLASH_OF_QUEENS_M4_V1_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Clash Of Queens',
                    "external_game_id" => 'CLASH_OF_QUEENS_M4_V1_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Fortune Turtle","2":"招福钱龟","3":"Fortune Turtle","4":"Fortune Turtle","5":"Fortune Turtle"}',
                    "game_code" => 'FORTUNE_TURTLE_V1_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Fortune Turtle',
                    "external_game_id" => 'FORTUNE_TURTLE_V1_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Mobster Lobster","2":"深海教父","3":"Mobster Lobster","4":"Mobster Lobster","5":"Mobster Lobster"}',
                    "game_code" => 'M4-0061;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Mobster Lobster',
                    "external_game_id" => 'M4-0061;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Sahara Queen","2":"沙漠妖姬","3":"Sahara Queen","4":"Sahara Queen","5":"Sahara Queen"}',
                    "game_code" => 'M4-0057;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Sahara Queen',
                    "external_game_id" => 'M4-0057;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Gumball Blaster ","2":"爆破口香糖","3":"Gumball Blaster ","4":"Gumball Blaster ","5":"Gumball Blaster "}',
                    "game_code" => 'GUMBALL_M4_V1_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Gumball Blaster ',
                    "external_game_id" => 'GUMBALL_M4_V1_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Galapagos Islands","2":"哥拉宝岛冒险","3":"Galapagos Islands","4":"Galapagos Islands","5":"Galapagos Islands"}',
                    "game_code" => 'WHITE_BUFFALO_M4_GAME4_V1_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Galapagos Islands',
                    "external_game_id" => 'WHITE_BUFFALO_M4_GAME4_V1_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Leprechaun Tales","2":"妖精王国","3":"Leprechaun Tales","4":"Leprechaun Tales","5":"Leprechaun Tales"}',
                    "game_code" => 'MORE_CHEESE_M4_V3_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Leprechaun Tales',
                    "external_game_id" => 'MORE_CHEESE_M4_V3_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Wu Xing","2":"五行传说","3":"Wu Xing","4":"Wu Xing","5":"Wu Xing"}',
                    "game_code" => 'WX_M4_V2_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Wu Xing',
                    "external_game_id" => 'WX_M4_V2_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Fire and Ice Island","2":"冰火岛","3":"Fire and Ice Island","4":"Fire and Ice Island","5":"Fire and Ice Island"}',
                    "game_code" => 'M4-0081;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Fire and Ice Island',
                    "external_game_id" => 'M4-0081;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Opera of the Masks","2":"百变四川","3":"Opera of the Masks","4":"Opera of the Masks","5":"Opera of the Masks"}',
                    "game_code" => 'M4-0078;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Opera of the Masks',
                    "external_game_id" => 'M4-0078;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Dragon’s Rock","2":"摇滚飞龙","3":"Dragon’s Rock","4":"Dragon’s Rock","5":"Dragon’s Rock"}',
                    "game_code" => 'DRAGON_ROCK_M4_V1_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Dragon’s Rock',
                    "external_game_id" => 'DRAGON_ROCK_M4_V1_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Rich Mans Toys","2":"富翁玩物","3":"Rich Mans Toys","4":"Rich Mans Toys","5":"Rich Mans Toys"}',
                    "game_code" => 'WOP_GAME4_V1;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Rich Mans Toys',
                    "external_game_id" => 'WOP_GAME4_V1;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Bloodlines","2":"嗜血一族","3":"Bloodlines","4":"Bloodlines","5":"Bloodlines"}',
                    "game_code" => 'BL_M4_V2_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Bloodlines',
                    "external_game_id" => 'BL_M4_V2_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Lust and Fortune","2":"金欲滿堂","3":"Lust and Fortune","4":"Lust and Fortune","5":"Lust and Fortune"}',
                    "game_code" => 'M4-0068;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Lust and Fortune',
                    "external_game_id" => 'M4-0068;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Birds & Blooms ","2":"鸟语花香","3":"Birds & Blooms ","4":"Birds & Blooms ","5":"Birds & Blooms "}',
                    "game_code" => 'BIRDS_IN_BLOOM_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Birds & Blooms ',
                    "external_game_id" => 'BIRDS_IN_BLOOM_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Boom Squad","2":"炸弹游击队","3":"Boom Squad","4":"Boom Squad","5":"Boom Squad"}',
                    "game_code" => 'BOOM_SQUAD_V1_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Boom Squad',
                    "external_game_id" => 'BOOM_SQUAD_V1_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Carnaval Cash","2":"现金狂欢节","3":"Carnaval Cash","4":"Carnaval Cash","5":"Carnaval Cash"}',
                    "game_code" => 'CARN_CASH_M4_V2_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Carnaval Cash',
                    "external_game_id" => 'CARN_CASH_M4_V2_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Robyn","2":"罗宾大探险","3":"Robyn","4":"Robyn","5":"Robyn"}',
                    "game_code" => 'ROBYN_M4_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Robyn',
                    "external_game_id" => 'ROBYN_M4_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Fruity Grooves","2":"水果乐章","3":"Fruity Grooves","4":"Fruity Grooves","5":"Fruity Grooves"}',
                    "game_code" => 'FRUITY_GROOVES_M4_V1_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Fruity Grooves',
                    "external_game_id" => 'FRUITY_GROOVES_M4_V1_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Hear Me Roar","2":"万兽王之吼","3":"Hear Me Roar","4":"Hear Me Roar","5":"Hear Me Roar"}',
                    "game_code" => 'DINO_M4_V2_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Hear Me Roar',
                    "external_game_id" => 'DINO_M4_V2_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Dinosaur Adventure","2":"恐龙历险记","3":"Dinosaur Adventure","4":"Dinosaur Adventure","5":"Dinosaur Adventure"}',
                    "game_code" => 'DINO_M4_V1_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Dinosaur Adventure',
                    "external_game_id" => 'DINO_M4_V1_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Machine-Gun Unicorn","2":"神枪独角兽","3":"Machine-Gun Unicorn","4":"Machine-Gun Unicorn","5":"Machine-Gun Unicorn"}',
                    "game_code" => 'MGU_M4_V1_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Machine-Gun Unicorn',
                    "external_game_id" => 'MGU_M4_V1_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"RumpelThrillSpins","2":"金線奇緣","3":"RumpelThrillSpins","4":"RumpelThrillSpins","5":"RumpelThrillSpins"}',
                    "game_code" => 'M4-0072;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'RumpelThrillSpins',
                    "external_game_id" => 'M4-0072;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Gods Of Giza","2":"古埃及之神","3":"Gods Of Giza","4":"Gods Of Giza","5":"Gods Of Giza"}',
                    "game_code" => 'GIZA_M4_V1_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Gods Of Giza',
                    "external_game_id" => 'GIZA_M4_V1_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"8-Bit Intruders","2":"8位元地球保卫战","3":"8-Bit Intruders","4":"8-Bit Intruders","5":"8-Bit Intruders"}',
                    "game_code" => 'M4-0062;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "attributes" => $db_true,
                    "english_name" => '8-Bit Intruders',
                    "external_game_id" => 'M4-0062;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Euro Golden Cup ","2":"欧足冠军杯","3":"Euro Golden Cup ","4":"Euro Golden Cup ","5":"Euro Golden Cup "}',
                    "game_code" => 'EURO_V2_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Euro Golden Cup ',
                    "external_game_id" => 'EURO_V2_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Lion Dance Festival ","2":"舞狮献瑞","3":"Lion Dance Festival ","4":"Lion Dance Festival ","5":"Lion Dance Festival "}',
                    "game_code" => 'LION_DANCE_M4_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Lion Dance Festival ',
                    "external_game_id" => 'LION_DANCE_M4_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Unicorn Grove","2":"妖精丛林","3":"Unicorn Grove","4":"Unicorn Grove","5":"Unicorn Grove"}',
                    "game_code" => 'UNICORN_GROVE_V1_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Unicorn Grove',
                    "external_game_id" => 'UNICORN_GROVE_V1_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Bark In The Park","2":"宠物王国","3":"Bark In The Park","4":"Bark In The Park","5":"Bark In The Park"}',
                    "game_code" => 'BARK_PARK_M4_V1_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Bark In The Park',
                    "external_game_id" => 'BARK_PARK_M4_V1_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Star Crystals","2":"星际水晶之谜","3":"Star Crystals","4":"Star Crystals","5":"Star Crystals"}',
                    "game_code" => 'STAR_CRYSTALS_M4_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Star Crystals',
                    "external_game_id" => 'STAR_CRYSTALS_M4_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Rise of The Empress","2":"女帝崛起","3":"Rise of The Empress","4":"Rise of The Empress","5":"Rise of The Empress"}',
                    "game_code" => 'ROTP_M4_V2_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Rise of The Empress',
                    "external_game_id" => 'ROTP_M4_V2_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Da Hong Bao","2":"大红包","3":"Da Hong Bao","4":"Da Hong Bao","5":"Da Hong Bao"}',
                    "game_code" => 'M4-0082;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Da Hong Bao',
                    "external_game_id" => 'M4-0082;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Single’s Day","2":"單身小時代","3":"Single’s Day","4":"Single’s Day","5":"Single’s Day"}',
                    "game_code" => 'M4-0079;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Single’s Day',
                    "external_game_id" => 'M4-0079;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Tree Of Life","2":"生命之树","3":"Tree Of Life","4":"Tree Of Life","5":"Tree Of Life"}',
                    "game_code" => 'TOL_M4_V2_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Tree Of Life',
                    "external_game_id" => 'TOL_M4_V2_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Lucky Dragon Boat","2":"开运龙舟","3":"Lucky Dragon Boat","4":"Lucky Dragon Boat","5":"Lucky Dragon Boat"}',
                    "game_code" => 'LUCKY_DRAGON_M4_V1_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Lucky Dragon Boat',
                    "external_game_id" => 'LUCKY_DRAGON_M4_V1_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Savanna King","2":"草原争霸战","3":"Savanna King","4":"Savanna King","5":"Savanna King"}',
                    "game_code" => 'SAVANAH_KING_96_M4_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Savanna King',
                    "external_game_id" => 'SAVANAH_KING_96_M4_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Pinata Bandidos","2":"荒野大盗皮纳塔","3":"Pinata Bandidos","4":"Pinata Bandidos","5":"Pinata Bandidos"}',
                    "game_code" => 'M4-0058;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Pinata Bandidos',
                    "external_game_id" => 'M4-0058;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Dragon’s Scroll ","2":"金龙卷","3":"Dragon’s Scroll ","4":"Dragon’s Scroll ","5":"Dragon’s Scroll "}',
                    "game_code" => 'DRAGON_SCROLL_V1_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Dragon’s Scroll ',
                    "external_game_id" => 'DRAGON_SCROLL_V1_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Dragon Slayers","2":"屠龙者","3":"Dragon Slayers","4":"Dragon Slayers","5":"Dragon Slayers"}',
                    "game_code" => 'DRAG_SLYER_M4_V2_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Dragon Slayers',
                    "external_game_id" => 'DRAG_SLYER_M4_V2_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Reindeer Wild Wins","2":"银雪驯鹿","3":"Reindeer Wild Wins","4":"Reindeer Wild Wins","5":"Reindeer Wild Wins"}',
                    "game_code" => 'REINDEER_WILDS_M4_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Reindeer Wild Wins',
                    "external_game_id" => 'REINDEER_WILDS_M4_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Red Panda Paradise","2":"熊猫乐园","3":"Red Panda Paradise","4":"Red Panda Paradise","5":"Red Panda Paradise"}',
                    "game_code" => 'WHITE_BUFFALO_M4_GAME2_V1_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Red Panda Paradise',
                    "external_game_id" => 'WHITE_BUFFALO_M4_GAME2_V1_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Living Luxurious","2":"奢华生活","3":"Living Luxurious","4":"Living Luxurious","5":"Living Luxurious"}',
                    "game_code" => 'WHITE_BUFFALO_M4_GAME1_V1_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Living Luxurious',
                    "external_game_id" => 'WHITE_BUFFALO_M4_GAME1_V1_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Vikings","2":"维京人传奇","3":"Vikings","4":"Vikings","5":"Vikings"}',
                    "game_code" => 'NECKER_ISLAND_GAME1_V1_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Vikings',
                    "external_game_id" => 'NECKER_ISLAND_GAME1_V1_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Tiger Temple","2":"金虎殿","3":"Tiger Temple","4":"Tiger Temple","5":"Tiger Temple"}',
                    "game_code" => 'M4-0076;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Tiger Temple',
                    "external_game_id" => 'M4-0076;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Rich Panda","2":"熊猫发财记","3":"Rich Panda","4":"Rich Panda","5":"Rich Panda"}',
                    "game_code" => 'RICH_PANDA_M4_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Rich Panda',
                    "external_game_id" => 'RICH_PANDA_M4_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Orion","2":"星际探索:猎户座","3":"Orion","4":"Orion","5":"Orion"}',
                    "game_code" => 'ORION_M4_V2_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Orion',
                    "external_game_id" => 'ORION_M4_V2_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Chang’e Goddess of the Moon","2":"仙女嫦娥","3":"Chang’e Goddess of the Moon","4":"Chang’e Goddess of the Moon","5":"Chang’e Goddess of the Moon"}',
                    "game_code" => 'M4-0066;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Chang’e Goddess of the Moon',
                    "external_game_id" => 'M4-0066;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Cai Shen’s Fortune","2":"财神888","3":"Cai Shen’s Fortune","4":"Cai Shen’s Fortune","5":"Cai Shen’s Fortune"}',
                    "game_code" => 'M4-0063;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Cai Shen’s Fortune',
                    "external_game_id" => 'M4-0063;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Jason’s Quest","2":"杰森探险记","3":"Jason’s Quest","4":"Jason’s Quest","5":"Jason’s Quest"}',
                    "game_code" => 'JASON_V2_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Jason’s Quest',
                    "external_game_id" => 'JASON_V2_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":" Attack of the Zombies ","2":"僵尸反击大战","3":" Attack of the Zombies ","4":" Attack of the Zombies ","5":" Attack of the Zombies "}',
                    "game_code" => 'ATTACK_OF_THE_ZOMBIES_RECORDER;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => ' Attack of the Zombies ',
                    "external_game_id" => 'ATTACK_OF_THE_ZOMBIES_RECORDER;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":" God of Cookery ","2":"食来运转","3":" God of Cookery ","4":" God of Cookery ","5":" God of Cookery "}',
                    "game_code" => 'M4-0083;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => ' God of Cookery ',
                    "external_game_id" => 'M4-0083;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1:" Year of the Dog","2":"食来运转","3:" Year of the Dog","4:" Year of the Dog","5:" Year of the Dog"}',
                    "game_code" => 'M4-0084;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Year of the Dog',
                    "external_game_id" => 'M4-0084;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Shanghai Nights","2":"夜上海","3":"Shanghai Nights","4":"Shanghai Nights","5":"Shanghai Nights"}',
                    "game_code" => 'M4-0085;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Shanghai Nights',
                    "external_game_id" => 'M4-0085;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Fortune Dragon","2":"金龍發","3":"Fortune Dragon","4":"Fortune Dragon","5":"Fortune Dragon"}',
                    "game_code" => 'M4-0088;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Fortune Dragon',
                    "external_game_id" => 'M4-0088;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Lion’s Fortune","2":"祥獅奪寶","3":"Lion’s Fortune","4":"Lion’s Fortune","5":"Lion’s Fortune"}',
                    "game_code" => 'M4-0092;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Lion’s Fortune',
                    "external_game_id" => 'M4-0092;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Flash Track","2":"激速衝鋒","3":"Flash Track","4":"Flash Track","5":"Flash Track"}',
                    "game_code" => 'M4-0095;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Flash Track',
                    "external_game_id" => 'M4-0095;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Bounty Hunter","2":"賞金獵人","3":"Bounty Hunter","4":"Bounty Hunter","5":"Bounty Hunter"}',
                    "game_code" => 'M4-0089;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Bounty Hunter',
                    "external_game_id" => 'M4-0089;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"World Cup","2":"熱血世界盃","3":"World Cup","4":"World Cup","5":"World Cup"}',
                    "game_code" => 'M4-0093;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'World Cup',
                    "external_game_id" => 'M4-0093;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Zombie Blackjack","2":"殭屍21點","3":"Zombie Blackjack","4":"Zombie Blackjack","5":"Zombie Blackjack"}',
                    "game_code" => 'M4-0091;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Zombie Blackjack',
                    "external_game_id" => 'M4-0091;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Savanna King Jackpot","2":"草原爭霸戰~ 彩金池豪華版","3":"Savanna King Jackpot","4":"Savanna King Jackpot","5":"Savanna King Jackpot"}',
                    "game_code" => 'M4-0087;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Savanna King Jackpot',
                    "external_game_id" => 'M4-0087;V:1',
            ],
            [
                    "game_platform_id" => $api_id,
                    "game_type_id" => $gameTypeCodeMaps[$game_type_code_slots],
                    "game_name" => '_json:{"1":"Tres Huevos","2":"寶蛋尋夢","3":"Tres Huevos","4":"Tres Huevos","5":"Tres Huevos"}',
                    "game_code" => 'M4-0096;V:1',
                    "status" => $db_true,
                    "flag_show_in_site" => $db_true,
                    "english_name" => 'Tres Huevos',
                    "external_game_id" => 'M4-0096;V:1',
            ],

            //===unknown======================================================================
            [
                'game_platform_id' => $api_id,
                'game_code' => 'unknown',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_unknown],
                'game_name' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                "english_name" => "Unknown",
                'external_game_id' => 'unknown',
                'status'=> $db_true,
                'flag_show_in_site'=>$db_false,
                'updated_at'=>$now,
            ],

        ];

        $this->load->model(['game_description_model']);

        $success=$this->game_description_model->syncGameDescription($game_descriptions);

        return $success;
    }

}
