<?php
trait game_description_cq9 {

    public function sync_game_description_cq9(){
        $api_id = CQ9_API;
        $this->sync_gamelist_cq9($api_id);
    }

    public function sync_gamelist_cq9($api_id){
		$cnt=0;
        $db_true = 1;
        $db_false = 0;
        $now = $this->utils->getNowForMysql();
        $game_type_code_arcade      = SYNC::TAG_CODE_ARCADE;
        $game_type_code_fishing_game = SYNC::TAG_CODE_FISHING_GAME;
        $game_type_code_slots       = SYNC::TAG_CODE_SLOT;
        $game_type_code_unknown     = SYNC::TAG_CODE_UNKNOWN_GAME;

        $game_types = [

             $game_type_code_arcade => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Arcade","2":"街机游戏","3":"Arcade","4":"Arcade","5":"Arcade"}',
                'game_type_lang' => '_json:{"1":"Arcade","2":"街机游戏","3":"Arcade","4":"Arcade","5":"Arcade"}',
                "game_type_code" => $game_type_code_arcade,
                'updated_at'=>$now,
                'game_tag_code' => SYNC::TAG_CODE_SLOT
            ],
           $game_type_code_fishing_game => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Fishing Game","2":"捕鱼王","3":"Fishing Game","4":"Fishing Game","5":"Fishing Game"}',
                'game_type_lang' => '_json:{"1":"Fishing Game","2":"捕鱼王","3":"Fishing Game","4":"Fishing Game","5":"Fishing Game"}',
                'game_type_code' => $game_type_code_fishing_game,
                'updated_at' => $now,
                'game_tag_code' => SYNC::TAG_CODE_FISHING_GAME
            ],
            $game_type_code_slots => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Slots","2":"老虎机","3":"Slots","4":"Slots","5":"Slots"}',
                'game_type_lang' => '_json:{"1":"Slots","2":"老虎机","3":"Slots","4":"Slots","5":"Slots"}',
                "game_type_code" => $game_type_code_slots,
                'updated_at'=>$now,
                'game_tag_code' => SYNC::TAG_CODE_SLOT
            ],
            $game_type_code_unknown => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                'game_type_lang' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                "game_type_code" => $game_type_code_unknown,
                'updated_at'=>$now,
                'game_tag_code' => SYNC::TAG_CODE_UNKNOWN_GAME
            ],
 
        ];

        $this->load->model(['game_type_model']);
        $gameTypeCodeMaps=$this->game_type_model->syncGameTypes($game_types);
        echo "<pre>";
        $this->utils->debug_log('gameTypeCodeMaps', $gameTypeCodeMaps);

		$game_descriptions = array(
			#===================================== Desktop games list only =========================
            
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_unknown],
                'game_name' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                'game_code' => 'unknown',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_false,
                'flag_show_in_site' => $db_false,
                'html_five_enabled' => $db_false,
                'english_name' => 'Unknown',
                'external_game_id' => 'unknown',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_false,
                'enabled_on_ios' => $db_false,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Jump High","2":"跳高高","3":"Jump High","4":"Jump High","5":"Jump High"}',
                'game_code' => '52',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Jump High',
                'external_game_id' => '52',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"RaveJump","2":"跳起来","3":"RaveJump","4":"RaveJump","5":"RaveJump"}',
                'game_code' => '7',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'RaveJump',
                'external_game_id' => '7',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"RaveJump2","2":"跳起来2","3":"RaveJump2","4":"RaveJump2","5":"RaveJump2"}',
                'game_code' => '24',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'RaveJump2',
                'external_game_id' => '24',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"LuckyBat","2":"五福临门","3":"LuckyBat","4":"LuckyBat","5":"LuckyBat"}',
                'game_code' => '10',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'LuckyBat',
                'external_game_id' => '10',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"God of War","2":"武圣","3":"God of War","4":"God of War","5":"God of War"}',
                'game_code' => '31',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'God of War',
                'external_game_id' => '31',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Fire Chibi","2":"火烧连环船","3":"Fire Chibi","4":"Fire Chibi","5":"Fire Chibi"}',
                'game_code' => '33',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Fire Chibi',
                'external_game_id' => '33',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Super5","2":"五行","3":"Super5","4":"Super5","5":"Super5"}',
                'game_code' => '16',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Super5',
                'external_game_id' => '16',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"GuGuGu","2":"金鸡报喜","3":"GuGuGu","4":"GuGuGu","5":"GuGuGu"}',
                'game_code' => '15',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'GuGuGu',
                'external_game_id' => '15',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Zeus","2":"宙斯","3":"Zeus","4":"Zeus","5":"Zeus"}',
                'game_code' => '64',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Zeus',
                'external_game_id' => '64',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Fire Queen","2":"火之女王","3":"Fire Queen","4":"Fire Queen","5":"Fire Queen"}',
                'game_code' => '83',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Fire Queen',
                'external_game_id' => '83',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Wild Magic","2":"奇幻魔術","3":"Wild Magic","4":"Wild Magic","5":"Wild Magic"}',
                'game_code' => '84',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Wild Magic',
                'external_game_id' => '84',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"GuGuGu2","2":"金鸡报喜2","3":"GuGuGu2","4":"GuGuGu2","5":"GuGuGu2"}',
                'game_code' => '58',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'GuGuGu2',
                'external_game_id' => '58',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Dragon OnHeart","2":"魔龙传奇","3":"Dragon OnHeart","4":"Dragon OnHeart","5":"Dragon OnHeart"}',
                'game_code' => '55',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Dragon OnHeart',
                'external_game_id' => '55',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"TreasureIsland","2":"金银岛","3":"TreasureIsland","4":"TreasureIsland","5":"TreasureIsland"}',
                'game_code' => '81',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'TreasureIsland',
                'external_game_id' => '81',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"WuKong&Peaches","2":"悟空偷桃","3":"WuKong&Peaches","4":"WuKong&Peaches","5":"WuKong&Peaches"}',
                'game_code' => '68',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'WuKong&Peaches',
                'external_game_id' => '68',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"HappyRichYear","2":"好运年年","3":"HappyRichYear","4":"HappyRichYear","5":"HappyRichYear"}',
                'game_code' => '72',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'HappyRichYear',
                'external_game_id' => '72',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"TreasureBowl","2":"聚宝盆","3":"TreasureBowl","4":"TreasureBowl","5":"TreasureBowl"}',
                'game_code' => '74',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'TreasureBowl',
                'external_game_id' => '74',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"RedPhoenix","2":"火凤凰","3":"RedPhoenix","4":"RedPhoenix","5":"RedPhoenix"}',
                'game_code' => '77',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'RedPhoenix',
                'external_game_id' => '77',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Apollo","2":"阿波罗","3":"Apollo","4":"Apollo","5":"Apollo"}',
                'game_code' => '78',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Apollo',
                'external_game_id' => '78',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Poseidon","2":"传奇海神","3":"Poseidon","4":"Poseidon","5":"Poseidon"}',
                'game_code' => '80',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Poseidon',
                'external_game_id' => '80',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Good Forture","2":"鸿福齐天","3":"Good Forture","4":"Good Forture","5":"Good Forture"}',
                'game_code' => '50',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Good Forture',
                'external_game_id' => '50',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Crazy NuoZha","2":"疯狂哪咤","3":"Crazy NuoZha","4":"Crazy NuoZha","5":"Crazy NuoZha"}',
                'game_code' => '35',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Crazy NuoZha',
                'external_game_id' => '35',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"FruitKing","2":"钻石水果王","3":"FruitKing","4":"FruitKing","5":"FruitKing"}',
                'game_code' => '1',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'FruitKing',
                'external_game_id' => '1',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"ZhongKui","2":"钟馗运财","3":"ZhongKui","4":"ZhongKui","5":"ZhongKui"}',
                'game_code' => '9',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'ZhongKui',
                'external_game_id' => '9',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"WaterWorld","2":"水世界","3":"WaterWorld","4":"WaterWorld","5":"WaterWorld"}',
                'game_code' => '29',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'WaterWorld',
                'external_game_id' => '29',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"WonWonWon","2":"旺旺旺","3":"WonWonWon","4":"WonWonWon","5":"WonWonWon"}',
                'game_code' => '76',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'WonWonWon',
                'external_game_id' => '76',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Dracula","2":"黯夜公爵","3":"Dracula","4":"Dracula","5":"Dracula"}',
                'game_code' => '56',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Dracula',
                'external_game_id' => '56',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"YuanBao","2":"金元宝","3":"YuanBao","4":"YuanBao","5":"YuanBao"}',
                'game_code' => '23',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'YuanBao',
                'external_game_id' => '23',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"WanBaoDino","2":"万饱龙","3":"WanBaoDino","4":"WanBaoDino","5":"WanBaoDino"}',
                'game_code' => '70',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'WanBaoDino',
                'external_game_id' => '70',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"FaChaiShen","2":"发财神","3":"FaChaiShen","4":"FaChaiShen","5":"FaChaiShen"}',
                'game_code' => '69',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'FaChaiShen',
                'external_game_id' => '69',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Wolf Moon","2":"狼月","3":"Wolf Moon","4":"Wolf Moon","5":"Wolf Moon"}',
                'game_code' => '46',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Wolf Moon',
                'external_game_id' => '46',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"FruitKing2","2":"豪华水果王","3":"FruitKing2","4":"FruitKing2","5":"FruitKing2"}',
                'game_code' => '44',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'FruitKing2',
                'external_game_id' => '44',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Apsaras","2":"飞天","3":"Apsaras","4":"Apsaras","5":"Apsaras"}',
                'game_code' => '39',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Apsaras',
                'external_game_id' => '39',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"The Ghouls","2":"寻龙诀","3":"The Ghouls","4":"The Ghouls","5":"The Ghouls"}',
                'game_code' => '63',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'The Ghouls',
                'external_game_id' => '63',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"HotSpin","2":"风火轮","3":"HotSpin","4":"HotSpin","5":"HotSpin"}',
                'game_code' => '19',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'HotSpin',
                'external_game_id' => '19',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"The Beast War","2":"神兽争霸","3":"The Beast War","4":"The Beast War","5":"The Beast War"}',
                'game_code' => '57',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'The Beast War',
                'external_game_id' => '57',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Funny Alpaca","2":"火草泥马","3":"Funny Alpaca","4":"Funny Alpaca","5":"Funny Alpaca"}',
                'game_code' => '54',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Funny Alpaca',
                'external_game_id' => '54',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Golden Egg","2":"赚金蛋","3":"Golden Egg","4":"Golden Egg","5":"Golden Egg"}',
                'game_code' => '67',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Golden Egg',
                'external_game_id' => '67',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"All Wilds","2":"舞力全开","3":"All Wilds","4":"All Wilds","5":"All Wilds"}',
                'game_code' => '38',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'All Wilds',
                'external_game_id' => '38',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"SoSweet","2":"甜蜜蜜","3":"SoSweet","4":"SoSweet","5":"SoSweet"}',
                'game_code' => '8',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'SoSweet',
                'external_game_id' => '8',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Gong He Xin Xi","2":"恭贺新禧","3":"Gong He Xin Xi","4":"Gong He Xin Xi","5":"Gong He Xin Xi"}',
                'game_code' => '43',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Gong He Xin Xi',
                'external_game_id' => '43',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Loneyly Planet","2":"寂寞星球","3":"Loneyly Planet","4":"Loneyly Planet","5":"Loneyly Planet"}',
                'game_code' => '49',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Loneyly Planet',
                'external_game_id' => '49',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Lotus","2":"莲","3":"Lotus","4":"Lotus","5":"Lotus"}',
                'game_code' => '48',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Lotus',
                'external_game_id' => '48',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"777","2":"777","3":"777","4":"777","5":"777"}',
                'game_code' => '26',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => '777',
                'external_game_id' => '26',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Love Night","2":"来电99","3":"Love Night","4":"Love Night","5":"Love Night"}',
                'game_code' => '53',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Love Night',
                'external_game_id' => '53',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"TreasureHouse","2":"金玉满堂","3":"TreasureHouse","4":"TreasureHouse","5":"TreasureHouse"}',
                'game_code' => '12',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'TreasureHouse',
                'external_game_id' => '12',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"SuperDiamonds","2":"非常钻","3":"SuperDiamonds","4":"SuperDiamonds","5":"SuperDiamonds"}',
                'game_code' => '62',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'SuperDiamonds',
                'external_game_id' => '62',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"1945","2":"1945","3":"1945","4":"1945","5":"1945"}',
                'game_code' => '6',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => '1945',
                'external_game_id' => '6',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"SummerMood","2":"夏日猩情","3":"SummerMood","4":"SummerMood","5":"SummerMood"}',
                'game_code' => '59',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'SummerMood',
                'external_game_id' => '59',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Mr.Rich","2":"金大款","3":"Mr.Rich","4":"Mr.Rich","5":"Mr.Rich"}',
                'game_code' => '5',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Mr.Rich',
                'external_game_id' => '5',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Fire777","2":"火爆777","3":"Fire777","4":"Fire777","5":"Fire777"}',
                'game_code' => '66',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Fire777',
                'external_game_id' => '66',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"GodOfChess","2":"棋圣","3":"GodOfChess","4":"GodOfChess","5":"GodOfChess"}',
                'game_code' => '2',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'GodOfChess',
                'external_game_id' => '2',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Detective Dee","2":"通天神探狄仁杰","3":"Detective Dee","4":"Detective Dee","5":"Detective Dee"}',
                'game_code' => '32',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Detective Dee',
                'external_game_id' => '32',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"GreatLion","2":"祥狮献瑞","3":"GreatLion","4":"GreatLion","5":"GreatLion"}',
                'game_code' => '17',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'GreatLion',
                'external_game_id' => '17',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Warrior legend","2":"三国序","3":"Warrior legend","4":"Warrior legend","5":"Warrior legend"}',
                'game_code' => '30',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Warrior legend',
                'external_game_id' => '30',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"WildTarzan","2":"森林泰后","3":"WildTarzan","4":"WildTarzan","5":"WildTarzan"}',
                'game_code' => '4',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'WildTarzan',
                'external_game_id' => '4',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Darts Champion","2":"镖王争霸","3":"Darts Champion","4":"Darts Champion","5":"Darts Champion"}',
                'game_code' => '40',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Darts Champion',
                'external_game_id' => '40',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Ecstatic Circus","2":"嗨爆大马戏","3":"Ecstatic Circus","4":"Ecstatic Circus","5":"Ecstatic Circus"}',
                'game_code' => '51',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Ecstatic Circus',
                'external_game_id' => '51',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"VampireKiss","2":"血之吻","3":"VampireKiss","4":"VampireKiss","5":"VampireKiss"}',
                'game_code' => '3',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'VampireKiss',
                'external_game_id' => '3',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Pub Tycoon","2":"夜店大亨","3":"Pub Tycoon","4":"Pub Tycoon","5":"Pub Tycoon"}',
                'game_code' => '36',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Pub Tycoon',
                'external_game_id' => '36',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"God of Cookery","2":"食神","3":"God of Cookery","4":"God of Cookery","5":"God of Cookery"}',
                'game_code' => '28',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'God of Cookery',
                'external_game_id' => '28',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"PokerSLOT","2":"扑克拉霸","3":"PokerSLOT","4":"PokerSLOT","5":"PokerSLOT"}',
                'game_code' => '25',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'PokerSLOT',
                'external_game_id' => '25',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Super8","2":"超级发","3":"Super8","4":"Super8","5":"Super8"}',
                'game_code' => '45',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Super8',
                'external_game_id' => '45',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"MahjongKing","2":"雀王","3":"MahjongKing","4":"MahjongKing","5":"MahjongKing"}',
                'game_code' => '18',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'MahjongKing',
                'external_game_id' => '18',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Magic World","2":"魔法世界","3":"Magic World","4":"Magic World","5":"Magic World"}',
                'game_code' => '27',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Magic World',
                'external_game_id' => '27',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Water Balloons","2":"水球大战","3":"Water Balloons","4":"Water Balloons","5":"Water Balloons"}',
                'game_code' => '41',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Water Balloons',
                'external_game_id' => '41',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"888","2":"发发发","3":"888","4":"888","5":"888"}',
                'game_code' => '20',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => '888',
                'external_game_id' => '20',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Wonderland2","2":"梦游仙境2","3":"Wonderland2","4":"Wonderland2","5":"Wonderland2"}',
                'game_code' => '11',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Wonderland2',
                'external_game_id' => '11',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Sherlock Holmes","2":"福尔摩斯","3":"Sherlock Holmes","4":"Sherlock Holmes","5":"Sherlock Holmes"}',
                'game_code' => '42',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Sherlock Holmes',
                'external_game_id' => '42',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Gophers War","2":"地鼠战役","3":"Gophers War","4":"Gophers War","5":"Gophers War"}',
                'game_code' => '34',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Gophers War',
                'external_game_id' => '34',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"SakuraLegend","2":"樱花妹子","3":"SakuraLegend","4":"SakuraLegend","5":"SakuraLegend"}',
                'game_code' => '13',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'SakuraLegend',
                'external_game_id' => '13',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"RichWitch","2":"绝赢巫师","3":"RichWitch","4":"RichWitch","5":"RichWitch"}',
                'game_code' => '14',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'RichWitch',
                'external_game_id' => '14',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"MonkeyOfficeLegend","2":"庶务西游二课","3":"MonkeyOfficeLegend","4":"MonkeyOfficeLegend","5":"MonkeyOfficeLegend"}',
                'game_code' => '22',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'MonkeyOfficeLegend',
                'external_game_id' => '22',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Pharaoh’s Gold","2":"法老宝藏","3":"Pharaoh’s Gold","4":"Pharaoh’s Gold","5":"Pharaoh’s Gold"}',
                'game_code' => '47',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Pharaoh’s Gold',
                'external_game_id' => '47',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"BigWolf","2":"野狼传说","3":"BigWolf","4":"BigWolf","5":"BigWolf"}',
                'game_code' => '21',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'BigWolf',
                'external_game_id' => '21',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_fishing_game],
                'game_name' => '_json:{"1":"Paradise","2":"皇金渔场","3":"Paradise","4":"Paradise","5":"Paradise"}',
                'game_code' => 'AB1',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Paradise',
                'external_game_id' => 'AB1',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_arcade],
                'game_name' => '_json:{"1":"The Monky King","2":"战西游","3":"The Monky King","4":"The Monky King","5":"The Monky King"}',
                'game_code' => 'AA301',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'The Monky King',
                'external_game_id' => 'AA301',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_arcade],
                'game_name' => '_json:{"1":"Jungle Party","2":"丛林舞会","3":"Jungle Party","4":"Jungle Party","5":"Jungle Party"}',
                'game_code' => '60',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Jungle Party',
                'external_game_id' => '60',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_arcade],
                'game_name' => '_json:{"1":"Mr.Been","2":"天天吃豆","3":"Mr.Been","4":"Mr.Been","5":"Mr.Been"}',
                'game_code' => '61',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Mr.Been',
                'external_game_id' => '61',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],


        );

		$this->load->model(['game_description_model']);

        $success=$this->game_description_model->syncGameDescription($game_descriptions);

        return $success;
	}

}
