<?php
trait game_description_agbbin {

    #use bbin game description
	// public function sync_game_description_agbbin(){

	// 	// $cnt=0;

	// 	$success=true;

	// 	$api_id=AGBBIN_API;
	// 	$db_true=1;
	// 	$db_false=0;
	// 	$now=$this->utils->getNowForMysql();

	// 	$game_type_code_sports='1';
	// 	$game_type_code_live='3';
	// 	$game_type_code_slots='5';
	// 	$game_type_code_lottery='12';
	// 	$game_type_code_tip='99';
	// 	$game_type_code_unknown='unknown';

	// 	//sync game type first
	// 	//game_type_code from bbin document
	// 	//use game_type_code as key
	// 	$game_types = [
	// 		$game_type_code_sports => [
	// 			'game_platform_id' => $api_id,
	// 			'game_type' => '_json:{"1":"BB Sports","2":"BB 体育"}',
	// 		],
	// 		$game_type_code_live => [
	// 			'game_platform_id' => $api_id,
	// 			'game_type' => '_json:{"1":"BB Live Dealer","2":"BB 视讯"}',
	// 		],
	// 		$game_type_code_slots => [
	// 			'game_platform_id' => $api_id,
	// 			'game_type' => '_json:{"1":"BB Casino","2":"BB 电子"}',
	// 		],
	// 		$game_type_code_lottery => [
	// 			'game_platform_id' => $api_id,
	// 			'game_type' => '_json:{"1":"BB Lottery","2":"BB 彩票"}',
	// 		],
	// 		$game_type_code_tip => [
	// 			'game_platform_id' => $api_id,
	// 			'game_type' => '_json:{"1":"BB Tip","2":"BB 小费"}',
	// 		],
	// 		$game_type_code_unknown=> [
	// 			'game_platform_id' => $api_id,
	// 			'game_type' => '_json:{"1":"Unknown","2":"不明类型"}',
	// 		]

	// 	];

	// 	$this->load->model(['game_type_model']);
	// 	$gameTypeCodeMaps=$this->game_type_model->syncGameTypes($game_types);

	// 	$this->utils->debug_log('gameTypeCodeMaps', $gameTypeCodeMaps);

	// 	if(empty($gameTypeCodeMaps)){
	// 		return false;
	// 	}

	// 	$game_descriptions = [

	// 		//===sports===================================
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'FT',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
	// 			'game_name' => '_json:{"1":"Football","2":"足球"}',
	// 			"english_name" => "Football",
	// 			'external_game_id' => 'FT',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'BK',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
	// 			'game_name' => '_json:{"1":"Basketball","2":"籃球"}',
	// 			"english_name" => "Basketball",
	// 			'external_game_id' => 'BK',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'FB',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
	// 			'game_name' => '_json:{"1":"American Football","2":"美式足球"}',
	// 			"english_name" => "American Football",
	// 			'external_game_id' => 'FB',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'IH',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
	// 			'game_name' => '_json:{"1":"IceHockey","2":"冰球"}',
	// 			"english_name" => "IceHockey",
	// 			'external_game_id' => 'IH',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'BS',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
	// 			'game_name' => '_json:{"1":"Baseball","2":"棒球"}',
	// 			"english_name" => "Baseball",
	// 			'external_game_id' => 'BS',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'TN',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
	// 			'game_name' => '_json:{"1":"Tennis","2":"網球"}',
	// 			"english_name" => "Tennis",
	// 			'external_game_id' => 'TN',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'F1',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
	// 			'game_name' => '_json:{"1":"Other","2":"其他"}',
	// 			"english_name" => "Other",
	// 			'external_game_id' => 'F1',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'SP',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
	// 			'game_name' => '_json:{"1":"Outright","2":"冠軍賽"}',
	// 			"english_name" => "Outright",
	// 			'external_game_id' => 'SP',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'CB',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
	// 			'game_name' => '_json:{"1":"Combo Parlay","2":"混合過關"}',
	// 			"english_name" => "Combo Parlay",
	// 			'external_game_id' => 'CB',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],

	// 		//===live===================================
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '3001',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_live],
	// 			'game_name' => '_json:{"1":"Baccarat","2":"百家樂"}',
	// 			"english_name" => "Baccarat",
	// 			'external_game_id' => '3001',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '3002',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_live],
	// 			'game_name' => '_json:{"1":"Mahjong Tiles","2":"二八槓"}',
	// 			"english_name" => "Mahjong Tiles",
	// 			'external_game_id' => '3002',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '3003',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_live],
	// 			'game_name' => '_json:{"1":"Dragon Tiger","2":"龍虎鬥"}',
	// 			"english_name" => "Dragon Tiger",
	// 			'external_game_id' => '3003',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '3005',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_live],
	// 			'game_name' => '_json:{"1":"3 Face","2":"三公"}',
	// 			"english_name" => "3 Face",
	// 			'external_game_id' => '3005',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '3006',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_live],
	// 			'game_name' => '_json:{"1":"Wenzhou Pai Gow","2":"溫州牌九"}',
	// 			"english_name" => "Wenzhou Pai Gow",
	// 			'external_game_id' => '3006',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '3007',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_live],
	// 			'game_name' => '_json:{"1":"Roulette","2":"輪盤"}',
	// 			"english_name" => "Roulette",
	// 			'external_game_id' => '3007',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '3008',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_live],
	// 			'game_name' => '_json:{"1":"Sic Bo","2":"骰寶"}',
	// 			"english_name" => "Sic Bo",
	// 			'external_game_id' => '3008',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '3010',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_live],
	// 			'game_name' => '_json:{"1":"Texas Hold em","2":"德州撲克"}',
	// 			"english_name" => "Texas Hold em",
	// 			'external_game_id' => '3010',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '3011',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_live],
	// 			'game_name' => '_json:{"1":"Se Die","2":"色碟"}',
	// 			"english_name" => "Se Die",
	// 			'external_game_id' => '3011',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '3012',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_live],
	// 			'game_name' => '_json:{"1":"Bull Bull","2":"牛牛"}',
	// 			"english_name" => "Bull Bull",
	// 			'external_game_id' => '3012',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '3014',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_live],
	// 			'game_name' => '_json:{"1":"Unlimited Blackjack","2":"無限21點"}',
	// 			"english_name" => "Unlimited Blackjack",
	// 			'external_game_id' => '3014',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '3015',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_live],
	// 			'game_name' => '_json:{"1":"Fan Tan","2":"番攤"}',
	// 			"english_name" => "Fan Tan",
	// 			'external_game_id' => '3015',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],

	// 		//===slots======================================================================
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5005',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Alien War","2":"惑星戰記"}',
	// 			"english_name" => "Alien War",
	// 			'external_game_id' => '5005',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5006',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Staronic","2":"Staronic"}',
	// 			"english_name" => "Staronic",
	// 			'external_game_id' => '5006',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5007',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Fruits Boom","2":"激爆水果盤"}',
	// 			"english_name" => "Fruits Boom",
	// 			'external_game_id' => '5007',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5008',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Monkey GoGo","2":"猴子爬樹"}',
	// 			"english_name" => "Monkey GoGo",
	// 			'external_game_id' => '5008',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5009',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"King Kong","2":"金剛爬樓"}',
	// 			"english_name" => "King Kong",
	// 			'external_game_id' => '5009',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5010',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Galaxy II","2":"外星戰記"}',
	// 			"english_name" => "Galaxy II",
	// 			'external_game_id' => '5010',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5012',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Galaxy","2":"外星爭霸"}',
	// 			"english_name" => "Galaxy",
	// 			'external_game_id' => '5012',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5013',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Classic","2":"傳統"}',
	// 			"english_name" => "Classic",
	// 			'external_game_id' => '5013',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5014',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Jungle","2":"叢林"}',
	// 			"english_name" => "Jungle",
	// 			'external_game_id' => '5014',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5015',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"FIFA2010","2":"FIFA2010"}',
	// 			"english_name" => "FIFA2010",
	// 			'external_game_id' => '5015',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5016',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Prehistoric Jungle","2":"史前叢林冒險"}',
	// 			"english_name" => "Prehistoric Jungle",
	// 			'external_game_id' => '5016',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5017',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Star Wars","2":"星際大戰"}',
	// 			"english_name" => "Star Wars",
	// 			'external_game_id' => '5017',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5020',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Tropical Fruit","2":"熱帶風情"}',
	// 			"english_name" => "Tropical Fruit",
	// 			'external_game_id' => '5020',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5026',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"London 2012","2":"2012 倫敦奧運"}',
	// 			"english_name" => "London 2012",
	// 			'external_game_id' => '5026',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5028',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Moon Festival Party","2":"中秋月光派對"}',
	// 			"english_name" => "Moon Festival Party",
	// 			'external_game_id' => '5028',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5029',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Xmas Party","2":"聖誕派對"}',
	// 			"english_name" => "Xmas Party",
	// 			'external_game_id' => '5029',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5030',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Chinese Mammon","2":"幸運財神"}',
	// 			"english_name" => "Chinese Mammon",
	// 			'external_game_id' => '5030',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5034',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Joker Poker","2":"王牌 5PK"}',
	// 			"english_name" => "Joker Poker",
	// 			'external_game_id' => '5034',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5035',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Caribbean Poker","2":"加勒比撲克"}',
	// 			"english_name" => "Caribbean Poker",
	// 			'external_game_id' => '5035',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5039',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Fish-Prawn-Crab Dice","2":"魚蝦蟹"}',
	// 			"english_name" => "Fish-Prawn-Crab Dice",
	// 			'external_game_id' => '5039',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5040',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Deuces Wild","2":"百搭二王"}',
	// 			"english_name" => "Deuces Wild",
	// 			'external_game_id' => '5040',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5041',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"7PK","2":"7PK"}',
	// 			'english_name' => "7PK",
	// 			'external_game_id' => '5041',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5042',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Lost Battlefield","2":"Lost Battlefield"}',
	// 			'english_name' => "Lost Battlefield",
	// 			'external_game_id' => '5042',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5043',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Diamond Fruits","2":"Diamond Fruits"}',
	// 			'english_name' => "Diamond Fruits",
	// 			'external_game_id' => '5043',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5044',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"STAR 97II","2":"STAR 97II"}',
	// 			'english_name' => "STAR 97II",
	// 			'external_game_id' => '5044',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5048',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Spy Crisis","2":"Spy Crisis"}',
	// 			'english_name' => "Spy Crisis",
	// 			'external_game_id' => '5048',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5049',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Sex And Zen","2":"Sex And Zen"}',
	// 			'english_name' => "Sex And Zen",
	// 			'external_game_id' => '5049',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5057',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Star97","2":"Star97"}',
	// 			'english_name' => "Star97",
	// 			'external_game_id' => '5057',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5058',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Crazy Fruit","2":"Crazy Fruit"}',
	// 			'english_name' => "Crazy Fruit",
	// 			'external_game_id' => '5058',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5060',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Fantastic Animals 5th","2":"Fantastic Animals 5th"}',
	// 			'english_name' => "Fantastic Animals 5th",
	// 			'external_game_id' => '5060',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5061',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Super 7","2":"Super 7"}',
	// 			'english_name' => "Super 7",
	// 			'external_game_id' => '5061',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5062',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Dragon Must Die","2":"Dragon Must Die"}',
	// 			'english_name' => "Dragon Must Die",
	// 			'external_game_id' => '5062',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5063',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Slot Cool Fruit","2":"Slot Cool Fruit"}',
	// 			'english_name' => "Slot Cool Fruit",
	// 			'external_game_id' => '5063',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5064',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Slot Poker","2":"Slot Poker"}',
	// 			'english_name' => "Slot Poker",
	// 			'external_game_id' => '5064',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5065',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Slot Mahjong Ball","2":"Slot Mahjong Ball"}',
	// 			'english_name' => "Slot Mahjong Ball",
	// 			'external_game_id' => '5065',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5066',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Slot Soccer","2":"Slot Soccer"}',
	// 			'english_name' => "Slot Soccer",
	// 			'external_game_id' => '5066',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5067',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"A Chinese Odyssey","2":"A Chinese Odyssey"}',
	// 			'english_name' => "A Chinese Odyssey",
	// 			'external_game_id' => '5067',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5068',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Kuso Circus","2":"Kuso Circus"}',
	// 			'english_name' => "Kuso Circus",
	// 			'external_game_id' => '5068',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5070',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Golden Wheel","2":"Golden Wheel"}',
	// 			'english_name' => "Golden Wheel",
	// 			'external_game_id' => '5070',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5073',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"BaccaratWheel","2":"BaccaratWheel"}',
	// 			'english_name' => "BaccaratWheel",
	// 			'external_game_id' => '5073',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5076',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Lucky Number","2":"Lucky Number"}',
	// 			'english_name' => "Lucky Number",
	// 			'external_game_id' => '5076',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5077',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Fruit","2":"Fruit"}',
	// 			'english_name' => "Fruit",
	// 			'external_game_id' => '5077',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5078',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Chess Wheel","2":"Chess Wheel"}',
	// 			'english_name' => "Chess Wheel",
	// 			'external_game_id' => '5078',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5079',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"3D Lucky Number","2":"3D Lucky Number"}',
	// 			'english_name' => "3D Lucky Number",
	// 			'external_game_id' => '5079',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5080',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Lottery Wheel","2":"Lottery Wheel"}',
	// 			'english_name' => "Lottery Wheel",
	// 			'external_game_id' => '5080',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5083',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Guess Train","2":"Guess Train"}',
	// 			'english_name' => "Guess Train",
	// 			'external_game_id' => '5083',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5084',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Monster Legend","2":"Monster Legend"}',
	// 			'english_name' => "Monster Legend",
	// 			'external_game_id' => '5084',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5088',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Casino War","2":"Casino War"}',
	// 			'english_name' => "Casino War",
	// 			'external_game_id' => '5088',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5089',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Red Dog","2":"Red Dog"}',
	// 			'english_name' => "Red Dog",
	// 			'external_game_id' => '5089',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5091',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Dynasty Warlord","2":"Dynasty Warlord"}',
	// 			'english_name' => "Dynasty Warlord",
	// 			'external_game_id' => '5091',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5092',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"The Legend and the Hero","2":"The Legend and the Hero"}',
	// 			'english_name' => "The Legend and the Hero",
	// 			'external_game_id' => '5092',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5093',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Jin Ping Mai","2":"Jin Ping Mai"}',
	// 			'english_name' => "Jin Ping Mai",
	// 			'external_game_id' => '5093',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5094',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Jin Ping Mai 2","2":"Jin Ping Mai 2"}',
	// 			'english_name' => "Jin Ping Mai 2",
	// 			'external_game_id' => '5094',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5095',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Cock Fighting","2":"Cock Fighting"}',
	// 			'english_name' => "Cock Fighting",
	// 			'external_game_id' => '5095',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5105',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"European Roulette","2":"European Roulette"}',
	// 			'english_name' => "European Roulette",
	// 			'external_game_id' => '5105',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5106',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"THREE KINGDOMS","2":"THREE KINGDOMS"}',
	// 			'english_name' => "THREE KINGDOMS",
	// 			'external_game_id' => '5106',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5107',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"American Roulette","2":"American Roulette"}',
	// 			'english_name' => "American Roulette",
	// 			'external_game_id' => '5107',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5108',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Jackpot Roulette","2":"Jackpot Roulette"}',
	// 			'english_name' => "Jackpot Roulette",
	// 			'external_game_id' => '5108',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5109',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"French Roulette","2":"French Roulette"}',
	// 			'english_name' => "French Roulette",
	// 			'external_game_id' => '5109',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5115',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Classic BlackJack","2":"Classic BlackJack"}',
	// 			'english_name' => "Classic BlackJack",
	// 			'external_game_id' => '5115',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5116',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Spanish BlackJack","2":"Spanish BlackJack"}',
	// 			'english_name' => "Spanish BlackJack",
	// 			'external_game_id' => '5116',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5117',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Vegas BlackJack","2":"Vegas BlackJack"}',
	// 			'english_name' => "Vegas BlackJack",
	// 			'external_game_id' => '5117',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5118',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Bonus BlackJack","2":"Bonus BlackJack"}',
	// 			'english_name' => "Bonus BlackJack",
	// 			'external_game_id' => '5118',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5131',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Royal Texas Hold’em","2":"Royal Texas Hold’em"}',
	// 			'english_name' => "Royal Texas Hold’em",
	// 			'external_game_id' => '5131',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5201',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Flaming Mountain","2":"Flaming Mountain"}',
	// 			'english_name' => "Flaming Mountain",
	// 			'external_game_id' => '5201',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5202',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Pandora’s Box","2":"Pandora’s Box"}',
	// 			'english_name' => "Pandora’s Box",
	// 			'external_game_id' => '5202',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5203',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Forever Love","2":"Forever Love"}',
	// 			'english_name' => "Forever Love",
	// 			'external_game_id' => '5203',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5204',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"2014 FIFA","2":"2014 FIFA"}',
	// 			'english_name' => "2014 FIFA",
	// 			'external_game_id' => '5204',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5402',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Let’s go Night-market !","2":"Let’s go Night-market !"}',
	// 			'english_name' => "Let’s go Night-market !",
	// 			'external_game_id' => '5402',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5404',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Beach Volleyball","2":"Beach Volleyball"}',
	// 			'english_name' => "Beach Volleyball",
	// 			'external_game_id' => '5404',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5406',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Starship27","2":"Starship27"}',
	// 			'english_name' => "Starship27",
	// 			'external_game_id' => '5406',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5407',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Don´t call me Little Red","2":"Don´t call me Little Red"}',
	// 			'english_name' => "Don´t call me Little Red",
	// 			'external_game_id' => '5407',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5601',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Adventure of Mystical Land","2":"Adventure of Mystical Land"}',
	// 			'english_name' => "Adventure of Mystical Land",
	// 			'external_game_id' => '5601',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5701',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"LinkGem","2":"LinkGem"}',
	// 			'english_name' => "LinkGem",
	// 			'external_game_id' => '5701',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5703',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"I Am Rich","2":"I Am Rich"}',
	// 			'english_name' => "I Am Rich",
	// 			'external_game_id' => '5703',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5704',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Bull Fight","2":"Bull Fight"}',
	// 			'english_name' => "Bull Fight",
	// 			'external_game_id' => '5704',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5705',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Treasure Pot","2":"Treasure Pot"}',
	// 			'english_name' => "Treasure Pot",
	// 			'external_game_id' => '5705',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5706',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Chocolate Passion","2":"Chocolate Passion"}',
	// 			'english_name' => "Chocolate Passion",
	// 			'external_game_id' => '5706',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5707',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"GOLDEN JAGUAR","2":"GOLDEN JAGUAR"}',
	// 			'english_name' => "GOLDEN JAGUAR",
	// 			'external_game_id' => '5707',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5801',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Dolphin Reef","2":"Dolphin Reef"}',
	// 			'english_name' => "Dolphin Reef",
	// 			'external_game_id' => '5801',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5802',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Achilles","2":"Achilles"}',
	// 			'english_name' => "Achilles",
	// 			'external_game_id' => '5802',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5803',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Aztec’s Treasure","2":"Aztec’s Treasure"}',
	// 			'english_name' => "Aztec’s Treasure",
	// 			'external_game_id' => '5803',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5804',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Big Shot","2":"Big Shot"}',
	// 			'english_name' => "Big Shot",
	// 			'external_game_id' => '5804',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5805',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Caesar’s Empire","2":"Caesar’s Empire"}',
	// 			'english_name' => "Caesar’s Empire",
	// 			'external_game_id' => '5805',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5806',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Enchanced Garden","2":"Enchanced Garden"}',
	// 			'english_name' => "Enchanced Garden",
	// 			'external_game_id' => '5806',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5808',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Ronin","2":"Ronin"}',
	// 			'english_name' => "Ronin",
	// 			'external_game_id' => '5808',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5809',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Tally Ho","2":"Tally Ho"}',
	// 			'english_name' => "Tally Ho",
	// 			'external_game_id' => '5809',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5810',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Victory","2":"Victory"}',
	// 			'english_name' => "Victory",
	// 			'external_game_id' => '5810',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5811',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"A Night Out","2":"A Night Out"}',
	// 			'english_name' => "A Night Out",
	// 			'external_game_id' => '5811',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5821',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Football","2":"Football"}',
	// 			'english_name' => "Football",
	// 			'external_game_id' => '5821',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5823',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Big Prosperity","2":"Big Prosperity"}',
	// 			'english_name' => "Big Prosperity",
	// 			'external_game_id' => '5823',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5824',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Mystic Dragon","2":"Mystic Dragon"}',
	// 			'english_name' => "Mystic Dragon",
	// 			'external_game_id' => '5824',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5825',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Golden Lotus","2":"Golden Lotus"}',
	// 			'english_name' => "Golden Lotus",
	// 			'external_game_id' => '5825',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5826',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Pay Dirt","2":"Pay Dirt"}',
	// 			'english_name' => "Pay Dirt",
	// 			'external_game_id' => '5826',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5827',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Sea Captain","2":"Sea Captain"}',
	// 			'english_name' => "Sea Captain",
	// 			'external_game_id' => '5827',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5828',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"T-Rex","2":"T-Rex"}',
	// 			'english_name' => "T-Rex",
	// 			'external_game_id' => '5828',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5831',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Golden Tour","2":"Golden Tour"}',
	// 			'english_name' => "Golden Tour",
	// 			'external_game_id' => '5831',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5832',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Highway Kings","2":"Highway Kings"}',
	// 			'english_name' => "Highway Kings",
	// 			'external_game_id' => '5832',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5833',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Silent Samurai","2":"Silent Samurai"}',
	// 			'english_name' => "Silent Samurai",
	// 			'external_game_id' => '5833',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5835',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Happy Golden Ox Of Happiness","2":"Happy Golden Ox Of Happiness"}',
	// 			'english_name' => "Happy Golden Ox Of Happiness",
	// 			'external_game_id' => '5835',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5836',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Triple Twister","2":"Triple Twister"}',
	// 			'english_name' => "Triple Twister",
	// 			'external_game_id' => '5836',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5837',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Happy Golden Monkey Of Happiness","2":"Happy Golden Monkey Of Happiness"}',
	// 			'english_name' => "Happy Golden Monkey Of Happiness",
	// 			'external_game_id' => '5837',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5901',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Duo Bao","2":"Duo Bao"}',
	// 			'english_name' => "Duo Bao",
	// 			'external_game_id' => '5901',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5902',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Candy Party","2":"Candy Party"}',
	// 			'english_name' => "Candy Party",
	// 			'external_game_id' => '5902',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5903',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Tomb of Dragon Emperor","2":"Tomb of Dragon Emperor"}',
	// 			'english_name' => "Tomb of Dragon Emperor",
	// 			'external_game_id' => '5903',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5904',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Pop Bomber","2":"Pop Bomber"}',
	// 			'english_name' => "Pop Bomber",
	// 			'external_game_id' => '5904',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5905',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Mahjong Bingo","2":"Mahjong Bingo"}',
	// 			'english_name' => "Mahjong Bingo",
	// 			'external_game_id' => '5905',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5888',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"JACKPOT","2":"JACKPOT"}',
	// 			'english_name' => "JACKPOT",
	// 			'external_game_id' => '5888',
	// 			'status' => $db_true,
	// 			'flag_show_in_site' => $db_true,
	// 			'updated_at' => $now
	// 		],

	// 		//===lottery===================================================================
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'LT',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
	// 			'game_name' => '_json:{"1":"Mark Six","2":"六合彩"}',
	// 			"english_name" => "Mark Six",
	// 			'external_game_id' => 'LT',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'BJ3D',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
	// 			'game_name' => '_json:{"1":"3D Lotto","2":"3D彩"}',
	// 			"english_name" => "3D Lotto",
	// 			'external_game_id' => 'BJ3D',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'PL3D',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
	// 			'game_name' => '_json:{"1":"Sports Lotto","2":"排列三"}',
	// 			"english_name" => "Sports Lotto",
	// 			'external_game_id' => 'PL3D',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'RDPK',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
	// 			'game_name' => '_json:{"1":"BB Raiden PK","2":"BB雷電PK"}',
	// 			"english_name" => "BB Raiden PK",
	// 			'external_game_id' => 'RDPK',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'LDDR',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
	// 			'game_name' => '_json:{"1":"Ladder Game","2":"梯子遊戲"}',
	// 			"english_name" => "Ladder Game",
	// 			'external_game_id' => 'LDDR',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'BBPK',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
	// 			'game_name' => '_json:{"1":"BB PK3","2":"BB PK3"}',
	// 			"english_name" => "BB PK3",
	// 			'external_game_id' => 'BBPK',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'BB3D',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
	// 			'game_name' => '_json:{"1":"BB3D","2":"BB3D"}',
	// 			"english_name" => "BB3D",
	// 			'external_game_id' => 'BB3D',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'BBKN',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
	// 			'game_name' => '_json:{"1":"BB KENO","2":"BB 快樂彩"}',
	// 			"english_name" => "BB KENO",
	// 			'external_game_id' => 'BBKN',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'BBRB',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
	// 			'game_name' => '_json:{"1":"BB Running","2":"BB 滾球王"}',
	// 			"english_name" => "BB Running",
	// 			'external_game_id' => 'BBRB',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'BCRA',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
	// 			'game_name' => '_json:{"1":"BB Bacca Lotto-A","2":"BB 百家彩票-A"}',
	// 			"english_name" => "BB Bacca Lotto-A",
	// 			'external_game_id' => 'BCRA',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'BCRB',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
	// 			'game_name' => '_json:{"1":"BB Bacca Lotto-B","2":"BB 百家彩票-B"}',
	// 			"english_name" => "BB Bacca Lotto-B",
	// 			'external_game_id' => 'BCRB',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'BCRC',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
	// 			'game_name' => '_json:{"1":"BB Bacca Lotto-C","2":"BB 百家彩票-C"}',
	// 			"english_name" => "BB Bacca Lotto-C",
	// 			'external_game_id' => 'BCRC',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'BCRD',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
	// 			'game_name' => '_json:{"1":"BB Bacca Lotto-D","2":"BB 百家彩票-D"}',
	// 			"english_name" => "BB Bacca Lotto-D",
	// 			'external_game_id' => 'BCRD',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'BCRE',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
	// 			'game_name' => '_json:{"1":"BB Bacca Lotto-E","2":"BB 百家彩票-E"}',
	// 			"english_name" => "BB Bacca Lotto-E",
	// 			'external_game_id' => 'BCRE',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'SH3D',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
	// 			'game_name' => '_json:{"1":"Shanghai Lotto","2":"上海時時樂"}',
	// 			"english_name" => "Shanghai Lotto",
	// 			'external_game_id' => 'SH3D',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'CQSC',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
	// 			'game_name' => '_json:{"1":"Chongqing Lotto","2":"重慶時時彩"}',
	// 			"english_name" => "Chongqing Lotto",
	// 			'external_game_id' => 'CQSC',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'TJSC',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
	// 			'game_name' => '_json:{"1":"Tianjin Lotto","2":"天津時時彩"}',
	// 			"english_name" => "Tianjin Lotto",
	// 			'external_game_id' => 'TJSC',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'XJSC',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
	// 			'game_name' => '_json:{"1":"Xinjiang Lotto","2":"新疆時時彩"}',
	// 			"english_name" => "Xinjiang Lotto",
	// 			'external_game_id' => 'XJSC',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'CQSF',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
	// 			'game_name' => '_json:{"1":"Chongqing Fortune Farm","2":"重慶幸運農場"}',
	// 			"english_name" => "Chongqing Fortune Farm",
	// 			'external_game_id' => 'CQSF',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'GXSF',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
	// 			'game_name' => '_json:{"1":"Guangxi Happy 10","2":"廣西十分彩"}',
	// 			"english_name" => "Guangxi Happy 10",
	// 			'external_game_id' => 'GXSF',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'TJSF',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
	// 			'game_name' => '_json:{"1":"Tianjin Happy 10","2":"天津十分彩"}',
	// 			"english_name" => "Tianjin Happy 10",
	// 			'external_game_id' => 'TJSF',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'BJPK',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
	// 			'game_name' => '_json:{"1":"Beijing PK10","2":"北京PK拾"}',
	// 			"english_name" => "Beijing PK10",
	// 			'external_game_id' => 'BJPK',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'BBQK',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
	// 			'game_name' => '_json:{"1":"BB Quick Keno","2":"BB 競速快樂彩"}',
	// 			"english_name" => "BB Quick Keno",
	// 			'external_game_id' => 'BBQK',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'BJKN',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
	// 			'game_name' => '_json:{"1":"Beijing Keno","2":"北京快樂 8"}',
	// 			"english_name" => "Beijing Keno",
	// 			'external_game_id' => 'BJKN',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'CAKN',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
	// 			'game_name' => '_json:{"1":"BC Keno","2":"加拿大卑斯"}',
	// 			"english_name" => "BC Keno",
	// 			'external_game_id' => 'CAKN',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'GDE5',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
	// 			'game_name' => '_json:{"1":"Guangdong 11/5","2":"廣東11選5"}',
	// 			"english_name" => "Guangdong 11/5",
	// 			'external_game_id' => 'GDE5',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'JXE5',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
	// 			'game_name' => '_json:{"1":"Jiangxi 11/5","2":"江西11選5"}',
	// 			"english_name" => "Jiangxi 11/5",
	// 			'external_game_id' => 'JXE5',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'SDE5',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
	// 			'game_name' => '_json:{"1":"Shandong 11/5","2":"山東十一運奪金"}',
	// 			"english_name" => "Shandong 11/5",
	// 			'external_game_id' => 'SDE5',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'BBLM',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
	// 			'game_name' => '_json:{"1":"BB Acey Deucey","2":"BB 射龍門"}',
	// 			"english_name" => "BB Acey Deucey",
	// 			'external_game_id' => 'BBLM',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'CQWC',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
	// 			'game_name' => '_json:{"1":"Chongqing Wild Card","2":"重慶百變王牌"}',
	// 			"english_name" => "Chongqing Wild Card",
	// 			'external_game_id' => 'CQWC',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'JSQ3',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
	// 			'game_name' => '_json:{"1":"Jiangsu Fast 3","2":"江蘇快 3"}',
	// 			"english_name" => "Jiangsu Fast 3",
	// 			'external_game_id' => 'JSQ3',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'AHQ3',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
	// 			'game_name' => '_json:{"1":"Anhui Fast 3","2":"安徽快 3"}',
	// 			"english_name" => "Anhui Fast 3",
	// 			'external_game_id' => 'AHQ3',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],

	// 		//===unknown======================================================================
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'unknown',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_unknown],
	// 			'game_name' => '_json:{"1":"Unknown","2":"未知"}',
	// 			"english_name" => "Unknown",
	// 			'external_game_id' => 'unknown',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],

	// 		//======New Games 3/17/2017=========================================================
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5069',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Fruit Fight","2":"水果擂台"}',
	// 			"english_name" => "Fruit Fight",
	// 			'external_game_id' => '5069',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5090',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Fortune of the Golden Rooster","2":"金鸡报喜"}',
	// 			"english_name" => "Fortune of the Golden Rooster",
	// 			'external_game_id' => '5090',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '5907',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
	// 			'game_name' => '_json:{"1":"Chiu Wei Tai Chiou","2":"趣味台球"}',
	// 			"english_name" => "Chiu Wei Tai Chiou",
	// 			'external_game_id' => '5907',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => 'LKPA',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
	// 			'game_name' => '_json:{"1":"BB Lucky Panda","2":"BB 幸运熊猫"}',
	// 			"english_name" => "BB Lucky Panda",
	// 			'external_game_id' => 'LKPA',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],

	// 		//======New Games 04/14/2017=========================================================
	// 		[
	// 			'game_platform_id' => $api_id,
	// 			'game_code' => '99',
	// 			'game_type_id' => $gameTypeCodeMaps[$game_type_code_tip],
	// 			'game_name' => '_json:{"1":"BB TIP","2":"BB 小费"}',
	// 			"english_name" => "BB Tip",
	// 			'external_game_id' => '99',
	// 			'status'=> $db_true,
	// 			'flag_show_in_site'=>$db_true,
	// 			'updated_at'=>$now,
	// 		],
 //            //======New Games 04/14/2017=========================================================
 //            [
 //                'game_platform_id' => $api_id,
 //                'game_code' => '5096',
 //                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
 //                'game_name' => '_json:{"1":"Wu Xing","2":"五星"}',
 //                "english_name" => "Wu Xing",
 //                'external_game_id' => '5096',
 //                'status'=> $db_true,
 //                'flag_show_in_site'=>$db_true,
 //                'updated_at'=>$now,
 //            ],
 //            [
 //                'game_platform_id' => $api_id,
 //                'game_code' => '5062',
 //                'game_type_id' => $gameTypeCodeMaps[$game_type_code_tip],
 //                'game_name' => '_json:{"1":"Dragon Must Die","2":"龙在囧途"}',
 //                "english_name" => "Dragon Must Die",
 //                'external_game_id' => '5062',
 //                'status'=> $db_true,
 //                'flag_show_in_site'=>$db_true,
 //                'updated_at'=>$now,
 //            ],
	// 	];

	// 	$this->load->model(['game_description_model']);

	// 	$success=$this->game_description_model->syncGameDescription($game_descriptions);

	// 	// $data = array();

	// 	// foreach ($game_descriptions as $game_list) {

	// 	// 	$game_code_exist = $this->db->select('COUNT(id) as count')
	// 	// 					 	->where('game_code', $game_list['game_code'])
	// 	// 					 	->where('game_platform_id', AG_API)
	// 	// 					 	->get('game_description')
	// 	// 			 		 	->row();

	// 	// 	if( $game_code_exist->count <= 0 ) continue;

	// 	// 	$this->db->where('game_code', $game_list['game_code']);
	// 	// 	$this->db->where('game_platform_id', AG_API);
	// 	// 	$this->db->update('game_description', $game_list);
	// 	// 	$cnt++;

	// 	// }

	// 	return $success;
	// }

}
