<?php
trait game_description_goldenf_pgsoft {

    public function sync_game_description_goldenf_pgsoft(){
        $api_id=GOLDENF_PGSOFT_API;
        $this->sync_gamelist_goldenf_pgsoft($api_id);
    }

    public function sync_gamelist_goldenf_pgsoft($api_id){

        $success=true;
        $db_true=1;
        $db_false=0;
        $now=$this->utils->getNowForMysql();

        $game_type_code_slots = SYNC::TAG_CODE_SLOT;
        $game_type_code_unknown = SYNC::TAG_CODE_UNKNOWN_GAME;

        $game_types = [
            $game_type_code_slots =>
                [
                    'game_platform_id' => $api_id,
                    'game_type' => '_json:{"1":"Slot Game","2":"老虎机游戏","3":"Slot Game","4":"Slot Game","5":"Slot Game"}',
                    'game_type_lang' => '_json:{"1":"Slot Game","2":"老虎机游戏","3":"Slot Game","4":"Slot Game","5":"Slot Game"}',
                    'game_type_code' => $game_type_code_slots,
                    'game_tag_code' => $game_type_code_slots,
                    'updated_at' => $now,
                ],
            $game_type_code_unknown =>
                [
                    'game_platform_id' => $api_id,
                    'game_type' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                    'game_type_lang' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                    "game_type_code" => $game_type_code_unknown,
                    "game_tag_code" => $game_type_code_unknown,
                    'flag_show_in_site' => $db_true,
                    'updated_at'=>$now,
                ],
            ];

        $cnt=0;
        $this->load->model(['game_type_model']);
        $gameTypeCodeMaps=$this->game_type_model->syncGameTypes($game_types);

        $this->utils->debug_log('gameTypeCodeMaps', $gameTypeCodeMaps);

        if(empty($gameTypeCodeMaps)){
            return false;
        }

     $game_descriptions = array(

            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_unknown],
                'game_name' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                'game_code' => 'unknown',
                'dlc_enabled' => $db_true,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'flag_show_in_site' => $db_false,
                'html_five_enabled' => $db_false,
                'english_name' => 'Unknown',
                'external_game_id' => 'unknown',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_false,
                'enabled_on_ios' => $db_false,
            ],            
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"HONEY TRAP OF DIAO CHAN","2":"夜戏貂蝉","3":"HONEY TRAP OF DIAO CHAN","4":"HONEY TRAP OF DIAO CHAN","5":"HONEY TRAP OF DIAO CHAN"}',
                'game_code' => "diaochan",
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"diaochan"}',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'HONEY TRAP OF DIAO CHAN',
                'html_five_enabled' => $db_false,
                'external_game_id' => "diaochan",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_false,
                'enabled_on_ios' => $db_false,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"FORTUNE GODS","2":"横财神","3":"FORTUNE GODS","4":"FORTUNE GODS","5":"FORTUNE GODS"}',
                'game_code' => "fortune-gods",
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"fortune-gods"}',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'FORTUNE GODS',
                'html_five_enabled' => $db_false,
                'external_game_id' => "fortune-gods",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_false,
                'enabled_on_ios' => $db_false,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"WIN WIN WON","2":"旺旺旺","3":"WIN WIN WON","4":"WIN WIN WON","5":"WIN WIN WON"}',
                'game_code' => "win-win-won",
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"win-win-won"}',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'WIN WIN WON',
                'html_five_enabled' => $db_false,
                'external_game_id' => "win-win-won",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_false,
                'enabled_on_ios' => $db_false,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"MEDUSA 2","2":"美杜莎 2","3":"MEDUSA 2","4":"MEDUSA 2","5":"MEDUSA 2"}',
                'game_code' => "medusa2",
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"medusa2"}',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'MEDUSA 2',
                'html_five_enabled' => $db_false,
                'external_game_id' => "medusa2",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_false,
                'enabled_on_ios' => $db_false,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"PEAS FAIRY","2":"豌豆精灵","3":"PEAS FAIRY","4":"PEAS FAIRY","5":"PEAS FAIRY"}',
                'game_code' => "peas-fairy",
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"peas-fairy"}',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'PEAS FAIRY',
                'html_five_enabled' => $db_false,
                'external_game_id' => "peas-fairy",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_false,
                'enabled_on_ios' => $db_false,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"TREE OF FORTUNE","2":"摇钱树","3":"TREE OF FORTUNE","4":"TREE OF FORTUNE","5":"TREE OF FORTUNE"}',
                'game_code' => "fortune-tree",
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"fortune-tree"}',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'TREE OF FORTUNE',
                'html_five_enabled' => $db_false,
                'external_game_id' => "fortune-tree",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_false,
                'enabled_on_ios' => $db_false,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"MEDUSA 1","2":"美杜莎 1","3":"MEDUSA 1","4":"MEDUSA 1","5":"MEDUSA 1"}',
                'game_code' => "medusa",
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"medusa"}',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'MEDUSA 1',
                'html_five_enabled' => $db_false,
                'external_game_id' => "medusa",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_false,
                'enabled_on_ios' => $db_false,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Plushie Frenzy","2":"抓抓乐","3":"Plushie Frenzy","4":"Plushie Frenzy","5":"Plushie Frenzy"}',
                'game_code' => "plushie-frenzy",
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"plushie-frenzy"}',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'Plushie Frenzy',
                'html_five_enabled' => $db_false,
                'external_game_id' => "plushie-frenzy",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_false,
                'enabled_on_ios' => $db_false,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Wizdom Wonders","2":"巫师之书","3":"Wizdom Wonders","4":"Wizdom Wonders","5":"Wizdom Wonders"}',
                'game_code' => "wizdom-wonders",
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"wizdom-wonders"}',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'Wizdom Wonders',
                'html_five_enabled' => $db_false,
                'external_game_id' => "wizdom-wonders",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_false,
                'enabled_on_ios' => $db_false,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Gem Saviour","2":"宝石侠","3":"Gem Saviour","4":"Gem Saviour","5":"Gem Saviour"}',
                'game_code' => "gem-saviour",
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"gem-saviour"}',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'Gem Saviour',
                'html_five_enabled' => $db_false,
                'external_game_id' => "gem-saviour",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_false,
                'enabled_on_ios' => $db_false,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Steampunk","2":"蒸汽朋克","3":"Steampunk","4":"Steampunk","5":"Steampunk"}',
                'game_code' => "steam-punk",
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"steam-punk"}',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'Steampunk',
                'html_five_enabled' => $db_false,
                'external_game_id' => "steam-punk",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_false,
                'enabled_on_ios' => $db_false,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Summon & Conquer","2":"国王的召唤","3":"Summon & Conquer","4":"Summon & Conquer","5":"Summon & Conquer"}',
                'game_code' => "summon-conquer",
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"summon-conquer"}',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'Summon & Conquer',
                'html_five_enabled' => $db_false,
                'external_game_id' => "summon-conquer",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_false,
                'enabled_on_ios' => $db_false,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Hood vs Wolf","2":"逆袭的小红帽","3":"Hood vs Wolf","4":"Hood vs Wolf","5":"Hood vs Wolf"}',
                'game_code' => "hood-wolf",
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"hood-wolf"}',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'Hood vs Wolf',
                'html_five_enabled' => $db_false,
                'external_game_id' => "hood-wolf",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_false,
                'enabled_on_ios' => $db_false,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Hotpot","2":"麻辣火锅","3":"Hotpot","4":"Hotpot","5":"Hotpot"}',
                'game_code' => "hotpot",
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"hotpot"}',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'Hotpot',
                'html_five_enabled' => $db_false,
                'external_game_id' => "hotpot",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_false,
                'enabled_on_ios' => $db_false,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Dragon Legend","2":"鱼跃龙门","3":"Dragon Legend","4":"Dragon Legend","5":"Dragon Legend"}',
                'game_code' => "dragon-legend",
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"dragon-legend"}',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'Dragon Legend',
                'html_five_enabled' => $db_false,
                'external_game_id' => "dragon-legend",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_false,
                'enabled_on_ios' => $db_false,
            ],
     );

        $this->load->model(['game_description_model']);

        $success=$this->game_description_model->syncGameDescription($game_descriptions);

        return $success;
    }

}
