<?php
trait game_description_pgsoft {

    // public function sync_all_pgsoft_games(){
    //     $this->sync_game_description_pgsoft_t1();
    //     $this->sync_game_description_pgsoft();
    // }

    // public function sync_game_description_pgsoft_t1(){
    //     $api_id = T1PGSOFT_API;
    //     $this->pgsoft_game_list($api_id);
    // }

    public function sync_game_description_pgsoft(){
        $api_id = PGSOFT_API;
        $this->pgsoft_game_list($api_id);
    }


    public function pgsoft_game_list($api_id){
        $cnt        = 0;
        $now        = $this->utils->getNowForMysql();
        $db_true    = SYNC::FLAG_TRUE;
        $db_false   = SYNC::FLAG_FALSE;

        $game_type_code_table_and_cards = SYNC::TAG_CODE_TABLE_AND_CARDS;
        $game_type_code_slots           = SYNC::TAG_CODE_SLOT;
        $game_type_code_unknown         = SYNC::TAG_CODE_UNKNOWN_GAME;

        $game_types = [
            $game_type_code_slots => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Slot Game","2":"老虎机游戏","3":"Slot Game","4":"Slot Game","5":"Slot Game"}',
                'game_type_lang' => '_json:{"1":"Slot Game","2":"老虎机游戏","3":"Slot Game","4":"Slot Game","5":"Slot Game"}',
                'game_type_code' => $game_type_code_slots,
                "game_tag_code" => $game_type_code_slots,
                'updated_at' => $now,
            ],
            $game_type_code_table_and_cards => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Table and Cards","2":"赌桌游戏","3":"Table and Cards","4":"Table and Cards","5":"Table and Cards"}',
                'game_type_lang' => '_json:{"1":"Table and Cards","2":"赌桌游戏","3":"Table and Cards","4":"Table and Cards","5":"Table and Cards"}',
                "game_type_code" => $game_type_code_table_and_cards,
                "game_tag_code" => $game_type_code_table_and_cards,
                'updated_at' => $now,
            ],
            $game_type_code_unknown => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                'game_type_lang' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                "game_type_code" => $game_type_code_unknown,
                "game_tag_code" => $game_type_code_unknown,
                'flag_show_in_site' => $db_true,
                'updated_at'=>$now,
            ],
        ];

        $this->load->model(['game_type_model']);
        echo "<pre>";
        $gameTypeCodeMaps=$this->game_type_model->syncGameTypes($game_types);

        $game_descriptions = array(
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_unknown],
                'game_name' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                'game_code' => 'unknown',
                'dlc_enabled' => $db_true,
                'progressive' => $db_false,
                'flash_enabled' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Unknown',
                'external_game_id' => 'unknown',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"HONEY TRAP OF DIAO CHAN","2":"夜戏貂蝉","3":"HONEY TRAP OF DIAO CHAN","4":"HONEY TRAP OF DIAO CHAN","5":"HONEY TRAP OF DIAO CHAN"}',
                'game_code' => "1",
                'dlc_enabled' => $db_true,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"diaochan"}',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'HONEY TRAP OF DIAO CHAN',
                'html_five_enabled' => $db_true,
                'external_game_id' => "1",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"FORTUNE GODS","2":"横财神","3":"FORTUNE GODS","4":"FORTUNE GODS","5":"FORTUNE GODS"}',
                'game_code' => "3",
                'dlc_enabled' => $db_true,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"fortune-gods"}',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'FORTUNE GODS',
                'html_five_enabled' => $db_true,
                'external_game_id' => "3",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Game Lobby","2":"游戏大厅","3":"Game Lobby","4":"Game Lobby","5":"Game Lobby"}',
                'game_code' => "0",
                'dlc_enabled' => $db_true,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => null,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'Game Lobby',
                'html_five_enabled' => $db_true,
                'external_game_id' => "0",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"WIN WIN WON","2":"旺旺旺","3":"WIN WIN WON","4":"WIN WIN WON","5":"WIN WIN WON"}',
                'game_code' => "24",
                'dlc_enabled' => $db_true,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"win-win-won4"}',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'WIN WIN WON',
                'html_five_enabled' => $db_true,
                'external_game_id' => "24",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"MEDUSA 2","2":"美杜莎 2","3":"MEDUSA 2","4":"MEDUSA 2","5":"MEDUSA 2"}',
                'game_code' => "6",
                'dlc_enabled' => $db_true,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"medusa2"}',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'MEDUSA 2',
                'html_five_enabled' => $db_true,
                'external_game_id' => "6",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"PEAS FAIRY","2":"豌豆精灵","3":"PEAS FAIRY","4":"PEAS FAIRY","5":"PEAS FAIRY"}',
                'game_code' => "8",
                'dlc_enabled' => $db_true,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"peas-fairy"}',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'PEAS FAIRY',
                'html_five_enabled' => $db_true,
                'external_game_id' => "8",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"TREE OF FORTUNE","2":"摇钱树","3":"TREE OF FORTUNE","4":"TREE OF FORTUNE","5":"TREE OF FORTUNE"}',
                'game_code' => "26",
                'dlc_enabled' => $db_true,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"fortune-tree"}',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'TREE OF FORTUNE',
                'html_five_enabled' => $db_true,
                'external_game_id' => "26",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_table_and_cards],
                'game_name' => '_json:{"1":"JOKER WILD","2":"小丑翻翻乐","3":"JOKER WILD","4":"JOKER WILD","5":"JOKER WILD"}',
                'game_code' => "10",
                'dlc_enabled' => $db_true,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"joker-wild"}',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'JOKER WILD',
                'html_five_enabled' => $db_true,
                'external_game_id' => "10",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"MEDUSA 1","2":"美杜莎 1","3":"MEDUSA 1","4":"MEDUSA 1","5":"MEDUSA 1"}',
                'game_code' => "7",
                'dlc_enabled' => $db_true,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"medusa"}',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'MEDUSA 1',
                'html_five_enabled' => $db_true,
                'external_game_id' => "7",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_table_and_cards],
                'game_name' => '_json:{"1":"European Blackjack","2":"欧式二十一点","3":"European Blackjack","4":"European Blackjack","5":"European Blackjack"}',
                'game_code' => "12",
                'dlc_enabled' => $db_true,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"blackjack-eu"}',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'European Blackjack',
                'html_five_enabled' => $db_true,
                'external_game_id' => "12",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_table_and_cards],
                'game_name' => '_json:{"1":"American Blackjack","2":"美式二十一点","3":"American Blackjack","4":"American Blackjack","5":"American Blackjack"}',
                'game_code' => "11",
                'dlc_enabled' => $db_true,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"blackjack-us"}',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'American Blackjack',
                'html_five_enabled' => $db_true,
                'external_game_id' => "11",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Plushie Frenzy","2":"抓抓乐","3":"Plushie Frenzy","4":"Plushie Frenzy","5":"Plushie Frenzy"}',
                'game_code' => "25",
                'dlc_enabled' => $db_true,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"plushie-frenzy"}',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'Plushie Frenzy',
                'html_five_enabled' => $db_true,
                'external_game_id' => "25",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Wizdom Wonders","2":"巫师之书","3":"Wizdom Wonders","4":"Wizdom Wonders","5":"Wizdom Wonders"}',
                'game_code' => "17",
                'dlc_enabled' => $db_true,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"wizdom-wonders"}',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'Wizdom Wonders',
                'html_five_enabled' => $db_true,
                'external_game_id' => "17",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Gem Saviour","2":"宝石侠","3":"Gem Saviour","4":"Gem Saviour","5":"Gem Saviour"}',
                'game_code' => "2",
                'dlc_enabled' => $db_true,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"gem-saviour"}',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'Gem Saviour',
                'html_five_enabled' => $db_true,
                'external_game_id' => "2",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Steampunk","2":"蒸汽朋克","3":"Steampunk","4":"Steampunk","5":"Steampunk"}',
                'game_code' => "19",
                'dlc_enabled' => $db_true,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"steam-punk"}',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'Steampunk',
                'html_five_enabled' => $db_true,
                'external_game_id' => "19",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Summon & Conquer","2":"国王的召唤","3":"Summon & Conquer","4":"Summon & Conquer","5":"Summon & Conquer"}',
                'game_code' => "4",
                'dlc_enabled' => $db_true,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"summon-conquer"}',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'Summon & Conquer',
                'html_five_enabled' => $db_true,
                'external_game_id' => "4",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Hood vs Wolf","2":"逆袭的小红帽","3":"Hood vs Wolf","4":"Hood vs Wolf","5":"Hood vs Wolf"}',
                'game_code' => "18",
                'dlc_enabled' => $db_true,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"hood-wolf"}',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'Hood vs Wolf',
                'html_five_enabled' => $db_true,
                'external_game_id' => "18",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Hotpot","2":"麻辣火锅","3":"Hotpot","4":"Hotpot","5":"Hotpot"}',
                'game_code' => "28",
                'dlc_enabled' => $db_true,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"hotpot"}',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'Hotpot',
                'html_five_enabled' => $db_true,
                'external_game_id' => "28",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Dragon Legend","2":"麻辣火锅","3":"Dragon Legend","4":"Dragon Legend","5":"Dragon Legend"}',
                'game_code' => "29",
                'dlc_enabled' => $db_true,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"dragon-legend"}',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'Dragon Legend',
                'html_five_enabled' => $db_true,
                'external_game_id' => "29",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Win Win Won 2","2":"旺旺旺2","3":"Win Win Won 2","4":"Win Win Won 2","5":"Win Win Won 2"}',
                'game_code' => "win-win-won2",
                'dlc_enabled' => $db_true,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"win-win-won2"}',
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'mobile_enabled' => $db_false,
                'english_name' => 'Win Win Won 2',
                'html_five_enabled' => $db_true,
                'external_game_id' => "win-win-won2",
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
        );

        $this->load->model(['game_description_model']);

        $success=$this->game_description_model->syncGameDescription($game_descriptions);

        return $success;
    }
}
