<?php
trait game_description_oneworks {

 	public function sync_game_description_oneworks(){
        $api_id = ONEWORKS_API;
        $this->oneworks_game_list($api_id);
    }

    public function sync_game_description_oneworks_t1(){
        $api_id = T1ONEWORKS_API;
        $this->oneworks_game_list($api_id);
    }

    public function oneworks_game_list($api_id){

        $success=true;
        $db_true=1;
        $db_false=0;
        $now=$this->utils->getNowForMysql();

        $game_type_code_sports  = SYNC::TAG_CODE_SPORTS;
        $game_type_code_unknown = SYNC::TAG_CODE_UNKNOWN_GAME;

        $game_types = [
            $game_type_code_sports => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Sports","2":"体育","3":"Sports","4":"Sports","5":"Sports"}',
                'game_type_lang' => '_json:{"1":"Sports","2":"体育","3":"Sports","4":"Sports","5":"Sports"}',
                "game_type_code" => $game_type_code_sports,
                'updated_at'=>$now,
                'game_tag_code' => SYNC::TAG_CODE_SPORTS
            ],
            $game_type_code_unknown=> [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Unknown","2":"不明类型","3":"Unknown","4":"Unknown","5":"Unknown"}',
                'game_type_lang' => '_json:{"1":"Unknown","2":"不明类型","3":"Unknown","4":"Unknown","5":"Unknown"}',
                "game_type_code" => $game_type_code_unknown,
                'updated_at'=>$now,
                'game_tag_code' => SYNC::TAG_CODE_UNKNOWN_GAME
            ],
        ];

        echo "<pre>";
        $this->load->model(['game_type_model']);
        $gameTypeCodeMaps=$this->game_type_model->syncGameTypes($game_types);

        $this->utils->debug_log('gameTypeCodeMaps', $gameTypeCodeMaps);

        if(empty($gameTypeCodeMaps)){
            return false;
        }

		$game_descriptions = array(
			[
				'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_unknown],
                'game_code' => 'unknown',
				'external_game_id' => 'unknown',
				'game_name' => '_json:{"1":"Unknown Oneworks Game","2":"Unknown Oneworks Game"}',
				'english_name' => 'Unknown Oneworks Game',
			],
			[
                'game_code' => '1',
                'external_game_id' => '1',
                'english_name' => 'Soccer',
                'game_name' => '_json:{"1":"Soccer","2":"Soccer","3":"Soccer","4":"Soccer","5":"Soccer"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '2',
                'external_game_id' => '2',
                'english_name' => 'Basketball',
                'game_name' => '_json:{"1":"Basketball","2":"Basketball","3":"Basketball","4":"Basketball","5":"Basketball"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '3',
                'external_game_id' => '3',
                'english_name' => 'Football',
                'game_name' => '_json:{"1":"Football","2":"Football","3":"Football","4":"Football","5":"Football"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '4',
                'external_game_id' => '4',
                'english_name' => 'Ice Hockey',
                'game_name' => '_json:{"1":"Ice Hockey","2":"Ice Hockey","3":"Ice Hockey","4":"Ice Hockey","5":"Ice Hockey"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '5',
                'external_game_id' => '5',
                'english_name' => 'Tennis',
                'game_name' => '_json:{"1":"Tennis","2":"Tennis","3":"Tennis","4":"Tennis","5":"Tennis"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '6',
                'external_game_id' => '6',
                'english_name' => 'Volleyball',
                'game_name' => '_json:{"1":"Volleyball","2":"Volleyball","3":"Volleyball","4":"Volleyball","5":"Volleyball"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '7',
                'external_game_id' => '7',
                'english_name' => 'Billiards',
                'game_name' => '_json:{"1":"Billiards","2":"Billiards","3":"Billiards","4":"Billiards","5":"Billiards"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '8',
                'external_game_id' => '8',
                'english_name' => 'Baseball',
                'game_name' => '_json:{"1":"Baseball","2":"Baseball","3":"Baseball","4":"Baseball","5":"Baseball"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '9',
                'external_game_id' => '9',
                'english_name' => 'Badminton',
                'game_name' => '_json:{"1":"Badminton","2":"Badminton","3":"Badminton","4":"Badminton","5":"Badminton"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '10',
                'external_game_id' => '10',
                'english_name' => 'Golf',
                'game_name' => '_json:{"1":"Golf","2":"Golf","3":"Golf","4":"Golf","5":"Golf"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '11',
                'external_game_id' => '11',
                'english_name' => 'Motorsports',
                'game_name' => '_json:{"1":"Motorsports","2":"Motorsports","3":"Motorsports","4":"Motorsports","5":"Motorsports"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '12',
                'external_game_id' => '12',
                'english_name' => 'Swimming',
                'game_name' => '_json:{"1":"Swimming","2":"Swimming","3":"Swimming","4":"Swimming","5":"Swimming"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '13',
                'external_game_id' => '13',
                'english_name' => 'Politics',
                'game_name' => '_json:{"1":"Politics","2":"Politics","3":"Politics","4":"Politics","5":"Politics"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '14',
                'external_game_id' => '14',
                'english_name' => 'Water Polo',
                'game_name' => '_json:{"1":"Water Polo","2":"Water Polo","3":"Water Polo","4":"Water Polo","5":"Water Polo"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '15',
                'external_game_id' => '15',
                'english_name' => 'Diving',
                'game_name' => '_json:{"1":"Diving","2":"Diving","3":"Diving","4":"Diving","5":"Diving"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '16',
                'external_game_id' => '16',
                'english_name' => 'Boxing',
                'game_name' => '_json:{"1":"Boxing","2":"Boxing","3":"Boxing","4":"Boxing","5":"Boxing"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '17',
                'external_game_id' => '17',
                'english_name' => 'Archery',
                'game_name' => '_json:{"1":"Archery","2":"Archery","3":"Archery","4":"Archery","5":"Archery"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '18',
                'external_game_id' => '18',
                'english_name' => 'Table Tennis',
                'game_name' => '_json:{"1":"Table Tennis","2":"Table Tennis","3":"Table Tennis","4":"Table Tennis","5":"Table Tennis"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '19',
                'external_game_id' => '19',
                'english_name' => 'Weightlifting',
                'game_name' => '_json:{"1":"Weightlifting","2":"Weightlifting","3":"Weightlifting","4":"Weightlifting","5":"Weightlifting"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '20',
                'external_game_id' => '20',
                'english_name' => 'Canoeing',
                'game_name' => '_json:{"1":"Canoeing","2":"Canoeing","3":"Canoeing","4":"Canoeing","5":"Canoeing"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '21',
                'external_game_id' => '21',
                'english_name' => 'Gymnastics',
                'game_name' => '_json:{"1":"Gymnastics","2":"Gymnastics","3":"Gymnastics","4":"Gymnastics","5":"Gymnastics"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '22',
                'external_game_id' => '22',
                'english_name' => 'Athletics',
                'game_name' => '_json:{"1":"Athletics","2":"Athletics","3":"Athletics","4":"Athletics","5":"Athletics"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '23',
                'external_game_id' => '23',
                'english_name' => 'Equestrian',
                'game_name' => '_json:{"1":"Equestrian","2":"Equestrian","3":"Equestrian","4":"Equestrian","5":"Equestrian"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '24',
                'external_game_id' => '24',
                'english_name' => 'Handball',
                'game_name' => '_json:{"1":"Handball","2":"Handball","3":"Handball","4":"Handball","5":"Handball"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '25',
                'external_game_id' => '25',
                'english_name' => 'Darts',
                'game_name' => '_json:{"1":"Darts","2":"Darts","3":"Darts","4":"Darts","5":"Darts"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '26',
                'external_game_id' => '26',
                'english_name' => 'Rugby',
                'game_name' => '_json:{"1":"Rugby","2":"Rugby","3":"Rugby","4":"Rugby","5":"Rugby"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '27',
                'external_game_id' => '27',
                'english_name' => 'Cricket',
                'game_name' => '_json:{"1":"Cricket","2":"Cricket","3":"Cricket","4":"Cricket","5":"Cricket"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '28',
                'external_game_id' => '28',
                'english_name' => 'Field Hockey',
                'game_name' => '_json:{"1":"Field Hockey","2":"Field Hockey","3":"Field Hockey","4":"Field Hockey","5":"Field Hockey"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '29',
                'external_game_id' => '29',
                'english_name' => 'Winter Sport',
                'game_name' => '_json:{"1":"Winter Sport","2":"Winter Sport","3":"Winter Sport","4":"Winter Sport","5":"Winter Sport"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '30',
                'external_game_id' => '30',
                'english_name' => 'Squash',
                'game_name' => '_json:{"1":"Squash","2":"Squash","3":"Squash","4":"Squash","5":"Squash"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '31',
                'external_game_id' => '31',
                'english_name' => 'Entertainment',
                'game_name' => '_json:{"1":"Entertainment","2":"Entertainment","3":"Entertainment","4":"Entertainment","5":"Entertainment"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '32',
                'external_game_id' => '32',
                'english_name' => 'Net Ball',
                'game_name' => '_json:{"1":"Net Ball","2":"Net Ball","3":"Net Ball","4":"Net Ball","5":"Net Ball"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '33',
                'external_game_id' => '33',
                'english_name' => 'Cycling',
                'game_name' => '_json:{"1":"Cycling","2":"Cycling","3":"Cycling","4":"Cycling","5":"Cycling"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '34',
                'external_game_id' => '34',
                'english_name' => 'Fencing',
                'game_name' => '_json:{"1":"Fencing","2":"Fencing","3":"Fencing","4":"Fencing","5":"Fencing"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '35',
                'external_game_id' => '35',
                'english_name' => 'Judo',
                'game_name' => '_json:{"1":"Judo","2":"Judo","3":"Judo","4":"Judo","5":"Judo"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '36',
                'external_game_id' => '36',
                'english_name' => 'M. Pentathlon',
                'game_name' => '_json:{"1":"M. Pentathlon","2":"M. Pentathlon","3":"M. Pentathlon","4":"M. Pentathlon","5":"M. Pentathlon"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '37',
                'external_game_id' => '37',
                'english_name' => 'Rowing',
                'game_name' => '_json:{"1":"Rowing","2":"Rowing","3":"Rowing","4":"Rowing","5":"Rowing"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '38',
                'external_game_id' => '38',
                'english_name' => 'Sailing',
                'game_name' => '_json:{"1":"Sailing","2":"Sailing","3":"Sailing","4":"Sailing","5":"Sailing"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '39',
                'external_game_id' => '39',
                'english_name' => 'Shooting',
                'game_name' => '_json:{"1":"Shooting","2":"Shooting","3":"Shooting","4":"Shooting","5":"Shooting"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '40',
                'external_game_id' => '40',
                'english_name' => 'Taekwondo',
                'game_name' => '_json:{"1":"Taekwondo","2":"Taekwondo","3":"Taekwondo","4":"Taekwondo","5":"Taekwondo"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '41',
                'external_game_id' => '41',
                'english_name' => 'Triathlon',
                'game_name' => '_json:{"1":"Triathlon","2":"Triathlon","3":"Triathlon","4":"Triathlon","5":"Triathlon"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '42',
                'external_game_id' => '42',
                'english_name' => 'Wrestling',
                'game_name' => '_json:{"1":"Wrestling","2":"Wrestling","3":"Wrestling","4":"Wrestling","5":"Wrestling"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '43',
                'external_game_id' => '43',
                'english_name' => 'E Sports',
                'game_name' => '_json:{"1":"E Sports","2":"E Sports","3":"E Sports","4":"E Sports","5":"E Sports"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '44',
                'external_game_id' => '44',
                'english_name' => 'Muay Thai',
                'game_name' => '_json:{"1":"Muay Thai","2":"Muay Thai","3":"Muay Thai","4":"Muay Thai","5":"Muay Thai"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '50',
                'external_game_id' => '50',
                'english_name' => 'Cricket',
                'game_name' => '_json:{"1":"Cricket","2":"Cricket","3":"Cricket","4":"Cricket","5":"Cricket"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '99',
                'external_game_id' => '99',
                'english_name' => 'Other Sports',
                'game_name' => '_json:{"1":"Other Sports","2":"Other Sports","3":"Other Sports","4":"Other Sports","5":"Other Sports"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '99MP',
                'external_game_id' => '99MP',
                'english_name' => 'Mix Parlay',
                'game_name' => '_json:{"1":"Mix Parlay","2":"Mix Parlay","3":"Mix Parlay","4":"Mix Parlay","5":"Mix Parlay"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '151',
                'external_game_id' => '151',
                'english_name' => 'Horse Racing',
                'game_name' => '_json:{"1":"Horse Racing","2":"Horse Racing","3":"Horse Racing","4":"Horse Racing","5":"Horse Racing"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '152',
                'external_game_id' => '152',
                'english_name' => 'Greyhounds',
                'game_name' => '_json:{"1":"Greyhounds","2":"Greyhounds","3":"Greyhounds","4":"Greyhounds","5":"Greyhounds"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '153',
                'external_game_id' => '153',
                'english_name' => 'Harness',
                'game_name' => '_json:{"1":"Harness","2":"Harness","3":"Harness","4":"Harness","5":"Harness"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '154',
                'external_game_id' => '154',
                'english_name' => 'Horse Racing Fixed Odds',
                'game_name' => '_json:{"1":"Horse Racing Fixed Odds","2":"Horse Racing Fixed Odds","3":"Horse Racing Fixed Odds","4":"Horse Racing Fixed Odds","5":"Horse Racing Fixed Odds"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '161',
                'external_game_id' => '161',
                'english_name' => 'Number Game',
                'game_name' => '_json:{"1":"Number Game","2":"Number Game","3":"Number Game","4":"Number Game","5":"Number Game"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '180',
                'external_game_id' => '180',
                'english_name' => 'Virtual Soccer (180)',
                'game_name' => '_json:{"1":"Virtual Soccer (180)","2":"Virtual Soccer (180)","3":"Virtual Soccer (180)","4":"Virtual Soccer (180)","5":"Virtual Soccer (180)"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '190',
                'external_game_id' => '190',
                'english_name' => 'Virtual Soccer (190)',
                'game_name' => '_json:{"1":"Virtual Soccer (190)","2":"Virtual Soccer (190)","3":"Virtual Soccer (190)","4":"Virtual Soccer (190)","5":"Virtual Soccer (190)"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '191',
                'external_game_id' => '191',
                'english_name' => 'Virtual Soccer (191)',
                'game_name' => '_json:{"1":"Virtual Soccer (191)","2":"Virtual Soccer (191)","3":"Virtual Soccer (191)","4":"Virtual Soccer (191)","5":"Virtual Soccer (191)"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '192',
                'external_game_id' => '192',
                'english_name' => 'Virtual Soccer (192)',
                'game_name' => '_json:{"1":"Virtual Soccer (192)","2":"Virtual Soccer (192)","3":"Virtual Soccer (192)","4":"Virtual Soccer (192)","5":"Virtual Soccer (192)"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '181',
                'external_game_id' => '181',
                'english_name' => 'Virtual Horse Racing',
                'game_name' => '_json:{"1":"Virtual Horse Racing","2":"Virtual Horse Racing","3":"Virtual Horse Racing","4":"Virtual Horse Racing","5":"Virtual Horse Racing"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '182',
                'external_game_id' => '182',
                'english_name' => 'Virtual Greyhound',
                'game_name' => '_json:{"1":"Virtual Greyhound","2":"Virtual Greyhound","3":"Virtual Greyhound","4":"Virtual Greyhound","5":"Virtual Greyhound"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '183',
                'external_game_id' => '183',
                'english_name' => 'Virtual Speedway',
                'game_name' => '_json:{"1":"Virtual Speedway","2":"Virtual Speedway","3":"Virtual Speedway","4":"Virtual Speedway","5":"Virtual Speedway"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '184',
                'external_game_id' => '184',
                'english_name' => 'Virtual F1',
                'game_name' => '_json:{"1":"Virtual F1","2":"Virtual F1","3":"Virtual F1","4":"Virtual F1","5":"Virtual F1"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '185',
                'external_game_id' => '185',
                'english_name' => 'Virtual Cycling',
                'game_name' => '_json:{"1":"Virtual Cycling","2":"Virtual Cycling","3":"Virtual Cycling","4":"Virtual Cycling","5":"Virtual Cycling"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '186',
                'external_game_id' => '186',
                'english_name' => 'Virtual Tennis (186)',
                'game_name' => '_json:{"1":"Virtual Tennis (186)","2":"Virtual Tennis (186)","3":"Virtual Tennis (186)","4":"Virtual Tennis (186)","5":"Virtual Tennis (186)"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '196',
                'external_game_id' => '196',
                'english_name' => 'Virtual Tennis (196)',
                'game_name' => '_json:{"1":"Virtual Tennis (196)","2":"Virtual Tennis (196)","3":"Virtual Tennis (196)","4":"Virtual Tennis (196)","5":"Virtual Tennis (196)"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '193',
                'external_game_id' => '193',
                'english_name' => 'Virtual BasketBall',
                'game_name' => '_json:{"1":"Virtual BasketBall","2":"Virtual BasketBall","3":"Virtual BasketBall","4":"Virtual BasketBall","5":"Virtual BasketBall"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '199',
                'external_game_id' => '199',
                'english_name' => 'Virtual Sport Parlay',
                'game_name' => '_json:{"1":"Virtual Sport Parlay","2":"Virtual Sport Parlay","3":"Virtual Sport Parlay","4":"Virtual Sport Parlay","5":"Virtual Sport Parlay"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '251',
                'external_game_id' => '251',
                'english_name' => 'Casino',
                'game_name' => '_json:{"1":"Casino","2":"Casino","3":"Casino","4":"Casino","5":"Casino"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '208',
                'external_game_id' => '208',
                'english_name' => 'RNG Game',
                'game_name' => '_json:{"1":"RNG Game","2":"RNG Game","3":"RNG Game","4":"RNG Game","5":"RNG Game"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '209',
                'external_game_id' => '209',
                'english_name' => 'Mini Game',
                'game_name' => '_json:{"1":"Mini Game","2":"Mini Game","3":"Mini Game","4":"Mini Game","5":"Mini Game"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
            [
                'game_code' => '210',
                'external_game_id' => '210',
                'english_name' => 'Mobile',
                'game_name' => '_json:{"1":"Mobile","2":"Mobile","3":"Mobile","4":"Mobile","5":"Mobile"}',
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'flash_enabled' => $db_true,
                'html_five_enabled' => $db_true,
            ],
		);

		$data = array();

		$this->load->model(['game_description_model']);

        $success=$this->game_description_model->syncGameDescription($game_descriptions);

        return $success;
	}

}
