<?php
trait game_description_uc {

    public function sync_game_description_uc (){

        $now=$this->utils->getNowForMysql();
        $api_id = UC_API;
        $db_true = 1;
        $db_false = 0;

        // echo "<pre>";
        // print_r($game_type_id);
        // die();
        $cnt=0;
        $cntInsert = 0;
        $cntUpdate = 0;
        $now = $this->utils->getNowForMysql();

        $game_type_code_slots           = SYNC::TAG_CODE_SLOT;
        $game_type_code_table_game      = SYNC::TAG_CODE_TABLE_GAMES;
        $game_type_code_unknown         = SYNC::TAG_CODE_UNKNOWN_GAME;

        // sync game type first
        // use game_type_code as key
        $game_types = [
            $game_type_code_slots => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Slot Game","2":"老虎机游戏","3":"Slot Game","4":"Slot Game","5":"Slot Game"}',
                'game_type_lang' => '_json:{"1":"Slot Game","2":"老虎机游戏","3":"Slot Game","4":"Slot Game","5":"Slot Game"}',
                'game_type_code' => $game_type_code_slots,
                'updated_at' => $now,
                'game_tag_code' => SYNC::TAG_CODE_SLOT
            ],
             $game_type_code_table_game => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Table Game","2":"桌面游戏","3":"Table Game","4":"Table Game","5":"Table Game"}',
                'game_type_lang' => '_json:{"1":"Table Game","2":"桌面游戏","3":"Table Game","4":"Table Game","5":"Table Game"}',
                'game_type_code' => $game_type_code_table_game,
                'updated_at' => $now,
                'game_type_code' => SYNC::TAG_CODE_TABLE_GAMES
            ],
            $game_type_code_unknown => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                'game_type_lang' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                "game_type_code" => $game_type_code_unknown,
                'updated_at'=>$now,
                'game_tag_code' => SYNC::TAG_CODE_UNKNOWN_GAME
            ],
        ];

        $this->load->model(['game_type_model']);
        $gameTypeCodeMaps=$this->game_type_model->syncGameTypes($game_types);
        // echo "<pre>";
        // print_r($gameTypeCodeMaps);
        // die();
        $game_descriptions = array(
            [
                'game_name' => '_json:{"1":"Nuts Commander","2":"突击队","3":"Nuts Commander","4":"Nuts Commander","5":"Nuts Commander"}',
                'game_code' => 'SlotMachine_NutsCommander',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_NutsCommander',
                'english_name' => 'Nuts Commander',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Terracota Wilds","2":"兵马俑","3":"Terracota Wilds","4":"Terracota Wilds","5":"Terracota Wilds"}',
                'game_code' => 'SlotMachine_TerracotaWilds',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_TerracotaWilds',
                'english_name' => 'Terracota Wilds',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Precious treasures","2":"潜水世界","3":"Precious treasures","4":"Precious treasures","5":"Precious treasures"}',
                'game_code' => 'SlotMachine_PreciousTreasures',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_PreciousTreasures',
                'english_name' => 'Precious treasures',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Reel Fighters","2":"街头霸王","3":"Reel Fighters","4":"Reel Fighters","5":"Reel Fighters"}',
                'game_code' => 'SlotMachine_ReelFighters',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_ReelFighters',
                'english_name' => 'Reel Fighters',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Peony Ladies","2":"窈窕美女","3":"Peony Ladies","4":"Peony Ladies","5":"Peony Ladies"}',
                'game_code' => 'SlotMachine_PeonyLadies',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_PeonyLadies',
                'english_name' => 'Peony Ladies',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Empires WarLords","2":"帝国勇士","3":"Empires WarLords","4":"Empires WarLords","5":"Empires WarLords"}',
                'game_code' => 'SlotMachine_EmpiresWarlords',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_EmpiresWarlords',
                'english_name' => 'Empires WarLords',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Live slot","2":"赌场欢乐","3":"Live slot","4":"Live slot","5":"Live slot"}',
                'game_code' => 'SlotMachine_LiveSlot',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_LiveSlot',
                'english_name' => 'Live slot',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Reel circus","2":"旋转马戏团","3":"Reel circus","4":"Reel circus","5":"Reel circus"}',
                'game_code' => 'SlotMachine_ReelCircus',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_ReelCircus',
                'english_name' => 'Reel circus',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Shogun bots","2":"机械战将","3":"Shogun bots","4":"Shogun bots","5":"Shogun bots"}',
                'game_code' => 'SlotMachine_ShogunBots',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_ShogunBots',
                'english_name' => 'Shogun bots',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Diner of fortune","2":"招财饭馆","3":"Diner of fortune","4":"Diner of fortune","5":"Diner of fortune"}',
                'game_code' => 'SlotMachine_DinerOfFortune',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_DinerOfFortune',
                'english_name' => 'Diner of fortune',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Strip to win","2":"脱衣舞男","3":"Strip to win","4":"Strip to win","5":"Strip to win"}',
                'game_code' => 'SlotMachine_StripToWin',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_StripToWin',
                'english_name' => 'Strip to win',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Forbidden slot","2":"天使与魔鬼之恋","3":"Forbidden slot","4":"Forbidden slot","5":"Forbidden slot"}',
                'game_code' => 'SlotMachine_ForbiddenSlot',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_ForbiddenSlot',
                'english_name' => 'Forbidden slot',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Steaming reels","2":"蒸汽朋克","3":"Steaming reels","4":"Steaming reels","5":"Steaming reels"}',
                'game_code' => 'SlotMachine_SteamingReels',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_SteamingReels',
                'english_name' => 'Steaming reels',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Wish list","2":"时尚心愿","3":"Wish list","4":"Wish list","5":"Wish list"}',
                'game_code' => 'SlotMachine_WishList',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_WishList',
                'english_name' => 'Wish list',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Wealth of monkeys","2":"幸运小猴","3":"Wealth of monkeys","4":"Wealth of monkeys","5":"Wealth of monkeys"}',
                'game_code' => 'SlotMachine_WealthOfTheMonkey',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_WealthOfTheMonkey',
                'english_name' => 'Wealth of monkeys',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Loot a fruit","2":"抢掠果实","3":"Loot a fruit","4":"Loot a fruit","5":"Loot a fruit"}',
                'game_code' => 'SlotMachine_LootAFruit',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_LootAFruit',
                'english_name' => 'Loot a fruit',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Pond of Koi","2":"锦鲤水池","3":"Pond of Koi","4":"Pond of Koi","5":"Pond of Koi"}',
                'game_code' => 'SlotMachine_PondOfKoi',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_PondOfKoi',
                'english_name' => 'Pond of Koi',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Royal win","2":"皇家双赢","3":"Royal win","4":"Royal win","5":"Royal win"}',
                'game_code' => 'SlotMachine_RoyalWin',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_RoyalWin',
                'english_name' => 'Royal win',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Scattered skies","2":"宇宙乾坤","3":"Scattered skies","4":"Scattered skies","5":"Scattered skies"}',
                'game_code' => 'SlotMachine_ScatteredSkies',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_ScatteredSkies',
                'english_name' => 'Scattered skies',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Scattered to hell","2":"地狱妖怪","3":"Scattered to hell","4":"Scattered to hell","5":"Scattered to hell"}',
                'game_code' => 'SlotMachine_ScatteredToHell',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_ScatteredToHell',
                'english_name' => 'Scattered to hell',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Golden Dynasty","2":"黄金盛世","3":"Golden Dynasty","4":"Golden Dynasty","5":"Golden Dynasty"}',
                'game_code' => 'SlotMachine_GoldenDynasty',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_GoldenDynasty',
                'english_name' => 'Golden Dynasty',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"88 Lucky charms","2":"吉祥发发","3":"88 Lucky charms","4":"88 Lucky charms","5":"88 Lucky charms"}',
                'game_code' => 'SlotMachine_88LuckyCharms',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_88LuckyCharms',
                'english_name' => '88 Lucky charms',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Amigos Fiesta","2":"友情盛宴","3":"Amigos Fiesta","4":"Amigos Fiesta","5":"Amigos Fiesta"}',
                'game_code' => 'SlotMachine_AmigosFiesta',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_AmigosFiesta',
                'english_name' => 'Amigos Fiesta',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Toys of Joy","2":"娃娃国土","3":"Toys of Joy","4":"Toys of Joy","5":"Toys of Joy"}',
                'game_code' => 'SlotMachine_ToysOfJoy',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_ToysOfJoy',
                'english_name' => 'Toys of Joy',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Surprising 7","2":"神妙 7","3":"Surprising 7","4":"Surprising 7","5":"Surprising 7"}',
                'game_code' => 'SlotMachine_Surprising7',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_Surprising7',
                'english_name' => 'Surprising 7',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Wild wild spin","2":"牛仔斡","3":"Wild wild spin","4":"Wild wild spin","5":"Wild wild spin"}',
                'game_code' => 'SlotMachine_WildWildSpin',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_WildWildSpin',
                'english_name' => 'Wild wild spin',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Samurai\'s Path","2":"武道","3":"Samurai\'s Path","4":"Samurai\'s Path","5":"Samurai\'s Path"}',
                'game_code' => 'SlotMachine_SamuraiPath',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_SamuraiPath',
                'english_name' => 'Samurai\'s Path',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Exploding Pirates","2":"变形海盗","3":"Exploding Pirates","4":"Exploding Pirates","5":"Exploding Pirates"}',
                'game_code' => 'SlotMachine_ExplodingPirates',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_ExplodingPirates',
                'english_name' => 'Exploding Pirates',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Secret Potion","2":"神密药水","3":"Secret Potion","4":"Secret Potion","5":"Secret Potion"}',
                'game_code' => 'SlotMachine_SecretPotion',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_SecretPotion',
                'english_name' => 'Secret Potion',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Demi Gods","2":"半神半人","3":"Demi Gods","4":"Demi Gods","5":"Demi Gods"}',
                'game_code' => 'SlotMachine_DemiGods',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_DemiGods',
                'english_name' => 'Demi Gods',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Power Pup Heroes","2":"幼仔英雄","3":"Power Pup Heroes","4":"Power Pup Heroes","5":"Power Pup Heroes"}',
                'game_code' => 'SlotMachine_PowerPupHeroes',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_PowerPupHeroes',
                'english_name' => 'Power Pup Heroes',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Stinky socks","2":"臭袜子","3":"Stinky socks","4":"Stinky socks","5":"Stinky socks"}',
                'game_code' => 'SlotMachine_StinkySocks',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_StinkySocks',
                'english_name' => 'Stinky socks',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Egyptian Rebirth","2":"重生埃及","3":"Egyptian Rebirth","4":"Egyptian Rebirth","5":"Egyptian Rebirth"}',
                'game_code' => 'SlotMachine_EgyptianRebirth',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_EgyptianRebirth',
                'english_name' => 'Egyptian Rebirth',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Irish Charm","2":"仙童之宝","3":"Irish Charm","4":"Irish Charm","5":"Irish Charm"}',
                'game_code' => 'SlotMachine_IrishCharms',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_IrishCharms',
                'english_name' => 'Irish Charm',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Santa Wild Helpers","2":"圣诞野性助手","3":"Santa Wild Helpers","4":"Santa Wild Helpers","5":"Santa Wild Helpers"}',
                'game_code' => 'SlotMachine_SantaWildHelpers',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_SantaWildHelpers',
                'english_name' => 'Santa Wild Helpers',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Greedy Servants","2":"贪婪仆人","3":"Greedy Servants","4":"Greedy Servants","5":"Greedy Servants"}',
                'game_code' => 'SlotMachine_GreedyServants',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_GreedyServants',
                'english_name' => 'Greedy Servants',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Iron Assassins","2":"杀人狂魔","3":"Iron Assassins","4":"Iron Assassins","5":"Iron Assassins"}',
                'game_code' => 'SlotMachine_IronAssassins',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_IronAssassins',
                'english_name' => 'Iron Assassins',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Fire&Ice","2":"冰焰战略","3":"Fire&Ice","4":"Fire&Ice","5":"Fire&Ice"}',
                'game_code' => 'SlotMachine_FireIce',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_FireIce',
                'english_name' => 'Fire&Ice',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Forest Harmony","2":"大自然和谐","3":"Forest Harmony","4":"Forest Harmony","5":"Forest Harmony"}',
                'game_code' => 'SlotMachine_ForestHarmony',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_ForestHarmony',
                'english_name' => 'Forest Harmony',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"9 Figures Club","2":"豪华派","3":"9 Figures Club","4":"9 Figures Club","5":"9 Figures Club"}',
                'game_code' => 'SlotMachine_9FiguresClub',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_9FiguresClub',
                'english_name' => '9 Figures Club',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Blazing Tires","2":"炽烈卡车","3":"Blazing Tires","4":"Blazing Tires","5":"Blazing Tires"}',
                'game_code' => 'SlotMachine_BlazingTires',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_BlazingTires',
                'english_name' => 'Blazing Tires',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Candy slot twins","2":"双胞胎糖果","3":"Candy slot twins","4":"Candy slot twins","5":"Candy slot twins"}',
                'game_code' => 'SlotMachine_CandySlotTwins',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_CandySlotTwins',
                'english_name' => 'Candy slot twins',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Cats gone wild","2":"狂猫蹦迪","3":"Cats gone wild","4":"Cats gone wild","5":"Cats gone wild"}',
                'game_code' => 'SlotMachine_CatsGoneWild',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_CatsGoneWild',
                'english_name' => 'Cats gone wild',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Jade Connection","2":"翡翠玉石","3":"Jade Connection","4":"Jade Connection","5":"Jade Connection"}',
                'game_code' => 'SlotMachine_JadeConnection',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_JadeConnection',
                'english_name' => 'Jade Connection',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Master Panda","2":"熊猫厨师","3":"Master Panda","4":"Master Panda","5":"Master Panda"}',
                'game_code' => 'SlotMachine_MasterPanda',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_MasterPanda',
                'english_name' => 'Master Panda',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Slot bound","2":"巫婆世纪","3":"Slot bound","4":"Slot bound","5":"Slot bound"}',
                'game_code' => 'SlotMachine_SlotBound',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_SlotBound',
                'english_name' => 'Slot bound',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Slotsaurus","2":"恐龙机","3":"Slotsaurus","4":"Slotsaurus","5":"Slotsaurus"}',
                'game_code' => 'SlotMachine_Slotosaurus',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_Slotosaurus',
                'english_name' => 'Slotsaurus',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Soccer babes","2":"足球女郎","3":"Soccer babes","4":"Soccer babes","5":"Soccer babes"}',
                'game_code' => 'SlotMachine_SoccerBabes',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_SoccerBabes',
                'english_name' => 'Soccer babes',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Tennis Champions","2":"网球王子","3":"Tennis Champions","4":"Tennis Champions","5":"Tennis Champions"}',
                'game_code' => 'SlotMachine_TennisChampion',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_TennisChampion',
                'english_name' => 'Tennis Champions',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Year of the monkey","2":"猴年","3":"Year of the monkey","4":"Year of the monkey","5":"Year of the monkey"}',
                'game_code' => 'SlotMachine_YearOfTheMonkey',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_YearOfTheMonkey',
                'english_name' => 'Year of the monkey',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Very Big Goats","2":"喜洋洋灰太狼","3":"Very Big Goats","4":"Very Big Goats","5":"Very Big Goats"}',
                'game_code' => 'SlotMachine_VeryBigGoats',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_VeryBigGoats',
                'english_name' => 'Very Big Goats',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Fortune Keepers","2":"财富守护使","3":"Fortune Keepers","4":"Fortune Keepers","5":"Fortune Keepers"}',
                'game_code' => 'SlotMachine_FortuneKeepers',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_FortuneKeepers',
                'english_name' => 'Fortune Keepers',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Zombie slot mania","2":"马尼亚僵尸症","3":"Zombie slot mania","4":"Zombie slot mania","5":"Zombie slot mania"}',
                'game_code' => 'SlotMachine_ZombieSlotmania',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_ZombieSlotmania',
                'english_name' => 'Zombie slot mania',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"8 Lucky Charms","2":"幸运8","3":"8 Lucky Charms","4":"8 Lucky Charms","5":"8 Lucky Charms"}',
                'game_code' => 'SlotMachine_8LuckyCharms',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_8LuckyCharms',
                'english_name' => '8 Lucky Charms',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Atlantic Treasures","2":"亚特兰蒂斯寻宝","3":"Atlantic Treasures","4":"Atlantic Treasures","5":"Atlantic Treasures"}',
                'game_code' => 'SlotMachine_AtlanticTreasures',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_AtlanticTreasures',
                'english_name' => 'Atlantic Treasures',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Code Name: Jackpot","2":"代号:头奖","3":"Code Name: Jackpot","4":"Code Name: Jackpot","5":"Code Name: Jackpot"}',
                'game_code' => 'SlotMachine_CodeNameJackpot',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_CodeNameJackpot',
                'english_name' => 'Code Name: Jackpot',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Farm of fun","2":"娱乐农场","3":"Farm of fun","4":"Farm of fun","5":"Farm of fun"}',
                'game_code' => 'SlotMachine_FarmOfFun',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_FarmOfFun',
                'english_name' => 'Farm of fun',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Bikers Gang","2":"摩托党","3":"Bikers Gang","4":"Bikers Gang","5":"Bikers Gang"}',
                'game_code' => 'SlotMachine_BikersGang',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_BikersGang',
                'english_name' => 'Bikers Gang',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Eat them all","2":"食肉植物","3":"Eat them all","4":"Eat them all","5":"Eat them all"}',
                'game_code' => 'SlotMachine_EatThemAll',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_EatThemAll',
                'english_name' => 'Eat them all',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Egyptian adventure","2":"冒险埃及","3":"Egyptian adventure","4":"Egyptian adventure","5":"Egyptian adventure"}',
                'game_code' => 'SlotMachine_EgyptianAdventure',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_EgyptianAdventure',
                'english_name' => 'Egyptian adventure',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Gangster\'s slot","2":"黑手党","3":"Gangster\'s slot","4":"Gangster\'s slot","5":"Gangster\'s slot"}',
                'game_code' => 'SlotMachine_GangsterSlots',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_GangsterSlots',
                'english_name' => 'Gangster\'s slot',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Gods Of Slots","2":"老虎机之神","3":"Gods Of Slots","4":"Gods Of Slots","5":"Gods Of Slots"}',
                'game_code' => 'SlotMachine_GodsOfSlots',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_GodsOfSlots',
                'english_name' => 'Gods Of Slots',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Hawaii Vacation","2":"夏威夷假期","3":"Hawaii Vacation","4":"Hawaii Vacation","5":"Hawaii Vacation"}',
                'game_code' => 'SlotMachine_HawaiiVacation',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_HawaiiVacation',
                'english_name' => 'Hawaii Vacation',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Lucky Miners","2":"幸运矿工","3":"Lucky Miners","4":"Lucky Miners","5":"Lucky Miners"}',
                'game_code' => 'SlotMachine_LuckyMiners',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_LuckyMiners',
                'english_name' => 'Lucky Miners',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Safari Samba","2":"草原桑巴","3":"Safari Samba","4":"Safari Samba","5":"Safari Samba"}',
                'game_code' => 'SlotMachine_SafariSamba',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_SafariSamba',
                'english_name' => 'Safari Samba',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Undying Passion","2":"不灭激情","3":"Undying Passion","4":"Undying Passion","5":"Undying Passion"}',
                'game_code' => 'SlotMachine_UndyingPassion',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_UndyingPassion',
                'english_name' => 'Undying Passion',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Viking\'s Glory","2":"维京人之荣","3":"Viking\'s Glory","4":"Viking\'s Glory","5":"Viking\'s Glory"}',
                'game_code' => 'SlotMachine_VikingsGlory',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_VikingsGlory',
                'english_name' => 'Viking\'s Glory',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Wacky monsters","2":"疯狂怪物","3":"Wacky monsters","4":"Wacky monsters","5":"Wacky monsters"}',
                'game_code' => 'SlotMachine_WackyMonsters',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_WackyMonsters',
                'english_name' => 'Wacky monsters',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Year of luck","2":"幸运年","3":"Year of luck","4":"Year of luck","5":"Year of luck"}',
                'game_code' => 'SlotMachine_YearOfLuck',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_YearOfLuck',
                'english_name' => 'Year of luck',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"May Dance Festival","2":"舞月狂欢","3":"May Dance Festival","4":"May Dance Festival","5":"May Dance Festival"}',
                'game_code' => 'SlotMachine_MayDanceFestival',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_MayDanceFestival',
                'english_name' => 'May Dance Festival',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Abundance Spell","2":"财富魔法","3":"Abundance Spell","4":"Abundance Spell","5":"Abundance Spell"}',
                'game_code' => 'SlotMachine_AbundanceSpell',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_AbundanceSpell',
                'english_name' => 'Abundance Spell',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Nights Of Fortune","2":"淘金之夜","3":"Nights Of Fortune","4":"Nights Of Fortune","5":"Nights Of Fortune"}',
                'game_code' => 'SlotMachine_NightsOfFortune',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_NightsOfFortune',
                'english_name' => 'Nights Of Fortune',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Tasty Win","2":"美味甜心","3":"Tasty Win","4":"Tasty Win","5":"Tasty Win"}',
                'game_code' => 'SlotMachine_TastyWin',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_TastyWin',
                'english_name' => 'Tasty Win',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Fluffy Slot","2":"绒毛之恋","3":"Fluffy Slot","4":"Fluffy Slot","5":"Fluffy Slot"}',
                'game_code' => 'SlotMachine_FluffySlot',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_FluffySlot',
                'english_name' => 'Fluffy Slot',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Red Square Games","2":"红场竞技","3":"Red Square Games","4":"Red Square Games","5":"Red Square Games"}',
                'game_code' => 'Lottery_RedSquareGames',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Lottery_RedSquareGames',
                'english_name' => 'Red Square Games',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Super Mask","2":"超级面具","3":"Super Mask","4":"Super Mask","5":"Super Mask"}',
                'game_code' => 'Lottery_SuperMask',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Lottery_SuperMask',
                'english_name' => 'Super Mask',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Donut Rush","2":"甜甜圈之恋","3":"Donut Rush","4":"Donut Rush","5":"Donut Rush"}',
                'game_code' => 'Lottery_DonutRush',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Lottery_DonutRush',
                'english_name' => 'Donut Rush',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Chest Of Fortunes","2":"富贵宝库","3":"Chest Of Fortunes","4":"Chest Of Fortunes","5":"Chest Of Fortunes"}',
                'game_code' => 'SlotMachine_ChestOfFortunes',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_ChestOfFortunes',
                'english_name' => 'Chest Of Fortunes',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'dlc_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                'english_name' => 'Unknown',
                'game_platform_id' => $api_id,
                'game_code' => 'unknown',
                'external_game_id' => 'unknown',
                'flash_enabled' => $db_true,
                'flag_show_in_site' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_unknown],
            ],
            [
                'game_name' => '_json:{"1":"Lotus Kingdom","2":"莲花王国","3":"Lotus Kingdom","4":"Lotus Kingdom","5":"Lotus Kingdom"}',
                'game_code' => 'SlotMachine_LotusKingdom',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_LotusKingdom',
                'english_name' => 'Lotus Kingdom',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Hunting Treasures","2":"大海寻珍","3":"Hunting Treasures","4":"Hunting Treasures","5":"Hunting Treasures"}',
                'game_code' => 'SlotMachine_HuntingTreasures',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_HuntingTreasures',
                'english_name' => 'Hunting Treasures',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Bugs Tale","2":"虫虫世界","3":"Bugs Tale","4":"Bugs Tale","5":"Bugs Tale"}"}',
                'game_code' => 'SlotMachine_BugsTale',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_BugsTale',
                'english_name' => 'Bugs Tale',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Signs Of Fortune","2":"财富神符","3":"Signs Of Fortune","4":"Signs Of Fortune","5":"Signs Of Fortune"}',
                'game_code' => 'Lottery_SignsOfFortune',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Lottery_SignsOfFortune',
                'english_name' => 'Signs Of Fortune',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Scratchy Bit","2":"刮刮乐园","3":"Scratchy Bit","4":"Scratchy Bit","5":"Scratchy Bit"}',
                'game_code' => 'Lottery_ScratchyBit',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Lottery_ScratchyBit',
                'english_name' => 'Scratchy Bit',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Secret Cupcakes","2":"神秘蛋糕","3":"Secret Cupcakes","4":"Secret Cupcakes","5":"Secret Cupcakes"}',
                'game_code' => 'Lottery_SecretCupcakes',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Lottery_SecretCupcakes',
                'english_name' => 'Secret Cupcakes',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Monsters’ Scratch","2":"怪兽刮刮乐","3":"Monsters’ Scratch","4":"Monsters’ Scratch","5":"Monsters’ Scratch"}',
                'game_code' => 'Lottery_MonsterScratch',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Lottery_MonsterScratch',
                'english_name' => 'Monsters’ Scratch',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Monsters’ Scratch","2":"怪兽刮刮乐","3":"Monsters’ Scratch","4":"Monsters’ Scratch","5":"Monsters’ Scratch"}',
                'game_code' => 'Lottery_MonsterScratch',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Lottery_MonsterScratch',
                'english_name' => 'Monsters’ Scratch',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"SlotNRoll","2":"摇滚老虎机","3":"SlotNRoll","4":"SlotNRoll","5":"SlotNRoll"}',
                'game_code' => 'SlotMachine_SlotNRoll',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_SlotNRoll',
                'english_name' => 'SlotNRoll',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Donut Rush","2":"甜甜圈之恋","3":"Donut Rush","4":"Donut Rush","5":"Donut Rush"}',
                'game_code' => 'Lottery_DonutsRush',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Lottery_DonutsRush',
                'english_name' => 'Donut Rush',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"4 Winning Directions","2":"财进四方","3":"4 Winning Directions","4":"4 Winning Directions","5":"4 Winning Directions"}',
                'game_code' => 'SlotMachine_4WinningDirections',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_4WinningDirections',
                'english_name' => '4 Winning Directions',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"European Roulette","2":"欧洲轮盘","3":"European Roulette","4":"European Roulette","5":"European Roulette"}',
                'game_code' => 'Table_EuropeanRoulette',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Table_EuropeanRoulette',
                'english_name' => 'European Roulette',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_table_game],
            ],
            [
                'game_name' => '_json:{"1":"Reviving Love","2":"再续前缘","3":"Reviving Love","4":"Reviving Love","5":"Reviving Love"}',
                'game_code' => 'SlotMachine_RevivingLove',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_RevivingLove',
                'english_name' => 'Reviving Love',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Snowing Luck","2":"瑞雪丰财","3":"Snowing Luck","4":"Snowing Luck","5":"Snowing Luck"}',
                'game_code' => 'SlotMachine_SnowingLuck',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_SnowingLuck',
                'english_name' => 'Snowing Luck',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"8 Lucky Charms Xtreme","2":"超级幸运8","3":"8 Lucky Charms Xtreme","4":"8 Lucky Charms Xtreme","5":"8 Lucky Charms Xtreme"}',
                'game_code' => 'SlotMachine_8LuckyCharmsXtreme',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_8LuckyCharmsXtreme',
                'english_name' => '8 Lucky Charms Xtreme',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Lilith\'s Passion","2":"莉莉斯激情","3":"Lilith\'s Passion","4":"Lilith\'s Passion","5":"Lilith\'s Passion"}',
                'game_code' => 'SlotMachine_LilithPassion',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_LilithPassion',
                'english_name' => 'Lilith\'s Passion',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Wild Heist","2":"动物总动员","3":"Wild Heist","4":"Wild Heist","5":"Wild Heist"}',
                'game_code' => 'SlotMachine_WildHeist',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_WildHeist',
                'english_name' => 'Wild Heist',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Hunting Treasures Deluxe","2":"大海寻珍:豪华版","3":"Hunting Treasures Deluxe","4":"Hunting Treasures Deluxe","5":"Hunting Treasures Deluxe"}',
                'game_code' => 'SlotMachine_HuntingTreasuresDeluxe',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_HuntingTreasuresDeluxe',
                'english_name' => 'Hunting Treasures Deluxe',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Tiki Rainbow","2":"提基彩虹","3":"Tiki Rainbow","4":"Tiki Rainbow","5":"Tiki Rainbow"}',
                'game_code' => 'SlotMachine_TikiRainbow',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_TikiRainbow',
                'english_name' => 'Tiki Rainbow',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Book Of Guardians","2":"天神宝典","3":"Book Of Guardians","4":"Book Of Guardians","5":"Book Of Guardians"}',
                'game_code' => 'SlotMachine_BookOfGuardians',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_BookOfGuardians',
                'english_name' => 'Book Of Guardians',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"Demi Gods II","2":"半神半人 II","3":"Demi Gods II","4":"Demi Gods II","5":"Demi Gods II"}',
                'game_code' => 'SlotMachine_DemiGods2',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SlotMachine_DemiGods2',
                'english_name' => 'Demi Gods II',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
        );

        $data = array();
        echo "<pre>";
        foreach ($game_descriptions as $game_list) {


            $game_code_exist = $this->db->select('COUNT(id) as count')
                                ->where('game_code', $game_list['game_code'])
                                ->where('game_platform_id', $api_id)
                                ->get('game_description')
                                ->row();

            if( $game_code_exist->count <= 0 ) {
                $game_list['created_on'] =  $now;
                $this->db->insert('game_description', $game_list);
                echo '=================================== Inserted games ==============================';
            $cntInsert++;
            }else{
                $game_list['updated_at'] =  $now;
                $this->db->where('game_code', $game_list['game_code']);
                $this->db->where('game_platform_id', $api_id);
                $this->db->update('game_description', $game_list);
                echo '=================================== Updated games ==============================';
            $cntUpdate++;
            }
            print_r($game_list);

        }
        echo "Total Inserted: " . $cntInsert . "<br>";
        echo "Total Updated: " . $cntUpdate;
    }
}