<?php
trait game_description_ebetbbtech {

	public function sync_game_description_ebetbbtech(){
		$cnt=0;
		$cntInsert = 0;
		$cntUpdate = 0;

		$db_true = 1;
		$db_false = 0;
		$api_id = EBET_BBTECH_API;

        $game_type_code_slots           = SYNC::TAG_CODE_SLOT;
        $game_type_code_other_games     = SYNC::TAG_CODE_OTHER;
        $game_type_code_unknown         = SYNC::TAG_CODE_UNKNOWN_GAME;

		// sync game type first
		// use game_type_code as key
		$game_types = [
            $game_type_code_slots => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Slot Game","2":"老虎机游戏","3":"Slot Game","4":"Slot Game","5":"Slot Game"}',
                'game_type_lang' => '_json:{"1":"Slot Game","2":"老虎机游戏","3":"Slot Game","4":"Slot Game","5":"Slot Game"}',
                'game_type_code' => $game_type_code_slots,
                'game_tag_code' => $game_type_code_slots,
            ],
            $game_type_code_other_games => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Others","2":"其它游戏","3":"Others","4":"Others"}',
                'game_type_lang' => '_json:{"1":"Others","2":"其它游戏","3":"Others","4":"Others"}',
                "game_type_code" => $game_type_code_other_games,
                "game_tag_code" => $game_type_code_other_games
            ],
            $game_type_code_unknown => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Unknown","2":"不明类型","3":"Unknown","4":"Unknown","5":"Unknown"}',
                "game_type_code" => $game_type_code_unknown,
                "game_tag_code" => $game_type_code_unknown,
                'flag_show_in_site' => $db_false,
            ],
		];


		$this->load->model(['game_type_model']);
		//this code is checking the game type table with game
		//also insertion of new game type based on game_type_code
		// 'game_type_id' => $gameTypeCodeMaps[$game_type_code_table_game],
		$gameTypeCodeMaps=$this->game_type_model->syncGameTypes($game_types);
		// echo "<pre>";
		// print_r($gameTypeCodeMaps);
		// die();
		$this->utils->debug_log('gameTypeCodeMaps', $gameTypeCodeMaps);

		$game_descriptions = array(
			#====================================start cascade Game list=========================================
			[
                'game_name' => '_json:{"1":"special guidance","2":"special guidance","3":"special guidance","4":"special guidance","5":"special guidance"}',
                'game_code' => '367',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '367',
                'english_name' => 'special guidance',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"yui uehara 3","2":"yui uehara 3","3":"yui uehara 3","4":"yui uehara 3","5":"yui uehara 3"}',
                'game_code' => '369',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '369',
                'english_name' => 'yui uehara 3',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"yui uehara 2","2":"yui uehara 2","3":"yui uehara 2","4":"yui uehara 2","5":"yui uehara 2"}',
                'game_code' => '361',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '361',
                'english_name' => 'yui uehara 2',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
              [
                'game_name' => '_json:{"1":"rin azuma chaku ero","2":"rin azuma chaku ero","3":"rin azuma chaku ero","4":"rin azuma chaku ero","5":"rin azuma chaku ero"}',
                'game_code' => '359',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '359',
                'english_name' => 'rin azuma chaku ero',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"alice","2":"alice","3":"alice","4":"alice","5":"alice"}',
                'game_code' => '356',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '356',
                'english_name' => 'alice',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"girl prison","2":"girl prison","3":"girl prison","4":"girl prison","5":"girl prison"}',
                'game_code' => '360',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '360',
                'english_name' => 'girl prison',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"jibril","2":"jibril","3":"jibril","4":"jibril","5":"jibril"}',
                'game_code' => '358',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '358',
                'english_name' => 'jibril',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"sister wife","2":"sister wife","3":"sister wife","4":"sister wife","5":"sister wife"}',
                'game_code' => '357',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '357',
                'english_name' => 'sister wife',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"lust tram","2":"lust tram","3":"lust tram","4":"lust tram","5":"lust tram"}',
                'game_code' => '353',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '353',
                'english_name' => 'lust tram',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"foretelling cards","2":"foretelling cards","3":"foretelling cards","4":"foretelling cards","5":"foretelling cards"}',
                'game_code' => '352',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '352',
                'english_name' => 'foretelling cards',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"starfleet","2":"starfleet","3":"starfleet","4":"starfleet","5":"starfleet"}',
                'game_code' => '350',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '350',
                'english_name' => 'starfleet',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"darkness","2":"darkness","3":"darkness","4":"darkness","5":"darkness"}',
                'game_code' => '349',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '349',
                'english_name' => 'darkness',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"ayu sadist 4xfuck","2":"ayu sadist 4xfuck","3":"ayu sadist 4xfuck","4":"ayu sadist 4xfuck","5":"ayu sadist 4xfuck"}',
                'game_code' => '345',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '345',
                'english_name' => 'ayu sadist 4xfuck',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"the youkai club","2":"the youkai club","3":"the youkai club","4":"the youkai club","5":"the youkai club"}',
                'game_code' => '348',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '348',
                'english_name' => 'the youkai club',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"blades","2":"blades","3":"blades","4":"blades","5":"blades"}',
                'game_code' => '344',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '344',
                'english_name' => 'blades',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"edo sushi","2":"edo sushi","3":"edo sushi","4":"edo sushi","5":"edo sushi"}',
                'game_code' => '347',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '347',
                'english_name' => 'edo sushi',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"mysterious cave","2":"mysterious cave","3":"mysterious cave","4":"mysterious cave","5":"mysterious cave"}',
                'game_code' => '346',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '346',
                'english_name' => 'mysterious cave',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"rin azuma slot 1","2":"rin azuma slot 1","3":"rin azuma slot 1","4":"rin azuma slot 1","5":"rin azuma slot 1"}',
                'game_code' => '342',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '342',
                'english_name' => 'rin azuma slot 1',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"rin azuma slot 2","2":"rin azuma slot 2","3":"rin azuma slot 2","4":"rin azuma slot 2","5":"rin azuma slot 2"}',
                'game_code' => '343',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '343',
                'english_name' => 'rin azuma slot 2',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"ayu masochist g-cup beauty girl","2":"ayu masochist g-cup beauty girl","3":"ayu masochist g-cup beauty girl","4":"ayu masochist g-cup beauty girl","5":"ayu masochist g-cup beauty girl"}',
                'game_code' => '340',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '340',
                'english_name' => 'ayu masochist g-cup beauty girl',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"yariman academy","2":"yariman academy","3":"yariman academy","4":"yariman academy","5":"yariman academy"}',
                'game_code' => '326',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '326',
                'english_name' => 'yariman academy',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"kuroinu","2":"kuroinu","3":"kuroinu","4":"kuroinu","5":"kuroinu"}',
                'game_code' => '297',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '297',
                'english_name' => 'kuroinu',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"sei shohjyo","2":"sei shohjyo","3":"sei shohjyo","4":"sei shohjyo","5":"sei shohjyo"}',
                'game_code' => '296',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '296',
                'english_name' => 'sei shohjyo',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"GFxGFxGF","2":"GFxGFxGF","3":"GFxGFxGF","4":"GFxGFxGF","5":"GFxGFxGF"}',
                'game_code' => '339',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '339',
                'english_name' => 'GFxGFxGF',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"oshiete ne:maid","2":"oshiete ne:maid","3":"oshiete ne:maid","4":"oshiete ne:maid","5":"oshiete ne:maid"}',
                'game_code' => '338',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '338',
                'english_name' => 'oshiete ne:maid',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"wife & mama mega boobs","2":"wife & mama mega boobs","3":"wife & mama mega boobs","4":"wife & mama mega boobs","5":"wife & mama mega boobs"}',
                'game_code' => '337',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '337',
                'english_name' => 'wife & mama mega boobs',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"megachu","2":"megachu","3":"megachu","4":"megachu","5":"megachu"}',
                'game_code' => '336',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '336',
                'english_name' => 'megachu',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"classmate f?cker","2":"classmate f?cker","3":"classmate f?cker","4":"classmate f?cker","5":"classmate f?cker"}',
                'game_code' => '333',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '333',
                'english_name' => 'classmate f?cker',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"hugyou","2":"hugyou","3":"hugyou","4":"hugyou","5":"hugyou"}',
                'game_code' => '332',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '332',
                'english_name' => 'hugyou',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"my sisters","2":"my sisters","3":"my sisters","4":"my sisters","5":"my sisters"}',
                'game_code' => '331',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '331',
                'english_name' => 'my sisters',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"wakatsuki shelby","2":"wakatsuki shelby","3":"wakatsuki shelby","4":"wakatsuki shelby","5":"wakatsuki shelby"}',
                'game_code' => '316',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '316',
                'english_name' => 'wakatsuki shelby',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"wakatsuki shelby 2","2":"wakatsuki shelby 2","3":"wakatsuki shelby 2","4":"wakatsuki shelby 2","5":"wakatsuki shelby 2"}',
                'game_code' => '329',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '329',
                'english_name' => 'wakatsuki shelby 2',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"wakatsuki shelby 3","2":"wakatsuki shelby 3","3":"wakatsuki shelby 3","4":"wakatsuki shelby 3","5":"wakatsuki shelby 3"}',
                'game_code' => '330',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '330',
                'english_name' => 'wakatsuki shelby 3',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"mahou syoujyo","2":"mahou syoujyo","3":"mahou syoujyo","4":"mahou syoujyo","5":"mahou syoujyo"}',
                'game_code' => '267',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '267',
                'english_name' => 'mahou syoujyo',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"dekakute","2":"dekakute","3":"dekakute","4":"dekakute","5":"dekakute"}',
                'game_code' => '269',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '269',
                'english_name' => 'dekakute',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"chobatsu shido","2":"chobatsu shido","3":"chobatsu shido","4":"chobatsu shido","5":"chobatsu shido"}',
                'game_code' => '270',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '270',
                'english_name' => 'chobatsu shido',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"resort boin","2":"resort boin","3":"resort boin","4":"resort boin","5":"resort boin"}',
                'game_code' => '265',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '265',
                'english_name' => 'resort boin',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"onmyouji","2":"onmyouji","3":"onmyouji","4":"onmyouji","5":"onmyouji"}',
                'game_code' => '271',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '271',
                'english_name' => 'onmyouji',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"you will be more and more hard","2":"you will be more and more hard","3":"you will be more and more hard","4":"you will be more and more hard","5":"you will be more and more hard"}',
                'game_code' => '273',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '273',
                'english_name' => 'you will be more and more hard',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"bible black","2":"bible black","3":"bible black","4":"bible black","5":"bible black"}',
                'game_code' => '272',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '272',
                'english_name' => 'bible black',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"pleas rape me","2":"pleas rape me","3":"pleas rape me","4":"pleas rape me","5":"pleas rape me"}',
                'game_code' => '276',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '276',
                'english_name' => 'pleas rape me',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"kunoichi sakuya","2":"kunoichi sakuya","3":"kunoichi sakuya","4":"kunoichi sakuya","5":"kunoichi sakuya"}',
                'game_code' => '292',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '292',
                'english_name' => 'kunoichi sakuya',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"oppai no ohjya 48","2":"oppai no ohjya 48","3":"oppai no ohjya 48","4":"oppai no ohjya 48","5":"oppai no ohjya 48"}',
                'game_code' => '293',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '293',
                'english_name' => 'oppai no ohjya 48',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"yokujtho bazooka","2":"yokujtho bazooka","3":"yokujtho bazooka","4":"yokujtho bazooka","5":"yokujtho bazooka"}',
                'game_code' => '291',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '291',
                'english_name' => 'yokujtho bazooka',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"syohjyo x syohjyo x syohjyo","2":"syohjyo x syohjyo x syohjyo","3":"syohjyo x syohjyo x syohjyo","4":"syohjyo x syohjyo x syohjyo","5":"syohjyo x syohjyo x syohjyo"}',
                'game_code' => '317',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '317',
                'english_name' => 'syohjyo x syohjyo x syohjyo',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
            [
                'game_name' => '_json:{"1":"yakin byoutou","2":"yakin byoutou","3":"yakin byoutou","4":"yakin byoutou","5":"yakin byoutou"}',
                'game_code' => '294',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '294',
                'english_name' => 'yakin byoutou',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
            ],
			#====================================End Game list=========================================

			#====================================start cascade Game list=========================================
			[
                'game_name' => '_json:{"1":"byakuya lin ne","2":"byakuya lin ne","3":"byakuya lin ne","4":"byakuya lin ne","5":"byakuya lin ne"}',
                'game_code' => '283',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '283',
                'english_name' => 'byakuya lin ne',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_other_games],
            ],
            [
                'game_name' => '_json:{"1":"kunoichi sakuya","2":"kunoichi sakuya","3":"kunoichi sakuya","4":"kunoichi sakuya","5":"kunoichi sakuya"}',
                'game_code' => '285',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '285',
                'english_name' => 'kunoichi sakuya',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_other_games],
            ],
            [
                'game_name' => '_json:{"1":"oppai no ohjya 48","2":"oppai no ohjya 48","3":"oppai no ohjya 48","4":"oppai no ohjya 48","5":"oppai no ohjya 48"}',
                'game_code' => '288',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '288',
                'english_name' => 'oppai no ohjya 48',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_other_games],
            ],
            [
                'game_name' => '_json:{"1":"yakin byouto","2":"yakin byouto","3":"yakin byouto","4":"yakin byouto","5":"yakin byouto"}',
                'game_code' => '290',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '290',
                'english_name' => 'yakin byouto',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_other_games],
            ],
            [
                'game_name' => '_json:{"1":"kuroinu","2":"kuroinu","3":"kuroinu","4":"kuroinu","5":"kuroinu"}',
                'game_code' => '286',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '286',
                'english_name' => 'kuroinu',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_other_games],
            ],
            [
                'game_name' => '_json:{"1":"hemekishi olivia","2":"hemekishi olivia","3":"hemekishi olivia","4":"hemekishi olivia","5":"hemekishi olivia"}',
                'game_code' => '284',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '284',
                'english_name' => 'hemekishi olivia',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_other_games],
            ],
            [
                'game_name' => '_json:{"1":"sei syohjyo","2":"sei syohjyo","3":"sei syohjyo","4":"sei syohjyo","5":"sei syohjyo"}',
                'game_code' => '289',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '289',
                'english_name' => 'sei syohjyo',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_other_games],
            ],
            [
                'game_name' => '_json:{"1":"koakuma kanojyo","2":"koakuma kanojyo","3":"koakuma kanojyo","4":"koakuma kanojyo","5":"koakuma kanojyo"}',
                'game_code' => '281',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '281',
                'english_name' => 'koakuma kanojyo',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_other_games],
            ],
            [
                'game_name' => '_json:{"1":"nozokiana","2":"nozokiana","3":"nozokiana","4":"nozokiana","5":"nozokiana"}',
                'game_code' => '282',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '282',
                'english_name' => 'nozokiana',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_other_games],
            ],
            [
                'game_name' => '_json:{"1":"dekakute h na ore no ane","2":"dekakute h na ore no ane","3":"dekakute h na ore no ane","4":"dekakute h na ore no ane","5":"dekakute h na ore no ane"}',
                'game_code' => '280',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '280',
                'english_name' => 'dekakute h na ore no ane',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_other_games],
            ],
            [
                'game_name' => '_json:{"1":"mahjong","2":"mahjong","3":"mahjong","4":"mahjong","5":"mahjong"}',
                'game_code' => '287',
                'html_five_enabled' => $db_true,
                'game_platform_id' => $api_id,
                'external_game_id' => '287',
                'english_name' => 'mahjong',
                'flash_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_other_games],
            ],
            [
                'game_name' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                'game_code' => 'unknown',
                'game_platform_id' => $api_id,
                'external_game_id' => 'unknown',
                'english_name' => 'Unknown',
                'status' => $db_true,
                'flag_show_in_site' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_unknown],
            ],

            #====================================End Game list=========================================
		);

		$this->load->model(['game_description_model']);

		$success=$this->game_description_model->syncGameDescription($game_descriptions);

		return $success;
	}

}
