<?php
trait game_description_whitelabel {

	public function sync_game_description_whitelabel(){
		$cnt=0;
		$cntInsert = 0;
		$cntUpdate = 0;

		$db_true = 1;
		$db_false = 0;
		$api_id = SBOBET_API;
		$now = $this->utils->getNowForMysql();

        $game_type_code_sport = "white_label_sport";
        $game_type_code_casino = "white_label_casino";
        $game_type_code_unknown = "white_label_unknown";


		// sync game type first
		// use game_type_code as key
		$game_types = [
            $game_type_code_sport => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Sports Book"}',
                'game_type_lang' => '_json:{"1":"Sports Book"}',
                'game_type_code' => $game_type_code_sport,
                'flag_show_in_site' => $db_true,
                'auto_add_new_game' => $db_true,
                'auto_add_to_cashback' => $db_true,
                'status' => $db_true,
                'updated_at' => $now,
                'game_tag_code' => SYNC::TAG_CODE_SPORTS
            ],
            $game_type_code_casino => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Casino"}',
                'game_type_lang' => '_json:{"1":"Casino"}',
                'game_type_code' => $game_type_code_casino,
                'flag_show_in_site' => $db_true,
                'auto_add_new_game' => $db_true,
                'auto_add_to_cashback' => $db_true,
                'status' => $db_true,
                'updated_at' => $now,
                'game_tag_code' => SYNC::TAG_CODE_CASINO
            ],
            $game_type_code_unknown => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Unknown","2":"不明类型","3":"Unknown","4":"Unknown"}',
                'game_type_lang' => '_json:{"1":"Unknown","2":"不明类型","3":"Unknown","4":"Unknown"}',
                "game_type_code" => $game_type_code_unknown,
                'flag_show_in_site' => $db_true,
                'auto_add_new_game' => $db_true,
                'auto_add_to_cashback' => $db_true,
                'status'=>$db_true,
                'updated_at'=>$now,
                'game_tag_code' => SYNC::TAG_CODE_UNKNOWN_GAME
            ],
		];


		$this->load->model(['game_type_model']);
		//this code is checking the game type table with game
		//also insertion of new game type based on game_type_code
		// 'game_type_id' => $gameTypeCodeMaps[$game_type_code_table_game],
		$gameTypeCodeMaps=$this->game_type_model->syncGameTypes($game_types);
		// echo "<pre>";
		// print_r($gameTypeCodeMaps);
		// die();
		$this->utils->debug_log('gameTypeCodeMaps', $gameTypeCodeMaps);

		$game_descriptions = array(
            #================================================== Sports Game ========================================
            [
                'game_name' => '_json:{"1":"Football","2":"Football","3":"Football","4":"Football","5":"Football"}',
                'game_code' => 'Football',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Football',
                'english_name' => 'Football',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sport],
                'flag_show_in_site' => $db_true,
                'status' =>  $db_true,
                'mobile_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Basketball","2":"Basketball","3":"Basketball","4":"Basketball","5":"Basketball"}',
                'game_code' => 'Basketball',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Basketball',
                'english_name' => 'Basketball',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sport],
                'flag_show_in_site' => $db_true,
                'status' =>  $db_true,
                'mobile_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Baseball","2":"Baseball","3":"Baseball","4":"Baseball","5":"Baseball"}',
                'game_code' => 'Baseball',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Baseball',
                'english_name' => 'Baseball',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sport],
                'flag_show_in_site' => $db_true,
                'status' =>  $db_true,
                'mobile_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Tennis","2":"Tennis","3":"Tennis","4":"Tennis","5":"Tennis"}',
                'game_code' => 'Tennis',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Tennis',
                'english_name' => 'Tennis',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sport],
                'flag_show_in_site' => $db_true,
                'status' =>  $db_true,
                'mobile_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"American Football","2":"American Football","3":"American Football","4":"American Football","5":"American Football"}',
                'game_code' => 'American Football',
                'game_platform_id' => $api_id,
                'external_game_id' => 'American Football',
                'english_name' => 'American Football',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sport],
                'flag_show_in_site' => $db_true,
                'status' =>  $db_true,
                'mobile_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Badminton","2":"Badminton","3":"Badminton","4":"Badminton","5":"Badminton"}',
                'game_code' => 'Badminton',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Badminton',
                'english_name' => 'Badminton',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sport],
                'flag_show_in_site' => $db_true,
                'status' =>  $db_true,
                'mobile_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Boxing","2":"Boxing","3":"Boxing","4":"Boxing","5":"Boxing"}',
                'game_code' => 'Boxing',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Boxing',
                'english_name' => 'Boxing',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sport],
                'flag_show_in_site' => $db_true,
                'status' =>  $db_true,
                'mobile_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Cricket","2":"Cricket","3":"Cricket","4":"Cricket","5":"Cricket"}',
                'game_code' => 'Cricket',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Cricket',
                'english_name' => 'Cricket',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sport],
                'flag_show_in_site' => $db_true,
                'status' =>  $db_true,
                'mobile_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Cycling","2":"Cycling","3":"Cycling","4":"Cycling","5":"Cycling"}',
                'game_code' => 'Cycling',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Cycling',
                'english_name' => 'Cycling',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sport],
                'flag_show_in_site' => $db_true,
                'status' =>  $db_true,
                'mobile_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Darts","2":"Darts","3":"Darts","4":"Darts","5":"Darts"}',
                'game_code' => 'Darts',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Darts',
                'english_name' => 'Darts',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sport],
                'flag_show_in_site' => $db_true,
                'status' =>  $db_true,
                'mobile_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Entertainment","2":"Entertainment","3":"Entertainment","4":"Entertainment","5":"Entertainment"}',
                'game_code' => 'Entertainment',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Entertainment',
                'english_name' => 'Entertainment',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sport],
                'flag_show_in_site' => $db_true,
                'status' =>  $db_true,
                'mobile_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Field Hockey","2":"Field Hockey","3":"Field Hockey","4":"Field Hockey","5":"Field Hockey"}',
                'game_code' => 'Field Hockey',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Field Hockey',
                'english_name' => 'Field Hockey',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sport],
                'flag_show_in_site' => $db_true,
                'status' =>  $db_true,
                'mobile_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Golf","2":"Golf","3":"Golf","4":"Golf","5":"Golf"}',
                'game_code' => 'Golf',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Golf',
                'english_name' => 'Golf',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sport],
                'flag_show_in_site' => $db_true,
                'status' =>  $db_true,
                'mobile_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Handball","2":"Handball","3":"Handball","4":"Handball","5":"Handball"}',
                'game_code' => 'Handball',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Handball',
                'english_name' => 'Handball',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sport],
                'flag_show_in_site' => $db_true,
                'status' =>  $db_true,
                'mobile_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Ice Hockey","2":"Ice Hockey","3":"Ice Hockey","4":"Ice Hockey","5":"Ice Hockey"}',
                'game_code' => 'Ice Hockey',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Ice Hockey',
                'english_name' => 'Ice Hockey',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sport],
                'flag_show_in_site' => $db_true,
                'status' =>  $db_true,
                'mobile_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Mixed Martial Arts","2":"Mixed Martial Arts","3":"Mixed Martial Arts","4":"Mixed Martial Arts","5":"Mixed Martial Arts"}',
                'game_code' => 'Mixed Martial Arts',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Mixed Martial Arts',
                'english_name' => 'Mixed Martial Arts',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sport],
                'flag_show_in_site' => $db_true,
                'status' =>  $db_true,
                'mobile_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Motor Sport","2":"Motor Sport","3":"Motor Sport","4":"Motor Sport","5":"Motor Sport"}',
                'game_code' => 'Motor Sport',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Motor Sport',
                'english_name' => 'Motor Sport',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sport],
                'flag_show_in_site' => $db_true,
                'status' =>  $db_true,
                'mobile_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Pool/Snooker","2":"Pool/Snooker","3":"Pool/Snooker","4":"Pool/Snooker","5":"Pool/Snooker"}',
                'game_code' => 'Pool/Snooker',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Pool/Snooker',
                'english_name' => 'Pool/Snooker',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sport],
                'flag_show_in_site' => $db_true,
                'status' =>  $db_true,
                'mobile_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Rugby","2":"Rugby","3":"Rugby","4":"Rugby","5":"Rugby"}',
                'game_code' => 'Rugby',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Rugby',
                'english_name' => 'Rugby',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sport],
                'flag_show_in_site' => $db_true,
                'status' =>  $db_true,
                'mobile_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Volleyball","2":"Volleyball","3":"Volleyball","4":"Volleyball","5":"Volleyball"}',
                'game_code' => 'Volleyball',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Volleyball',
                'english_name' => 'Volleyball',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sport],
                'flag_show_in_site' => $db_true,
                'status' =>  $db_true,
                'mobile_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Winter Sports","2":"Winter Sports","3":"Winter Sports","4":"Winter Sports","5":"Winter Sports"}',
                'game_code' => 'Winter Sports',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Winter Sports',
                'english_name' => 'Winter Sports',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sport],
                'flag_show_in_site' => $db_true,
                'status' =>  $db_true,
                'mobile_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Mix Parlay","2":"Mix Parlay","3":"Mix Parlay","4":"Mix Parlay","5":"Mix Parlay"}',
                'game_code' => 'Mix Parlay',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Mix Parlay',
                'english_name' => 'Mix Parlay',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sport],
                'flag_show_in_site' => $db_true,
                'status' =>  $db_true,
                'mobile_enabled' => $db_false,
            ],
			#================================================== Casino Game ========================================
            [
                'game_name' => '_json:{"1":"Baccarat","2":"Baccarat","3":"Baccarat","4":"Baccarat","5":"Baccarat"}',
                'game_code' => 'Baccarat',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Baccarat',
                'english_name' => 'Baccarat',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_casino],
                'flag_show_in_site' => $db_true,
                'status' =>  $db_true,
                'mobile_enabled' => $db_true,
            ],
            [
                'game_name' => '_json:{"1":"Roulette","2":"Roulette","3":"Roulette","4":"Roulette","5":"Roulette"}',
                'game_code' => 'Roulette',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Roulette',
                'english_name' => 'Roulette',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_casino],
                'flag_show_in_site' => $db_true,
                'status' =>  $db_true,
                'mobile_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"SicBo","2":"SicBo","3":"SicBo","4":"SicBo","5":"SicBo"}',
                'game_code' => 'SicBo',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SicBo',
                'english_name' => 'SicBo',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_casino],
                'flag_show_in_site' => $db_true,
                'status' =>  $db_true,
                'mobile_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Super6","2":"Super6","3":"Super6","4":"Super6","5":"Super6"}',
                'game_code' => 'Super6',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Super6',
                'english_name' => 'Super6',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_casino],
                'flag_show_in_site' => $db_true,
                'status' =>  $db_true,
                'mobile_enabled' => $db_false,
            ],
            #================================================== Unknown Game ========================================
            [
                'game_name' => '_json:{"1":"Unknown","2":"不明类型","3":"Unknown","4":"Unknown"}',
                'game_code' => 'unknown',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_unknown],
                // 'game_type' => Table Game
                'external_game_id' => 'unknown',
                'english_name' => 'Unknown',
                'game_platform_id' => $api_id,
                'status'=> $db_true,
                'flag_show_in_site'=>$db_true,
                'updated_at'=>$now,
            ],

            #====================================End Game list=========================================
		);

		$this->load->model(['game_description_model']);

		$success=$this->game_description_model->syncGameDescription($game_descriptions);

		return $success;
	}

}
