<?php

trait game_description_evolution_gaming {

    public function sync_game_description_evolution_gaming(){

        $db_true = 1;
        $db_false = 0;
        $api_id = EVOLUTION_GAMING_API;
        $now = $this->utils->getNowForMysql();

        $game_type_code_live_dealer = SYNC::TAG_CODE_LIVE_DEALER;
        $game_type_code_unknown     = SYNC::TAG_CODE_UNKNOWN_GAME;

        $game_types = [
            $game_type_code_live_dealer => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Live Game","2":"Live Game","3":"Live Game","4":"Live Game","5":"Live Game"}',
                'game_type_lang' => '_json:{"1":"Live Game","2":"Live Game","3":"Live Game","4":"Live Game","5":"Live Game"}',
                'game_type_code' => $game_type_code_live_dealer,
                'game_tag_code' => SYNC::TAG_CODE_LIVE_DEALER
            ],
            $game_type_code_unknown => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Unknown","2":"不明类型","3":"Unknown","4":"Unknown","5":"Unknown"}',
                'game_type_lang' => '_json:{"1":"Unknown","2":"不明类型","3":"Unknown","4":"Unknown","5":"Unknown"}',
                "game_type_code" => $game_type_code_unknown,
                'game_tag_code' => SYNC::TAG_CODE_UNKNOWN_GAME
            ],
        ];


        $this->load->model(['game_type_model']);
        $gameTypeCodeMaps=$this->game_type_model->syncGameTypes($game_types);
        $this->utils->debug_log('gameTypeCodeMaps', $gameTypeCodeMaps);

        $game_descriptions = array(
            [
                'game_name' => '_json:{"1":"Baccarat Squeeze","2":"Baccarat Squeeze","3":"Baccarat Squeeze","4":"Baccarat Squeeze","5":"Baccarat Squeeze"}',
                'game_code' => 'yd1vlvep5q6tln6l',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Baccarat Squeeze',
                'english_name' => 'Baccarat Squeeze',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"baccarat"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],
            [
                'game_name' => '_json:{"1":"Baccarat Controlled Squeeze","2":"Baccarat Controlled Squeeze","3":"Baccarat Controlled Squeeze","4":"Baccarat Controlled Squeeze","5":"Baccarat Controlled Squeeze"}',
                'game_code' => 'k2oswnib7jjaaznw',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Baccarat Controlled Squeeze',
                'english_name' => 'Baccarat Controlled Squeeze',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"baccarat"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],
            [
                'game_name' => '_json:{"1":"Baccarat A","2":"Baccarat A","3":"Baccarat A","4":"Baccarat A","5":"Baccarat A"}',
                'game_code' => 'oytmvb9m1zysmc44',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Baccarat A',
                'english_name' => 'Baccarat A',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"baccarat"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Baccarat B","2":"Baccarat B","3":"Baccarat B","4":"Baccarat B","5":"Baccarat B"}',
                'game_code' => '60i0lcfx5wkkv3sy',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Baccarat B',
                'english_name' => 'Baccarat B',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"baccarat"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Speed Baccarat","2":"Speed Baccarat","3":"Speed Baccarat","4":"Speed Baccarat","5":"Speed Baccarat"}',
                'game_code' => 'leqhceumaq6qfoug',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Speed Baccarat',
                'english_name' => 'Speed Baccarat',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"baccarat"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Blackjack A","2":"Blackjack A","3":"Blackjack A","4":"Blackjack A","5":"Blackjack A"}',
                'game_code' => 'uwd2bl2khwcikjlz',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Blackjack A',
                'english_name' => 'Blackjack A',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Blackjack B","2":"Blackjack B","3":"Blackjack B","4":"Blackjack B","5":"Blackjack B"}',
                'game_code' => 'xphpcthv8e6ivc16',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Blackjack B',
                'english_name' => 'Blackjack B',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],
            [
                'game_name' => '_json:{"1":"Blackjack C ","2":"Blackjack C ","3":"Blackjack C ","4":"Blackjack C ","5":"Blackjack C "}',
                'game_code' => 'jhs44mm0v3fi3aux',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Blackjack C',
                'english_name' => 'Blackjack C ',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],
            [
                'game_name' => '_json:{"1":"Blackjack D ","2":"Blackjack D ","3":"Blackjack D ","4":"Blackjack D ","5":"Blackjack D "}',
                'game_code' => 'xqyb2u7fqkexxpa0',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Blackjack D',
                'english_name' => 'Blackjack D ',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],
            [
                'game_name' => '_json:{"1":"Blackjack E ","2":"Blackjack E ","3":"Blackjack E ","4":"Blackjack E ","5":"Blackjack E "}',
                'game_code' => 'ylq4gmw8yl22u5dj',
                'game_platform_id' => $api_id,
                'external_game_id' =>'Blackjack E',
                'english_name' => 'Blackjack E ',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],
            [
                'game_name' => '_json:{"1":"Blackjack F ","2":"Blackjack F ","3":"Blackjack F ","4":"Blackjack F ","5":"Blackjack F "}',
                'game_code' => 'bghflgi59db7d7r2',
                'game_platform_id' => $api_id,
                'external_game_id' =>  'Blackjack F',
                'english_name' => 'Blackjack F ',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],
            [
                'game_name' => '_json:{"1":"Blackjack G ","2":"Blackjack G ","3":"Blackjack G ","4":"Blackjack G ","5":"Blackjack G "}',
                'game_code' => '1xwfnktjybsolkn6',
                'game_platform_id' => $api_id,
                'external_game_id' =>'Blackjack G',
                'english_name' => 'Blackjack G ',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],
            [
                'game_name' => '_json:{"1":"Blackjack H ","2":"Blackjack H ","3":"Blackjack H ","4":"Blackjack H ","5":"Blackjack H "}',
                'game_code' => 'nc3u2l6y0khszjv7',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Blackjack H',
                'english_name' => 'Blackjack H ',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],
            [
                'game_name' => '_json:{"1":"Blackjack I ","2":"Blackjack I ","3":"Blackjack I ","4":"Blackjack I ","5":"Blackjack I "}',
                'game_code' => 'xstnlyzrm345ev95',
                'game_platform_id' => $api_id,
                'external_game_id' =>  'Blackjack I',
                'english_name' => 'Blackjack I ',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Blackjack VIP A ","2":"Blackjack VIP A ","3":"Blackjack VIP A ","4":"Blackjack VIP A ","5":"Blackjack VIP A "}',
                'game_code' => '0mvn914lkmo9vaq8',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Blackjack VIP A',
                'english_name' => 'Blackjack VIP A ',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Blackjack VIP B ","2":"Blackjack VIP B ","3":"Blackjack VIP B ","4":"Blackjack VIP B ","5":"Blackjack VIP B "}',
                'game_code' => 'cpxl81x0rgi34cmo',
                'game_platform_id' => $api_id,
                'external_game_id' =>  'Blackjack VIP B',
                'english_name' => 'Blackjack VIP B ',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Blackjack VIP C ","2":"Blackjack VIP C ","3":"Blackjack VIP C ","4":"Blackjack VIP C ","5":"Blackjack VIP C "}',
                'game_code' => 'l5aug44hhzr3qvxs',
                'game_platform_id' => $api_id,
                'external_game_id' =>  'Blackjack VIP C',
                'english_name' => 'Blackjack VIP C ',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Blackjack VIP D ","2":"Blackjack VIP D ","3":"Blackjack VIP D ","4":"Blackjack VIP D ","5":"Blackjack VIP D "}',
                'game_code' => '45afijelic04xbtm',
                'game_platform_id' => $api_id,
                'external_game_id' =>'Blackjack VIP D',
                'english_name' => 'Blackjack VIP D ',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Blackjack VIP E ","2":"Blackjack VIP E ","3":"Blackjack VIP E ","4":"Blackjack VIP E ","5":"Blackjack VIP E "}',
                'game_code' => 'psm2um7k4da8zwc2',
                'game_platform_id' => $api_id,
                'external_game_id' =>  'Blackjack VIP E',
                'english_name' => 'Blackjack VIP E ',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Fortune VIP ","2":"Fortune VIP ","3":"Fortune VIP ","4":"Fortune VIP ","5":"Fortune VIP "}',
                'game_code' => 'ejx1a04w4ben0mou',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Fortune VIP',
                'english_name' => 'Fortune VIP ',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Blackjack VIP G ","2":"Blackjack VIP G ","3":"Blackjack VIP G ","4":"Blackjack VIP G ","5":"Blackjack VIP G "}',
                'game_code' => 'z5pf5pichcsw3d2o',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Blackjack VIP G',
                'english_name' => 'Blackjack VIP G ',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Blackjack VIP H ","2":"Blackjack VIP H ","3":"Blackjack VIP H ","4":"Blackjack VIP H ","5":"Blackjack VIP H "}',
                'game_code' => 's63nx2mpdomgjagb',
                'game_platform_id' => $api_id,
                'external_game_id' =>'Blackjack VIP H',
                'english_name' => 'Blackjack VIP H ',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Blackjack VIP I ","2":"Blackjack VIP I ","3":"Blackjack VIP I ","4":"Blackjack VIP I ","5":"Blackjack VIP I "}',
                'game_code' => 'i6vwet1je324g8n7',
                'game_platform_id' => $api_id,
                'external_game_id' =>  'Blackjack VIP I',
                'english_name' => 'Blackjack VIP I ',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Silver1","2":"Silver1","3":"Silver1","4":"Silver1","5":"Silver1"}',
                'game_code' => 'gkmq0o2hryjyqu30',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Silver1',
                'english_name' => 'Silver1  ',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Silver2  ","2":"Silver2  ","3":"Silver2  ","4":"Silver2  ","5":"Silver2  "}',
                'game_code' => '9f4xhuhdd005xlbl',
                'game_platform_id' => $api_id,
                'external_game_id' =>  'Silver2',
                'english_name' => 'Silver2  ',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Platinum VIP  ","2":"Platinum VIP  ","3":"Platinum VIP  ","4":"Platinum VIP  ","5":"Platinum VIP  "}',
                'game_code' => 'h463tlq1rhl1lfr2',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Platinum VIP',
                'english_name' => 'Platinum VIP',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Party BJ  ","2":"Party BJ  ","3":"Party BJ  ","4":"Party BJ  ","5":"Party BJ  "}',
                'game_code' => 'sni5cza6d1vvl50i',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Party BJ',
                'english_name' => 'Party BJ',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Diamond VIP  ","2":"Diamond VIP  ","3":"Diamond VIP  ","4":"Diamond VIP  ","5":"Diamond VIP  "}',
                'game_code' => 'rdefcn4sffgo39l7',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Diamond VIP',
                'english_name' => 'Diamond VIP',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Blackjack White 1  ","2":"Blackjack White 1  ","3":"Blackjack White 1  ","4":"Blackjack White 1  ","5":"Blackjack White 1  "}',
                'game_code' => 'k4r2ejwx4eqqb6tv',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Blackjack White 1',
                'english_name' => 'Blackjack White 1',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Blackjack White 2  ","2":"Blackjack White 2  ","3":"Blackjack White 2  ","4":"Blackjack White 2  ","5":"Blackjack White 2  "}',
                'game_code' => 'k4r2hyhw4eqqb6us',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Blackjack White 2',
                'english_name' => 'Blackjack White 2',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Blackjack White 3  ","2":"Blackjack White 3  ","3":"Blackjack White 3  ","4":"Blackjack White 3  ","5":"Blackjack White 3  "}',
                'game_code' => 'Blackjack White 3 ',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Blackjack White 3',
                'english_name' => 'Blackjack White 3',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],
            [
                'game_name' => '_json:{"1":"Casino Holdem","2":"Casino Holdem","3":"Casino Holdem","4":"Casino Holdem","5":"Casino Holdem"}',
                'game_code' => 'HoldemTable00001',
                'game_platform_id' => $api_id,
                'external_game_id' => "Casino Hold'em",
                'english_name' => "Casino Hold'em",
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"ch"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],
            [
                'game_name' => '_json:{"1":"Auto-Roulette","2":"Auto-Roulette","3":"Auto-Roulette","4":"Auto-Roulette","5":"Auto-Roulette"}',
                'game_code' => '48z5pjps3ntvqc1b',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Auto-Roulette',
                'english_name' => 'Auto-Roulette  ',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"roulette"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Auto-Roulette La Partage","2":"Auto-Roulette La Partage","3":"Auto-Roulette La Partage","4":"Auto-Roulette La Partage","5":"Auto-Roulette La Partage"}',
                'game_code' => 'f1f4rm9xgh4j3u2z',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Auto-Roulette La Partage',
                'english_name' => 'Auto-Roulette La Partage',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"roulette"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Auto-Roulette VIP","2":"Auto-Roulette VIP","3":"Auto-Roulette VIP","4":"Auto-Roulette VIP","5":"Auto-Roulette VIP"}',
                'game_code' => '01rb77cq1gtenhmo',
                'game_platform_id' => $api_id,
                'external_game_id' =>  'Auto-Roulette VIP',
                'english_name' => 'Auto-Roulette VIP',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"roulette"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Immersive Roulette","2":"Immersive Roulette","3":"Immersive Roulette","4":"Immersive Roulette","5":"Immersive Roulette"}',
                'game_code' => '7x0b1tgh7agmf6hv',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Immersive Roulette',
                'english_name' => 'Immersive Roulette',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"roulette"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Roulette","2":"Roulette","3":"Roulette","4":"Roulette","5":"Roulette"}',
                'game_code' => 'vctlz20yfnmp1ylr',
                'game_platform_id' => $api_id,
                'external_game_id' =>'Roulette Game',
                'english_name' => 'Roulette',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"roulette"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"VIP Roulette","2":"VIP Roulette","3":"VIP Roulette","4":"VIP Roulette","5":"VIP Roulette"}',
                'game_code' => 'wzg6kdkad1oe7m5k',
                'game_platform_id' => $api_id,
                'external_game_id' => 'VIP Roulette',
                'english_name' => 'VIP Roulette',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"roulette"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Three Card Poker","2":"Three Card Poker","3":"Three Card Poker","4":"Three Card Poker","5":"Three Card Poker"}',
                'game_code' => 'n5emwq5c5dwepwam',
                'game_platform_id' => $api_id,
                'external_game_id' => 'THREE CARD POKER',
                'english_name' => 'Three Card Poker',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"tcp"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Caribbean Stud Poker","2":"Caribbean Stud Poker","3":"Caribbean Stud Poker","4":"Caribbean Stud Poker","5":"Caribbean Stud Poker"}',
                'game_code' => 'CSPTable00000001',
                'game_platform_id' => $api_id,
                'external_game_id' =>  'Caribbean Stud Poker',
                'english_name' => 'Caribbean Stud Poker',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"csp"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

//            [
//                'game_name' => '_json:{"1":"Ultimate Texas Holdem","2":"Ultimate Texas Holdem","3":"Ultimate Texas Holdem","4":"Ultimate Texas Holdem","5":"Ultimate Texas Holdem"}',
//                'game_code' => 'UTHTable00000001',
//                'game_platform_id' => $api_id,
//                'external_game_id' => "Ultimate Texas Hold'em",
//                'english_name' => "Ultimate Texas Hold'em",
//                'flash_enabled' => $db_false,
//                'attributes' => '{"game_type":"uth"}',
//                'html_five_enabled' => $db_true,
//                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
//                'mobile_enabled' => $db_true,
//            ],

            [
                'game_name' => '_json:{"1":"Triple Card Poker","2":"Triple Card Poker","3":"Triple Card Poker","4":"Triple Card Poker","5":"Triple Card Poker"}',
                'game_code' => 'TRPTable00000001',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Triple Card Poker',
                'english_name' => 'Triple Card Poker',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"tcp"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Extreme Texas Holdem","2":"Extreme Texas Holdem","3":"Extreme Texas Holdem","4":"Extreme Texas Holdem","5":"Extreme Texas Holdem"}',
                'game_code' => 'ETHTable00000001',
                'game_platform_id' => $api_id,
                'external_game_id' => "Extreme Texas Hold'em",
                'english_name' => "Extreme Texas Hold'em",
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"eth"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Dream Catcher","2":"Dream Catcher","3":"Dream Catcher","4":"Dream Catcher","5":"Dream Catcher"}',
                'game_code' => 'MOWDream00000001',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Dream Catcher',
                'english_name' => 'Dream Catcher',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"moneywheel"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],


            // ADDED LIST
            [
                'game_name' => '_json:{"1":"Speed Baccarat B","2":"Speed Baccarat B","3":"Speed Baccarat B","4":"Speed Baccarat B","5":"Speed Baccarat B"}',
                'game_code' => 'lv2kzclunt2qnxo5',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Speed Baccarat B',
                'english_name' => 'Speed Baccarat B',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"baccarat"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Blackjack J","2":"Blackjack J","3":"Blackjack J","4":"Blackjack J","5":"Blackjack J"}',
                'game_code' => 'i5j1cyqhrypkih23',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Blackjack J',
                'english_name' => 'Blackjack J',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Blackjack K","2":"Blackjack K","3":"Blackjack K","4":"Blackjack K","5":"Blackjack K"}',
                'game_code' => 'ehw2fvl831m5n2km',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Blackjack K',
                'english_name' => 'Blackjack K',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Blackjack L","2":"Blackjack L","3":"Blackjack L","4":"Blackjack L","5":"Blackjack L"}',
                'game_code' => 'bciewncrf5ijneys',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Blackjack L',
                'english_name' => 'Blackjack L',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Blackjack M","2":"Blackjack M","3":"Blackjack M","4":"Blackjack M","5":"Blackjack M"}',
                'game_code' => '2uxabtm1rwaxcmdm',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Blackjack M',
                'english_name' => 'Blackjack M',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Silver3  ","2":"Silver3  ","3":"Silver3  ","4":"Silver3  ","5":"Silver3  "}',
                'game_code' => 'qlrc3fq3v7p6awm4',
                'game_platform_id' => $api_id,
                'external_game_id' =>  'Silver3',
                'english_name' => 'Silver3  ',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Silver4  ","2":"Silver4  ","3":"Silver4  ","4":"Silver4  ","5":"Silver4  "}',
                'game_code' => 'qckwjf2o52r9ikeb',
                'game_platform_id' => $api_id,
                'external_game_id' =>  'Silver4',
                'english_name' => 'Silver4  ',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Silver5  ","2":"Silver5  ","3":"Silver5  ","4":"Silver5  ","5":"Silver5  "}',
                'game_code' => 'gazgtkid9h1b0dn9',
                'game_platform_id' => $api_id,
                'external_game_id' =>  'Silver5',
                'english_name' => 'Silver5  ',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Silver6  ","2":"Silver6  ","3":"Silver6  ","4":"Silver6  ","5":"Silver6  "}',
                'game_code' => 'lnofoyxv756qaezy',
                'game_platform_id' => $api_id,
                'external_game_id' =>  'Silver6',
                'english_name' => 'Silver6  ',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Silver7  ","2":"Silver7  ","3":"Silver7  ","4":"Silver7  ","5":"Silver7  "}',
                'game_code' => 'lnofpmm3756qae2c',
                'game_platform_id' => $api_id,
                'external_game_id' =>  'Silver7',
                'english_name' => 'Silver7  ',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Grand VIP ","2":"Grand VIP ","3":"Grand VIP ","4":"Grand VIP ","5":"Grand VIP "}',
                'game_code' => 'gfzrqe4hqv24kukc',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Grand VIP',
                'english_name' => 'Grand VIP ',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"blackjack"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            [
                'game_name' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                'game_code' => 'unknown',
                'game_platform_id' => $api_id,
                'external_game_id' => 'unknown',
                'english_name' => 'Unknown',
                'status' => $db_true,
                'flag_show_in_site' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_unknown],
            ],
            [
                'game_name' => '_json:{"1":"Double Ball Roulette","2":"Double Ball Roulette","3":"Double Ball Roulette","4":"Double Ball Roulette","5":"Double Ball Roulette"}',
                'game_code' => 'DoubleBallRou001',
                'game_platform_id' => $api_id,
                'external_game_id' => 'Double Ball Roulette',
                'english_name' => 'Double Ball Roulette  ',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"roulette"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

            // changes game name in back office ( web crawler )
            [
                'game_name' => '_json:{"1":"Baccarat Squeeze","2":"Baccarat Squeeze","3":"Baccarat Squeeze","4":"Baccarat Squeeze","5":"Baccarat Squeeze"}',
                'game_code' => 'yd1vlvep5q6tln6l',
                'game_platform_id' => $api_id,
                'external_game_id' => 'BetEast Squeeze Baccarat',
                'english_name' => 'Baccarat Squeeze',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"baccarat"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],
            [
                'game_name' => '_json:{"1":"Speed Baccarat","2":"Speed Baccarat","3":"Speed Baccarat","4":"Speed Baccarat","5":"Speed Baccarat"}',
                'game_code' => 'leqhceumaq6qfoug',
                'game_platform_id' => $api_id,
                'external_game_id' => 'BetEast Speed Baccarat',
                'english_name' => 'Speed Baccarat',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"baccarat"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],
            [
                'game_name' => '_json:{"1":"Roulette","2":"Roulette","3":"Roulette","4":"Roulette","5":"Roulette"}',
                'game_code' => 'vctlz20yfnmp1ylr',
                'game_platform_id' => $api_id,
                'external_game_id' =>'BetEast Roulette',
                'english_name' => 'Roulette',
                'flash_enabled' => $db_false,
                'attributes' => '{"game_type":"roulette"}',
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_live_dealer],
                'mobile_enabled' => $db_true,
            ],

        );


        $this->load->model(['game_description_model']);

        $success=$this->game_description_model->syncGameDescription($game_descriptions);

        return $success;
    }

}
