<?php
trait game_description_dt {

    public function sync_game_description_dt_t1(&$cnt=0){
        $api_id=T1DT_API;
        $this->dt_game_list($api_id);
    }

    public function sync_game_description_dt(&$cnt=0){
        $api_id=DT_API;
        $this->dt_game_list($api_id);
    }

	public function dt_game_list($api_id){

		// $cnt=0;

		$success=true;

		$db_true=1;
		$db_false=0;
		$now=$this->utils->getNowForMysql();

		$game_type_code_slots=sync::TAG_CODE_SLOT;
		$game_type_code_unknown=sync::TAG_CODE_UNKNOWN_GAME;

		//sync game type first
		//use game_type_code as key
		$game_types = [
			$game_type_code_slots => [
				'game_platform_id' => $api_id,
				'game_type' => '_json:{"1":"Classic Slots","2":"经典老虎机","3":"Classic Slots","4":"Classic Slots","5":"Classic Slots"}',
				'game_type_lang' => '_json:{"1":"Classic Slots","2":"经典老虎机","3":"Classic Slots","4":"Classic Slots","5":"Classic Slots"}',
				"game_type_code" => $game_type_code_slots,
				'flag_show_in_site' => $db_true,
				'auto_add_new_game' => $db_true,
				'auto_add_to_cashback' => $db_true,
				'status'=>$db_true,
				'updated_at'=>$now,
				'game_tag_code' => sync::TAG_CODE_SLOT
			],
			$game_type_code_unknown => [
				'game_platform_id' => $api_id,
				'game_type' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
				'game_type_lang' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
				"game_type_code" => $game_type_code_unknown,
				'flag_show_in_site' => $db_false,
				'auto_add_new_game' => $db_true,
				'auto_add_to_cashback' => $db_true,
				'status'=>$db_true,
				'updated_at'=>$now,
				'game_tag_code' => sync::TAG_CODE_UNKNOWN_GAME
			]
		];

		$this->load->model(['game_type_model']);
		$gameTypeCodeMaps=$this->game_type_model->syncGameTypes($game_types);

		$this->utils->debug_log('gameTypeCodeMaps', $gameTypeCodeMaps);

		if(empty($gameTypeCodeMaps)){
			return false;
		}

		$game_descriptions = [

			#=========================================== Game List ========================================
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Investiture of Gods","2":"封神榜","3":"Investiture of Gods","4":"Investiture of Gods","5":"Investiture of Gods"}',
                'game_code' => 'tlod',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Investiture of Gods',
                'external_game_id' => 'tlod',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Cosmicgirl","2":"宇宙少女战士","3":"Cosmicgirl", "4":"Cosmicgirl","5":"Cosmicgirl"}',
                'game_code' => 'cosmicgirl3x1',
                'dlc_enabled' => $db_true,
                'flash_enabled' => $db_true,
                'mobile_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'english_name' => 'Cosmicgirl',
                'external_game_id' => 'cosmicgirl3x1',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"KING OF PIRATE","2":"海盗无双","3":"KING OF PIRATE","4":"KING OF PIRATE","5":"KING OF PIRATE"}',
                'game_code' => 'onepiece',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'KING OF PIRATE',
                'external_game_id' => 'onepiece',
                'enabled_freespin' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Saiyan Battle","2":"赛亚烈战","3":"Saiyan Battle","4":"Saiyan Battle","5":"Saiyan Battle"}',
                'game_code' => 'dragonball',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Saiyan Battle',
                'external_game_id' => 'dragonball',
                'enabled_freespin' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Four Beauty","2":"倾城四美","3":"Four Beauty","4":"Four Beauty","5":"Four Beauty"}',
                'game_code' => 'fourbeauty',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Four Beauty',
                'external_game_id' => 'fourbeauty',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"4X4 BATTLE","2":"四驱大赛","3":"4X4 BATTLE","4":"4X4 BATTLE","5":"4X4 BATTLE"}',
                'game_code' => 'sq5x243',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => '4X4 BATTLE',
                'external_game_id' => 'sq5x243',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Happy Farm","2":"快乐农庄","3":"Happy Farm","4":"Happy Farm","5":"Happy Farm"}',
                'game_code' => 'klnz5x20',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Happy Farm',
                'external_game_id' => 'klnz5x20',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Chinese Paladin","2":"仙剑奇缘","3":"Chinese Paladin","4":"Chinese Paladin","5":"Chinese Paladin"}',
                'game_code' => 'xjqy5x9',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Chinese Paladin',
                'external_game_id' => 'xjqy5x9',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"DragonPhoenix Prosper","2":"龙凤呈祥","3":"DragonPhoenix Prosper","4":"DragonPhoenix Prosper","5":"DragonPhoenix Prosper"}',
                'game_code' => 'dnp',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'DragonPhoenix Prosper',
                'external_game_id' => 'dnp',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Tales Of Wusong","2":"武松传","3":"Tales Of Wusong","4":"Tales Of Wusong","5":"Tales Of Wusong"}',
                'game_code' => 'watermargin',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Tales Of Wusong',
                'external_game_id' => 'watermargin',
                'enabled_freespin' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Basketball Master 2","2":"灌篮大师2","3":"Basketball Master 2","4":"Basketball Master 2","5":"Basketball Master 2"}',
                'game_code' => 'sd5',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Basketball Master 2',
                'external_game_id' => 'sd5',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"NINJA","2":"NINJA","3":"NINJA","4":"NINJA","5":"NINJA"}',
                'game_code' => 'naruto',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'NINJA',
                'external_game_id' => 'naruto',
                'enabled_freespin' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Shogun","2":"幕府风云","3":"Shogun","4":"Shogun","5":"Shogun"}',
                'game_code' => 'shogun',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Shogun',
                'external_game_id' => 'shogun',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Crossing","2":"十字路口","3":"Crossing","4":"Crossing","5":"Crossing"}',
                'game_code' => 'crossing',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Crossing',
                'external_game_id' => 'crossing',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Football All Star","2":"传奇之路","3":"Football All Star","4":"Football All Star","5":"Football All Star"}',
                'game_code' => 'football',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Football All Star',
                'external_game_id' => 'football',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"nightclub","2":"夜店之王","3":"nightclub","4":"nightclub","5":"nightclub"}',
                'game_code' => 'nightclub5x20',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'nightclub',
                'external_game_id' => 'nightclub5x20',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Demon Hunt to West","2":"西游降妖","3":"Demon Hunt to West","4":"Demon Hunt to West","5":"Demon Hunt to West"}',
                'game_code' => 'jtw',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Demon Hunt to West',
                'external_game_id' => 'jtw',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Street Fighter II","2":"街霸","3":"Street Fighter II","4":"Street Fighter II","5":"Street Fighter II"}',
                'game_code' => 'streetfighter3x1',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Street Fighter II',
                'external_game_id' => 'streetfighter3x1',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Fantasy Forest","2":"梦幻森林","3":"Fantasy Forest","4":"Fantasy Forest","5":"Fantasy Forest"}',
                'game_code' => 'fantasyforest3x1',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Fantasy Forest',
                'external_game_id' => 'fantasyforest3x1',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Sweet House","2":"甜蜜糖果屋","3":"Sweet House","4":"Sweet House","5":"Sweet House"}',
                'game_code' => 'sweethouse',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Sweet House',
                'external_game_id' => 'sweethouse',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Basketball Master","2":"灌篮大师","3":"Basketball Master","4":"Basketball Master","5":"Basketball Master"}',
                'game_code' => 'sd',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Basketball Master',
                'external_game_id' => 'sd',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Bikini Girls","2":"比基尼派对","3":"Bikini Girls","4":"Bikini Girls","5":"Bikini Girls"}',
                'game_code' => 'bikini',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Bikini Girls',
                'external_game_id' => 'bikini',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Crazy Circus","2":"疯狂马戏团","3":"Crazy Circus","4":"Crazy Circus","5":"Crazy Circus"}',
                'game_code' => 'circus',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Crazy Circus',
                'external_game_id' => 'circus',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Watermargin","2":"水浒传","3":"Watermargin","4":"Watermargin","5":"Watermargin"}',
                'game_code' => 'watermargin5x25',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Watermargin',
                'external_game_id' => 'watermargin5x25',
                'enabled_freespin' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Magic Lamp","2":"阿拉丁神灯","3":"Magic Lamp","4":"Magic Lamp","5":"Magic Lamp"}',
                'game_code' => 'aladdin5x243',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Magic Lamp',
                'external_game_id' => 'aladdin5x243',
                'enabled_freespin' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Five Elements","2":"五行世界","3":"Five Elements","4":"Five Elements","5":"Five Elements"}',
                'game_code' => 'fiveelements5x9',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Five Elements',
                'external_game_id' => 'fiveelements5x9',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Onepiece","2":"海贼王","3":"Onepiece","4":"Onepiece","5":"Onepiece"}',
                'game_code' => 'onepiece3x1',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Onepiece',
                'external_game_id' => 'onepiece3x1',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Merry Christmas","2":"圣诞快乐","3":"Merry Christmas","4":"Merry Christmas","5":"Merry Christmas"}',
                'game_code' => 'merryxmas',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Merry Christmas',
                'external_game_id' => 'merryxmas',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Hip-hop Man","2":"嘻哈侠","3":"Hip-hop Man","4":"Hip-hop Man","5":"Hip-hop Man"}',
                'game_code' => 'hiphopman',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Hip-hop Man',
                'external_game_id' => 'hiphopman',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Rocknight","2":"摇滚之夜","3":"Rocknight","4":"Rocknight","5":"Rocknight"}',
                'game_code' => 'rocknight',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Rocknight',
                'external_game_id' => 'rocknight',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Glory of Heroes","2":"英雄荣耀","3":"Glory of Heroes", "4":"Glory of Heroes","5":"Glory of Heroes"}',
                'game_code' => 'crystal',
                'dlc_enabled' => $db_true,
                'flash_enabled' => $db_true,
                'mobile_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'english_name' => '',
                'external_game_id' => 'Glory of Heroes',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"whitesnake","2":"白蛇传","3":"whitesnake","4":"whitesnake","5":"whitesnake"}',
                'game_code' => 'whitesnake',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'whitesnake',
                'external_game_id' => 'whitesnake',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Wealthy God Arriving","2":"财神到","3":"Wealthy God Arriving","4":"Wealthy God Arriving","5":"Wealthy God Arriving"}',
                'game_code' => 'tgow',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Wealthy God Arriving',
                'external_game_id' => 'tgow',
                'enabled_freespin' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Gundam","2":"高达","3":"Gundam","4":"Gundam","5":"Gundam"}',
                'game_code' => 'gundam3x5',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Gundam',
                'external_game_id' => 'gundam3x5',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Fighting Spirit","2":"格斗之魂","3":"Fighting Spirit","4":"Fighting Spirit","5":"Fighting Spirit"}',
                'game_code' => 'kof',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Fighting Spirit',
                'external_game_id' => 'kof',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Legend of the King","2":"王者传奇","3":"Legend of the King","4":"Legend of the King","5":"Legend of the King"}',
                'game_code' => 'legend5x25',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Legend of the King',
                'external_game_id' => 'legend5x25',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Paladins","2":"圣战骑士","3":"Paladins","4":"Paladins","5":"Paladins"}',
                'game_code' => 'crusader',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Paladins',
                'external_game_id' => 'crusader',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"3D Slot","2":"3D老虎机","3":"3D Slot","4":"3D Slot","5":"3D Slot"}',
                'game_code' => 'casino',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => '3D Slot',
                'external_game_id' => 'casino',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Glory of Heroes","2":"英雄荣耀","3":"Glory of Heroes","4":"Glory of Heroes","5":"Glory of Heroes"}',
                'game_code' => 'crystal',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Glory of Heroes',
                'external_game_id' => 'crystal',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"XIANGYAOCHUANQI","2":"降妖传奇","3":"XIANGYAOCHUANQI","4":"XIANGYAOCHUANQI","5":"XIANGYAOCHUANQI"}',
                'game_code' => 'xiyouji5x9',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'XIANGYAOCHUANQI',
                'external_game_id' => 'xiyouji5x9',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"XIYOUJI","2":"西游记","3":"XIYOUJI","4":"XIYOUJI","5":"XIYOUJI"}',
                'game_code' => 'xiyouji5x25',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'XIYOUJI',
                'external_game_id' => 'xiyouji5x25',
                'enabled_freespin' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Doraemon","2":"哆啦A梦","3":"Doraemon","4":"Doraemon","5":"Doraemon"}',
                'game_code' => 'doraemon3x5',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Doraemon',
                'external_game_id' => 'doraemon3x5',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"The King of Fighters98","2":"拳皇98","3":"The King of Fighters98","4":"The King of Fighters98","5":"The King of Fighters98"}',
                'game_code' => 'kof5x9',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'The King of Fighters98',
                'external_game_id' => 'kof5x9',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"SO YOUNG","2":"致青春","3":"SO YOUNG","4":"SO YOUNG","5":"SO YOUNG"}',
                'game_code' => 'foryouth5x25',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'SO YOUNG',
                'external_game_id' => 'foryouth5x25',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"4x4 Hero","2":"四驱英雄","3":"4x4 Hero","4":"4x4 Hero","5":"4x4 Hero"}',
                'game_code' => 'dash',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => '4x4 Hero',
                'external_game_id' => 'dash',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Blue Sea","2":"深蓝海域","3":"Blue Sea","4":"Blue Sea","5":"Blue Sea"}',
                'game_code' => 'bluesea',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Blue Sea',
                'external_game_id' => 'bluesea',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Crazy Basketball","2":"劲爆篮球","3":"Crazy Basketball","4":"Crazy Basketball","5":"Crazy Basketball"}',
                'game_code' => 'btball5x20',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Crazy Basketball',
                'external_game_id' => 'btball5x20',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"FULUSHOU","2":"福禄寿","3":"FULUSHOU","4":"FULUSHOU","5":"FULUSHOU"}',
                'game_code' => 'fls',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'FULUSHOU',
                'external_game_id' => 'fls',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Happy New Year","2":"新年到","3":"Happy New Year","4":"Happy New Year","5":"Happy New Year"}',
                'game_code' => 'newyear',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Happy New Year',
                'external_game_id' => 'newyear',
                'enabled_freespin' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Seiya","2":"圣域传说","3":"Seiya","4":"Seiya","5":"Seiya"}',
                'game_code' => 'seiya',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Seiya',
                'external_game_id' => 'seiya',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Battle of Red Cliffs","2":"赤壁之战","3":"Battle of Red Cliffs","4":"Battle of Red Cliffs","5":"Battle of Red Cliffs"}',
                'game_code' => 'san',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Battle of Red Cliffs',
                'external_game_id' => 'san',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Pirate Treasure","2":"海盗宝藏","3":"Pirate Treasure","4":"Pirate Treasure","5":"Pirate Treasure"}',
                'game_code' => 'piratetreasure',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Pirate Treasure',
                'external_game_id' => 'piratetreasure',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Monopoly","2":"地产大亨","3":"Monopoly","4":"Monopoly","5":"Monopoly"}',
                'game_code' => 'estate5x25',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Monopoly',
                'external_game_id' => 'estate5x25',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Four Holy Beasts","2":"四圣兽","3":"Four Holy Beasts","4":"Four Holy Beasts","5":"Four Holy Beasts"}',
                'game_code' => 'fourss',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Four Holy Beasts',
                'external_game_id' => 'fourss',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Crazy GO GO GO","2":"疯狂转转转","3":"Crazy GO GO GO","4":"Crazy GO GO GO","5":"Crazy GO GO GO"}',
                'game_code' => 'crazy5x243',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Crazy GO GO GO',
                'external_game_id' => 'crazy5x243',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Spicy Hot Pot","2":"麻辣火锅","3":"Spicy Hot Pot","4":"Spicy Hot Pot","5":"Spicy Hot Pot"}',
                'game_code' => 'hotpot5x25',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Spicy Hot Pot',
                'external_game_id' => 'hotpot5x25',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Happiness Overflow","2":"喜气冲天","3":"Happiness Overflow","4":"Happiness Overflow","5":"Happiness Overflow"}',
                'game_code' => 'rocket6x25',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Happiness Overflow',
                'external_game_id' => 'rocket6x25',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Classic Drama show","2":"喜气冲天","3":"Classic Drama show","4":"Classic Drama show","5":"Classic Drama show"}',
                'game_code' => 'opera',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Classic Drama show',
                'external_game_id' => 'opera',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Vampire Legend","2":"夜影传说","3":"Vampire Legend","4":"Vampire Legend","5":"Vampire Legend"}',
                'game_code' => 'vampire',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Vampire Legend',
                'external_game_id' => 'vampire',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Zombie Outbreak","2":"丧尸来袭","3":"Zombie Outbreak","4":"Zombie Outbreak","5":"Zombie Outbreak"}',
                'game_code' => 'zombie',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Zombie Outbreak',
                'external_game_id' => 'zombie',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":" Perfect Detective","2":"全能侦探","3":" Perfect Detective","4":" Perfect Detective","5":" Perfect Detective"}',
                'game_code' => 'perfectdet',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => ' Perfect Detective',
                'external_game_id' => 'perfectdet',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Man Tang Hong","2":"满堂红","3":"Man Tang Hong","4":"Man Tang Hong","5":"Man Tang Hong"}',
                'game_code' => 'bigred',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Man Tang Hong',
                'external_game_id' => 'bigred',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Wrath of Thor","2":"雷霆神域","3":"Wrath of Thor","4":"Wrath of Thor","5":"Wrath of Thor"}',
                'game_code' => 'wrathofthor',
                'flash_enabled' => $db_true,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Wrath of Thor',
                'external_game_id' => 'wrathofthor',
                'enabled_freespin' => $db_true,
            ],

			//===unknown======================================================================
			[
				'game_platform_id' => $api_id,
				'game_code' => 'unknown',
				'game_type_id' => $gameTypeCodeMaps[$game_type_code_unknown],
				'game_name' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
				"english_name" => "Unknown",
				'external_game_id' => 'unknown',
				'status'=> $db_true,
				'flag_show_in_site'=>$db_false,
				'updated_at'=>$now,
			],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Pet House","2":"萌宠小窝","3":"Pet House","4":"Pet House","5":"Pet House"}',
                'game_code' => 'pethouse',
                'flash_enabled' => $db_false,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Pet House',
                'external_game_id' => 'pethouse',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"HOGA","2":"HOGA","3":"HOGA","4":"HOGA","5":"HOGA"}',
                'game_code' => 'huga5x9',
                'flash_enabled' => $db_false,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'HOGA',
                'external_game_id' => 'huga5x9',
                'enabled_freespin' => $db_false,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Bellum Street","2":"热血街头","3":"Bellum Street","4":"Bellum Street","5":"Bellum Street"}',
                'game_code' => 'guhuozai',
                'flash_enabled' => $db_false,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Bellum Street',
                'external_game_id' => 'guhuozai',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Boxing Arena","2":"铁拳擂台","3":"Boxing Arena","4":"Boxing Arena","5":"Boxing Arena"}',
                'game_code' => 'boxingarena',
                'flash_enabled' => $db_false,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Boxing Arena',
                'external_game_id' => 'boxingarena',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Eight Immortals","2":"八仙过海","3":"Eight Immortals","4":"Eight Immortals","5":"Eight Immortals"}',
                'game_code' => 'bxgh5x25',
                'flash_enabled' => $db_false,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Eight Immortals',
                'external_game_id' => 'bxgh5x25',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Elves Kingdom","2":"精灵王国","3":"Elves Kingdom","4":"Elves Kingdom","5":"Elves Kingdom"}',
                'game_code' => 'fantasyforest',
                'flash_enabled' => $db_false,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Elves Kingdom',
                'external_game_id' => 'fantasyforest',
                'enabled_freespin' => $db_true,
            ],
             [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Sexy Camgirl","2":"心动女主播","3":"Sexy Camgirl","4":"Sexy Camgirl","5":"Sexy Camgirl"}',
                'game_code' => 'camgirl5x25',
                'flash_enabled' => $db_false,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Sexy Camgirl',
                'external_game_id' => 'camgirl5x25',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Egyptian Empire","2":"心动女主播","3":"Egyptian Empire","4":"Egyptian Empire","5":"Egyptian Empire"}',
                'game_code' => 'egyptian',
                'flash_enabled' => $db_false,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Egyptian Empire',
                'external_game_id' => 'egyptian',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Galactic War","2":"银河战争","3":"Galactic War","4":"Galactic War","5":"Galactic War"}',
                'game_code' => 'galaxywars',
                'flash_enabled' => $db_false,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Galactic War',
                'external_game_id' => 'galaxywars',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Easy Rider","2":"逍遥骑士","3":"Easy Rider","4":"Easy Rider","5":"Easy Rider"}',
                'game_code' => 'easyrider',
                'flash_enabled' => $db_false,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Easy Rider',
                'external_game_id' => 'easyrider',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Joust for a spouse","2":"比武招亲","3":"Joust for a spouse","4":"Joust for a spouse","5":"Joust for a spouse"}',
                'game_code' => 'bwzq5x25',
                'flash_enabled' => $db_false,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Joust for a spouse',
                'external_game_id' => 'bwzq5x25',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"FIFA World Cup","2":"决战世界杯","3":"FIFA World Cup","4":"FIFA World Cup","5":"FIFA World Cup"}',
                'game_code' => 'worldCup5x25',
                'flash_enabled' => $db_false,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'FIFA World Cup',
                'external_game_id' => 'worldCup5x25',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Jin Yu Man Tang","2":"金玉满堂","3":"Jin Yu Man Tang","4":"Jin Yu Man Tang","5":"Jin Yu Man Tang"}',
                'game_code' => 'goldjade5x50',
                'flash_enabled' => $db_false,
                'status' => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'english_name' => 'Jin Yu Man Tang',
                'external_game_id' => 'goldjade5x50',
                'enabled_freespin' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Shokudo","2":"深夜食堂","3":"Shokudo","4":"Shokudo","5":"Shokudo"}',
                'game_code' => 'shokudo',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'attributes' => '{"game_launch_code":"shokudo"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Shokudo',
                'external_game_id' => 'shokudo',
                'enabled_freespin' => $db_true,
                'enabled_on_android' => $db_false,
                'enabled_on_ios' => $db_false,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Treasure Hunt Trip","2":"寻宝之旅","3":"Treasure Hunt Trip","4":"Treasure Hunt Trip","5":"Treasure Hunt Trip"}',
                'game_code' => 'train',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'attributes' => '{"game_launch_code":"train"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Treasure Hunt Trip',
                'external_game_id' => 'train',
                'enabled_freespin' => $db_true,
                'enabled_on_android' => $db_false,
                'enabled_on_ios' => $db_false,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Treasure Hunt Trip","2":"寻宝之旅","3":"Treasure Hunt Trip","4":"Treasure Hunt Trip","5":"Treasure Hunt Trip"}',
                'game_code' => 'train',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'attributes' => '{"game_launch_code":"train"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Treasure Hunt Trip',
                'external_game_id' => 'train',
                'enabled_freespin' => $db_true,
                'enabled_on_android' => $db_false,
                'enabled_on_ios' => $db_false,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"FaFaFa","2":"发发发","3":"FaFaFa","4":"FaFaFa","5":"FaFaFa"}',
                'game_code' => 'dtfafafa15x9',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'attributes' => '{"game_launch_code":"dtfafafa15x9"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'FaFaFa',
                'external_game_id' => 'dtfafafa15x9',
                'enabled_freespin' => $db_true,
                'enabled_on_android' => $db_false,
                'enabled_on_ios' => $db_false,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Feng Shen","2":"五行封神榜","3":"Feng Shen","4":"Feng Shen","5":"Feng Shen"}',
                'game_code' => 'fengshen5x20',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'attributes' => '{"game_launch_code":"fengshen5x20"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Feng Shen',
                'external_game_id' => 'fengshen5x20',
                'enabled_freespin' => $db_true,
                'enabled_on_android' => $db_false,
                'enabled_on_ios' => $db_false,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Ocean Park","2":"海洋游乐场","3":"Ocean Park","4":"Ocean Park","5":"Ocean Park"}',
                'game_code' => 'oceanpark5x50',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'attributes' => '{"game_launch_code":"oceanpark5x50"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Ocean Park',
                'external_game_id' => 'oceanpark5x50',
                'enabled_freespin' => $db_true,
                'enabled_on_android' => $db_false,
                'enabled_on_ios' => $db_false,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Guan Ren","2":"官人我要","3":"Guan Ren","4":"Guan Ren","5":"Guan Ren"}',
                'game_code' => 'guanren5x50',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'attributes' => '{"game_launch_code":"guanren5x50"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Guan Ren',
                'external_game_id' => 'guanren5x50',
                'enabled_freespin' => $db_true,
                'enabled_on_android' => $db_false,
                'enabled_on_ios' => $db_false,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Hot Wikiki","2":"热浪夏威夷","3":"Hot Wikiki","4":"Hot Wikiki","5":"Hot Wikiki"}',
                'game_code' => 'wikiki5x20',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'attributes' => '{"game_launch_code":"wikiki5x20"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Hot Wikiki',
                'external_game_id' => 'wikiki5x20',
                'enabled_freespin' => $db_true,
                'enabled_on_android' => $db_false,
                'enabled_on_ios' => $db_false,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Guan Gong","2":"武圣关公","3":"Guan Gong","4":"Guan Gong","5":"Guan Gong"}',
                'game_code' => 'dtguangong15x9',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'attributes' => '{"game_launch_code":"dtguangong15x9"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Guan Gong',
                'external_game_id' => 'dtguangong15x9',
                'enabled_freespin' => $db_true,
                'enabled_on_android' => $db_false,
                'enabled_on_ios' => $db_false,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Invincible Lvbu","2":"真吕布无双","3":"Invincible Lvbu","4":"Invincible Lvbu","5":"Invincible Lvbu"}',
                'game_code' => 'lvbu5x25',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'attributes' => '{"game_launch_code":"lvbu5x25"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Invincible Lvbu',
                'external_game_id' => 'lvbu5x25',
                'enabled_freespin' => $db_true,
                'enabled_on_android' => $db_false,
                'enabled_on_ios' => $db_false,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"France feelings Amorous","2":"法兰西风情","3":"France feelings Amorous","4":"France feelings Amorous","5":"France feelings Amorous"}',
                'game_code' => 'france',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'attributes' => '{"game_launch_code":"france"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'France feelings Amorous',
                'external_game_id' => 'france',
                'enabled_freespin' => $db_true,
                'enabled_on_android' => $db_false,
                'enabled_on_ios' => $db_false,
            ],



		];

		$this->load->model(['game_description_model']);
        echo "<pre>";
		$success=$this->game_description_model->syncGameDescription($game_descriptions);

		return $success;
	}

}
