<?php
trait game_description_rtg {

    public function sync_game_description_rtg(){
        $api_id=RTG_API;
        $this->sync_gamelist_rtg($api_id);
    }

    public function sync_gamelist_rtg($api_id){

        $success=true;
        $db_true=1;
        $db_false=0;
        $now=$this->utils->getNowForMysql();

        $game_type_code_slots = SYNC::TAG_CODE_SLOT;
        $game_type_code_table_game   = SYNC::TAG_CODE_TABLE_GAMES;
        $game_type_code_video_poker  = SYNC::TAG_CODE_VIDEO_POKER;
        $game_type_code_others       = SYNC::TAG_CODE_OTHER;
        $game_type_code_unknown = SYNC::TAG_CODE_UNKNOWN_GAME;

        $game_types = [
            $game_type_code_slots =>
                [
                    'game_platform_id' => $api_id,
                    'game_type' => '_json:{"1":"Slot Game","2":"老虎机游戏","3":"Slot Game","4":"Slot Game","5":"Slot Game"}',
                    'game_type_lang' => '_json:{"1":"Slot Game","2":"老虎机游戏","3":"Slot Game","4":"Slot Game","5":"Slot Game"}',
                    'game_type_code' => $game_type_code_slots,
                    'game_tag_code' => $game_type_code_slots,
                    'updated_at' => $now,
                ],  
            $game_type_code_table_game => 
                [
                    'game_platform_id' => $api_id,
                    'game_type' => '_json:{"1":"Table Game","2":"桌面游戏","3":"Table Game","4":"Table Game","5":"Table Game"}',
                    'game_type_lang' => '_json:{"1":"Table Game","2":"桌面游戏","3":"Table Game","4":"Table Game","5":"Table Game"}',
                    'game_type_code' => $game_type_code_table_game,
                    'game_tag_code' => $game_type_code_table_game,
                ],
            $game_type_code_video_poker => 
                [
                    'game_platform_id' => $api_id,
                    'game_type' => '_json:{"1":"Video Poker","2":"视频扑克","3":"Video Poker","4":"Video Poker","5":"Video Poker"}',
                    'game_type_lang' => '_json:{"1":"Video Poker","2":"视频扑克","3":"Video Poker","4":"Video Poker","5":"Video Poker"}',
                    'game_type_code' => $game_type_code_video_poker,
                    'game_tag_code' => $game_type_code_video_poker,
                ],
            $game_type_code_others => 
                [
                    'game_platform_id' => $api_id,
                    'game_type' => '_json:{"1":"Others","2":"其他","3":"Others","4":"Others","5":"Others"}',
                    'game_type_lang' => '_json:{"1":"Others","2":"其他","3":"Others","4":"Others","5":"Others"}',
                    'game_type_code' => $game_type_code_others,
                    'game_tag_code' => $game_type_code_others,
                ],
            $game_type_code_unknown => 
                [
                    'game_platform_id' => $api_id,
                    'game_type' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                    'game_type_lang' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                    "game_type_code" => $game_type_code_unknown,
                    "game_tag_code" => $game_type_code_unknown,
                    'flag_show_in_site' => $db_true,
                    'updated_at'=>$now,
                ],
            ];

        $cnt=0;
        $this->load->model(['game_type_model']);
        $gameTypeCodeMaps=$this->game_type_model->syncGameTypes($game_types);

        $this->utils->debug_log('gameTypeCodeMaps', $gameTypeCodeMaps);

        if(empty($gameTypeCodeMaps)){
            return false;
        }

        $game_descriptions = array(

            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_unknown],
                'game_name' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                'game_code' => 'unknown',
                'dlc_enabled' => $db_true,
                'mobile_enabled' => $db_true,
                'flag_show_in_site' => $db_false,
                'english_name' => 'Unknown',
                'external_game_id' => 'unknown',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Eagle Shadow Fist","2":"北派功夫","3":"Eagle Shadow Fist","4":"Eagle Shadow Fist","5":"Eagle Shadow Fist"}',
                'game_code' => '223',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'english_name' => 'Eagle Shadow Fist',
                'external_game_id' => '18223',
                'sub_game_provider' => '18',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Shanghai Lights","2":"霓虹上海","3":"Shanghai Lights","4":"Shanghai Lights","5":"Shanghai Lights"}',
                'game_code' => '221',
                'html_five_enabled' => $db_true,
                'english_name' => 'Shanghai Lights',
                'external_game_id' => '18221',
                'sub_game_provider' => '18',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Asgard","2":"阿萨神域","3":"Asgard","4":"Asgard","5":"Asgard"}',
                'game_code' => '191',
                'html_five_enabled' => $db_true,
                'english_name' => 'Asgard',
                'external_game_id' => '18191',
                'sub_game_provider' => '18',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Bubble Bubble 2","2":"女巫温妮 2","3":"Bubble Bubble 2","4":"Bubble Bubble 2","5":"Bubble Bubble 2"}',
                'game_code' => '199',
                'html_five_enabled' => $db_true,
                'english_name' => 'Bubble Bubble 2',
                'external_game_id' => '18199',
                'sub_game_provider' => '18',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Kung Fu Rooster","2":"功夫雄鸡","3":"Kung Fu Rooster","4":"Kung Fu Rooster","5":"Kung Fu Rooster"}',
                'game_code' => '198',
                'html_five_enabled' => $db_true,
                'english_name' => 'Kung Fu Rooster',
                'external_game_id' => '18198',
                'sub_game_provider' => '18',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Popinata","2":"皮纳塔狂欢","3":"Popinata","4":"Popinata","5":"Popinata"}',
                'game_code' => '190',
                'html_five_enabled' => $db_true,
                'english_name' => 'Popinata',
                'external_game_id' => '18190',
                'sub_game_provider' => '18',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Fucanglong","2":"伏藏龙","3":"Fucanglong","4":"Fucanglong","5":"Fucanglong"}',
                'game_code' => '188',
                'html_five_enabled' => $db_true,
                'english_name' => 'Fucanglong',
                'external_game_id' => '18188',
                'sub_game_provider' => '18',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Sweet 16","2":"甜蜜 16 岁","3":"Sweet 16","4":"Sweet 16","5":"Sweet 16"}',
                'game_code' => '181',
                'html_five_enabled' => $db_true,
                'english_name' => 'Sweet 16',
                'external_game_id' => '18181',
                'sub_game_provider' => '18',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Snowmania","2":"冰雪风暴","3":"Snowmania","4":"Snowmania","5":"Snowmania"}',
                'game_code' => '179',
                'html_five_enabled' => $db_true,
                'english_name' => 'Snowmania',
                'external_game_id' => '18179',
                'sub_game_provider' => '18',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Witch’s Brew","2":"女巫製藥","3":"Witch’s Brew","4":"Witch’s Brew","5":"Witch’s Brew"}',
                'game_code' => '177',
                'html_five_enabled' => $db_true,
                'english_name' => 'Witch’s Brew',
                'external_game_id' => '18177',
                'sub_game_provider' => '18',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Nova 7s","2":"新星7s","3":"Nova 7s","4":"Nova 7s","5":"Nova 7s"}',
                'game_code' => '176',
                'html_five_enabled' => $db_true,
                'english_name' => 'Nova 7s',
                'external_game_id' => '18176',
                'sub_game_provider' => '18',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Panda Magic","2":"魔幻猫熊","3":"Panda Magic","4":"Panda Magic","5":"Panda Magic"}',
                'game_code' => '173',
                'html_five_enabled' => $db_true,
                'english_name' => 'Panda Magic',
                'external_game_id' => '18173',
                'sub_game_provider' => '18',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Enchanted Garden II","2":"梦幻花园 II","3":"Enchanted Garden II","4":"Enchanted Garden II","5":"Enchanted Garden II"}',
                'game_code' => '172',
                'html_five_enabled' => $db_true,
                'english_name' => 'Enchanted Garden II',
                'external_game_id' => '18172',
                'sub_game_provider' => '18',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Super 6","2":"超级 6","3":"Super 6","4":"Super 6","5":"Super 6"}',
                'game_code' => '170',
                'html_five_enabled' => $db_true,
                'english_name' => 'Super 6',
                'external_game_id' => '18170',
                'sub_game_provider' => '18',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"The Big Bopper","2":"The Big Bopper","3":"The Big Bopper","4":"The Big Bopper","5":"The Big Bopper"}',
                'game_code' => '169',
                'html_five_enabled' => $db_true,
                'english_name' => 'The Big Bopper',
                'external_game_id' => '18169',
                'sub_game_provider' => '18',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Eternal Love","2":"永恒的爱","3":"Eternal Love","4":"Eternal Love","5":"Eternal Love"}',
                'game_code' => '167',
                'html_five_enabled' => $db_true,
                'english_name' => 'Eternal Love',
                'external_game_id' => '18167',
                'sub_game_provider' => '18',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Lucky 6","2":"幸运 6","3":"Lucky 6","4":"Lucky 6","5":"Lucky 6"}',
                'game_code' => '162',
                'html_five_enabled' => $db_true,
                'english_name' => 'Lucky 6',
                'external_game_id' => '18162',
                'sub_game_provider' => '18',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"The Nice List","2":"缤纷圣诞","3":"The Nice List","4":"The Nice List","5":"The Nice List"}',
                'game_code' => '165',
                'html_five_enabled' => $db_true,
                'english_name' => 'The Nice List',
                'external_game_id' => '18165',
                'sub_game_provider' => '18',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Bubble Bubble","2":"女巫温妮","3":"Bubble Bubble","4":"Bubble Bubble","5":"Bubble Bubble"}',
                'game_code' => '164',
                'html_five_enabled' => $db_true,
                'english_name' => 'Bubble Bubble',
                'external_game_id' => '18164',
                'sub_game_provider' => '18',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Lucha Libre","2":"自由式摔跤","3":"Lucha Libre","4":"Lucha Libre","5":"Lucha Libre"}',
                'game_code' => '161',
                'html_five_enabled' => $db_true,
                'english_name' => 'Lucha Libre',
                'external_game_id' => '18161',
                'sub_game_provider' => '18',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"The Three Stooges Brideless Groom","2":"The Three Stooges Brideless Groom","3":"The Three Stooges Brideless Groom","4":"The Three Stooges Brideless Groom","5":"The Three Stooges Brideless Groom"}',
                'game_code' => '158',
                'html_five_enabled' => $db_true,
                'english_name' => 'The Three Stooges Brideless Groom',
                'external_game_id' => '18158',
                'sub_game_provider' => '18',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Voodoo Magic","2":"伏都巫术","3":"Voodoo Magic","4":"Voodoo Magic","5":"Voodoo Magic"}',
                'game_code' => '155',
                'html_five_enabled' => $db_true,
                'english_name' => 'Voodoo Magic',
                'external_game_id' => '18155',
                'sub_game_provider' => '18',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Cai Hong","2":"彩虹","3":"Cai Hong","4":"Cai Hong","5":"Cai Hong"}',
                'game_code' => '230',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'english_name' => 'Cai Hong',
                'external_game_id' => '18230',
                'sub_game_provider' => '18',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Richie Valen’s La Bamba","2":"里奇·瓦伦斯LA BAMBA","3":"Richie Valen’s La Bamba","4":"Richie Valen’s La Bamba","5":"Richie Valen’s La Bamba"}',
                'game_code' => '224',
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
                'english_name' => 'Richie Valen’s La Bamba',
                'external_game_id' => '18224',
                'sub_game_provider' => '18',
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Spirit of the Inca","2":"印加人精神","3":"Spirit of the Inca","4":"Spirit of the Inca","5":"Spirit of the Inca"}',
                'game_code' => '128',
                'html_five_enabled' => $db_false,
                'mobile_enabled' => $db_false,
                'english_name' => 'Spirit of the Inca',
                'external_game_id' => '18128',
                'sub_game_provider' => '18',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Megasaur","2":"巨兽","3":"Megasaur","4":"Megasaur","5":"Megasaur"}',
                'game_code' => '137',
                'html_five_enabled' => $db_false,
                'mobile_enabled' => $db_false,
                'english_name' => 'Megasaur',
                'external_game_id' => '18137',
                'sub_game_provider' => '18',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Aztec’s Millions","2":"古代战士","3":"Aztec’s Millions","4":"Aztec’s Millions","5":"Aztec’s Millions"}',
                'game_code' => '56',
                'html_five_enabled' => $db_true,
                'mobile_enabled' => $db_true,
                'english_name' => 'Aztec’s Millions',
                'external_game_id' => '1856',
                'sub_game_provider' => '18',
                'status' => $db_false,
                'flag_show_in_site' => $db_false,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Eagle Shadow Fist","2":"北派功夫","3":"Eagle Shadow Fist","4":"Eagle Shadow Fist","5":"Eagle Shadow Fist"}',
                'game_code' => '223',
                'html_five_enabled' => $db_true,
                'mobile_enabled' => $db_true,
                'english_name' => 'Eagle Shadow Fist',
                'external_game_id' => '18223',
                'sub_game_provider' => '18',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Shanghai Lights","2":"霓虹上海","3":"Shanghai Lights","4":"Shanghai Lights","5":"Shanghai Lights"}',
                'game_code' => '221',
                'html_five_enabled' => $db_true,
                'mobile_enabled' => $db_true,
                'english_name' => 'Shanghai Lights',
                'external_game_id' => '18221',
                'sub_game_provider' => '18',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Lucha Libre 2","2":"墨西哥摔角 2","3":"Lucha Libre 2","4":"Lucha Libre 2","5":"Lucha Libre 2"}',
                'game_code' => '225',
                'html_five_enabled' => $db_true,
                'mobile_enabled' => $db_true,
                'english_name' => 'Lucha Libre 2',
                'external_game_id' => '18225',
                'sub_game_provider' => '18',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Three Kingdom Wars","2":"三国争霸","3":"Three Kingdom Wars","4":"Three Kingdom Wars","5":"Three Kingdom Wars"}',
                'game_code' => '236',
                'html_five_enabled' => $db_true,
                'mobile_enabled' => $db_true,
                'english_name' => 'Three Kingdom Wars',
                'external_game_id' => '18236',
                'sub_game_provider' => '18',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Gods of Nature","2":"天地元素","3":"Gods of Nature","4":"Gods of Nature","5":"Gods of Nature"}',
                'game_code' => '237',
                'html_five_enabled' => $db_true,
                'mobile_enabled' => $db_true,
                'english_name' => 'Gods of Nature',
                'external_game_id' => '18237',
                'sub_game_provider' => '18',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Secret Jungle","2":"秘密丛林","3":"Secret Jungle","4":"Secret Jungle","5":"Secret Jungle"}',
                'game_code' => '228',
                'html_five_enabled' => $db_true,
                'mobile_enabled' => $db_true,
                'english_name' => 'Secret Jungle',
                'external_game_id' => '18228',
                'sub_game_provider' => '18',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Ancient Gods","2":"远古圣兽","3":"Ancient Gods","4":"Ancient Gods","5":"Ancient Gods"}',
                'game_code' => '238',
                'html_five_enabled' => $db_true,
                'mobile_enabled' => $db_true,
                'english_name' => 'Ancient Gods',
                'external_game_id' => '18238',
                'sub_game_provider' => '18',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Fantasy Mission Force","2":"迷你特攻队","3":"Fantasy Mission Force","4":"Fantasy Mission Force","5":"Fantasy Mission Force"}',
                'game_code' => '222',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"222"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Fantasy Mission Force',
                'external_game_id' => '18222',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Fu Chi","2":"福气","3":"Fu Chi","4":"Fu Chi","5":"Fu Chi"}',
                'game_code' => '219',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"219"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Fu Chi',
                'external_game_id' => '18219',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Swindle All the Way","2":"一路抢到底","3":"Swindle All the Way","4":"Swindle All the Way","5":"Swindle All the Way"}',
                'game_code' => '220',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"220"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Swindle All the Way',
                'external_game_id' => '18220',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Dragon Orb","2":"龙珠","3":"Dragon Orb","4":"Dragon Orb","5":"Dragon Orb"}',
                'game_code' => '192',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"192"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Dragon Orb',
                'external_game_id' => '18192',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Gemtopia","2":"宝石天堂","3":"Gemtopia","4":"Gemtopia","5":"Gemtopia"}',
                'game_code' => '193',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"193"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Gemtopia',
                'external_game_id' => '18193',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Cash Bandits 2","2":"警匪追逐2","3":"Cash Bandits 2","4":"Cash Bandits 2","5":"Cash Bandits 2"}',
                'game_code' => '197',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"197"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Cash Bandits 2',
                'external_game_id' => '18197',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Purrfect Pets","2":"完美宠物","3":"Purrfect Pets","4":"Purrfect Pets","5":"Purrfect Pets"}',
                'game_code' => '194',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"194"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Purrfect Pets',
                'external_game_id' => '18194',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Secret Symbol","2":"秘密符号","3":"Secret Symbol","4":"Secret Symbol","5":"Secret Symbol"}',
                'game_code' => '189',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"189"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Secret Symbol',
                'external_game_id' => '18189',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Megaquarium","2":"财富水族箱","3":"Megaquarium","4":"Megaquarium","5":"Megaquarium"}',
                'game_code' => '187',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"187"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Megaquarium',
                'external_game_id' => '18187',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Samba Sunset","2":"桑巴日落","3":"Samba Sunset","4":"Samba Sunset","5":"Samba Sunset"}',
                'game_code' => '174',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"174"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Samba Sunset',
                'external_game_id' => '18174',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Zhanshi","2":"古代战士","3":"Zhanshi","4":"Zhanshi","5":"Zhanshi"}',
                'game_code' => '171',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"171"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Zhanshi',
                'external_game_id' => '18171',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"God of Wealth","2":"财神到","3":"God of Wealth","4":"God of Wealth","5":"God of Wealth"}',
                'game_code' => '168',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"168"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'God of Wealth',
                'external_game_id' => '18168',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Cash Bandits","2":"警匪追逐","3":"Cash Bandits","4":"Cash Bandits","5":"Cash Bandits"}',
                'game_code' => '160',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"160"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Cash Bandits',
                'external_game_id' => '18160',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Ghost Ship","2":"幽灵船","3":"Ghost Ship","4":"Ghost Ship","5":"Ghost Ship"}',
                'game_code' => '141',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"141"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Ghost Ship',
                'external_game_id' => '18141',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Double Ya Luck!","2":"双喜运","3":"Double Ya Luck!","4":"Double Ya Luck!","5":"Double Ya Luck!"}',
                'game_code' => '213',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"213"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Double Ya Luck!',
                'external_game_id' => '18213',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"The Naughty List","2":"圣诞凤骚女","3":"The Naughty List","4":"The Naughty List","5":"The Naughty List"}',
                'game_code' => '156',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"156"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'The Naughty List',
                'external_game_id' => '18156',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"High Fashion","2":"模特梦","3":"High Fashion","4":"High Fashion","5":"High Fashion"}',
                'game_code' => '149',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"149"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'High Fashion',
                'external_game_id' => '18149',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Football Frenzy","2":"足球狂热","3":"Football Frenzy","4":"Football Frenzy","5":"Football Frenzy"}',
                'game_code' => '153',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"153"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Football Frenzy',
                'external_game_id' => '18153',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Lucky 8","2":"幸运 8","3":"Lucky 8","4":"Lucky 8","5":"Lucky 8"}',
                'game_code' => '121',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"121"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Lucky 8',
                'external_game_id' => '18121',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Santastic!","2":"奇妙圣诞","3":"Santastic!","4":"Santastic!","5":"Santastic!"}',
                'game_code' => '212',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"212"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Santastic!',
                'external_game_id' => '18212',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Henhouse","2":"农村人家","3":"Henhouse","4":"Henhouse","5":"Henhouse"}',
                'game_code' => '120',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"120"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Henhouse',
                'external_game_id' => '18120',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Small Fortune","2":"郊外野餐","3":"Small Fortune","4":"Small Fortune","5":"Small Fortune"}',
                'game_code' => '148',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"148"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Small Fortune',
                'external_game_id' => '18148',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Regal Riches","2":"貴族富豪","3":"Regal Riches","4":"Regal Riches","5":"Regal Riches"}',
                'game_code' => '147',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"147"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Regal Riches',
                'external_game_id' => '18147',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Ocean Oddities","2":"海洋生物","3":"Ocean Oddities","4":"Ocean Oddities","5":"Ocean Oddities"}',
                'game_code' => '146',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"146"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Ocean Oddities',
                'external_game_id' => '18146',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Ninja Star","2":"忍者星","3":"Ninja Star","4":"Ninja Star","5":"Ninja Star"}',
                'game_code' => '130',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"130"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Ninja Star',
                'external_game_id' => '18130',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"The Three Stooges II","2":"The Three Stooges II","3":"The Three Stooges II","4":"The Three Stooges II","5":"The Three Stooges II"}',
                'game_code' => '209',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"209"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'The Three Stooges II',
                'external_game_id' => '18209',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Count Spectacular","2":"吸血伯爵","3":"Count Spectacular","4":"Count Spectacular","5":"Count Spectacular"}',
                'game_code' => '78',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"78"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Count Spectacular',
                'external_game_id' => '1878',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Return of the Rudolph","2":"驯鹿鲁道夫","3":"Return of the Rudolph","4":"Return of the Rudolph","5":"Return of the Rudolph"}',
                'game_code' => '83',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"83"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Return of the Rudolph',
                'external_game_id' => '1883',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Builder Beaver","2":"海狸伐木先生","3":"Builder Beaver","4":"Builder Beaver","5":"Builder Beaver"}',
                'game_code' => '122',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"122"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Builder Beaver',
                'external_game_id' => '18122',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Triple Twister","2":"龙卷风","3":"Triple Twister","4":"Triple Twister","5":"Triple Twister"}',
                'game_code' => '61',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"61"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Triple Twister',
                'external_game_id' => '1861',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Naughty or Nice","2":"淘气或乖乖","3":"Naughty or Nice","4":"Naughty or Nice","5":"Naughty or Nice"}',
                'game_code' => '65',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"65"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Naughty or Nice',
                'external_game_id' => '1865',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Paydirt!","2":"金矿探索","3":"Paydirt!","4":"Paydirt!","5":"Paydirt!"}',
                'game_code' => '49',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"49"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Paydirt!',
                'external_game_id' => '1849',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Rudolph’s Revenge","2":"魯道夫的復仇","3":"Rudolph’s Revenge","4":"Rudolph’s Revenge","5":"Rudolph’s Revenge"}',
                'game_code' => '44',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"44"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Rudolph’s Revenge',
                'external_game_id' => '1844',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Coyote Cash","2":"恶棍郊狼","3":"Coyote Cash","4":"Coyote Cash","5":"Coyote Cash"}',
                'game_code' => '43',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"43"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Coyote Cash',
                'external_game_id' => '1843',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Texan Tycoon","2":"德州大亨","3":"Texan Tycoon","4":"Texan Tycoon","5":"Texan Tycoon"}',
                'game_code' => '60',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"60"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Texan Tycoon',
                'external_game_id' => '1860',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"T-Rex","2":"暴龙","3":"T-Rex","4":"T-Rex","5":"T-Rex"}',
                'game_code' => '51',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"51"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'T-Rex',
                'external_game_id' => '1851',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Penguin Power","2":"金胡子","3":"Penguin Power","4":"Penguin Power","5":"Penguin Power"}',
                'game_code' => '36',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"36"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Penguin Power',
                'external_game_id' => '1836',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Achilles","2":"古希臘英雄","3":"Achilles","4":"Achilles","5":"Achilles"}',
                'game_code' => '32',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"32"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Achilles',
                'external_game_id' => '1832',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Crystal Waters","2":"深海遨游","3":"Crystal Waters","4":"Crystal Waters","5":"Crystal Waters"}',
                'game_code' => '26',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"26"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Crystal Waters',
                'external_game_id' => '1826',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Aladdin’s Wishes","2":"阿拉丁的愿望","3":"Aladdin’s Wishes","4":"Aladdin’s Wishes","5":"Aladdin’s Wishes"}',
                'game_code' => '25',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"25"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Aladdin’s Wishes',
                'external_game_id' => '1825',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Enchanted Garden","2":"梦幻花园","3":"Enchanted Garden","4":"Enchanted Garden","5":"Enchanted Garden"}',
                'game_code' => '23',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"23"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Enchanted Garden',
                'external_game_id' => '1823',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Hillbillies","2":"乡下佬","3":"Hillbillies","4":"Hillbillies","5":"Hillbillies"}',
                'game_code' => '15',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"15"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Hillbillies',
                'external_game_id' => '1815',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Mermaid Queen","2":"人鱼女王","3":"Mermaid Queen","4":"Mermaid Queen","5":"Mermaid Queen"}',
                'game_code' => '14',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"14"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Mermaid Queen',
                'external_game_id' => '1814',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Caesar’s Empire","2":"凯撒帝国","3":"Caesar’s Empire","4":"Caesar’s Empire","5":"Caesar’s Empire"}',
                'game_code' => '5',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"5"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Caesar’s Empire',
                'external_game_id' => '185',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Goldbeard","2":"金胡子","3":"Goldbeard","4":"Goldbeard","5":"Goldbeard"}',
                'game_code' => '4',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"4"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Goldbeard',
                'external_game_id' => '184',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Cleopatra’s Gold","2":"埃及艳后","3":"Cleopatra’s Gold","4":"Cleopatra’s Gold","5":"Cleopatra’s Gold"}',
                'game_code' => '2',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"2"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Cleopatra’s Gold',
                'external_game_id' => '182',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_slots],
                'game_name' => '_json:{"1":"Loch Ness Loot","2":"尼斯湖水怪","3":"Loch Ness Loot","4":"Loch Ness Loot","5":"Loch Ness Loot"}',
                'game_code' => '124',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'attributes' => '{"game_launch_code":"18","match_id":"124"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Loch Ness Loot',
                'external_game_id' => '18124',
                'enabled_freespin' => $db_false,
                'mobile_enabled' => $db_true,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_others],
                'game_name' => '_json:{"1":"European Roulette","2":"European Roulette","3":"European Roulette","4":"European Roulette","5":"European Roulette"}',
                'game_code' => '4',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'attributes' => '{"game_launch_code":"18",4"match_id":"1"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'European Roulette',
                'external_game_id' => '41',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_others],
                'game_name' => '_json:{"1":"Keno","2":"Keno","3":"Keno","4":"Keno","5":"Keno"}',
                'game_code' => '13',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'attributes' => '{"game_launch_code":"18",13"match_id":"0"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Keno',
                'external_game_id' => '130',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_video_poker],
                'game_name' => '_json:{"1":"Aces & Eights","2":"Aces & Eights","3":"Aces & Eights","4":"Aces & Eights","5":"Aces & Eights"}',
                'game_code' => '7',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'attributes' => '{"game_launch_code":"18",7"match_id":"3"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Aces & Eights',
                'external_game_id' => '73',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_video_poker],
                'game_name' => '_json:{"1":"All American Poker","2":"All American Poker","3":"All American Poker","4":"All American Poker","5":"All American Poker"}',
                'game_code' => '7',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'attributes' => '{"game_launch_code":"18",7"match_id":"4"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'All American Poker',
                'external_game_id' => '74',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_video_poker],
                'game_name' => '_json:{"1":"Bonus Deuces Wild","2":"Bonus Deuces Wild","3":"Bonus Deuces Wild","4":"Bonus Deuces Wild","5":"Bonus Deuces Wild"}',
                'game_code' => '7',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'attributes' => '{"game_launch_code":"18",7"match_id":"13"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Bonus Deuces Wild',
                'external_game_id' => '713',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_video_poker],
                'game_name' => '_json:{"1":"Bonus Poker","2":"Bonus Poker","3":"Bonus Poker","4":"Bonus Poker","5":"Bonus Poker"}',
                'game_code' => '7',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'attributes' => '{"game_launch_code":"18",7"match_id":"5"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Bonus Poker',
                'external_game_id' => '75',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_video_poker],
                'game_name' => '_json:{"1":"Bonus Poker Deluxe","2":"Bonus Poker Deluxe","3":"Bonus Poker Deluxe","4":"Bonus Poker Deluxe","5":"Bonus Poker Deluxe"}',
                'game_code' => '7',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'attributes' => '{"game_launch_code":"18",7"match_id":"6"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Bonus Poker Deluxe',
                'external_game_id' => '76',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_video_poker],
                'game_name' => '_json:{"1":"Deuces Wild","2":"Deuces Wild","3":"Deuces Wild","4":"Deuces Wild","5":"Deuces Wild"}',
                'game_code' => '7',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'attributes' => '{"game_launch_code":"18",7"match_id":"2"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Deuces Wild',
                'external_game_id' => '72',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_video_poker],
                'game_name' => '_json:{"1":"Double Bonus Poker","2":"Double Bonus Poker","3":"Double Bonus Poker","4":"Double Bonus Poker","5":"Double Bonus Poker"}',
                'game_code' => '7',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'attributes' => '{"game_launch_code":"18",7"match_id":"7"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Double Bonus Poker',
                'external_game_id' => '77',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_video_poker],
                'game_name' => '_json:{"1":"Double Double Jackpot Poker","2":"Double Double Jackpot Poker","3":"Double Double Jackpot Poker","4":"Double Double Jackpot Poker","5":"Double Double Jackpot Poker"}',
                'game_code' => '7',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'attributes' => '{"game_launch_code":"18",7"match_id":"9"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Double Double Jackpot Poker',
                'external_game_id' => '79',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_video_poker],
                'game_name' => '_json:{"1":"Double Jackpot Poker","2":"Double Jackpot Poker","3":"Double Jackpot Poker","4":"Double Jackpot Poker","5":"Double Jackpot Poker"}',
                'game_code' => '7',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'attributes' => '{"game_launch_code":"18",7"match_id":"10"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Double Jackpot Poker',
                'external_game_id' => '10',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_video_poker],
                'game_name' => '_json:{"1":"Jacks or Better","2":"Jacks or Better","3":"Jacks or Better","4":"Jacks or Better","5":"Jacks or Better"}',
                'game_code' => '7',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'attributes' => '{"game_launch_code":"18",7"match_id":"0"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Jacks or Better',
                'external_game_id' => '70',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_video_poker],
                'game_name' => '_json:{"1":"Joker Poker","2":"Joker Poker","3":"Joker Poker","4":"Joker Poker","5":"Joker Poker"}',
                'game_code' => '7',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'attributes' => '{"game_launch_code":"18",7"match_id":"1"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Joker Poker',
                'external_game_id' => '71',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_video_poker],
                'game_name' => '_json:{"1":"Loose Deuces","2":"Loose Deuces","3":"Loose Deuces","4":"Loose Deuces","5":"Loose Deuces"}',
                'game_code' => '7',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'attributes' => '{"game_launch_code":"18",7"match_id":"11"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Loose Deuces',
                'external_game_id' => '711',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_video_poker],
                'game_name' => '_json:{"1":"Sevens Wild","2":"Sevens Wild","3":"Sevens Wild","4":"Sevens Wild","5":"Sevens Wild"}',
                'game_code' => '7',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'attributes' => '{"game_launch_code":"18",7"match_id":"12"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Sevens Wild',
                'external_game_id' => '712',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_table_game],
                'game_name' => '_json:{"1":"Tri Card Poker","2":"Tri Card Poker","3":"Tri Card Poker","4":"Tri Card Poker","5":"Tri Card Poker"}',
                'game_code' => '12',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'attributes' => '{"game_launch_code":"18",12"match_id":"0"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Tri Card Poker',
                'external_game_id' => '120',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_table_game],
                'game_name' => '_json:{"1":"Blackjack","2":"Blackjack","3":"Blackjack","4":"Blackjack","5":"Blackjack"}',
                'game_code' => '0',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'attributes' => '{"game_launch_code":"0",0"match_id":"0"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Blackjack',
                'external_game_id' => '00',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_table_game],
                'game_name' => '_json:{"1":"Suit’Em Up Blackjack","2":"Suit’Em Up Blackjack","3":"Suit’Em Up Blackjack","4":"Suit’Em Up Blackjack","5":"Suit’Em Up Blackjack"}',
                'game_code' => '0',
                'dlc_enabled' => $db_false,
                'progressive' => $db_false,
                'offline_enabled' => $db_false,
                'mobile_enabled' => $db_true,
                'attributes' => '{"game_launch_code":"0",0"match_id":"9"}',
                'html_five_enabled' => $db_true,
                'english_name' => 'Suit’Em Up Blackjack',
                'external_game_id' => '09',
                'enabled_freespin' => $db_false,
                'enabled_on_android' => $db_true,
                'enabled_on_ios' => $db_true,
            ],

        );

        $this->load->model(['game_description_model']);

        $success=$this->game_description_model->syncGameDescription($game_descriptions);

        return $success;
    }

}
