<?php
trait game_description_ig {

    public function sync_game_description_ig(){

        $db_true = 1;
        $db_false = 0;
        $api_id = IG_API;
        $now = $this->utils->getNowForMysql();

        $game_type_code_lottery = SYNC::TAG_CODE_LOTTERY;
        $game_type_code_unknown = SYNC::TAG_CODE_UNKNOWN_GAME;

        $game_types = [
            $game_type_code_lottery => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Lottery Game","2":"Lottery Game","3":"Lottery Game","4":"Lottery Game","5":"Lottery Game"}',
                'game_type_lang' => '_json:{"1":"Lottery Game","2":"Lottery Game","3":"Lottery Game","4":"Lottery Game","5":"Lottery Game"}',
                'game_type_code' => $game_type_code_lottery,
                'updated_at' => $now,
                'game_tag_code' => SYNC::TAG_CODE_LOTTERY
            ],
            $game_type_code_unknown => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                'game_type_lang' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                "game_type_code" => $game_type_code_unknown,
                'updated_at'=>$now,
                'game_tag_code' => SYNC::TAG_CODE_UNKNOWN_GAME
            ],
        ];

        $this->load->model(['game_type_model']);
        $gameTypeCodeMaps=$this->game_type_model->syncGameTypes($game_types);
        $this->utils->debug_log('gameTypeCodeMaps', $gameTypeCodeMaps);

        $game_descriptions = array(
            [
                'game_name' => '_json:{"1":"IG Lottery Game","2":"IG Lottery Game","3":"IG Lottery Game","4":"IG Lottery Game","5":"IG Lottery Game"}',
                'game_code' => 'ig_lottery',
                'game_platform_id' => $api_id,
                'external_game_id' => 'IG_lottery',
                'english_name' => 'IG Lottery Game',
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
            ],
            [
                'game_name' => '_json:{"1":"IG Lotto Game","2":"IG Lotto Game","3":"IG Lotto Game","4":"IG Lotto Game","5":"IG Lotto Game"}',
                'game_code' => 'ig_lotto',
                'game_platform_id' => $api_id,
                'external_game_id' => 'IG_lotto',
                'english_name' => 'IG Lotto Game',
                'mobile_enabled' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
            ],
            [
                'game_name' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                'game_code' => 'unknown',
                'game_platform_id' => $api_id,
                'external_game_id' => 'unknown',
                'english_name' => 'Unknown',
                'status' => $db_true,
                'flag_show_in_site' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_unknown],
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"KLC","2":"广东快乐十分","3":"KLC","4":"KLC","5":"KLC"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'KLC',
                'external_game_id' => '1',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"SSC","2":"重庆时时彩","3":"SSC","4":"SSC","5":"SSC"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'SSC',
                'external_game_id' => '2',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"BJC","2":"北京赛车(PK10)","3":"BJC","4":"BJC","5":"BJC"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'BJC',
                'external_game_id' => '3',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"JSC","2":"江苏骰宝(快3)","3":"JSC","4":"JSC","5":"JSC"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'JSC',
                'external_game_id' => '4',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"XYC","2":"幸运农场","3":"XYC","4":"XYC","5":"XYC"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'XYC',
                'external_game_id' => '5',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"TJSC","2":"天津时时彩","3":"TJSC","4":"TJSC","5":"TJSC"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'TJSC',
                'external_game_id' => '6',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"XJSC","2":"新疆时时彩","3":"XJSC","4":"XJSC","5":"XJSC"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'XJSC',
                'external_game_id' => '7',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"JXSC","2":"江西时时彩","3":"JXSC","4":"JXSC","5":"JXSC"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'JXSC',
                'external_game_id' => '8',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"YNSC","2":"云南时时彩","3":"YNSC","4":"YNSC","5":"YNSC"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'YNSC',
                'external_game_id' => '9',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"SHSC","2":"上海时时彩","3":"SHSC","4":"SHSC","5":"SHSC"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'SHSC',
                'external_game_id' => '10',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"TJKC","2":"天津快乐十分","3":"TJKC","4":"TJKC","5":"TJKC"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'TJKC',
                'external_game_id' => '11',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"GXKC","2":"广西快乐十分","3":"GXKC","4":"GXKC","5":"GXKC"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'GXKC',
                'external_game_id' => '12',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"HNKC","2":"湖南快乐十分","3":"HNKC","4":"HNKC","5":"HNKC"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'HNKC',
                'external_game_id' => '13',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"AHK3","2":"安徽快3","3":"AHK3","4":"AHK3","5":"AHK3"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'AHK3',
                'external_game_id' => '14',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"GXK3","2":"广西快3","3":"GXK3","4":"GXK3","5":"GXK3"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'GXK3',
                'external_game_id' => '15',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"JLK3","2":"吉林快3","3":"JLK3","4":"JLK3","5":"JLK3"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'JLK3',
                'external_game_id' => '16',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"XYFT","2":"幸运飞艇","3":"XYFT","4":"XYFT","5":"XYFT"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'XYFT',
                'external_game_id' => '17',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"GD115","2":"广东11选5","3":"GD115","4":"GD115","5":"GD115"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'GD115',
                'external_game_id' => '18',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"JX115","2":"江西11选5","3":"JX115","4":"JX115","5":"JX115"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'JX115',
                'external_game_id' => '19',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"SD115","2":"山东11选5","3":"SD115","4":"SD115","5":"SD115"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'SD115',
                'external_game_id' => '20',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"BJ115","2":"北京11选5","3":"BJ115","4":"BJ115","5":"BJ115"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'BJ115',
                'external_game_id' => '21',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"SH115","2":"上海11选5","3":"SH115","4":"SH115","5":"SH115"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'SH115',
                'external_game_id' => '22',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"LN115","2":"辽宁11选5","3":"LN115","4":"LN115","5":"LN115"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'LN115',
                'external_game_id' => '23',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"HB115","2":"湖北11选5","3":"HB115","4":"HB115","5":"HB115"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'HB115',
                'external_game_id' => '24',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"JS115","2":"江苏11选5","3":"JS115","4":"JS115","5":"JS115"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'JS115',
                'external_game_id' => '25',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"AH115","2":"安徽11选5","3":"AH115","4":"AH115","5":"AH115"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'AH115',
                'external_game_id' => '26',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"BJKL8","2":"北京快乐8","3":"BJKL8","4":"BJKL8","5":"BJKL8"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'BJKL8',
                'external_game_id' => '27',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"AZKL8","2":"澳洲快乐8","3":"AZKL8","4":"AZKL8","5":"AZKL8"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'AZKL8',
                'external_game_id' => '28',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"HGKL8","2":"韩国快乐8","3":"HGKL8","4":"HGKL8","5":"HGKL8"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'HGKL8',
                'external_game_id' => '29',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"JNDKL8","2":"加拿大卑斯快乐8","3":"JNDKL8","4":"JNDKL8","5":"JNDKL8"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'JNDKL8',
                'external_game_id' => '30',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"JNDDKL8","2":"加拿大西部快乐8","3":"JNDDKL8","4":"JNDDKL8","5":"JNDDKL8"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'JNDDKL8',
                'external_game_id' => '31',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"SLFKKL8","2":"斯洛伐克快乐8","3":"SLFKKL8","4":"SLFKKL8","5":"SLFKKL8"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'SLFKKL8',
                'external_game_id' => '32',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"METKL8","2":"马耳他快乐8","3":"METKL8","4":"METKL8","5":"METKL8"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'METKL8',
                'external_game_id' => '33',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"TWBGKL8","2":"台湾宾果","3":"TWBGKL8","4":"TWBGKL8","5":"TWBGKL8"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'TWBGKL8',
                'external_game_id' => '34',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"DJKL8","2":"东京快乐8","3":"DJKL8","4":"DJKL8","5":"DJKL8"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'DJKL8',
                'external_game_id' => '35',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"FC3D","2":"福彩3D","3":"FC3D","4":"FC3D","5":"FC3D"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'FC3D',
                'external_game_id' => '36',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"TC3D","2":"体彩3D","3":"TC3D","4":"TC3D","5":"TC3D"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'TC3D',
                'external_game_id' => '37',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"YNKC","2":"云南快乐十分","3":"YNKC","4":"YNKC","5":"YNKC"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'YNKC',
                'external_game_id' => '38',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"BJKL8_PCEGG","2":"北京快8PC蛋蛋","3":"BJKL8_PCEGG","4":"BJKL8_PCEGG","5":"BJKL8_PCEGG"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'BJKL8_PCEGG',
                'external_game_id' => '39',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"AZKL8_PCEGG","2":"澳洲快8PC蛋蛋","3":"AZKL8_PCEGG","4":"AZKL8_PCEGG","5":"AZKL8_PCEGG"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'AZKL8_PCEGG',
                'external_game_id' => '40',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"HGKL8_PCEGG","2":"韩国快8PC蛋蛋","3":"HGKL8_PCEGG","4":"HGKL8_PCEGG","5":"HGKL8_PCEGG"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'HGKL8_PCEGG',
                'external_game_id' => '41',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"JNDKL8_PCEGG","2":"加拿大快8PC蛋蛋","3":"JNDKL8_PCEGG","4":"JNDKL8_PCEGG","5":"JNDKL8_PCEGG"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'JNDKL8_PCEGG',
                'external_game_id' => '42',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"JNDDKL8_PCEGG","2":"加拿大大西部快8PC蛋蛋","3":"JNDDKL8_PCEGG","4":"JNDDKL8_PCEGG","5":"JNDDKL8_PCEGG"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'JNDDKL8_PCEGG',
                'external_game_id' => '43',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"SLFKKL8_PCEGG","2":"斯洛伐克PC蛋蛋","3":"SLFKKL8_PCEGG","4":"SLFKKL8_PCEGG","5":"SLFKKL8_PCEGG"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'SLFKKL8_PCEGG',
                'external_game_id' => '44',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"METKL8_PCEGG","2":"马耳他PC蛋蛋","3":"METKL8_PCEGG","4":"METKL8_PCEGG","5":"METKL8_PCEGG"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'METKL8_PCEGG',
                'external_game_id' => '45',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"TWBGKL8_PCEGG","2":"台湾宾果PC蛋蛋","3":"TWBGKL8_PCEGG","4":"TWBGKL8_PCEGG","5":"TWBGKL8_PCEGG"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'TWBGKL8_PCEGG',
                'external_game_id' => '46',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"DJKL8_PCEGG","2":"东京快乐8PC蛋蛋","3":"DJKL8_PCEGG","4":"DJKL8_PCEGG","5":"DJKL8_PCEGG"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'DJKL8_PCEGG',
                'external_game_id' => '47',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"JSSC","2":"极速赛车","3":"JSSC","4":"JSSC","5":"JSSC"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'JSSC',
                'external_game_id' => '48',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"JSCQ","2":"极速时时彩","3":"JSCQ","4":"JSCQ","5":"JSCQ"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'JSCQ',
                'external_game_id' => '49',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"JSSC60","2":"一分赛车","3":"JSSC60","4":"JSSC60","5":"JSSC60"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'JSSC60',
                'external_game_id' => '50',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"JSCQ60","2":"一分时时彩","3":"JSCQ60","4":"JSCQ60","5":"JSCQ60"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'JSCQ60',
                'external_game_id' => '51',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"KLC_90","2":"极速快乐十分","3":"KLC_90","4":"KLC_90","5":"KLC_90"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'KLC_90',
                'external_game_id' => '52',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"GD115_90","2":"极速十一选五","3":"GD115_90","4":"GD115_90","5":"GD115_90"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'GD115_90',
                'external_game_id' => '53',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"JSC_90","2":"极速快三","3":"JSC_90","4":"JSC_90","5":"JSC_90"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'JSC_90',
                'external_game_id' => '54',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"BJKL8_90","2":"极速快乐8","3":"BJKL8_90","4":"BJKL8_90","5":"BJKL8_90"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'BJKL8_90',
                'external_game_id' => '55',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"FC3D_90","2":"极速3D","3":"FC3D_90","4":"FC3D_90","5":"FC3D_90"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'FC3D_90',
                'external_game_id' => '56',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"PCEGG_90","2":"极速PC蛋蛋","3":"PCEGG_90","4":"PCEGG_90","5":"PCEGG_90"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'PCEGG_90',
                'external_game_id' => '57',
                'sub_game_provider' => 'ig_lottery',
            ],
            [
                'game_platform_id' => $api_id,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_lottery],
                'game_name' => '_json:{"1":"LOTTO_90","2":"极速六合彩","3":"LOTTO_90","4":"LOTTO_90","5":"LOTTO_90"}',
                'game_code' => 'ig_lottery',
                'flash_enabled' => $db_false,
                'english_name' => 'LOTTO_90',
                'external_game_id' => '58',
                'sub_game_provider' => 'ig_lottery',
            ],


        );

        $this->load->model(['game_description_model']);

        $success=$this->game_description_model->syncGameDescription($game_descriptions);

        return $success;
    }

}