<?php
trait game_description_yungu {

	public function sync_game_description_yungu(){
		$cnt=0;
		$cntInsert = 0;
		$cntUpdate = 0;

		$db_true = 1;
		$db_false = 0;
		$api_id = YUNGU_GAME_API;
		$now = $this->utils->getNowForMysql();


        $game_type_code_lottery = SYNC::TAG_CODE_LOTTERY;
        $game_type_code_others  = SYNC::TAG_CODE_OTHER;
        $game_type_code_unknown = SYNC::TAG_CODE_UNKNOWN_GAME;

		// sync game type first
		// use game_type_code as key
        $game_types = [
            $game_type_code_lottery => [
                'game_platform_id'     => $api_id,
                'game_type'            => '_json:{"1":"Lottery credit play","2":"彩票信用玩法","3":"Lottery credit play","4":"Lottery credit play","5":"Lottery credit play"}',
                'game_type_lang'       => '_json:{"1":"Lottery credit play","2":"彩票信用玩法","3":"Lottery credit play","4":"Lottery credit play","5":"Lottery credit play"}',
                'game_type_code'       => $game_type_code_lottery,
                'game_tag_code'       => $game_type_code_lottery,
            ],
            $game_type_code_others => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Others","2":"其他","3":"Others","4":"Others","5":"Others"}',
                'game_type_lang' => '_json:{"1":"Others","2":"其他","3":"Others","4":"Others","5":"Others"}',
                'game_type_code' => $game_type_code_others,
                'game_tag_code' => $game_type_code_others,
            ],
            $game_type_code_unknown => [
                'game_platform_id'     => $api_id,
                'game_type'            => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                'game_type_lang'       => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                'game_type_code'       => $game_type_code_unknown,
                'game_tag_code'       => $game_type_code_unknown,
            ],

		];


		$this->load->model(['game_type_model']);
		$gameTypeCodeMaps=$this->game_type_model->syncGameTypes($game_types);
		$this->utils->debug_log('gameTypeCodeMaps', $gameTypeCodeMaps);

        $game_descriptions = array(
                [
                'game_name'         => '_json:{"1":"Mark Six","2":"六合彩","3":"Mark Six","4":"Mark Six","5":"Mark Six"}',
                'game_code'         => 'liuhecai',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'liuhecai',
                'english_name'      => 'Mark Six',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_lottery],
                ],
                [
                'game_name'         => '_json:{"1":"Lotto 3D","2":"福彩 3d","3":"Lotto 3D","4":"Lotto 3D","5":"Lotto 3D"}',
                'game_code'         => 'fc3d',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'fc3d',
                'english_name'      => 'Lotto 3D',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_lottery],
                ],
                [
                'game_name'         => '_json:{"1":"Sports Lotto","2":"排列 3","3":"Sports Lotto","4":"Sports Lotto","5":"Sports Lotto"}',
                'game_code'         => 'pailie3',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'pailie3',
                'english_name'      => 'Sports Lotto',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_lottery],
                ],
                [
                'game_name'         => '_json:{"1":"Seven Color","2":"七星彩","3":"Seven Color","4":"Seven Color","5":"Seven Color"}',
                'game_code'         => 'qixing',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'qixing',
                'english_name'      => 'Seven Color',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_lottery],
                ],
                [
                'game_name'         => '_json:{"1":"Chongqing Lotto","2":"重庆时时彩","3":"Chongqing Lotto","4":"Chongqing Lotto","5":"Chongqing Lotto"}',
                'game_code'         => 'cqshishicai',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'cqshishicai',
                'english_name'      => 'Chongqing Lotto',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_lottery],
                ],
                [
                'game_name'         => '_json:{"1":"Tianjin Lotto","2":"天津时时彩","3":"Tianjin Lotto","4":"Tianjin Lotto","5":"Tianjin Lotto"}',
                'game_code'         => 'tjshishicai',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'tjshishicai',
                'english_name'      => 'Tianjin Lotto',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_lottery],
                ],
                [
                'game_name'         => '_json:{"1":"Jiangxi Lotto","2":"江西时时彩","3":"Jiangxi Lotto","4":"Jiangxi Lotto","5":"Jiangxi Lotto"}',
                'game_code'         => 'jxshishicai',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'jxshishicai',
                'english_name'      => 'Jiangxi Lotto',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_lottery],
                ],
                [
                'game_name'         => '_json:{"1":"Xinjiang Lotto","2":"新疆时时彩","3":"Xinjiang Lotto","4":"Xinjiang Lotto","5":"Xinjiang Lotto"}',
                'game_code'         => 'xjshishicai',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'xjshishicai',
                'english_name'      => 'Xinjiang Lotto',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_lottery],
                ],
                [
                'game_name'         => '_json:{"1":"Guangxi Happy 10","2":"广西快乐十分","3":"Guangxi Happy 10","4":"Guangxi Happy 10","5":"Guangxi Happy 10"}',
                'game_code'         => 'gxkuaile10',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'gxkuaile10',
                'english_name'      => 'Guangxi Happy 10',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_lottery],
                ],
                [
                'game_name'         => '_json:{"1":"Guangxi Happy 10","2":"广东快乐十分","3":"Guangxi Happy 10","4":"Guangxi Happy 10","5":"Guangxi Happy 10"}',
                'game_code'         => 'gdkuaile10',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'gdkuaile10',
                'english_name'      => 'Guangxi Happy 10',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_lottery],
                ],
                [
                'game_name'         => '_json:{"1":"Chongqing Happy 10","2":"重庆快乐十分","3":"Chongqing Happy 10","4":"Chongqing Happy 10","5":"Chongqing Happy 10"}',
                'game_code'         => 'cqkuaile10',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'cqkuaile10',
                'english_name'      => 'Chongqing Happy 10',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_lottery],
                ],
                [
                'game_name'         => '_json:{"1":"Tianjin Happy 10","2":"天津快乐十分","3":"Tianjin Happy 10","4":"Tianjin Happy 10","5":"Tianjin Happy 10"}',
                'game_code'         => 'tjkuaile10',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'tjkuaile10',
                'english_name'      => 'Tianjin Happy 10',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_lottery],
                ],
                [
                'game_name'         => '_json:{"1":"Guangdong 11/5","2":"广东 11 选 5","3":"Guangdong 11/5","4":"Guangdong 11/5","5":"Guangdong 11/5"}',
                'game_code'         => 'gd11xuan5',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'gd11xuan5',
                'english_name'      => 'Guangdong 11/5',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_lottery],
                ],
                [
                'game_name'         => '_json:{"1":"Jiangxi 11/5","2":"江西 11 选 5","3":"Jiangxi 11/5","4":"Jiangxi 11/5","5":"Jiangxi 11/5"}',
                'game_code'         => 'jx11xuan5',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'jx11xuan5',
                'english_name'      => 'Jiangxi 11/5',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_lottery],
                ],
                [
                'game_name'         => '_json:{"1":"Shandong 11/5","2":"山东 11 选 5","3":"Shandong 11/5","4":"Shandong 11/5","5":"Shandong 11/5"}',
                'game_code'         => 'sd11xuan5',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'sd11xuan5',
                'english_name'      => 'Shandong 11/5',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_lottery],
                ],
                [
                'game_name'         => '_json:{"1":"Guizhou 11/5","2":"贵州 11 选 5","3":"Guizhou 11/5","4":"Guizhou 11/5","5":"Guizhou 11/5"}',
                'game_code'         => 'gz11xuan5',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'gz11xuan5',
                'english_name'      => 'Guizhou 11/5',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_lottery],
                ],
                [
                'game_name'         => '_json:{"1":"Beijing PK10","2":"北京 PK 拾","3":"Beijing PK10","4":"Beijing PK10","5":"Beijing PK10"}',
                'game_code'         => 'bjpkshi',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'bjpkshi',
                'english_name'      => 'Beijing PK10',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_lottery],
                ],
                [
                'game_name'         => '_json:{"1":"Beijing Happy 8","2":"北京快乐 8","3":"Beijing Happy 8","4":"Beijing Happy 8","5":"Beijing Happy 8"}',
                'game_code'         => 'bjkuaile8',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'bjkuaile8',
                'english_name'      => 'Beijing Happy 8',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_lottery],
                ],
                [
                'game_name'         => '_json:{"1":"Guangxi Fast 3","2":"广西快 3","3":"Guangxi Fast 3","4":"Guangxi Fast 3","5":"Guangxi Fast 3"}',
                'game_code'         => 'gxkuai3',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'gxkuai3',
                'english_name'      => 'Guangxi Fast 3',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_lottery],
                ],
                [
                'game_name'         => '_json:{"1":"Jilin Fast 3","2":"吉林快 3","3":"Jilin Fast 3","4":"Jilin Fast 3","5":"Jilin Fast 3"}',
                'game_code'         => 'jilin_kuai3',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'jilin_kuai3',
                'english_name'      => 'Jilin Fast 3',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_lottery],
                ],
                [
                'game_name'         => '_json:{"1":"Anhui Sic Bo","2":"安徽骰宝","3":"Anhui Sic Bo","4":"Anhui Sic Bo","5":"Anhui Sic Bo"}',
                'game_code'         => 'ahkuai3',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'ahkuai3',
                'english_name'      => 'Anhui Sic Bo',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_lottery],
                ],
                [
                'game_name'         => '_json:{"1":"Jiangsu Sic Bo","2":"江苏骰宝","3":"Jiangsu Sic Bo","4":"Jiangsu Sic Bo","5":"Jiangsu Sic Bo"}',
                'game_code'         => 'jskuai3',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'jskuai3',
                'english_name'      => 'Jiangsu Sic Bo',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_lottery],
                ],
                [
                'game_name'         => '_json:{"1":"Hubei Sic Bo","2":"湖北骰宝","3":"Hubei Sic Bo","4":"Hubei Sic Bo","5":"Hubei Sic Bo"}',
                'game_code'         => 'hubei_shaibao',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'hubei_shaibao',
                'english_name'      => 'Hubei Sic Bo',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_lottery],
                ],
                [
                'game_name'         => '_json:{"1":"Hebei Sic Bo","2":"河北骰宝","3":"Hebei Sic Bo","4":"Hebei Sic Bo","5":"Hebei Sic Bo"}',
                'game_code'         => 'hebei_shaibao',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'hebei_shaibao',
                'english_name'      => 'Hebei Sic Bo',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_lottery],
                ],

                [
                'game_name'         => '_json:{"1":"Chongqing Lotto","2":"重庆时时彩","3":"Chongqing Lotto","4":"Chongqing Lotto","5":"Chongqing Lotto"}',
                'game_code'         => 'cqshishicai_gf',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'cqshishicai_gf',
                'english_name'      => 'Chongqing Lotto',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_lottery],
                ],
                [
                'game_name'         => '_json:{"1":"Tianjin Lotto","2":"天津时时彩","3":"Tianjin Lotto","4":"Tianjin Lotto","5":"Tianjin Lotto"}',
                'game_code'         => 'tjshishicai_gf',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'tjshishicai_gf',
                'english_name'      => 'Tianjin Lotto',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_lottery],
                ],
                [
                'game_name'         => '_json:{"1":"Xinjiang Lotto","2":"新疆时时彩","3":"Xinjiang Lotto","4":"Xinjiang Lotto","5":"Xinjiang Lotto"}',
                'game_code'         => 'xjshishicai_gf',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'xjshishicai_gf',
                'english_name'      => 'Xinjiang Lotto',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_lottery],
                ],
                [
                'game_name'         => '_json:{"1":"Beijing PK10","2":"北京 PK 拾","3":"Beijing PK10","4":"Beijing PK10","5":"Beijing PK10"}',
                'game_code'         => 'bjpkshi_gf',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'bjpkshi_gf',
                'english_name'      => 'Beijing PK10',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_lottery],
                ],
                [
                'game_name'         => '_json:{"1":"Guangdong 11/5","2":"广东 11 选 5","3":"Guangdong 11/5","4":"Guangdong 11/5","5":"Guangdong 11/5"}',
                'game_code'         => 'gd11xuan5_gf',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'gd11xuan5_gf',
                'english_name'      => 'Guangdong 11/5',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_lottery],
                ],
                [
                'game_name'         => '_json:{"1":"Shandong 11/5","2":"山东 11 选 5","3":"Shandong 11/5","4":"Shandong 11/5","5":"Shandong 11/5"}',
                'game_code'         => 'sd11xuan5_gf',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'sd11xuan5_gf',
                'english_name'      => 'Shandong 11/5',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_lottery],
                ],
                [
                'game_name'         => '_json:{"1":"Jiangxi 11/5","2":"江西 11 选 5","3":"Jiangxi 11/5","4":"Jiangxi 11/5","5":"Jiangxi 11/5"}',
                'game_code'         => 'jx11xuan5_gf',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'jx11xuan5_gf',
                'english_name'      => 'Jiangxi 11/5',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_lottery],
                ],
                [
                'game_name'         => '_json:{"1":"Shanghai 11/5","2":"上海 11 选 5","3":"Shanghai 11/5","4":"Shanghai 11/5","5":"Shanghai 11/5"}',
                'game_code'         => 'sh11xuan5_gf',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'sh11xuan5_gf',
                'english_name'      => 'Shanghai 11/5',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_lottery],
                ],
                [
                'game_name'         => '_json:{"1":"Lotto 3D","2":"福彩 3D","3":"Lotto 3D","4":"Lotto 3D","5":"Lotto 3D"}',
                'game_code'         => 'fc3d_gf',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'fc3d_gf',
                'english_name'      => 'Lotto 3D',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_lottery],
                ],
                [
                'game_name'         => '_json:{"1":"Sports Lotto","2":"排列 3","3":"Sports Lotto","4":"Sports Lotto","5":"Sports Lotto"}',
                'game_code'         => 'pailie3_gf',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'pailie3_gf',
                'english_name'      => 'Sports Lotto',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_lottery],
                ],

                [
                'game_name'         => '_json:{"1":"Fish Hunter King","2":"捕鱼王","3":"Fish Hunter King","4":"Fish Hunter King","5":"Fish Hunter King"}',
                'game_code'         => 'BUYU',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'BUYU',
                'english_name'      => 'Fish Hunter King',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_others],
                ],
                [
                'game_name'         => '_json:{"1":"AGIN","2":"AG 国际游戏厅","3":"AGIN","4":"AGIN","5":"AGIN"}',
                'game_code'         => 'AGIN',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'AGIN',
                'english_name'      => 'AGIN',
                'status'            => $db_true,
                'flag_show_in_site' => $db_true,
                'html_five_enabled' => $db_true,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_others],
                ],

                [
                'game_name'         => '_json:{"1":"UNKNOWN GAME","2":"不明游戏","3":"UNKNOWN GAME","4":"UNKNOWN GAME","5":"UNKNOWN GAME"}',
                'game_code'         => 'unknown',
                'game_platform_id'  => $api_id,
                'external_game_id'  => 'unknown',
                'english_name'      => 'UNKNOWN GAME',
                'status'            => $db_true,
                'flag_show_in_site' => $db_false,
                'game_type_id'      => $gameTypeCodeMaps[$game_type_code_unknown],
                ],
                );

                $this->load->model(['game_description_model']);

                $success=$this->game_description_model->syncGameDescription($game_descriptions);

                return $success;
    }
}
