<?php
trait game_description_ebet_ag {

    public function sync_game_description_ebet_ag(){
        $api_id=EBET_AG_API;
        $db_true=1;
        $db_false=0;
        $now=$this->utils->getNowForMysql();

        $game_type_code_agin='ag_agin';
        $game_type_code_hunter='ag_hunter';
        $game_type_code_agtex='ag_agtex';
        $game_type_code_xin='ag_xin';
        $game_type_code_yoplay='ag_yoplay';
        $game_type_code_unknown='ag_unknown';

        //sync game type first
        $game_types = [
            $game_type_code_agin => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"AGIN","2":"AG 国际厅","3":"AGIN","4":"AGIN","5":"AGIN"}',
                'game_type_lang' => '_json:{"1":"AGIN","2":"AG 国际厅","3":"AGIN","4":"AGIN","5":"AGIN"}',
                'game_type_code' => $game_type_code_agin,
                'updated_at' => $now,
                'game_tag_code' => SYNC::TAG_CODE_LIVE_DEALER
            ],
            $game_type_code_hunter => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"HUNTER","2":"捕鱼王","3":"HUNTER","4":"HUNTER","5":"HUNTER"}',
                'game_type_lang' => '_json:{"1":"HUNTER","2":"捕鱼王","3":"HUNTER","4":"HUNTER","5":"HUNTER"}',
                'game_type_code' => $game_type_code_hunter,
                'updated_at' => $now,
                'game_tag_code' => SYNC::TAG_CODE_FISHING_GAME
            ],
            $game_type_code_agtex => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Asia Gaming Tex","2":"棋牌大厅","3":"Asia Gaming Tex","4":"Asia Gaming Tex","5":"Asia Gaming Tex"}',
                'game_type_lang' => '_json:{"1":"Asia Gaming Tex","2":"棋牌大厅","3":"Asia Gaming Tex","4":"Asia Gaming Tex","5":"Asia Gaming Tex"}',
                'game_type_code' => $game_type_code_agtex,
                'updated_at' => $now,
                'game_tag_code' => SYNC::TAG_CODE_SLOT
            ],
            $game_type_code_xin => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"XIN","2":"XIN电子游戏","3":"XIN","4":"XIN","5":"XIN"}',
                'game_type_lang' => '_json:{"1":"XIN","2":"XIN电子游戏","3":"XIN","4":"XIN","5":"XIN"}',
                'game_type_code' => $game_type_code_xin,
                'updated_at' => $now,
                'game_tag_code' => SYNC::TAG_CODE_SLOT
            ],
            $game_type_code_yoplay => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"YoPlay","2":"YoPlay游戏","3":"YoPlay","4":"YoPlay","5":"YoPlay"}',
                'game_type_lang' => '_json:{"1":"YoPlay","2":"YoPlay游戏","3":"YoPlay","4":"YoPlay","5":"YoPlay"}',
                'game_type_code' => $game_type_code_yoplay,
                'updated_at' => $now,
                'game_tag_code' => SYNC::TAG_CODE_SLOT
            ],
            $game_type_code_unknown => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Unknown","2":"不明类型","3":"Unknown","4":"Unknown","5":"Unknown"}',
                'game_type_lang' => '_json:{"1":"Unknown","2":"不明类型","3":"Unknown","4":"Unknown","5":"Unknown"}',
                'game_type_code' => $game_type_code_unknown,
                'updated_at' => $now,
                'game_tag_code' => SYNC::TAG_CODE_UNKNOWN_GAME
            ],
        ];

        $this->load->model(['game_type_model']);
        $gameTypeCodeMaps=$this->game_type_model->syncGameTypes($game_types);

        $this->utils->debug_log('gameTypeCodeMaps', $gameTypeCodeMaps);

        if(empty($gameTypeCodeMaps)){
            return false;
        }

        $game_descriptions = array(
            [
                'game_name' => '_json:{"1":"FIFA (2014 FIFA World Cup Brazil)","2":"巴西世界杯","3":"FIFA (2014 FIFA World Cup Brazil)","4":"FIFA (2014 FIFA World Cup Brazil)","5":"FIFA (2014 FIFA World Cup Brazil)"}',
                'game_code' => 'SL1',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SL1',
                'english_name' => 'FIFA (2014 FIFA World Cup Brazil)',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Fruit Shop Frenzy","2":"疯狂水果店","3":"Fruit Shop Frenzy","4":"Fruit Shop Frenzy","5":"Fruit Shop Frenzy"}',
                'game_code' => 'SL2',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SL2',
                'english_name' => 'Fruit Shop Frenzy',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"3D Aquarlum","2":"3D 水族馆","3":"3D Aquarlum","4":"3D Aquarlum","5":"3D Aquarlum"}',
                'game_code' => 'SL3',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SL3',
                'english_name' => '3D Aquarlum',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Video Poker(jacks or better)","2":"视频扑克(杰克高手)","3":"Video Poker(jacks or better)","4":"Video Poker(jacks or better)","5":"Video Poker(jacks or better)"}',
                'game_code' => 'PK_J',
                'game_platform_id' => $api_id,
                'external_game_id' => 'PK_J',
                'english_name' => 'Video Poker(jacks or better)',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Speed Racing","2":"极速赛车","3":"Speed Racing","4":"Speed Racing","5":"Speed Racing"}',
                'game_code' => 'SL4',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SL4',
                'english_name' => 'Speed Racing',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Video poker2 (jacks or better)","2":"新视频扑克(杰克高手)","3":"Video poker2 (jacks or better)","4":"Video poker2 (jacks or better)","5":"Video poker2 (jacks or better)"}',
                'game_code' => 'PKBJ',
                'game_platform_id' => $api_id,
                'external_game_id' => 'PKBJ',
                'english_name' => 'Video poker2 (jacks or better)',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Fruit Slot","2":"水果拉霸","3":"Fruit Slot","4":"Fruit Slot","5":"Fruit Slot"}',
                'game_code' => 'FRU',
                'game_platform_id' => $api_id,
                'external_game_id' => 'FRU',
                'english_name' => 'Fruit Slot',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Beauty & Beach Volley","2":"美女沙排(沙滩排球)","3":"Beauty & Beach Volley","4":"Beauty & Beach Volley","5":"Beauty & Beach Volley"}',
                'game_code' => 'SLM1',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SLM1',
                'english_name' => 'Beauty & Beach Volley',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"The Wealthy Lamb","2":"运财羊(新年运财羊)","3":"The Wealthy Lamb","4":"The Wealthy Lamb","5":"The Wealthy Lamb"}',
                'game_code' => 'SLM2',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SLM2',
                'english_name' => 'The Wealthy Lamb',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Legend of Warriors","2":"武圣传","3":"Legend of Warriors","4":"Legend of Warriors","5":"Legend of Warriors"}',
                'game_code' => 'SLM3',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SLM3',
                'english_name' => 'Legend of Warriors',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Lucky Slot","2":"幸运老虎机","3":"Lucky Slot","4":"Lucky Slot","5":"Lucky Slot"}',
                'game_code' => 'SC01',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SC01',
                'english_name' => 'Lucky Slot',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Speedy Lucky Wheel","2":"极速幸运轮","3":"Speedy Lucky Wheel","4":"Speedy Lucky Wheel","5":"Speedy Lucky Wheel"}',
                'game_code' => 'TGLW',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TGLW',
                'english_name' => 'Speedy Lucky Wheel',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Empress Wu Zetian","2":"武则天","3":"Empress Wu Zetian","4":"Empress Wu Zetian","5":"Empress Wu Zetian"}',
                'game_code' => 'SLM4',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SLM4',
                'english_name' => 'Empress Wu Zetian',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Casino War","2":"赌场战争","3":"Casino War","4":"Casino War","5":"Casino War"}',
                'game_code' => 'TGCW',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TGCW',
                'english_name' => 'Casino War',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Space Odyssey","2":"太空漫游","3":"Space Odyssey","4":"Space Odyssey","5":"Space Odyssey"}',
                'game_code' => 'SB01',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB01',
                'english_name' => 'Space Odyssey',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Vintage Garden","2":"复古花园","3":"Vintage Garden","4":"Vintage Garden","5":"Vintage Garden"}',
                'game_code' => 'SB02',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB02',
                'english_name' => 'Vintage Garden',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Oden","2":"关东煮","3":"Oden","4":"Oden","5":"Oden"}',
                'game_code' => 'SB03',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB03',
                'english_name' => 'Oden',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Farm Café","2":"牧场咖啡","3":"Farm Café","4":"Farm Café","5":"Farm Café"}',
                'game_code' => 'SB04',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB04',
                'english_name' => 'Farm Café',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Sweets Home","2":"甜一甜屋","3":"Sweets Home","4":"Sweets Home","5":"Sweets Home"}',
                'game_code' => 'SB05',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB05',
                'english_name' => 'Sweets Home',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Samurai","2":"日本武士","3":"Samurai","4":"Samurai","5":"Samurai"}',
                'game_code' => 'SB06',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB06',
                'english_name' => 'Samurai',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Chinese Chess Slot","2":"象棋老虎机","3":"Chinese Chess Slot","4":"Chinese Chess Slot","5":"Chinese Chess Slot"}',
                'game_code' => 'SB07',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB07',
                'english_name' => 'Chinese Chess Slot',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Mahjong Slot","2":"麻将老虎机","3":"Mahjong Slot","4":"Mahjong Slot","5":"Mahjong Slot"}',
                'game_code' => 'SB08',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB08',
                'english_name' => 'Mahjong Slot',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Chess Slot","2":"西洋棋老虎机","3":"Chess Slot","4":"Chess Slot","5":"Chess Slot"}',
                'game_code' => 'SB09',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB09',
                'english_name' => 'Chess Slot',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Happy Farm","2":"开心农场","3":"Happy Farm","4":"Happy Farm","5":"Happy Farm"}',
                'game_code' => 'SB10',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB10',
                'english_name' => 'Happy Farm',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Summer Campsite","2":"夏日营地","3":"Summer Campsite","4":"Summer Campsite","5":"Summer Campsite"}',
                'game_code' => 'SB11',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB11',
                'english_name' => 'Summer Campsite',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Sea World Odyssey","2":"海底漫游","3":"Sea World Odyssey","4":"Sea World Odyssey","5":"Sea World Odyssey"}',
                'game_code' => 'SB12',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB12',
                'english_name' => 'Sea World Odyssey',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Funny Clown","2":"鬼马小丑","3":"Funny Clown","4":"Funny Clown","5":"Funny Clown"}',
                'game_code' => 'SB13',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB13',
                'english_name' => 'Funny Clown',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Amazing Rides","2":"机动乐园","3":"Amazing Rides","4":"Amazing Rides","5":"Amazing Rides"}',
                'game_code' => 'SB14',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB14',
                'english_name' => 'Amazing Rides',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Spooky House","2":"惊吓鬼屋","3":"Spooky House","4":"Spooky House","5":"Spooky House"}',
                'game_code' => 'SB15',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB15',
                'english_name' => 'Spooky House',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Crazy Circus","2":"疯狂马戏团","3":"Crazy Circus","4":"Crazy Circus","5":"Crazy Circus"}',
                'game_code' => 'SB16',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB16',
                'english_name' => 'Crazy Circus',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Ocean Theatre","2":"海洋剧场","3":"Ocean Theatre","4":"Ocean Theatre","5":"Ocean Theatre"}',
                'game_code' => 'SB17',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB17',
                'english_name' => 'Ocean Theatre',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Wonderful Waterpark","2":"水上乐园","3":"Wonderful Waterpark","4":"Wonderful Waterpark","5":"Wonderful Waterpark"}',
                'game_code' => 'SB18',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB18',
                'english_name' => 'Wonderful Waterpark',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"God of Land Fortune","2":"土地神","3":"God of Land Fortune","4":"God of Land Fortune","5":"God of Land Fortune"}',
                'game_code' => 'SB25',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB25',
                'english_name' => 'God of Land Fortune',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"God of Bag Monk Fortune","2":"布袋和尚","3":"God of Bag Monk Fortune","4":"God of Bag Monk Fortune","5":"God of Bag Monk Fortune"}',
                'game_code' => 'SB26',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB26',
                'english_name' => 'God of Bag Monk Fortune',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"God of Fortune","2":"正财神","3":"God of Fortune","4":"God of Fortune","5":"God of Fortune"}',
                'game_code' => 'SB27',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB27',
                'english_name' => 'God of Fortune',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"God of Wu Fortune","2":"武财神","3":"God of Wu Fortune","4":"God of Wu Fortune","5":"God of Wu Fortune"}',
                'game_code' => 'SB28',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB28',
                'english_name' => 'God of Wu Fortune',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"God of Gamble Fortune","2":"偏财神","3":"God of Gamble Fortune","4":"God of Gamble Fortune","5":"God of Gamble Fortune"}',
                'game_code' => 'SB29',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB29',
                'english_name' => 'God of Gamble Fortune',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Aerial Warfare","2":"空中战争","3":"Aerial Warfare","4":"Aerial Warfare","5":"Aerial Warfare"}',
                'game_code' => 'SB19',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB19',
                'english_name' => 'Aerial Warfare',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Rock And Roll","2":"摇滚狂迷","3":"Rock And Roll","4":"Rock And Roll","5":"Rock And Roll"}',
                'game_code' => 'SB20',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB20',
                'english_name' => 'Rock And Roll',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Motor Gear","2":"越野机车","3":"Motor Gear","4":"Motor Gear","5":"Motor Gear"}',
                'game_code' => 'SB21',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB21',
                'english_name' => 'Motor Gear',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Egypt Mystery","2":"埃及奥秘","3":"Egypt Mystery","4":"Egypt Mystery","5":"Egypt Mystery"}',
                'game_code' => 'SB22',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB22',
                'english_name' => 'Egypt Mystery',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Happy Hour","2":"欢乐时光","3":"Happy Hour","4":"Happy Hour","5":"Happy Hour"}',
                'game_code' => 'SB23',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB23',
                'english_name' => 'Happy Hour',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Jurassic Slot","2":"侏罗纪","3":"Jurassic Slot","4":"Jurassic Slot","5":"Jurassic Slot"}',
                'game_code' => 'SB24',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB24',
                'english_name' => 'Jurassic Slot',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Sexy Maid","2":"性感女仆","3":"Sexy Maid","4":"Sexy Maid","5":"Sexy Maid"}',
                'game_code' => 'AV01',
                'game_platform_id' => $api_id,
                'external_game_id' => 'AV01',
                'english_name' => 'Sexy Maid',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Dragons Pearl","2":"龙珠","3":"Dragons Pearl","4":"Dragons Pearl","5":"Dragons Pearl"}',
                'game_code' => 'XG01',
                'game_platform_id' => $api_id,
                'external_game_id' => 'XG01',
                'english_name' => 'Dragons Pearl',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Lucky8","2":"幸运 8","3":"Lucky8","4":"Lucky8","5":"Lucky8"}',
                'game_code' => 'XG02',
                'game_platform_id' => $api_id,
                'external_game_id' => 'XG02',
                'english_name' => 'Lucky8',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Bling Bling","2":"闪亮女郎","3":"Bling Bling","4":"Bling Bling","5":"Bling Bling"}',
                'game_code' => 'XG03',
                'game_platform_id' => $api_id,
                'external_game_id' => 'XG03',
                'english_name' => 'Bling Bling',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Goldfish","2":"金鱼","3":"Goldfish","4":"Goldfish","5":"Goldfish"}',
                'game_code' => 'XG04',
                'game_platform_id' => $api_id,
                'external_game_id' => 'XG04',
                'english_name' => 'Goldfish',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Chinese New Year","2":"中国新年","3":"Chinese New Year","4":"Chinese New Year","5":"Chinese New Year"}',
                'game_code' => 'XG05',
                'game_platform_id' => $api_id,
                'external_game_id' => 'XG05',
                'english_name' => 'Chinese New Year',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Pirates","2":"海盗王","3":"Pirates","4":"Pirates","5":"Pirates"}',
                'game_code' => 'XG06',
                'game_platform_id' => $api_id,
                'external_game_id' => 'XG06',
                'english_name' => 'Pirates',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Fruitmania","2":"鲜果狂热","3":"Fruitmania","4":"Fruitmania","5":"Fruitmania"}',
                'game_code' => 'XG07',
                'game_platform_id' => $api_id,
                'external_game_id' => 'XG07',
                'english_name' => 'Fruitmania',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Red Panda","2":"小熊猫","3":"Red Panda","4":"Red Panda","5":"Red Panda"}',
                'game_code' => 'XG08',
                'game_platform_id' => $api_id,
                'external_game_id' => 'XG08',
                'english_name' => 'Red Panda',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"High Roller","2":"大豪客","3":"High Roller","4":"High Roller","5":"High Roller"}',
                'game_code' => 'XG09',
                'game_platform_id' => $api_id,
                'external_game_id' => 'XG09',
                'english_name' => 'High Roller',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Year of the Monkey","2":"灵猴献瑞","3":"Year of the Monkey","4":"Year of the Monkey","5":"Year of the Monkey"}',
                'game_code' => 'SB30',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB30',
                'english_name' => 'Year of the Monkey',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Sky Guardians","2":"天空守护者","3":"Sky Guardians","4":"Sky Guardians","5":"Sky Guardians"}',
                'game_code' => 'SB31',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB31',
                'english_name' => 'Sky Guardians',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Deuces Wild","2":"百搭二王","3":"Deuces Wild","4":"Deuces Wild","5":"Deuces Wild"}',
                'game_code' => 'PKBD',
                'game_platform_id' => $api_id,
                'external_game_id' => 'PKBD',
                'english_name' => 'Deuces Wild',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Bonus Deuces Wild","2":"红利百搭","3":"Bonus Deuces Wild","4":"Bonus Deuces Wild","5":"Bonus Deuces Wild"}',
                'game_code' => 'PKBB',
                'game_platform_id' => $api_id,
                'external_game_id' => 'PKBB',
                'english_name' => 'Bonus Deuces Wild',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Monkey King","2":"齐天大圣","3":"Monkey King","4":"Monkey King","5":"Monkey King"}',
                'game_code' => 'SB32',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB32',
                'english_name' => 'Monkey King',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Candy Quest","2":"糖果碰碰乐","3":"Candy Quest","4":"Candy Quest","5":"Candy Quest"}',
                'game_code' => 'SB33',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB33',
                'english_name' => 'Candy Quest',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Ice Crush","2":"冰河世界","3":"Ice Crush","4":"Ice Crush","5":"Ice Crush"}',
                'game_code' => 'SB34',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB34',
                'english_name' => 'Ice Crush',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Fruit Slot 2","2":"水果拉霸 2","3":"Fruit Slot 2","4":"Fruit Slot 2","5":"Fruit Slot 2"}',
                'game_code' => 'FRU2',
                'game_platform_id' => $api_id,
                'external_game_id' => 'FRU2',
                'english_name' => 'Fruit Slot 2',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Blackjack","2":"21 点 (电子游戏)","3":"Blackjack","4":"Blackjack","5":"Blackjack"}',
                'game_code' => 'TG01',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TG01',
                'english_name' => 'Blackjack',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Baccarat","2":"百家乐 (电子游戏)","3":"Baccarat","4":"Baccarat","5":"Baccarat"}',
                'game_code' => 'TG02',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TG02',
                'english_name' => 'Baccarat',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Roulette","2":"轮盘 (电子游戏)","3":"Roulette","4":"Roulette","5":"Roulette"}',
                'game_code' => 'TG03',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TG03',
                'english_name' => 'Roulette',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Euro Football Champ","2":"欧洲列强争霸 ","3":"Euro Football Champ","4":"Euro Football Champ","5":"Euro Football Champ"}',
                'game_code' => 'SB35',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB35',
                'english_name' => 'Euro Football Champ',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Fish Hunter King","2":"捕鱼王者","3":"Fish Hunter King","4":"Fish Hunter King","5":"Fish Hunter King"}',
                'game_code' => 'SB36',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB36',
                'english_name' => 'Fish Hunter King',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Shanghai Bund","2":"上海百乐门","3":"Shanghai Bund","4":"Shanghai Bund","5":"Shanghai Bund"}',
                'game_code' => 'SB37',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB37',
                'english_name' => 'Shanghai Bund',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Rio Fever","2":"竞技狂热","3":"Rio Fever","4":"Rio Fever","5":"Rio Fever"}',
                'game_code' => 'SB38',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB38',
                'english_name' => 'Rio Fever',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Space Fruit","2":"太空水果","3":"Space Fruit","4":"Space Fruit","5":"Space Fruit"}',
                'game_code' => 'SB39',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB39',
                'english_name' => 'Space Fruit',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Qin Empire","2":"秦始皇","3":"Qin Empire","4":"Qin Empire","5":"Qin Empire"}',
                'game_code' => 'SB40',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SB40',
                'english_name' => 'Qin Empire',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Multi Hand Blackjack Low Limits","2":"多手二十一点 低额投注","3":"Multi Hand Blackjack Low Limits","4":"Multi Hand Blackjack Low Limits","5":"Multi Hand Blackjack Low Limits"}',
                'game_code' => 'TA01',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA01',
                'english_name' => 'Multi Hand Blackjack Low Limits',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Multi Hand Blackjack","2":"多手二十一点","3":"Multi Hand Blackjack","4":"Multi Hand Blackjack","5":"Multi Hand Blackjack"}',
                'game_code' => 'TA02',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA02',
                'english_name' => 'Multi Hand Blackjack',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Multi Hand Blackjack High Limits","2":"多手二十一点 高额投注","3":"Multi Hand Blackjack High Limits","4":"Multi Hand Blackjack High Limits","5":"Multi Hand Blackjack High Limits"}',
                'game_code' => 'TA03',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA03',
                'english_name' => 'Multi Hand Blackjack High Limits',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Single Hand Blackjack Low Limits","2":"1 手二十一点 低额投注","3":"Single Hand Blackjack Low Limits","4":"Single Hand Blackjack Low Limits","5":"Single Hand Blackjack Low Limits"}',
                'game_code' => 'TA04',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA04',
                'english_name' => 'Single Hand Blackjack Low Limits',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Single Hand Blackjack","2":"1 手二十一点","3":"Single Hand Blackjack","4":"Single Hand Blackjack","5":"Single Hand Blackjack"}',
                'game_code' => 'TA05',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA05',
                'english_name' => 'Single Hand Blackjack',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Single Hand Blackjack High Limits","2":"1 手二十一点 高额投注","3":"Single Hand Blackjack High Limits","4":"Single Hand Blackjack High Limits","5":"Single Hand Blackjack High Limits"}',
                'game_code' => 'TA06',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA06',
                'english_name' => 'Single Hand Blackjack High Limits',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Hilo Low Limits","2":"Hilo 低额投注","3":"Hilo Low Limits","4":"Hilo Low Limits","5":"Hilo Low Limits"}',
                'game_code' => 'TA07',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA07',
                'english_name' => 'Hilo Low Limits',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Hilo","2":"Hilo","3":"Hilo","4":"Hilo","5":"Hilo"}',
                'game_code' => 'TA08',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA08',
                'english_name' => 'Hilo',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Hilo High Limits","2":"Hilo 高額投注 ","3":"Hilo High Limits","4":"Hilo High Limits","5":"Hilo High Limits"}',
                'game_code' => 'TA09',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA09',
                'english_name' => 'Hilo High Limits',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"5H Hilo","2":"5 手 Hilo","3":"5H Hilo","4":"5H Hilo","5":"5H Hilo"}',
                'game_code' => 'TA0A',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA0A',
                'english_name' => '5H Hilo',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"5H Hilo High Limits","2":"5 手 Hilo 高额投注","3":"5H Hilo High Limits","4":"5H Hilo High Limits","5":"5H Hilo High Limits"}',
                'game_code' => 'TA0B',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA0B',
                'english_name' => '5H Hilo High Limits',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"3H Hilo High Limits","2":"3 手 Hilo 高额投注","3":"3H Hilo High Limits","4":"3H Hilo High Limits","5":"3H Hilo High Limits"}',
                'game_code' => 'TA0C',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA0C',
                'english_name' => '3H Hilo High Limits',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Roulette High Limits","2":"轮盘","3":"Roulette High Limits","4":"Roulette High Limits","5":"Roulette High Limits"}',
                'game_code' => 'TA0F',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA0F',
                'english_name' => 'Roulette High Limits',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Roulette","2":"轮盘","3":"Roulette","4":"Roulette","5":"Roulette"}',
                'game_code' => 'TA0G',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA0G',
                'english_name' => 'Roulette',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"5H Jacks or Better","2":"5 手杰克高手","3":"5H Jacks or Better","4":"5H Jacks or Better","5":"5H Jacks or Better"}',
                'game_code' => 'TA0Z',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA0Z',
                'english_name' => '5H Jacks or Better',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"5H Joker Wild","2":"5 手百搭小丑","3":"5H Joker Wild","4":"5H Joker Wild","5":"5H Joker Wild"}',
                'game_code' => 'TA10',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA10',
                'english_name' => '5H Joker Wild',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"5H Deuces Wild","2":"5 手百搭二王","3":"5H Deuces Wild","4":"5H Deuces Wild","5":"5H Deuces Wild"}',
                'game_code' => 'TA11',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA11',
                'english_name' => '5H Deuces Wild',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"1H Jacks or Better","2":"1 手杰克高手","3":"1H Jacks or Better","4":"1H Jacks or Better","5":"1H Jacks or Better"}',
                'game_code' => 'TA12',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA12',
                'english_name' => '1H Jacks or Better',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"10H Jacks or Better","2":"10 手杰克高手","3":"10H Jacks or Better","4":"10H Jacks or Better","5":"10H Jacks or Better"}',
                'game_code' => 'TA13',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA13',
                'english_name' => '10H Jacks or Better',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"25H Jacks or Better","2":"25 手杰克高手","3":"25H Jacks or Better","4":"25H Jacks or Better","5":"25H Jacks or Better"}',
                'game_code' => 'TA14',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA14',
                'english_name' => '25H Jacks or Better',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"50H Jacks or Better","2":"50 手杰克高手","3":"50H Jacks or Better","4":"50H Jacks or Better","5":"50H Jacks or Better"}',
                'game_code' => 'TA15',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA15',
                'english_name' => '50H Jacks or Better',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"1H Joker Wild","2":"1 手百搭小丑","3":"1H Joker Wild","4":"1H Joker Wild","5":"1H Joker Wild"}',
                'game_code' => 'TA17',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA17',
                'english_name' => '1H Joker Wild',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"10H Joker Wild","2":"10 手百搭小丑","3":"10H Joker Wild","4":"10H Joker Wild","5":"10H Joker Wild"}',
                'game_code' => 'TA18',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA18',
                'english_name' => '10H Joker Wild',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"25H Joker Wild","2":"25 手百搭小丑 ","3":"25H Joker Wild","4":"25H Joker Wild","5":"25H Joker Wild"}',
                'game_code' => 'TA19',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA19',
                'english_name' => '25H Joker Wild',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"50H Joker Wild","2":"50 手百搭小丑","3":"50H Joker Wild","4":"50H Joker Wild","5":"50H Joker Wild"}',
                'game_code' => 'TA1A',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA1A',
                'english_name' => '50H Joker Wild',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"1H Deuces Wild","2":"1 手百搭二王","3":"1H Deuces Wild","4":"1H Deuces Wild","5":"1H Deuces Wild"}',
                'game_code' => 'TA1C',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA1C',
                'english_name' => '1H Deuces Wild',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"10H Deuces Wild","2":"10 手百搭二王","3":"10H Deuces Wild","4":"10H Deuces Wild","5":"10H Deuces Wild"}',
                'game_code' => 'TA1D',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA1D',
                'english_name' => '10H Deuces Wild',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"25H Deuces Wild","2":"25 手百搭二王","3":"25H Deuces Wild","4":"25H Deuces Wild","5":"25H Deuces Wild"}',
                'game_code' => 'TA1E',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA1E',
                'english_name' => '25H Deuces Wild',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"50H Deuces Wild","2":"50 手百搭二王","3":"50H Deuces Wild","4":"50H Deuces Wild","5":"50H Deuces Wild"}',
                'game_code' => 'TA1F',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA1F',
                'english_name' => '50H Deuces Wild',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Lowriders","2":"经典轿车","3":"Lowriders","4":"Lowriders","5":"Lowriders"}',
                'game_code' => 'TA0U',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA0U',
                'english_name' => 'Lowriders',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Galactic Cash","2":"星际大战","3":"Galactic Cash","4":"Galactic Cash","5":"Galactic Cash"}',
                'game_code' => 'TA0V',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA0V',
                'english_name' => 'Galactic Cash',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Jolly Roger","2":"海盗夺宝","3":"Jolly Roger","4":"Jolly Roger","5":"Jolly Roger"}',
                'game_code' => 'TA0W',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA0W',
                'english_name' => 'Jolly Roger',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Cafe de Paris","2":"巴黎茶座","3":"Cafe de Paris","4":"Cafe de Paris","5":"Cafe de Paris"}',
                'game_code' => 'TA0X',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA0X',
                'english_name' => 'Cafe de Paris',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Golden Dragon","2":"金龙献宝","3":"Golden Dragon","4":"Golden Dragon","5":"Golden Dragon"}',
                'game_code' => 'TA0Y',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA0Y',
                'english_name' => 'Golden Dragon',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Dragon Boat Festival","2":"龙舟竞渡","3":"Dragon Boat Festival","4":"Dragon Boat Festival","5":"Dragon Boat Festival"}',
                'game_code' => 'XG10',
                'game_platform_id' => $api_id,
                'external_game_id' => 'XG10',
                'english_name' => 'Dragon Boat Festival',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Moon Festival","2":"中秋佳节","3":"Moon Festival","4":"Moon Festival","5":"Moon Festival"}',
                'game_code' => 'XG11',
                'game_platform_id' => $api_id,
                'external_game_id' => 'XG11',
                'english_name' => 'Moon Festival',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"K-Pop","2":"韩风劲舞","3":"K-Pop","4":"K-Pop","5":"K-Pop"}',
                'game_code' => 'XG12',
                'game_platform_id' => $api_id,
                'external_game_id' => 'XG12',
                'english_name' => 'K-Pop',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Fantasies","2":"美女大格斗","3":"Fantasies","4":"Fantasies","5":"Fantasies"}',
                'game_code' => 'XG13',
                'game_platform_id' => $api_id,
                'external_game_id' => 'XG13',
                'english_name' => 'Fantasies',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Phoenix and Dragon","2":"龙凤呈祥","3":"Phoenix and Dragon","4":"Phoenix and Dragon","5":"Phoenix and Dragon"}',
                'game_code' => 'XG14',
                'game_platform_id' => $api_id,
                'external_game_id' => 'XG14',
                'english_name' => 'Phoenix and Dragon',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Kick Off","2":"黄金对垒","3":"Kick Off","4":"Kick Off","5":"Kick Off"}',
                'game_code' => 'XG16',
                'game_platform_id' => $api_id,
                'external_game_id' => 'XG16',
                'english_name' => 'Kick Off',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_true,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"GourMonsters","2":"怪兽食坊","3":"GourMonsters","4":"GourMonsters","5":"GourMonsters"}',
                'game_code' => 'TA0P',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA0P',
                'english_name' => 'GourMonsters',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Soccer Challenge","2":"足球竞赛","3":"Soccer Challenge","4":"Soccer Challenge","5":"Soccer Challenge"}',
                'game_code' => 'TA0S',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA0S',
                'english_name' => 'Soccer Challenge',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"The Mob","2":"无法无天","3":"The Mob","4":"The Mob","5":"The Mob"}',
                'game_code' => 'TA0L',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA0L',
                'english_name' => 'The Mob',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Pharaoh\'s Secret","2":"法老秘密","3":"Pharaoh\'s Secret","4":"Pharaoh\'s Secret","5":"Pharaoh\'s Secret"}',
                'game_code' => 'TA0M',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA0M',
                'english_name' => 'Pharaoh\'s Secret',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Full Throttle","2":"烈火战车","3":"Full Throttle","4":"Full Throttle","5":"Full Throttle"}',
                'game_code' => 'TA0N',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA0N',
                'english_name' => 'Full Throttle',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Hunting Season","2":"捕猎季节","3":"Hunting Season","4":"Hunting Season","5":"Hunting Season"}',
                'game_code' => 'TA0O',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA0O',
                'english_name' => 'Hunting Season',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Day and Night","2":"日与夜","3":"Day and Night","4":"Day and Night","5":"Day and Night"}',
                'game_code' => 'TA0Q',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA0Q',
                'english_name' => 'Day and Night',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Seven Wonders","2":"七大奇迹","3":"Seven Wonders","4":"Seven Wonders","5":"Seven Wonders"}',
                'game_code' => 'TA0R',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA0R',
                'english_name' => 'Seven Wonders',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Diamonds And Pearls","2":"珠光宝气","3":"Diamonds And Pearls","4":"Diamonds And Pearls","5":"Diamonds And Pearls"}',
                'game_code' => 'TA0T',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA0T',
                'english_name' => 'Diamonds And Pearls',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Roulette Deluxe High Limits (mobile)","2":"歐洲輪盤 高額投注（移動版）","3":"Roulette Deluxe High Limits (mobile)","4":"Roulette Deluxe High Limits (mobile)","5":"Roulette Deluxe High Limits (mobile)"}',
                'game_code' => 'TAITA1N',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TAITA1N',
                'english_name' => 'Roulette Deluxe High Limits (mobile)',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Roulette Deluxe (mobile)","2":"歐洲輪盤（移動版）","3":"Roulette Deluxe (mobile)","4":"Roulette Deluxe (mobile)","5":"Roulette Deluxe (mobile)"}',
                'game_code' => 'TAITA10',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TAITA10',
                'english_name' => 'Roulette Deluxe (mobile)',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Roulette Deluxe Low Limits (mobile)","2":"歐洲輪盤（移動版）","3":"Roulette Deluxe Low Limits (mobile)","4":"Roulette Deluxe Low Limits (mobile)","5":"Roulette Deluxe Low Limits (mobile)"}',
                'game_code' => 'TAITA1P',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TAITA1P',
                'english_name' => 'Roulette Deluxe Low Limits (mobile)',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Roulette Deluxe High Limits (desktop)","2":"歐洲輪盤 高額投注（桌面版）","3":"Roulette Deluxe High Limits (desktop)","4":"Roulette Deluxe High Limits (desktop)","5":"Roulette Deluxe High Limits (desktop)"}',
                'game_code' => 'TAITA1K',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TAITA1K',
                'english_name' => 'Roulette Deluxe High Limits (desktop)',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Roulette Deluxe (desktop)","2":"歐洲輪盤（桌面版）","3":"Roulette Deluxe (desktop)","4":"Roulette Deluxe (desktop)","5":"Roulette Deluxe (desktop)"}',
                'game_code' => 'TAITA1L',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TAITA1L',
                'english_name' => 'Roulette Deluxe (desktop)',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Roulette Deluxe Low Limits (desktop)","2":"歐洲輪盤 低額投注（桌面版）","3":"Roulette Deluxe Low Limits (desktop)","4":"Roulette Deluxe Low Limits (desktop)","5":"Roulette Deluxe Low Limits (desktop)"}',
                'game_code' => 'TAITA1M',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TAITA1M',
                'english_name' => 'Roulette Deluxe Low Limits (desktop)',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            // ================================== slots ==================================

            // ================================== live ==================================
            [
                'game_name' => '_json:{"1":"Baccarat","2":"百家乐","3":"Baccarat","4":"Baccarat","5":"Baccarat"}',
                'game_code' => 'BAC',
                'game_platform_id' => $api_id,
                'external_game_id' => 'BAC',
                'english_name' => 'Baccarat',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_agin],
            ],
            [
                'game_name' => '_json:{"1":"VIP Baccarat","2":"包桌百家乐","3":"VIP Baccarat","4":"VIP Baccarat","5":"VIP Baccarat"}',
                'game_code' => 'CBAC',
                'game_platform_id' => $api_id,
                'external_game_id' => 'CBAC',
                'english_name' => 'VIP Baccarat',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_agin],
            ],
            [
                'game_name' => '_json:{"1":"Multiple platform","2":"多台","3":"Multiple platform","4":"Multiple platform","5":"Multiple platform"}',
                'game_code' => 'LINK',
                'game_platform_id' => $api_id,
                'external_game_id' => 'LINK',
                'english_name' => 'Multiple platform',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_agin],
            ],
            [
                'game_name' => '_json:{"1":"Dragon Tiger","2":"龙虎","3":"Dragon Tiger","4":"Dragon Tiger","5":"Dragon Tiger"}',
                'game_code' => 'DT',
                'game_platform_id' => $api_id,
                'external_game_id' => 'DT',
                'english_name' => 'Dragon Tiger',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_agin],
            ],
            [
                'game_name' => '_json:{"1":"Sicbo","2":"骰宝","3":"Sicbo","4":"Sicbo","5":"Sicbo"}',
                'game_code' => 'SHB',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SHB',
                'english_name' => 'Sicbo',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_agin],
            ],
            [
                'game_name' => '_json:{"1":"Roulette","2":"轮盘","3":"Roulette","4":"Roulette","5":"Roulette"}',
                'game_code' => 'ROU',
                'game_platform_id' => $api_id,
                'external_game_id' => 'ROU',
                'english_name' => 'Roulette',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_agin],
            ],
            [
                'game_name' => '_json:{"1":"Fan Tan","2":"番摊","3":"Fan Tan","4":"Fan Tan","5":"Fan Tan"}',
                'game_code' => 'FT',
                'game_platform_id' => $api_id,
                'external_game_id' => 'FT',
                'english_name' => 'Fan Tan',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_agin],
            ],
            [
                'game_name' => '_json:{"1":"Bid Baccarat","2":"竞咪百家乐","3":"Bid Baccarat","4":"Bid Baccarat","5":"Bid Baccarat"}',
                'game_code' => 'LBAC',
                'game_platform_id' => $api_id,
                'external_game_id' => 'LBAC',
                'english_name' => 'Bid Baccarat',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_agin],
            ],
            [
                'game_name' => '_json:{"1":"Ultimate Holdem","2":"终极德州扑克","3":"Ultimate Holdem","4":"Ultimate Holdem","5":"Ultimate Holdem"}',
                'game_code' => 'ULPK',
                'game_platform_id' => $api_id,
                'external_game_id' => 'ULPK',
                'english_name' => 'Ultimate Holdem',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_agin],
            ],
            [
                'game_name' => '_json:{"1":"Insurance Bacarrat","2":"保險百家樂","3":"Insurance Bacarrat","4":"Insurance Bacarrat","5":"Insurance Bacarrat"}',
                'game_code' => 'SBAC',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SBAC',
                'english_name' => 'Insurance Bacarrat',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_agin],
            ],
            [
                'game_name' => '_json:{"1":"Bull Bull ","2":"牛牛","3":"Bull Bull ","4":"Bull Bull ","5":"Bull Bull "}',
                'game_code' => 'NN',
                'game_platform_id' => $api_id,
                'external_game_id' => 'NN',
                'english_name' => 'Bull Bull ',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_agin],
            ],
            [
                'game_name' => '_json:{"1":"Blackjack","2":"21 點","3":"Blackjack","4":"Blackjack","5":"Blackjack"}',
                'game_code' => 'BJ',
                'game_platform_id' => $api_id,
                'external_game_id' => 'BJ',
                'english_name' => 'Blackjack',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_agin],
            ],
            // ================================== live ==================================

            // ================================== lottery ==================================
            [
                'game_name' => '_json:{"1":"JSKS","2":"江苏快三","3":"JSKS","4":"JSKS","5":"JSKS"}',
                'game_code' => '27',
                'game_platform_id' => $api_id,
                'external_game_id' => '27',
                'english_name' => 'JSKS',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_agin],
            ],
            [
                'game_name' => '_json:{"1":"CQEverycolor","2":"重庆时时彩","3":"CQEverycolor","4":"CQEverycolor","5":"CQEverycolor"}',
                'game_code' => '24',
                'game_platform_id' => $api_id,
                'external_game_id' => '24',
                'english_name' => 'CQEverycolor',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_agin],
            ],
            [
                'game_name' => '_json:{"1":"Lottory 3D","2":"中国福彩 3D","3":"Lottory 3D","4":"Lottory 3D","5":"Lottory 3D"}',
                'game_code' => '13',
                'game_platform_id' => $api_id,
                'external_game_id' => '13',
                'english_name' => 'Lottory 3D',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_agin],
            ],
            [
                'game_name' => '_json:{"1":"happy 8","2":"北京快乐 8","3":"happy 8","4":"happy 8","5":"happy 8"}',
                'game_code' => '25',
                'game_platform_id' => $api_id,
                'external_game_id' => '25',
                'english_name' => 'happy 8',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_agin],
            ],
            [
                'game_name' => '_json:{"1":"HunanKLSF","2":"湖南快乐十分","3":"HunanKLSF","4":"HunanKLSF","5":"HunanKLSF"}',
                'game_code' => '26',
                'game_platform_id' => $api_id,
                'external_game_id' => '26',
                'english_name' => 'HunanKLSF',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_agin],
            ],
            [
                'game_name' => '_json:{"1":"11sddj","2":"十一运夺金","3":"11sddj","4":"11sddj","5":"11sddj"}',
                'game_code' => '29',
                'game_platform_id' => $api_id,
                'external_game_id' => '29',
                'english_name' => '11sddj',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_agin],
            ],
            [
                'game_name' => '_json:{"1":"JXEverycolor","2":"江西时时彩","3":"JXEverycolor","4":"JXEverycolor","5":"JXEverycolor"}',
                'game_code' => '23',
                'game_platform_id' => $api_id,
                'external_game_id' => '23',
                'english_name' => 'JXEverycolor',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_agin],
            ],
            // ================================== lottery ==================================

            // ================================== agtext ==================================
            [
                'game_name' => '_json:{"1":"Texas Hold\'em","2":"德州","3":"Texas Hold\'em","4":"Texas Hold\'em","5":"Texas Hold\'em"}',
                'game_code' => 'DZPK',
                'game_platform_id' => $api_id,
                'external_game_id' => 'DZPK',
                'english_name' => 'Texas Hold\'em',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_agtex],
            ],
            [
                'game_name' => '_json:{"1":"Guangdong mahjong","2":"广东麻将","3":"Guangdong mahjong","4":"Guangdong mahjong","5":"Guangdong mahjong"}',
                'game_code' => 'GDMJ',
                'game_platform_id' => $api_id,
                'external_game_id' => 'GDMJ',
                'english_name' => 'Guangdong mahjong',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_agtex],
            ],
            // ================================== agtext ==================================

            // ================================== sports ==================================
            [
                'game_name' => '_json:{"1":"Sport","2":"体育","3":"Sport","4":"Sport","5":"Sport"}',
                'game_code' => 'FIFA',
                'game_platform_id' => $api_id,
                'external_game_id' => 'FIFA',
                'english_name' => 'Sport',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_agtex],
            ],

            [
                'game_name' => '_json:{"1":"AG Sport","2":"AG 体育","3":"AG Sport","4":"AG Sport","5":"AG Sport"}',
                'game_code' => 'SPTA',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SPTA',
                'english_name' => 'AG Sport',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_agtex],
            ],


            // ================================== fishing game ==================================

            [
                'game_name' => '_json:{"1":"Hunter","2":"捕鱼","3":"Hunter","4":"Hunter","5":"Hunter"}',
                'game_code' => 'hunter',
                'game_platform_id' => $api_id,
                'external_game_id' => 'hunter',
                'english_name' => 'Hunter',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_hunter],
            ],

            # ================ new games as of september 2017 =========================
            [
                'game_name' => '_json:{"1":"Saiyan Battle Z","2":"Saiyan Battle Z","3":"Saiyan Battle Z","4":"Saiyan Battle Z","5":"Saiyan Battle Z"}',
                'game_code' => '220',
                'game_platform_id' => $api_id,
                'external_game_id' => '220',
                'english_name' => 'Saiyan Battle Z',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_hunter],
            ],
            // ================================== unknown game ==================================


            /**
             * ADDED BASE ON EBET AG DOCS
             */
            [
                'game_name' => '_json:{"1":"Roulette Deluxe High Limits (mobile)","2":"歐洲輪盤 高額投注（移動版）","3":"Roulette Deluxe High Limits (mobile)","4":"Roulette Deluxe High Limits (mobile)","5":"Roulette Deluxe High Limits (mobile)"}',
                'game_code' => 'TA1N',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA1N',
                'english_name' => 'Roulette Deluxe High Limits (mobile)',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],

            [
                'game_name' => '_json:{"1":"5H Joker Wild","2":"5 手百搭小丑","3":"5H Joker Wild","4":"5H Joker Wild","5":"5H Joker Wild"}',
                'game_code' => 'TA1O',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA1O',
                'english_name' => '5H Joker Wild',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Roulette Deluxe Low Limits (mobile)","2":"歐洲輪盤（移動版）","3":"Roulette Deluxe Low Limits (mobile)","4":"Roulette Deluxe Low Limits (mobile)","5":"Roulette Deluxe Low Limits (mobile)"}',
                'game_code' => 'TA1P',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA1P',
                'english_name' => 'Roulette Deluxe Low Limits (mobile)',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Roulette Deluxe High Limits (desktop)","2":"歐洲輪盤 高額投注（桌面版）","3":"Roulette Deluxe High Limits (desktop)","4":"Roulette Deluxe High Limits (desktop)","5":"Roulette Deluxe High Limits (desktop)"}',
                'game_code' => 'TA1K',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA1K',
                'english_name' => 'Roulette Deluxe High Limits (desktop)',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"Roulette Deluxe (desktop)","2":"歐洲輪盤（桌面版）","3":"Roulette Deluxe (desktop)","4":"Roulette Deluxe (desktop)","5":"Roulette Deluxe (desktop)"}',
                'game_code' => 'TA1L',
                'game_platform_id' => $api_id,
                'external_game_id' => 'TA1L',
                'english_name' => 'Roulette Deluxe (desktop)',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],

            [
                'game_name' => '_json:{"1":"富贵金鸡","2":"富贵金鸡","3":"富贵金鸡","4":"富贵金鸡","5":"富贵金鸡"}',
                'game_code' => 'SV41',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SV41',
                'english_name' => '富贵金鸡',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],

            [
                'game_name' => '_json:{"1":"赛亚烈战","2":"赛亚烈战","3":"赛亚烈战","4":"赛亚烈战","5":"赛亚烈战"}',
                'game_code' => 'SX01',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SX01',
                'english_name' => '赛亚烈战',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],
            [
                'game_name' => '_json:{"1":"街头烈战","2":"街头烈战","3":"街头烈战","4":"街头烈战","5":"街头烈战"}',
                'game_code' => 'SX02',
                'game_platform_id' => $api_id,
                'external_game_id' => 'SX02',
                'english_name' => '街头烈战',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_xin],
            ],

            # Added YoPlay games 20180108
            [
                'game_name' => '_json:{"1":"水果派对","2":"水果派对","3":"水果派对","4":"水果派对","5":"水果派对"}',
                'game_code' => 'YFP',
                'game_platform_id' => $api_id,
                'external_game_id' => 'YFP',
                'english_name' => '水果派对',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_yoplay],
            ],
            [
                'game_name' => '_json:{"1":"德州牛仔","2":"德州牛仔","3":"德州牛仔","4":"德州牛仔","5":"德州牛仔"}',
                'game_code' => 'YDZ',
                'game_platform_id' => $api_id,
                'external_game_id' => 'YDZ',
                'english_name' => '德州牛仔',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_yoplay],
            ],
            [
                'game_name' => '_json:{"1":"飞禽走兽","2":"飞禽走兽","3":"飞禽走兽","4":"飞禽走兽","5":"飞禽走兽"}',
                'game_code' => 'YBIR',
                'game_platform_id' => $api_id,
                'external_game_id' => 'YBIR',
                'english_name' => '飞禽走兽',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_yoplay],
            ],
            [
                'game_name' => '_json:{"1":"森林舞会多人版","2":"森林舞会多人版","3":"森林舞会多人版","4":"森林舞会多人版","5":"森林舞会多人版"}',
                'game_code' => 'YMFD',
                'game_platform_id' => $api_id,
                'external_game_id' => 'YMFD',
                'english_name' => '森林舞会多人版',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_yoplay],
            ],
            [
                'game_name' => '_json:{"1":"森林舞会","2":"森林舞会","3":"森林舞会","4":"森林舞会","5":"森林舞会"}',
                'game_code' => 'YFD',
                'game_platform_id' => $api_id,
                'external_game_id' => 'YFD',
                'english_name' => '森林舞会',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_yoplay],
            ],
            [
                'game_name' => '_json:{"1":"奔驰宝马","2":"奔驰宝马","3":"奔驰宝马","4":"奔驰宝马","5":"奔驰宝马"}',
                'game_code' => 'YBEN',
                'game_platform_id' => $api_id,
                'external_game_id' => 'YBEN',
                'english_name' => '奔驰宝马',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_yoplay],
            ],
            [
                'game_name' => '_json:{"1":"极速赛马","2":"极速赛马","3":"极速赛马","4":"极速赛马","5":"极速赛马"}',
                'game_code' => 'YHR',
                'game_platform_id' => $api_id,
                'external_game_id' => 'YHR',
                'english_name' => '极速赛马',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_yoplay],
            ],
            [
                'game_name' => '_json:{"1":"水果拉霸多人版","2":"水果拉霸多人版","3":"水果拉霸多人版","4":"水果拉霸多人版","5":"水果拉霸多人版"}',
                'game_code' => 'YMFR',
                'game_platform_id' => $api_id,
                'external_game_id' => 'YMFR',
                'english_name' => '水果拉霸多人版',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_yoplay],
            ],
            [
                'game_name' => '_json:{"1":"猜猜乐","2":"猜猜乐","3":"猜猜乐","4":"猜猜乐","5":"猜猜乐"}',
                'game_code' => 'YGS',
                'game_platform_id' => $api_id,
                'external_game_id' => 'YGS',
                'english_name' => '猜猜乐',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_yoplay],
            ],
            [
                'game_name' => '_json:{"1":"水果拉霸","2":"水果拉霸","3":"水果拉霸","4":"水果拉霸","5":"水果拉霸"}',
                'game_code' => 'YFR',
                'game_platform_id' => $api_id,
                'external_game_id' => 'YFR',
                'english_name' => '水果拉霸',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_yoplay],
            ],
            [
                'game_name' => '_json:{"1":"猜猜乐多人版","2":"猜猜乐多人版","3":"猜猜乐多人版","4":"猜猜乐多人版","5":"猜猜乐多人版"}',
                'game_code' => 'YMGS',
                'game_platform_id' => $api_id,
                'external_game_id' => 'YMGS',
                'english_name' => '猜猜乐多人版',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_yoplay],
            ],
            [
                'game_name' => '_json:{"1":"百人牛牛","2":"百人牛牛","3":"百人牛牛","4":"百人牛牛","5":"百人牛牛"}',
                'game_code' => 'YMBN',
                'game_platform_id' => $api_id,
                'external_game_id' => 'YMBN',
                'english_name' => '百人牛牛',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_yoplay],
            ],
            [
                'game_name' => '_json:{"1":"多宝水果拉霸","2":"多宝水果拉霸","3":"多宝水果拉霸","4":"多宝水果拉霸","5":"多宝水果拉霸"}',
                'game_code' => 'YGFS',
                'game_platform_id' => $api_id,
                'external_game_id' => 'YGFS',
                'english_name' => '多宝水果拉霸',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_yoplay],
            ],
            [
                'game_name' => '_json:{"1":"彩金水果拉霸","2":"彩金水果拉霸","3":"彩金水果拉霸","4":"彩金水果拉霸","5":"彩金水果拉霸"}',
                'game_code' => 'YJFS',
                'game_platform_id' => $api_id,
                'external_game_id' => 'YJFS',
                'english_name' => '彩金水果拉霸',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_yoplay],
            ],
            [
                'game_name' => '_json:{"1":"飞禽走兽多人版","2":"飞禽走兽多人版","3":"飞禽走兽多人版","4":"飞禽走兽多人版","5":"飞禽走兽多人版"}',
                'game_code' => 'YMBI',
                'game_platform_id' => $api_id,
                'external_game_id' => 'YMBI',
                'english_name' => '飞禽走兽多人版',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_yoplay],
            ],
            [
                'game_name' => '_json:{"1":"牛牛对战","2":"牛牛对战","3":"牛牛对战","4":"牛牛对战","5":"牛牛对战"}',
                'game_code' => 'YMBA',
                'game_platform_id' => $api_id,
                'external_game_id' => 'YMBA',
                'english_name' => '牛牛对战',
                'flash_enabled' => $db_false,
                'html_five_enabled' => $db_false,
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_yoplay],
            ],

            [
                'game_platform_id' => $api_id,
                'game_code' => 'unknown',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_unknown],
                'game_name' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                "english_name" => "Unknown",
                'external_game_id' => 'unknown',
                'status'=> $db_true,
                'flag_show_in_site'=>$db_false,
                'updated_at'=>$now,
            ],

        );

        $this->load->model(['game_description_model']);

        $success=$this->game_description_model->syncGameDescription($game_descriptions);

        return $success;
    }

}
