<?php
trait game_description_agshaba {

    public function sync_game_description_agshaba(){
        $api_id= AGSHABA_API;
        $db_true=1;
        $db_false=0;
        $now=$this->utils->getNowForMysql();

        $game_type_code_sports  = SYNC::TAG_CODE_SPORTS;
        $game_type_code_unknown = SYNC::TAG_CODE_UNKNOWN_GAME;


        //sync game type first
        //use game_type_code as key
        $game_types = [
            $game_type_code_sports => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Sports","2":"体育","3":"Sports","4":"Sports","5":"Sports"}',
                'game_type_code' => $game_type_code_sports,
                'game_tag_code' => $game_type_code_sports,
            ],
            $game_type_code_unknown => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                'game_type_code' => $game_type_code_unknown,
                'game_tag_code' => $game_type_code_unknown,
            ]
        ];

        echo "<pre>";
        $this->load->model(['game_type_model']);
        $gameTypeCodeMaps=$this->game_type_model->syncGameTypes($game_types);

        $this->utils->debug_log('gameTypeCodeMaps', $gameTypeCodeMaps);

        $game_descriptions=[
            [
                'game_name' => '_json:{"1":"Soccer","2":"英式足球","3":"Soccer","4":"Soccer","5":"Soccer"}',
                'game_code' => 1,
                'external_game_id' => 1,
                'english_name' => "Soccer",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Basketball","2":"篮球","3":"Basketball","4":"Basketball","5":"Basketball"}',
                'game_code' => 2,
                'external_game_id' => 2,
                'english_name' => "Basketball",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Football","2":"橄榄球","3":"Football","4":"Football","5":"Football"}',
                'game_code' => 3,
                'external_game_id' => 3,
                'english_name' => "Football",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Ice Hockey","2":"冰上曲棍球","3":"Ice Hockey","4":"Ice Hockey","5":"Ice Hockey"}',
                'game_code' => 4,
                'external_game_id' => 4,
                'english_name' => "Ice Hockey",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Tennis","2":"网球","3":"Tennis","4":"Tennis","5":"Tennis"}',
                'game_code' => 5,
                'external_game_id' => 5,
                'english_name' => "Tennis",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Volleyball","2":"排球","3":"Volleyball","4":"Volleyball","5":"Volleyball"}',
                'game_code' => 6,
                'external_game_id' => 6,
                'english_name' => "Volleyball",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Billiards","2":"台球","3":"Billiards","4":"Billiards","5":"Billiards"}',
                'game_code' => 7,
                'external_game_id' => 7,
                'english_name' => "Billiards",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Baseball","2":"棒球","3":"Baseball","4":"Baseball","5":"Baseball"}',
                'game_code' => 8,
                'external_game_id' => 8,
                'english_name' => "Baseball",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Badminton","2":"羽毛球","3":"Badminton","4":"Badminton","5":"Badminton"}',
                'game_code' => 9,
                'external_game_id' => 9,
                'english_name' => "Badminton",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Golf","2":"高尔夫","3":"Golf","4":"Golf","5":"Golf"}',
                'game_code' => 10,
                'external_game_id' => 10,
                'english_name' => "Golf",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Motorsports","2":"赛车","3":"Motorsports","4":"Motorsports","5":"Motorsports"}',
                'game_code' => 11,
                'external_game_id' => 11,
                'english_name' => "Motorsports",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Swimming","2":"游泳","3":"Swimming","4":"Swimming","5":"Swimming"}',
                'game_code' => 12,
                'external_game_id' => 12,
                'english_name' => "Swimming",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Politics","2":"政治","3":"Politics","4":"Politics","5":"Politics"}',
                'game_code' => 13,
                'external_game_id' => 13,
                'english_name' => "Politics",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Water Polo","2":"水球","3":"Water Polo","4":"Water Polo","5":"Water Polo"}',
                'game_code' => 14,
                'external_game_id' => 14,
                'english_name' => "Water Polo",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Diving","2":"潜水","3":"Diving","4":"Diving","5":"Diving"}',
                'game_code' => 15,
                'external_game_id' => 15,
                'english_name' => "Diving",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Boxing","2":"射箭","3":"Boxing","4":"Boxing","5":"Boxing"}',
                'game_code' => 16,
                'external_game_id' => 16,
                'english_name' => "Boxing",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Archery","2":"射箭","3":"Archery","4":"Archery","5":"Archery"}',
                'game_code' => 17,
                'external_game_id' => 17,
                'english_name' => "Archery",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Table Tennis","2":"乒乓球","3":"Table Tennis","4":"Table Tennis","5":"Table Tennis"}',
                'game_code' => 18,
                'external_game_id' => 18,
                'english_name' => "Table Tennis",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Weightlifting","2":".举重","3":"Weightlifting","4":"Weightlifting","5":"Weightlifting"}',
                'game_code' => 19,
                'external_game_id' => 19,
                'english_name' => "Weightlifting",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Canoeing","2":"划独木舟","3":"Canoeing","4":"Canoeing","5":"Canoeing"}',
                'game_code' => 20,
                'external_game_id' => 20,
                'english_name' => "Canoeing",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Gymnastics","2":"体操","3":"Gymnastics","4":"Gymnastics","5":"Gymnastics"}',
                'game_code' => 21,
                'external_game_id' => 21,
                'english_name' => "Gymnastics",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Athletics","2":"田径","3":"Athletics","4":"Athletics","5":"Athletics"}',
                'game_code' => 22,
                'external_game_id' => 22,
                'english_name' => "Athletics",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Equestrian","2":"马术","3":"Equestrian","4":"Equestrian","5":"Equestrian"}',
                'game_code' => 23,
                'external_game_id' => 23,
                'english_name' => "Equestrian",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Handball","2":"手球","3":"Handball","4":"Handball","5":"Handball"}',
                'game_code' => 24,
                'external_game_id' => 24,
                'english_name' => "Handball",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Darts","2":"飞镖","3":"Darts","4":"Darts","5":"Darts"}',
                'game_code' => 25,
                'external_game_id' => 25,
                'english_name' => "Darts",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Rugby","2":"橄榄球","3":"Rugby","4":"Rugby","5":"Rugby"}',
                'game_code' => 26,
                'external_game_id' => 26,
                'english_name' => "Rugby",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Cricket","2":"板球","3":"Cricket","4":"Cricket","5":"Cricket"}',
                'game_code' => 27,
                'external_game_id' => 27,
                'english_name' => "Cricket",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Field Hockey","2":"曲棍球","3":"Field Hockey","4":"Field Hockey","5":"Field Hockey"}',
                'game_code' => 28,
                'external_game_id' => 28,
                'english_name' => "Field Hockey",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Winter Sport","2":"冬季运动","3":"Winter Sport","4":"Winter Sport","5":"Winter Sport"}',
                'game_code' => 29,
                'external_game_id' => 29,
                'english_name' => "Winter Sport",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Squash","2":"壁球","3":"Squash","4":"Squash","5":"Squash"}',
                'game_code' => 30,
                'external_game_id' => 30,
                'english_name' => "Squash",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Entertainment","2":"游艺","3":"Entertainment","4":"Entertainment","5":"Entertainment"}',
                'game_code' => 31,
                'external_game_id' => 31,
                'english_name' => "Entertainment",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Net Ball","2":"净球","3":"Net Ball","4":"Net Ball","5":"Net Ball"}',
                'game_code' => 32,
                'external_game_id' => 32,
                'english_name' => "Net Ball",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Cycling","2":"脚踏车","3":"Cycling","4":"Cycling","5":"Cycling"}',
                'game_code' => 33,
                'external_game_id' => 33,
                'english_name' => "Cycling",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Fencing","2":".剑术","3":"Fencing","4":"Fencing","5":"Fencing"}',
                'game_code' => 34,
                'external_game_id' => 34,
                'english_name' => "Fencing",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Judo","2":"柔道","3":"Judo","4":"Judo","5":"Judo"}',
                'game_code' => 35,
                'external_game_id' => 35,
                'english_name' => "Judo",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"M. Pentathlon","2":"五项锦标赛","3":"M. Pentathlon","4":"M. Pentathlon","5":"M. Pentathlon"}',
                'game_code' => 36,
                'external_game_id' => 36,
                'english_name' => "M. Pentathlon",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Rowing","2":"划艇","3":"Rowing","4":"Rowing","5":"Rowing"}',
                'game_code' => 37,
                'external_game_id' => 37,
                'english_name' => "Rowing",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Sailing","2":"航行","3":"Sailing","4":"Sailing","5":"Sailing"}',
                'game_code' => 38,
                'external_game_id' => 38,
                'english_name' => "Sailing",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Shooting","2":"射击","3":"Shooting","4":"Shooting","5":"Shooting"}',
                'game_code' => 39,
                'external_game_id' => 39,
                'english_name' => "Shooting",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Taekwondo","2":"跆拳道","3":"Taekwondo","4":"Taekwondo","5":"Taekwondo"}',
                'game_code' => 40,
                'external_game_id' => 40,
                'english_name' => "Taekwondo",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Triathlon","2":"铁人三项","3":"Triathlon","4":"Triathlon","5":"Triathlon"}',
                'game_code' => 41,
                'external_game_id' => 41,
                'english_name' => "Triathlon",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Wrestling","2":"摔跤","3":"Wrestling","4":"Wrestling","5":"Wrestling"}',
                'game_code' => 42,
                'external_game_id' => 42,
                'english_name' => "Wrestling",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"E Sports","2":"电子竞技","3":"E Sports","4":"E Sports","5":"E Sports"}',
                'game_code' => 43,
                'external_game_id' => 43,
                'english_name' => "E Sports",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Other Sports","2":"其他体育","3":"Other Sports","4":"Other Sports","5":"Other Sports"}',
                'game_code' => 99,
                'external_game_id' => 99,
                'english_name' => "Other Sports",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Horse Racing","2":"赛马","3":"Horse Racing","4":"Horse Racing","5":"Horse Racing"}',
                'game_code' => 151,
                'external_game_id' => 151,
                'english_name' => "Horse Racing",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Greyhounds","2":"灰猎犬","3":"Greyhounds","4":"Greyhounds","5":"Greyhounds"}',
                'game_code' => 152,
                'external_game_id' => 152,
                'english_name' => "Greyhounds",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Harness","2":"马具","3":"Harness","4":"Harness","5":"Harness"}',
                'game_code' => 153,
                'external_game_id' => 153,
                'english_name' => "Harness",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"HorseRacing FixedOdds","2":"赛马固定赔率","3":"HorseRacing FixedOdds","4":"HorseRacing FixedOdds","5":"HorseRacing FixedOdds"}',
                'game_code' => 154,
                'external_game_id' => 154,
                'english_name' => "HorseRacing FixedOdds",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Number Game","2":"数字游戏","3":"Number Game","4":"Number Game","5":"Number Game"}',
                'game_code' => 161,
                'external_game_id' => 161,
                'english_name' => "Number Game",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Live Casino","2":"真人娱乐","3":"Live Casino","4":"Live Casino","5":"Live Casino"}',
                'game_code' => 162,
                'external_game_id' => 162,
                'english_name' => "Live Casino",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Virtual Soccer","2":"虚拟足球","3":"Virtual Soccer","4":"Virtual Soccer","5":"Virtual Soccer"}',
                'game_code' => 180,
                'external_game_id' => 180,
                'english_name' => "Virtual Soccer",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Virtual Horse Racing","2":"虚拟赛马","3":"Virtual Horse Racing","4":"Virtual Horse Racing","5":"Virtual Horse Racing"}',
                'game_code' => 181,
                'external_game_id' => 181,
                'english_name' => "Virtual Horse Racing",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Virtual Greyhound","2":"虚拟灵狮","3":"Virtual Greyhound","4":"Virtual Greyhound","5":"Virtual Greyhound"}',
                'game_code' => 182,
                'external_game_id' => 182,
                'english_name' => "Virtual Greyhound",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Virtual Speedway","2":"虚拟高速公路","3":"Virtual Speedway","4":"Virtual Speedway","5":"Virtual Speedway"}',
                'game_code' => 183,
                'external_game_id' => 183,
                'english_name' => "Virtual Speedway",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Virtual F1","2":"虚拟F1","3":"Virtual F1","4":"Virtual F1","5":"Virtual F1"}',
                'game_code' => 184,
                'external_game_id' => 184,
                'english_name' => "Virtual F1",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Virtual Cycling","2":"虚拟循环","3":"Virtual Cycling","4":"Virtual Cycling","5":"Virtual Cycling"}',
                'game_code' => 185,
                'external_game_id' => 185,
                'english_name' => "Virtual Cycling",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Virtual Tennis","2":"虚拟网球","3":"Virtual Tennis","4":"Virtual Tennis","5":"Virtual Tennis"}',
                'game_code' => 186,
                'external_game_id' => 186,
                'english_name' => "Virtual Tennis",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Keno","2":"基诺","3":"Keno","4":"Keno","5":"Keno"}',
                'game_code' => 202,
                'external_game_id' => 202,
                'english_name' => "Keno",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Casino","2":"娱乐场","3":"Casino","4":"Casino","5":"Casino"}',
                'game_code' => 251,
                'external_game_id' => 251,
                'english_name' => "Casino",
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_platform_id' => $api_id,
                'game_code' => 'unknown',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_unknown],
                'game_name' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                "english_name" => "Unknown",
                'external_game_id' => 'unknown',
                'status'=> $db_true,
                'flag_show_in_site'=>$db_false,
                'updated_at'=>$now,
            ],
            [
                'game_name' => '_json:{"1":"FT Correct Score(Soccer)","2":"波膽(足球)"}',
                'game_code' => 413,
                'external_game_id' => 413,
                'english_name' => 'FT Correct Score(Soccer)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Correct Score(Soccer)","2":"上半場波膽(足球)"}',
                'game_code' => 414,
                'external_game_id' => 414,
                'english_name' => 'Correct Score(Soccer)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Teams To Score/Result (Soccer)","2":"兩隊皆進球/賽果(足球)"}',
                'game_code' => 417,
                'external_game_id' => 417,
                'english_name' => 'Teams To Score/Result (Soccer)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Both Teams To Score/Total Goal (Soccer)","2":"兩隊皆進球/總進球數(足球)"}',
                'game_code' => 418,
                'external_game_id' => 418,
                'english_name' => 'Both Teams To Score/Total Goal (Soccer)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Which Half First Goal (Soccer)","2":"預測進第一個球的半場(足球)"}',
                'game_code' => 419,
                'external_game_id' => 419,
                'english_name' => 'Which Half First Goal (Soccer)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Home Team Which Half First Goal (Soccer)","2":"主隊於哪個半場先進球(足球)"}',
                'game_code' => 420,
                'external_game_id' => 420,
                'english_name' => 'Home Team Which Half First Goal (Soccer)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Away Team Which Half First Goal (Soccer)","2":"客隊於哪個半場先進球(足球)"}',
                'game_code' => 421,
                'external_game_id' => 421,
                'english_name' => 'Away Team Which Half First Goal (Soccer)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Team 2 Goals (Soccer)","2":"最先進兩個球的球隊(足球)"}',
                'game_code' => 422,
                'external_game_id' => 422,
                'english_name' => 'Team 2 Goals (Soccer)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Team 3 Goals (Soccer)","2":"最先進三個球的球隊(足球)"}',
                'game_code' => 423,
                'external_game_id' => 423,
                'english_name' => 'Team 3 Goals (Soccer)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"First Goal Method (Soccer)","2":"第一個進球方式(足球)"}',
                'game_code' => 424,
                'external_game_id' => 424,
                'english_name' => 'First Goal Method (Soccer)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Win From Behind (Soccer)","2":"落後反超獲勝的球隊(足球)"}',
                'game_code' => 425,
                'external_game_id' => 425,
                'english_name' => 'Win From Behind (Soccer)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"1H Winning Margin (Soccer)","2":"上半場淨胜球數(足球)"}',
                'game_code' => 426,
                'external_game_id' => 426,
                'english_name' => '1H Winning Margin (Soccer)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"2ndHalf Goals(Soccer)","2":"準確的下半場總進球(足球)"}',
                'game_code' => 429,
                'external_game_id' => 429,
                'english_name' => '2ndHalf Goals(Soccer)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Team To Score in 1H/2H (Soccer)","2":"兩隊皆進球上半場/下半場(足球)"}',
                'game_code' => 445,
                'external_game_id' => 445,
                'english_name' => 'Team To Score in 1H/2H (Soccer)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"1H To Score/2H To Score (Soccer)","2":"主隊均進球上半場/下半場(足球)"}',
                'game_code' => 446,
                'external_game_id' => 446,
                'english_name' => '1H To Score/2H To Score (Soccer)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"1H To Score/2H To Score (Soccer)","2":"客隊均進球上半場/下半場(足球)"}',
                'game_code' => 447,
                'external_game_id' => 447,
                'english_name' => '1H To Score/2H To Score (Soccer)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Home TeamOU(Dec)","2":"主隊大小盤(Dec)"}',
                'game_code' => 461,
                'external_game_id' => 461,
                'english_name' => 'Home TeamOU(Dec)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Away Team OU(Dec)","2":"客隊大小盤(Dec)"}',
                'game_code' => 462,
                'external_game_id' => 462,
                'english_name' => 'Away Team OU(Dec)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Home Team OU(Dec)","2":"上半場主隊大小盤(Dec)"}',
                'game_code' => 463,
                'external_game_id' => 463,
                'english_name' => 'Home Team OU(Dec)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Away Team OU(Dec)","2":"上半場客隊大小盤(Dec)"}',
                'game_code' => 464,
                'external_game_id' => 464,
                'english_name' => 'Away Team OU(Dec)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Winner (Cricket)","2":"比賽獲勝者(板球)"}',
                'game_code' => 501,
                'external_game_id' => 501,
                'english_name' => 'Winner (Cricket)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"FT Winning Margin 14 Way(Basketball)","2":"淨勝分數14項(籃球)"}',
                'game_code' => 601,
                'external_game_id' => 601,
                'english_name' => 'FT Winning Margin 14 Way(Basketball)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"FT Winning Margin 12 Way(Basketball)","2":"淨勝分數12項(籃球)"}',
                'game_code' => 602,
                'external_game_id' => 602,
                'english_name' => 'FT Winning Margin 12 Way(Basketball)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"FT Which team to score the highest quarter(Basketball)","2":"賽節得分最高的球隊(籃球)"}',
                'game_code' => 603,
                'external_game_id' => 603,
                'english_name' => 'FT Which team to score the highest quarter(Basketball)"',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"FT Which team to score the first basket(Basketball)","2":"最先得分球隊(籃球)"}',
                'game_code' => 604,
                'external_game_id' => 604,
                'english_name' => '"FT Which team to score the first basket(Basketball)"',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"FT Which team to score the last basket(Basketball)","2":"最後得分球隊(籃球)"}',
                'game_code' => 605,
                'external_game_id' => 605,
                'english_name' => '"FT Which team to score the last basket(Basketball)"',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"1H Race to X(Basketball)","2":"上半場首先獲得X  分(籃球)"}',
                'game_code' => 606,
                'external_game_id' => 606,
                'english_name' => '1H Race to X(Basketball)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"2H Race to X(Basketball)","2":"下半場首先獲得X  分(籃球)"}',
                'game_code' => 607,
                'external_game_id' => 607,
                'english_name' => '2H Race to X(Basketball)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"1H Winning Margin 13 Way(Basketball)","2":"上半場淨勝分數13項(籃球)"}',
                'game_code' => 608,
                'external_game_id' => 608,
                'english_name' => '1H Winning Margin 13 Way(Basketball)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"X Handicap(Basketball)","2":"第X  節讓球盤(籃球)"}',
                'game_code' => 609,
                'external_game_id' => 609,
                'english_name' => 'X Handicap(Basketball)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"X Over Under(Basketball)","2":"第X  節大小盤(籃球)"}',
                'game_code' => 610,
                'external_game_id' => 610,
                'english_name' => 'X Over Under(Basketball)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"X Odd Even(Basketball)","2":"第X  節單雙盤(籃球)"}',
                'game_code' => 611,
                'external_game_id' => 611,
                'english_name' => 'X Odd Even(Basketball)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Quarter X Moneyline(Basketball)","2":"第X  節獨贏(籃球)"}',
                'game_code' => 612,
                'external_game_id' => 612,
                'english_name' => 'Quarter X Moneyline(Basketball)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"X Race To Y Points(Basketball)","2":"第X  節首先獲得Y  分(籃球)"}',
                'game_code' => 613,
                'external_game_id' => 613,
                'english_name' => 'X Race To Y Points(Basketball)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"X Winning Margin 7 Way(Basketball)","2":"第X  節的淨勝分數7項(籃球)"}',
                'game_code' => 614,
                'external_game_id' => 614,
                'english_name' => 'X Winning Margin 7 Way(Basketball)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Quarter X Home Team Over Under(Basketball)","2":"第X  節主隊大小盤(籃球)"}',
                'game_code' => 615,
                'external_game_id' => 615,
                'english_name' => 'Quarter X Home Team Over Under(Basketball)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Quarter X Away Team Over Under(Basketball)","2":"第X  節客隊大小盤(籃球)"}',
                'game_code' => 616,
                'external_game_id' => 616,
                'english_name' => 'Quarter X Away Team Over Under(Basketball)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],
            [
                'game_name' => '_json:{"1":"Quarter X Which team to score the last basket(Basketball)","2":"第X  節最後得分球隊(籃球)"}',
                'game_code' => 617,
                'external_game_id' => 617,
                'english_name' => 'Quarter X Which team to score the last basket(Basketball)',
                'game_type_id' => $gameTypeCodeMaps[$game_type_code_sports],
                'game_platform_id' => $api_id,
                'html_five_enabled' => $db_true,
                'flash_enabled' => $db_false,
            ],

        ];
        $this->load->model(['game_description_model']);

        // $success=$this->game_description_model->syncGameDescription($game_descriptions);

        $data = array();
        $cntInsert = 0;
        $cntUpdate = 0;
        foreach ($game_descriptions as $game_list) {

            $game_code_exist = $this->db->select('COUNT(id) as count')
                                ->where('external_game_id', $game_list['external_game_id'])
                                ->where('game_platform_id', $api_id)
                                ->get('game_description')
                                ->row();

            if( $game_code_exist->count <= 0 ){
                echo "==============================================>Insert<===========================================";
                $game_list['created_on']= $now;
                $this->db->insert('game_description', $game_list);
                $cntInsert++;
            }else{
                echo "==============================================>Update<===========================================";
                $game_list['updated_at']= $now;
                $this->db->where('external_game_id', $game_list['external_game_id']);
                $this->db->where('game_platform_id', $api_id);
                $this->db->update('game_description', $game_list);
                $cntUpdate++;
            }
            print_r($game_list);
            // $cnt++;
        }

        echo "Total Inserted Games: " . $cntInsert;
        echo "Total Updated Games: " . $cntUpdate;
    }

}
