<?php
trait game_description_ky {

    public function sync_all_ky_games(){
        $this->sync_game_description_ky_t1();
        $this->sync_game_description_ky();
    }
    
    public function sync_game_description_ky_t1(){
        $api_id = T1KYCARD_API;
        $this->ky_game_list($api_id);
    }

    public function sync_game_description_ky(){
        $api_id = KYCARD_API;
        $this->ky_game_list($api_id);
    }

    public function ky_game_list($api_id){
		$cnt=0;
        $db_true = 1;
        $db_false = 0;
        $now = $this->utils->getNowForMysql();
        $game_type_code_table_game  = SYNC::TAG_CODE_TABLE_AND_CARDS;
        $game_type_code_unknown     = SYNC::TAG_CODE_UNKNOWN_GAME;

        $game_types = [
            $game_type_code_table_game => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Table Games and Cards","2":"牌桌&牌游戏","3":"Table Games and Cards","4":"Table Games and Cards"}',
                'game_type_lang' => '_json:{"1":"Table Games and Cards","2":"牌桌&牌游戏","3":"Table Games and Cards","4":"Table Games and Cards"}',
                "game_type_code" => $game_type_code_table_game,
                'updated_at'=>$now,
                'game_tag_code' => SYNC::TAG_CODE_TABLE_AND_CARDS,
            ],
            $game_type_code_unknown => [
                'game_platform_id' => $api_id,
                'game_type' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                'game_type_lang' => '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
                "game_type_code" => $game_type_code_unknown,
                'updated_at'=>$now,
                'game_tag_code' => SYNC::TAG_CODE_UNKNOWN_GAME
            ],
        ];

        $this->load->model(['game_type_model']);
        $gameTypeCodeMaps=$this->game_type_model->syncGameTypes($game_types);
        echo "<pre>";
        $this->utils->debug_log('gameTypeCodeMaps', $gameTypeCodeMaps);

		$game_descriptions = array(
			#===================================== Desktop games list only =========================
            

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_unknown],
            'game_name'=> '_json:{"1":"Unknown","2":"不明","3":"Unknown","4":"Unknown","5":"Unknown"}',
            'game_code'=> 'unknown',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_false,
            'flag_show_in_site'=> $db_false,
            'html_five_enabled'=> $db_false,
            'english_name'=> 'Unknown',
            'external_game_id'=> 'unknown',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Texas Hold’em Poker","2":"德州扑克","3":"Texas Hold’em Poker","4":"Texas Hold’em Poker","5":"Texas Hold’em Poker"}',
            'game_code'=> '620',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Texas Hold’em Poker',
            'external_game_id'=> '620',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Two-Eight","2":"二八杠","3":"Two-Eight","4":"Two-Eight","5":"Two-Eight"}',
            'game_code'=> '720',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Two-Eight',
            'external_game_id'=> '720',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Banker Niu-Niu","2":"抢庄牛牛","3":"Banker Niu-Niu","4":"Banker Niu-Niu","5":"Banker Niu-Niu"}',
            'game_code'=> '830',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Banker Niu-Niu',
            'external_game_id'=> '830',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Golden Flower","2":"炸金花","3":"Golden Flower","4":"Golden Flower","5":"Golden Flower"}',
            'game_code'=> '220',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Golden Flower',
            'external_game_id'=> '220',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"San-Gong","2":"三公","3":"San-Gong","4":"San-Gong","5":"San-Gong"}',
            'game_code'=> '860',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'San-Gong',
            'external_game_id'=> '860',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Dragon-Tiger","2":"押庄龙虎","3":"Dragon-Tiger","4":"Dragon-Tiger","5":"Dragon-Tiger"}',
            'game_code'=> '900',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Dragon-Tiger',
            'external_game_id'=> '900',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"The 21 point[Black Jack],","2":"21 点","3":"The 21 point[Black Jack],","4":"The 21 point[Black Jack],","5":"The 21 point[Black Jack],"}',
            'game_code'=> '600',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'The 21 point[Black Jack],',
            'external_game_id'=> '600',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Casino Niu-Niu","2":"通比牛牛","3":"Casino Niu-Niu","4":"Casino Niu-Niu","5":"Casino Niu-Niu"}',
            'game_code'=> '870',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Casino Niu-Niu',
            'external_game_id'=> '870',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Happy Red Packets","2":"欢乐红包","3":"Happy Red Packets","4":"Happy Red Packets","5":"Happy Red Packets"}',
            'game_code'=> '880',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Happy Red Packets',
            'external_game_id'=> '880',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Texas Hold’em Poker Novice’s Room","2":"德州扑克新手房 ","3":"Texas Hold’em Poker Novice’s Room","4":"Texas Hold’em Poker Novice’s Room","5":"Texas Hold’em Poker Novice’s Room"}',
            'game_code'=> '620',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Texas Hold’em Poker Novice’s Room',
            'external_game_id'=> '6203600',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Texas Hold’em Poker Beginner’s Room","2":"德州扑克初级房 ","3":"Texas Hold’em Poker Beginner’s Room","4":"Texas Hold’em Poker Beginner’s Room","5":"Texas Hold’em Poker Beginner’s Room"}',
            'game_code'=> '620',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Texas Hold’em Poker Beginner’s Room',
            'external_game_id'=> '6203601',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Texas Hold’em Poker Intermediate Room","2":"德州扑克中级房 ","3":"Texas Hold’em Poker Intermediate Room","4":"Texas Hold’em Poker Intermediate Room","5":"Texas Hold’em Poker Intermediate Room"}',
            'game_code'=> '620',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Texas Hold’em Poker Intermediate Room',
            'external_game_id'=> '6203602',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Texas Hold’em Poker Advanced Room","2":"德州扑克高级房 ","3":"Texas Hold’em Poker Advanced Room","4":"Texas Hold’em Poker Advanced Room","5":"Texas Hold’em Poker Advanced Room"}',
            'game_code'=> '620',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Texas Hold’em Poker Advanced Room',
            'external_game_id'=> '6203603',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Texas Hold’em Poker cai da qi cu room","2":"德州扑克财大气粗房","3":"Texas Hold’em Poker cai da qi cu room","4":"Texas Hold’em Poker cai da qi cu room","5":"Texas Hold’em Poker cai da qi cu room"}',
            'game_code'=> '620',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Texas Hold’em Poker cai da qi cu room',
            'external_game_id'=> '6203700',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Texas  Hold’em Poker yao chan wan guan room","2":"德州扑克腰缠万贯房","3":"Texas  Hold’em Poker yao chan wan guan room","4":"Texas  Hold’em Poker yao chan wan guan room","5":"Texas  Hold’em Poker yao chan wan guan room"}',
            'game_code'=> '620',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Texas  Hold’em Poker yao chan wan guan room',
            'external_game_id'=> '6203701',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Texas Hold’em Poker hui jin ru tu room","2":"德州扑克挥金如土房","3":"Texas Hold’em Poker hui jin ru tu room","4":"Texas Hold’em Poker hui jin ru tu room","5":"Texas Hold’em Poker hui jin ru tu room"}',
            'game_code'=> '620',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Texas Hold’em Poker hui jin ru tu room',
            'external_game_id'=> '6203702',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Texas Hold’em Poker fu gui bi ren room","2":"德州扑克富贵逼人房","3":"Texas Hold’em Poker fu gui bi ren room","4":"Texas Hold’em Poker fu gui bi ren room","5":"Texas Hold’em Poker fu gui bi ren room"}',
            'game_code'=> '620',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Texas Hold’em Poker fu gui bi ren room',
            'external_game_id'=> '6203703',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Two-Eight Fresh Room","2":"二八杠体验房 ","3":"Two-Eight Fresh Room","4":"Two-Eight Fresh Room","5":"Two-Eight Fresh Room"}',
            'game_code'=> '720',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Two-Eight Fresh Room',
            'external_game_id'=> '7207201',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Two-Eight Beginner’s Room","2":"二八杠初级房","3":"Two-Eight Beginner’s Room","4":"Two-Eight Beginner’s Room","5":"Two-Eight Beginner’s Room"}',
            'game_code'=> '720',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Two-Eight Beginner’s Room',
            'external_game_id'=> '7207202',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Two-Eight Intermediate Room","2":"二八杠中级房","3":"Two-Eight Intermediate Room","4":"Two-Eight Intermediate Room","5":"Two-Eight Intermediate Room"}',
            'game_code'=> '720',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Two-Eight Intermediate Room',
            'external_game_id'=> '7207203',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Two-Eight Advanced Room","2":"二八杠高级房","3":"Two-Eight Advanced Room","4":"Two-Eight Advanced Room","5":"Two-Eight Advanced Room"}',
            'game_code'=> '720',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Two-Eight Advanced Room',
            'external_game_id'=> '7207204',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Banker Niu-NiuFresh Room","2":"抢庄牛牛体验房 ","3":"Banker Niu-NiuFresh Room","4":"Banker Niu-NiuFresh Room","5":"Banker Niu-NiuFresh Room"}',
            'game_code'=> '830',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Banker Niu-NiuFresh Room',
            'external_game_id'=> '8308301',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Banker Niu-NiuBeginner’s Room","2":"抢庄牛牛初级房 ","3":"Banker Niu-NiuBeginner’s Room","4":"Banker Niu-NiuBeginner’s Room","5":"Banker Niu-NiuBeginner’s Room"}',
            'game_code'=> '830',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Banker Niu-NiuBeginner’s Room',
            'external_game_id'=> '8308302',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Banker Niu-NiuIntermediate Room","2":"抢庄牛牛中级房 ","3":"Banker Niu-NiuIntermediate Room","4":"Banker Niu-NiuIntermediate Room","5":"Banker Niu-NiuIntermediate Room"}',
            'game_code'=> '830',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Banker Niu-NiuIntermediate Room',
            'external_game_id'=> '8308303',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Banker Niu-NiuAdvanced Room","2":"抢庄牛牛高级房 ","3":"Banker Niu-NiuAdvanced Room","4":"Banker Niu-NiuAdvanced Room","5":"Banker Niu-NiuAdvanced Room"}',
            'game_code'=> '830',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Banker Niu-NiuAdvanced Room',
            'external_game_id'=> '8308304',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Golden FlowerFresh Room","2":"炸金花体验房 ","3":"Golden FlowerFresh Room","4":"Golden FlowerFresh Room","5":"Golden FlowerFresh Room"}',
            'game_code'=> '220',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Golden FlowerFresh Room',
            'external_game_id'=> '2202201',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Golden FlowerBeginner’s Room","2":"炸金花初级房 ","3":"Golden FlowerBeginner’s Room","4":"Golden FlowerBeginner’s Room","5":"Golden FlowerBeginner’s Room"}',
            'game_code'=> '220',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Golden FlowerBeginner’s Room',
            'external_game_id'=> '2202202',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Golden FlowerIntermediate Room","2":"炸金花中级房 ","3":"Golden FlowerIntermediate Room","4":"Golden FlowerIntermediate Room","5":"Golden FlowerIntermediate Room"}',
            'game_code'=> '220',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Golden FlowerIntermediate Room',
            'external_game_id'=> '2202203',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Golden FlowerAdvanced Room","2":"炸金花高级房 ","3":"Golden FlowerAdvanced Room","4":"Golden FlowerAdvanced Room","5":"Golden FlowerAdvanced Room"}',
            'game_code'=> '220',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Golden FlowerAdvanced Room',
            'external_game_id'=> '2202204',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"San-GongFresh Room","2":"三公体验房 ","3":"San-GongFresh Room","4":"San-GongFresh Room","5":"San-GongFresh Room"}',
            'game_code'=> '860',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'San-GongFresh Room',
            'external_game_id'=> '8608601',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"San-GongBeginner’s Room","2":"三公初级房 ","3":"San-GongBeginner’s Room","4":"San-GongBeginner’s Room","5":"San-GongBeginner’s Room"}',
            'game_code'=> '860',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'San-GongBeginner’s Room',
            'external_game_id'=> '8608602',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"San-GongIntermediate Room","2":"三公中级房 ","3":"San-GongIntermediate Room","4":"San-GongIntermediate Room","5":"San-GongIntermediate Room"}',
            'game_code'=> '860',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'San-GongIntermediate Room',
            'external_game_id'=> '8608603',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"San-GongAdvanced Room","2":"三公高级房 ","3":"San-GongAdvanced Room","4":"San-GongAdvanced Room","5":"San-GongAdvanced Room"}',
            'game_code'=> '860',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'San-GongAdvanced Room',
            'external_game_id'=> '8608604',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Dragon-Tiger Fresh Room","2":"龙虎体验房 ","3":"Dragon-Tiger Fresh Room","4":"Dragon-Tiger Fresh Room","5":"Dragon-Tiger Fresh Room"}',
            'game_code'=> '900',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Dragon-Tiger Fresh Room',
            'external_game_id'=> '9009001',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Dragon-Tiger Beginner’s Room","2":"龙虎初级房 ","3":"Dragon-Tiger Beginner’s Room","4":"Dragon-Tiger Beginner’s Room","5":"Dragon-Tiger Beginner’s Room"}',
            'game_code'=> '900',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Dragon-Tiger Beginner’s Room',
            'external_game_id'=> '9009002',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Dragon-Tiger Intermediate Room","2":"龙虎中级房 ","3":"Dragon-Tiger Intermediate Room","4":"Dragon-Tiger Intermediate Room","5":"Dragon-Tiger Intermediate Room"}',
            'game_code'=> '900',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Dragon-Tiger Intermediate Room',
            'external_game_id'=> '9009003',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Dragon-Tiger Advanced Room","2":"龙虎高级房 ","3":"Dragon-Tiger Advanced Room","4":"Dragon-Tiger Advanced Room","5":"Dragon-Tiger Advanced Room"}',
            'game_code'=> '900',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Dragon-Tiger Advanced Room',
            'external_game_id'=> '9009004',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"The 21 point Fresh Room","2":"21 点体验房 ","3":"The 21 point Fresh Room","4":"The 21 point Fresh Room","5":"The 21 point Fresh Room"}',
            'game_code'=> '600',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'The 21 point Fresh Room',
            'external_game_id'=> '6006001',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"The 21 point Beginner’s Room","2":"21 点初级房 ","3":"The 21 point Beginner’s Room","4":"The 21 point Beginner’s Room","5":"The 21 point Beginner’s Room"}',
            'game_code'=> '600',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'The 21 point Beginner’s Room',
            'external_game_id'=> '6006002',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"The 21 point Intermediate Room","2":"21 点中级房 ","3":"The 21 point Intermediate Room","4":"The 21 point Intermediate Room","5":"The 21 point Intermediate Room"}',
            'game_code'=> '600',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'The 21 point Intermediate Room',
            'external_game_id'=> '6006003',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"The 21 point Advanced Room","2":"21 点高级房 ","3":"The 21 point Advanced Room","4":"The 21 point Advanced Room","5":"The 21 point Advanced Room"}',
            'game_code'=> '600',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'The 21 point Advanced Room',
            'external_game_id'=> '6006004',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Casino Niu-Niu Fresh Room","2":"通比牛牛体验房 ","3":"Casino Niu-Niu Fresh Room","4":"Casino Niu-Niu Fresh Room","5":"Casino Niu-Niu Fresh Room"}',
            'game_code'=> '870',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Casino Niu-Niu Fresh Room',
            'external_game_id'=> '8708701',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Casino Niu-Niu Beginner’s Room","2":"通比牛牛初级房 ","3":"Casino Niu-Niu Beginner’s Room","4":"Casino Niu-Niu Beginner’s Room","5":"Casino Niu-Niu Beginner’s Room"}',
            'game_code'=> '870',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Casino Niu-Niu Beginner’s Room',
            'external_game_id'=> '8708702',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Casino Niu-Niu Intermediate Room","2":"通比牛牛中级房","3":"Casino Niu-Niu Intermediate Room","4":"Casino Niu-Niu Intermediate Room","5":"Casino Niu-Niu Intermediate Room"}',
            'game_code'=> '870',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Casino Niu-Niu Intermediate Room',
            'external_game_id'=> '8708703',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Casino Niu-Niu Advanced Room","2":"通比牛牛高级房 ","3":"Casino Niu-Niu Advanced Room","4":"Casino Niu-Niu Advanced Room","5":"Casino Niu-Niu Advanced Room"}',
            'game_code'=> '870',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Casino Niu-Niu Advanced Room',
            'external_game_id'=> '8708704',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Happy Red Packets Fresh Room","2":"欢乐红包体验房 ","3":"Happy Red Packets Fresh Room","4":"Happy Red Packets Fresh Room","5":"Happy Red Packets Fresh Room"}',
            'game_code'=> '880',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Happy Red Packets Fresh Room',
            'external_game_id'=> '8808801',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Happy Red Packets Beginner’s Room","2":"欢乐红包初级房 ","3":"Happy Red Packets Beginner’s Room","4":"Happy Red Packets Beginner’s Room","5":"Happy Red Packets Beginner’s Room"}',
            'game_code'=> '880',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Happy Red Packets Beginner’s Room',
            'external_game_id'=> '8808802',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Happy Red Packets Intermediate Room","2":"欢乐红包中级房 ","3":"Happy Red Packets Intermediate Room","4":"Happy Red Packets Intermediate Room","5":"Happy Red Packets Intermediate Room"}',
            'game_code'=> '880',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Happy Red Packets Intermediate Room',
            'external_game_id'=> '8808803',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Happy Red Packets Advanced Room","2":"欢乐红包高级房 ","3":"Happy Red Packets Advanced Room","4":"Happy Red Packets Advanced Room","5":"Happy Red Packets Advanced Room"}',
            'game_code'=> '880',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Happy Red Packets Advanced Room',
            'external_game_id'=> '8808804',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Topspeed golden flower Fresh Room","2":"极速炸金花新手房","3":"Topspeed golden flower Fresh Room","4":"Topspeed golden flower Fresh Room","5":"Topspeed golden flower Fresh Room"}',
            'game_code'=> '230',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Topspeed golden flower Fresh Room',
            'external_game_id'=> '2302301',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Topspeed golden flower Beginner’s Room","2":"极速炸金花初级房","3":"Topspeed golden flower Beginner’s Room","4":"Topspeed golden flower Beginner’s Room","5":"Topspeed golden flower Beginner’s Room"}',
            'game_code'=> '230',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Topspeed golden flower Beginner’s Room',
            'external_game_id'=> '2302302',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Topspeed golden flower Intermediate Room","2":"极速炸金花中级房","3":"Topspeed golden flower Intermediate Room","4":"Topspeed golden flower Intermediate Room","5":"Topspeed golden flower Intermediate Room"}',
            'game_code'=> '230',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Topspeed golden flower Intermediate Room',
            'external_game_id'=> '2302303',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Topspeed golden flower Advanced Room","2":"极速炸金花高级房","3":"Topspeed golden flower Advanced Room","4":"Topspeed golden flower Advanced Room","5":"Topspeed golden flower Advanced Room"}',
            'game_code'=> '230',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Topspeed golden flower Advanced Room',
            'external_game_id'=> '2302304',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Banker Pai Gow Fresh Room","2":"抢庄牌九新手房 ","3":"Banker Pai Gow Fresh Room","4":"Banker Pai Gow Fresh Room","5":"Banker Pai Gow Fresh Room"}',
            'game_code'=> '730',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Banker Pai Gow Fresh Room',
            'external_game_id'=> '7307301',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Banker Pai Gow Beginner’s Room","2":"抢庄牌九初级房 ","3":"Banker Pai Gow Beginner’s Room","4":"Banker Pai Gow Beginner’s Room","5":"Banker Pai Gow Beginner’s Room"}',
            'game_code'=> '730',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Banker Pai Gow Beginner’s Room',
            'external_game_id'=> '7307302',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Banker Pai Gow Intermediate Room","2":"抢庄牌九中级房 ","3":"Banker Pai Gow Intermediate Room","4":"Banker Pai Gow Intermediate Room","5":"Banker Pai Gow Intermediate Room"}',
            'game_code'=> '730',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Banker Pai Gow Intermediate Room',
            'external_game_id'=> '7307303',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Banker Pai Gow Advanced Room","2":"抢庄牌九高级房 ","3":"Banker Pai Gow Advanced Room","4":"Banker Pai Gow Advanced Room","5":"Banker Pai Gow Advanced Room"}',
            'game_code'=> '730',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Banker Pai Gow Advanced Room',
            'external_game_id'=> '7307304',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Topspeed  Golden Flower","2":"极速炸金花","3":"Topspeed  Golden Flower","4":"Topspeed  Golden Flower","5":"Topspeed  Golden Flower"}',
            'game_code'=> '230',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Topspeed  Golden Flower',
            'external_game_id'=> '230',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Banker  Pai  Gow","2":"抢庄牌九 ","3":"Banker  Pai  Gow","4":"Banker  Pai  Gow","5":"Banker  Pai  Gow"}',
            'game_code'=> '730',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Banker  Pai  Gow',
            'external_game_id'=> '730',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"13  shui","2":"十三水 ","3":"13  shui","4":"13  shui","5":"13  shui"}',
            'game_code'=> '630',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> '13  shui',
            'external_game_id'=> '630',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"lucky  5  cards","2":"幸运五张","3":"lucky  5  cards","4":"lucky  5  cards","5":"lucky  5  cards"}',
            'game_code'=> '380',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'lucky  5  cards',
            'external_game_id'=> '380',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Fight  the  landlord","2":"斗地主","3":"Fight  the  landlord","4":"Fight  the  landlord","5":"Fight  the  landlord"}',
            'game_code'=> '610',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Fight  the  landlord',
            'external_game_id'=> '610',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Dragon  Gate","2":"射龙门","3":"Dragon  Gate","4":"Dragon  Gate","5":"Dragon  Gate"}',
            'game_code'=> '390',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Dragon  Gate',
            'external_game_id'=> '390',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Banker Niu-Niu Masterroom","2":"抢庄牛牛至尊房 ","3":"Banker Niu-Niu Masterroom","4":"Banker Niu-Niu Masterroom","5":"Banker Niu-Niu Masterroom"}',
            'game_code'=> '830',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Banker Niu-Niu Masterroom',
            'external_game_id'=> '8308305',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Fight the landlord Fresh Room","2":"斗地主体验房 ","3":"Fight the landlord Fresh Room","4":"Fight the landlord Fresh Room","5":"Fight the landlord Fresh Room"}',
            'game_code'=> '610',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Fight the landlord Fresh Room',
            'external_game_id'=> '6106101',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Fight the landlord Beginner’s Room","2":"斗地主初级房 ","3":"Fight the landlord Beginner’s Room","4":"Fight the landlord Beginner’s Room","5":"Fight the landlord Beginner’s Room"}',
            'game_code'=> '610',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Fight the landlord Beginner’s Room',
            'external_game_id'=> '6106102',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Fight the landlord Intermediate Room","2":"斗地主中级房 ","3":"Fight the landlord Intermediate Room","4":"Fight the landlord Intermediate Room","5":"Fight the landlord Intermediate Room"}',
            'game_code'=> '610',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Fight the landlord Intermediate Room',
            'external_game_id'=> '6106103',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Fight the landlord Advanced Room","2":"斗地主高级房 ","3":"Fight the landlord Advanced Room","4":"Fight the landlord Advanced Room","5":"Fight the landlord Advanced Room"}',
            'game_code'=> '610',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Fight the landlord Advanced Room',
            'external_game_id'=> '6106104',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"13 shiu regukar Fresh Room","2":"十三水常规场新手房","3":"13 shiu regukar Fresh Room","4":"13 shiu regukar Fresh Room","5":"13 shiu regukar Fresh Room"}',
            'game_code'=> '630',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> '13 shiu regukar Fresh Room',
            'external_game_id'=> '6306301',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"13 shiu regukar Beginner’s Room","2":"十三水常规场初级房","3":"13 shiu regukar Beginner’s Room","4":"13 shiu regukar Beginner’s Room","5":"13 shiu regukar Beginner’s Room"}',
            'game_code'=> '630',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> '13 shiu regukar Beginner’s Room',
            'external_game_id'=> '6306302',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"13 shiu regukar Intermediate Room","2":"十三水常规场中级房","3":"13 shiu regukar Intermediate Room","4":"13 shiu regukar Intermediate Room","5":"13 shiu regukar Intermediate Room"}',
            'game_code'=> '630',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> '13 shiu regukar Intermediate Room',
            'external_game_id'=> '6306303',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"13 shiu regukar Advanced Room","2":"十三水常规场高级房","3":"13 shiu regukar Advanced Room","4":"13 shiu regukar Advanced Room","5":"13 shiu regukar Advanced Room"}',
            'game_code'=> '630',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> '13 shiu regukar Advanced Room',
            'external_game_id'=> '6306304',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"13 shui speed Fresh Room","2":"十三水极速场新手房","3":"13 shui speed Fresh Room","4":"13 shui speed Fresh Room","5":"13 shui speed Fresh Room"}',
            'game_code'=> '630',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> '13 shui speed Fresh Room',
            'external_game_id'=> '6306305',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"13 shui speed Beginner’s Room","2":"十三水极速场初级房","3":"13 shui speed Beginner’s Room","4":"13 shui speed Beginner’s Room","5":"13 shui speed Beginner’s Room"}',
            'game_code'=> '630',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> '13 shui speed Beginner’s Room',
            'external_game_id'=> '6306306',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"13 shui speed Intermediate Room","2":"十三水极速场中级房","3":"13 shui speed Intermediate Room","4":"13 shui speed Intermediate Room","5":"13 shui speed Intermediate Room"}',
            'game_code'=> '630',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> '13 shui speed Intermediate Room',
            'external_game_id'=> '6306307',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"13 shui speed Advanced Room","2":"十三水极速场高级房","3":"13 shui speed Advanced Room","4":"13 shui speed Advanced Room","5":"13 shui speed Advanced Room"}',
            'game_code'=> '630',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> '13 shui speed Advanced Room',
            'external_game_id'=> '6306308',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"lucky 5 cards Fresh Room","2":"幸运五张体验房","3":"lucky 5 cards Fresh Room","4":"lucky 5 cards Fresh Room","5":"lucky 5 cards Fresh Room"}',
            'game_code'=> '380',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'lucky 5 cards Fresh Room',
            'external_game_id'=> '3803801',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"lucky 5 cards Beginner’s Room","2":"幸运五张初级房 ","3":"lucky 5 cards Beginner’s Room","4":"lucky 5 cards Beginner’s Room","5":"lucky 5 cards Beginner’s Room"}',
            'game_code'=> '380',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'lucky 5 cards Beginner’s Room',
            'external_game_id'=> '3803802',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"lucky 5 cards Intermediate Room","2":"幸运五张中级房 ","3":"lucky 5 cards Intermediate Room","4":"lucky 5 cards Intermediate Room","5":"lucky 5 cards Intermediate Room"}',
            'game_code'=> '380',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'lucky 5 cards Intermediate Room',
            'external_game_id'=> '3803803',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"lucky 5 cards Advanced Room","2":"幸运五张高级房 ","3":"lucky 5 cards Advanced Room","4":"lucky 5 cards Advanced Room","5":"lucky 5 cards Advanced Room"}',
            'game_code'=> '380',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'lucky 5 cards Advanced Room',
            'external_game_id'=> '3803804',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Dragon Gate","2":"射龙门 ","3":"Dragon Gate","4":"Dragon Gate","5":"Dragon Gate"}',
            'game_code'=> '390',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Dragon Gate',
            'external_game_id'=> '3903901',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Dragon Gate","2":"射龙门 ","3":"Dragon Gate","4":"Dragon Gate","5":"Dragon Gate"}',
            'game_code'=> '390',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Dragon Gate',
            'external_game_id'=> '3903902',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Baccarat","2":"百家乐","3":"Baccarat","4":"Baccarat","5":"Baccarat"}',
            'game_code'=> '910',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Baccarat',
            'external_game_id'=> '910',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Baccarat Fresh Room","2":"百家乐体验房","3":"Baccarat Fresh Room","4":"Baccarat Fresh Room","5":"Baccarat Fresh Room"}',
            'game_code'=> '910',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Baccarat Fresh Room',
            'external_game_id'=> '9109101',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Baccarat Beginner’s Room","2":"百家乐初级房","3":"Baccarat Beginner’s Room","4":"Baccarat Beginner’s Room","5":"Baccarat Beginner’s Room"}',
            'game_code'=> '910',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Baccarat Beginner’s Room',
            'external_game_id'=> '9109102',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Baccarat Intermediate Room","2":"百家乐中级房","3":"Baccarat Intermediate Room","4":"Baccarat Intermediate Room","5":"Baccarat Intermediate Room"}',
            'game_code'=> '910',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Baccarat Intermediate Room',
            'external_game_id'=> '9109103',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        [
            'game_platform_id'=> $api_id,
            'game_type_id'=> $gameTypeCodeMaps[$game_type_code_table_game],
            'game_name'=> '_json:{"1":"Baccarat Advanced Room","2":"百家乐高级房","3":"Baccarat Advanced Room","4":"Baccarat Advanced Room","5":"Baccarat Advanced Room"}',
            'game_code'=> '910',
            'dlc_enabled'=> $db_false,
            'progressive'=> $db_false,
            'flash_enabled'=> $db_false,
            'offline_enabled'=> $db_false,
            'mobile_enabled'=> $db_true,
            'html_five_enabled'=> $db_true,
            'english_name'=> 'Baccarat Advanced Room',
            'external_game_id'=> '9109104',
            'enabled_freespin'=> $db_false,
            'enabled_on_android'=> $db_false,
            'enabled_on_ios'=> $db_false,
        ],

        );

		$this->load->model(['game_description_model']);

        $success=$this->game_description_model->syncGameDescription($game_descriptions);

        return $success;
	}

}
