<?php

defined('BASEPATH') OR exit('No direct script access allowed');

class Migration_update_fg_game_description_20161103 extends CI_Migration {
	
	const FLAG_TRUE = 1;
	const FLAG_FALSE = 0;

	public function up() {

		$this->db->start_trans();

		$game_descriptions = array(
			array(
				'game_platform_id' => 51, 
				'game_code' => '70070', 
				'game_name' => '_json:{"1":"A While on the Nile","2":"A While on the Nile"}', 
				'english_name' => 'A While on the Nile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '70011', 
				'game_name' => '_json:{"1":"Call of the Colosseum","2":"Call of the Colosseum"}', 
				'english_name' => 'Call of the Colosseum',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '70076', 
				'game_name' => '_json:{"1":"Casinomeister","2":"Casinomeister"}', 
				'english_name' => 'Casinomeister',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '70005', 
				'game_name' => '_json:{"1":"Doctor Love","2":"Doctor Love"}', 
				'english_name' => 'Doctor Love',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '70033', 
				'game_name' => '_json:{"1":"Genie Wild","2":"Genie Wild"}', 
				'english_name' => 'Genie Wild',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '70128', 
				'game_name' => '_json:{"1":"Scratch Big Foot","2":"Scratch Big Foot"}', 
				'english_name' => 'Scratch Big Foot',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '70140', 
				'game_name' => '_json:{"1":"Scratch Call of the Colosseum","2":"Scratch Call of the Colosseum"}', 
				'english_name' => 'Scratch Call of the Colosseum',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '70097', 
				'game_name' => '_json:{"1":"Scratch Dr Love ","2":"Scratch Dr Love "}', 
				'english_name' => 'Scratch Dr Love ',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '70098', 
				'game_name' => '_json:{"1":"Scratch Dr Love On Vacation","2":"Scratch Dr Love On Vacation"}', 
				'english_name' => 'Scratch Dr Love On Vacation',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '70096', 
				'game_name' => '_json:{"1":"Scratch Emperors Garden ","2":"Scratch Emperors Garden "}', 
				'english_name' => 'Scratch Emperors Garden ',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '70095', 
				'game_name' => '_json:{"1":"Scratch Foxin Wins ","2":"Scratch Foxin Wins "}', 
				'english_name' => 'Scratch Foxin Wins ',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '70130', 
				'game_name' => '_json:{"1":"Scratch Genie Wild","2":"Scratch Genie Wild"}', 
				'english_name' => 'Scratch Genie Wild',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '70110', 
				'game_name' => '_json:{"1":"Scratch Gorilla Go Wild","2":"Scratch Gorilla Go Wild"}', 
				'english_name' => 'Scratch Gorilla Go Wild',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '70102', 
				'game_name' => '_json:{"1":"Scratch Irish Eyes","2":"Scratch Irish Eyes"}', 
				'english_name' => 'Scratch Irish Eyes',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '70094', 
				'game_name' => '_json:{"1":"Scratch Irish Eyes 2 ","2":"Scratch Irish Eyes 2 "}', 
				'english_name' => 'Scratch Irish Eyes 2 ',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '70099', 
				'game_name' => '_json:{"1":"Scratch Medusa","2":"Scratch Medusa"}', 
				'english_name' => 'Scratch Medusa',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '70100', 
				'game_name' => '_json:{"1":"Scratch Merlins Millions","2":"Scratch Merlins Millions"}', 
				'english_name' => 'Scratch Merlins Millions',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '70135', 
				'game_name' => '_json:{"1":"Scratch Oil Mania","2":"Scratch Oil Mania"}', 
				'english_name' => 'Scratch Oil Mania',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '70132', 
				'game_name' => '_json:{"1":"Scratch Pandamania","2":"Scratch Pandamania"}', 
				'english_name' => 'Scratch Pandamania',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '70101', 
				'game_name' => '_json:{"1":"Scratch Ramesses Riches ","2":"Scratch Ramesses Riches "}', 
				'english_name' => 'Scratch Ramesses Riches
			 '
			,),
			array(
				'game_platform_id' => 51, 
				'game_code' => '70093', 
				'game_name' => '_json:{"1":"Scratch The Codfather ","2":"Scratch The Codfather "}', 
				'english_name' => 'Scratch The Codfather ',
			),
			array(
				'game_platform_id' => 51,
				'game_code' => '70133', 
				'game_name' => '_json:{"1":"Scratch The Snake Charmer","2":"Scratch The Snake Charmer"}', 
				'english_name' => 'Scratch The Snake Charmer',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '70111', 
				'game_name' => '_json:{"1":"Scratch Volcano Eruption","2":"Scratch Volcano Eruption"}', 
				'english_name' => 'Scratch Volcano Eruption',
			 ),
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70071', 
				'game_name' => '_json:{"1":"1 Can 2 Can","2":"1 Can 2 Can"}', 
				'english_name' => '1 Can 2 Can',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70003', 
				'game_name' => '_json:{"1":"300 Shields","2":"300 Shields"}', 
				'english_name' => '300 Shields',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70058', 
				'game_name' => '_json:{"1":"5 Knights","2":"5 Knights"}', 
				'english_name' => '5 Knights',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70008', 
				'game_name' => '_json:{"1":"Andre the Giant","2":"Andre the Giant"}', 
				'english_name' => 'Andre the Giant',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70009', 
				'game_name' => '_json:{"1":"Bangkok Nights","2":"Bangkok Nights"}', 
				'english_name' => 'Bangkok Nights',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70010', 
				'game_name' => '_json:{"1":"Big Foot","2":"Big Foot"}', 
				'english_name' => 'Big Foot',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70112', 
				'game_name' => '_json:{"1":"Big Foot Mini","2":"Big Foot Mini"}', 
				'english_name' => 'Big Foot Mini',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70109', 
				'game_name' => '_json:{"1":"Bingo Billions","2":"Bingo Billions"}', 
				'english_name' => 'Bingo Billions',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70083', 
				'game_name' => '_json:{"1":"Blackjack Pro Monte Carlo Multi-hand ","2":"Blackjack Pro Monte Carlo Multi-hand "}', 
				'english_name' => 'Blackjack Pro Monte Carlo Multi-hand ',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70084', 
				'game_name' => '_json:{"1":"Blackjack Pro Monte Carlo Single-hand ","2":"Blackjack Pro Monte Carlo Single-hand "}', 
				'english_name' => 'Blackjack Pro Monte Carlo Single-hand ',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70028', 
				'game_name' => '_json:{"1":"Bobby 7’s","2":"Bobby 7’s"}', 
				'english_name' => 'Bobby 7’s',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70113', 
				'game_name' => '_json:{"1":"Bobby 7’s Mini","2":"Bobby 7’s Mini"}', 
				'english_name' => 'Bobby 7’s Mini',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70023', 
				'game_name' => '_json:{"1":"Butterflies","2":"Butterflies"}', 
				'english_name' => 'Butterflies',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70018', 
				'game_name' => '_json:{"1":"California Gold","2":"California Gold"}', 
				'english_name' => 'California Gold',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70145', 
				'game_name' => '_json:{"1":"Cash Stampede","2":"Cash Stampede"}', 
				'english_name' => 'Cash Stampede',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70013', 
				'game_name' => '_json:{"1":"Cherry Blossoms","2":"Cherry Blossoms"}', 
				'english_name' => 'Cherry Blossoms',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70114', 
				'game_name' => '_json:{"1":"Cherry Blossoms Mini","2":"Cherry Blossoms Mini"}', 
				'english_name' => 'Cherry Blossoms Mini',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70004', 
				'game_name' => '_json:{"1":"Crocodopolis","2":"Crocodopolis"}', 
				'english_name' => 'Crocodopolis',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70115', 
				'game_name' => '_json:{"1":"Doctor Love Mini","2":"Doctor Love Mini"}', 
				'english_name' => 'Doctor Love Mini',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70014', 
				'game_name' => '_json:{"1":"Dolphin Reef","2":"Dolphin Reef"}', 
				'english_name' => 'Dolphin Reef',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70138', 
				'game_name' => '_json:{"1":"Double Play SuperBet","2":"Double Play SuperBet"}', 
				'english_name' => 'Double Play SuperBet',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70043', 
				'game_name' => '_json:{"1":"Doctor Love on Vacation","2":"Doctor Love on Vacation"}', 
				'english_name' => 'Doctor Love on Vacation',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70068', 
				'game_name' => '_json:{"1":"Dragon Drop","2":"Dragon Drop"}', 
				'english_name' => 'Dragon Drop',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70015', 
				'game_name' => '_json:{"1":"Dynasty","2":"Dynasty"}', 
				'english_name' => 'Dynasty',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70049', 
				'game_name' => '_json:{"1":"Eastern Dragon","2":"Eastern Dragon"}', 
				'english_name' => 'Eastern Dragon',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70065', 
				'game_name' => '_json:{"1":"Easy Slider","2":"Easy Slider"}', 
				'english_name' => 'Easy Slider',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70059', 
				'game_name' => '_json:{"1":"Emperor’s Garden","2":"Emperor’s Garden"}', 
				'english_name' => 'Emperor’s Garden',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70024', 
				'game_name' => '_json:{"1":"Enchanted Mermaid","2":"Enchanted Mermaid"}', 
				'english_name' => 'Enchanted Mermaid',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70067', 
				'game_name' => '_json:{"1":"Extra Cash!!","2":"Extra Cash!!"}', 
				'english_name' => 'Extra Cash!!',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70016', 
				'game_name' => '_json:{"1":"Fairies Forest","2":"Fairies Forest"}', 
				'english_name' => 'Fairies Forest',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70032', 
				'game_name' => '_json:{"1":"Fire Hawk","2":"Fire Hawk"}', 
				'english_name' => 'Fire Hawk',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70044', 
				'game_name' => '_json:{"1":"Foxin’ Wins","2":"Foxin’ Wins"}', 
				'english_name' => 'Foxin’ Wins',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70080', 
				'game_name' => '_json:{"1":"Foxin’ Wins Again","2":"Foxin’ Wins Again"}', 
				'english_name' => 'Foxin’ Wins Again',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70025', 
				'game_name' => '_json:{"1":"Gold Ahoy","2":"Gold Ahoy"}', 
				'english_name' => 'Gold Ahoy',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70090', 
				'game_name' => '_json:{"1":"Gorilla Go Wild","2":"Gorilla Go Wild"}', 
				'english_name' => 'Gorilla Go Wild',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70029', 
				'game_name' => '_json:{"1":"Hot Roller","2":"Hot Roller"}', 
				'english_name' => 'Hot Roller',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70006', 
				'game_name' => '_json:{"1":"Irish Eyes","2":"Irish Eyes"}', 
				'english_name' => 'Irish Eyes',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70116', 
				'game_name' => '_json:{"1":"Irish Eyes Mini","2":"Irish Eyes Mini"}', 
				'english_name' => 'Irish Eyes Mini',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70042', 
				'game_name' => '_json:{"1":"Irish Eyes 2","2":"Irish Eyes 2"}', 
				'english_name' => 'Irish Eyes 2',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70144', 
				'game_name' => '_json:{"1":"Jack’s Beanstalk","2":"Jack’s Beanstalk"}', 
				'english_name' => 'Jack’s Beanstalk',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70041', 
				'game_name' => '_json:{"1":"Jackpot Jester 50k","2":"Jackpot Jester 50k"}', 
				'english_name' => 'Jackpot Jester 50k',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70143', 
				'game_name' => '_json:{"1":"Jackpot Jester Wild Nudge","2":"Jackpot Jester Wild Nudge"}', 
				'english_name' => 'Jackpot Jester Wild Nudge',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70034', 
				'game_name' => '_json:{"1":"Joker Jester","2":"Joker Jester"}', 
				'english_name' => 'Joker Jester',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70117', 
				'game_name' => '_json:{"1":"Joker Jester Mini","2":"Joker Jester Mini"}', 
				'english_name' => 'Joker Jester Mini',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70017', 
				'game_name' => '_json:{"1":"King Tiger","2":"King Tiger"}', 
				'english_name' => 'King Tiger',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70019', 
				'game_name' => '_json:{"1":"La Cucaracha ","2":"La Cucaracha "}', 
				'english_name' => 'La Cucaracha ',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70035', 
				'game_name' => '_json:{"1":"Love Bugs","2":"Love Bugs"}', 
				'english_name' => 'Love Bugs',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70118', 
				'game_name' => '_json:{"1":"Love Bugs Mini","2":"Love Bugs Mini"}', 
				'english_name' => 'Love Bugs Mini',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70002', 
				'game_name' => '_json:{"1":"Mad Mad Monkey","2":"Mad Mad Monkey"}', 
				'english_name' => 'Mad Mad Monkey',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70119', 
				'game_name' => '_json:{"1":"Mad Mad Monkey Mini","2":"Mad Mad Monkey Mini"}', 
				'english_name' => 'Mad Mad Monkey Mini',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70046', 
				'game_name' => '_json:{"1":"Maid O Money","2":"Maid O Money"}', 
				'english_name' => 'Maid O Money',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70020', 
				'game_name' => '_json:{"1":"Medusa","2":"Medusa"}', 
				'english_name' => 'Medusa',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70120', 
				'game_name' => '_json:{"1":"Medusa Mini","2":"Medusa Mini"}', 
				'english_name' => 'Medusa Mini',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70072', 
				'game_name' => '_json:{"1":"Medusa II","2":"Medusa II"}', 
				'english_name' => 'Medusa II',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70069', 
				'game_name' => '_json:{"1":"Merlin’s Magic Respins","2":"Merlin’s Magic Respins"}', 
				'english_name' => 'Merlin’s Magic Respins',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70030', 
				'game_name' => '_json:{"1":"Merlin’s Millions Superbet","2":"Merlin’s Millions Superbet"}', 
				'english_name' => 'Merlin’s Millions Superbet',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70121', 
				'game_name' => '_json:{"1":"Merlin’s Millions Superbet Mini ","2":"Merlin’s Millions Superbet Mini "}', 
				'english_name' => 'Merlin’s Millions Superbet Mini ',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70089', 
				'game_name' => '_json:{"1":"Miss Midas","2":"Miss Midas"}', 
				'english_name' => 'Miss Midas',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70045', 
				'game_name' => '_json:{"1":"Munchers","2":"Munchers"}', 
				'english_name' => 'Munchers',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70122', 
				'game_name' => '_json:{"1":"Munchers Mini","2":"Munchers Mini"}', 
				'english_name' => 'Munchers Mini',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70066', 
				'game_name' => '_json:{"1":"Napoleon Boney Parts","2":"Napoleon Boney Parts"}', 
				'english_name' => 'Napoleon Boney Parts',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70036', 
				'game_name' => '_json:{"1":"Oil Mania","2":"Oil Mania"}', 
				'english_name' => 'Oil Mania',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70123', 
				'game_name' => '_json:{"1":"Oil Mania Mini","2":"Oil Mania Mini"}', 
				'english_name' => 'Oil Mania Mini',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70075', 
				'game_name' => '_json:{"1":"Owl Eyes","2":"Owl Eyes"}', 
				'english_name' => 'Owl Eyes',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70082', 
				'game_name' => '_json:{"1":"Pandamania","2":"Pandamania"}', 
				'english_name' => 'Pandamania',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70047', 
				'game_name' => '_json:{"1":"Pizza Prize","2":"Pizza Prize"}', 
				'english_name' => 'Pizza Prize',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70063', 
				'game_name' => '_json:{"1":"Potion Commotion","2":"Potion Commotion"}', 
				'english_name' => 'Potion Commotion',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70007', 
				'game_name' => '_json:{"1":"Ramesses Riches","2":"Ramesses Riches"}', 
				'english_name' => 'Ramesses Riches',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70124', 
				'game_name' => '_json:{"1":"Ramesses Riches Mini","2":"Ramesses Riches Mini"}', 
				'english_name' => 'Ramesses Riches Mini',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70073', 
				'game_name' => '_json:{"1":"Roulette Master","2":"Roulette Master"}', 
				'english_name' => 'Roulette Master',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70012', 
				'game_name' => '_json:{"1":"Shaaark! Superbet","2":"Shaaark! Superbet"}', 
				'english_name' => 'Shaaark! Superbet',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70061', 
				'game_name' => '_json:{"1":"Spanish Eyes","2":"Spanish Eyes"}', 
				'english_name' => 'Spanish Eyes',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70152', 
				'game_name' => '_json:{"1":"Spin Sorceress","2":"Spin Sorceress"}', 
				'english_name' => 'Spin Sorceress',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70146', 
				'game_name' => '_json:{"1":"Starmania","2":"Starmania"}', 
				'english_name' => 'Starmania',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70062', 
				'game_name' => '_json:{"1":"Super Safari","2":"Super Safari"}', 
				'english_name' => 'Super Safari',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70048', 
				'game_name' => '_json:{"1":"Teddy Bears’ Picnic","2":"Teddy Bears’ Picnic"}', 
				'english_name' => 'Teddy Bears’ Picnic',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70031', 
				'game_name' => '_json:{"1":"The Bermuda Mysteries","2":"The Bermuda Mysteries"}', 
				'english_name' => 'The Bermuda Mysteries',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70060', 
				'game_name' => '_json:{"1":"The Codfather","2":"The Codfather"}', 
				'english_name' => 'The Codfather',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70026', 
				'game_name' => '_json:{"1":"The Snake Charmer","2":"The Snake Charmer"}', 
				'english_name' => 'The Snake Charmer',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70125', 
				'game_name' => '_json:{"1":"The Snake Charmer Mini","2":"The Snake Charmer Mini"}', 
				'english_name' => 'The Snake Charmer Mini',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70107', 
				'game_name' => '_json:{"1":"The Spin Lab","2":"The Spin Lab"}', 
				'english_name' => 'The Spin Lab',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70077', 
				'game_name' => '_json:{"1":"Titan Storm","2":"Titan Storm"}', 
				'english_name' => 'Titan Storm',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70027', 
				'game_name' => '_json:{"1":"Tootin Car Man","2":"Tootin Car Man"}', 
				'english_name' => 'Tootin Car Man',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70021', 
				'game_name' => '_json:{"1":"Unicorn Legend","2":"Unicorn Legend"}', 
				'english_name' => 'Unicorn Legend',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70022', 
				'game_name' => '_json:{"1":"Venetian Rose","2":"Venetian Rose"}', 
				'english_name' => 'Venetian Rose',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70126', 
				'game_name' => '_json:{"1":"Venetian Rose Mini","2":"Venetian Rose Mini"}', 
				'english_name' => 'Venetian Rose Mini',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70001', 
				'game_name' => '_json:{"1":"Volcano Eruption","2":"Volcano Eruption"}', 
				'english_name' => 'Volcano Eruption',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70127', 
				'game_name' => '_json:{"1":"Volcano Eruption Mini","2":"Volcano Eruption Mini"}', 
				'english_name' => 'Volcano Eruption Mini',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70078', 
				'game_name' => '_json:{"1":"Wild West","2":"Wild West"}', 
				'english_name' => 'Wild West',
			), 
			array( 
				'game_platform_id' => 51, 
				'game_code' => '70064', 
				'game_name' => '_json:{"1":"Wildcat Canyon","2":"Wildcat Canyon"}', 
				'english_name' => 'Wildcat Canyon',
			), 
			array(
				'game_platform_id' => 51, 
				'game_code' => 'alice_c', 
				'game_name' => '_json:{"1":"Alice in Wonderslots","2":"Alice in Wonderslots"}', 
				'english_name' => 'Alice in Wonderslots',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'aquatica_c', 
				'game_name' => '_json:{"1":"Aquatica","2":"Aquatica"}', 
				'english_name' => 'Aquatica',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'aquarium_c', 
				'game_name' => '_json:{"1":"Aquarium","2":"Aquarium"}', 
				'english_name' => 'Aquarium',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'aztec_empire_c', 
				'game_name' => '_json:{"1":"Aztec Empire","2":"Aztec Empire"}', 
				'english_name' => 'Aztec Empire',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'blackjack_classic', 
				'game_name' => '_json:{"1":"Black Jack ","2":"Black Jack "}', 
				'english_name' => 'Black Jack ',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'bumper_crop', 
				'game_name' => '_json:{"1":"Bumper Crop","2":"Bumper Crop"}', 
				'english_name' => 'Bumper Crop',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'burlesque_queen', 
				'game_name' => '_json:{"1":"Burlesque Queen","2":"Burlesque Queen"}', 
				'english_name' => 'Burlesque Queen',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'circus_deluxe_c', 
				'game_name' => '_json:{"1":"Circus Deluxe","2":"Circus Deluxe"}', 
				'english_name' => 'Circus Deluxe',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'doublejokerpoker', 
				'game_name' => '_json:{"1":"Double Joker Poker ","2":"Double Joker Poker "}', 
				'english_name' => 'Double Joker Poker ',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'draculas_family_c', 
				'game_name' => '_json:{"1":"Dracula’s Family","2":"Dracula’s Family"}', 
				'english_name' => 'Dracula’s Family',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'eastern_delights_c', 
				'game_name' => '_json:{"1":"Eastern Delights","2":"Eastern Delights"}', 
				'english_name' => 'Eastern Delights',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'fruits_of_the_nile_c', 
				'game_name' => '_json:{"1":"Fruits of the Nile","2":"Fruits of the Nile"}', 
				'english_name' => 'Fruits of the Nile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'fruits_n_stars_c', 
				'game_name' => '_json:{"1":"Fruits’n’Stars","2":"Fruits’n’Stars"}', 
				'english_name' => 'Fruits’n’Stars',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'gold_rush', 
				'game_name' => '_json:{"1":"Gold Rush","2":"Gold Rush"}', 
				'english_name' => 'Gold Rush',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'happy_jungle_deluxe_c', 
				'game_name' => '_json:{"1":"Happy Jungle Deluxe","2":"Happy Jungle Deluxe"}', 
				'english_name' => 'Happy Jungle Deluxe',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'juice_and_fruits_c', 
				'game_name' => '_json:{"1":"Juice’n’Fruits","2":"Juice’n’Fruits"}', 
				'english_name' => 'Juice’n’Fruits',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'lucky_birds_c', 
				'game_name' => '_json:{"1":"Lucky Birds","2":"Lucky Birds"}', 
				'english_name' => 'Lucky Birds',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'lucky_pirates_c', 
				'game_name' => '_json:{"1":"Lucky Pirates","2":"Lucky Pirates"}', 
				'english_name' => 'Lucky Pirates',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'lucky_reels_c', 
				'game_name' => '_json:{"1":"Lucky Reels","2":"Lucky Reels"}', 
				'english_name' => 'Lucky Reels',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'magic_forest_c', 
				'game_name' => '_json:{"1":"Magic Forest","2":"Magic Forest"}', 
				'english_name' => 'Magic Forest',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'merry_christmas_c', 
				'game_name' => '_json:{"1":"Merry Christmas","2":"Merry Christmas"}', 
				'english_name' => 'Merry Christmas',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'notre_dames_c', 
				'game_name' => '_json:{"1":"Mysteries of Notre Dames","2":"Mysteries of Notre Dames"}', 
				'english_name' => 'Mysteries of Notre Dames',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'odysseus_c', 
				'game_name' => '_json:{"1":"Odysseus","2":"Odysseus"}', 
				'english_name' => 'Odysseus',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'pirate_treasures_deluxe_c', 
				'game_name' => '_json:{"1":"Pirate’s Treasures Deluxe","2":"Pirate’s Treasures Deluxe"}', 
				'english_name' => 'Pirate’s Treasures Deluxe',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'roulette_with_track', 
				'game_name' => '_json:{"1":"Roulette with track ","2":"Roulette with track "}', 
				'english_name' => 'Roulette with track ',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'riches_of_cleopatra_c', 
				'game_name' => '_json:{"1":"Riches of Cleopatra","2":"Riches of Cleopatra"}', 
				'english_name' => 'Riches of Cleopatra',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'sky_way_c', 
				'game_name' => '_json:{"1":"Skyway","2":"Skyway"}', 
				'english_name' => 'Skyway',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'spaces_corsairs', 
				'game_name' => '_json:{"1":"Space Corsairs","2":"Space Corsairs"}', 
				'english_name' => 'Space Corsairs',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'spirit_of_aztec_e', 
				'game_name' => '_json:{"1":"Spirit Of Aztec","2":"Spirit Of Aztec"}', 
				'english_name' => 'Spirit Of Aztec',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'taiga_c', 
				'game_name' => '_json:{"1":"Taiga","2":"Taiga"}', 
				'english_name' => 'Taiga',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'thunder_reels_c', 
				'game_name' => '_json:{"1":"Thunder Reels","2":"Thunder Reels"}', 
				'english_name' => 'Thunder Reels',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'treasures_of_tombs_bonus_c', 
				'game_name' => '_json:{"1":"Treasures Of Tombs","2":"Treasures Of Tombs"}', 
				'english_name' => 'Treasures Of Tombs',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'wild_hunter_c', 
				'game_name' => '_json:{"1":"Wild Hunter","2":"Wild Hunter"}', 
				'english_name' => 'Wild Hunter',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'wild_sevens', 
				'game_name' => '_json:{"1":"Wild Sevens","2":"Wild Sevens"}', 
				'english_name' => 'Wild Sevens',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'zombirthday_c', 
				'game_name' => '_json:{"1":"Zombirthday","2":"Zombirthday"}', 
				'english_name' => 'Zombirthday',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'alice_c_mob', 
				'game_name' => '_json:{"1":"Alice in Wonderslots","2":"Alice in Wonderslots"}', 
				'english_name' => 'Alice in Wonderslots',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'aquatica_c_mob', 
				'game_name' => '_json:{"1":"Aquatica","2":"Aquatica"}', 
				'english_name' => 'Aquatica',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'aquarium_c_mob', 
				'game_name' => '_json:{"1":"Aquarium","2":"Aquarium"}', 
				'english_name' => 'Aquarium',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'aztec_empire_c_mob', 
				'game_name' => '_json:{"1":"Aztec Empire","2":"Aztec Empire"}', 
				'english_name' => 'Aztec Empire',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'blackjack_mob', 
				'game_name' => '_json:{"1":"Black Jack ","2":"Black Jack "}', 
				'english_name' => 'Black Jack ',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'bumper_crop_mob', 
				'game_name' => '_json:{"1":"Bumper Crop","2":"Bumper Crop"}', 
				'english_name' => 'Bumper Crop',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'burlesque_queen_mob', 
				'game_name' => '_json:{"1":"Burlesque Queen","2":"Burlesque Queen"}', 
				'english_name' => 'Burlesque Queen',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'circus_deluxe_c_mob', 
				'game_name' => '_json:{"1":"Circus Deluxe","2":"Circus Deluxe"}', 
				'english_name' => 'Circus Deluxe',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'doublejokerpoker_mob', 
				'game_name' => '_json:{"1":"Double Joker Poker ","2":"Double Joker Poker "}', 
				'english_name' => 'Double Joker Poker ',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'draculas_family_c_mob', 
				'game_name' => '_json:{"1":"Dracula’s Family","2":"Dracula’s Family"}', 
				'english_name' => 'Dracula’s Family',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'eastern_delights_c_mob', 
				'game_name' => '_json:{"1":"Eastern Delights","2":"Eastern Delights"}', 
				'english_name' => 'Eastern Delights',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'fruits_of_the_nile_c_mob', 
				'game_name' => '_json:{"1":"Fruits of the Nile","2":"Fruits of the Nile"}', 
				'english_name' => 'Fruits of the Nile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'fruits_n_stars_c_mob', 
				'game_name' => '_json:{"1":"Fruits’n’Stars","2":"Fruits’n’Stars"}', 
				'english_name' => 'Fruits’n’Stars',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'gold_rush', 
				'game_name' => '_json:{"1":"Gold Rush","2":"Gold Rush"}', 
				'english_name' => 'Gold Rush',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'happy_jungle_deluxe_c_mob', 
				'game_name' => '_json:{"1":"Happy Jungle Deluxe","2":"Happy Jungle Deluxe"}', 
				'english_name' => 'Happy Jungle Deluxe',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'juice_and_fruits_c_mob', 
				'game_name' => '_json:{"1":"Juice’n’Fruits","2":"Juice’n’Fruits"}', 
				'english_name' => 'Juice’n’Fruits',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'lucky_birds_c_mob', 
				'game_name' => '_json:{"1":"Lucky Birds","2":"Lucky Birds"}', 
				'english_name' => 'Lucky Birds',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'lucky_pirates_c_mob', 
				'game_name' => '_json:{"1":"Lucky Pirates","2":"Lucky Pirates"}', 
				'english_name' => 'Lucky Pirates',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'lucky_reels_c_mob', 
				'game_name' => '_json:{"1":"Lucky Reels","2":"Lucky Reels"}', 
				'english_name' => 'Lucky Reels',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'magic_forest_c_mob', 
				'game_name' => '_json:{"1":"Magic Forest","2":"Magic Forest"}', 
				'english_name' => 'Magic Forest',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'merry_christmas_c_mob', 
				'game_name' => '_json:{"1":"Merry Christmas","2":"Merry Christmas"}', 
				'english_name' => 'Merry Christmas',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'notre_dames_c_mob', 
				'game_name' => '_json:{"1":"Mysteries of Notre Dames","2":"Mysteries of Notre Dames"}', 
				'english_name' => 'Mysteries of Notre Dames',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'odysseus_c_mob', 
				'game_name' => '_json:{"1":"Odysseus","2":"Odysseus"}', 
				'english_name' => 'Odysseus',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'pirate_treasures_deluxe_c_mob', 
				'game_name' => '_json:{"1":"Pirate’s Treasures Deluxe","2":"Pirate’s Treasures Deluxe"}', 
				'english_name' => 'Pirate’s Treasures Deluxe',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'roulette_with_track_mob', 
				'game_name' => '_json:{"1":"Roulette with track ","2":"Roulette with track "}', 
				'english_name' => 'Roulette with track ',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'riches_of_cleopatra_c_mob', 
				'game_name' => '_json:{"1":"Riches of Cleopatra","2":"Riches of Cleopatra"}', 
				'english_name' => 'Riches of Cleopatra',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'sky_way_c_mob', 
				'game_name' => '_json:{"1":"Skyway","2":"Skyway"}', 
				'english_name' => 'Skyway',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'space_corsairs_mob', 
				'game_name' => '_json:{"1":"Space Corsairs","2":"Space Corsairs"}', 
				'english_name' => 'Space Corsairs',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'spirit_of_aztec_e_mob', 
				'game_name' => '_json:{"1":"Spirit Of Aztec","2":"Spirit Of Aztec"}', 
				'english_name' => 'Spirit Of Aztec',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'taiga_c_mob', 
				'game_name' => '_json:{"1":"Taiga","2":"Taiga"}', 
				'english_name' => 'Taiga',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'thunder_reels_c_mob', 
				'game_name' => '_json:{"1":"Thunder Reels","2":"Thunder Reels"}', 
				'english_name' => 'Thunder Reels',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'treasures_of_tombs_bonus_c_mob', 
				'game_name' => '_json:{"1":"Treasures Of Tombs","2":"Treasures Of Tombs"}', 
				'english_name' => 'Treasures Of Tombs',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'wild_hunter_c_mob', 
				'game_name' => '_json:{"1":"Wild Hunter","2":"Wild Hunter"}', 
				'english_name' => 'Wild Hunter',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'wild_sevens_mob', 
				'game_name' => '_json:{"1":"Wild Sevens","2":"Wild Sevens"}', 
				'english_name' => 'Wild Sevens',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'zombirthday_c_mob', 
				'game_name' => '_json:{"1":"Zombirthday","2":"Zombirthday"}', 
				'english_name' => 'Zombirthday',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100199', 
				'game_name' => '_json:{"1":"5x Magic Mobile","2":"5x Magic Mobile"}', 
				'english_name' => '5x Magic Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100099', 
				'game_name' => '_json:{"1":"Ace of Spades Mobile","2":"Ace of Spades Mobile"}', 
				'english_name' => 'Ace of Spades Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100243', 
				'game_name' => '_json:{"1":"Aztec Idols Mobile","2":"Aztec Idols Mobile"}', 
				'english_name' => 'Aztec Idols Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100034', 
				'game_name' => '_json:{"1":"Beat Me Mobile","2":"Beat Me Mobile"}', 
				'english_name' => 'Beat Me Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100105', 
				'game_name' => '_json:{"1":"Bell of Fortune Mobile","2":"Bell of Fortune Mobile"}', 
				'english_name' => 'Bell of Fortune Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100052', 
				'game_name' => '_json:{"1":"BlackJack MH Mobile","2":"BlackJack MH Mobile"}', 
				'english_name' => 'BlackJack MH Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100310', 
				'game_name' => '_json:{"1":"Book of Dead Mobile","2":"Book of Dead Mobile"}', 
				'english_name' => 'Book of Dead Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100057', 
				'game_name' => '_json:{"1":"Casino Hold’em Mobile","2":"Casino Hold’em Mobile"}', 
				'english_name' => 'Casino Hold’em Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100035', 
				'game_name' => '_json:{"1":"Casino Stud Poker Mobile","2":"Casino Stud Poker Mobile"}', 
				'english_name' => 'Casino Stud Poker Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100277', 
				'game_name' => '_json:{"1":"Chinese New Year Mobile","2":"Chinese New Year Mobile"}', 
				'english_name' => 'Chinese New Year Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100300', 
				'game_name' => '_json:{"1":"Cloud Quest","2":"Cloud Quest"}', 
				'english_name' => 'Cloud Quest',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100284', 
				'game_name' => '_json:{"1":"Crazy Cows Mobile","2":"Crazy Cows Mobile"}', 
				'english_name' => 'Crazy Cows Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100275', 
				'game_name' => '_json:{"1":"Deuces & Joker","2":"Deuces & Joker"}', 
				'english_name' => 'Deuces & Joker',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100270', 
				'game_name' => '_json:{"1":"Deuces Wild MH Mobile","2":"Deuces Wild MH Mobile"}', 
				'english_name' => 'Deuces Wild MH Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100274', 
				'game_name' => '_json:{"1":"Double Bonus","2":"Double Bonus"}', 
				'english_name' => 'Double Bonus',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100054', 
				'game_name' => '_json:{"1":"Double Exposure Mobile","2":"Double Exposure Mobile"}', 
				'english_name' => 'Double Exposure Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100238', 
				'game_name' => '_json:{"1":"Dragon Ship Mobile","2":"Dragon Ship Mobile"}', 
				'english_name' => 'Dragon Ship Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100293', 
				'game_name' => '_json:{"1":"Easter Eggs Mobile","2":"Easter Eggs Mobile"}', 
				'english_name' => 'Easter Eggs Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100259', 
				'game_name' => '_json:{"1":"Enchanted Crystals Mobile","2":"Enchanted Crystals Mobile"}', 
				'english_name' => 'Enchanted Crystals Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100225', 
				'game_name' => '_json:{"1":"Enchanted Meadow Mobile","2":"Enchanted Meadow Mobile"}', 
				'english_name' => 'Enchanted Meadow Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100262', 
				'game_name' => '_json:{"1":"Energoonz Mobile","2":"Energoonz Mobile"}', 
				'english_name' => 'Energoonz Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100053', 
				'game_name' => '_json:{"1":"European Blackjack Mobile","2":"European Blackjack Mobile"}', 
				'english_name' => 'European Blackjack Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100031', 
				'game_name' => '_json:{"1":"European Roulette Mobile","2":"European Roulette Mobile"}', 
				'english_name' => 'European Roulette Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100297', 
				'game_name' => '_json:{"1":"Eye of the Kraken Mobile","2":"Eye of the Kraken Mobile"}', 
				'english_name' => 'Eye of the Kraken Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100307', 
				'game_name' => '_json:{"1":"Fire Joker","2":"Fire Joker"}', 
				'english_name' => 'Fire Joker',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100196', 
				'game_name' => '_json:{"1":"Fortune Teller Mobile","2":"Fortune Teller Mobile"}', 
				'english_name' => 'Fortune Teller Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100043', 
				'game_name' => '_json:{"1":"Fruit Bonanza Mobile","2":"Fruit Bonanza Mobile"}', 
				'english_name' => 'Fruit Bonanza Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100286', 
				'game_name' => '_json:{"1":"GEMiX Mobile","2":"GEMiX Mobile"}', 
				'english_name' => 'GEMiX Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100107', 
				'game_name' => '_json:{"1":"Gift Shop Mobile","2":"Gift Shop Mobile"}', 
				'english_name' => 'Gift Shop Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100246', 
				'game_name' => '_json:{"1":"Gold Trophy 2 Mobile","2":"Gold Trophy 2 Mobile"}', 
				'english_name' => 'Gold Trophy 2 Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100312', 
				'game_name' => '_json:{"1":"Golden Caravan","2":"Golden Caravan"}', 
				'english_name' => 'Golden Caravan',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100108', 
				'game_name' => '_json:{"1":"Golden Goal Mobile","2":"Golden Goal Mobile"}', 
				'english_name' => 'Golden Goal Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100290', 
				'game_name' => '_json:{"1":"Golden Legend Mobile","2":"Golden Legend Mobile"}', 
				'english_name' => 'Golden Legend Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100285', 
				'game_name' => '_json:{"1":"Golden Ticket Mobile","2":"Golden Ticket Mobile"}', 
				'english_name' => 'Golden Ticket Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100305', 
				'game_name' => '_json:{"1":"Happy Halloween Mobile","2":"Happy Halloween Mobile"}', 
				'english_name' => 'Happy Halloween Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100094', 
				'game_name' => '_json:{"1":"Hole-in-One Mobile","2":"Hole-in-One Mobile"}', 
				'english_name' => 'Hole-in-One Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100200', 
				'game_name' => '_json:{"1":"Irish Gold Mobile","2":"Irish Gold Mobile"}', 
				'english_name' => 'Irish Gold Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100276', 
				'game_name' => '_json:{"1":"Jackpot Poker Mobile","2":"Jackpot Poker Mobile"}', 
				'english_name' => 'Jackpot Poker Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100269', 
				'game_name' => '_json:{"1":"Jacks or Better MH Mobile","2":"Jacks or Better MH Mobile"}', 
				'english_name' => 'Jacks or Better MH Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100242', 
				'game_name' => '_json:{"1":"Jewel Box Mobile","2":"Jewel Box Mobile"}', 
				'english_name' => 'Jewel Box Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100271', 
				'game_name' => '_json:{"1":"Joker Poker MH Mobile","2":"Joker Poker MH Mobile"}', 
				'english_name' => 'Joker Poker MH Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100040', 
				'game_name' => '_json:{"1":"Jolly Roger Mobile","2":"Jolly Roger Mobile"}', 
				'english_name' => 'Jolly Roger Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100239', 
				'game_name' => '_json:{"1":"Keno Mobile","2":"Keno Mobile"}', 
				'english_name' => 'Keno Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100272', 
				'game_name' => '_json:{"1":"Kings or Better","2":"Kings or Better"}', 
				'english_name' => 'Kings or Better',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100278', 
				'game_name' => '_json:{"1":"Lady of Fortune Mobile","2":"Lady of Fortune Mobile"}', 
				'english_name' => 'Lady of Fortune Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100251', 
				'game_name' => '_json:{"1":"Leprechaun goes Egypt Mobile","2":"Leprechaun goes Egypt Mobile"}', 
				'english_name' => 'Leprechaun goes Egypt Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100005', 
				'game_name' => '_json:{"1":"Lucky Diamonds Mobile","2":"Lucky Diamonds Mobile"}', 
				'english_name' => 'Lucky Diamonds Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100288', 
				'game_name' => '_json:{"1":"Merry Xmas Mobile","2":"Merry Xmas Mobile"}', 
				'english_name' => 'Merry Xmas Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100011', 
				'game_name' => '_json:{"1":"Mini Baccarat Mobile","2":"Mini Baccarat Mobile"}', 
				'english_name' => 'Mini Baccarat Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100318', 
				'game_name' => '_json:{"1":"Money Wheel","2":"Money Wheel"}', 
				'english_name' => 'Money Wheel',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100283', 
				'game_name' => '_json:{"1":"Mystery Joker Mobile","2":"Mystery Joker Mobile"}', 
				'english_name' => 'Mystery Joker Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100245', 
				'game_name' => '_json:{"1":"Myth Mobile","2":"Myth Mobile"}', 
				'english_name' => 'Myth Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100253', 
				'game_name' => '_json:{"1":"Ninja Fruits Mobile","2":"Ninja Fruits Mobile"}', 
				'english_name' => 'Ninja Fruits Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100058', 
				'game_name' => '_json:{"1":"Pai Gow Poker Mobile","2":"Pai Gow Poker Mobile"}', 
				'english_name' => 'Pai Gow Poker Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100241', 
				'game_name' => '_json:{"1":"Pearl Lagoon Mobile","2":"Pearl Lagoon Mobile"}', 
				'english_name' => 'Pearl Lagoon Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100282', 
				'game_name' => '_json:{"1":"Pearls of India Mobile","2":"Pearls of India Mobile"}', 
				'english_name' => 'Pearls of India Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100197', 
				'game_name' => '_json:{"1":"Photo Safari Mobile","2":"Photo Safari Mobile"}', 
				'english_name' => 'Photo Safari Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100291', 
				'game_name' => '_json:{"1":"Pimped Mobile","2":"Pimped Mobile"}', 
				'english_name' => 'Pimped Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100257', 
				'game_name' => '_json:{"1":"Rage to Riches Mobile","2":"Rage to Riches Mobile"}', 
				'english_name' => 'Rage to Riches Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100237', 
				'game_name' => '_json:{"1":"Riches of RA Mobile","2":"Riches of RA Mobile"}', 
				'english_name' => 'Riches of RA Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100298', 
				'game_name' => '_json:{"1":"Royal Masquerade Mobile","2":"Royal Masquerade Mobile"}', 
				'english_name' => 'Royal Masquerade Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100311', 
				'game_name' => '_json:{"1":"Sails of Gold","2":"Sails of Gold"}', 
				'english_name' => 'Sails of Gold',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100304', 
				'game_name' => '_json:{"1":"Samba Carnival Mobile","2":"Samba Carnival Mobile"}', 
				'english_name' => 'Samba Carnival Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100093', 
				'game_name' => '_json:{"1":"Scratch Ahoy Mobile","2":"Scratch Ahoy Mobile"}', 
				'english_name' => 'Scratch Ahoy Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100055', 
				'game_name' => '_json:{"1":"Single Deck Blackjack Mobile","2":"Single Deck Blackjack Mobile"}', 
				'english_name' => 'Single Deck Blackjack Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100198', 
				'game_name' => '_json:{"1":"Space Race Mobile","2":"Space Race Mobile"}', 
				'english_name' => 'Space Race Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100106', 
				'game_name' => '_json:{"1":"Speed Cash Mobile","2":"Speed Cash Mobile"}', 
				'english_name' => 'Speed Cash Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100292', 
				'game_name' => '_json:{"1":"Spin Party Mobile","2":"Spin Party Mobile"}', 
				'english_name' => 'Spin Party Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100273', 
				'game_name' => '_json:{"1":"Tens or Better","2":"Tens or Better"}', 
				'english_name' => 'Tens or Better',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100287', 
				'game_name' => '_json:{"1":"Tower Quest Mobile","2":"Tower Quest Mobile"}', 
				'english_name' => 'Tower Quest Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100235', 
				'game_name' => '_json:{"1":"Triple Chance HiLo Mobile","2":"Triple Chance HiLo Mobile"}', 
				'english_name' => 'Triple Chance HiLo Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100250', 
				'game_name' => '_json:{"1":"Wild Blood Mobile","2":"Wild Blood Mobile"}', 
				'english_name' => 'Wild Blood Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100004', 
				'game_name' => '_json:{"1":"Wild Melon Mobile","2":"Wild Melon Mobile"}', 
				'english_name' => 'Wild Melon Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100294', 
				'game_name' => '_json:{"1":"Wild North Mobile","2":"Wild North Mobile"}', 
				'english_name' => 'Wild North Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100302', 
				'game_name' => '_json:{"1":"Wizard of Gems Mobile","2":"Wizard of Gems Mobile"}', 
				'english_name' => 'Wizard of Gems Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '100309', 
				'game_name' => '_json:{"1":"Xmas Joker Mobile","2":"Xmas Joker Mobile"}', 
				'english_name' => 'Xmas Joker Mobile',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => 'Game', 
				'game_name' => '_json:{"1":"ID	Game Name","2":"ID	Game Name"}', 
				'english_name' => 'ID	Game Name',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '199', 
				'game_name' => '_json:{"1":"5x Magic","2":"5x Magic"}', 
				'english_name' => '5x Magic',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '99', 
				'game_name' => '_json:{"1":"Ace of Spades","2":"Ace of Spades"}', 
				'english_name' => 'Ace of Spades',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '243', 
				'game_name' => '_json:{"1":"Aztec Idols","2":"Aztec Idols"}', 
				'english_name' => 'Aztec Idols',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '301', 
				'game_name' => '_json:{"1":"Aztec Princess","2":"Aztec Princess"}', 
				'english_name' => 'Aztec Princess',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '34', 
				'game_name' => '_json:{"1":"Beat Me","2":"Beat Me"}', 
				'english_name' => 'Beat Me',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '105', 
				'game_name' => '_json:{"1":"Bell of Fortune","2":"Bell of Fortune"}', 
				'english_name' => 'Bell of Fortune',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '52', 
				'game_name' => '_json:{"1":"BlackJack MH","2":"BlackJack MH"}', 
				'english_name' => 'BlackJack MH',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '310', 
				'game_name' => '_json:{"1":"Book of Dead","2":"Book of Dead"}', 
				'english_name' => 'Book of Dead',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '57', 
				'game_name' => '_json:{"1":"Casino Hold’em","2":"Casino Hold’em"}', 
				'english_name' => 'Casino Hold’em',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '35', 
				'game_name' => '_json:{"1":"Casino Stud Poker","2":"Casino Stud Poker"}', 
				'english_name' => 'Casino Stud Poker',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '193', 
				'game_name' => '_json:{"1":"Cats and Cash","2":"Cats and Cash"}', 
				'english_name' => 'Cats and Cash',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '277', 
				'game_name' => '_json:{"1":"Chinese New Year","2":"Chinese New Year"}', 
				'english_name' => 'Chinese New Year',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '300', 
				'game_name' => '_json:{"1":"Cloud Quest","2":"Cloud Quest"}', 
				'english_name' => 'Cloud Quest',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '194', 
				'game_name' => '_json:{"1":"Cops’n’Robbers","2":"Cops’n’Robbers"}', 
				'english_name' => 'Cops’n’Robbers',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '284', 
				'game_name' => '_json:{"1":"Crazy Cows","2":"Crazy Cows"}', 
				'english_name' => 'Crazy Cows',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '275', 
				'game_name' => '_json:{"1":"Deuces & Joker","2":"Deuces & Joker"}', 
				'english_name' => 'Deuces & Joker',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '270', 
				'game_name' => '_json:{"1":"Deuces Wild MH","2":"Deuces Wild MH"}', 
				'english_name' => 'Deuces Wild MH',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '274', 
				'game_name' => '_json:{"1":"Double Bonus","2":"Double Bonus"}', 
				'english_name' => 'Double Bonus',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '54', 
				'game_name' => '_json:{"1":"Double Exposure BlackJack MH","2":"Double Exposure BlackJack MH"}', 
				'english_name' => 'Double Exposure BlackJack MH',
			)
			,
			array(
				'game_platform_id' => 51, 
				'game_code' => '238', 
				'game_name' => '_json:{"1":"Dragon Ship","2":"Dragon Ship"}', 
				'english_name' => 'Dragon Ship',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '293', 
				'game_name' => '_json:{"1":"Easter Eggs","2":"Easter Eggs"}', 
				'english_name' => 'Easter Eggs',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '259', 
				'game_name' => '_json:{"1":"Enchanted Crystals","2":"Enchanted Crystals"}', 
				'english_name' => 'Enchanted Crystals',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '225', 
				'game_name' => '_json:{"1":"Enchanted Meadow","2":"Enchanted Meadow"}', 
				'english_name' => 'Enchanted Meadow',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '262', 
				'game_name' => '_json:{"1":"Energoonz","2":"Energoonz"}', 
				'english_name' => 'Energoonz',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '32', 
				'game_name' => '_json:{"1":"English Roulette","2":"English Roulette"}', 
				'english_name' => 'English Roulette',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '81', 
				'game_name' => '_json:{"1":"English Roulette La Partage","2":"English Roulette La Partage"}', 
				'english_name' => 'English Roulette La Partage',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '53', 
				'game_name' => '_json:{"1":"European BlackJack MH","2":"European BlackJack MH"}', 
				'english_name' => 'European BlackJack MH',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '31', 
				'game_name' => '_json:{"1":"European Roulette","2":"European Roulette"}', 
				'english_name' => 'European Roulette',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '80', 
				'game_name' => '_json:{"1":"European Roulette La Partage","2":"European Roulette La Partage"}', 
				'english_name' => 'European Roulette La Partag
			e',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '297', 
				'game_name' => '_json:{"1":"Eye of the Kraken","2":"Eye of the Kraken"}', 
				'english_name' => 'Eye of the Kraken',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '307', 
				'game_name' => '_json:{"1":"Fire Joker","2":"Fire Joker"}', 
				'english_name' => 'Fire Joker',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '196', 
				'game_name' => '_json:{"1":"Fortune Teller","2":"Fortune Teller"}', 
				'english_name' => 'Fortune Teller',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '33', 
				'game_name' => '_json:{"1":"French Roulette","2":"French Roulette"}', 
				'english_name' => 'French Roulette',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '33', 
				'game_name' => '_json:{"1":"French Roulette La Partage","2":"French Roulette La Partage"}', 
				'english_name' => 'French Roulette La Partage',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '43', 
				'game_name' => '_json:{"1":"Fruit Bonanza","2":"Fruit Bonanza"}', 
				'english_name' => 'Fruit Bonanza',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '286', 
				'game_name' => '_json:{"1":"GEMiX","2":"GEMiX"}', 
				'english_name' => 'GEMiX',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '107', 
				'game_name' => '_json:{"1":"Gift Shop","2":"Gift Shop"}', 
				'english_name' => 'Gift Shop',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '246', 
				'game_name' => '_json:{"1":"Gold Trophy 2","2":"Gold Trophy 2"}', 
				'english_name' => 'Gold Trophy 2',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '312', 
				'game_name' => '_json:{"1":"Golden Caravan","2":"Golden Caravan"}', 
				'english_name' => 'Golden Caravan',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '108', 
				'game_name' => '_json:{"1":"Golden Goal","2":"Golden Goal"}', 
				'english_name' => 'Golden Goal',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '290', 
				'game_name' => '_json:{"1":"Golden Legend","2":"Golden Legend"}', 
				'english_name' => 'Golden Legend',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '285', 
				'game_name' => '_json:{"1":"Golden Ticket","2":"Golden Ticket"}', 
				'english_name' => 'Golden Ticket',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '244', 
				'game_name' => '_json:{"1":"Gunslinger","2":"Gunslinger"}', 
				'english_name' => 'Gunslinger',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '305', 
				'game_name' => '_json:{"1":"Happy Halloween","2":"Happy Halloween"}', 
				'english_name' => 'Happy Halloween',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '94', 
				'game_name' => '_json:{"1":"Hole-in-one","2":"Hole-in-one"}', 
				'english_name' => 'Hole-in-one',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '200', 
				'game_name' => '_json:{"1":"Irish Gold","2":"Irish Gold"}', 
				'english_name' => 'Irish Gold',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '276', 
				'game_name' => '_json:{"1":"Jackpot Poker","2":"Jackpot Poker"}', 
				'english_name' => 'Jackpot Poker',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '269', 
				'game_name' => '_json:{"1":"Jacks or Better MH","2":"Jacks or Better MH"}', 
				'english_name' => 'Jacks or Better MH',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '242', 
				'game_name' => '_json:{"1":"Jewel Box","2":"Jewel Box"}', 
				'english_name' => 'Jewel Box',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '271', 
				'game_name' => '_json:{"1":"Joker Poker MH","2":"Joker Poker MH"}', 
				'english_name' => 'Joker Poker MH',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '40', 
				'game_name' => '_json:{"1":"Jolly Roger","2":"Jolly Roger"}', 
				'english_name' => 'Jolly Roger',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '272', 
				'game_name' => '_json:{"1":"Kings of Better","2":"Kings of Better"}', 
				'english_name' => 'Kings of Better',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '278', 
				'game_name' => '_json:{"1":"Lady of Fortune","2":"Lady of Fortune"}', 
				'english_name' => 'Lady of Fortune',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '251', 
				'game_name' => '_json:{"1":"Leprechaun goes Egypt","2":"Leprechaun goes Egypt"}', 
				'english_name' => 'Leprechaun goes Egypt',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '5', 
				'game_name' => '_json:{"1":"Lucky Diamonds","2":"Lucky Diamonds"}', 
				'english_name' => 'Lucky Diamonds',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '288', 
				'game_name' => '_json:{"1":"Merry Xmas","2":"Merry Xmas"}', 
				'english_name' => 'Merry Xmas',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '11', 
				'game_name' => '_json:{"1":"Mini Baccarat","2":"Mini Baccarat"}', 
				'english_name' => 'Mini Baccarat',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '283', 
				'game_name' => '_json:{"1":"Mystery Joker","2":"Mystery Joker"}', 
				'english_name' => 'Mystery Joker',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '245', 
				'game_name' => '_json:{"1":"Myth","2":"Myth"}', 
				'english_name' => 'Myth',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '253', 
				'game_name' => '_json:{"1":"Ninja Fruits","2":"Ninja Fruits"}', 
				'english_name' => 'Ninja Fruits',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '58', 
				'game_name' => '_json:{"1":"Pai Gow Poker","2":"Pai Gow Poker"}', 
				'english_name' => 'Pai Gow Poker',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '241', 
				'game_name' => '_json:{"1":"Pearl Lagoon","2":"Pearl Lagoon"}', 
				'english_name' => 'Pearl Lagoon',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '282', 
				'game_name' => '_json:{"1":"Pearls of India","2":"Pearls of India"}', 
				'english_name' => 'Pearls of India',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '197', 
				'game_name' => '_json:{"1":"Photo Safari","2":"Photo Safari"}', 
				'english_name' => 'Photo Safari',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '291', 
				'game_name' => '_json:{"1":"Pimped","2":"Pimped"}', 
				'english_name' => 'Pimped',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '257', 
				'game_name' => '_json:{"1":"Rage to Riches","2":"Rage to Riches"}', 
				'english_name' => 'Rage to Riches',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '237', 
				'game_name' => '_json:{"1":"Riches of RA","2":"Riches of RA"}', 
				'english_name' => 'Riches of RA',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '298', 
				'game_name' => '_json:{"1":"Royal Masquerade","2":"Royal Masquerade"}', 
				'english_name' => 'Royal Masquerade',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '311', 
				'game_name' => '_json:{"1":"Sails of Gold","2":"Sails of Gold"}', 
				'english_name' => 'Sails of Gold',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '304', 
				'game_name' => '_json:{"1":"Samba Carnival","2":"Samba Carnival"}', 
				'english_name' => 'Samba Carnival',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '93', 
				'game_name' => '_json:{"1":"Scratch Ahoy","2":"Scratch Ahoy"}', 
				'english_name' => 'Scratch Ahoy',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '55', 
				'game_name' => '_json:{"1":"Single Deck BlackJack MH","2":"Single Deck BlackJack MH"}', 
				'english_name' => 'Single Deck BlackJack MH',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '198', 
				'game_name' => '_json:{"1":"Space Race","2":"Space Race"}', 
				'english_name' => 'Space Race',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '106', 
				'game_name' => '_json:{"1":"Speed Cash","2":"Speed Cash"}', 
				'english_name' => 'Speed Cash',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '292', 
				'game_name' => '_json:{"1":"Spin Party","2":"Spin Party"}', 
				'english_name' => 'Spin Party',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '273', 
				'game_name' => '_json:{"1":"Tens or Better","2":"Tens or Better"}', 
				'english_name' => 'Tens or Better',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '287', 
				'game_name' => '_json:{"1":"Tower Quest","2":"Tower Quest"}', 
				'english_name' => 'Tower Quest',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '235', 
				'game_name' => '_json:{"1":"Triple Chance HiLo","2":"Triple Chance HiLo"}', 
				'english_name' => 'Triple Chance HiLo',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '250', 
				'game_name' => '_json:{"1":"Wild Blood","2":"Wild Blood"}', 
				'english_name' => 'Wild Blood',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '4', 
				'game_name' => '_json:{"1":"Wild Melon","2":"Wild Melon"}', 
				'english_name' => 'Wild Melon',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '294', 
				'game_name' => '_json:{"1":"Wild North","2":"Wild North"}', 
				'english_name' => 'Wild North',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '302', 
				'game_name' => '_json:{"1":"Wizard of Gems","2":"Wizard of Gems"}', 
				'english_name' => 'Wizard of Gems',
			),
			array(
				'game_platform_id' => 51, 
				'game_code' => '309', 
				'game_name' => '_json:{"1":"Xmas Joker","2":"Xmas Joker"}', 
				'english_name' => 'Xmas Joker',
			),
		);

		$this->db->where('game_platform_id', FG_API);
		$this->db->update_batch('game_description', $game_descriptions, 'game_code');

		$this->db->trans_complete();
	}

	public function down() {
	}
}
