delete from player;
delete from playeraccount;
delete from transactions;
delete from manualthirdpartydepositdetails;
delete from otcpaymentmethoddetails;
delete from ptplayertransactiondetails;
delete from localbankdepositdetails;
delete from manualthirdpartydepositdetails;
delete from sale_orders;
delete from affiliates;
delete from affiliatepayout;
delete from affiliatepaymenthistory;
delete from affiliatepayment;
delete from affiliate_stats;
delete from affiliateoptions;
delete from affiliatetag;
delete from balanceadjustmenthistory;
delete from bankaccountplayerlevellimit;
delete from bankcompensationfeehistory;
delete from batch;
delete from game_provider_auth;
delete from gameapirecord;
delete from games_report;
delete from http_request;
-- delete from income_report;
delete from issuereportptapi;
delete from localbankdepositdetails;
delete from localbankwithdrawaldetails;
delete from logs;
delete from manualthirdpartydepositdetails;
delete from player_level_history;
delete from player_level_history_allowed_games;
delete from player_level_history_game_api_details;
delete from player_report;
delete from playerbankdetails;
delete from playerbankhistory;
delete from playercashback;
delete from playerdetails;
delete from playerfriendreferral;
delete from playergame;
delete from playergamehistory;
delete from playergamehistorydetails;
delete from playergameprofile;
delete from playerlevel;
delete from playerpromo;
delete from playertag;
delete from playerupdatehistory;
delete from ptplayertransactiondetails;
delete from response_results;
delete from subwalletdetails;
delete from summary_report;
delete from traffic_stats;
delete from walletaccount;
delete from withdraw_conditions;
delete from withdrawaldetails;
delete from adminusers where userId!=1;
delete from roles where roleId!=1;
delete from rolefunctions where roleId!=1;
delete from rolefunctions_giving where roleId!=1;
delete from promocmssetting where promoName!='_SYSTEM_MANUAL';
delete from promorules where promoName!='_SYSTEM_MANUAL';
delete from promotype where promoTypeName!='_SYSTEM_MANUAL';
delete from promorulesallowedplayerlevel;
delete from promorulesgamebetrule;
delete from promorulesgametype;
delete from report_logs;
