<?php

defined('BASEPATH') OR exit('No direct script access allowed');

class Migration_add_rows_to_game_description_20151009 extends CI_Migration {

	public function up() {
		// $this->db->query("INSERT INTO `game_description`
		// 								(`id`,
		// 								 `game_platform_id`,
		// 								 `game_type_id`,
		// 								 `game_name`,
		// 								 `game_code`,
		// 								 `dlc_enabled`,
		// 								 `progressive`,
		// 								 `flash_enabled`,
		// 								 `mobile_enabled`,
		// 								 `note`,
		// 								 `status`,
		// 								 `flag_show_in_site`,
		// 								 `no_cash_back`,
		// 								 `void_bet`,
		// 								 `attributes`,
		// 								 `game_order`,
		// 								 `html_five_enabled`
		// 								 )
		// 				  VALUES
		// 					('', 6, 15,'mg.acesAndEights','acesAndEights','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 15,'mg.acesAndFaces','acesAndFaces','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 15,'mg.bonusDeucesWild','bonusDeucesWild','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 15,'mg.deucesWild','deucesWild','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 15,'mg.doubleDoubleBonus','doubleDoubleBonus','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 13,'mg.europeanRoulette','europeanRoulette','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 15,'mg.jacksOrBetter','jacksOrBetter','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.mermaidsMillions','mermaidsMillions','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.thunderstruck','thunderstruck','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.tombRaider','tombRaider','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 13,'mg.europeanBlackjackGold','europeanBlackjackGold','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.ladiesNite','ladiesNite','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.springBreak','springBreak','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.avalon','avalon','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.agentJaneBlonde','agentJaneBlonde','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.burningDesire','burningDesire','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.deckTheHalls','deckTheHalls','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.adventurePalace','adventurePalace','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.tallyHo','tallyHo','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 16,'mg.cashSplash','cashSplash','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 16,'mg.majorMillions','majorMillions','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.loaded','loaded','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.breakDaBankAgain','breakDaBankAgain','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 16,'mg.treasureNile','treasureNile','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.cashapillar','cashapillar','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.alaskanFishing','alaskanFishing','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.stashOfTheTitans','stashOfTheTitans','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.carnaval','carnaval','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.voila','voila','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.lionsPride','lionsPride','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.bigTop','bigTop','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.breakDaBank','breakDaBank','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.purePlatinum','purePlatinum','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.5ReelDrive','5ReelDrive','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.couchPotato','couchPotato','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.halloweenies','halloweenies','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.whatAHoot','whatAHoot','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.thunderstruckII','thunderstruckII','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.reelThunder','reelThunder','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.isis','isis','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.centreCourt','centreCourt','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.theTwistedCircus','theTwistedCircus','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.starlightKiss','starlightKiss','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.mayanPrincess','mayanPrincess','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.tigersEye','tigersEye','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.eaglesWings','eaglesWings','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.highSociety','highSociety','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.hitman','hitman','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.footballStar','footballStar','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.treasurePalace','treasurePalace','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.beachBabes','beachBabes','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.madHatters','madHatters','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.theGrandJourney','theGrandJourney','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.kathmandu','kathmandu','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.summertime','summertime','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.silverfang','silverfang','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.mysticDreams','mysticDreams','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.bushTelegraph','bushTelegraph','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.ageOfDiscovery','ageOfDiscovery','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 13,'mg.classicBlackjackGold','classicBlackjackGold','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.barsNStripes','barsNStripes','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 13,'mg.atlanticCityBlackjackGold','atlanticCityBlackjackGold','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.rivieraRiches','rivieraRiches','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.santaPaws','santaPaws','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.bigKahuna','bigKahuna','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.sureWin','sureWin','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 13,'mg.vegasDowntownBlackjackGold','vegasDowntownBlackjackGold','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 13,'mg.vegasSingleDeckBlackjackGold','vegasSingleDeckBlackjackGold','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.cricketStar','cricketStar','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.secretAdmirer','secretAdmirer','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 13,'mg.vegasStripBlackjackGold','vegasStripBlackjackGold','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.luckyLeprechaun','luckyLeprechaun','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.rhymingReelsGeorgiePorgie','rhymingReelsGeorgiePorgie','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.harveys','harveys','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.boogieMonsters','boogieMonsters','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.liquidGold','liquidGold','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.dragonsMyth','dragonsMyth','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.coolWolf','coolWolf','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.breakAway','breakAway','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.ariana','ariana','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.cashville','cashville','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.fishParty','fishParty','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.kingsOfCash','kingsOfCash','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.summerHoliday','summerHoliday','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.supeItUp','supeItUp','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.partyIsland','partyIsland','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 13,'mg.americanRouletteGold','americanRouletteGold','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.asianBeauty','asianBeauty','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.bridesmaids','bridesmaids','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.sterlingSilver','sterlingSilver','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1),
		// 					('', 6, 14,'mg.rugbyStar','','',NULL,1,'',NULL,1,1,NULL,NULL,NULL,NULL,1)
		// 					;
		// 				");
	}

	public function down() {
		// $this->db->query('DELETE FROM game_description WHERE game_platform_id = 6');
	}
}