<?php

defined('BASEPATH') OR exit('No direct script access allowed');

class Migration_add_bbin_to_game_description_201511120203 extends CI_Migration {
	const GAMETYPE_SPORT_GAMES = 33;
	const GAMETYPE_LOTTERY_GAMES = 34;
	const GAMETYPE_3DHALL_GAMES = 35;
	const GAMETYPE_LIVE_GAMES = 36;
	const GAMETYPE_CASINO_GAMES = 37;
	const FLAG_TRUE = true;
	public function up() {

		//check config first
		// $sys = $this->config->item('external_system_map');
		// // if (array_key_exists(BBIN_API, $sys)) {
		// $this->db->trans_start();

		// $data = array(
		// 	//----------- GAMETYPE_SPORT_GAMES ------------------//

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_SPORT_GAMES,
		// 		'game_name' => 'bbin.Basketball',
		// 		'english_name' => 'Basketball',
		// 		'external_game_id' => 'BS',
		// 		'game_code' => 'BK',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_SPORT_GAMES,
		// 		'game_name' => 'bbin.Baseball',
		// 		'english_name' => 'Baseball',
		// 		'external_game_id' => 'BS',
		// 		'game_code' => 'BS',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_SPORT_GAMES,
		// 		'game_name' => 'bbin.Other',
		// 		'english_name' => 'Other',
		// 		'external_game_id' => 'F1',
		// 		'game_code' => 'F1',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_SPORT_GAMES,
		// 		'game_name' => 'bbin.Football',
		// 		'english_name' => 'Football',
		// 		'external_game_id' => 'FB',
		// 		'game_code' => 'FB',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_SPORT_GAMES,
		// 		'game_name' => 'bbin.Soccer',
		// 		'english_name' => 'Soccer',
		// 		'external_game_id' => 'FT',
		// 		'game_code' => 'FT',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_SPORT_GAMES,
		// 		'game_name' => 'bbin.Stock',
		// 		'english_name' => 'Stock',
		// 		'external_game_id' => 'FU',
		// 		'game_code' => 'FU',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_SPORT_GAMES,
		// 		'game_name' => 'bbin.IceHockey',
		// 		'english_name' => 'IceHockey',
		// 		'external_game_id' => 'IH',
		// 		'game_code' => 'IH',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_SPORT_GAMES,
		// 		'game_name' => 'bbin.SpeciallyGames',
		// 		'english_name' => 'Specially Games',
		// 		'external_game_id' => 'SP',
		// 		'game_code' => 'SP',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_SPORT_GAMES,
		// 		'game_name' => 'bbin.Tennis',
		// 		'english_name' => 'Tennis',
		// 		'external_game_id' => 'TN',
		// 		'game_code' => 'TN',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	//----------- GAMETYPE_LOTTERY_GAMES ------------------//

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_LOTTERY_GAMES,
		// 		'game_name' => 'bbin.MarkSix',
		// 		'english_name' => 'Mark Six',
		// 		'external_game_id' => 'LT',
		// 		'game_code' => 'LT',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_LOTTERY_GAMES,
		// 		'game_name' => 'bbin.MarkSix',
		// 		'english_name' => 'Mark Six',
		// 		'external_game_id' => 'LT',
		// 		'game_code' => 'LT',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_LOTTERY_GAMES,
		// 		'game_name' => 'bbin.3DLotto',
		// 		'english_name' => '3D Lotto',
		// 		'external_game_id' => 'D3',
		// 		'game_code' => 'D3',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_LOTTERY_GAMES,
		// 		'game_name' => 'bbin.SportsLotto',
		// 		'english_name' => 'Sports Lotto',
		// 		'external_game_id' => 'P3',
		// 		'game_code' => 'P3',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_LOTTERY_GAMES,
		// 		'game_name' => 'bbin.BB3D',
		// 		'english_name' => 'BB3D',
		// 		'external_game_id' => 'BT',
		// 		'game_code' => 'BT',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_LOTTERY_GAMES,
		// 		'game_name' => 'bbin.ShanghaiLotto',
		// 		'english_name' => 'Shanghai Lotto',
		// 		'external_game_id' => 'T3',
		// 		'game_code' => 'T3',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_LOTTERY_GAMES,
		// 		'game_name' => 'bbin.ChongqingLotto',
		// 		'english_name' => 'Chongqing Lotto',
		// 		'external_game_id' => 'CQ',
		// 		'game_code' => 'CQ',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_LOTTERY_GAMES,
		// 		'game_name' => 'bbin.JiangxiLotto',
		// 		'english_name' => 'Jiangxi Lotto',
		// 		'external_game_id' => 'JX',
		// 		'game_code' => 'JX',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_LOTTERY_GAMES,
		// 		'game_name' => 'bbin.TianjinLotto',
		// 		'english_name' => 'Tianjin Lotto',
		// 		'external_game_id' => 'TJ',
		// 		'game_code' => 'TJ',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_LOTTERY_GAMES,
		// 		'game_name' => 'bbin.GuangxiHappy10',
		// 		'english_name' => 'Guangxi Happy 10',
		// 		'external_game_id' => 'GXSF',
		// 		'game_code' => 'GXSF',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_LOTTERY_GAMES,
		// 		'game_name' => 'bbin.GuangdongHappy10',
		// 		'english_name' => 'Guangdong Happy 10',
		// 		'external_game_id' => 'GDSF',
		// 		'game_code' => 'GDSF',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_LOTTERY_GAMES,
		// 		'game_name' => 'bbin.TianjinHappy10',
		// 		'english_name' => 'Tianjin Happy 10',
		// 		'external_game_id' => 'TJSF',
		// 		'game_code' => 'TJSF',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_LOTTERY_GAMES,
		// 		'game_name' => 'bbin.BeijingKeno',
		// 		'english_name' => 'BC Keno',
		// 		'external_game_id' => 'CAKN',
		// 		'game_code' => 'CAKN',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_LOTTERY_GAMES,
		// 		'game_name' => 'bbin.ACTC',
		// 		'english_name' => 'ACTC',
		// 		'external_game_id' => 'AUKN',
		// 		'game_code' => 'AUKN',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_LOTTERY_GAMES,
		// 		'game_name' => 'bbin.BBKeno',
		// 		'english_name' => 'BB Keno',
		// 		'external_game_id' => 'BBKN',
		// 		'game_code' => 'BBKN',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_LOTTERY_GAMES,
		// 		'game_name' => 'bbin.BeijingPK10',
		// 		'english_name' => 'Beijing PK10',
		// 		'external_game_id' => 'BJPK',
		// 		'game_code' => 'BJPK',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_LOTTERY_GAMES,
		// 		'game_name' => 'bbin.Guangdong11/5',
		// 		'english_name' => 'Guangdong 11/5',
		// 		'external_game_id' => 'GDE5',
		// 		'game_code' => 'GDE5',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_LOTTERY_GAMES,
		// 		'game_name' => 'bbin.Chongqing11/5',
		// 		'english_name' => 'Chongqing 11/5',
		// 		'external_game_id' => 'CQE5',
		// 		'game_code' => 'CQE5',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_LOTTERY_GAMES,
		// 		'game_name' => 'bbin.Jiangxi11/5',
		// 		'english_name' => 'Jiangxi 11/5',
		// 		'external_game_id' => 'JXE5',
		// 		'game_code' => 'JXE5',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_LOTTERY_GAMES,
		// 		'game_name' => 'bbin.Shangdong11/5',
		// 		'english_name' => 'Shangdong 11/5',
		// 		'external_game_id' => 'SDE5',
		// 		'game_code' => 'SDE5',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_LOTTERY_GAMES,
		// 		'game_name' => 'bbin.BBRunningKing',
		// 		'english_name' => 'BB Running King',
		// 		'external_game_id' => 'BBRB',
		// 		'game_code' => 'BBRB',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	//----------- GAMETYPE_3DHALL_GAMES ------------------//

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_3DHALL_GAMES,
		// 		'game_name' => 'bbin.3DSexAndZen',
		// 		'english_name' => '3D Sex And Zen',
		// 		'external_game_id' => '15006',
		// 		'game_code' => '15006',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_3DHALL_GAMES,
		// 		'game_name' => 'bbin.KingOfCookery',
		// 		'english_name' => 'KingOfCookery',
		// 		'external_game_id' => '15016',
		// 		'game_code' => '15016',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_3DHALL_GAMES,
		// 		'game_name' => 'bbin.DuoBao',
		// 		'english_name' => 'DuoBao',
		// 		'external_game_id' => '15017',
		// 		'game_code' => '15017',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_3DHALL_GAMES,
		// 		'game_name' => 'bbin.Indulge243',
		// 		'english_name' => 'Indulge243',
		// 		'external_game_id' => '15018',
		// 		'game_code' => '15018',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_3DHALL_GAMES,
		// 		'game_name' => 'bbin.TheEnchantingShadow',
		// 		'english_name' => 'The Enchanting Shadow',
		// 		'external_game_id' => '15019',
		// 		'game_code' => '15019',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_3DHALL_GAMES,
		// 		'game_name' => 'bbin.Paparazzo',
		// 		'english_name' => 'Paparazzo',
		// 		'external_game_id' => '15021',
		// 		'game_code' => '15021',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_3DHALL_GAMES,
		// 		'game_name' => 'bbin.LinkGem',
		// 		'english_name' => 'LinkGem',
		// 		'external_game_id' => '15023',
		// 		'game_code' => '15023',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_3DHALL_GAMES,
		// 		'game_name' => 'bbin.2014FifaWorldCup',
		// 		'english_name' => '2014 Fifa World Cup',
		// 		'external_game_id' => '15024',
		// 		'game_code' => '15024',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	//----------- GAMETYPE_LIVE_GAMES ------------------//

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_LIVE_GAMES,
		// 		'game_name' => 'bbin.Baccarat',
		// 		'english_name' => 'Baccarat',
		// 		'external_game_id' => '3001',
		// 		'game_code' => '3001',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_LIVE_GAMES,
		// 		'game_name' => 'bbin.MahjongTiles',
		// 		'english_name' => 'Mahjong Tiles',
		// 		'external_game_id' => '3002',
		// 		'game_code' => '3002',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_LIVE_GAMES,
		// 		'game_name' => 'bbin.DragonTiger',
		// 		'english_name' => 'Dragon Tiger',
		// 		'external_game_id' => '3003',
		// 		'game_code' => '3003',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_LIVE_GAMES,
		// 		'game_name' => 'bbin.3Face',
		// 		'english_name' => '3 Face',
		// 		'external_game_id' => '3005',
		// 		'game_code' => '3005',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_LIVE_GAMES,
		// 		'game_name' => 'bbin.WenzhouPaiGow',
		// 		'english_name' => 'Wenzhou Pai Gow',
		// 		'external_game_id' => '3006',
		// 		'game_code' => '3006',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_LIVE_GAMES,
		// 		'game_name' => 'bbin.Roullete',
		// 		'english_name' => 'Roullete',
		// 		'external_game_id' => '3007',
		// 		'game_code' => '3007',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_LIVE_GAMES,
		// 		'game_name' => 'bbin.Sicbo',
		// 		'english_name' => 'Sic bo',
		// 		'external_game_id' => '3008',
		// 		'game_code' => '3008',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_LIVE_GAMES,
		// 		'game_name' => 'bbin.TexasHoldem',
		// 		'english_name' => 'Texas Hold\'em',
		// 		'external_game_id' => '3010',
		// 		'game_code' => '3010',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_LIVE_GAMES,
		// 		'game_name' => 'bbin.SeDie',
		// 		'english_name' => 'Se Die',
		// 		'external_game_id' => '3011',
		// 		'game_code' => '3011',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_LIVE_GAMES,
		// 		'game_name' => 'bbin.BullBull',
		// 		'english_name' => 'Bull Bull',
		// 		'external_game_id' => '3012',
		// 		'game_code' => '3012',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_LIVE_GAMES,
		// 		'game_name' => 'bbin.Saihonbiki',
		// 		'english_name' => 'Saihonbiki',
		// 		'external_game_id' => '3013',
		// 		'game_code' => '3013',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_LIVE_GAMES,
		// 		'game_name' => 'bbin.UnlimitedBlackjack',
		// 		'english_name' => 'Unlimited Blackjack',
		// 		'external_game_id' => '3014',
		// 		'game_code' => '3014',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	//----------- GAMETYPE_CASINO_GAMES ------------------//

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.SlotCoolFruit',
		// 		'english_name' => 'Slot Cool Fruit',
		// 		'external_game_id' => '5001',
		// 		'game_code' => '5001',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.SlotPoker',
		// 		'english_name' => 'Slot Poker',
		// 		'external_game_id' => '5002',
		// 		'game_code' => '5002',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.SlotMahjongBall',
		// 		'english_name' => 'Slot Mahjong Ball',
		// 		'external_game_id' => '5003',
		// 		'game_code' => '5003',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.SlotSoccer',
		// 		'english_name' => 'Slot Soccer',
		// 		'external_game_id' => '5004',
		// 		'game_code' => '5004',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.WestJourney',
		// 		'english_name' => 'West Journey',
		// 		'external_game_id' => '5011',
		// 		'game_code' => '5011',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.Galaxy',
		// 		'english_name' => 'Galaxy',
		// 		'external_game_id' => '5012',
		// 		'game_code' => '5012',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.Classic',
		// 		'english_name' => 'Classic',
		// 		'external_game_id' => '5013',
		// 		'game_code' => '5013',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.Jungle',
		// 		'english_name' => 'Jungle',
		// 		'external_game_id' => '5014',
		// 		'game_code' => '5014',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.Fifa2010',
		// 		'english_name' => 'Fifa 2010',
		// 		'external_game_id' => '5015',
		// 		'game_code' => '5015',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.PrehistoricJungle',
		// 		'english_name' => 'Prehistoric Jungle',
		// 		'external_game_id' => '5016',
		// 		'game_code' => '5016',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.StarWars',
		// 		'english_name' => 'Star Wars',
		// 		'external_game_id' => '5017',
		// 		'game_code' => '5017',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.MonkeyKing',
		// 		'english_name' => 'Monkey King',
		// 		'external_game_id' => '5018',
		// 		'game_code' => '5018',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.FruitParadise',
		// 		'english_name' => 'Fruit Paradise',
		// 		'external_game_id' => '5019',
		// 		'game_code' => '5019',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.TropicalFruit',
		// 		'english_name' => 'Tropical Fruit',
		// 		'external_game_id' => '5020',
		// 		'game_code' => '5020',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.TropicalFruit',
		// 		'english_name' => 'Tropical Fruit',
		// 		'external_game_id' => '5021',
		// 		'game_code' => '5021',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.7Pk',
		// 		'english_name' => '7 Card Stud Poker',
		// 		'external_game_id' => '5023',
		// 		'game_code' => '5023',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.WhiteSnake',
		// 		'english_name' => 'White Snake',
		// 		'external_game_id' => '5025',
		// 		'game_code' => '5025',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.London2012',
		// 		'english_name' => 'London 2012',
		// 		'external_game_id' => '5026',
		// 		'game_code' => '5026',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.KungFuLoung',
		// 		'english_name' => 'Kung Fu Loung',
		// 		'external_game_id' => '5027',
		// 		'game_code' => '5027',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.MoonFestivalParty',
		// 		'english_name' => 'Moon Festival Party',
		// 		'external_game_id' => '5029',
		// 		'game_code' => '5029',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.XmasParty',
		// 		'english_name' => 'X\'mas  Party',
		// 		'external_game_id' => '5029',
		// 		'game_code' => '5029',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.ChineseMammon',
		// 		'english_name' => 'Chinese Mammon',
		// 		'external_game_id' => '5030',
		// 		'game_code' => '5030',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.JokerPoker',
		// 		'english_name' => 'Joker Poker',
		// 		'external_game_id' => '5034',
		// 		'game_code' => '5034',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.CaribbeanPoker',
		// 		'english_name' => 'Caribbean Poker',
		// 		'external_game_id' => '5035',
		// 		'game_code' => '5035',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.FishPrawnCrabDice',
		// 		'english_name' => 'Fish Prawn Crab Dice',
		// 		'external_game_id' => '5039',
		// 		'game_code' => '5039',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.ZombieLand',
		// 		'english_name' => 'Zombie Land',
		// 		'external_game_id' => '5047',
		// 		'game_code' => '5047',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.SpyCrisis',
		// 		'english_name' => 'Spy Crisis',
		// 		'external_game_id' => '5048',
		// 		'game_code' => '5048',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.SexAndZen',
		// 		'english_name' => 'Sex And Zen',
		// 		'external_game_id' => '5049',
		// 		'game_code' => '5049',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.WarLady',
		// 		'english_name' => 'War Lady',
		// 		'external_game_id' => '5050',
		// 		'game_code' => '5050',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.Star97',
		// 		'english_name' => 'Star97',
		// 		'external_game_id' => '5057',
		// 		'game_code' => '5057',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.CrazyFruit',
		// 		'english_name' => 'Crazy Fruit',
		// 		'external_game_id' => '5058',
		// 		'game_code' => '5058',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.Circus',
		// 		'english_name' => 'Circus',
		// 		'external_game_id' => '5059',
		// 		'game_code' => '5059',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.FantasticAnimals5th',
		// 		'english_name' => 'Fantastic Animals 5th',
		// 		'external_game_id' => '5060',
		// 		'game_code' => '5060',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.Super7',
		// 		'english_name' => 'Super 7',
		// 		'external_game_id' => '5061',
		// 		'game_code' => '5061',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.DragonMustDie',
		// 		'english_name' => 'Dragon Must Die',
		// 		'external_game_id' => '5062',
		// 		'game_code' => '5062',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.GoldenWheel',
		// 		'english_name' => 'Golden Wheel',
		// 		'external_game_id' => '5070',
		// 		'game_code' => '5070',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.GuessTrain',
		// 		'english_name' => 'Guess Train',
		// 		'external_game_id' => '5074',
		// 		'game_code' => '5074',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.MonsterLegend',
		// 		'english_name' => 'Monster Legend',
		// 		'external_game_id' => '5075',
		// 		'game_code' => '5075',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.LuckyNumber',
		// 		'english_name' => 'Lucky Number',
		// 		'external_game_id' => '5076',
		// 		'game_code' => '5076',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.Fruit',
		// 		'english_name' => 'Fruit',
		// 		'external_game_id' => '5077',
		// 		'game_code' => '5077',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.ChessWheel',
		// 		'english_name' => 'Chess Wheel',
		// 		'external_game_id' => '5078',
		// 		'game_code' => '5078',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.3DLuckyNumber',
		// 		'english_name' => '3D Lucky Number',
		// 		'external_game_id' => '5079',
		// 		'game_code' => '5079',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.LotteryWheel',
		// 		'english_name' => 'LotteryWheel',
		// 		'external_game_id' => '5080',
		// 		'game_code' => '5080',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.CasinoWar',
		// 		'english_name' => 'Casino War',
		// 		'external_game_id' => '5088',
		// 		'game_code' => '5088',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.RedDog',
		// 		'english_name' => 'Red Dog',
		// 		'external_game_id' => '5089',
		// 		'game_code' => '5089',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.DynastyWarlord',
		// 		'english_name' => 'Dynasty Warlord',
		// 		'external_game_id' => '5091',
		// 		'game_code' => '5091',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.TheLegendAndTheHero',
		// 		'english_name' => 'The Legend and the Hero',
		// 		'external_game_id' => '5092',
		// 		'game_code' => '5092',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.JinPingMai',
		// 		'english_name' => 'Jin Ping Mai',
		// 		'external_game_id' => '5093',
		// 		'game_code' => '5093',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.JinPingMai2',
		// 		'english_name' => 'Jin Ping Mai 2',
		// 		'external_game_id' => '5094',
		// 		'game_code' => '5094',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.EuropeanRoulette',
		// 		'english_name' => 'European Roulette',
		// 		'external_game_id' => '5101',
		// 		'game_code' => '5101',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.AmericanRoulette',
		// 		'english_name' => 'American Roulette',
		// 		'external_game_id' => '5102',
		// 		'game_code' => '5102',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.JackpotRoulette',
		// 		'english_name' => 'Jackpot Roulette',
		// 		'external_game_id' => '5103',
		// 		'game_code' => '5103',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.FrenchRoulette',
		// 		'english_name' => 'French Roulette',
		// 		'external_game_id' => '5104',
		// 		'game_code' => '5104',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.ClassicBlackjack',
		// 		'english_name' => 'Classic Roulette',
		// 		'external_game_id' => '5115',
		// 		'game_code' => '5115',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.SpanishBlackjack',
		// 		'english_name' => 'Spanish Blackjack',
		// 		'external_game_id' => '5116',
		// 		'game_code' => '5116',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.VegasBlackjack',
		// 		'english_name' => 'Vegas Blackjack',
		// 		'external_game_id' => '5117',
		// 		'game_code' => '5117',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.BonusBlackjack',
		// 		'english_name' => 'Bonus Blackjack',
		// 		'external_game_id' => '5118',
		// 		'game_code' => '5118',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.RoyalTexasHoldem',
		// 		'english_name' => 'Royal Texas Hold\'em',
		// 		'external_game_id' => '5131',
		// 		'game_code' => '5131',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.FlamingMountain',
		// 		'english_name' => 'Flaming Mountain',
		// 		'external_game_id' => '5201',
		// 		'game_code' => '5201',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.PandorasBox',
		// 		'english_name' => 'Pandora\'s Box',
		// 		'external_game_id' => '5202',
		// 		'game_code' => '5202',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.ForeverLove',
		// 		'english_name' => 'Forever Love',
		// 		'external_game_id' => '5203',
		// 		'game_code' => '5203',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.2014Fifa',
		// 		'english_name' => '2014 Fifa',
		// 		'external_game_id' => '5204',
		// 		'game_code' => '5204',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.ChineseHeroLovers',
		// 		'english_name' => 'Chinese Hero Lovers',
		// 		'external_game_id' => '5401',
		// 		'game_code' => '5401',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.LetsGoNightMarket',
		// 		'english_name' => 'Let\'s Go Night-market',
		// 		'external_game_id' => '5402',
		// 		'game_code' => '5402',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.LegendOf7Swords',
		// 		'english_name' => 'Legend of 7 Swords',
		// 		'external_game_id' => '5403',
		// 		'game_code' => '5403',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.DolphinReef',
		// 		'english_name' => 'Dolphin Reef',
		// 		'external_game_id' => '5801',
		// 		'game_code' => '5801',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.Achilles',
		// 		'english_name' => 'Achilles',
		// 		'external_game_id' => '5802',
		// 		'game_code' => '5802',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.AztecsTreasure',
		// 		'english_name' => 'Aztec\'s Treasure',
		// 		'external_game_id' => '5803',
		// 		'game_code' => '5803',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.BigShot',
		// 		'english_name' => 'Big Shot',
		// 		'external_game_id' => '5804',
		// 		'game_code' => '5804',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.CaesarsEmpire',
		// 		'english_name' => 'Caesar\'s Empire',
		// 		'external_game_id' => '5805',
		// 		'game_code' => '5805',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.EnchancedGarden',
		// 		'english_name' => 'Enchanced Garden',
		// 		'external_game_id' => '5806',
		// 		'game_code' => '5806',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.OrientExpress',
		// 		'english_name' => 'Orient Express',
		// 		'external_game_id' => '5807',
		// 		'game_code' => '5807',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.Ronin',
		// 		'english_name' => 'Ronin',
		// 		'external_game_id' => '5808',
		// 		'game_code' => '5808',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.TallyHo',
		// 		'english_name' => 'Tally Ho',
		// 		'external_game_id' => '5809',
		// 		'game_code' => '5809',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.Victory',
		// 		'english_name' => 'Victory',
		// 		'external_game_id' => '5810',
		// 		'game_code' => '5810',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.ANightOut',
		// 		'english_name' => 'A Night Out',
		// 		'external_game_id' => '5811',
		// 		'game_code' => '5811',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.Football',
		// 		'english_name' => 'Football',
		// 		'external_game_id' => '5821',
		// 		'game_code' => '5821',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.PlayBunny',
		// 		'english_name' => 'Play Bunny',
		// 		'external_game_id' => '5822',
		// 		'game_code' => '5822',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.BigProsperity',
		// 		'english_name' => 'Big Prosperity',
		// 		'external_game_id' => '5823',
		// 		'game_code' => '5823',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.MysticDragon',
		// 		'english_name' => 'Mystic Dragon',
		// 		'external_game_id' => '5824',
		// 		'game_code' => '5824',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.GoldenLotus',
		// 		'english_name' => 'Golden Lotus',
		// 		'external_game_id' => '5825',
		// 		'game_code' => '5825',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.PayDirt',
		// 		'english_name' => 'Pay Dirt',
		// 		'external_game_id' => '5826',
		// 		'game_code' => '5826',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.SeaCaptain',
		// 		'english_name' => 'Sea Captain',
		// 		'external_game_id' => '5827',
		// 		'game_code' => '5827',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.TRex',
		// 		'english_name' => 'T-Rex',
		// 		'external_game_id' => '5828',
		// 		'game_code' => '5828',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.GoldenTour',
		// 		'english_name' => 'GoldenTour',
		// 		'external_game_id' => '5831',
		// 		'game_code' => '5831',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.HighwayKings',
		// 		'english_name' => 'Highway Kings',
		// 		'external_game_id' => '5832',
		// 		'game_code' => '5832',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.SilentSamurai',
		// 		'english_name' => 'Silent Samurai',
		// 		'external_game_id' => '5833',
		// 		'game_code' => '5833',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.StriperNight',
		// 		'english_name' => 'Striper Night',
		// 		'external_game_id' => '5834',
		// 		'game_code' => '5834',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.HappyGoldenOxOfHappiness',
		// 		'english_name' => 'Happy Golden Ox Of Happiness',
		// 		'external_game_id' => '5835',
		// 		'game_code' => '5835',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.TripleTwister',
		// 		'english_name' => 'Triple Twister',
		// 		'external_game_id' => '5836',
		// 		'game_code' => '5836',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => self::GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.Jackpot',
		// 		'english_name' => 'Jackpot',
		// 		'external_game_id' => '5888',
		// 		'game_code' => '5888',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),
		// );

		// $this->db->insert_batch('game_description', $data);
		// $this->db->trans_complete();
		// }
	}

	public function down() {
		// $this->db->delete('game_description', array('game_platform_id' => BBIN_API));
	}
}