<?php

defined('BASEPATH') OR exit('No direct script access allowed');

class Migration_add_188_to_game_description_201511250519 extends CI_Migration {
	const FLAG_TRUE = true;
	public function up() {

		//check config first
		// $sys = $this->config->item('external_system_map');
		// if (array_key_exists(ONE88_API, $sys)) {
		// $this->db->trans_start();

		// $data = array(
		// 	array('game_platform_id' => ONE88_API,
		// 		'game_name' => 'one88.AmericanFootball',
		// 		'english_name' => 'American Football',
		// 		'external_game_id' => 'AF',
		// 		'game_code' => 'AF',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => ONE88_API,
		// 		'game_name' => 'one88.Badminton',
		// 		'english_name' => 'Badminton',
		// 		'external_game_id' => 'BA',
		// 		'game_code' => 'BA',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => ONE88_API,
		// 		'game_name' => 'one88.Baseball',
		// 		'english_name' => 'Baseball',
		// 		'external_game_id' => 'BB',
		// 		'game_code' => 'BB',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => ONE88_API,
		// 		'game_name' => 'one88.Basketball',
		// 		'english_name' => 'Basketball',
		// 		'external_game_id' => 'BKB',
		// 		'game_code' => 'BKB',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => ONE88_API,
		// 		'game_name' => 'one88.BeachSoccer',
		// 		'english_name' => 'Beach Soccer',
		// 		'external_game_id' => 'BS',
		// 		'game_code' => 'BS',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => ONE88_API,
		// 		'game_name' => 'one88.BeachVolleyball',
		// 		'english_name' => 'Beach Volleyball',
		// 		'external_game_id' => 'BV',
		// 		'game_code' => 'BV',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => ONE88_API,
		// 		'game_name' => 'one88.BeautyPageant',
		// 		'english_name' => 'Beauty Pageant',
		// 		'external_game_id' => 'BP',
		// 		'game_code' => 'BP',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => ONE88_API,
		// 		'game_name' => 'one88.BoxingFighting',
		// 		'english_name' => 'Boxing/Fighting',
		// 		'external_game_id' => 'BF',
		// 		'game_code' => 'BF',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => ONE88_API,
		// 		'game_name' => 'one88.Cricket',
		// 		'english_name' => 'Cricket',
		// 		'external_game_id' => 'CK',
		// 		'game_code' => 'CK',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => ONE88_API,
		// 		'game_name' => 'one88.Cycling',
		// 		'english_name' => 'Cycling',
		// 		'external_game_id' => 'CY',
		// 		'game_code' => 'CY',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => ONE88_API,
		// 		'game_name' => 'one88.Darts',
		// 		'english_name' => 'Darts',
		// 		'external_game_id' => 'DA',
		// 		'game_code' => 'DA',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => ONE88_API,
		// 		'game_name' => 'one88.ESports',
		// 		'english_name' => 'E-Sports',
		// 		'external_game_id' => 'SP',
		// 		'game_code' => 'SP',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => ONE88_API,
		// 		'game_name' => 'one88.FieldHockey',
		// 		'english_name' => 'FieldHockey',
		// 		'external_game_id' => 'FH',
		// 		'game_code' => 'FH',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => ONE88_API,
		// 		'game_name' => 'one88.FinancialBets',
		// 		'english_name' => 'Financial Bets',
		// 		'external_game_id' => 'FB',
		// 		'game_code' => 'FB',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => ONE88_API,
		// 		'game_name' => 'one88.Football',
		// 		'english_name' => 'Football',
		// 		'external_game_id' => 'FBL',
		// 		'game_code' => 'FBL',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => ONE88_API,
		// 		'game_name' => 'one88.Futsal',
		// 		'english_name' => 'Futsal',
		// 		'external_game_id' => 'FS',
		// 		'game_code' => 'FS',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => ONE88_API,
		// 		'game_name' => 'one88.Golf',
		// 		'english_name' => 'Golf',
		// 		'external_game_id' => 'GF',
		// 		'game_code' => 'GF',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => ONE88_API,
		// 		'game_name' => 'one88.Gymnastics',
		// 		'english_name' => 'Gymnastics',
		// 		'external_game_id' => 'GM',
		// 		'game_code' => 'GM',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => ONE88_API,
		// 		'game_name' => 'one88.Handball',
		// 		'english_name' => 'Handball',
		// 		'external_game_id' => 'GM',
		// 		'game_code' => 'GM',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => ONE88_API,
		// 		'game_name' => 'one88.IceHockey',
		// 		'english_name' => 'IceHockey',
		// 		'external_game_id' => 'IH',
		// 		'game_code' => 'IH',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => ONE88_API,
		// 		'game_name' => 'one88.Lottery',
		// 		'english_name' => 'Lottery',
		// 		'external_game_id' => 'LT',
		// 		'game_code' => 'LT',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => ONE88_API,
		// 		'game_name' => 'one88.MoreSports',
		// 		'english_name' => 'More Sports',
		// 		'external_game_id' => 'LT',
		// 		'game_code' => 'LT',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => ONE88_API,
		// 		'game_name' => 'one88.MotorRacing',
		// 		'english_name' => 'Motor Racing',
		// 		'external_game_id' => 'MR',
		// 		'game_code' => 'MR',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => ONE88_API,
		// 		'game_name' => 'one88.Rugby',
		// 		'english_name' => 'Rugby',
		// 		'external_game_id' => 'RB',
		// 		'game_code' => 'RB',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => ONE88_API,
		// 		'game_name' => 'one88.SnookerPool',
		// 		'english_name' => 'Snooker/Pool',
		// 		'external_game_id' => 'RB',
		// 		'game_code' => 'RB',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => ONE88_API,
		// 		'game_name' => 'one88.SoftBall',
		// 		'english_name' => 'Soft Ball',
		// 		'external_game_id' => 'RB',
		// 		'game_code' => 'RB',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => ONE88_API,
		// 		'game_name' => 'one88.SpecialEvents',
		// 		'english_name' => 'Special Events',
		// 		'external_game_id' => 'RB',
		// 		'game_code' => 'RB',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => ONE88_API,
		// 		'game_name' => 'one88.Swimming',
		// 		'english_name' => 'Swimming',
		// 		'external_game_id' => 'SW',
		// 		'game_code' => 'SW',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => ONE88_API,
		// 		'game_name' => 'one88.TableTennis',
		// 		'english_name' => 'Table Tennis',
		// 		'external_game_id' => 'TT',
		// 		'game_code' => 'TT',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => ONE88_API,
		// 		'game_name' => 'one88.Tennis',
		// 		'english_name' => 'Tennis',
		// 		'external_game_id' => 'TT',
		// 		'game_code' => 'TT',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => ONE88_API,
		// 		'game_name' => 'one88.TrackAndField',
		// 		'english_name' => 'Track and Field',
		// 		'external_game_id' => 'TF',
		// 		'game_code' => 'TF',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => ONE88_API,
		// 		'game_name' => 'one88.Volleyball',
		// 		'english_name' => 'Volleyball',
		// 		'external_game_id' => 'TF',
		// 		'game_code' => 'TF',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => ONE88_API,
		// 		'game_name' => 'one88.WinterSports',
		// 		'english_name' => 'Winter Sports',
		// 		'external_game_id' => 'WS',
		// 		'game_code' => 'WS',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),
		// );

		// $this->db->insert_batch('game_description', $data);
		// $this->db->trans_complete();
		// }
	}

	public function down() {
		// $this->db->delete('game_description', array('game_platform_id' => ONE88_API));
	}
}