<?php

defined('BASEPATH') OR exit('No direct script access allowed');

class Migration_add_bbin_game_in_game_description_201512021205 extends CI_Migration {
	const FLAG_TRUE = 1;
	private $tableName = 'game_description';

	public function up() {
		// $sys = $this->config->item('external_system_map');
		// // if (array_key_exists(BBIN_API, $sys)) {
		// $this->db->trans_start();
		// //insert to game_description
		// $this->load->model('game_description_model');

		// //delete wrong game
		// $codes = array('FU', '15017', '15023', '3013', '5021', '5023', '5029', '5074', '5075', '5807', '5822', '5834');
		// $this->db->where_in('game_code', $codes);
		// $this->db->where('game_platform_id', BBIN_API);
		// $this->db->delete($this->tableName);

		// $data = array(
		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_SPORT_GAMES,
		// 		'game_name' => 'bbin.ComboParlay',
		// 		'english_name' => 'Cock Fighting',
		// 		'external_game_id' => 'CB',
		// 		'game_code' => 'CB',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_LOTTERY_GAMES,
		// 		'game_name' => 'bbin.ChongqingFortuneFarm',
		// 		'english_name' => 'Chongqing Fortune Farm',
		// 		'external_game_id' => 'CQSF',
		// 		'game_code' => 'CQSF',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_LOTTERY_GAMES,
		// 		'game_name' => 'bbin.BeijingKeno',
		// 		'english_name' => 'Beijing Keno',
		// 		'external_game_id' => 'BJKN',
		// 		'game_code' => 'BJKN',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_LOTTERY_GAMES,
		// 		'game_name' => 'bbin.ChongqingWildCard',
		// 		'english_name' => 'Chongqing Wild Card',
		// 		'external_game_id' => 'CQWC',
		// 		'game_code' => 'CQWC',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_LOTTERY_GAMES,
		// 		'game_name' => 'bbin.JilinFast3',
		// 		'english_name' => 'Jilin Fast 3',
		// 		'external_game_id' => 'JLQ3',
		// 		'game_code' => 'JLQ3',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_LOTTERY_GAMES,
		// 		'game_name' => 'bbin.JiangsuFast3',
		// 		'english_name' => 'Jiangsu Fast 3',
		// 		'external_game_id' => 'JSQ3',
		// 		'game_code' => 'JSQ3',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_LOTTERY_GAMES,
		// 		'game_name' => 'bbin.AnhuiFast3',
		// 		'english_name' => 'Anhui Fast 3',
		// 		'external_game_id' => 'AHQ3',
		// 		'game_code' => 'AHQ3',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_3DHALL_GAMES,
		// 		'game_name' => 'bbin.AngerAirspace',
		// 		'english_name' => 'Anger Airspace',
		// 		'external_game_id' => '15022',
		// 		'game_code' => '15022',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_LIVE_GAMES,
		// 		'game_name' => 'bbin.FanTan',
		// 		'english_name' => 'Fan Tan',
		// 		'external_game_id' => '3015',
		// 		'game_code' => '3015',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.AlienWar',
		// 		'english_name' => 'Alien War',
		// 		'external_game_id' => '5005',
		// 		'game_code' => '5005',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.Starburst',
		// 		'english_name' => 'Starburst',
		// 		'external_game_id' => '5006',
		// 		'game_code' => '5006',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.FruitsBoom',
		// 		'english_name' => 'Fruits Boom',
		// 		'external_game_id' => '5007',
		// 		'game_code' => '5007',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.MonkeyGoGo',
		// 		'english_name' => 'Monkey GoGo',
		// 		'external_game_id' => '5008',
		// 		'game_code' => '5008',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.KingKong',
		// 		'english_name' => 'King Kong',
		// 		'external_game_id' => '5009',
		// 		'game_code' => '5009',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.MoonFestivalParty',
		// 		'english_name' => 'Moon Festival Party',
		// 		'external_game_id' => '5028',
		// 		'game_code' => '5028',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.XmasParty',
		// 		'english_name' => 'X\'mas Party',
		// 		'external_game_id' => '5029',
		// 		'game_code' => '5029',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.DeucesWild',
		// 		'english_name' => 'Deuces Wild ',
		// 		'external_game_id' => '5040',
		// 		'game_code' => '5040',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.7PK',
		// 		'english_name' => '7PK',
		// 		'external_game_id' => '5041',
		// 		'game_code' => '5041',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.LostBattlefield',
		// 		'english_name' => 'Lost Battlefield',
		// 		'external_game_id' => '5042',
		// 		'game_code' => '5042',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.BaccaratWheel',
		// 		'english_name' => 'BaccaratWheel',
		// 		'external_game_id' => '5073',
		// 		'game_code' => '5073',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.GuessTrain',
		// 		'english_name' => 'Guess Train',
		// 		'external_game_id' => '5083',
		// 		'game_code' => '5083',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.MonsterLegend',
		// 		'english_name' => 'Monster Legend',
		// 		'external_game_id' => '5084',
		// 		'game_code' => '5084',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.OceanParty',
		// 		'english_name' => 'Ocean Party',
		// 		'external_game_id' => '5086',
		// 		'game_code' => '5086',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.CockFighting',
		// 		'english_name' => 'Cock Fighting',
		// 		'external_game_id' => '5095',
		// 		'game_code' => '5095',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.ThreeKingdoms',
		// 		'english_name' => 'Three Kingdoms',
		// 		'external_game_id' => '5106',
		// 		'game_code' => '5106',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.BeachVolleyball',
		// 		'english_name' => 'Beach Volleyball',
		// 		'external_game_id' => '5404',
		// 		'game_code' => '5404',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.KingofHiddenWeapon',
		// 		'english_name' => 'King of Hidden Weapon',
		// 		'external_game_id' => '5405',
		// 		'game_code' => '5405',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.Starship27',
		// 		'english_name' => 'Starship27',
		// 		'external_game_id' => '5406',
		// 		'game_code' => '5406',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.DontCallMeLittleRed',
		// 		'english_name' => 'Don\'t call me Little Red',
		// 		'external_game_id' => '5407',
		// 		'game_code' => '5407',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.AdventureOfMysticalLand',
		// 		'english_name' => 'Adventure of Mystical Land',
		// 		'external_game_id' => '5601',
		// 		'game_code' => '5601',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.LinkGem',
		// 		'english_name' => 'LinkGem',
		// 		'external_game_id' => '5701',
		// 		'game_code' => '5701',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.IAmRich',
		// 		'english_name' => 'I Am Rich',
		// 		'external_game_id' => '5703',
		// 		'game_code' => '5703',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.BullFight',
		// 		'english_name' => 'Bull Fight',
		// 		'external_game_id' => '5704',
		// 		'game_code' => '5704',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.TreasurePot',
		// 		'english_name' => 'Treasure Pot',
		// 		'external_game_id' => '5705',
		// 		'game_code' => '5705',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.ChocolatePassion',
		// 		'english_name' => 'Chocolate Passion',
		// 		'external_game_id' => '5706',
		// 		'game_code' => '5706',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.GoldenJaguar',
		// 		'english_name' => 'Golden Jaguar',
		// 		'external_game_id' => '5707',
		// 		'game_code' => '5707',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.HappyGoldenMonkeyOfHappiness',
		// 		'english_name' => 'Happy Golden Monkey Of Happiness',
		// 		'external_game_id' => '5837',
		// 		'game_code' => '5837',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.DuoBao',
		// 		'english_name' => 'Duo Bao',
		// 		'external_game_id' => '5901',
		// 		'game_code' => '5901',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.CandyParty',
		// 		'english_name' => 'Candy Party',
		// 		'external_game_id' => '5902',
		// 		'game_code' => '5902',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),

		// 	array('game_platform_id' => BBIN_API,
		// 		'game_type_id' => Game_description_model::BBIN_GAMETYPE_CASINO_GAMES,
		// 		'game_name' => 'bbin.TombOfDragonEmperor',
		// 		'english_name' => 'Tomb of Dragon Emperor',
		// 		'external_game_id' => '5903',
		// 		'game_code' => '5903',
		// 		'flash_enabled' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'status' => self::FLAG_TRUE),
		// );

		// $this->db->insert_batch('game_description', $data);
		// $this->db->trans_complete();
		// }
	}

	public function down() {
		// $codes = array(
		// 	'CB', 'CQSF', 'BJKN', 'CQWC', 'JLQ3', 'JSQ3', 'AHQ3', '15022', '3015', '5005', '5006', '5007', '5008',
		// 	'5009', '5028', '5029', '5040', '5041', '5042', '5073', '5083', '5084', '5086', '5095', '5106', '5404',
		// 	'5405', '5406', '5407', '5601', '5701', '5703', '5704', '5705', '5706', '5707', '5837', '5901', '5092', '5093');
		// $this->db->where_in('game_code', $codes);
		// $this->db->where('game_platform_id', BBIN_API);
		// $this->db->delete($this->tableName);
	}
}