<?php

defined('BASEPATH') OR exit('No direct script access allowed');

class Migration_add_nt_new_games_201601061551 extends CI_Migration {

	public function up() {
		// $this->db->trans_start();
		// $data = array(
		// 	array('game_platform_id' => 7,
		// 		'game_type_id' => 20,
		// 		'game_name' => 'nt.games.150',
		// 		'english_name' => 'dazzle me',
		// 		'external_game_id' => '150',
		// 		'game_code' => 'dazzle_not_mobile',
		// 		'flash_enabled' => 1,
		// 		'flag_show_in_site' => 1,
		// 		'status' => 1,
		// 		'attributes' => '{"stat_id":150,"image":"dazzle_not_mobile"}',
		// 		'game_order' => 80),

		// 	array('game_platform_id' => 7,
		// 		'game_type_id' => 20,
		// 		'game_name' => 'nt.games.151',
		// 		'english_name' => 'stickers',
		// 		'external_game_id' => '151',
		// 		'game_code' => 'stickers_not_mobile',
		// 		'flash_enabled' => 1,
		// 		'flag_show_in_site' => 1,
		// 		'status' => 1,
		// 		'attributes' => '{"stat_id":151,"image":"stickers_not_mobile"}',
		// 		'game_order' => 81),

		// 	array('game_platform_id' => 7,
		// 		'game_type_id' => 20,
		// 		'game_name' => 'nt.games.152',
		// 		'english_name' => 'neonstaxx',
		// 		'external_game_id' => '152',
		// 		'game_code' => 'neonstaxx_not_mobile',
		// 		'flash_enabled' => 1,
		// 		'flag_show_in_site' => 1,
		// 		'status' => 1,
		// 		'attributes' => '{"stat_id":152,"image":"neonstaxx_not_mobile"}',
		// 		'game_order' => 82),

		// 	array('game_platform_id' => 7,
		// 		'game_type_id' => 20,
		// 		'game_name' => 'nt.games.153',
		// 		'english_name' => 'alien',
		// 		'external_game_id' => '153',
		// 		'game_code' => 'alien',
		// 		'flash_enabled' => 1,
		// 		'flag_show_in_site' => 1,
		// 		'status' => 1,
		// 		'attributes' => '{"stat_id":153,"image":"alien"}',
		// 		'game_order' => 83),

		// 	array('game_platform_id' => 7,
		// 		'game_type_id' => 20,
		// 		'game_name' => 'nt.games.154',
		// 		'english_name' => 'sparks',
		// 		'external_game_id' => '154',
		// 		'game_code' => 'sparks_not_mobile',
		// 		'flash_enabled' => 1,
		// 		'flag_show_in_site' => 1,
		// 		'status' => 1,
		// 		'attributes' => '{"stat_id":154,"image":"sparks_not_mobile"}',
		// 		'game_order' => 84),

		// 	array('game_platform_id' => 7,
		// 		'game_type_id' => 20,
		// 		'game_name' => 'nt.games.155',
		// 		'english_name' => 'crusaders',
		// 		'external_game_id' => '155',
		// 		'game_code' => 'crusaders',
		// 		'flash_enabled' => 1,
		// 		'flag_show_in_site' => 1,
		// 		'status' => 1,
		// 		'attributes' => '{"stat_id":155,"image":"crusaders"}',
		// 		'game_order' => 85),

		// 	array('game_platform_id' => 7,
		// 		'game_type_id' => 20,
		// 		'game_name' => 'nt.games.156',
		// 		'english_name' => 'jackhammer',
		// 		'external_game_id' => '156',
		// 		'game_code' => 'jackhammer',
		// 		'flash_enabled' => 1,
		// 		'flag_show_in_site' => 1,
		// 		'status' => 1,
		// 		'attributes' => '{"stat_id":156,"image":"jackhammer"}',
		// 		'game_order' => 86),

		// 	array('game_platform_id' => 7,
		// 		'game_type_id' => 20,
		// 		'game_name' => 'nt.games.157',
		// 		'english_name' => 'evolution',
		// 		'external_game_id' => '157',
		// 		'game_code' => 'evolution',
		// 		'flash_enabled' => 1,
		// 		'flag_show_in_site' => 1,
		// 		'status' => 1,
		// 		'attributes' => '{"stat_id":157,"image":"evolution"}',
		// 		'game_order' => 87),

		// 	array('game_platform_id' => 7,
		// 		'game_type_id' => 20,
		// 		'game_name' => 'nt.games.176',
		// 		'english_name' => 'devils delight',
		// 		'external_game_id' => '176',
		// 		'game_code' => 'devil',
		// 		'flash_enabled' => 1,
		// 		'flag_show_in_site' => 1,
		// 		'status' => 1,
		// 		'attributes' => '{"stat_id":176,"image":"devil"}',
		// 		'game_order' => 88),

		// 	array('game_platform_id' => 7,
		// 		'game_type_id' => 20,
		// 		'game_name' => 'nt.games.178',
		// 		'english_name' => 'boombrothers',
		// 		'external_game_id' => '178',
		// 		'game_code' => 'boombrothers',
		// 		'flash_enabled' => 1,
		// 		'flag_show_in_site' => 1,
		// 		'status' => 1,
		// 		'attributes' => '{"stat_id":178,"image":"boombrothers"}',
		// 		'game_order' => 89),

		// 	array('game_platform_id' => 7,
		// 		'game_type_id' => 20,
		// 		'game_name' => 'nt.games.179',
		// 		'english_name' => 'pacific',
		// 		'external_game_id' => '179',
		// 		'game_code' => 'pacific',
		// 		'flash_enabled' => 1,
		// 		'flag_show_in_site' => 1,
		// 		'status' => 1,
		// 		'attributes' => '{"stat_id":179,"image":"pacific"}',
		// 		'game_order' => 90),

		// 	array('game_platform_id' => 7,
		// 		'game_type_id' => 20,
		// 		'game_name' => 'nt.games.180',
		// 		'english_name' => 'scarface',
		// 		'external_game_id' => '180',
		// 		'game_code' => 'scarface',
		// 		'flash_enabled' => 1,
		// 		'flag_show_in_site' => 1,
		// 		'status' => 1,
		// 		'attributes' => '{"stat_id":180,"image":"scarface"}',
		// 		'game_order' => 91),

		// 	array('game_platform_id' => 7,
		// 		'game_type_id' => 20,
		// 		'game_name' => 'nt.games.181',
		// 		'english_name' => 'invisibleman',
		// 		'external_game_id' => '181',
		// 		'game_code' => 'invisibleman_not_mobile',
		// 		'flash_enabled' => 1,
		// 		'flag_show_in_site' => 1,
		// 		'status' => 1,
		// 		'attributes' => '{"stat_id":181,"image":"invisibleman_not_mobile"}',
		// 		'game_order' => 92),

		// 	array('game_platform_id' => 7,
		// 		'game_type_id' => 20,
		// 		'game_name' => 'nt.games.185',
		// 		'english_name' => 'robinhood',
		// 		'external_game_id' => '185',
		// 		'game_code' => 'robinhood',
		// 		'flash_enabled' => 1,
		// 		'flag_show_in_site' => 1,
		// 		'status' => 1,
		// 		'attributes' => '{"stat_id":185,"image":"robinhood"}',
		// 		'game_order' => 93),

		// 	array('game_platform_id' => 7,
		// 		'game_type_id' => 20,
		// 		'game_name' => 'nt.games.192',
		// 		'english_name' => 'pyramid: quest for immortality',
		// 		'external_game_id' => '192',
		// 		'game_code' => 'pyramid_not_mobile',
		// 		'flash_enabled' => 1,
		// 		'flag_show_in_site' => 1,
		// 		'status' => 1,
		// 		'attributes' => '{"stat_id":192,"image":"pyramid_not_mobile"}',
		// 		'game_order' => 94),

		// 	array('game_platform_id' => 7,
		// 		'game_type_id' => 20,
		// 		'game_name' => 'nt.games.197',
		// 		'english_name' => 'hooksheroes',
		// 		'external_game_id' => '197',
		// 		'game_code' => 'hooksheroes_not_mobile',
		// 		'flash_enabled' => 1,
		// 		'flag_show_in_site' => 1,
		// 		'status' => 1,
		// 		'attributes' => '{"stat_id":197,"image":"hooksheroes_not_mobile"}',
		// 		'game_order' => 95),
		// );

		// $this->db->insert_batch('game_description', $data);
		// $fruitdata = array(
		// 	'game_platform_id' => 7,
		// 	'game_type_id' => 20,
		// 	'game_name' => 'nt.games.212',
		// 	'english_name' => 'fruit case',
		// 	'external_game_id' => '212',
		// 	'game_code' => 'fruits',
		// 	'flash_enabled' => 1,
		// 	'flag_show_in_site' => 1,
		// 	'status' => 1,
		// 	'attributes' => '{"stat_id":212,"image":"fruit_case"}',
		// 	'game_order' => 96
		// );
		// $this->db->where('game_name', 'nt.games.212');
		// $this->db->update('game_description',$fruitdata);
		// $this->db->trans_complete();
	}

	public function down() {
		// $codes = array(
		// 	'150','151','152','153','154','155','156','157','178','176','179','180','181',
		// 	'185','192','197','212');
		// $this->db->where_in('external_game_id', $codes);
		// $this->db->where('game_platform_id', 7);
		// $this->db->delete('game_description');
	}
}