<?php

defined('BASEPATH') OR exit('No direct script access allowed');

class Migration_add_ibc_in_game_type_and_game_description_201604011034 extends CI_Migration {
	const FLAG_TRUE = 1;
	const FLAG_FALSE = 0;

	public function up() {
		// $this->db->trans_start();

		// //insert to game_description
		// $data = array(
		// 	array(
		// 		'game_type' => 'Sports',
		// 		'game_type_lang' => 'ibc_sports',
		// 		'status' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'game_description_list' => array(
		// 			array('game_name' => 'ibc.games.1',
		// 				'english_name' => 'Soccer',
		// 				'external_game_id' => '1',
		// 				'game_code' => '1',
		// 			),
		// 			array('game_name' => 'ibc.games.2',
		// 				'english_name' => 'Basketball',
		// 				'external_game_id' => '2',
		// 				'game_code' => '2',
		// 			),
		// 			array('game_name' => 'ibc.games.3',
		// 				'english_name' => 'Football',
		// 				'external_game_id' => '3',
		// 				'game_code' => '3',
		// 			),
		// 			array('game_name' => 'ibc.games.4',
		// 				'english_name' => 'Ice Hockey',
		// 				'external_game_id' => '4',
		// 				'game_code' => '4',
		// 			),
		// 			array('game_name' => 'ibc.games.5',
		// 				'english_name' => 'Tennis',
		// 				'external_game_id' => '5',
		// 				'game_code' => '5',
		// 			),
		// 			array('game_name' => 'ibc.games.6',
		// 				'english_name' => 'Volleyball',
		// 				'external_game_id' => '6',
		// 				'game_code' => '6',
		// 			),
		// 			array('game_name' => 'ibc.games.7',
		// 				'english_name' => 'Billiards',
		// 				'external_game_id' => '7',
		// 				'game_code' => '7',
		// 			),
		// 			array('game_name' => 'ibc.games.8',
		// 				'english_name' => 'Baseball',
		// 				'external_game_id' => '8',
		// 				'game_code' => '8',
		// 			),
		// 			array('game_name' => 'ibc.games.9',
		// 				'english_name' => 'Badminton',
		// 				'external_game_id' => '9',
		// 				'game_code' => '9',
		// 			),
		// 			array('game_name' => 'ibc.games.10',
		// 				'english_name' => 'Golf',
		// 				'external_game_id' => '10',
		// 				'game_code' => '10',
		// 			),
		// 			array('game_name' => 'ibc.games.11',
		// 				'english_name' => 'Motorsports',
		// 				'external_game_id' => '11',
		// 				'game_code' => '11',
		// 			),
		// 			array('game_name' => 'ibc.games.12',
		// 				'english_name' => 'Swimming',
		// 				'external_game_id' => '12',
		// 				'game_code' => '12',
		// 			),
		// 			array('game_name' => 'ibc.games.13',
		// 				'english_name' => 'Politics',
		// 				'external_game_id' => '13',
		// 				'game_code' => '13',
		// 			),
		// 			array('game_name' => 'ibc.games.14',
		// 				'english_name' => 'Water Polo',
		// 				'external_game_id' => '14',
		// 				'game_code' => '14',
		// 			),
		// 			array('game_name' => 'ibc.games.15',
		// 				'english_name' => 'Diving',
		// 				'external_game_id' => '15',
		// 				'game_code' => '15',
		// 			),
		// 			array('game_name' => 'ibc.games.16',
		// 				'english_name' => 'Boxing',
		// 				'external_game_id' => '16',
		// 				'game_code' => '16',
		// 			),
		// 			array('game_name' => 'ibc.games.17',
		// 				'english_name' => 'Archery',
		// 				'external_game_id' => '17',
		// 				'game_code' => '17',
		// 			),
		// 			array('game_name' => 'ibc.games.18',
		// 				'english_name' => 'Table Tennis',
		// 				'external_game_id' => '18',
		// 				'game_code' => '18',
		// 			),
		// 			array('game_name' => 'ibc.games.19',
		// 				'english_name' => 'Weightlifting',
		// 				'external_game_id' => '19',
		// 				'game_code' => '19',
		// 			),
		// 			array('game_name' => 'ibc.games.20',
		// 				'english_name' => 'Canoeing',
		// 				'external_game_id' => '20',
		// 				'game_code' => '20',
		// 			),
		// 			array('game_name' => 'ibc.games.21',
		// 				'english_name' => 'Gymnastics',
		// 				'external_game_id' => '21',
		// 				'game_code' => '21',
		// 			),
		// 			array('game_name' => 'ibc.games.22',
		// 				'english_name' => 'Athletics',
		// 				'external_game_id' => '22',
		// 				'game_code' => '22',
		// 			),
		// 			array('game_name' => 'ibc.games.23',
		// 				'english_name' => 'Equestrian',
		// 				'external_game_id' => '23',
		// 				'game_code' => '23',
		// 			),
		// 			array('game_name' => 'ibc.games.24',
		// 				'english_name' => 'Handball',
		// 				'external_game_id' => '24',
		// 				'game_code' => '24',
		// 			),
		// 			array('game_name' => 'ibc.games.25',
		// 				'english_name' => 'Darts',
		// 				'external_game_id' => '25',
		// 				'game_code' => '25',
		// 			),
		// 			array('game_name' => 'ibc.games.26',
		// 				'english_name' => 'Rugby',
		// 				'external_game_id' => '26',
		// 				'game_code' => '26',
		// 			),
		// 			array('game_name' => 'ibc.games.27',
		// 				'english_name' => 'Cricket',
		// 				'external_game_id' => '27',
		// 				'game_code' => '27',
		// 			),
		// 			array('game_name' => 'ibc.games.28',
		// 				'english_name' => 'Field Hockey',
		// 				'external_game_id' => '28',
		// 				'game_code' => '28',
		// 			),
		// 			array('game_name' => 'ibc.games.29',
		// 				'english_name' => 'Winter Sport',
		// 				'external_game_id' => '29',
		// 				'game_code' => '29',
		// 			),
		// 			array('game_name' => 'ibc.games.30',
		// 				'english_name' => 'Squash',
		// 				'external_game_id' => '30',
		// 				'game_code' => '30',
		// 			),
		// 			array('game_name' => 'ibc.games.31',
		// 				'english_name' => 'Entertainment',
		// 				'external_game_id' => '31',
		// 				'game_code' => '31',
		// 			),
		// 			array('game_name' => 'ibc.games.32',
		// 				'english_name' => 'Net Ball',
		// 				'external_game_id' => '32',
		// 				'game_code' => '32',
		// 			),
		// 			array('game_name' => 'ibc.games.33',
		// 				'english_name' => 'Cycling',
		// 				'external_game_id' => '33',
		// 				'game_code' => '33',
		// 			),
		// 			array('game_name' => 'ibc.games.34',
		// 				'english_name' => 'Fencing',
		// 				'external_game_id' => '34',
		// 				'game_code' => '34',
		// 			),
		// 			array('game_name' => 'ibc.games.35',
		// 				'english_name' => 'Judo',
		// 				'external_game_id' => '35',
		// 				'game_code' => '35',
		// 			),
		// 			array('game_name' => 'ibc.games.36',
		// 				'english_name' => 'M. Pentathlon',
		// 				'external_game_id' => '36',
		// 				'game_code' => '36',
		// 			),
		// 			array('game_name' => 'ibc.games.37',
		// 				'english_name' => 'Rowing',
		// 				'external_game_id' => '37',
		// 				'game_code' => '37',
		// 			),
		// 			array('game_name' => 'ibc.games.38',
		// 				'english_name' => 'Sailing',
		// 				'external_game_id' => '38',
		// 				'game_code' => '38',
		// 			),
		// 			array('game_name' => 'ibc.games.39',
		// 				'english_name' => 'Shooting',
		// 				'external_game_id' => '39',
		// 				'game_code' => '39',
		// 			),
		// 			array('game_name' => 'ibc.games.40',
		// 				'english_name' => 'Taekwondo',
		// 				'external_game_id' => '40',
		// 				'game_code' => '40',
		// 			),
		// 			array('game_name' => 'ibc.games.41',
		// 				'english_name' => 'Triathlon',
		// 				'external_game_id' => '41',
		// 				'game_code' => '41',
		// 			),
		// 			array('game_name' => 'ibc.games.42',
		// 				'english_name' => 'Wrestling',
		// 				'external_game_id' => '42',
		// 				'game_code' => '42',
		// 			),
		// 			array('game_name' => 'ibc.games.43',
		// 				'english_name' => 'E Sports ',
		// 				'external_game_id' => '43',
		// 				'game_code' => '43',
		// 			),
		// 			array('game_name' => 'ibc.games.44',
		// 				'english_name' => 'E Sports ',
		// 				'external_game_id' => '44',
		// 				'game_code' => '44',
		// 			),
		// 			array('game_name' => 'ibc.games.99',
		// 				'english_name' => 'Other Sports',
		// 				'external_game_id' => '99',
		// 				'game_code' => '99',
		// 			),
		// 			array('game_name' => 'ibc.games.151',
		// 				'english_name' => 'Horse Racing',
		// 				'external_game_id' => '151',
		// 				'game_code' => '151',
		// 			),
		// 			array('game_name' => 'ibc.games.152',
		// 				'english_name' => 'Greyhounds',
		// 				'external_game_id' => '152',
		// 				'game_code' => '152',
		// 			),
		// 			array('game_name' => 'ibc.games.153',
		// 				'english_name' => 'Harness',
		// 				'external_game_id' => '153',
		// 				'game_code' => '153',
		// 			),
		// 			array('game_name' => 'ibc.games.154',
		// 				'english_name' => 'Horse Racing Fixed Odds',
		// 				'external_game_id' => '154',
		// 				'game_code' => '154',
		// 			),
		// 			array('game_name' => 'ibc.games.161',
		// 				'english_name' => 'Number Game',
		// 				'external_game_id' => '161',
		// 				'game_code' => '161',
		// 			),
		// 			array('game_name' => 'ibc.games.162',
		// 				'english_name' => 'Live Casino',
		// 				'external_game_id' => '162',
		// 				'game_code' => '162',
		// 			),
		// 			array('game_name' => 'ibc.games.180',
		// 				'english_name' => 'Virtual Soccer',
		// 				'external_game_id' => '180',
		// 				'game_code' => '180',
		// 			),
		// 			array('game_name' => 'ibc.games.181',
		// 				'english_name' => 'Virtual Horse Racing',
		// 				'external_game_id' => '181',
		// 				'game_code' => '181',
		// 			),
		// 			array('game_name' => 'ibc.games.182',
		// 				'english_name' => 'Virtual Greyhound',
		// 				'external_game_id' => '182',
		// 				'game_code' => '182',
		// 			),
		// 			array('game_name' => 'ibc.games.183',
		// 				'english_name' => 'Virtual Speedway',
		// 				'external_game_id' => '183',
		// 				'game_code' => '183',
		// 			),
		// 			array('game_name' => 'ibc.games.184',
		// 				'english_name' => 'Virtual F1',
		// 				'external_game_id' => '184',
		// 				'game_code' => '184',
		// 			),
		// 			array('game_name' => 'ibc.games.185',
		// 				'english_name' => 'Virtual Cycling',
		// 				'external_game_id' => '185',
		// 				'game_code' => '185',
		// 			),
		// 			array('game_name' => 'ibc.games.186',
		// 				'english_name' => 'Virtual Tennis',
		// 				'external_game_id' => '186',
		// 				'game_code' => '186',
		// 			),
		// 			array('game_name' => 'ibc.games.202',
		// 				'english_name' => 'Keno',
		// 				'external_game_id' => '202',
		// 				'game_code' => '202',
		// 			),
		// 			array('game_name' => 'ibc.games.251',
		// 				'english_name' => 'Casino',
		// 				'external_game_id' => '251',
		// 				'game_code' => '251',
		// 			),
		// 		),
		// 	),

		// 	array(
		// 		'game_type' => 'unknown',
		// 		'game_type_lang' => 'ibc.unknown',
		// 		'status' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_FALSE,
		// 		'game_description_list' => array(
		// 			array('game_name' => 'ibc.unknown',
		// 				'english_name' => 'Unknown Ibc Game',
		// 				'external_game_id' => 'unknown',
		// 				'game_code' => 'unknown',
		// 			),

		// 		),
		// 	),

		// );

		// $game_description_list = array();
		// foreach ($data as $game_type) {
		// 	$this->db->insert('game_type', array(
		// 		'game_platform_id' => IBC_API,
		// 		'game_type' => $game_type['game_type'],
		// 		'game_type_lang' => $game_type['game_type_lang'],
		// 		'status' => $game_type['status'],
		// 		'flag_show_in_site' => $game_type['flag_show_in_site'],
		// 	));

		// 	$game_type_id = $this->db->insert_id();
		// 	foreach ($game_type['game_description_list'] as $game_description) {
		// 		$game_description_list[] = array_merge(array(
		// 			'game_platform_id' => IBC_API,
		// 			'game_type_id' => $game_type_id,
		// 		), $game_description);
		// 	}
		// }

		// $this->db->insert_batch('game_description', $game_description_list);
		// $this->db->trans_complete();

	}

	public function down() {
		// $this->db->trans_start();
		// $this->db->delete('game_type', array('game_platform_id' => IBC_API));
		// $this->db->delete('game_description', array('game_platform_id' => IBC_API));
		// $this->db->trans_complete();
	}
}