<?php

defined('BASEPATH') OR exit('No direct script access allowed');

class Migration_add_gameplay_sbtech_in_game_type_and_game_description_201604051222 extends CI_Migration {
	const FLAG_TRUE = 1;
	const FLAG_FALSE = 0;

	public function up() {
		// $this->db->trans_start();

		// //insert to game_description
		// $data = array(
		// 	array(
		// 		'game_type' => 'Arcades',
		// 		'game_type_lang' => 'gameplay_sbtech_arcades',
		// 		'status' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'game_description_list' => array(
		// 			array("english_name" => "Basebull Scratch",
		// 				"game_code" => "xc_basebullscratch",
		// 				"game_name" => "gameplay.sbtech.xc_basebullscratch",
		// 				"external_game_id" => "xc_basebullscratch"),
		// 			array("english_name" => "Bingo Scratch",
		// 				"game_code" => "xc_bingoscratch",
		// 				"game_name" => "gameplay.sbtech.xc_bingoscratch",
		// 				"external_game_id" => "xc_bingoscratch"),
		// 			array("english_name" => "Cubana-Tropicana Scratch",
		// 				"game_code" => "xc_cubanatropicanascratch",
		// 				"game_name" => "gameplay.sbtech.xc_cubanatropicanascratch",
		// 				"external_game_id" => "xc_cubanatropicanascratch"),
		// 			array("english_name" => "Easter Feast Scratch",
		// 				"game_code" => "xc_easterfeastscratch",
		// 				"game_name" => "gameplay.sbtech.xc_easterfeastscratch",
		// 				"external_game_id" => "xc_easterfeastscratch"),
		// 			array("english_name" => "Freaky Thimbles",
		// 				"game_code" => "xc_freakythimblesscratch",
		// 				"game_name" => "gameplay.sbtech.xc_freakythimblesscratch",
		// 				"external_game_id" => "xc_freakythimblesscratch"),
		// 			array("english_name" => "Gangsters\' Loot",
		// 				"game_code" => "xc_gangstersscratch",
		// 				"game_name" => "gameplay.sbtech.xc_gangstersscratch",
		// 				"external_game_id" => "xc_gangstersscratch"),
		// 			array("english_name" => "Gold 999.9",
		// 				"game_code" => "xc_goldenscratch",
		// 				"game_name" => "gameplay.sbtech.xc_goldenscratch",
		// 				"external_game_id" => "xc_goldenscratch"),
		// 			array("english_name" => "Hockey Potshot",
		// 				"game_code" => "xc_potshot",
		// 				"game_name" => "gameplay.sbtech.xc_potshot",
		// 				"external_game_id" => "xc_potshot"),
		// 			array("english_name" => "Instant Lotto",
		// 				"game_code" => "xc_lotto",
		// 				"game_name" => "gameplay.sbtech.xc_lotto",
		// 				"external_game_id" => "xc_lotto"),
		// 			array("english_name" => "Jour Del Amour Scratch",
		// 				"game_code" => "xc_jourdelamourscratch",
		// 				"game_name" => "gameplay.sbtech.xc_jourdelamourscratch",
		// 				"external_game_id" => "xc_jourdelamourscratch"),
		// 			array("english_name" => "Keno",
		// 				"game_code" => "xc_keno",
		// 				"game_name" => "gameplay.sbtech.xc_keno",
		// 				"external_game_id" => "xc_keno"),
		// 			array("english_name" => "Magic Pot Scratch",
		// 				"game_code" => "xc_magicpotscratch",
		// 				"game_name" => "gameplay.sbtech.xc_magicpotscratch",
		// 				"external_game_id" => "xc_magicpotscratch"),
		// 			array("english_name" => "Moonapolis",
		// 				"game_code" => "xc_moonapolisscratch",
		// 				"game_name" => "gameplay.sbtech.xc_moonapolisscratch",
		// 				"external_game_id" => "xc_moonapolisscratch"),
		// 			array("english_name" => "Soccer Scratch",
		// 				"game_code" => "xc_soccerscratch",
		// 				"game_name" => "gameplay.sbtech.xc_soccerscratch",
		// 				"external_game_id" => "xc_soccerscratch"),
		// 			array("english_name" => "Soccer Shot",
		// 				"game_code" => "xc_soccershot",
		// 				"game_name" => "gameplay.sbtech.xc_soccershot",
		// 				"external_game_id" => "xc_soccershot"),
		// 			array("english_name" => "Sparkle Ladies",
		// 				"game_code" => "xc_sparkleladiesscratch",
		// 				"game_name" => "gameplay.sbtech.xc_sparkleladiesscratch",
		// 				"external_game_id" => "xc_sparkleladiesscratch"),
		// 		),
		// 	),
		// 	array(
		// 		'game_type' => 'Card Games',
		// 		'game_type_lang' => 'gameplay_sbtech_cardgames',
		// 		'status' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'game_description_list' => array(
		// 			array("english_name" => "Baccarat",
		// 				"game_code" => "xc_baccarat",
		// 				"game_name" => "gameplay.sbtech.xc_baccarat",
		// 				"external_game_id" => "xc_baccarat"),
		// 			array("english_name" => "Blackjack",
		// 				"game_code" => "xc_bj",
		// 				"game_name" => "gameplay.sbtech.xc_bj",
		// 				"external_game_id" => "xc_bj"),
		// 			array("english_name" => "Blackjack Classic",
		// 				"game_code" => "xc_blackjack",
		// 				"game_name" => "gameplay.sbtech.xc_blackjack",
		// 				"external_game_id" => "xc_blackjack"),
		// 			array("english_name" => "Blackjack Surrender",
		// 				"game_code" => "xc_bj_s",
		// 				"game_name" => "gameplay.sbtech.xc_bj_s",
		// 				"external_game_id" => "xc_bj_s"),
		// 			array("english_name" => "Blackjack Surrender Classic",
		// 				"game_code" => "xc_blackjack_s",
		// 				"game_name" => "gameplay.sbtech.xc_blackjack_s",
		// 				"external_game_id" => "xc_blackjack_s"),
		// 			array("english_name" => "Face Up 21 Blackjack Classic",
		// 				"game_code" => "xc_blackjack_faceup",
		// 				"game_name" => "gameplay.sbtech.xc_blackjack_faceup",
		// 				"external_game_id" => "xc_blackjack_faceup"),
		// 			array("english_name" => "Multi Hand Baccarat",
		// 				"game_code" => "xc_mhbaccarat",
		// 				"game_name" => "gameplay.sbtech.xc_mhbaccarat",
		// 				"external_game_id" => "xc_mhbaccarat"),
		// 			array("english_name" => "Oasis Poker",
		// 				"game_code" => "xc_poker_oasis",
		// 				"game_name" => "gameplay.sbtech.xc_poker_oasis",
		// 				"external_game_id" => "xc_poker_oasis"),
		// 			array("english_name" => "Pai Gow Poker",
		// 				"game_code" => "xc_paigowpoker",
		// 				"game_name" => "gameplay.sbtech.xc_paigowpoker",
		// 				"external_game_id" => "xc_paigowpoker"),
		// 			array("english_name" => "Perfect Pairs Blackjack",
		// 				"game_code" => "xc_blackjack_perfectpairs",
		// 				"game_name" => "gameplay.sbtech.xc_blackjack_perfectpairs",
		// 				"external_game_id" => "xc_blackjack_perfectpairs"),
		// 			array("english_name" => "Pontoon",
		// 				"game_code" => "xc_blackjack_pontoon",
		// 				"game_name" => "gameplay.sbtech.xc_blackjack_pontoon",
		// 				"external_game_id" => "xc_blackjack_pontoon"),
		// 			array("english_name" => "Russian Poker",
		// 				"game_code" => "xc_poker_russian",
		// 				"game_name" => "gameplay.sbtech.xc_poker_russian",
		// 				"external_game_id" => "xc_poker_russian"),
		// 			array("english_name" => "Spanish Blackjack",
		// 				"game_code" => "xc_blackjack_spanish",
		// 				"game_name" => "gameplay.sbtech.xc_blackjack_spanish",
		// 				"external_game_id" => "xc_blackjack_spanish"),
		// 		),
		// 	),
		// 	array(
		// 		'game_type' => 'Slots',
		// 		'game_type_lang' => 'gameplay_sbtech_slots',
		// 		'status' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'game_description_list' => array(
		// 			array("english_name" => "Archipelago",
		// 				"game_code" => "xc_archipelagoslots",
		// 				"game_name" => "gameplay.sbtech.xc_archipelagoslots",
		// 				"external_game_id" => "xc_archipelagoslots"),
		// 			array("english_name" => "Atlantis Dive",
		// 				"game_code" => "xc_atlantisdiveslots",
		// 				"game_name" => "gameplay.sbtech.xc_atlantisdiveslots",
		// 				"external_game_id" => "xc_atlantisdiveslots"),
		// 			array("english_name" => "Aztec Slots New",
		// 				"game_code" => "xc_aztecslotsnew",
		// 				"game_name" => "gameplay.sbtech.xc_aztecslotsnew",
		// 				"external_game_id" => "xc_aztecslotsnew"),
		// 			array("english_name" => "Battleground Spins",
		// 				"game_code" => "xc_battlegroundslots",
		// 				"game_name" => "gameplay.sbtech.xc_battlegroundslots",
		// 				"external_game_id" => "xc_battlegroundslots"),
		// 			array("english_name" => "China MegaWild",
		// 				"game_code" => "xc_wildchinaslots",
		// 				"game_name" => "gameplay.sbtech.xc_wildchinaslots",
		// 				"external_game_id" => "xc_wildchinaslots"),
		// 			array("english_name" => "Choo Choo Slots",
		// 				"game_code" => "xc_choochooslots",
		// 				"game_name" => "gameplay.sbtech.xc_choochooslots",
		// 				"external_game_id" => "xc_choochooslots"),
		// 			array("english_name" => "Cleopatra Treasure",
		// 				"game_code" => "xc_cleopatratreasureslots",
		// 				"game_name" => "gameplay.sbtech.xc_cleopatratreasureslots",
		// 				"external_game_id" => "xc_cleopatratreasureslots"),
		// 			array("english_name" => "Cubana-Tropicana",
		// 				"game_code" => "xc_cubanatropicanaslots",
		// 				"game_name" => "gameplay.sbtech.xc_cubanatropicanaslots",
		// 				"external_game_id" => "xc_cubanatropicanaslots"),
		// 			array("english_name" => "Easter Feast",
		// 				"game_code" => "xc_easterfeastslots",
		// 				"game_name" => "gameplay.sbtech.xc_easterfeastslots",
		// 				"external_game_id" => "xc_easterfeastslots"),
		// 			array("english_name" => "Farm Slot",
		// 				"game_code" => "xc_farmslots",
		// 				"game_name" => "gameplay.sbtech.xc_farmslots",
		// 				"external_game_id" => "xc_farmslots"),
		// 			array("english_name" => "Football Cup",
		// 				"game_code" => "xc_footballcupslots",
		// 				"game_name" => "gameplay.sbtech.xc_footballcupslots",
		// 				"external_game_id" => "xc_footballcupslots"),
		// 			array("english_name" => "Freaky Bandits",
		// 				"game_code" => "xc_freakybanditsslots",
		// 				"game_name" => "gameplay.sbtech.xc_freakybanditsslots",
		// 				"external_game_id" => "xc_freakybanditsslots"),
		// 			array("english_name" => "Freaky Cars",
		// 				"game_code" => "xc_freakycarsslots",
		// 				"game_name" => "gameplay.sbtech.xc_freakycarsslots",
		// 				"external_game_id" => "xc_freakycarsslots"),
		// 			array("english_name" => "Freaky Cowboys",
		// 				"game_code" => "xc_freakycowboysslots",
		// 				"game_name" => "gameplay.sbtech.xc_freakycowboysslots",
		// 				"external_game_id" => "xc_freakycowboysslots"),
		// 			array("english_name" => "Freaky Fruits",
		// 				"game_code" => "xc_freakyfruitsslots",
		// 				"game_name" => "gameplay.sbtech.xc_freakyfruitsslots",
		// 				"external_game_id" => "xc_freakyfruitsslots"),
		// 			array("english_name" => "Freaky Gym",
		// 				"game_code" => "xc_freakygymslots",
		// 				"game_name" => "gameplay.sbtech.xc_freakygymslots",
		// 				"external_game_id" => "xc_freakygymslots"),
		// 			array("english_name" => "Freaky Wild West 3D",
		// 				"game_code" => "xc_freakywildwest3Dslots",
		// 				"game_name" => "gameplay.sbtech.xc_freakywildwest3Dslots",
		// 				"external_game_id" => "xc_freakywildwest3Dslots"),
		// 			array("english_name" => "Gems and the City",
		// 				"game_code" => "xc_gemsandthecityslots",
		// 				"game_name" => "gameplay.sbtech.xc_gemsandthecityslots",
		// 				"external_game_id" => "xc_gemsandthecityslots"),
		// 			array("english_name" => "Generous Santa",
		// 				"game_code" => "xc_generoussantaslots",
		// 				"game_name" => "gameplay.sbtech.xc_generoussantaslots",
		// 				"external_game_id" => "xc_generoussantaslots"),
		// 			array("english_name" => "Golden India Slots",
		// 				"game_code" => "xc_goldenindiaslots",
		// 				"game_name" => "gameplay.sbtech.xc_goldenindiaslots",
		// 				"external_game_id" => "xc_goldenindiaslots"),
		// 			array("english_name" => "House of Scare",
		// 				"game_code" => "xc_houseofscareslots",
		// 				"game_name" => "gameplay.sbtech.xc_houseofscareslots",
		// 				"external_game_id" => "xc_houseofscareslots"),
		// 			array("english_name" => "Karaoke Star Slots",
		// 				"game_code" => "xc_karaokeslots",
		// 				"game_name" => "gameplay.sbtech.xc_karaokeslots",
		// 				"external_game_id" => "xc_karaokeslots"),
		// 			array("english_name" => "Magic Pot",
		// 				"game_code" => "xc_magicpotslots",
		// 				"game_name" => "gameplay.sbtech.xc_magicpotslots",
		// 				"external_game_id" => "xc_magicpotslots"),
		// 			array("english_name" => "Mexican Slots",
		// 				"game_code" => "xc_mexicoslots",
		// 				"game_name" => "gameplay.sbtech.xc_mexicoslots",
		// 				"external_game_id" => "xc_mexicoslots"),
		// 			array("english_name" => "Midnight Lucky Sky Slots",
		// 				"game_code" => "xc_firecrackerslots",
		// 				"game_name" => "gameplay.sbtech.xc_firecrackerslots",
		// 				"external_game_id" => "xc_firecrackerslots"),
		// 			array("english_name" => "Mystic Slots",
		// 				"game_code" => "xc_mysticslots",
		// 				"game_name" => "gameplay.sbtech.xc_mysticslots",
		// 				"external_game_id" => "xc_mysticslots"),
		// 			array("english_name" => "Non Stop Party",
		// 				"game_code" => "xc_nonstoppartyslots",
		// 				"game_name" => "gameplay.sbtech.xc_nonstoppartyslots",
		// 				"external_game_id" => "xc_nonstoppartyslots"),
		// 			array("english_name" => "Olympic Slots",
		// 				"game_code" => "xc_olympicslots",
		// 				"game_name" => "gameplay.sbtech.xc_olympicslots",
		// 				"external_game_id" => "xc_olympicslots"),
		// 			array("english_name" => "Party Night",
		// 				"game_code" => "xc_partynightslots",
		// 				"game_name" => "gameplay.sbtech.xc_partynightslots",
		// 				"external_game_id" => "xc_partynightslots"),
		// 			array("english_name" => "Pirate Slots",
		// 				"game_code" => "xc_pirateslots",
		// 				"game_name" => "gameplay.sbtech.xc_pirateslots",
		// 				"external_game_id" => "xc_pirateslots"),
		// 			array("english_name" => "Polar Tale",
		// 				"game_code" => "xc_polartaleslots",
		// 				"game_name" => "gameplay.sbtech.xc_polartaleslots",
		// 				"external_game_id" => "xc_polartaleslots"),
		// 			array("english_name" => "Run Chicken Run",
		// 				"game_code" => "xc_henhouseslots",
		// 				"game_name" => "gameplay.sbtech.xc_henhouseslots",
		// 				"external_game_id" => "xc_henhouseslots"),
		// 			array("english_name" => "Space Robbers",
		// 				"game_code" => "xc_spacerobbersslots",
		// 				"game_name" => "gameplay.sbtech.xc_spacerobbersslots",
		// 				"external_game_id" => "xc_spacerobbersslots"),
		// 			array("english_name" => "Spin the World",
		// 				"game_code" => "xc_spintheworldslots",
		// 				"game_name" => "gameplay.sbtech.xc_spintheworldslots",
		// 				"external_game_id" => "xc_spintheworldslots"),
		// 			array("english_name" => "Summer Dream",
		// 				"game_code" => "xc_summerdreamslots",
		// 				"game_name" => "gameplay.sbtech.xc_summerdreamslots",
		// 				"external_game_id" => "xc_summerdreamslots"),
		// 			array("english_name" => "Totem Quest",
		// 				"game_code" => "xc_totemquestslots",
		// 				"game_name" => "gameplay.sbtech.xc_totemquestslots",
		// 				"external_game_id" => "xc_totemquestslots"),
		// 			array("english_name" => "Vampire Slayers",
		// 				"game_code" => "xc_vampireslayersslots",
		// 				"game_name" => "gameplay.sbtech.xc_vampireslayersslots",
		// 				"external_game_id" => "xc_vampireslayersslots"),
		// 			array("english_name" => "World-Cup Soccer Spins",
		// 				"game_code" => "xc_soccerslots",
		// 				"game_name" => "gameplay.sbtech.xc_soccerslots",
		// 				"external_game_id" => "xc_soccerslots"),
		// 			array("english_name" => "Pipezillas Slots",
		// 				"game_code" => "xc_pipezillasslots",
		// 				"game_name" => "gameplay.sbtech.xc_pipezillasslots",
		// 				"external_game_id" => "xc_pipezillasslots"),
		// 			array("english_name" => "Double Bonus Slots",
		// 				"game_code" => "xc_doublebonusslots",
		// 				"game_name" => "gameplay.sbtech.xc_doublebonusslots",
		// 				"external_game_id" => "xc_doublebonusslots"),
		// 			array("english_name" => "Maya Wheel of Luck",
		// 				"game_code" => "xc_mayawheelofluckslots",
		// 				"game_name" => "gameplay.sbtech.xc_mayawheelofluckslots",
		// 				"external_game_id" => "xc_mayawheelofluckslots"),
		// 			array("english_name" => "East Wind Battle",
		// 				"game_code" => "xc_eastwindbattleslots95",
		// 				"game_name" => "gameplay.sbtech.xc_eastwindbattleslots95",
		// 				"external_game_id" => "xc_eastwindbattleslots95"),
		// 			array("english_name" => "Maverick Saloon Slots",
		// 				"game_code" => "xc_mavericksaloonslots",
		// 				"game_name" => "gameplay.sbtech.xc_mavericksaloonslots",
		// 				"external_game_id" => "xc_mavericksaloonslots"),
		// 			array("english_name" => "Buffalo Slots",
		// 				"game_code" => "xc_buffaloslots",
		// 				"game_name" => "gameplay.sbtech.xc_buffaloslots",
		// 				"external_game_id" => "xc_buffaloslots"),
		// 			array("english_name" => "Magic of Oz",
		// 				"game_code" => "xc_magicofozslots",
		// 				"game_name" => "gameplay.sbtech.xc_magicofozslots",
		// 				"external_game_id" => "xc_magicofozslots"),
		// 			array("english_name" => "Cash Out Fortune",
		// 				"game_code" => "xc_fortunecashout",
		// 				"game_name" => "gameplay.sbtech.xc_fortunecashout",
		// 				"external_game_id" => "xc_fortunecashout"),
		// 			array("english_name" => "Jour Del Amour Slots",
		// 				"game_code" => "xc_jourdelamourslots",
		// 				"game_name" => "gameplay.sbtech.xc_jourdelamourslots",
		// 				"external_game_id" => "xc_jourdelamourslots"),
		// 		),
		// 	),
		// 	array(
		// 		'game_type' => 'Table Games',
		// 		'game_type_lang' => 'gameplay_sbtech_table_games',
		// 		'status' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'game_description_list' => array(
		// 			array("english_name" => "American Roulette",
		// 				"game_code" => "xc_americanroulette",
		// 				"game_name" => "gameplay.sbtech.xc_americanroulette",
		// 				"external_game_id" => "xc_americanroulette"),
		// 			array("english_name" => "European Roulette",
		// 				"game_code" => "xc_euroulette",
		// 				"game_name" => "gameplay.sbtech.xc_euroulette",
		// 				"external_game_id" => "xc_euroulette"),
		// 			array("english_name" => "Roulette Pro",
		// 				"game_code" => "xc_euroulettepro",
		// 				"game_name" => "gameplay.sbtech.xc_euroulettepro",
		// 				"external_game_id" => "xc_euroulettepro"),
		// 			array("english_name" => "Sic Bo",
		// 				"game_code" => "xc_sic_bo",
		// 				"game_name" => "gameplay.sbtech.xc_sic_bo",
		// 				"external_game_id" => "xc_sic_bo"),
		// 		),
		// 	),
		// 	array(
		// 		'game_type' => 'Video Poker',
		// 		'game_type_lang' => 'gameplay_sbtech_video_poker',
		// 		'status' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'game_description_list' => array(
		// 			array("english_name" => "Deuces Wild",
		// 				"game_code" => "xc_deuceswild",
		// 				"game_name" => "gameplay.sbtech.xc_deuceswild",
		// 				"external_game_id" => "xc_deuceswild"),
		// 			array("english_name" => "Deuces Wild 10-Line",
		// 				"game_code" => "xc_deuceswild10l",
		// 				"game_name" => "gameplay.sbtech.xc_deuceswild10l",
		// 				"external_game_id" => "xc_deuceswild10l"),
		// 			array("english_name" => "Deuces Wild 25-Line",
		// 				"game_code" => "xc_deuceswild25l",
		// 				"game_name" => "gameplay.sbtech.xc_deuceswild25l",
		// 				"external_game_id" => "xc_deuceswild25l"),
		// 			array("english_name" => "Deuces Wild 4-Line",
		// 				"game_code" => "xc_deuceswild4l",
		// 				"game_name" => "gameplay.sbtech.xc_deuceswild4l",
		// 				"external_game_id" => "xc_deuceswild4l"),
		// 			array("english_name" => "Deuces Wild 50-Line",
		// 				"game_code" => "xc_deuceswild50l",
		// 				"game_name" => "gameplay.sbtech.xc_deuceswild50l",
		// 				"external_game_id" => "xc_deuceswild50l"),
		// 			array("english_name" => "Face the Ace",
		// 				"game_code" => "xc_faceace",
		// 				"game_name" => "gameplay.sbtech.xc_faceace",
		// 				"external_game_id" => "xc_faceace"),
		// 			array("english_name" => "Face the Ace 10-Line",
		// 				"game_code" => "xc_faceace10l",
		// 				"game_name" => "gameplay.sbtech.xc_faceace10l",
		// 				"external_game_id" => "xc_faceace10l"),
		// 			array("english_name" => "Face the Ace 25-Line",
		// 				"game_code" => "xc_faceace25l",
		// 				"game_name" => "gameplay.sbtech.xc_faceace25l",
		// 				"external_game_id" => "xc_faceace25l"),
		// 			array("english_name" => "Face the Ace 4-Line",
		// 				"game_code" => "xc_faceace4l",
		// 				"game_name" => "gameplay.sbtech.xc_faceace4l",
		// 				"external_game_id" => "xc_faceace4l"),
		// 			array("english_name" => "Face the Ace 50-Line",
		// 				"game_code" => "xc_faceace50l",
		// 				"game_name" => "gameplay.sbtech.xc_faceace50l",
		// 				"external_game_id" => "xc_faceace50l"),
		// 			array("english_name" => "Five Aces",
		// 				"game_code" => "xc_fiveaces",
		// 				"game_name" => "gameplay.sbtech.xc_fiveaces",
		// 				"external_game_id" => "xc_fiveaces"),
		// 			array("english_name" => "Jacks or Better",
		// 				"game_code" => "xc_jacksorbetter",
		// 				"game_name" => "gameplay.sbtech.xc_jacksorbetter",
		// 				"external_game_id" => "xc_jacksorbetter"),
		// 			array("english_name" => "Jacks or Better 10-Line",
		// 				"game_code" => "xc_jacksorbetter10l",
		// 				"game_name" => "gameplay.sbtech.xc_jacksorbetter10l",
		// 				"external_game_id" => "xc_jacksorbetter10l"),
		// 			array("english_name" => "Jacks or Better 25-Line",
		// 				"game_code" => "xc_jacksorbetter25l",
		// 				"game_name" => "gameplay.sbtech.xc_jacksorbetter25l",
		// 				"external_game_id" => "xc_jacksorbetter25l"),
		// 			array("english_name" => "Jacks or Better 4-Line",
		// 				"game_code" => "xc_jacksorbetter4l",
		// 				"game_name" => "gameplay.sbtech.xc_jacksorbetter4l",
		// 				"external_game_id" => "xc_jacksorbetter4l"),
		// 			array("english_name" => "Jacks or Better 50-Line",
		// 				"game_code" => "xc_jacksorbetter50l",
		// 				"game_name" => "gameplay.sbtech.xc_jacksorbetter50l",
		// 				"external_game_id" => "xc_jacksorbetter50l"),
		// 			array("english_name" => "Joker Wild",
		// 				"game_code" => "xc_jokerwild",
		// 				"game_name" => "gameplay.sbtech.xc_jokerwild",
		// 				"external_game_id" => "xc_jokerwild"),
		// 			array("english_name" => "Joker Wild 10-Line",
		// 				"game_code" => "xc_jokerwild10l",
		// 				"game_name" => "gameplay.sbtech.xc_jokerwild10l",
		// 				"external_game_id" => "xc_jokerwild10l"),
		// 			array("english_name" => "Joker Wild 25-Line",
		// 				"game_code" => "xc_jokerwild25l",
		// 				"game_name" => "gameplay.sbtech.xc_jokerwild25l",
		// 				"external_game_id" => "xc_jokerwild25l"),
		// 			array("english_name" => "Joker Wild 4-Line",
		// 				"game_code" => "xc_jokerwild4l",
		// 				"game_name" => "gameplay.sbtech.xc_jokerwild4l",
		// 				"external_game_id" => "xc_jokerwild4l"),
		// 			array("english_name" => "Joker Wild 50-Line",
		// 				"game_code" => "xc_jokerwild50l",
		// 				"game_name" => "gameplay.sbtech.xc_jokerwild50l",
		// 				"external_game_id" => "xc_jokerwild50l"),
		// 			array("english_name" => "Shockwave Poker",
		// 				"game_code" => "xc_shockwave",
		// 				"game_name" => "gameplay.sbtech.xc_shockwave",
		// 				"external_game_id" => "xc_shockwave"),
		// 		),
		// 	),

		// 	array(
		// 		'game_type' => 'unknown',
		// 		'game_type_lang' => 'gameplay.sbtech.unknown',
		// 		'status' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_FALSE,
		// 		'game_description_list' => array(
		// 			array('game_name' => 'gameplay.sbtech.unknown',
		// 				'english_name' => 'Unknown Gameplay Sbtech Game',
		// 				'external_game_id' => 'unknown',
		// 				'game_code' => 'unknown',
		// 			),

		// 		),
		// 	),

		// );

		// $game_description_list = array();
		// foreach ($data as $game_type) {
		// 	$this->db->insert('game_type', array(
		// 		'game_platform_id' => GAMEPLAY_API,
		// 		'game_type' => $game_type['game_type'],
		// 		'game_type_lang' => $game_type['game_type_lang'],
		// 		'status' => $game_type['status'],
		// 		'flag_show_in_site' => $game_type['flag_show_in_site'],
		// 	));

		// 	$game_type_id = $this->db->insert_id();
		// 	foreach ($game_type['game_description_list'] as $game_description) {
		// 		$game_description_list[] = array_merge(array(
		// 			'game_platform_id' => GAMEPLAY_API,
		// 			'game_type_id' => $game_type_id,
		// 		), $game_description);
		// 	}
		// }

		// $this->db->insert_batch('game_description', $game_description_list);
		// $this->db->trans_complete();

	}

	public function down() {
		// $this->db->trans_start();
		// $this->db->delete('game_type', array('game_platform_id' => GAMEPLAY_API));
		// $this->db->delete('game_description', array('game_platform_id' => GAMEPLAY_API));
		// $this->db->trans_complete();
	}
}