<?php

defined('BASEPATH') OR exit('No direct script access allowed');

class Migration_add_bs_in_game_description_and_game_type_20160421 extends CI_Migration {

	const FLAG_TRUE = 1;
	const FLAG_FALSE = 0;

	public function up() {
		// $this->db->trans_start();

		// $data = array(
		// 	BS_API => array(
		// 		array(
		// 			'game_type' => array(
		// 				'game_type' 		=> 'Video Poker',
		// 				'game_type_lang' 	=> 'Video Poker',
		// 				'status' 			=> self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_FALSE,
		// 			),
		// 			'game_description' => array(
		// 				array(
		// 					'game_name' => 'Five Draw Poker',
		// 					'english_name' => 'Five Draw Poker',
		// 					'external_game_id' => 23,
		// 					'game_code' => 23,
		// 				),
		// 				array(
		// 					'game_name' => 'Deuces Wild',
		// 					'english_name' => 'Deuces Wild',
		// 					'external_game_id' => 29,
		// 					'game_code' => 29,
		// 				),
		// 				array(
		// 					'game_name' => 'Jacks Or Better',
		// 					'english_name' => 'Jacks Or Better',
		// 					'external_game_id' => 31,
		// 					'game_code' => 31,
		// 				),
		// 				array(
		// 					'game_name' => 'Joker Poker',
		// 					'english_name' => 'Joker Poker',
		// 					'external_game_id' => 30,
		// 					'game_code' => 30,
		// 				),
		// 				array(
		// 					'game_name' => 'All American',
		// 					'english_name' => 'All American',
		// 					'external_game_id' => 46,
		// 					'game_code' => 46,
		// 				),
		// 				array(
		// 					'game_name' => 'Deuces Wild Windows Phone',
		// 					'english_name' => 'Deuces Wild Windows Phone',
		// 					'external_game_id' => 541,
		// 					'game_code' => 541,
		// 				),
		// 				array(
		// 					'game_name' => 'Deuces Wild Android',
		// 					'english_name' => 'Deuces Wild Android',
		// 					'external_game_id' => 540,
		// 					'game_code' => 540,
		// 				),
		// 				array(
		// 					'game_name' => 'Deuces Wild Mobile',
		// 					'english_name' => 'Deuces Wild Mobile',
		// 					'external_game_id' => 539,
		// 					'game_code' => 539,
		// 				),
		// 				array(
		// 					'game_name' => 'Bonus Poker',
		// 					'english_name' => 'Bonus Poker',
		// 					'external_game_id' => 137,
		// 					'game_code' => 137,
		// 				),
		// 				array(
		// 					'game_name' => 'Double Bonus',
		// 					'english_name' => 'Double Bonus',
		// 					'external_game_id' => 139,
		// 					'game_code' => 139,
		// 				),
		// 				array(
		// 					'game_name' => 'Split Way Royal',
		// 					'english_name' => 'Split Way Royal',
		// 					'external_game_id' => 142,
		// 					'game_code' => 142,
		// 				),
		// 				array(
		// 					'game_name' => 'Double Joker',
		// 					'english_name' => 'Double Joker',
		// 					'external_game_id' => 144,
		// 					'game_code' => 144,
		// 				),
		// 				array(
		// 					'game_name' => 'Bonus Deuces',
		// 					'english_name' => 'Bonus Deuces',
		// 					'external_game_id' => 145,
		// 					'game_code' => 145,
		// 				),
		// 				array(
		// 					'game_name' => 'Tens or Better',
		// 					'english_name' => 'Tens or Better',
		// 					'external_game_id' => 146,
		// 					'game_code' => 146,
		// 				),
		// 				array(
		// 					'game_name' => 'Deuces And Jokers',
		// 					'english_name' => 'Deuces And Jokers',
		// 					'external_game_id' => 147,
		// 					'game_code' => 147,
		// 				),
		// 			),
		// 		),
		// 		##############################################################################################################
		// 		array(
		// 			'game_type' => array(
		// 				'game_type' 		=> 'Multihand Poker',
		// 				'game_type_lang' 	=> 'Multihand Poker',
		// 				'status' 			=> self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_FALSE,
		// 			),
		// 			'game_description' => array(
		// 				array(
		// 					'game_name' => 'Five Draw Poker',
		// 					'english_name' => 'Five Draw Poker',
		// 					'external_game_id' => 23,
		// 					'game_code' => 23,
		// 				),
		// 				array(
		// 					'game_name' => 'Deuces Wild',
		// 					'english_name' => 'Deuces Wild',
		// 					'external_game_id' => 29,
		// 					'game_code' => 29,
		// 				),
		// 				array(
		// 					'game_name' => 'Jacks Or Better',
		// 					'english_name' => 'Jacks Or Better',
		// 					'external_game_id' => 31,
		// 					'game_code' => 31,
		// 				),
		// 				array(
		// 					'game_name' => 'Joker Poker',
		// 					'english_name' => 'Joker Poker',
		// 					'external_game_id' => 30,
		// 					'game_code' => 30,
		// 				),
		// 				array(
		// 					'game_name' => 'All American',
		// 					'english_name' => 'All American',
		// 					'external_game_id' => 46,
		// 					'game_code' => 46,
		// 				),
		// 				array(
		// 					'game_name' => 'Deuces Wild Windows Phone',
		// 					'english_name' => 'Deuces Wild Windows Phone',
		// 					'external_game_id' => 541,
		// 					'game_code' => 541,
		// 				),
		// 				array(
		// 					'game_name' => 'Deuces Wild Android',
		// 					'english_name' => 'Deuces Wild Android',
		// 					'external_game_id' => 540,
		// 					'game_code' => 540,
		// 				),
		// 				array(
		// 					'game_name' => 'Deuces Wild Mobile',
		// 					'english_name' => 'Deuces Wild Mobile',
		// 					'external_game_id' => 539,
		// 					'game_code' => 539,
		// 				),
		// 				array(
		// 					'game_name' => 'Bonus Poker',
		// 					'english_name' => 'Bonus Poker',
		// 					'external_game_id' => 137,
		// 					'game_code' => 137,
		// 				),
		// 				array(
		// 					'game_name' => 'Double Bonus',
		// 					'english_name' => 'Double Bonus',
		// 					'external_game_id' => 139,
		// 					'game_code' => 139,
		// 				),
		// 				array(
		// 					'game_name' => 'Split Way Royal',
		// 					'english_name' => 'Split Way Royal',
		// 					'external_game_id' => 142,
		// 					'game_code' => 142,
		// 				),
		// 				array(
		// 					'game_name' => 'Double Joker',
		// 					'english_name' => 'Double Joker',
		// 					'external_game_id' => 144,
		// 					'game_code' => 144,
		// 				),
		// 				array(
		// 					'game_name' => 'Bonus Deuces',
		// 					'english_name' => 'Bonus Deuces',
		// 					'external_game_id' => 145,
		// 					'game_code' => 145,
		// 				),
		// 				array(
		// 					'game_name' => 'Tens or Better',
		// 					'english_name' => 'Tens or Better',
		// 					'external_game_id' => 146,
		// 					'game_code' => 146,
		// 				),
		// 				array(
		// 					'game_name' => 'Deuces And Jokers',
		// 					'english_name' => 'Deuces And Jokers',
		// 					'external_game_id' => 147,
		// 					'game_code' => 147,
		// 				),
		// 			),

		// 		),
		// 		##############################################################################################################
		// 		array(
		// 			'game_type' => array(
		// 				'game_type' 		=> 'Soft Games',
		// 				'game_type_lang' 	=> 'Soft Games',
		// 				'status' 			=> self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_FALSE,
		// 			),
		// 			'game_description' => array(
		// 				array(
		// 					'game_name' => 'Scratcherz',
		// 					'english_name' => 'Scratcherz',
		// 					'external_game_id' => 143,
		// 					'game_code' => 143,
		// 				),
		// 				array(
		// 					'game_name' => 'Virtual Racebook 3D',
		// 					'english_name' => 'Virtual Racebook 3D',
		// 					'external_game_id' => 199,
		// 					'game_code' => 199,
		// 				),
		// 			),
		// 		),
		// 		##############################################################################################################
		// 		array(
		// 			'game_type' => array(
		// 				'game_type' 		=> 'Slots',
		// 				'game_type_lang' 	=> 'Slots',
		// 				'status' 			=> self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_FALSE,
		// 			),
		// 			'game_description' => array(
		// 				array(
		// 					'game_name' => 'Event Horizon Android',
		// 					'english_name' => 'Event Horizon Android',
		// 					'external_game_id' => 550,
		// 					'game_code' => 550,
		// 				),
		// 				array(
		// 					'game_name' => 'Event Horizon Windows Phone',
		// 					'english_name' => 'Event Horizon Windows Phone',
		// 					'external_game_id' => 551,
		// 					'game_code' => 551,
		// 				),
		// 				array(
		// 					'game_name' => 'Event Horizon',
		// 					'english_name' => 'Event Horizon',
		// 					'external_game_id' => 548,
		// 					'game_code' => 548,
		// 				),
		// 				array(
		// 					'game_name' => 'Lucky Seven',
		// 					'english_name' => 'Lucky Seven',
		// 					'external_game_id' => 2,
		// 					'game_code' => 2,
		// 				),
		// 				array(
		// 					'game_name' => 'Event Horizon Mobile',
		// 					'english_name' => 'Event Horizon Mobile',
		// 					'external_game_id' => 549,
		// 					'game_code' => 549,
		// 				),
		// 				array(
		// 					'game_name' => 'Slots Angels Android',
		// 					'english_name' => 'Slots Angels Android',
		// 					'external_game_id' => 546,
		// 					'game_code' => 546,
		// 				),
		// 				array(
		// 					'game_name' => 'Slots Angels Windows Phone',
		// 					'english_name' => 'Slots Angels Windows Phone',
		// 					'external_game_id' => 547,
		// 					'game_code' => 547,
		// 				),
		// 				array(
		// 					'game_name' => '7th Heaven Windows Phone',
		// 					'english_name' => '7th Heaven Windows Phone',
		// 					'external_game_id' => 544,
		// 					'game_code' => 544,
		// 				),
		// 				array(
		// 					'game_name' => 'Slots Angels Mobile',
		// 					'english_name' => 'Slots Angels Mobile',
		// 					'external_game_id' => 545,
		// 					'game_code' => 545,
		// 				),
		// 				array(
		// 					'game_name' => 'Mega Glam Life JP',
		// 					'english_name' => 'Mega Glam Life JP',
		// 					'external_game_id' => 554,
		// 					'game_code' => 554,
		// 				),
		// 				array(
		// 					'game_name' => 'Alkemor\'s Tower',
		// 					'english_name' => 'Alkemor\'s Tower',
		// 					'external_game_id' => 553,
		// 					'game_code' => 553,
		// 				),
		// 				array(
		// 					'game_name' => 'Diamond Progressive',
		// 					'english_name' => 'Diamond Progressive',
		// 					'external_game_id' => 32,
		// 					'game_code' => 32,
		// 				),
		// 				array(
		// 					'game_name' => 'Fruit Zen',
		// 					'english_name' => 'Fruit Zen',
		// 					'external_game_id' => 512,
		// 					'game_code' => 512,
		// 				),
		// 				array(
		// 					'game_name' => 'Fruit Zen Mobile',
		// 					'english_name' => 'Fruit Zen Mobile',
		// 					'external_game_id' => 513,
		// 					'game_code' => 513,
		// 				),
		// 				array(
		// 					'game_name' => 'Fruit Zen Android',
		// 					'english_name' => 'Fruit Zen Android',
		// 					'external_game_id' => 514,
		// 					'game_code' => 514,
		// 				),
		// 				array(
		// 					'game_name' => 'Fruit Zen Windows Phone',
		// 					'english_name' => 'Fruit Zen Windows Phone',
		// 					'external_game_id' => 515,
		// 					'game_code' => 515,
		// 				),
		// 				array(
		// 					'game_name' => 'Once Upon A Time Mobile',
		// 					'english_name' => 'Once Upon A Time Mobile',
		// 					'external_game_id' => 524,
		// 					'game_code' => 524,
		// 				),
		// 				array(
		// 					'game_name' => 'Once Upon A Time Android',
		// 					'english_name' => 'Once Upon A Time Android',
		// 					'external_game_id' => 525,
		// 					'game_code' => 525,
		// 				),
		// 				array(
		// 					'game_name' => 'Once Upon A Time Windows Phone',
		// 					'english_name' => 'Once Upon A Time Windows Phone',
		// 					'external_game_id' => 526,
		// 					'game_code' => 526,
		// 				),
		// 				array(
		// 					'game_name' => 'Jackpot Jamba',
		// 					'english_name' => 'Jackpot Jamba',
		// 					'external_game_id' => 41,
		// 					'game_code' => 41,
		// 				),
		// 				array(
		// 					'game_name' => 'Pinocchio',
		// 					'english_name' => 'Pinocchio',
		// 					'external_game_id' => 520,
		// 					'game_code' => 520,
		// 				),
		// 				array(
		// 					'game_name' => 'Pinocchio Mobile',
		// 					'english_name' => 'Pinocchio Mobile',
		// 					'external_game_id' => 521,
		// 					'game_code' => 521,
		// 				),
		// 				array(
		// 					'game_name' => 'Pinocchio Android',
		// 					'english_name' => 'Pinocchio Android',
		// 					'external_game_id' => 522,
		// 					'game_code' => 522,
		// 				),
		// 				array(
		// 					'game_name' => 'Pinocchio Windows Phone',
		// 					'english_name' => 'Pinocchio Windows Phone',
		// 					'external_game_id' => 523,
		// 					'game_code' => 523,
		// 				),
		// 				array(
		// 					'game_name' => 'Enchanted JP Windows Phone',
		// 					'english_name' => 'Enchanted JP Windows Phone',
		// 					'external_game_id' => 533,
		// 					'game_code' => 533,
		// 				),
		// 				array(
		// 					'game_name' => 'Enchanted JP Android',
		// 					'english_name' => 'Enchanted JP Android',
		// 					'external_game_id' => 532,
		// 					'game_code' => 532,
		// 				),
		// 				array(
		// 					'game_name' => 'Mega Gems Mobile',
		// 					'english_name' => 'Mega Gems Mobile',
		// 					'external_game_id' => 535,
		// 					'game_code' => 535,
		// 				),
		// 				array(
		// 					'game_name' => 'Mega Gems',
		// 					'english_name' => 'Mega Gems',
		// 					'external_game_id' => 534,
		// 					'game_code' => 534,
		// 				),
		// 				array(
		// 					'game_name' => 'Enchanted JP Mobile',
		// 					'english_name' => 'Enchanted JP Mobile',
		// 					'external_game_id' => 531,
		// 					'game_code' => 531,
		// 				),
		// 				array(
		// 					'game_name' => '7th Heaven Android',
		// 					'english_name' => '7th Heaven Android',
		// 					'external_game_id' => 543,
		// 					'game_code' => 543,
		// 				),
		// 				array(
		// 					'game_name' => '7th Heaven Mobile',
		// 					'english_name' => '7th Heaven Mobile',
		// 					'external_game_id' => 542,
		// 					'game_code' => 542,
		// 				),
		// 				array(
		// 					'game_name' => 'Mega Gems Windows Phone',
		// 					'english_name' => 'Mega Gems Windows Phone',
		// 					'external_game_id' => 537,
		// 					'game_code' => 537,
		// 				),
		// 				array(
		// 					'game_name' => 'Mega Gems Android',
		// 					'english_name' => 'Mega Gems Android',
		// 					'external_game_id' => 536,
		// 					'game_code' => 536,
		// 				),
		// 				array(
		// 					'game_name' => 'Glam Life Mobile',
		// 					'english_name' => 'Glam Life Mobile',
		// 					'external_game_id' => 610,
		// 					'game_code' => 610,
		// 				),
		// 				array(
		// 					'game_name' => 'Glam Life Android',
		// 					'english_name' => 'Glam Life Android',
		// 					'external_game_id' => 611,
		// 					'game_code' => 611,
		// 				),
		// 				array(
		// 					'game_name' => 'At the Movies Android',
		// 					'english_name' => 'At the Movies Android',
		// 					'external_game_id' => 608,
		// 					'game_code' => 608,
		// 				),
		// 				array(
		// 					'game_name' => 'At the Movies Windows Phone',
		// 					'english_name' => 'At the Movies Windows Phone',
		// 					'external_game_id' => 609,
		// 					'game_code' => 609,
		// 				),
		// 				array(
		// 					'game_name' => 'Glam Life Windows Phone',
		// 					'english_name' => 'Glam Life Windows Phone',
		// 					'external_game_id' => 612,
		// 					'game_code' => 612,
		// 				),
		// 				array(
		// 					'game_name' => '2 Million B.C. Windows Phone',
		// 					'english_name' => '2 Million B.C. Windows Phone',
		// 					'external_game_id' => 618,
		// 					'game_code' => 618,
		// 				),
		// 				array(
		// 					'game_name' => 'A Christmas Carol',
		// 					'english_name' => 'A Christmas Carol',
		// 					'external_game_id' => 619,
		// 					'game_code' => 619,
		// 				),
		// 				array(
		// 					'game_name' => '2 Million B.C. Mobile',
		// 					'english_name' => '2 Million B.C. Mobile',
		// 					'external_game_id' => 616,
		// 					'game_code' => 616,
		// 				),
		// 				array(
		// 					'game_name' => '2 Million B.C. Android',
		// 					'english_name' => '2 Million B.C. Android',
		// 					'external_game_id' => 617,
		// 					'game_code' => 617,
		// 				),
		// 				array(
		// 					'game_name' => 'A Christmas Carol Windows Phone',
		// 					'english_name' => 'A Christmas Carol Windows Phone',
		// 					'external_game_id' => 622,
		// 					'game_code' => 622,
		// 				),
		// 				array(
		// 					'game_name' => 'A Christmas Carol Mobile',
		// 					'english_name' => 'A Christmas Carol Mobile',
		// 					'external_game_id' => 620,
		// 					'game_code' => 620,
		// 				),
		// 				array(
		// 					'game_name' => 'A Christmas Carol Android',
		// 					'english_name' => 'A Christmas Carol Android',
		// 					'external_game_id' => 621,
		// 					'game_code' => 621,
		// 				),
		// 				array(
		// 					'game_name' => 'Barbary Coast Mobile',
		// 					'english_name' => 'Barbary Coast Mobile',
		// 					'external_game_id' => 627,
		// 					'game_code' => 627,
		// 				),
		// 				array(
		// 					'game_name' => 'Barbary Coast Windows Phone',
		// 					'english_name' => 'Barbary Coast Windows Phone',
		// 					'external_game_id' => 629,
		// 					'game_code' => 629,
		// 				),
		// 				array(
		// 					'game_name' => 'Barbary Coast Android',
		// 					'english_name' => 'Barbary Coast Android',
		// 					'external_game_id' => 628,
		// 					'game_code' => 628,
		// 				),
		// 				array(
		// 					'game_name' => '4 Seasons Android',
		// 					'english_name' => '4 Seasons Android',
		// 					'external_game_id' => 639,
		// 					'game_code' => 639,
		// 				),
		// 				array(
		// 					'game_name' => '4 Seasons Mobile',
		// 					'english_name' => '4 Seasons Mobile',
		// 					'external_game_id' => 638,
		// 					'game_code' => 638,
		// 				),
		// 				array(
		// 					'game_name' => '4 Seasons',
		// 					'english_name' => '4 Seasons',
		// 					'external_game_id' => 637,
		// 					'game_code' => 637,
		// 				),
		// 				array(
		// 					'game_name' => 'Mamma Mia Mobile',
		// 					'english_name' => 'Mamma Mia Mobile',
		// 					'external_game_id' => 584,
		// 					'game_code' => 584,
		// 				),
		// 				array(
		// 					'game_name' => 'Mamma Mia Android',
		// 					'english_name' => 'Mamma Mia Android',
		// 					'external_game_id' => 585,
		// 					'game_code' => 585,
		// 				),
		// 				array(
		// 					'game_name' => 'Mamma Mia Windows Phone',
		// 					'english_name' => 'Mamma Mia Windows Phone',
		// 					'external_game_id' => 586,
		// 					'game_code' => 586,
		// 				),
		// 				array(
		// 					'game_name' => 'Mega Glam Life JP Mobile',
		// 					'english_name' => 'Mega Glam Life JP Mobile',
		// 					'external_game_id' => 587,
		// 					'game_code' => 587,
		// 				),
		// 				array(
		// 					'game_name' => 'Mega Glam Life JP Android',
		// 					'english_name' => 'Mega Glam Life JP Android',
		// 					'external_game_id' => 588,
		// 					'game_code' => 588,
		// 				),
		// 				array(
		// 					'game_name' => 'Mega Glam Life JP Windows Phone',
		// 					'english_name' => 'Mega Glam Life JP Windows Phone',
		// 					'external_game_id' => 589,
		// 					'game_code' => 589,
		// 				),
		// 				array(
		// 					'game_name' => 'Weekend In Vegas',
		// 					'english_name' => 'Weekend In Vegas',
		// 					'external_game_id' => 590,
		// 					'game_code' => 590,
		// 				),
		// 				array(
		// 					'game_name' => 'Weekend In Vegas Mobile',
		// 					'english_name' => 'Weekend In Vegas Mobile',
		// 					'external_game_id' => 591,
		// 					'game_code' => 591,
		// 				),
		// 				array(
		// 					'game_name' => 'Weekend In Vegas Windows Phone',
		// 					'english_name' => 'Weekend In Vegas Windows Phone',
		// 					'external_game_id' => 593,
		// 					'game_code' => 593,
		// 				),
		// 				array(
		// 					'game_name' => 'Weekend In Vegas Android',
		// 					'english_name' => 'Weekend In Vegas Android',
		// 					'external_game_id' => 592,
		// 					'game_code' => 592,
		// 				),
		// 				array(
		// 					'game_name' => 'The Tipsy Tourist',
		// 					'english_name' => 'The Tipsy Tourist',
		// 					'external_game_id' => 597,
		// 					'game_code' => 597,
		// 				),
		// 				array(
		// 					'game_name' => 'The Tipsy Tourist Android',
		// 					'english_name' => 'The Tipsy Tourist Android',
		// 					'external_game_id' => 599,
		// 					'game_code' => 599,
		// 				),
		// 				array(
		// 					'game_name' => 'The Tipsy Tourist Mobile',
		// 					'english_name' => 'The Tipsy Tourist Mobile',
		// 					'external_game_id' => 598,
		// 					'game_code' => 598,
		// 				),
		// 				array(
		// 					'game_name' => 'Black Gold Mobile',
		// 					'english_name' => 'Black Gold Mobile',
		// 					'external_game_id' => 601,
		// 					'game_code' => 601,
		// 				),
		// 				array(
		// 					'game_name' => 'The Tipsy Tourist Windows Phone',
		// 					'english_name' => 'The Tipsy Tourist Windows Phone',
		// 					'external_game_id' => 600,
		// 					'game_code' => 600,
		// 				),
		// 				array(
		// 					'game_name' => 'Black Gold Windows Phone',
		// 					'english_name' => 'Black Gold Windows Phone',
		// 					'external_game_id' => 603,
		// 					'game_code' => 603,
		// 				),
		// 				array(
		// 					'game_name' => 'Black Gold Android',
		// 					'english_name' => 'Black Gold Android',
		// 					'external_game_id' => 602,
		// 					'game_code' => 602,
		// 				),
		// 				array(
		// 					'game_name' => 'Alkemor\'s Tower Android',
		// 					'english_name' => 'Alkemor\'s Tower Android',
		// 					'external_game_id' => 605,
		// 					'game_code' => 605,
		// 				),
		// 				array(
		// 					'game_name' => 'Alkemor\'s Tower Mobile',
		// 					'english_name' => 'Alkemor\'s Tower Mobile',
		// 					'external_game_id' => 604,
		// 					'game_code' => 604,
		// 				),
		// 				array(
		// 					'game_name' => 'At the Movies Mobile',
		// 					'english_name' => 'At the Movies Mobile',
		// 					'external_game_id' => 607,
		// 					'game_code' => 607,
		// 				),
		// 				array(
		// 					'game_name' => 'Alkemor\'s Tower Windows Phone',
		// 					'english_name' => 'Alkemor\'s Tower Windows Phone',
		// 					'external_game_id' => 606,
		// 					'game_code' => 606,
		// 				),
		// 				array(
		// 					'game_name' => 'The Ghouls',
		// 					'english_name' => 'The Ghouls',
		// 					'external_game_id' => 156,
		// 					'game_code' => 156,
		// 				),
		// 				array(
		// 					'game_name' => 'Treasure Room',
		// 					'english_name' => 'Treasure Room',
		// 					'external_game_id' => 158,
		// 					'game_code' => 158,
		// 				),
		// 				array(
		// 					'game_name' => 'Mad Scientist',
		// 					'english_name' => 'Mad Scientist',
		// 					'external_game_id' => 159,
		// 					'game_code' => 159,
		// 				),
		// 				array(
		// 					'game_name' => 'Glam Life',
		// 					'english_name' => 'Glam Life',
		// 					'external_game_id' => 173,
		// 					'game_code' => 173,
		// 				),
		// 				array(
		// 					'game_name' => 'Frankenslot\'s Monster',
		// 					'english_name' => 'Frankenslot\'s Monster',
		// 					'external_game_id' => 647,
		// 					'game_code' => 647,
		// 				),
		// 				array(
		// 					'game_name' => '4 Seasons Windows Phone',
		// 					'english_name' => '4 Seasons Windows Phone',
		// 					'external_game_id' => 640,
		// 					'game_code' => 640,
		// 				),
		// 				array(
		// 					'game_name' => 'Aztec Treasures',
		// 					'english_name' => 'Aztec Treasures',
		// 					'external_game_id' => 190,
		// 					'game_code' => 190,
		// 				),
		// 				array(
		// 					'game_name' => 'Gladiator',
		// 					'english_name' => 'Gladiator',
		// 					'external_game_id' => 178,
		// 					'game_code' => 178,
		// 				),
		// 				array(
		// 					'game_name' => 'Genie\'s Fortune',
		// 					'english_name' => 'Genie\'s Fortune',
		// 					'external_game_id' => 177,
		// 					'game_code' => 177,
		// 				),
		// 				array(
		// 					'game_name' => 'Heist',
		// 					'english_name' => 'Heist',
		// 					'external_game_id' => 180,
		// 					'game_code' => 180,
		// 				),
		// 				array(
		// 					'game_name' => 'Once Upon A Time',
		// 					'english_name' => 'Once Upon A Time',
		// 					'external_game_id' => 193,
		// 					'game_code' => 193,
		// 				),
		// 				array(
		// 					'game_name' => 'Barbary Coast',
		// 					'english_name' => 'Barbary Coast',
		// 					'external_game_id' => 194,
		// 					'game_code' => 194,
		// 				),
		// 				array(
		// 					'game_name' => 'RockStar',
		// 					'english_name' => 'RockStar',
		// 					'external_game_id' => 220,
		// 					'game_code' => 220,
		// 				),
		// 				array(
		// 					'game_name' => 'House of Fun',
		// 					'english_name' => 'House of Fun',
		// 					'external_game_id' => 221,
		// 					'game_code' => 221,
		// 				),
		// 				array(
		// 					'game_name' => 'Gold Diggers',
		// 					'english_name' => 'Gold Diggers',
		// 					'external_game_id' => 222,
		// 					'game_code' => 222,
		// 				),
		// 				array(
		// 					'game_name' => 'Royal Reels',
		// 					'english_name' => 'Royal Reels',
		// 					'external_game_id' => 223,
		// 					'game_code' => 223,
		// 				),
		// 				array(
		// 					'game_name' => 'Mr. Vegas',
		// 					'english_name' => 'Mr. Vegas',
		// 					'external_game_id' => 210,
		// 					'game_code' => 210,
		// 				),
		// 				array(
		// 					'game_name' => 'Mamma Mia',
		// 					'english_name' => 'Mamma Mia',
		// 					'external_game_id' => 238,
		// 					'game_code' => 238,
		// 				),
		// 				array(
		// 					'game_name' => 'True Illusions',
		// 					'english_name' => 'True Illusions',
		// 					'external_game_id' => 236,
		// 					'game_code' => 236,
		// 				),
		// 				array(
		// 					'game_name' => '7th Heaven',
		// 					'english_name' => '7th Heaven',
		// 					'external_game_id' => 229,
		// 					'game_code' => 229,
		// 				),
		// 				array(
		// 					'game_name' => 'Viking Age',
		// 					'english_name' => 'Viking Age',
		// 					'external_game_id' => 228,
		// 					'game_code' => 228,
		// 				),
		// 				array(
		// 					'game_name' => 'Arrival',
		// 					'english_name' => 'Arrival',
		// 					'external_game_id' => 226,
		// 					'game_code' => 226,
		// 				),
		// 				array(
		// 					'game_name' => 'Paco and the Popping Peppers',
		// 					'english_name' => 'Paco and the Popping Peppers',
		// 					'external_game_id' => 225,
		// 					'game_code' => 225,
		// 				),
		// 				array(
		// 					'game_name' => '2 Million B.C.',
		// 					'english_name' => '2 Million B.C.',
		// 					'external_game_id' => 224,
		// 					'game_code' => 224,
		// 				),
		// 				array(
		// 					'game_name' => 'Lost',
		// 					'english_name' => 'Lost',
		// 					'external_game_id' => 248,
		// 					'game_code' => 248,
		// 				),
		// 				array(
		// 					'game_name' => 'Madder Scientist',
		// 					'english_name' => 'Madder Scientist',
		// 					'external_game_id' => 247,
		// 					'game_code' => 247,
		// 				),
		// 				array(
		// 					'game_name' => 'Ned and his Friends',
		// 					'english_name' => 'Ned and his Friends',
		// 					'external_game_id' => 243,
		// 					'game_code' => 243,
		// 				),
		// 				array(
		// 					'game_name' => 'Rook\'s Revenge',
		// 					'english_name' => 'Rook\'s Revenge',
		// 					'external_game_id' => 277,
		// 					'game_code' => 277,
		// 				),
		// 				array(
		// 					'game_name' => 'Safari Sam',
		// 					'english_name' => 'Safari Sam',
		// 					'external_game_id' => 280,
		// 					'game_code' => 280,
		// 				),
		// 				array(
		// 					'game_name' => 'Slots Angels',
		// 					'english_name' => 'Slots Angels',
		// 					'external_game_id' => 258,
		// 					'game_code' => 258,
		// 				),
		// 				array(
		// 					'game_name' => 'Under the Sea',
		// 					'english_name' => 'Under the Sea',
		// 					'external_game_id' => 259,
		// 					'game_code' => 259,
		// 				),
		// 				array(
		// 					'game_name' => 'Black Gold',
		// 					'english_name' => 'Black Gold',
		// 					'external_game_id' => 256,
		// 					'game_code' => 256,
		// 				),
		// 				array(
		// 					'game_name' => 'The Exterminator',
		// 					'english_name' => 'The Exterminator',
		// 					'external_game_id' => 262,
		// 					'game_code' => 262,
		// 				),
		// 				array(
		// 					'game_name' => 'Lucky Seven Mobile',
		// 					'english_name' => 'Lucky Seven Mobile',
		// 					'external_game_id' => 263,
		// 					'game_code' => 263,
		// 				),
		// 				array(
		// 					'game_name' => 'At the Movies',
		// 					'english_name' => 'At the Movies',
		// 					'external_game_id' => 266,
		// 					'game_code' => 266,
		// 				),
		// 				array(
		// 					'game_name' => 'Mr. Vegas Android',
		// 					'english_name' => 'Mr. Vegas Android',
		// 					'external_game_id' => 270,
		// 					'game_code' => 270,
		// 				),
		// 				array(
		// 					'game_name' => 'Lucky Seven Android',
		// 					'english_name' => 'Lucky Seven Android',
		// 					'external_game_id' => 268,
		// 					'game_code' => 268,
		// 				),
		// 				array(
		// 					'game_name' => 'Mr. Vegas Mobile',
		// 					'english_name' => 'Mr. Vegas Mobile',
		// 					'external_game_id' => 269,
		// 					'game_code' => 269,
		// 				),
		// 				array(
		// 					'game_name' => 'Safari Sam Android',
		// 					'english_name' => 'Safari Sam Android',
		// 					'external_game_id' => 304,
		// 					'game_code' => 304,
		// 				),
		// 				array(
		// 					'game_name' => 'After Night Falls Android',
		// 					'english_name' => 'After Night Falls Android',
		// 					'external_game_id' => 307,
		// 					'game_code' => 307,
		// 				),
		// 				array(
		// 					'game_name' => 'After Night Falls Mobile',
		// 					'english_name' => 'After Night Falls Mobile',
		// 					'external_game_id' => 306,
		// 					'game_code' => 306,
		// 				),
		// 				array(
		// 					'game_name' => 'Under the Bed',
		// 					'english_name' => 'Under the Bed',
		// 					'external_game_id' => 308,
		// 					'game_code' => 308,
		// 				),
		// 				array(
		// 					'game_name' => 'At The Copa Mobile',
		// 					'english_name' => 'At The Copa Mobile',
		// 					'external_game_id' => 312,
		// 					'game_code' => 312,
		// 				),
		// 				array(
		// 					'game_name' => 'At The Copa Android',
		// 					'english_name' => 'At The Copa Android',
		// 					'external_game_id' => 315,
		// 					'game_code' => 315,
		// 				),
		// 				array(
		// 					'game_name' => 'Rook\'s Revenge Android',
		// 					'english_name' => 'Rook\'s Revenge Android',
		// 					'external_game_id' => 319,
		// 					'game_code' => 319,
		// 				),
		// 				array(
		// 					'game_name' => 'Rook\'s Revenge Mobile',
		// 					'english_name' => 'Rook\'s Revenge Mobile',
		// 					'external_game_id' => 318,
		// 					'game_code' => 318,
		// 				),
		// 				array(
		// 					'game_name' => 'Sushi Bar',
		// 					'english_name' => 'Sushi Bar',
		// 					'external_game_id' => 288,
		// 					'game_code' => 288,
		// 				),
		// 				array(
		// 					'game_name' => 'Genie\'s Fortune Mobile',
		// 					'english_name' => 'Genie\'s Fortune Mobile',
		// 					'external_game_id' => 291,
		// 					'game_code' => 291,
		// 				),
		// 				array(
		// 					'game_name' => 'Genie\'s Fortune Android',
		// 					'english_name' => 'Genie\'s Fortune Android',
		// 					'external_game_id' => 292,
		// 					'game_code' => 292,
		// 				),
		// 				array(
		// 					'game_name' => 'After Night Falls',
		// 					'english_name' => 'After Night Falls',
		// 					'external_game_id' => 295,
		// 					'game_code' => 295,
		// 				),
		// 				array(
		// 					'game_name' => 'At The Copa',
		// 					'english_name' => 'At The Copa',
		// 					'external_game_id' => 300,
		// 					'game_code' => 300,
		// 				),
		// 				array(
		// 					'game_name' => 'Safari Sam Mobile',
		// 					'english_name' => 'Safari Sam Mobile',
		// 					'external_game_id' => 303,
		// 					'game_code' => 303,
		// 				),
		// 				array(
		// 					'game_name' => 'Greedy Goblins Android',
		// 					'english_name' => 'Greedy Goblins Android',
		// 					'external_game_id' => 343,
		// 					'game_code' => 343,
		// 				),
		// 				array(
		// 					'game_name' => 'Greedy Goblins Mobile',
		// 					'english_name' => 'Greedy Goblins Mobile',
		// 					'external_game_id' => 342,
		// 					'game_code' => 342,
		// 				),
		// 				array(
		// 					'game_name' => 'Greedy Goblins',
		// 					'english_name' => 'Greedy Goblins',
		// 					'external_game_id' => 341,
		// 					'game_code' => 341,
		// 				),
		// 				array(
		// 					'game_name' => 'A Night in Paris JP',
		// 					'english_name' => 'A Night in Paris JP',
		// 					'external_game_id' => 351,
		// 					'game_code' => 351,
		// 				),
		// 				array(
		// 					'game_name' => 'Enchanted JP',
		// 					'english_name' => 'Enchanted JP',
		// 					'external_game_id' => 350,
		// 					'game_code' => 350,
		// 				),
		// 				array(
		// 					'game_name' => 'Slotfather JP Android',
		// 					'english_name' => 'Slotfather JP Android',
		// 					'external_game_id' => 346,
		// 					'game_code' => 346,
		// 				),
		// 				array(
		// 					'game_name' => 'Slotfather JP Mobile',
		// 					'english_name' => 'Slotfather JP Mobile',
		// 					'external_game_id' => 345,
		// 					'game_code' => 345,
		// 				),
		// 				array(
		// 					'game_name' => 'Slotfather JP',
		// 					'english_name' => 'Slotfather JP',
		// 					'external_game_id' => 344,
		// 					'game_code' => 344,
		// 				),
		// 				array(
		// 					'game_name' => 'Boomanji Mobile',
		// 					'english_name' => 'Boomanji Mobile',
		// 					'external_game_id' => 324,
		// 					'game_code' => 324,
		// 				),
		// 				array(
		// 					'game_name' => 'Boomanji Android',
		// 					'english_name' => 'Boomanji Android',
		// 					'external_game_id' => 325,
		// 					'game_code' => 325,
		// 				),
		// 				array(
		// 					'game_name' => 'Boomanji',
		// 					'english_name' => 'Boomanji',
		// 					'external_game_id' => 323,
		// 					'game_code' => 323,
		// 				),
		// 				array(
		// 					'game_name' => 'Under the Bed Mobile',
		// 					'english_name' => 'Under the Bed Mobile',
		// 					'external_game_id' => 320,
		// 					'game_code' => 320,
		// 				),
		// 				array(
		// 					'game_name' => 'Under the Bed Android',
		// 					'english_name' => 'Under the Bed Android',
		// 					'external_game_id' => 321,
		// 					'game_code' => 321,
		// 				),
		// 				array(
		// 					'game_name' => 'Safari Sam Windows Phone',
		// 					'english_name' => 'Safari Sam Windows Phone',
		// 					'external_game_id' => 373,
		// 					'game_code' => 373,
		// 				),
		// 				array(
		// 					'game_name' => 'Boomanji Windows Phone',
		// 					'english_name' => 'Boomanji Windows Phone',
		// 					'external_game_id' => 369,
		// 					'game_code' => 369,
		// 				),
		// 				array(
		// 					'game_name' => 'Rook\'s Revenge Windows Phone',
		// 					'english_name' => 'Rook\'s Revenge Windows Phone',
		// 					'external_game_id' => 368,
		// 					'game_code' => 368,
		// 				),
		// 				array(
		// 					'game_name' => 'Treasure Room Mobile',
		// 					'english_name' => 'Treasure Room Mobile',
		// 					'external_game_id' => 381,
		// 					'game_code' => 381,
		// 				),
		// 				array(
		// 					'game_name' => 'Treasure Room Windows Phone',
		// 					'english_name' => 'Treasure Room Windows Phone',
		// 					'external_game_id' => 383,
		// 					'game_code' => 383,
		// 				),
		// 				array(
		// 					'game_name' => 'Treasure Room Android',
		// 					'english_name' => 'Treasure Room Android',
		// 					'external_game_id' => 382,
		// 					'game_code' => 382,
		// 				),
		// 				array(
		// 					'game_name' => 'Slotfather JP Windows Phone',
		// 					'english_name' => 'Slotfather JP Windows Phone',
		// 					'external_game_id' => 376,
		// 					'game_code' => 376,
		// 				),
		// 				array(
		// 					'game_name' => 'Genie\'s Fortune Windows Phone',
		// 					'english_name' => 'Genie\'s Fortune Windows Phone',
		// 					'external_game_id' => 356,
		// 					'game_code' => 356,
		// 				),
		// 				array(
		// 					'game_name' => 'Greedy Goblins Windows Phone',
		// 					'english_name' => 'Greedy Goblins Windows Phone',
		// 					'external_game_id' => 353,
		// 					'game_code' => 353,
		// 				),
		// 				array(
		// 					'game_name' => 'Lucky Seven Windows Phone',
		// 					'english_name' => 'Lucky Seven Windows Phone',
		// 					'external_game_id' => 355,
		// 					'game_code' => 355,
		// 				),
		// 				array(
		// 					'game_name' => 'After Night Falls Windows Phone',
		// 					'english_name' => 'After Night Falls Windows Phone',
		// 					'external_game_id' => 364,
		// 					'game_code' => 364,
		// 				),
		// 				array(
		// 					'game_name' => 'Under the Bed Windows Phone',
		// 					'english_name' => 'Under the Bed Windows Phone',
		// 					'external_game_id' => 365,
		// 					'game_code' => 365,
		// 				),
		// 				array(
		// 					'game_name' => 'At The Copa Windows Phone',
		// 					'english_name' => 'At The Copa Windows Phone',
		// 					'external_game_id' => 361,
		// 					'game_code' => 361,
		// 				),
		// 				array(
		// 					'game_name' => 'Mr. Vegas Windows Phone',
		// 					'english_name' => 'Mr. Vegas Windows Phone',
		// 					'external_game_id' => 362,
		// 					'game_code' => 362,
		// 				),
		// 				array(
		// 					'game_name' => 'Gladiator Windows Phone',
		// 					'english_name' => 'Gladiator Windows Phone',
		// 					'external_game_id' => 408,
		// 					'game_code' => 408,
		// 				),
		// 				array(
		// 					'game_name' => 'Madder Scientist Windows Phone',
		// 					'english_name' => 'Madder Scientist Windows Phone',
		// 					'external_game_id' => 414,
		// 					'game_code' => 414,
		// 				),
		// 				array(
		// 					'game_name' => 'Madder Scientist Mobile',
		// 					'english_name' => 'Madder Scientist Mobile',
		// 					'external_game_id' => 412,
		// 					'game_code' => 412,
		// 				),
		// 				array(
		// 					'game_name' => 'Madder Scientist Android',
		// 					'english_name' => 'Madder Scientist Android',
		// 					'external_game_id' => 413,
		// 					'game_code' => 413,
		// 				),
		// 				array(
		// 					'game_name' => 'SugarPop',
		// 					'english_name' => 'SugarPop',
		// 					'external_game_id' => 402,
		// 					'game_code' => 402,
		// 				),
		// 				array(
		// 					'game_name' => 'Gladiator Mobile',
		// 					'english_name' => 'Gladiator Mobile',
		// 					'external_game_id' => 406,
		// 					'game_code' => 406,
		// 				),
		// 				array(
		// 					'game_name' => 'Gladiator Android',
		// 					'english_name' => 'Gladiator Android',
		// 					'external_game_id' => 407,
		// 					'game_code' => 407,
		// 				),
		// 				array(
		// 					'game_name' => 'A Night in Paris JP Windows Phone',
		// 					'english_name' => 'A Night in Paris JP Windows Phone',
		// 					'external_game_id' => 393,
		// 					'game_code' => 393,
		// 				),
		// 				array(
		// 					'game_name' => 'A Night in Paris JP Android',
		// 					'english_name' => 'A Night in Paris JP Android',
		// 					'external_game_id' => 392,
		// 					'game_code' => 392,
		// 				),
		// 				array(
		// 					'game_name' => 'True Illusions Windows Phone',
		// 					'english_name' => 'True Illusions Windows Phone',
		// 					'external_game_id' => 398,
		// 					'game_code' => 398,
		// 				),
		// 				array(
		// 					'game_name' => 'True Illusions Android',
		// 					'english_name' => 'True Illusions Android',
		// 					'external_game_id' => 397,
		// 					'game_code' => 397,
		// 				),
		// 				array(
		// 					'game_name' => 'True Illusions Mobile',
		// 					'english_name' => 'True Illusions Mobile',
		// 					'external_game_id' => 396,
		// 					'game_code' => 396,
		// 				),
		// 				array(
		// 					'game_name' => 'The True Sheriff Windows Phone',
		// 					'english_name' => 'The True Sheriff Windows Phone',
		// 					'external_game_id' => 387,
		// 					'game_code' => 387,
		// 				),
		// 				array(
		// 					'game_name' => 'The True Sheriff Android',
		// 					'english_name' => 'The True Sheriff Android',
		// 					'external_game_id' => 386,
		// 					'game_code' => 386,
		// 				),
		// 				array(
		// 					'game_name' => 'The True Sheriff Mobile',
		// 					'english_name' => 'The True Sheriff Mobile',
		// 					'external_game_id' => 385,
		// 					'game_code' => 385,
		// 				),
		// 				array(
		// 					'game_name' => 'The True Sheriff',
		// 					'english_name' => 'The True Sheriff',
		// 					'external_game_id' => 384,
		// 					'game_code' => 384,
		// 				),
		// 				array(
		// 					'game_name' => 'A Night in Paris JP Mobile',
		// 					'english_name' => 'A Night in Paris JP Mobile',
		// 					'external_game_id' => 391,
		// 					'game_code' => 391,
		// 				),
		// 				array(
		// 					'game_name' => 'More Gold Diggin',
		// 					'english_name' => 'More Gold Diggin',
		// 					'external_game_id' => 444,
		// 					'game_code' => 444,
		// 				),
		// 				array(
		// 					'game_name' => 'Good Girl, Bad Girl Windows Phone',
		// 					'english_name' => 'Good Girl, Bad Girl Windows Phone',
		// 					'external_game_id' => 432,
		// 					'game_code' => 432,
		// 				),
		// 				array(
		// 					'game_name' => 'Lost Windows Phone',
		// 					'english_name' => 'Lost Windows Phone',
		// 					'external_game_id' => 424,
		// 					'game_code' => 424,
		// 				),
		// 				array(
		// 					'game_name' => 'Good Girl, Bad Girl',
		// 					'english_name' => 'Good Girl, Bad Girl',
		// 					'external_game_id' => 426,
		// 					'game_code' => 426,
		// 				),
		// 				array(
		// 					'game_name' => 'Good Girl, Bad Girl Mobile',
		// 					'english_name' => 'Good Girl, Bad Girl Mobile',
		// 					'external_game_id' => 428,
		// 					'game_code' => 428,
		// 				),
		// 				array(
		// 					'game_name' => 'Good Girl, Bad Girl Android',
		// 					'english_name' => 'Good Girl, Bad Girl Android',
		// 					'external_game_id' => 430,
		// 					'game_code' => 430,
		// 				),
		// 				array(
		// 					'game_name' => 'Lost Android',
		// 					'english_name' => 'Lost Android',
		// 					'external_game_id' => 423,
		// 					'game_code' => 423,
		// 				),
		// 				array(
		// 					'game_name' => 'Lost Mobile',
		// 					'english_name' => 'Lost Mobile',
		// 					'external_game_id' => 422,
		// 					'game_code' => 422,
		// 				),
		// 				array(
		// 					'game_name' => 'Gypsy Rose',
		// 					'english_name' => 'Gypsy Rose',
		// 					'external_game_id' => 478,
		// 					'game_code' => 478,
		// 				),
		// 				array(
		// 					'game_name' => 'Gypsy Rose Mobile',
		// 					'english_name' => 'Gypsy Rose Mobile',
		// 					'external_game_id' => 479,
		// 					'game_code' => 479,
		// 				),
		// 				array(
		// 					'game_name' => 'Tycoons Plus Windows Phone',
		// 					'english_name' => 'Tycoons Plus Windows Phone',
		// 					'external_game_id' => 474,
		// 					'game_code' => 474,
		// 				),
		// 				array(
		// 					'game_name' => 'Tycoons Plus Mobile',
		// 					'english_name' => 'Tycoons Plus Mobile',
		// 					'external_game_id' => 472,
		// 					'game_code' => 472,
		// 				),
		// 				array(
		// 					'game_name' => 'Tycoons Plus Android',
		// 					'english_name' => 'Tycoons Plus Android',
		// 					'external_game_id' => 473,
		// 					'game_code' => 473,
		// 				),
		// 				array(
		// 					'game_name' => 'Heist Windows Phone',
		// 					'english_name' => 'Heist Windows Phone',
		// 					'external_game_id' => 470,
		// 					'game_code' => 470,
		// 				),
		// 				array(
		// 					'game_name' => 'Tycoons Plus',
		// 					'english_name' => 'Tycoons Plus',
		// 					'external_game_id' => 471,
		// 					'game_code' => 471,
		// 				),
		// 				array(
		// 					'game_name' => 'Heist Mobile',
		// 					'english_name' => 'Heist Mobile',
		// 					'external_game_id' => 468,
		// 					'game_code' => 468,
		// 				),
		// 				array(
		// 					'game_name' => 'Heist Android',
		// 					'english_name' => 'Heist Android',
		// 					'external_game_id' => 469,
		// 					'game_code' => 469,
		// 				),
		// 				array(
		// 					'game_name' => 'Sushi Bar Android',
		// 					'english_name' => 'Sushi Bar Android',
		// 					'external_game_id' => 466,
		// 					'game_code' => 466,
		// 				),
		// 				array(
		// 					'game_name' => 'Sushi Bar Windows Phone',
		// 					'english_name' => 'Sushi Bar Windows Phone',
		// 					'external_game_id' => 467,
		// 					'game_code' => 467,
		// 				),
		// 				array(
		// 					'game_name' => 'The Curious Machine Plus Windows Phone',
		// 					'english_name' => 'The Curious Machine Plus Windows Phone',
		// 					'external_game_id' => 464,
		// 					'game_code' => 464,
		// 				),
		// 				array(
		// 					'game_name' => 'Sushi Bar Mobile',
		// 					'english_name' => 'Sushi Bar Mobile',
		// 					'external_game_id' => 465,
		// 					'game_code' => 465,
		// 				),
		// 				array(
		// 					'game_name' => 'The Curious Machine Plus Android',
		// 					'english_name' => 'The Curious Machine Plus Android',
		// 					'external_game_id' => 463,
		// 					'game_code' => 463,
		// 				),
		// 				array(
		// 					'game_name' => 'The Curious Machine Plus Mobile',
		// 					'english_name' => 'The Curious Machine Plus Mobile',
		// 					'external_game_id' => 462,
		// 					'game_code' => 462,
		// 				),
		// 				array(
		// 					'game_name' => 'The Curious Machine Plus',
		// 					'english_name' => 'The Curious Machine Plus',
		// 					'external_game_id' => 461,
		// 					'game_code' => 461,
		// 				),
		// 				array(
		// 					'game_name' => 'Under the Sea Windows Phone',
		// 					'english_name' => 'Under the Sea Windows Phone',
		// 					'external_game_id' => 457,
		// 					'game_code' => 457,
		// 				),
		// 				array(
		// 					'game_name' => 'Under the Sea Android',
		// 					'english_name' => 'Under the Sea Android',
		// 					'external_game_id' => 456,
		// 					'game_code' => 456,
		// 				),
		// 				array(
		// 					'game_name' => 'Under the Sea Mobile',
		// 					'english_name' => 'Under the Sea Mobile',
		// 					'external_game_id' => 455,
		// 					'game_code' => 455,
		// 				),
		// 				array(
		// 					'game_name' => 'More Gold Diggin Windows Phone',
		// 					'english_name' => 'More Gold Diggin Windows Phone',
		// 					'external_game_id' => 453,
		// 					'game_code' => 453,
		// 				),
		// 				array(
		// 					'game_name' => 'More Gold Diggin Android',
		// 					'english_name' => 'More Gold Diggin Android',
		// 					'external_game_id' => 452,
		// 					'game_code' => 452,
		// 				),
		// 				array(
		// 					'game_name' => 'More Gold Diggin Mobile',
		// 					'english_name' => 'More Gold Diggin Mobile',
		// 					'external_game_id' => 451,
		// 					'game_code' => 451,
		// 				),
		// 				array(
		// 					'game_name' => 'It Came From Venus JP Plus',
		// 					'english_name' => 'It Came From Venus JP Plus',
		// 					'external_game_id' => 504,
		// 					'game_code' => 504,
		// 				),
		// 				array(
		// 					'game_name' => 'It Came From Venus JP Plus Mobile',
		// 					'english_name' => 'It Came From Venus JP Plus Mobile',
		// 					'external_game_id' => 505,
		// 					'game_code' => 505,
		// 				),
		// 				array(
		// 					'game_name' => 'It Came From Venus JP Plus Android',
		// 					'english_name' => 'It Came From Venus JP Plus Android',
		// 					'external_game_id' => 506,
		// 					'game_code' => 506,
		// 				),
		// 				array(
		// 					'game_name' => 'It Came From Venus JP Plus Windows Phone',
		// 					'english_name' => 'It Came From Venus JP Plus Windows Phone',
		// 					'external_game_id' => 507,
		// 					'game_code' => 507,
		// 				),
		// 				array(
		// 					'game_name' => 'Dr. Jekyll & Mr. Hyde',
		// 					'english_name' => 'Dr. Jekyll & Mr. Hyde',
		// 					'external_game_id' => 500,
		// 					'game_code' => 500,
		// 				),
		// 				array(
		// 					'game_name' => 'Dr. Jekyll & Mr. Hyde Mobile',
		// 					'english_name' => 'Dr. Jekyll & Mr. Hyde Mobile',
		// 					'external_game_id' => 501,
		// 					'game_code' => 501,
		// 				),
		// 				array(
		// 					'game_name' => 'Dr. Jekyll & Mr. Hyde Android',
		// 					'english_name' => 'Dr. Jekyll & Mr. Hyde Android',
		// 					'external_game_id' => 502,
		// 					'game_code' => 502,
		// 				),
		// 				array(
		// 					'game_name' => 'Dr. Jekyll & Mr. Hyde Windows Phone',
		// 					'english_name' => 'Dr. Jekyll & Mr. Hyde Windows Phone',
		// 					'external_game_id' => 503,
		// 					'game_code' => 503,
		// 				),
		// 				array(
		// 					'game_name' => 'SugarPop Windows Phone',
		// 					'english_name' => 'SugarPop Windows Phone',
		// 					'external_game_id' => 496,
		// 					'game_code' => 496,
		// 				),
		// 				array(
		// 					'game_name' => 'SugarPop Android',
		// 					'english_name' => 'SugarPop Android',
		// 					'external_game_id' => 495,
		// 					'game_code' => 495,
		// 				),
		// 				array(
		// 					'game_name' => 'SugarPop Mobile',
		// 					'english_name' => 'SugarPop Mobile',
		// 					'external_game_id' => 494,
		// 					'game_code' => 494,
		// 				),
		// 				array(
		// 					'game_name' => 'WhoSpunIt Plus',
		// 					'english_name' => 'WhoSpunIt Plus',
		// 					'external_game_id' => 490,
		// 					'game_code' => 490,
		// 				),
		// 				array(
		// 					'game_name' => 'Puppy Love Plus Windows Phone',
		// 					'english_name' => 'Puppy Love Plus Windows Phone',
		// 					'external_game_id' => 485,
		// 					'game_code' => 485,
		// 				),
		// 				array(
		// 					'game_name' => 'Puppy Love Plus Android',
		// 					'english_name' => 'Puppy Love Plus Android',
		// 					'external_game_id' => 484,
		// 					'game_code' => 484,
		// 				),
		// 				array(
		// 					'game_name' => 'Gypsy Rose Windows Phone',
		// 					'english_name' => 'Gypsy Rose Windows Phone',
		// 					'external_game_id' => 481,
		// 					'game_code' => 481,
		// 				),
		// 				array(
		// 					'game_name' => 'Gypsy Rose Android',
		// 					'english_name' => 'Gypsy Rose Android',
		// 					'external_game_id' => 480,
		// 					'game_code' => 480,
		// 				),
		// 				array(
		// 					'game_name' => 'Puppy Love Plus Mobile',
		// 					'english_name' => 'Puppy Love Plus Mobile',
		// 					'external_game_id' => 483,
		// 					'game_code' => 483,
		// 				),
		// 				array(
		// 					'game_name' => 'Puppy Love Plus',
		// 					'english_name' => 'Puppy Love Plus',
		// 					'external_game_id' => 482,
		// 					'game_code' => 482,
		// 				),
		// 			),
		// 		),
		// 		##############################################################################################################
		// 		array(
		// 			'game_type' => array(
		// 				'game_type' 		=> 'Pyramid Poker',
		// 				'game_type_lang' 	=> 'Pyramid Poker',
		// 				'status' 			=> self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_FALSE,
		// 			),
		// 			'game_description' => array(
		// 				array(
		// 					'game_name' => 'Pyramid Aces And Faces',
		// 					'english_name' => 'Pyramid Aces And Faces',
		// 					'external_game_id' => 68,
		// 					'game_code' => 68,
		// 				),
		// 				array(
		// 					'game_name' => 'Pyramid Bonus Poker',
		// 					'english_name' => 'Pyramid Bonus Poker',
		// 					'external_game_id' => 69,
		// 					'game_code' => 69,
		// 				),
		// 				array(
		// 					'game_name' => 'Pyramid Bonus Deluxe',
		// 					'english_name' => 'Pyramid Bonus Deluxe',
		// 					'external_game_id' => 70,
		// 					'game_code' => 70,
		// 				),
		// 				array(
		// 					'game_name' => 'Pyramid Double Bonus',
		// 					'english_name' => 'Pyramid Double Bonus',
		// 					'external_game_id' => 71,
		// 					'game_code' => 71,
		// 				),
		// 				array(
		// 					'game_name' => 'Pyramid Jacks Or Better',
		// 					'english_name' => 'Pyramid Jacks Or Better',
		// 					'external_game_id' => 65,
		// 					'game_code' => 65,
		// 				),
		// 				array(
		// 					'game_name' => 'Pyramid Deuces Wild',
		// 					'english_name' => 'Pyramid Deuces Wild',
		// 					'external_game_id' => 66,
		// 					'game_code' => 66,
		// 				),
		// 				array(
		// 					'game_name' => 'Pyramid Joker Poker',
		// 					'english_name' => 'Pyramid Joker Poker',
		// 					'external_game_id' => 67,
		// 					'game_code' => 67,
		// 				),
		// 				array(
		// 					'game_name' => 'Pyramid Double Jackpot',
		// 					'english_name' => 'Pyramid Double Jackpot',
		// 					'external_game_id' => 72,
		// 					'game_code' => 72,
		// 				),
		// 			),
		// 		),
		// 		##############################################################################################################
		// 		array(
		// 			'game_type' => array(
		// 				'game_type' 		=> 'Table',
		// 				'game_type_lang' 	=> 'Table',
		// 				'status' 			=> self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_FALSE,
		// 			),
		// 			'game_description' => array(
		// 				array(
		// 					'game_name' => 'American Roulette',
		// 					'english_name' => 'American Roulette',
		// 					'external_game_id' => 5,
		// 					'game_code' => 5,
		// 				),
		// 				array(
		// 					'game_name' => 'Pai Gow',
		// 					'english_name' => 'Pai Gow',
		// 					'external_game_id' => 9,
		// 					'game_code' => 9,
		// 				),
		// 				array(
		// 					'game_name' => 'Craps',
		// 					'english_name' => 'Craps',
		// 					'external_game_id' => 10,
		// 					'game_code' => 10,
		// 				),
		// 				array(
		// 					'game_name' => 'Caribbean Poker',
		// 					'english_name' => 'Caribbean Poker',
		// 					'external_game_id' => 12,
		// 					'game_code' => 12,
		// 				),
		// 				array(
		// 					'game_name' => 'Baccarat',
		// 					'english_name' => 'Baccarat',
		// 					'external_game_id' => 13,
		// 					'game_code' => 13,
		// 				),
		// 				array(
		// 					'game_name' => 'Ride`m Poker',
		// 					'english_name' => 'Ride`m Poker',
		// 					'external_game_id' => 43,
		// 					'game_code' => 43,
		// 				),
		// 				array(
		// 					'game_name' => 'Super 7 Blackjack',
		// 					'english_name' => 'Super 7 Blackjack',
		// 					'external_game_id' => 44,
		// 					'game_code' => 44,
		// 				),
		// 				array(
		// 					'game_name' => 'Top Card Trumps',
		// 					'english_name' => 'Top Card Trumps',
		// 					'external_game_id' => 48,
		// 					'game_code' => 48,
		// 				),
		// 				array(
		// 					'game_name' => 'Single Deck Blackjack',
		// 					'english_name' => 'Single Deck Blackjack',
		// 					'external_game_id' => 63,
		// 					'game_code' => 63,
		// 				),
		// 				array(
		// 					'game_name' => '21 Burn Blackjack',
		// 					'english_name' => '21 Burn Blackjack',
		// 					'external_game_id' => 64,
		// 					'game_code' => 64,
		// 				),
		// 				array(
		// 					'game_name' => 'European Roulette',
		// 					'english_name' => 'European Roulette',
		// 					'external_game_id' => 79,
		// 					'game_code' => 79,
		// 				),
		// 				array(
		// 					'game_name' => 'Draw Hi-Lo',
		// 					'english_name' => 'Draw Hi-Lo',
		// 					'external_game_id' => 74,
		// 					'game_code' => 74,
		// 				),
		// 				array(
		// 					'game_name' => 'Pontoon',
		// 					'english_name' => 'Pontoon',
		// 					'external_game_id' => 81,
		// 					'game_code' => 81,
		// 				),
		// 				array(
		// 					'game_name' => 'Pirate 21',
		// 					'english_name' => 'Pirate 21',
		// 					'external_game_id' => 82,
		// 					'game_code' => 82,
		// 				),
		// 				array(
		// 					'game_name' => 'Red Dog',
		// 					'english_name' => 'Red Dog',
		// 					'external_game_id' => 94,
		// 					'game_code' => 94,
		// 				),
		// 				array(
		// 					'game_name' => 'Triple Edge Poker',
		// 					'english_name' => 'Triple Edge Poker',
		// 					'external_game_id' => 105,
		// 					'game_code' => 105,
		// 				),
		// 				array(
		// 					'game_name' => 'European Blackjack',
		// 					'english_name' => 'European Blackjack',
		// 					'external_game_id' => 191,
		// 					'game_code' => 191,
		// 				),
		// 				array(
		// 					'game_name' => 'Oasis Poker',
		// 					'english_name' => 'Oasis Poker',
		// 					'external_game_id' => 203,
		// 					'game_code' => 203,
		// 				),
		// 				array(
		// 					'game_name' => 'Vip European Roulette',
		// 					'english_name' => 'Vip European Roulette',
		// 					'external_game_id' => 197,
		// 					'game_code' => 197,
		// 				),
		// 				array(
		// 					'game_name' => 'Vip American Roulette',
		// 					'english_name' => 'Vip American Roulette',
		// 					'external_game_id' => 198,
		// 					'game_code' => 198,
		// 				),
		// 				array(
		// 					'game_name' => 'American Blackjack',
		// 					'english_name' => 'American Blackjack',
		// 					'external_game_id' => 195,
		// 					'game_code' => 195,
		// 				),
		// 				array(
		// 					'game_name' => 'Common Draw Roulette',
		// 					'english_name' => 'Common Draw Roulette',
		// 					'external_game_id' => 209,
		// 					'game_code' => 209,
		// 				),
		// 				array(
		// 					'game_name' => 'Poker3 Heads Up Hold\'em',
		// 					'english_name' => 'Poker3 Heads Up Hold\'em',
		// 					'external_game_id' => 249,
		// 					'game_code' => 249,
		// 				),
		// 				array(
		// 					'game_name' => 'Three Card Rummy',
		// 					'english_name' => 'Three Card Rummy',
		// 					'external_game_id' => 244,
		// 					'game_code' => 244,
		// 				),
		// 				array(
		// 					'game_name' => 'European Roulette Mobile',
		// 					'english_name' => 'European Roulette Mobile',
		// 					'external_game_id' => 275,
		// 					'game_code' => 275,
		// 				),
		// 				array(
		// 					'game_name' => 'American Blackjack Android',
		// 					'english_name' => 'American Blackjack Android',
		// 					'external_game_id' => 272,
		// 					'game_code' => 272,
		// 				),
		// 				array(
		// 					'game_name' => 'Zoom Roulette',
		// 					'english_name' => 'Zoom Roulette',
		// 					'external_game_id' => 278,
		// 					'game_code' => 278,
		// 				),
		// 				array(
		// 					'game_name' => 'European Roulette Android',
		// 					'english_name' => 'European Roulette Android',
		// 					'external_game_id' => 276,
		// 					'game_code' => 276,
		// 				),
		// 				array(
		// 					'game_name' => 'American Blackjack Mobile',
		// 					'english_name' => 'American Blackjack Mobile',
		// 					'external_game_id' => 271,
		// 					'game_code' => 271,
		// 				),
		// 				array(
		// 					'game_name' => 'European Roulette Windows Phone',
		// 					'english_name' => 'European Roulette Windows Phone',
		// 					'external_game_id' => 371,
		// 					'game_code' => 371,
		// 				),
		// 				array(
		// 					'game_name' => 'American Blackjack Windows Phone',
		// 					'english_name' => 'American Blackjack Windows Phone',
		// 					'external_game_id' => 366,
		// 					'game_code' => 366,
		// 				),
		// 				array(
		// 					'game_name' => 'Caribbean Poker Mobile',
		// 					'english_name' => 'Caribbean Poker Mobile',
		// 					'external_game_id' => 445,
		// 					'game_code' => 445,
		// 				),
		// 				array(
		// 					'game_name' => 'Caribbean Poker Android',
		// 					'english_name' => 'Caribbean Poker Android',
		// 					'external_game_id' => 446,
		// 					'game_code' => 446,
		// 				),
		// 				array(
		// 					'game_name' => 'Caribbean Poker Windows Phone',
		// 					'english_name' => 'Caribbean Poker Windows Phone',
		// 					'external_game_id' => 447,
		// 					'game_code' => 447,
		// 				),
		// 				array(
		// 					'game_name' => 'Single Deck Blackjack Windows Phone',
		// 					'english_name' => 'Single Deck Blackjack Windows Phone',
		// 					'external_game_id' => 450,
		// 					'game_code' => 450,
		// 				),
		// 				array(
		// 					'game_name' => 'Single Deck Blackjack Android',
		// 					'english_name' => 'Single Deck Blackjack Android',
		// 					'external_game_id' => 449,
		// 					'game_code' => 449,
		// 				),
		// 				array(
		// 					'game_name' => 'Single Deck Blackjack Mobile',
		// 					'english_name' => 'Single Deck Blackjack Mobile',
		// 					'external_game_id' => 448,
		// 					'game_code' => 448,
		// 				),
		// 			),
		// 		),
		// 		##############################################################################################################
		// 	)
		// );

		// $game_description_list = array();
		// foreach ($data as $game_platform_id => $game_types) {
		// 	foreach ($game_types as $game_type) {

		// 		$game_type['game_type']['game_platform_id'] = $game_platform_id;
		// 		$this->db->insert('game_type', $game_type['game_type']);
		// 		$game_type_id = $this->db->insert_id();

		// 		foreach ($game_type['game_description'] as &$game_description) {
		// 			$game_description['game_platform_id'] = $game_platform_id;
		// 			$game_description['game_type_id'] = $game_type_id;
		// 		}

		// 		$this->db->insert_batch('game_description', $game_type['game_description']);
		// 	}

		// }

		// $this->db->trans_complete();
	}

	public function down() {

		// $game_platform_id = BS_API;

		// $this->db->where('game_platform_id', $game_platform_id);
		// $this->db->where('game_code !=', 'unknown');
		// $this->db->delete('game_description');

		// $this->db->where('game_platform_id', $game_platform_id);
		// $this->db->where('game_type !=', 'unknown');
		// $this->db->delete('game_type');
	}
}
