<?php

defined('BASEPATH') OR exit('No direct script access allowed');

class Migration_add_ttg_in_game_description_and_game_type_20160510 extends CI_Migration {

	public function up() {
		// $this->load->model('game_type_model');
		// $this->db->trans_start();
		// $game_type_id = $this->game_type_model->createGameType('Card games', TTG_API);
		// $this->db->insert_batch('game_description', array(
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'Baccarat',
		// 		'external_game_id' => 'Baccarat',
		// 		'game_name' => 'Baccarat',
		// 		'english_name' => 'Baccarat',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 13,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'PaigowPoker',
		// 		'external_game_id' => 'PaigowPoker',
		// 		'game_name' => 'Paigow Poker',
		// 		'english_name' => 'Paigow Poker',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 14,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'Lucky7Blackjack',
		// 		'external_game_id' => 'Lucky7Blackjack',
		// 		'game_name' => 'Lucky 7 Blackjack',
		// 		'english_name' => 'Lucky 7 Blackjack',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 25,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'ThreeCardPoker',
		// 		'external_game_id' => 'ThreeCardPoker',
		// 		'game_name' => 'Three Card Poker',
		// 		'english_name' => 'Three Card Poker',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 32,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'CasinoWar',
		// 		'external_game_id' => 'CasinoWar',
		// 		'game_name' => 'Casino War',
		// 		'english_name' => 'Casino War',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 34,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'EuroBlackjack',
		// 		'external_game_id' => 'EuroBlackjack',
		// 		'game_name' => 'Euro Blackjack',
		// 		'english_name' => 'Euro Blackjack',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 38,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'RedDog',
		// 		'external_game_id' => 'RedDog',
		// 		'game_name' => 'Red Dog',
		// 		'english_name' => 'Red Dog',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 44,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'NoCommissionBaccarat',
		// 		'external_game_id' => 'NoCommissionBaccarat',
		// 		'game_name' => 'No Commission Baccarat',
		// 		'english_name' => 'No Commission Baccarat',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 448,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'PerfectPairsBlackjack',
		// 		'external_game_id' => 'PerfectPairsBlackjack',
		// 		'game_name' => 'Perfect Pairs Blackjack',
		// 		'english_name' => 'Perfect Pairs Blackjack',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 454,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'PerfectPairsBJSidebet',
		// 		'external_game_id' => 'PerfectPairsBJSidebet',
		// 		'game_name' => 'Perfect Pairs BJ Sidebet',
		// 		'english_name' => 'Perfect Pairs BJ Sidebet',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 455,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'TexasHoldEmBonus',
		// 		'external_game_id' => 'TexasHoldEmBonus',
		// 		'game_name' => 'Texas Hold Em Bonus',
		// 		'english_name' => 'Texas Hold Em Bonus',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 457,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'CaribbeanStudPoker',
		// 		'external_game_id' => 'CaribbeanStudPoker',
		// 		'game_name' => 'Caribbean Stud Poker',
		// 		'english_name' => 'Caribbean Stud Poker',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 469,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'UltimateTexasHoldem',
		// 		'external_game_id' => 'UltimateTexasHoldem',
		// 		'game_name' => 'Ultimate Texas Holdem',
		// 		'english_name' => 'Ultimate Texas Holdem',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 479,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'Blackjack',
		// 		'external_game_id' => 'Blackjack',
		// 		'game_name' => 'Blackjack',
		// 		'english_name' => 'Blackjack',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 5,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'SideBetBlackjack',
		// 		'external_game_id' => 'SideBetBlackjack',
		// 		'game_name' => 'Side Bet Blackjack',
		// 		'english_name' => 'Side Bet Blackjack',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 523,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'SDBlackjack',
		// 		'external_game_id' => 'SDBlackjack',
		// 		'game_name' => 'SD Blackjack',
		// 		'english_name' => 'SD Blackjack',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 58,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'CasinoStudPoker',
		// 		'external_game_id' => 'CasinoStudPoker',
		// 		'game_name' => 'Casino Stud Poker',
		// 		'english_name' => 'Casino Stud Poker',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 6,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// ));

		// $game_type_id = $this->game_type_model->createGameType('Slot', TTG_API);
		// $this->db->insert_batch('game_description', array(
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'FastTrack',
		// 		'external_game_id' => 'FastTrack',
		// 		'game_name' => 'Fast Track',
		// 		'english_name' => 'Fast Track',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 10,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'FortunePays',
		// 		'external_game_id' => 'FortunePays',
		// 		'game_name' => 'Fortune Pay',
		// 		'english_name' => 'Fortune Pay',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 1000,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'FuStar',
		// 		'external_game_id' => 'FuStar',
		// 		'game_name' => 'Fu Star',
		// 		'english_name' => 'Fu Star',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 1001,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'ZodiacWilds',
		// 		'external_game_id' => 'ZodiacWilds',
		// 		'game_name' => 'Zodiac Wild',
		// 		'english_name' => 'Zodiac Wild',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 1002,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'DolphinGold',
		// 		'external_game_id' => 'DolphinGold',
		// 		'game_name' => 'Dolphin Gold',
		// 		'english_name' => 'Dolphin Gold',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 1003,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'JourneyWest',
		// 		'external_game_id' => 'JourneyWest',
		// 		'game_name' => 'Journey West',
		// 		'english_name' => 'Journey West',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 1004,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'ActionHeroes',
		// 		'external_game_id' => 'ActionHeroes',
		// 		'game_name' => 'Action Heroes',
		// 		'english_name' => 'Action Heroes',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 1006,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'SilverLion',
		// 		'external_game_id' => 'SilverLion',
		// 		'game_name' => 'Silver Lion',
		// 		'english_name' => 'Silver Lion',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 1007,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'CashGrabII',
		// 		'external_game_id' => 'CashGrabII',
		// 		'game_name' => 'Cash Grab II',
		// 		'english_name' => 'Cash Grab II',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 1008,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'KatLeeII',
		// 		'external_game_id' => 'KatLeeII',
		// 		'game_name' => 'Kat LeeII',
		// 		'english_name' => 'Kat LeeII',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 1009,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'JadeEmpire',
		// 		'external_game_id' => 'JadeEmpire',
		// 		'game_name' => 'Jade Empire',
		// 		'english_name' => 'Jade Empire',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 1011,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'FivePirates',
		// 		'external_game_id' => 'FivePirates',
		// 		'game_name' => 'Five Pirates',
		// 		'english_name' => 'Five Pirates',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 1012,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'MonkeyAndTheMoon',
		// 		'external_game_id' => 'MonkeyAndTheMoon',
		// 		'game_name' => 'Monkey And The Moon',
		// 		'english_name' => 'Monkey And The Moon',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 1013,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'MoreMonkeys',
		// 		'external_game_id' => 'MoreMonkeys',
		// 		'game_name' => 'More Monkeys',
		// 		'english_name' => 'More Monkeys',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 1014,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'RedHotFreeSpins',
		// 		'external_game_id' => 'RedHotFreeSpins',
		// 		'game_name' => 'Red Hot Free Spins',
		// 		'english_name' => 'Red Hot Free Spins',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 1015,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'MadMonkey',
		// 		'external_game_id' => 'MadMonkey',
		// 		'game_name' => 'Mad Monkey',
		// 		'english_name' => 'Mad Monkey',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 1016,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'ZeusVsHades',
		// 		'external_game_id' => 'ZeusVsHades',
		// 		'game_name' => 'Zeus Vs Hades',
		// 		'english_name' => 'Zeus Vs Hades',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 1017,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'PotOGoldII',
		// 		'external_game_id' => 'PotOGoldII',
		// 		'game_name' => 'Pot O Gold II',
		// 		'english_name' => 'Pot O Gold II',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 1018,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'FireGoddess',
		// 		'external_game_id' => 'FireGoddess',
		// 		'game_name' => 'Fire Goddess',
		// 		'english_name' => 'Fire Goddess',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 1019,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'DragonKing',
		// 		'external_game_id' => 'DragonKing',
		// 		'game_name' => 'Dragon King',
		// 		'english_name' => 'Dragon King',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 1021,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'HotVolcano',
		// 		'external_game_id' => 'HotVolcano',
		// 		'game_name' => 'Hot Volcano',
		// 		'english_name' => 'Hot Volcano',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 1022,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'SnakeCharmer',
		// 		'external_game_id' => 'SnakeCharmer',
		// 		'game_name' => 'Snake Charmer',
		// 		'english_name' => 'Snake Charmer',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 1023,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'LuckyPanda',
		// 		'external_game_id' => 'LuckyPanda',
		// 		'game_name' => 'Lucky Panda',
		// 		'english_name' => 'Lucky Panda',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 1025,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'Athena',
		// 		'external_game_id' => 'Athena',
		// 		'game_name' => 'Athena',
		// 		'english_name' => 'Athena',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 1026,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'AladdinHandOfMidas',
		// 		'external_game_id' => 'AladdinHandOfMidas',
		// 		'game_name' => 'Aladdin Hand Of Midas',
		// 		'english_name' => 'Aladdin Hand Of Midas',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 1027,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'GrandPrix',
		// 		'external_game_id' => 'GrandPrix',
		// 		'game_name' => 'Grand Prix',
		// 		'english_name' => 'Grand Prix',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 1028,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'DragonPalace',
		// 		'external_game_id' => 'DragonPalace',
		// 		'game_name' => 'Dragon Palace',
		// 		'english_name' => 'Dragon Palace',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 1029,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'YearOfTheMonkey',
		// 		'external_game_id' => 'YearOfTheMonkey',
		// 		'game_name' => 'Year of The Monkey',
		// 		'english_name' => 'Year of The Monkey',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 1035,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'GenericSlots',
		// 		'external_game_id' => 'GenericSlots',
		// 		'game_name' => 'Wild West',
		// 		'english_name' => 'Wild West',
		// 		'attributes' => json_encode(array(
		// 			'gameD' => 11,
		// 			'gameType' => 16,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'HollywoodReels',
		// 		'external_game_id' => 'HollywoodReels',
		// 		'game_name' => 'Hollywood Reels',
		// 		'english_name' => 'Hollywood Reels',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 15,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'GenericSlots',
		// 		'external_game_id' => 'GenericSlots',
		// 		'game_name' => 'Space Invasion',
		// 		'english_name' => 'Space Invasion',
		// 		'attributes' => json_encode(array(
		// 			'gameD' => 16,
		// 			'gameType' => 20,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'GenericSlots',
		// 		'external_game_id' => 'GenericSlots',
		// 		'game_name' => 'Lucky Cherry',
		// 		'english_name' => 'Lucky Cherry',
		// 		'attributes' => json_encode(array(
		// 			'gameD' => 17,
		// 			'gameType' => 11,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'HoleInOne',
		// 		'external_game_id' => 'HoleInOne',
		// 		'game_name' => 'Hole In One',
		// 		'english_name' => 'Hole In One',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 18,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'GenericSlots',
		// 		'external_game_id' => 'GenericSlots',
		// 		'game_name' => 'Cash Grab',
		// 		'english_name' => 'Cash Grab',
		// 		'attributes' => json_encode(array(
		// 			'gameD' => 391,
		// 			'gameType' => 21,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'FiveReelSlots',
		// 		'external_game_id' => 'FiveReelSlots',
		// 		'game_name' => 'Cash Inferno',
		// 		'english_name' => 'Cash Inferno',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 40,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'GoooalSlots',
		// 		'external_game_id' => 'GoooalSlots',
		// 		'game_name' => 'Goooal Slots',
		// 		'english_name' => 'Goooal Slots',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 401,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'FruitParty',
		// 		'external_game_id' => 'FruitParty',
		// 		'game_name' => 'Fruit Party',
		// 		'english_name' => 'Fruit Party',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 411,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'JackpotHolidaySlots',
		// 		'external_game_id' => 'JackpotHolidaySlots',
		// 		'game_name' => 'Jackpot Holiday Slots',
		// 		'english_name' => 'Jackpot Holiday Slots',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 413,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'AmazonAdventureSlots',
		// 		'external_game_id' => 'AmazonAdventureSlots',
		// 		'game_name' => 'Amazon Adventure Slots',
		// 		'english_name' => 'Amazon Adventure Slots',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 414,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'NeptunesGoldSlots',
		// 		'external_game_id' => 'NeptunesGoldSlots',
		// 		'game_name' => 'Neptunes Gold Slots',
		// 		'english_name' => 'Neptunes Gold Slots',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 416,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'MonkeyLoveSlots',
		// 		'external_game_id' => 'MonkeyLoveSlots',
		// 		'game_name' => 'Monkey Love Slots',
		// 		'english_name' => 'Monkey Love Slots',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 421,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'Dragon8sSlots',
		// 		'external_game_id' => 'Dragon8sSlots',
		// 		'game_name' => 'Dragon 8s Slots',
		// 		'english_name' => 'Dragon 8s Slots',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 423,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'PolarRichesSlots',
		// 		'external_game_id' => 'PolarRichesSlots',
		// 		'game_name' => 'Polar Riches Slots',
		// 		'english_name' => 'Polar Riches Slots',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 424,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'WildMummySlots',
		// 		'external_game_id' => 'WildMummySlots',
		// 		'game_name' => 'Wild Mummy Slots',
		// 		'english_name' => 'Wild Mummy Slots',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 428,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'FanCashticSlots',
		// 		'external_game_id' => 'FanCashticSlots',
		// 		'game_name' => 'Fan Cashtic Slots',
		// 		'english_name' => 'Fan Cashtic Slots',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 437,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'VivaVeneziaSlots',
		// 		'external_game_id' => 'VivaVeneziaSlots',
		// 		'game_name' => 'Viva Venezia Slots',
		// 		'english_name' => 'Viva Venezia Slots',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 438,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'LadysCharmsSlots',
		// 		'external_game_id' => 'LadysCharmsSlots',
		// 		'game_name' => 'Ladys Charms Slots',
		// 		'english_name' => 'Ladys Charms Slots',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 439,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'KatLeeSlots',
		// 		'external_game_id' => 'KatLeeSlots',
		// 		'game_name' => 'Kat Lee Slots',
		// 		'english_name' => 'Kat Lee Slots',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 440,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'BerryBlastSlots',
		// 		'external_game_id' => 'BerryBlastSlots',
		// 		'game_name' => 'Berry Blast Slots',
		// 		'english_name' => 'Berry Blast Slots',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 444,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'FortuneTellerSlots',
		// 		'external_game_id' => 'FortuneTellerSlots',
		// 		'game_name' => 'Fortune Teller Slots',
		// 		'english_name' => 'Fortune Teller Slots',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 446,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'TBSpinNWinSlots',
		// 		'external_game_id' => 'TBSpinNWinSlots',
		// 		'game_name' => 'TB Spin N Win Slots',
		// 		'english_name' => 'TB Spin N Win Slots',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 447,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'SurfsUpSlots',
		// 		'external_game_id' => 'SurfsUpSlots',
		// 		'game_name' => 'Surfs Up Slots',
		// 		'english_name' => 'Surfs Up Slots',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 449,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'MagicalGroveSlots',
		// 		'external_game_id' => 'MagicalGroveSlots',
		// 		'game_name' => 'Magical Grove Slots',
		// 		'english_name' => 'Magical Grove Slots',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 452,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'TheGreatCasiniSlots',
		// 		'external_game_id' => 'TheGreatCasiniSlots',
		// 		'game_name' => 'The Great Casini Slots',
		// 		'english_name' => 'The Great Casini Slots',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 453,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'SleepyHollowSlots',
		// 		'external_game_id' => 'SleepyHollowSlots',
		// 		'game_name' => 'Sleepy Hollow Slots',
		// 		'english_name' => 'Sleepy Hollow Slots',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 456,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'ArthursQuestIISlots',
		// 		'external_game_id' => 'ArthursQuestIISlots',
		// 		'game_name' => 'Arthurs Quest II',
		// 		'english_name' => 'Arthurs Quest II',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 462,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'AgentMaxCashSlots',
		// 		'external_game_id' => 'AgentMaxCashSlots',
		// 		'game_name' => 'Agent Max Cash',
		// 		'english_name' => 'Agent Max Cash',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 466,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'AmazonWild',
		// 		'external_game_id' => 'AmazonWild',
		// 		'game_name' => 'Amazon Wild',
		// 		'english_name' => 'Amazon Wild',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 467,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'VictoryRidgeSlots',
		// 		'external_game_id' => 'VictoryRidgeSlots',
		// 		'game_name' => 'Victory Ridge Slots',
		// 		'english_name' => 'Victory Ridge Slots',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 468,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'GoldRushShowdown',
		// 		'external_game_id' => 'GoldRushShowdown',
		// 		'game_name' => 'Gold Rush Showdown',
		// 		'english_name' => 'Gold Rush Showdown',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 472,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'BarsAndBellsSlots',
		// 		'external_game_id' => 'BarsAndBellsSlots',
		// 		'game_name' => 'Bars And Bells Slots',
		// 		'english_name' => 'Bars And Bells Slots',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 473,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'SinfulSpinsSlots',
		// 		'external_game_id' => 'SinfulSpinsSlots',
		// 		'game_name' => 'Sinful Spins Slots',
		// 		'english_name' => 'Sinful Spins Slots',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 474,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'DracosFire',
		// 		'external_game_id' => 'DracosFire',
		// 		'game_name' => 'Dracos Fire',
		// 		'english_name' => 'Dracos Fire',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 475,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'AngelsTouch',
		// 		'external_game_id' => 'AngelsTouch',
		// 		'game_name' => 'Angels Touch',
		// 		'english_name' => 'Angels Touch',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 477,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'SerengetiDiamonds',
		// 		'external_game_id' => 'SerengetiDiamonds',
		// 		'game_name' => 'Serengeti Diamonds',
		// 		'english_name' => 'Serengeti Diamonds',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 478,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'VampiresVsWerewolves',
		// 		'external_game_id' => 'VampiresVsWerewolves',
		// 		'game_name' => 'Vampires Vs Werewolves',
		// 		'english_name' => 'Vampires Vs Werewolves',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 480,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'RamessesRiches',
		// 		'external_game_id' => 'RamessesRiches',
		// 		'game_name' => 'Ramesses Riches',
		// 		'english_name' => 'Ramesses Riches',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 481,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'UnicornLegend',
		// 		'external_game_id' => 'UnicornLegend',
		// 		'game_name' => 'Unicorn Legend',
		// 		'english_name' => 'Unicorn Legend',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 482,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'ShogunShowdown',
		// 		'external_game_id' => 'ShogunShowdown',
		// 		'game_name' => 'Shogun Show down',
		// 		'english_name' => 'Shogun Show down',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 483,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'LostTemple',
		// 		'external_game_id' => 'LostTemple',
		// 		'game_name' => 'Lost Temple',
		// 		'english_name' => 'Lost Temple',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 484,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'ThunderingZeus',
		// 		'external_game_id' => 'ThunderingZeus',
		// 		'game_name' => 'Thundering Zeus',
		// 		'english_name' => 'Thundering Zeus',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 486,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'IrishEyes',
		// 		'external_game_id' => 'IrishEyes',
		// 		'game_name' => 'Irish Eyes',
		// 		'english_name' => 'Irish Eyes',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 487,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'Medusa',
		// 		'external_game_id' => 'Medusa',
		// 		'game_name' => 'Medusa',
		// 		'english_name' => 'Medusa',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 488,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'CherryBlossoms',
		// 		'external_game_id' => 'CherryBlossoms',
		// 		'game_name' => 'Cherry Blossoms',
		// 		'english_name' => 'Cherry Blossoms',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 489,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'Crocodopolis',
		// 		'external_game_id' => 'Crocodopolis',
		// 		'game_name' => 'Crocodopolis',
		// 		'english_name' => 'Crocodopolis',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 490,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => '300Shields',
		// 		'external_game_id' => '300Shields',
		// 		'game_name' => '300 Shields',
		// 		'english_name' => '300 Shields',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 491,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'DoctorLove',
		// 		'external_game_id' => 'DoctorLove',
		// 		'game_name' => 'Doctor Love',
		// 		'english_name' => 'Doctor Love',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 492,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'VenetianRose',
		// 		'external_game_id' => 'VenetianRose',
		// 		'game_name' => 'Venetian Rose',
		// 		'english_name' => 'Venetian Rose',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 493,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'CallOfTheColosseum',
		// 		'external_game_id' => 'CallOfTheColosseum',
		// 		'game_name' => 'Call Of The Colosseum',
		// 		'english_name' => 'Call Of The Colosseum',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 495,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'Bobby7s',
		// 		'external_game_id' => 'Bobby7s',
		// 		'game_name' => 'Bobby 7s',
		// 		'english_name' => 'Bobby 7s',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 506,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'SamuraiPrincess',
		// 		'external_game_id' => 'SamuraiPrincess',
		// 		'game_name' => 'Samurai Princess',
		// 		'english_name' => 'Samurai Princess',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 515,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'Taxi',
		// 		'external_game_id' => 'Taxi',
		// 		'game_name' => 'Taxi',
		// 		'english_name' => 'Taxi',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 516,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'JokerJester',
		// 		'external_game_id' => 'JokerJester',
		// 		'game_name' => 'Joker Jester',
		// 		'english_name' => 'Joker Jester',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 518,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'Butterflies',
		// 		'external_game_id' => 'Butterflies',
		// 		'game_name' => 'Butter flies',
		// 		'english_name' => 'Butter flies',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 519,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'TheSnakeCharmer',
		// 		'external_game_id' => 'TheSnakeCharmer',
		// 		'game_name' => 'The Snake Charmer',
		// 		'english_name' => 'The Snake Charmer',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 524,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'AladdinsLegacy',
		// 		'external_game_id' => 'AladdinsLegacy',
		// 		'game_name' => 'Aladdins Legacy',
		// 		'english_name' => 'Aladdins Legacy',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 525,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'FrogsNFlies',
		// 		'external_game_id' => 'FrogsNFlies',
		// 		'game_name' => 'Frogs N Flies',
		// 		'english_name' => 'Frogs N Flies',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 526,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'MadMadMonkey',
		// 		'external_game_id' => 'MadMadMonkey',
		// 		'game_name' => 'Mad Mad Monkey',
		// 		'english_name' => 'Mad Mad Monkey',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 527,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'HotHotVolcano',
		// 		'external_game_id' => 'HotHotVolcano',
		// 		'game_name' => 'Hot Hot Volcano',
		// 		'english_name' => 'Hot Hot Volcano',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 528,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'WheresTheGold',
		// 		'external_game_id' => 'WheresTheGold',
		// 		'game_name' => 'Wheres The Gold',
		// 		'english_name' => 'Wheres The Gold',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 529,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'ChoySunDoa',
		// 		'external_game_id' => 'ChoySunDoa',
		// 		'game_name' => 'Choy Sun Doa',
		// 		'english_name' => 'Choy Sun Doa',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 530,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'Pompeii',
		// 		'external_game_id' => 'Pompeii',
		// 		'game_name' => 'Pompeii',
		// 		'english_name' => 'Pompeii',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 531,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'WildPanda',
		// 		'external_game_id' => 'WildPanda',
		// 		'game_name' => 'Wild Panda',
		// 		'english_name' => 'Wild Panda',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 532,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'ChilliGold',
		// 		'external_game_id' => 'ChilliGold',
		// 		'game_name' => 'Chilli Gold',
		// 		'english_name' => 'Chilli Gold',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 533,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'Fortune8Cat',
		// 		'external_game_id' => 'Fortune8Cat',
		// 		'game_name' => 'Fortune 8 Cat',
		// 		'english_name' => 'Fortune 8 Cat',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 540,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'GenericSlots',
		// 		'external_game_id' => 'GenericSlots',
		// 		'game_name' => 'Jump For Gold',
		// 		'english_name' => 'Jump For Gold',
		// 		'attributes' => json_encode(array(
		// 			'gameD' => 57,
		// 			'gameType' => 10,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'ArthursQuest',
		// 		'external_game_id' => 'ArthursQuest',
		// 		'game_name' => 'Arthurs Quest',
		// 		'english_name' => 'Arthurs Quest',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 63,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'BullsEyeBucks',
		// 		'external_game_id' => 'BullsEyeBucks',
		// 		'game_name' => 'Bulls Eye Bucks',
		// 		'english_name' => 'Bulls Eye Bucks',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 64,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'Oktoberfest',
		// 		'external_game_id' => 'Oktoberfest',
		// 		'game_name' => 'Oktoberfest',
		// 		'english_name' => 'Oktoberfest',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 65,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'GenericSlots',
		// 		'external_game_id' => 'GenericSlots',
		// 		'game_name' => 'Pirate Treasure',
		// 		'english_name' => 'Pirate Treasure',
		// 		'attributes' => json_encode(array(
		// 			'gameD' => 9,
		// 			'gameType' => 17,
		// 		)),
		// 	),
		// ));

		// $game_type_id = $this->game_type_model->createGameType('Soft games', TTG_API);
		// $this->db->insert_batch('game_description', array(
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'CardSharks',
		// 		'external_game_id' => 'CardSharks',
		// 		'game_name' => 'Card Sharks',
		// 		'english_name' => 'Card Sharks',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 390,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'MadMatterhorn',
		// 		'external_game_id' => 'MadMatterhorn',
		// 		'game_name' => 'Mad Matterhorn',
		// 		'english_name' => 'Mad Matterhorn',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 399,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'HiLoGameShow',
		// 		'external_game_id' => 'HiLoGameShow',
		// 		'game_name' => 'Hi Lo Game Show',
		// 		'english_name' => 'Hi Lo Game Show',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 403,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'FinalScoreMultiLeague',
		// 		'external_game_id' => 'FinalScoreMultiLeague',
		// 		'game_name' => 'Final Score Multi League',
		// 		'english_name' => 'Final Score Multi League',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 422,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'GoldenBonanzaKeno',
		// 		'external_game_id' => 'GoldenBonanzaKeno',
		// 		'game_name' => 'Golden Bonanza Keno',
		// 		'english_name' => 'Golden Bonanza Keno',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 426,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'Darts',
		// 		'external_game_id' => 'Darts',
		// 		'game_name' => 'Darts',
		// 		'english_name' => 'Darts',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 427,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'PinballRoulette',
		// 		'external_game_id' => 'PinballRoulette',
		// 		'game_name' => 'Pinball Roulette',
		// 		'english_name' => 'Pinball Roulette',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 429,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'HoldemShowdown',
		// 		'external_game_id' => 'HoldemShowdown',
		// 		'game_name' => 'Holdem Showdown',
		// 		'english_name' => 'Holdem Showdown',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 436,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'BlackjackStandOrBust',
		// 		'external_game_id' => 'BlackjackStandOrBust',
		// 		'game_name' => 'Blackjack Stand Or Bust',
		// 		'english_name' => 'Blackjack Stand Or Bust',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 441,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'HiLoDEALER',
		// 		'external_game_id' => 'HiLoDEALER',
		// 		'game_name' => 'Hi Lo DEALER',
		// 		'english_name' => 'Hi Lo DEALER',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 442,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'GenericSlots',
		// 		'external_game_id' => 'GenericSlots',
		// 		'game_name' => 'Diving for Dollars',
		// 		'english_name' => 'Diving for Dollars',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 51,
		// 			'gameType' => 4,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'GenericSlots',
		// 		'external_game_id' => 'GenericSlots',
		// 		'game_name' => 'Candy Island',
		// 		'english_name' => 'Candy Island',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 52,
		// 			'gameType' => 5,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'GenericSlots',
		// 		'external_game_id' => 'GenericSlots',
		// 		'game_name' => 'Magic Money',
		// 		'english_name' => 'Magic Money',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 54,
		// 			'gameType' => 7,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'GenericSlots',
		// 		'external_game_id' => 'GenericSlots',
		// 		'game_name' => 'Go Bananas',
		// 		'english_name' => 'Go Bananas',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 55,
		// 			'gameType' => 8,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'GenericSlots',
		// 		'external_game_id' => 'GenericSlots',
		// 		'game_name' => 'Hot Streak',
		// 		'english_name' => 'Hot Streak',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 56,
		// 			'gameType' => 9,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'HiLo',
		// 		'external_game_id' => 'HiLo',
		// 		'game_name' => 'Hi Lo',
		// 		'english_name' => 'Hi Lo',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 99,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// ));

		// $game_type_id = $this->game_type_model->createGameType('Table games', TTG_API);
		// $this->db->insert_batch('game_description', array(
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'EuroRoulette',
		// 		'external_game_id' => 'EuroRoulette',
		// 		'game_name' => 'Euro Roulette',
		// 		'english_name' => 'Euro Roulette',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 23,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'CommonDrawSingleZeroRoulette',
		// 		'external_game_id' => 'CommonDrawSingleZeroRoulette',
		// 		'game_name' => 'Common Draw Single Zero Roulette',
		// 		'english_name' => 'Common Draw Single Zero Roulette',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 400,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'Craps',
		// 		'external_game_id' => 'Craps',
		// 		'game_name' => 'Craps',
		// 		'english_name' => 'Craps',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 7,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'Roulette',
		// 		'external_game_id' => 'Roulette',
		// 		'game_name' => 'Roulette',
		// 		'english_name' => 'Roulette',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 8,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// ));

		// $game_type_id = $this->game_type_model->createGameType('Video Poker', TTG_API);
		// $this->db->insert_batch('game_description', array(
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'VideoPoker',
		// 		'external_game_id' => 'VideoPoker',
		// 		'game_name' => 'Jacks or Better',
		// 		'english_name' => 'Jacks or Better',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 1,
		// 			'gameType' => 1,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'VideoPoker',
		// 		'external_game_id' => 'VideoPoker',
		// 		'game_name' => 'Deuces Wild',
		// 		'english_name' => 'Deuces Wild',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 2,
		// 			'gameType' => 2,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'VideoPoker',
		// 		'external_game_id' => 'VideoPoker',
		// 		'game_name' => 'Joker Poker',
		// 		'english_name' => 'Joker Poker',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 3,
		// 			'gameType' => 3,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'VideoPoker',
		// 		'external_game_id' => 'VideoPoker',
		// 		'game_name' => 'All American',
		// 		'english_name' => 'All American',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 4,
		// 			'gameType' => 4,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'Play4_Jacks_or_Better',
		// 		'external_game_id' => 'Play4_Jacks_or_Better',
		// 		'game_name' => 'Play4 Jacks or Better',
		// 		'english_name' => 'Play4 Jacks or Better',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 405,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'Play4_Deuces_Wild',
		// 		'external_game_id' => 'Play4_Deuces_Wild',
		// 		'game_name' => 'Play4 Deuces Wild',
		// 		'english_name' => 'Play4 Deuces Wild',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 406,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'Play4_Joker_Poker',
		// 		'external_game_id' => 'Play4_Joker_Poker',
		// 		'game_name' => 'Play4 Joker Poker',
		// 		'english_name' => 'Play4 Joker Poker',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 407,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'Play4_All_American',
		// 		'external_game_id' => 'Play4_All_American',
		// 		'game_name' => 'Play4 All American',
		// 		'english_name' => 'Play4 All American',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 408,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// 	array(
		// 		'game_platform_id' => TTG_API,
		// 		'game_type_id' => $game_type_id,
		// 		'game_code' => 'ChallengeVideoPoker',
		// 		'external_game_id' => 'ChallengeVideoPoker',
		// 		'game_name' => 'Challenge Video Poker',
		// 		'english_name' => 'Challenge Video Poker',
		// 		'attributes' => json_encode(array(
		// 			'gameId' => 410,
		// 			'gameType' => 0,
		// 		)),
		// 	),
		// ));
		// $this->db->trans_complete();

	}

	public function down() {

		// $game_platform_id = TTG_API;

		// $this->db->trans_start();

		// $this->db->where('game_platform_id', $game_platform_id);
		// $this->db->where('game_code !=', 'unknown');
		// $this->db->delete('game_description');

		// $this->db->where('game_platform_id', $game_platform_id);
		// $this->db->where('game_type !=', 'unknown');
		// $this->db->delete('game_type');

		// $this->db->trans_complete();
	}

}