<?php

defined('BASEPATH') OR exit('No direct script access allowed');

class Migration_add_flowgaming_to_game_type_and_game_description_201607021127 extends CI_Migration {

	const FLAG_TRUE = 1;
	const FLAG_FALSE = 0;

	public function up() {
		// $this->db->trans_start();
		// $data = array(
		// 				array(
		// 					'game_type' => 'NYX Slots Game',
		// 					'game_type_lang' => 'fg_nyx_slots_game',
		// 					'status' => self::FLAG_TRUE,
		// 					'flag_show_in_site' => self::FLAG_TRUE,
		// 					'game_description_list' => array(
		// 						array(
		// 							'game_name' => '1 Can 2 Can',
		// 							'english_name' => '1 Can 2 Can',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70071',
		// 							'external_game_id' => '70071',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => '300 Shields',
		// 							'english_name' => '300 Shields',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70003',
		// 							'external_game_id' => '70003',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => '5 Knights',
		// 							'english_name' => '5 Knights',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70058',
		// 							'external_game_id' => '70058',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'A While on the Nile',
		// 							'english_name' => 'A While on the Nile',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70070',
		// 							'external_game_id' => '70070',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Andre the Giant',
		// 							'english_name' => 'Andre the Giant',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70008',
		// 							'external_game_id' => '70008',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Bangkok Nights',
		// 							'english_name' => 'Bangkok Nights',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70009',
		// 							'external_game_id' => '70009',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Big Foot',
		// 							'english_name' => 'Big Foot',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70010',
		// 							'external_game_id' => '70010',
		// 							'related_game_desc_id' => null
		// 						),

		// 						array(
		// 							'game_name' => 'Bingo Billions',
		// 							'english_name' => 'Bingo Billions',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70109',
		// 							'external_game_id' => '70109',
		// 							'related_game_desc_id' => null
		// 						),

		// 						array(
		// 							'game_name' => 'Bobby 7\'s',
		// 							'english_name' => 'Bobby 7\'s',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70028',
		// 							'external_game_id' => '70028',
		// 							'related_game_desc_id' => null
		// 						),

		// 						array(
		// 							'game_name' => 'Butterflies',
		// 							'english_name' => 'Butterflies',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70023',
		// 							'external_game_id' => '70023',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'California Gold',
		// 							'english_name' => 'California Gold',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70023',
		// 							'external_game_id' => '70023',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Call of the Colosseum',
		// 							'english_name' => 'Call of the Colosseum',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70011',
		// 							'external_game_id' => '70011',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Cash Stampede',
		// 							'english_name' => 'Cash Stampede',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70145',
		// 							'external_game_id' => '70145',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Casinomeister',
		// 							'english_name' => 'Casinomeister',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70076',
		// 							'external_game_id' => '70076',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Cherry Blossoms',
		// 							'english_name' => 'Cherry Blossoms',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70013',
		// 							'external_game_id' => '70013',
		// 							'related_game_desc_id' => null
		// 						),

		// 						array(
		// 							'game_name' => 'Crocodopolis',
		// 							'english_name' => 'Crocodopolis',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70004',
		// 							'external_game_id' => '70004',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Doctor Love',
		// 							'english_name' => 'Doctor Love',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70005',
		// 							'external_game_id' => '70005',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Dolphin Reef',
		// 							'english_name' => 'Dolphin Reef',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70014',
		// 							'external_game_id' => '70014',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Double Play SuperBet',
		// 							'english_name' => 'Double Play SuperBet',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70138',
		// 							'external_game_id' => '70138',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Doctor Love on Vacation',
		// 							'english_name' => 'Doctor Love on Vacation',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70043',
		// 							'external_game_id' => '70043',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Dragon Drop',
		// 							'english_name' => 'Dragon Drop',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70068',
		// 							'external_game_id' => '70068',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Dynasty',
		// 							'english_name' => 'Dynasty',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70015',
		// 							'external_game_id' => '70015',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Eastern Dragon',
		// 							'english_name' => 'Eastern Dragon',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70049',
		// 							'external_game_id' => '70049',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Easy Slider',
		// 							'english_name' => 'Easy Slider',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70065',
		// 							'external_game_id' => '70065',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Emperor\'s Garden',
		// 							'english_name' => 'Emperor\'s Garden',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70059',
		// 							'external_game_id' => '70059',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Enchanted Mermaid',
		// 							'english_name' => 'Enchanted Mermaid',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70024',
		// 							'external_game_id' => '70024',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Extra Cash',
		// 							'english_name' => 'Extra Cash',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70067',
		// 							'external_game_id' => '70067',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Fairies Forest',
		// 							'english_name' => 'Fairies Forest',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70016',
		// 							'external_game_id' => '70016',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Fire Hawk',
		// 							'english_name' => 'Fire Hawk',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70032',
		// 							'external_game_id' => '70032',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Foxin Wins',
		// 							'english_name' => 'Foxin Wins',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70044',
		// 							'external_game_id' => '70044',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Foxin Wins Again',
		// 							'english_name' => 'Foxin Wins Again',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70080',
		// 							'external_game_id' => '70080',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Genie Wild',
		// 							'english_name' => 'Genie Wild',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70033',
		// 							'external_game_id' => '70033',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Gold Ahoy',
		// 							'english_name' => 'Gold Ahoy',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70025',
		// 							'external_game_id' => '70025',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Gorilla Go Wild',
		// 							'english_name' => 'Gorilla Go Wild',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70090',
		// 							'external_game_id' => '70090',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Hot Roller',
		// 							'english_name' => 'Hot Roller',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70029',
		// 							'external_game_id' => '70029',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Irish Eyes',
		// 							'english_name' => 'Irish Eyes',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70006',
		// 							'external_game_id' => '70006',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Irish Eyes 2',
		// 							'english_name' => 'Irish Eyes 2',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70042',
		// 							'external_game_id' => '70042',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Jack\'s Beanstalk',
		// 							'english_name' => 'Jack\'s Beanstalk',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70144',
		// 							'external_game_id' => '70144',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Jackpot Jester 50k',
		// 							'english_name' => 'Jackpot Jester 50k',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70041',
		// 							'external_game_id' => '70041',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Jackpot Jester Wild Nudge',
		// 							'english_name' => 'Jackpot Jester Wild Nudge',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70143',
		// 							'external_game_id' => '70143',
		// 							'related_game_desc_id' => null
		// 						),

		// 						array(
		// 							'game_name' => 'King Tiger',
		// 							'english_name' => 'King Tiger',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70017',
		// 							'external_game_id' => '70017',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'La Cucaracha',
		// 							'english_name' => 'La Cucaracha',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70019',
		// 							'external_game_id' => '70019',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Love Bugs',
		// 							'english_name' => 'Love Bugs',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70035',
		// 							'external_game_id' => '70035',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Mad Mad Monkey',
		// 							'english_name' => 'Mad Mad Monkey',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70002',
		// 							'external_game_id' => '70002',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Maid O Money',
		// 							'english_name' => 'Maid O Money',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70046',
		// 							'external_game_id' => '70046',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Medusa',
		// 							'english_name' => 'Medusa',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70020',
		// 							'external_game_id' => '70020',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Medusa II',
		// 							'english_name' => 'Medusa II',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70072',
		// 							'external_game_id' => '70072',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Merlin\'s Magic Respins',
		// 							'english_name' => 'Merlin\'s Magic Respins',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70069',
		// 							'external_game_id' => '70069',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Merlin\'s Millions Superbet',
		// 							'english_name' => 'Merlin\'s Millions Superbet',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70030',
		// 							'external_game_id' => '70030',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Miss Midas',
		// 							'english_name' => 'Miss Midas',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70089',
		// 							'external_game_id' => '70089',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Munchers',
		// 							'english_name' => 'Munchers',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70045',
		// 							'external_game_id' => '70045',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Napoleon Boney Parts',
		// 							'english_name' => 'Napoleon Boney Parts',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70066',
		// 							'external_game_id' => '70066',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Oil Mania',
		// 							'english_name' => 'Oil Mania',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70036',
		// 							'external_game_id' => '70036',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Owl Eyes',
		// 							'english_name' => 'Owl Eyes',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70075',
		// 							'external_game_id' => '70075',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Pandamania',
		// 							'english_name' => 'Pandamania',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70082',
		// 							'external_game_id' => '70082',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Pizza Prize',
		// 							'english_name' => 'Pizza Prize',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70047',
		// 							'external_game_id' => '70047',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Potion Commotion',
		// 							'english_name' => 'Potion Commotion',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70063',
		// 							'external_game_id' => '70063',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Ramesses Riches',
		// 							'english_name' => 'Ramesses Riches',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70007',
		// 							'external_game_id' => '70007',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Shaaark Superbet',
		// 							'english_name' => 'Shaaark Superbet',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70012',
		// 							'external_game_id' => '70012',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Spanish Eyes',
		// 							'english_name' => 'Spanish Eyes',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70061',
		// 							'external_game_id' => '70061',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Spin Sorceress',
		// 							'english_name' => 'Spin Sorceress',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70152',
		// 							'external_game_id' => '70152',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Starmania',
		// 							'english_name' => 'Starmania',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70146',
		// 							'external_game_id' => '70146',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Super Safari',
		// 							'english_name' => 'Super Safari',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70062',
		// 							'external_game_id' => '70062',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Teddy Bears Picnic',
		// 							'english_name' => 'Teddy Bears Picnic',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70048',
		// 							'external_game_id' => '70048',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'The Bermuda Mysteries',
		// 							'english_name' => 'The Bermuda Mysteries',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70031',
		// 							'external_game_id' => '70031',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'The Codfather',
		// 							'english_name' => 'The Codfather',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70060',
		// 							'external_game_id' => '70060',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'The Snake Charmer',
		// 							'english_name' => 'The Snake Charmer',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70026',
		// 							'external_game_id' => '70026',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'The Spin Lab',
		// 							'english_name' => 'The Spin Lab',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70107',
		// 							'external_game_id' => '70107',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Titan Storm',
		// 							'english_name' => 'Titan Storm',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70077',
		// 							'external_game_id' => '70077',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Tootin Car Man',
		// 							'english_name' => 'Tootin Car Man',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70027',
		// 							'external_game_id' => '70027',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Unicorn Legend',
		// 							'english_name' => 'Unicorn Legend',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70021',
		// 							'external_game_id' => '70021',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Venetian Rose',
		// 							'english_name' => 'Venetian Rose',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70022',
		// 							'external_game_id' => '70022',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Volcano Eruption',
		// 							'english_name' => 'Volcano Eruption',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70001',
		// 							'external_game_id' => '70001',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Wild West',
		// 							'english_name' => 'Wild West',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70078',
		// 							'external_game_id' => '70078',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Wildcat Canyon',
		// 							'english_name' => 'Wildcat Canyon',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70064',
		// 							'external_game_id' => '70064',
		// 							'related_game_desc_id' => null
		// 						),
		// 					),
		// 				),
		// 				array(
		// 					'game_type' => 'NYX Slots Mini Games',
		// 					'game_type_lang' => 'fg_nyx_slots_mini_games',
		// 					'status' => self::FLAG_TRUE,
		// 					'flag_show_in_site' => self::FLAG_TRUE,
		// 					'game_description_list' => array(
		// 						array(
		// 							'game_name' => 'Bobby 7\'s Mini',
		// 							'english_name' => 'Bobby 7\'s Mini',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70113',
		// 							'external_game_id' => '70113',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Cherry Blossoms Mini',
		// 							'english_name' => 'Cherry Blossoms Mini',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70114',
		// 							'external_game_id' => '70114',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Doctor Love Mini',
		// 							'english_name' => 'Doctor Love Mini',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70115',
		// 							'external_game_id' => '70115',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Irish Eyes Mini',
		// 							'english_name' => 'Irish Eyes Mini',
		// 							'html_five_enabled' =>self::FLAG_TRUE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '70116',
		// 							'external_game_id' => '70116',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Joker Jester Mini',
		// 							'english_name' => 'Joker Jester Mini',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70117',
		// 							'external_game_id' => '70117',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Love Bugs Mini',
		// 							'english_name' => 'Love Bugs Mini',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70118',
		// 							'external_game_id' => '70118',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Mad Mad Monkey Mini',
		// 							'english_name' => 'Mad Mad Monkey Mini',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70119',
		// 							'external_game_id' => '70119',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Medusa Mini',
		// 							'english_name' => 'Medusa Mini',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70120',
		// 							'external_game_id' => '70120',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Merlin\'s Millions Superbet Mini',
		// 							'english_name' => 'Merlin\'s Millions Superbet Mini',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70121',
		// 							'external_game_id' => '70121',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Munchers Mini',
		// 							'english_name' => 'Munchers Mini',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70122',
		// 							'external_game_id' => '70122',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Oil Mania Mini',
		// 							'english_name' => 'Oil Mania Mini',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70123',
		// 							'external_game_id' => '70123',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Ramesses Riches Mini',
		// 							'english_name' => 'Ramesses Riches Mini',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70124',
		// 							'external_game_id' => '70124',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'The Snake Charmer Mini',
		// 							'english_name' => 'The Snake Charmer Mini',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70125',
		// 							'external_game_id' => '70125',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Venetian Rose Mini',
		// 							'english_name' => 'Venetian Rose Mini',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70126',
		// 							'external_game_id' => '70126',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Volcano Eruption Mini',
		// 							'english_name' => 'Volcano Eruption Mini',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70127',
		// 							'external_game_id' => '70127',
		// 							'related_game_desc_id' => null
		// 						),
		// 					),
		// 				),
		// 				array(
		// 					'game_type' => 'NYX Table Game',
		// 					'game_type_lang' => 'fg_nyx_table_game',
		// 					'status' => self::FLAG_TRUE,
		// 					'flag_show_in_site' => self::FLAG_TRUE,
		// 					'game_description_list' => array(
		// 						array(
		// 							'game_name' => 'Blackjack Pro Monte Carlo Multi-hand',
		// 							'english_name' => 'Blackjack Pro Monte Carlo Multi-hand',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70083',
		// 							'external_game_id' => '70083',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Blackjack Pro Monte Carlo Single-hand',
		// 							'english_name' => 'Blackjack Pro Monte Carlo Single-hand',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70084',
		// 							'external_game_id' => '70084',
		// 							'related_game_desc_id' => null
		// 						),
		// 						array(
		// 							'game_name' => 'Roulette Master',
		// 							'english_name' => 'Roulette Master',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '70073',
		// 							'external_game_id' => '70073',
		// 							'related_game_desc_id' => null
		// 						),
		// 					),
		// 				),
		// 				array(
		// 					'game_type' => 'PlayNGO Slots Game',
		// 					'game_type_lang' => 'fg_playngo_slots_game',
		// 					'status' => self::FLAG_TRUE,
		// 					'flag_show_in_site' => self::FLAG_TRUE,
		// 					'game_description_list' => array(
		// 						array(
		// 							'game_name' => '5x Magic',
		// 							'english_name' => '5x Magic',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '199',
		// 							'external_game_id' => '199',
		// 							'related_game_desc_id' => '5xmagic',
		// 						),
		// 						array(
		// 							'game_name' => 'Ace of Spades',
		// 							'english_name' => 'Ace of Spades',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '99',
		// 							'external_game_id' => '99',
		// 							'related_game_desc_id' => 'aceofspades',
		// 						),
		// 						array(
		// 							'game_name' => 'Aztec Idols',
		// 							'english_name' => 'Aztec Idols',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '243',
		// 							'external_game_id' => '243',
		// 							'related_game_desc_id' => 'aztecidols',
		// 						),
		// 						array(
		// 							'game_name' => 'Aztec Princess',
		// 							'english_name' => 'Aztec Princess',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '301',
		// 							'external_game_id' => '301',
		// 							'related_game_desc_id' => 'aztecprincess',
		// 						),

		// 						array(
		// 							'game_name' => 'Bell of Fortune',
		// 							'english_name' => 'Bell of Fortune',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '105',
		// 							'external_game_id' => '105',
		// 							'related_game_desc_id' => 'belloffortune',
		// 						),
		// 						array(
		// 							'game_name' => 'Book of Dead',
		// 							'english_name' => 'Book of Dead',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '310',
		// 							'external_game_id' => '310',
		// 							'related_game_desc_id' => 'bookofdead',
		// 						),
		// 						array(
		// 							'game_name' => 'Cats and Cash',
		// 							'english_name' => 'Cats and Cash',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '193',
		// 							'external_game_id' => '193',
		// 							'related_game_desc_id' => 'catsandcash',
		// 						),
		// 						array(
		// 							'game_name' => 'Chinese New Year',
		// 							'english_name' => 'Chinese New Year',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '277',
		// 							'external_game_id' => '277',
		// 							'related_game_desc_id' => 'chinesenewyear',
		// 						),
		// 						array(
		// 							'game_name' => 'Cops n Robbers',
		// 							'english_name' => 'Cops n Robbers',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '194',
		// 							'external_game_id' => '194',
		// 							'related_game_desc_id' => 'copsnrobbers',
		// 						),
		// 						array(
		// 							'game_name' => 'Crazy Cows',
		// 							'english_name' => 'Crazy Cows',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '284',
		// 							'external_game_id' => '284',
		// 							'related_game_desc_id' => 'crazycows',
		// 						),
		// 						array(
		// 							'game_name' => 'Dragon Ship',
		// 							'english_name' => 'Dragon Ship',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '238',
		// 							'external_game_id' => '238',
		// 							'related_game_desc_id' => 'dragonship',
		// 						),
		// 						array(
		// 							'game_name' => 'Easter Eggs',
		// 							'english_name' => 'Easter Eggs',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '293',
		// 							'external_game_id' => '293',
		// 							'related_game_desc_id' => 'eastereggs',
		// 						),
		// 						array(
		// 							'game_name' => 'Enchanted Crystals',
		// 							'english_name' => 'Enchanted Crystals',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '259',
		// 							'external_game_id' => '259',
		// 							'related_game_desc_id' => 'enchantedcrystals',
		// 						),
		// 						array(
		// 							'game_name' => 'Enchanted Meadow',
		// 							'english_name' => 'Enchanted Meadow',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '225',
		// 							'external_game_id' => '225',
		// 							'related_game_desc_id' => 'enchantedmeadow',
		// 						),
		// 						array(
		// 							'game_name' => 'Eye of the Kraken',
		// 							'english_name' => 'Eye of the Kraken',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '297',
		// 							'external_game_id' => '297',
		// 							'related_game_desc_id' => 'eyeofthekraken',
		// 						),
		// 						array(
		// 							'game_name' => 'Fire Joker',
		// 							'english_name' => 'Fire Joker',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '307',
		// 							'external_game_id' => '307',
		// 							'related_game_desc_id' => 'firejoker',
		// 						),
		// 						array(
		// 							'game_name' => 'Fortune Teller',
		// 							'english_name' => 'Fortune Teller',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '196',
		// 							'external_game_id' => '196',
		// 							'related_game_desc_id' => 'fortuneteller',
		// 						),
		// 						array(
		// 							'game_name' => 'Fruit Bonanza',
		// 							'english_name' => 'Fruit Bonanza',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '43',
		// 							'external_game_id' => '43',
		// 							'related_game_desc_id' => 'fruitbonanza',
		// 						),
		// 						array(
		// 							'game_name' => 'Gift Shop',
		// 							'english_name' => 'Gift Shop',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '107',
		// 							'external_game_id' => '107',
		// 							'related_game_desc_id' => 'giftshop',
		// 						),
		// 						array(
		// 							'game_name' => 'Gold Trophy 2',
		// 							'english_name' => 'Gold Trophy 2',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '246',
		// 							'external_game_id' => '246',
		// 							'related_game_desc_id' => 'goldtrophy2',
		// 						),
		// 						array(
		// 							'game_name' => 'Golden Caravan',
		// 							'english_name' => 'Golden Caravan',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '312',
		// 							'external_game_id' => '312',
		// 							'related_game_desc_id' => 'goldencaravan',
		// 						),
		// 						array(
		// 							'game_name' => 'Golden Goal',
		// 							'english_name' => 'Golden Goal',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '108',
		// 							'external_game_id' => '108',
		// 							'related_game_desc_id' => 'goldengoal',
		// 						),
		// 						array(
		// 							'game_name' => 'Golden Legend',
		// 							'english_name' => 'Golden Legend',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '290',
		// 							'external_game_id' => '290',
		// 							'related_game_desc_id' => 'goldenlegend',
		// 						),
		// 						array(
		// 							'game_name' => 'Gunslinger',
		// 							'english_name' => 'Gunslinger',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '244',
		// 							'external_game_id' => '244',
		// 							'related_game_desc_id' => 'gunslinger',
		// 						),
		// 						array(
		// 							'game_name' => 'Happy Halloween',
		// 							'english_name' => 'Happy Halloween',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '305',
		// 							'external_game_id' => '305',
		// 							'related_game_desc_id' => 'happyhalloween',
		// 						),
		// 						array(
		// 							'game_name' => 'Irish Gold',
		// 							'english_name' => 'Irish Gold',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '200',
		// 							'external_game_id' => '200',
		// 							'related_game_desc_id' => 'irishgold',
		// 						),
		// 						array(
		// 							'game_name' => 'Jewel Box',
		// 							'english_name' => 'Jewel Box',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '242',
		// 							'external_game_id' => '242',
		// 							'related_game_desc_id' => 'jewelbox',
		// 						),
		// 						array(
		// 							'game_name' => 'Jolly Roger',
		// 							'english_name' => 'Jolly Roger',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '40',
		// 							'external_game_id' => '40',
		// 							'related_game_desc_id' => 'jollyroger',
		// 						),
		// 						array(
		// 							'game_name' => 'Lady of Fortune',
		// 							'english_name' => 'Lady of Fortune',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '278',
		// 							'external_game_id' => '278',
		// 							'related_game_desc_id' => 'ladyoffortune',
		// 						),
		// 						array(
		// 							'game_name' => 'Leprechaun goes Egypt',
		// 							'english_name' => 'Leprechaun goes Egypt',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '251',
		// 							'external_game_id' => '251',
		// 							'related_game_desc_id' => 'leprechaungoesegypt',
		// 						),
		// 						array(
		// 							'game_name' => 'Lucky Diamonds',
		// 							'english_name' => 'Lucky Diamonds',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '5',
		// 							'external_game_id' => '5',
		// 							'related_game_desc_id' => 'luckydiamonds',
		// 						),
		// 						array(
		// 							'game_name' => 'Lucky Diamonds',
		// 							'english_name' => 'Lucky Diamonds',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '5',
		// 							'external_game_id' => '5',
		// 							'related_game_desc_id' => 'luckydiamonds',
		// 						),
		// 						array(
		// 							'game_name' => 'Merry Xmas',
		// 							'english_name' => 'Merry Xmas',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '288',
		// 							'external_game_id' => '288',
		// 							'related_game_desc_id' => 'merryxmas',
		// 						),
		// 						array(
		// 							'game_name' => 'Mystery Joker',
		// 							'english_name' => 'Mystery Joker',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '283',
		// 							'external_game_id' => '283',
		// 							'related_game_desc_id' => 'mysteryjoker',
		// 						),
		// 						array(
		// 							'game_name' => 'Myth',
		// 							'english_name' => 'Myth',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '245',
		// 							'external_game_id' => '245',
		// 							'related_game_desc_id' => 'myth',
		// 						),
		// 						array(
		// 							'game_name' => 'Ninja Fruits',
		// 							'english_name' => 'Ninja Fruits',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '253',
		// 							'external_game_id' => '253',
		// 							'related_game_desc_id' => 'ninjafruits',
		// 						),
		// 						array(
		// 							'game_name' => 'Pearl Lagoon',
		// 							'english_name' => 'Pearl Lagoon',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '241',
		// 							'external_game_id' => '241',
		// 							'related_game_desc_id' => 'pearllagoon',
		// 						),
		// 						array(
		// 							'game_name' => 'Photo Safari',
		// 							'english_name' => 'Photo Safari',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '197',
		// 							'external_game_id' => '197',
		// 							'related_game_desc_id' => 'photosafari',
		// 						),
		// 						array(
		// 							'game_name' => 'Pimped',
		// 							'english_name' => 'Pimped',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '291',
		// 							'external_game_id' => '291',
		// 							'related_game_desc_id' => 'pimped',
		// 						),
		// 						array(
		// 							'game_name' => 'Rage to Riches',
		// 							'english_name' => 'Rage to Riches',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '257',
		// 							'external_game_id' => '257',
		// 							'related_game_desc_id' => 'ragetoriches',
		// 						),
		// 						array(
		// 							'game_name' => 'Riches of RA',
		// 							'english_name' => 'Riches of RA',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '237',
		// 							'external_game_id' => '237',
		// 							'related_game_desc_id' => 'richesofra',
		// 						),
		// 						array(
		// 							'game_name' => 'Royal Masquerade',
		// 							'english_name' => 'Royal Masquerade',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '298',
		// 							'external_game_id' => '298',
		// 							'related_game_desc_id' => 'masquerade',
		// 						),
		// 						array(
		// 							'game_name' => 'Sails of Gold',
		// 							'english_name' => 'Sails of Gold',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '311',
		// 							'external_game_id' => '311',
		// 							'related_game_desc_id' => 'sailsofgold',
		// 						),
		// 						array(
		// 							'game_name' => 'Samba Carnival',
		// 							'english_name' => 'Samba Carnival',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '304',
		// 							'external_game_id' => '304',
		// 							'related_game_desc_id' => 'sambacarnival',
		// 						),
		// 						array(
		// 							'game_name' => 'Space Race',
		// 							'english_name' => 'Space Race',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '198',
		// 							'external_game_id' => '198',
		// 							'related_game_desc_id' => 'spacerace',
		// 						),
		// 						array(
		// 							'game_name' => 'Speed Cash',
		// 							'english_name' => 'Speed Cash',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '106',
		// 							'external_game_id' => '106',
		// 							'related_game_desc_id' => 'speedcash',
		// 						),
		// 						array(
		// 							'game_name' => 'Spin Party',
		// 							'english_name' => 'Spin Party',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '292',
		// 							'external_game_id' => '292',
		// 							'related_game_desc_id' => 'spinparty',
		// 						),
		// 						array(
		// 							'game_name' => 'Tower Quest',
		// 							'english_name' => 'Tower Quest',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '287',
		// 							'external_game_id' => '287',
		// 							'related_game_desc_id' => 'towerquest',
		// 						),
		// 						array(
		// 							'game_name' => 'Wild Blood',
		// 							'english_name' => 'Wild Blood',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '250',
		// 							'external_game_id' => '250',
		// 							'related_game_desc_id' => 'wildblood',
		// 						),
		// 						array(
		// 							'game_name' => 'Wild Melon',
		// 							'english_name' => 'Wild Melon',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '4',
		// 							'external_game_id' => '4',
		// 							'related_game_desc_id' => 'wildmelon',
		// 						),
		// 						array(
		// 							'game_name' => 'Wild North',
		// 							'english_name' => 'Wild North',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '294',
		// 							'external_game_id' => '294',
		// 							'related_game_desc_id' => 'wildnorth',
		// 						),
		// 						array(
		// 							'game_name' => 'Wizard of Gems',
		// 							'english_name' => 'Wizard of Gems',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '302',
		// 							'external_game_id' => '302',
		// 							'related_game_desc_id' => 'wizardofgems',
		// 						),
		// 						array(
		// 							'game_name' => 'Xmas Joker',
		// 							'english_name' => 'Xmas Joker',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '309',
		// 							'external_game_id' => '309',
		// 							'related_game_desc_id' => 'christmasjoker',
		// 						),
		// 					),
		// 				),
		// 				array(
		// 					'game_type' => 'PlayNGO Table Game',
		// 					'game_type_lang' => 'fg_playngo_table_game',
		// 					'status' => self::FLAG_TRUE,
		// 					'flag_show_in_site' => self::FLAG_TRUE,
		// 					'game_description_list' => array(
		// 						array(
		// 							'game_name' => 'Beat Me',
		// 							'english_name' => 'Beat Me',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '34',
		// 							'external_game_id' => '34',
		// 						 	'related_game_desc_id' => 'beatme',
		// 						),
		// 						array(
		// 							'game_name' => 'BlackJack MH',
		// 							'english_name' => 'BlackJack MH',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '52',
		// 							'external_game_id' => '52',
		// 						 	'related_game_desc_id' => 'blackjackmh',
		// 						),
		// 						array(
		// 							'game_name' => 'Casino Hold\'em',
		// 							'english_name' => 'Casino Hold\'em',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '57',
		// 							'external_game_id' => '57',
		// 							'related_game_desc_id' => 'casinoholdem',
		// 						),
		// 						array(
		// 							'game_name' => 'Casino Stud Poker',
		// 							'english_name' => 'Casino Stud Poker',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '35',
		// 							'external_game_id' => '35',
		// 							'related_game_desc_id' => 'casinostudpoker',
		// 						),
		// 						array(
		// 							'game_name' => 'Double Exposure BlackJack MH',
		// 							'english_name' => 'Double Exposure BlackJack MH',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '54',
		// 							'external_game_id' => '54',
		// 							'related_game_desc_id' => 'doubleexposureblackjackmh',
		// 						),
		// 						array(
		// 							'game_name' => 'English Roulette',
		// 							'english_name' => 'English Roulette',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '32',
		// 							'external_game_id' => '32',
		// 							'related_game_desc_id' => 'englishroulette',
		// 						),
		// 						array(
		// 							'game_name' => 'English Roulette La Partage',
		// 							'english_name' => 'English Roulette La Partage',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '81',
		// 							'external_game_id' => '81',
		// 							'related_game_desc_id' => 'englishroulettelp',
		// 						),
		// 						array(
		// 							'game_name' => 'European BlackJack MH',
		// 							'english_name' => 'European BlackJack MH',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '53',
		// 							'external_game_id' => '53',
		// 							'related_game_desc_id' => 'europeanblackjackmh',
		// 						),
		// 						array(
		// 							'game_name' => 'European Roulette',
		// 							'english_name' => 'European Roulette',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '31',
		// 							'external_game_id' => '31',
		// 							'related_game_desc_id' => 'europeanroulette',
		// 						),
		// 						array(
		// 							'game_name' => 'European Roulette La Partage',
		// 							'english_name' => 'European Roulette La Partage',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '80',
		// 							'external_game_id' => '80',
		// 							'related_game_desc_id' => 'europeanroulettelp',
		// 						),
		// 						array(
		// 							'game_name' => 'French Roulette',
		// 							'english_name' => 'French Roulette',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '33',
		// 							'external_game_id' => '33',
		// 							'related_game_desc_id' => 'frenchroulettelp',
		// 						),
		// 						array(
		// 							'game_name' => 'Pai Gow Poker',
		// 							'english_name' => 'Pai Gow Poker',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '58',
		// 							'external_game_id' => '58',
		// 							'related_game_desc_id' => 'paigowpoker',
		// 						),
		// 						array(
		// 							'game_name' => 'Single Deck BlackJack MH',
		// 							'english_name' => 'Single Deck BlackJack MH',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '55',
		// 							'external_game_id' => '55',
		// 							'related_game_desc_id' => 'singledeckblackjackmh',
		// 						),
		// 					),
		// 				),
		// 				array(
		// 					'game_type' => 'PlayNGO Grid Slot Game',
		// 					'game_type_lang' => 'fg_playngo_grid_slots_game',
		// 					'status' => self::FLAG_TRUE,
		// 					'flag_show_in_site' => self::FLAG_TRUE,
		// 					'game_description_list' => array(
		// 						array(
		// 							'game_name' => 'Cloud Quest',
		// 							'english_name' => 'Cloud Quest',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '300',
		// 							'external_game_id' => '300',
		// 							'related_game_desc_id' => 'cloudquest',
		// 						),
		// 						array(
		// 							'game_name' => 'Energoonz',
		// 							'english_name' => 'Energoonz',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '262',
		// 							'external_game_id' => '262',
		// 							'related_game_desc_id' => 'energoonz',
		// 						),
		// 						array(
		// 							'game_name' => 'GEMiX',
		// 							'english_name' => 'GEMiX',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '286',
		// 							'external_game_id' => '286',
		// 							'related_game_desc_id' => 'gemix',
		// 						),
		// 						array(
		// 							'game_name' => 'Golden Ticket',
		// 							'english_name' => 'Golden Ticket',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '285',
		// 							'external_game_id' => '285',
		// 							'related_game_desc_id' => 'goldenticket',
		// 						),
		// 					),
		// 				),
		// 				array(
		// 					'game_type' => 'PlayNGO Video Poker Game',
		// 					'game_type_lang' => 'fg_playngo_video_poker_game',
		// 					'status' => self::FLAG_TRUE,
		// 					'flag_show_in_site' => self::FLAG_TRUE,
		// 					'game_description_list' => array(
		// 						array(
		// 							'game_name' => 'Deuces & Joker',
		// 							'english_name' => 'Deuces & Joker',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '275',
		// 							'external_game_id' => '275',
		// 							'related_game_desc_id' => 'deucesandjoker',
		// 						),
		// 						array(
		// 							'game_name' => 'Deuces Wild MH',
		// 							'english_name' => 'Deuces Wild MH',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '270',
		// 							'external_game_id' => '270',
		// 							'related_game_desc_id' => 'deuceswild',
		// 						),
		// 						array(
		// 							'game_name' => 'Double Bonus',
		// 							'english_name' => 'Double Bonus',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '274',
		// 							'external_game_id' => '274',
		// 							'related_game_desc_id' => 'doublebonus',
		// 						),
		// 						array(
		// 							'game_name' => 'Jackpot Poker',
		// 							'english_name' => 'Jackpot Poker',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '276',
		// 							'external_game_id' => '276',
		// 							'related_game_desc_id' => 'jackpotpoker',
		// 						),
		// 						array(
		// 							'game_name' => 'Jacks or Better MH',
		// 							'english_name' => 'Jacks or Better MH',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '269',
		// 							'external_game_id' => '269',
		// 							'related_game_desc_id' => 'jacksorbetter',
		// 						),
		// 						array(
		// 							'game_name' => 'Kings of Better',
		// 							'english_name' => 'Kings of Better',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '272',
		// 							'external_game_id' => '272',
		// 							'related_game_desc_id' => 'kingsorbetter',
		// 						),
		// 						array(
		// 							'game_name' => 'Tens or Better',
		// 							'english_name' => 'Tens or Better',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '273',
		// 							'external_game_id' => '273',
		// 							'related_game_desc_id' => 'tensorbetter',
		// 						),
		// 					),
		// 				),
		// 				array(
		// 					'game_type' => 'PlayNGO Scratch Card Game',
		// 					'game_type_lang' => 'fg_playngo_scratch_card_game',
		// 					'status' => self::FLAG_TRUE,
		// 					'flag_show_in_site' => self::FLAG_TRUE,
		// 					'game_description_list' => array(
		// 						array(
		// 							'game_name' => 'Hole-in-one',
		// 							'english_name' => 'Hole-in-one',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '94',
		// 							'external_game_id' => '94',
		// 							'related_game_desc_id' => 'holeinone',
		// 						),
		// 						array(
		// 							'game_name' => 'Scratch Ahoy',
		// 							'english_name' => 'Scratch Ahoy',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '93',
		// 							'external_game_id' => '93',
		// 							'related_game_desc_id' => 'scratchahoy',
		// 						),
		// 					),
		// 				),
		// 				array(
		// 					'game_type' => 'PlayNGO Mini Games',
		// 					'game_type_lang' => 'fg_playngo_mini_game',
		// 					'status' => self::FLAG_TRUE,
		// 					'flag_show_in_site' => self::FLAG_TRUE,
		// 					'game_description_list' => array(
		// 						array(
		// 							'game_name' => 'Mini Baccarat',
		// 							'english_name' => 'Mini Baccarat',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '11',
		// 							'external_game_id' => '11',
		// 							'related_game_desc_id' => 'minibaccarat',
		// 						),
		// 					),
		// 				),
		// 				array(
		// 					'game_type' => 'PlayNGO Other Games',
		// 					'game_type_lang' => 'fg_playngo_other_games',
		// 					'status' => self::FLAG_TRUE,
		// 					'flag_show_in_site' => self::FLAG_TRUE,
		// 					'game_description_list' => array(
		// 						array(
		// 							'game_name' => 'Triple Chance HiLo',
		// 							'english_name' => 'Triple Chance HiLo',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => '235',
		// 							'external_game_id' => '235',
		// 							'related_game_desc_id' => 'triplechancehilo',
		// 						),
		// 					),
		// 				),
		// 				array(
		// 					'game_type' => 'unknown',
		// 					'game_type_lang' => 'fg.unknown',
		// 					'status' => self::FLAG_TRUE,
		// 					'flag_show_in_site' => self::FLAG_FALSE,
		// 					'game_description_list' => array(
		// 						array(
		// 							'game_name' => 'fg.unknown',
		// 							'english_name' => 'fg.unknown',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled'  =>self::FLAG_TRUE,
		// 							'mobile_enabled' =>self::FLAG_FALSE,
		// 							'game_code' => 'unknown',
		// 							'external_game_id' => 'unknown',
		// 							'related_game_desc_id' => 'unknown',
		// 						)
		// 					)
		// 				),
		// 			);

		// $game_description_list = array();
		// foreach ($data as $game_type) {

		// 	$this->db->insert('game_type', array(
		// 		'game_platform_id' => FG_API,
		// 		'game_type' => $game_type['game_type'],
		// 		'game_type_lang' => $game_type['game_type_lang'],
		// 		'status' => $game_type['status'],
		// 		'flag_show_in_site' => $game_type['flag_show_in_site'],
		// 		));

		// 	$game_type_id = $this->db->insert_id();
		// 	foreach ($game_type['game_description_list'] as $game_description) {
		// 		$game_description_list[] = array_merge(array(
		// 			'game_platform_id' => FG_API,
		// 			'game_type_id' => $game_type_id,
		// 			), $game_description);
		// 	}

		// }

		// $this->db->insert_batch('game_description', $game_description_list);
		// $this->db->trans_complete();
	}

	public function down() {
		// $this->db->trans_start();
		// $this->db->delete('game_type', array('game_platform_id' => FG_API));
		// $this->db->delete('game_description', array('game_platform_id' => FG_API));
		// $this->db->trans_complete();
	}
}