<?php

defined('BASEPATH') OR exit('No direct script access allowed');

class Migration_add_flowgaming_to_game_type_and_game_description_201607020651 extends CI_Migration {

	const FLAG_TRUE = 1;
	const FLAG_FALSE = 0;

	public function up() {
		// $this->db->trans_start();
		// $data = array(
		// 				array(
		// 					'game_type' => 'PlayNGO Slot Mobile Games',
		// 					'game_type_lang' => 'fg_playngo_slot_mobile_games',
		// 					'status' => self::FLAG_TRUE,
		// 					'flag_show_in_site' => self::FLAG_TRUE,
		// 					'game_description_list' => array(
		// 						array(
		// 							'game_name' => '5x Magic Mobile',
		// 							'english_name' => '5x Magic Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100199',
		// 							'external_game_id' => '100199',
		// 							'related_game_desc_id' => '5xmagicmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Ace of Spades Mobile',
		// 							'english_name' => 'Ace of Spades Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100099',
		// 							'external_game_id' => '100099',
		// 							'related_game_desc_id' => 'aceofspadesmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Aztec Idols Mobile',
		// 							'english_name' => 'Aztec Idols Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100243',
		// 							'external_game_id' => '100243',
		// 							'related_game_desc_id' => 'aztecidolsmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Bell of Fortune Mobile',
		// 							'english_name' => 'Bell of Fortune Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100105',
		// 							'external_game_id' => '100105',
		// 							'related_game_desc_id' => 'belloffortunemobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Book of Dead Mobile',
		// 							'english_name' => 'Book of Dead Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100310',
		// 							'external_game_id' => '100310',
		// 							'related_game_desc_id' => 'bookofdeadmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Chinese New Year Mobile',
		// 							'english_name' => 'Chinese New Year Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100277',
		// 							'external_game_id' => '100277',
		// 							'related_game_desc_id' => 'chinesenewyearmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Crazy Cows Mobile',
		// 							'english_name' => 'Crazy Cows Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100284',
		// 							'external_game_id' => '100284',
		// 							'related_game_desc_id' => 'crazycowsmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Dragon Ship Mobile',
		// 							'english_name' => 'Dragon Ship Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100238',
		// 							'external_game_id' => '100238',
		// 							'related_game_desc_id' => 'dragonshipmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Easter Eggs Mobile',
		// 							'english_name' => 'Easter Eggs Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100293',
		// 							'external_game_id' => '100293',
		// 							'related_game_desc_id' => 'eastereggsmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Enchanted Crystals Mobile',
		// 							'english_name' => 'Enchanted Crystals Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100259',
		// 							'external_game_id' => '100259',
		// 							'related_game_desc_id' => 'enchantedcrystalsmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Enchanted Meadow Mobile',
		// 							'english_name' => 'Enchanted Meadow Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100225',
		// 							'external_game_id' => '100225',
		// 							'related_game_desc_id' => 'enchantedmeadowmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Eye of the Kraken Mobile',
		// 							'english_name' => 'Eye of the Kraken Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100297',
		// 							'external_game_id' => '100297',
		// 							'related_game_desc_id' => 'eyeofthekrakenmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Fire Joker',
		// 							'english_name' => 'Fire Joker',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100307',
		// 							'external_game_id' => '100307',
		// 							'related_game_desc_id' => 'firejokermobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Fortune Teller Mobile',
		// 							'english_name' => 'Fortune Teller Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100196',
		// 							'external_game_id' => '100196',
		// 							'related_game_desc_id' => 'fortunetellermobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Fruit Bonanza Mobile',
		// 							'english_name' => 'Fruit Bonanza Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100043',
		// 							'external_game_id' => '100043',
		// 							'related_game_desc_id' => 'fruitbonanzamobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Gift Shop Mobile',
		// 							'english_name' => 'Gift Shop Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100107',
		// 							'external_game_id' => '100107',
		// 							'related_game_desc_id' => 'giftshopmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Gold Trophy 2 Mobile',
		// 							'english_name' => 'Gold Trophy 2 Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100246',
		// 							'external_game_id' => '100246',
		// 							'related_game_desc_id' => 'goldtrophy2mobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Golden Caravan',
		// 							'english_name' => 'Golden Caravan',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100312',
		// 							'external_game_id' => '100312',
		// 							'related_game_desc_id' => 'goldencaravanmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Golden Goal Mobile',
		// 							'english_name' => 'Golden Goal Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100108',
		// 							'external_game_id' => '100108',
		// 							'related_game_desc_id' => 'goldengoalmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Golden Legend Mobile',
		// 							'english_name' => 'Golden Legend Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100290',
		// 							'external_game_id' => '100290',
		// 							'related_game_desc_id' => 'goldenlegendmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Happy Halloween Mobile',
		// 							'english_name' => 'Happy Halloween Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100305',
		// 							'external_game_id' => '100305',
		// 							'related_game_desc_id' => 'happyhalloweenmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Irish Gold Mobile',
		// 							'english_name' => 'Irish Gold Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100200',
		// 							'external_game_id' => '100200',
		// 							'related_game_desc_id' => 'irishgoldmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Jewel Box Mobile',
		// 							'english_name' => 'Jewel Box Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100242',
		// 							'external_game_id' => '100242',
		// 							'related_game_desc_id' => 'jewelboxmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Jolly Roger Mobile',
		// 							'english_name' => 'Jolly Roger Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100040',
		// 							'external_game_id' => '100040',
		// 							'related_game_desc_id' => 'jollyrogermobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Lady of Fortune Mobile',
		// 							'english_name' => 'Lady of Fortune Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100278',
		// 							'external_game_id' => '100278',
		// 							'related_game_desc_id' => 'ladyoffortunemobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Lucky Diamonds Mobile',
		// 							'english_name' => 'Lucky Diamonds Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100005',
		// 							'external_game_id' => '100005',
		// 							'related_game_desc_id' => 'luckydiamondsmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Merry Xmas Mobile',
		// 							'english_name' => 'Merry Xmas Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100288',
		// 							'external_game_id' => '100288',
		// 							'related_game_desc_id' => 'merryxmasmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Mystery Joker Mobile',
		// 							'english_name' => 'Mystery Joker Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100283',
		// 							'external_game_id' => '100283',
		// 							'related_game_desc_id' => 'mysteryjokermobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Myth Mobile',
		// 							'english_name' => 'Myth Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100245',
		// 							'external_game_id' => '100245',
		// 							'related_game_desc_id' => 'mythmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Ninja Fruits Mobile',
		// 							'english_name' => 'Ninja Fruits Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100253',
		// 							'external_game_id' => '100253',
		// 							'related_game_desc_id' => 'ninjafruitsmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Pearl Lagoon Mobile',
		// 							'english_name' => 'Pearl Lagoon Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100241',
		// 							'external_game_id' => '100241',
		// 							'related_game_desc_id' => 'pearllagoonmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Pearls of India Mobile',
		// 							'english_name' => 'Pearls of India Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100282',
		// 							'external_game_id' => '100282',
		// 							'related_game_desc_id' => 'pearlsofindiamobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Photo Safari Mobile',
		// 							'english_name' => 'Photo Safari Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100197',
		// 							'external_game_id' => '100197',
		// 							'related_game_desc_id' => 'photosafarimobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Pimped Mobile',
		// 							'english_name' => 'Pimped Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100291',
		// 							'external_game_id' => '100291',
		// 							'related_game_desc_id' => 'pimpedmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Rage to Riches Mobile',
		// 							'english_name' => 'Rage to Riches Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100257',
		// 							'external_game_id' => '100257',
		// 							'related_game_desc_id' => 'ragetorichesmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Riches of RA Mobile',
		// 							'english_name' => 'Riches of RA Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100237',
		// 							'external_game_id' => '100237',
		// 							'related_game_desc_id' => 'richesoframobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Royal Masquerade Mobile',
		// 							'english_name' => 'Royal Masquerade Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100298',
		// 							'external_game_id' => '100298',
		// 							'related_game_desc_id' => 'masquerademobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Sails of Gold',
		// 							'english_name' => 'Sails of Gold',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100311',
		// 							'external_game_id' => '100311',
		// 							'related_game_desc_id' => 'sailsofgoldmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Samba Carnival Mobile',
		// 							'english_name' => 'Samba Carnival Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100304',
		// 							'external_game_id' => '100304',
		// 							'related_game_desc_id' => 'sambacarnivalmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Space Race Mobile',
		// 							'english_name' => 'Space Race Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100198',
		// 							'external_game_id' => '100198',
		// 							'related_game_desc_id' => 'spaceracemobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Speed Cash Mobile',
		// 							'english_name' => 'Speed Cash Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100106',
		// 							'external_game_id' => '100106',
		// 							'related_game_desc_id' => 'speedcashmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Spin Party Mobile',
		// 							'english_name' => 'Spin Party Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100292',
		// 							'external_game_id' => '100292',
		// 							'related_game_desc_id' => 'spinpartymobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Tower Quest Mobile',
		// 							'english_name' => 'Tower Quest Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100287',
		// 							'external_game_id' => '100287',
		// 							'related_game_desc_id' => 'towerquestmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Wild Blood Mobile',
		// 							'english_name' => 'Wild Blood Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100250',
		// 							'external_game_id' => '100250',
		// 							'related_game_desc_id' => 'wildbloodmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Wild Melon Mobile',
		// 							'english_name' => 'Wild Melon Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100004',
		// 							'external_game_id' => '100004',
		// 							'related_game_desc_id' => 'wildmelonmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Wild North Mobile',
		// 							'english_name' => 'Wild North Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100294',
		// 							'external_game_id' => '100294',
		// 							'related_game_desc_id' => 'wildmelonmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Wild North Mobile',
		// 							'english_name' => 'Wild North Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100294',
		// 							'external_game_id' => '100294',
		// 							'related_game_desc_id' => 'wildnorthmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Wizard of Gems Mobile',
		// 							'english_name' => 'Wizard of Gems Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100302',
		// 							'external_game_id' => '100302',
		// 							'related_game_desc_id' => 'wizardofgemsmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Xmas Joker Mobile',
		// 							'english_name' => 'Xmas Joker Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100309',
		// 							'external_game_id' => '100309',
		// 							'related_game_desc_id' => 'christmasjokermobile',
		// 						),
		// 					),
		// 				),
		// 				array(
		// 					'game_type' => 'PlayNGO Grid Slot Mobile Games',
		// 					'game_type_lang' => 'fg_playngo_gridslot_mobile_games',
		// 					'status' => self::FLAG_TRUE,
		// 					'flag_show_in_site' => self::FLAG_TRUE,
		// 					'game_description_list' => array(
		// 						array(
		// 							'game_name' => 'Cloud Quest',
		// 							'english_name' => 'Cloud Quest',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100300',
		// 							'external_game_id' => '100300',
		// 							'related_game_desc_id' => 'cloudquestmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Energoonz Mobile',
		// 							'english_name' => 'Energoonz Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100262',
		// 							'external_game_id' => '100262',
		// 							'related_game_desc_id' => 'energoonzmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'GEMiX Mobile',
		// 							'english_name' => 'GEMiX Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100286',
		// 							'external_game_id' => '100286',
		// 							'related_game_desc_id' => 'gemixmobile',
		// 						),
		// 					),
		// 				),
		// 				array(
		// 					'game_type' => 'PlayNGO Table Mobile Games',
		// 					'game_type_lang' => 'fg_playngo_table_mobile_games',
		// 					'status' => self::FLAG_TRUE,
		// 					'flag_show_in_site' => self::FLAG_TRUE,
		// 					'game_description_list' => array(
		// 						array(
		// 							'game_name' => 'Beat Me Mobile',
		// 							'english_name' => 'Beat Me Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100034',
		// 							'external_game_id' => '100034',
		// 							'related_game_desc_id' => 'beatmemobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Casino Hold\'em Mobile',
		// 							'english_name' => 'Casino Hold\'em Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100057',
		// 							'external_game_id' => '100057',
		// 							'related_game_desc_id' => 'casinoholdemmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Casino Stud Poker Mobile',
		// 							'english_name' => 'Casino Stud Poker Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100035',
		// 							'external_game_id' => '100035',
		// 							'related_game_desc_id' => 'casinostudpokermobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Double Exposure Mobile',
		// 							'english_name' => 'Double Exposure Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100054',
		// 							'external_game_id' => '100054',
		// 							'related_game_desc_id' => 'doubleexposureblackjackmhmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'European Blackjack Mobile',
		// 							'english_name' => 'European Blackjack Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100053',
		// 							'external_game_id' => '100053',
		// 							'related_game_desc_id' => 'europeanblackjackmhmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'European Roulette Mobile',
		// 							'english_name' => 'European Roulette Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100031',
		// 							'external_game_id' => '100031',
		// 							'related_game_desc_id' => 'europeanroulettemobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Mini Baccarat Mobile',
		// 							'english_name' => 'Mini Baccarat Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100011',
		// 							'external_game_id' => '100011',
		// 							'related_game_desc_id' => 'minibaccaratmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Money Wheel',
		// 							'english_name' => 'Money Wheel',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100318',
		// 							'external_game_id' => '100318',
		// 							'related_game_desc_id' => 'moneywheelmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Pai Gow Poker Mobile',
		// 							'english_name' => 'Pai Gow Poker Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100058',
		// 							'external_game_id' => '100058',
		// 							'related_game_desc_id' => 'paigowpokermobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Single Deck Blackjack Mobile',
		// 							'english_name' => 'Single Deck Blackjack Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100055',
		// 							'external_game_id' => '100055',
		// 							'related_game_desc_id' => 'singledeckblackjackmhmobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Single Deck Blackjack Mobile',
		// 							'english_name' => 'Single Deck Blackjack Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100055',
		// 							'external_game_id' => '100055',
		// 							'related_game_desc_id' => 'singledeckblackjackmhmobile',
		// 						),
		// 					),
		// 				),
		// 				array(
		// 					'game_type' => 'PlayNGO Scratch Mobile Games',
		// 					'game_type_lang' => 'fg_playngo_scratch_mobile_games',
		// 					'status' => self::FLAG_TRUE,
		// 					'flag_show_in_site' => self::FLAG_TRUE,
		// 					'game_description_list' => array(
		// 						array(
		// 							'game_name' => 'Scratch Ahoy Mobile',
		// 							'english_name' => 'Scratch Ahoy Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100093',
		// 							'external_game_id' => '100093',
		// 							'related_game_desc_id' => 'scratchahoymobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Hole-in-One Mobile',
		// 							'english_name' => 'Hole-in-One Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100094',
		// 							'external_game_id' => '100094',
		// 							'related_game_desc_id' => 'holeinonemobile',
		// 						),
		// 					),
		// 				),
		// 				array(
		// 					'game_type' => 'PlayNGO Other Mobile Games',
		// 					'game_type_lang' => 'fg_playngo_other_mobile_games',
		// 					'status' => self::FLAG_TRUE,
		// 					'flag_show_in_site' => self::FLAG_TRUE,
		// 					'game_description_list' => array(
		// 						array(
		// 							'game_name' => 'Keno Mobile',
		// 							'english_name' => 'Keno Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100239',
		// 							'external_game_id' => '100239',
		// 							'related_game_desc_id' => 'kenomobile',
		// 						),
		// 						array(
		// 							'game_name' => 'Triple Chance HiLo Mobile',
		// 							'english_name' => 'Triple Chance HiLo Mobile',
		// 							'html_five_enabled' =>self::FLAG_FALSE,
		// 							'flash_enabled' =>self::FLAG_FALSE,
		// 							'mobile_enabled' =>self::FLAG_TRUE,
		// 							'game_code' => '100235',
		// 							'external_game_id' => '100235',
		// 							'related_game_desc_id' => 'triplechancehilomobile',
		// 						),
		// 					),
		// 				),
		// 			);

		// $game_description_list = array();
		// foreach ($data as $game_type) {

		// 	$this->db->insert('game_type', array(
		// 		'game_platform_id' => FG_API,
		// 		'game_type' => $game_type['game_type'],
		// 		'game_type_lang' => $game_type['game_type_lang'],
		// 		'status' => $game_type['status'],
		// 		'flag_show_in_site' => $game_type['flag_show_in_site'],
		// 		));

		// 	$game_type_id = $this->db->insert_id();
		// 	foreach ($game_type['game_description_list'] as $game_description) {
		// 		$game_description_list[] = array_merge(array(
		// 			'game_platform_id' => FG_API,
		// 			'game_type_id' => $game_type_id,
		// 			), $game_description);
		// 	}

		// }

		// $this->db->insert_batch('game_description', $game_description_list);
		// $this->db->trans_complete();
	}

	public function down() {
		// $this->db->trans_start();
		// $this->db->delete('game_type', array('game_platform_id' => FG_API));
		// $this->db->delete('game_description', array('game_platform_id' => FG_API));
		// $this->db->trans_complete();
	}
}