<?php

defined('BASEPATH') OR exit('No direct script access allowed');

class Migration_add_isoftbet_game_type_and_game_description_201607150256 extends CI_Migration {

	const FLAG_TRUE = 1;
	const FLAG_FALSE = 0;

	public function up() {
		// $this->db->trans_start();
		// $data = array(
		// 	array(
		// 		'game_type' => 'Isoftbet Slots Game',
		// 		'game_type_lang' => 'isb_slots_game',
		// 		'status' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'game_description_list' => array(
		// 			array(
		// 				'game_name' => 'Skulls of Legend',
		// 				'english_name' => 'Skulls of Legend',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_FALSE,
		// 				'game_code' => NULL,
		// 				'external_game_id' => NULL,
		// 			),
		// 			array(
		// 				'game_name' => 'Cloud Tales',
		// 				'english_name' => 'Cloud Tales',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '​881597',
		// 				'external_game_id' => '​881597',
		// 			),
		// 			array(
		// 				'game_name' => 'MegaBoy',
		// 				'english_name' => 'MegaBoy',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881589',
		// 				'external_game_id' => '881589',
		// 			),
		// 			array(
		// 				'game_name' => 'Alice Adventure',
		// 				'english_name' => 'Alice Adventure',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881525',
		// 				'external_game_id' => '881525',
		// 			),
		// 			array(
		// 				'game_name' => 'Aliens Attack',
		// 				'english_name' => 'Aliens Attack',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881565',
		// 				'external_game_id' => '881565',
		// 			),
		// 			array(
		// 				'game_name' => 'Ambiance',
		// 				'english_name' => 'Ambiance',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881578',
		// 				'external_game_id' => '881578',
		// 			),
		// 			array(
		// 				'game_name' => 'Astro Magic',
		// 				'english_name' => 'Astro Magic',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881591',
		// 				'external_game_id' => '881591',
		// 			),
		// 			array(
		// 				'game_name' => 'Best things in life',
		// 				'english_name' => 'Best things in life',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881573',
		// 				'external_game_id' => '881573',
		// 			),
		// 			array(
		// 				'game_name' => 'Bewitched',
		// 				'english_name' => 'Bewitched',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881508',
		// 				'external_game_id' => '881508',
		// 			),
		// 			array(
		// 				'game_name' => 'Bug\'s World',
		// 				'english_name' => 'Bug\'s World',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881270',
		// 				'external_game_id' => '881270',
		// 			),
		// 			array(
		// 				'game_name' => 'Dolphin\'s Island',
		// 				'english_name' => 'Dolphin\'s Island',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881586',
		// 				'external_game_id' => '881586',
		// 			),
		// 			array(
		// 				'game_name' => 'Fruit Boxes',
		// 				'english_name' => 'Fruit Boxes',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881527',
		// 				'external_game_id' => '881527',
		// 			),
		// 			array(
		// 				'game_name' => 'Gifts From Caesar',
		// 				'english_name' => 'Gifts From Caesar',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881556',
		// 				'external_game_id' => '881556',
		// 			),
		// 			array(
		// 				'game_name' => 'Happy Birds',
		// 				'english_name' => 'Happy Birds',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881572',
		// 				'external_game_id' => '881572',
		// 			),
		// 			array(
		// 				'game_name' => 'Illusions 2',
		// 				'english_name' => 'Illusions 2',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881526',
		// 				'external_game_id' => '881526',
		// 			),
		// 			array(
		// 				'game_name' => 'Lucky Leprechaun',
		// 				'english_name' => 'Lucky Leprechaun',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881537',
		// 				'external_game_id' => '881537',
		// 			),
		// 			array(
		// 				'game_name' => 'Luxury Rome',
		// 				'english_name' => 'Luxury Rome',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881595',
		// 				'external_game_id' => '881595',
		// 			),
		// 			array(
		// 				'game_name' => 'Mona Lisa Jewels',
		// 				'english_name' => 'Mona Lisa Jewels',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881511',
		// 				'external_game_id' => '881511',
		// 			),
		// 			array(
		// 				'game_name' => 'Musketeer Slot',
		// 				'english_name' => 'Musketeer Slot',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881250',
		// 				'external_game_id' => '881250',
		// 			),
		// 			array(
		// 				'game_name' => 'Neon Reels',
		// 				'english_name' => 'Neon Reels',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881592',
		// 				'external_game_id' => '881592',
		// 			),
		// 			array(
		// 				'game_name' => 'Ninja Chef',
		// 				'english_name' => 'Ninja Chef',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881516',
		// 				'external_game_id' => '881516',
		// 			),
		// 			array(
		// 				'game_name' => 'Pin Up Girls',
		// 				'english_name' => 'Pin Up Girls',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881280',
		// 				'external_game_id' => '881280',
		// 			),
		// 			array(
		// 				'game_name' => 'Pirates Island',
		// 				'english_name' => 'Pirates Island',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881559',
		// 				'external_game_id' => '881559',
		// 			),
		// 			array(
		// 				'game_name' => 'Red Dragon Wild',
		// 				'english_name' => 'Red Dragon Wild',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881550',
		// 				'external_game_id' => '881550',
		// 			),
		// 			array(
		// 				'game_name' => 'Royal Cash',
		// 				'english_name' => 'Royal Cash',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881549',
		// 				'external_game_id' => '881549',
		// 			),
		// 			array(
		// 				'game_name' => 'Scrolls of Ra HD',
		// 				'english_name' => 'Scrolls of Ra HD',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881585',
		// 				'external_game_id' => '881585',
		// 			),
		// 			array(
		// 				'game_name' => 'Shaolin Spin',
		// 				'english_name' => 'Shaolin Spin',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881593',
		// 				'external_game_id' => '881593',
		// 			),
		// 			array(
		// 				'game_name' => 'Spooky Family',
		// 				'english_name' => 'Spooky Family',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881521',
		// 				'external_game_id' => '881521',
		// 			),
		// 			array(
		// 				'game_name' => 'The Best Witch',
		// 				'english_name' => 'The Best Witch',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881581',
		// 				'external_game_id' => '881581',
		// 			),
		// 			array(
		// 				'game_name' => 'The Olympic Slots',
		// 				'english_name' => 'The Olympic Slots',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881538',
		// 				'external_game_id' => '881538',
		// 			),
		// 			array(
		// 				'game_name' => 'Treasure Chest',
		// 				'english_name' => 'Treasure Chest',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881557',
		// 				'external_game_id' => '881557',
		// 			),
		// 			array(
		// 				'game_name' => 'Wisps',
		// 				'english_name' => 'Wisps',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881588',
		// 				'external_game_id' => '881588',
		// 			),
		// 			array(
		// 				'game_name' => 'World Tour',
		// 				'english_name' => 'World Tour',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881563',
		// 				'external_game_id' => '881563',
		// 			),
		// 		),
		// 	),
		// 	array(
		// 		'game_type' => 'Isoftbet Mechanical Slot Game',
		// 		'game_type_lang' => 'isb_mechanical_slot_game',
		// 		'status' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'game_description_list' => array(
		// 			array(
		// 				'game_name' => 'Super Multitimes Progressive HD',
		// 				'english_name' => 'Super Multitimes Progressive HD',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881501',
		// 				'external_game_id' => '881501',
		// 			),
		// 			array(
		// 				'game_name' => 'Spin or Reel HD',
		// 				'english_name' => 'Spin or Reel HD',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881539',
		// 				'external_game_id' => '881539',
		// 			),
		// 			array(
		// 				'game_name' => '3 Hit Pay',
		// 				'english_name' => '3 Hit Pay',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881500',
		// 				'external_game_id' => '881500',
		// 			),
		// 			array(
		// 				'game_name' => 'Absolute Super Reels',
		// 				'english_name' => 'Absolute Super Reels',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881507',
		// 				'external_game_id' => '881507',
		// 			),
		// 			array(
		// 				'game_name' => 'Diamond Wild',
		// 				'english_name' => 'Diamond Wild',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881505',
		// 				'external_game_id' => '881505',
		// 			),
		// 			array(
		// 				'game_name' => 'Gold Hold',
		// 				'english_name' => 'Gold Hold',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881547',
		// 				'external_game_id' => '881547',
		// 			),
		// 			array(
		// 				'game_name' => 'Lucky Clover',
		// 				'english_name' => 'Lucky Clover',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881504',
		// 				'external_game_id' => '881504',
		// 			),
		// 			array(
		// 				'game_name' => 'Million Cents',
		// 				'english_name' => 'Million Cents',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881503',
		// 				'external_game_id' => '881503',
		// 			),
		// 			array(
		// 				'game_name' => 'Million Cents HD',
		// 				'english_name' => 'Million Cents HD',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881580',
		// 				'external_game_id' => '881580',
		// 			),
		// 			array(
		// 				'game_name' => 'Super Fast Hot Hot',
		// 				'english_name' => 'Super Fast Hot Hot',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881506',
		// 				'external_game_id' => '881506',
		// 			),
		// 			array(
		// 				'game_name' => 'Super Lucky Reels',
		// 				'english_name' => 'Super Lucky Reels',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881535',
		// 				'external_game_id' => '881535',
		// 			),
		// 			array(
		// 				'game_name' => 'Super Multitimes Progressive',
		// 				'english_name' => 'Super Multitimes Progressive',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881501',
		// 				'external_game_id' => '881501',
		// 			),
		// 			array(
		// 				'game_name' => 'Super Tricolor',
		// 				'english_name' => 'Super Tricolor',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881502',
		// 				'external_game_id' => '881502',
		// 			),
		// 			array(
		// 				'game_name' => 'Ultimate Super Reels',
		// 				'english_name' => 'Ultimate Super Reels',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881536',
		// 				'external_game_id' => '881536',
		// 			),
		// 		),
		// 	),
		// 	array(
		// 		'game_type' => 'Isoftbet Branded Slot Game',
		// 		'game_type_lang' => 'isb_branded_slot_game',
		// 		'status' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'game_description_list' => array(
		// 			array(
		// 				'game_name' => 'Platoon Wild™Progressive',
		// 				'english_name' => 'Platoon Wild™Progressive',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881605',
		// 				'external_game_id' => '881605',
		// 			),
		// 			array(
		// 				'game_name' => 'Platoon Wild™',
		// 				'english_name' => 'Platoon Wild™',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881606',
		// 				'external_game_id' => '881606',
		// 			),
		// 			array(
		// 				'game_name' => '24™',
		// 				'english_name' => '24™',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881594',
		// 				'external_game_id' => '881594',
		// 			),
		// 			array(
		// 				'game_name' => 'Basic Instinct™',
		// 				'english_name' => 'Basic Instinct™',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881513',
		// 				'external_game_id' => '881513',
		// 			),
		// 			array(
		// 				'game_name' => 'Beverly Hills 90210™',
		// 				'english_name' => 'Beverly Hills 90210™',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881570',
		// 				'external_game_id' => '881570',
		// 			),
		// 			array(
		// 				'game_name' => 'Hansel & Gretel: Witch Hunters™',
		// 				'english_name' => 'Hansel & Gretel: Witch Hunters™',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881590',
		// 				'external_game_id' => '881590',
		// 			),
		// 			array(
		// 				'game_name' => 'Heavy Metal: Warriors™',
		// 				'english_name' => 'Heavy Metal: Warriors™',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881582',
		// 				'external_game_id' => '881582',
		// 			),
		// 			array(
		// 				'game_name' => 'Jackpot Rango™',
		// 				'english_name' => 'Jackpot Rango™',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881510',
		// 				'external_game_id' => '881510',
		// 			),
		// 			array(
		// 				'game_name' => 'Kobushi™',
		// 				'english_name' => 'Kobushi™',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881517',
		// 				'external_game_id' => '881517',
		// 			),
		// 			array(
		// 				'game_name' => 'Nacho Libre™',
		// 				'english_name' => 'Nacho Libre™',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881576',
		// 				'external_game_id' => '881576',
		// 			),
		// 			array(
		// 				'game_name' => 'Platoon™',
		// 				'english_name' => 'Platoon™',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881575',
		// 				'external_game_id' => '881575',
		// 			),
		// 			array(
		// 				'game_name' => 'Rambo™',
		// 				'english_name' => 'Rambo™',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881568',
		// 				'external_game_id' => '881568',
		// 			),
		// 			array(
		// 				'game_name' => 'The Love Guru™',
		// 				'english_name' => 'The Love Guru™',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881512',
		// 				'external_game_id' => '881512',
		// 			),
		// 			array(
		// 				'game_name' => 'The Warriors™',
		// 				'english_name' => 'The Warriors™',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '881577',
		// 				'external_game_id' => '881577',
		// 			),
		// 		),
		// 	),

		// 	array(
		// 		'game_type' => 'Isoftbet Table Game',
		// 		'game_type_lang' => 'isb_table_game',
		// 		'status' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'game_description_list' => array(
		// 			array(
		// 				'game_name' => 'American Roulette',
		// 				'english_name' => 'American Roulette',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '883014',
		// 				'external_game_id' => '883014',
		// 			),
		// 			array(
		// 				'game_name' => 'Bonus Roulette',
		// 				'english_name' => 'Bonus Roulette',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '883044',
		// 				'external_game_id' => '883044',
		// 			),
		// 			array(
		// 				'game_name' => 'Easy Roulette',
		// 				'english_name' => 'Easy Roulette',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '883020',
		// 				'external_game_id' => '883020',
		// 			),
		// 			array(
		// 				'game_name' => 'European Progressive Roulette',
		// 				'english_name' => 'European Progressive Roulette',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '883017',
		// 				'external_game_id' => '883017',
		// 			),
		// 			array(
		// 				'game_name' => 'European Roulette',
		// 				'english_name' => 'European Roulette',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '883021',
		// 				'external_game_id' => '883021',
		// 			),
		// 			array(
		// 				'game_name' => 'European Roulette Small Bets',
		// 				'english_name' => 'European Roulette Small Bets',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '883012',
		// 				'external_game_id' => '883012',
		// 			),
		// 			array(
		// 				'game_name' => 'Roulette 3D',
		// 				'english_name' => 'Roulette 3D',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '883032',
		// 				'external_game_id' => '883032',
		// 			),
		// 			array(
		// 				'game_name' => 'Roulette Silver',
		// 				'english_name' => 'Roulette Silver',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '883028',
		// 				'external_game_id' => '883028',
		// 			),
		// 			array(
		// 				'game_name' => 'Roulette VIP',
		// 				'english_name' => 'Roulette VIP',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '883027',
		// 				'external_game_id' => '883027',
		// 			),
		// 			array(
		// 				'game_name' => 'Blackjack',
		// 				'english_name' => 'Blackjack',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '883007',
		// 				'external_game_id' => '883007',
		// 			),
		// 			array(
		// 				'game_name' => 'Blackjack Atlantic City',
		// 				'english_name' => 'Blackjack Atlantic City',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '883023',
		// 				'external_game_id' => '883023',
		// 			),
		// 			array(
		// 				'game_name' => 'Blackjack French',
		// 				'english_name' => 'Blackjack French',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '883033',
		// 				'external_game_id' => '883033',
		// 			),
		// 			array(
		// 				'game_name' => 'Blackjack Multi Hand 3D',
		// 				'english_name' => 'Blackjack Multi Hand 3D',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '883048',
		// 				'external_game_id' => '883048',
		// 			),
		// 			array(
		// 				'game_name' => 'Blackjack Multihand',
		// 				'english_name' => 'Blackjack Multihand',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '883016',
		// 				'external_game_id' => '883016',
		// 			),
		// 			array(
		// 				'game_name' => 'Blackjack Multihand VIP',
		// 				'english_name' => 'Blackjack Multihand VIP',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '883037',
		// 				'external_game_id' => '883037',
		// 			),
		// 			array(
		// 				'game_name' => 'Blackjack Reno',
		// 				'english_name' => 'Blackjack Reno',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '883034',
		// 				'external_game_id' => '883034',
		// 			),
		// 			array(
		// 				'game_name' => 'Blackjack Super 7\'s Multihand',
		// 				'english_name' => 'Blackjack Super 7\'s Multihand',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '883039',
		// 				'external_game_id' => '883039',
		// 			),
		// 			array(
		// 				'game_name' => 'Blackjack VIP',
		// 				'english_name' => 'Blackjack VIP',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '883029',
		// 				'external_game_id' => '883029',
		// 			),
		// 			array(
		// 				'game_name' => 'Baccarat',
		// 				'english_name' => 'Baccarat',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '883006',
		// 				'external_game_id' => '883006',
		// 			),
		// 			array(
		// 				'game_name' => 'Stud Poker',
		// 				'english_name' => 'Stud Poker',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '883008',
		// 				'external_game_id' => '883008',
		// 			),
		// 			array(
		// 				'game_name' => 'Poker Pursuit',
		// 				'english_name' => 'Poker Pursuit',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '883011',
		// 				'external_game_id' => '883011',
		// 			),
		// 			array(
		// 				'game_name' => 'Casino Hold\'em',
		// 				'english_name' => 'Casino Hold\'em',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '883024',
		// 				'external_game_id' => '883024',
		// 			),
		// 			array(
		// 				'game_name' => 'Casino High Low',
		// 				'english_name' => 'Casino High Low',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '883038',
		// 				'external_game_id' => '883038',
		// 			),
		// 			array(
		// 				'game_name' => 'Punto Banco',
		// 				'english_name' => 'Punto Banco',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '883045',
		// 				'external_game_id' => '883045',
		// 			),
		// 			array(
		// 				'game_name' => 'Stud Poker 3D',
		// 				'english_name' => 'Stud Poker 3D',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '883049',
		// 				'external_game_id' => '883049',
		// 			),
		// 		),
		// 	),
		// 	array(
		// 		'game_type' => 'Isoftbet Video Poker Game',
		// 		'game_type_lang' => 'isb_video_poker_game',
		// 		'status' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'game_description_list' => array(
		// 			array('english_name' => '100x Play',
		// 				'game_name' => '100x Play',
		// 				'game_code' => '882026',
		// 				'external_game_id' => '882026',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 			),
		// 			array('english_name' => '10x Deuce Wild',
		// 				'game_name' => '10x Deuce Wild',
		// 				'game_code' => '882022',
		// 				'external_game_id' => '882022',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 			),
		// 			array('english_name' => '10x Play',
		// 				'game_name' => '10x Play',
		// 				'game_code' => '882001',
		// 				'external_game_id' => '882001',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 			),
		// 			array('english_name' => '2 Deuce Wild',
		// 				'game_name' => '2 Deuce Wild',
		// 				'game_code' => '882002',
		// 				'external_game_id' => '882002',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 			),
		// 			array('english_name' => '25x Deuces Poker',
		// 				'game_name' => '25x Deuces Poker',
		// 				'game_code' => '882023',
		// 				'external_game_id' => '882023',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 			),
		// 			array('english_name' => '25x Play',
		// 				'game_name' => '25x Play',
		// 				'game_code' => '882003',
		// 				'external_game_id' => '882003',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 			),
		// 			array('english_name' => '3x Deuce Poker',
		// 				'game_name' => '3x Deuce Poker',
		// 				'game_code' => '882021',
		// 				'external_game_id' => '882021',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 			),
		// 			array('english_name' => '3x Double Play',
		// 				'game_name' => '3x Double Play',
		// 				'game_code' => '882004',
		// 				'external_game_id' => '882004',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 			),
		// 			array('english_name' => '3x Joker Play',
		// 				'game_name' => '3x Joker Play',
		// 				'game_code' => '882005',
		// 				'external_game_id' => '882005',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 			),
		// 			array('english_name' => '3x Play', 'game_name' => '3x Play',
		// 				'game_code' => '882006',
		// 				'external_game_id' => '882006',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 			),
		// 			array('english_name' => '4x Deuce Wild',
		// 				'game_name' => '4x Deuce Wild',
		// 				'game_code' => '882034',
		// 				'external_game_id' => '882034',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 			),
		// 			array('english_name' => '4x Tens or Better',
		// 				'game_name' => '4x Tens or Better',
		// 				'game_code' => '882033',
		// 				'external_game_id' => '882033',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 			),
		// 			array('english_name' => '4x Vegas Joker',
		// 				'game_name' => '4x Vegas Joker',
		// 				'game_code' => '882028',
		// 				'external_game_id' => '882028',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 			),
		// 			array('english_name' => '50x Play',
		// 				'game_name' => '50x Play',
		// 				'game_code' => '882020',
		// 				'external_game_id' => '882020',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 			),
		// 			array('english_name' => 'Deuce Wild Progressive',
		// 				'game_name' => 'Deuce Wild Progressive',
		// 				'game_code' => '882032',
		// 				'external_game_id' => '882032',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 			),
		// 			array('english_name' => 'Deuces and Joker Poker',
		// 				'game_name' => 'Deuces and Joker Poker',
		// 				'game_code' => '882027',
		// 				'external_game_id' => '882027',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 			),
		// 			array('english_name' => 'Deuces Wild 4UP',
		// 				'game_name' => 'Deuces Wild 4UP',
		// 				'game_code' => '882039',
		// 				'external_game_id' => '882039',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 			),
		// 			array('english_name' => 'Double Joker',
		// 				'game_name' => 'Double Joker',
		// 				'game_code' => '882019',
		// 				'external_game_id' => '882019',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 			),
		// 			array('english_name' => 'Jacks or Better',
		// 				'game_name' => 'Jacks or Better',
		// 				'game_code' => '882007',
		// 				'external_game_id' => '882007',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 			),
		// 			array('english_name' => 'Joker Multitimes',
		// 				'game_name' => 'Joker Multitimes',
		// 				'game_code' => '882008',
		// 				'external_game_id' => '882008',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 			),
		// 			array('english_name' => 'Joker Poker',
		// 				'game_name' => 'Joker Poker',
		// 				'game_code' => '882009',
		// 				'external_game_id' => '882009',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 			),
		// 			array('english_name' => 'Joker Poker Big Beer',
		// 				'game_name' => 'Joker Poker Big Beer',
		// 				'game_code' => '882015',
		// 				'external_game_id' => '882015',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 			),
		// 			array('english_name' => 'Joker Poker Progressive',
		// 				'game_name' => 'Joker Poker Progressive',
		// 				'game_code' => '882010',
		// 				'external_game_id' => '882010',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 			),
		// 			array('english_name' => 'Joker Poker VIP',
		// 				'game_name' => 'Joker Poker VIP',
		// 				'game_code' => '882030',
		// 				'external_game_id' => '882030',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 			),
		// 			array('english_name' => 'Joker Vegas 4UP',
		// 				'game_name' => 'Joker Vegas 4UP',
		// 				'game_code' => '882029',
		// 				'external_game_id' => '882029',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 			),
		// 			array('english_name' => 'Joker Wheel Bonus',
		// 				'game_name' => 'Joker Wheel Bonus',
		// 				'game_code' => '882012',
		// 				'external_game_id' => '882012',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 			),
		// 			array('english_name' => 'Joker Wild Poker',
		// 				'game_name' => 'Joker Wild Poker',
		// 				'game_code' => '882013',
		// 				'external_game_id' => '882013',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 			),
		// 			array('english_name' => 'Poker Bowling Strike',
		// 				'game_name' => 'Poker Bowling Strike',
		// 				'game_code' => '882014',
		// 				'external_game_id' => '882014',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 			),
		// 			array('english_name' => 'Poker Pursuit',
		// 				'game_name' => 'Poker Pursuit',
		// 				'game_code' => '882011',
		// 				'external_game_id' => '882011',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 			),
		// 			array('english_name' => 'Tens or Better Poker',
		// 				'game_name' => 'Tens or Better Poker',
		// 				'game_code' => '882018',
		// 				'external_game_id' => '882018',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 			),
		// 			array('english_name' => 'Tens or Better Progressive',
		// 				'game_name' => 'Tens or Better Progressive',
		// 				'game_code' => '882031',
		// 				'external_game_id' => '882031',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 			),
		// 			array('english_name' => 'Texas Hold\'em Joker Poker',
		// 				'game_name' => 'Texas Hold\'em Joker Poker',
		// 				'game_code' => '882016',
		// 				'external_game_id' => '882016',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 			),
		// 			array('english_name' => 'Vegas Joker Poker',
		// 				'game_name' => 'Vegas Joker Poker',
		// 				'game_code' => '882017',
		// 				'external_game_id' => '882017',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 			),
		// 		),
		// 	),
		// 	array(
		// 		'game_type' => 'Isoftbet Slots Html5 Game',
		// 		'game_type_lang' => 'isb_slots_html5_game',
		// 		'status' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'game_description_list' => array(
		// 			array(
		// 				'game_name' => 'Skulls of Legend',
		// 				'english_name' => 'Skulls of Legend',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => NULL,
		// 				'external_game_id' => NULL,
		// 			),
		// 			array(
		// 				'game_name' => 'Cloud Tales',
		// 				'english_name' => 'Cloud Tales',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '896551',
		// 				'external_game_id' => '896551',
		// 			),
		// 			array(
		// 				'game_name' => 'MegaBoy',
		// 				'english_name' => 'MegaBoy',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '896550',
		// 				'external_game_id' => '896550',
		// 			),
		// 			array(
		// 				'game_name' => 'Alice Adventure',
		// 				'english_name' => 'Alice Adventure',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '906504',
		// 				'external_game_id' => '906504',
		// 			),
		// 			array(
		// 				'game_name' => 'Ambiance',
		// 				'english_name' => 'Ambiance',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '896527',
		// 				'external_game_id' => '896527',
		// 			),
		// 			array(
		// 				'game_name' => 'Astro Magic',
		// 				'english_name' => 'Astro Magic',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '906544',
		// 				'external_game_id' => '906544',
		// 			),
		// 			array(
		// 				'game_name' => 'Best things in life',
		// 				'english_name' => 'Best things in life',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '896528',
		// 				'external_game_id' => '896528',
		// 			),
		// 			array(
		// 				'game_name' => 'Bewitched',
		// 				'english_name' => 'Bewitched',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '906517',
		// 				'external_game_id' => '906517',
		// 			),
		// 			array(
		// 				'game_name' => 'Dolphin\'s Island',
		// 				'english_name' => 'Dolphin\'s Island',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '896542',
		// 				'external_game_id' => '896542',
		// 			),
		// 			array(
		// 				'game_name' => 'Happy Birds',
		// 				'english_name' => 'Happy Birds',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '906525',
		// 				'external_game_id' => '906525',
		// 			),
		// 			array(
		// 				'game_name' => 'Illusions 2',
		// 				'english_name' => 'Illusions 2',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '906505',
		// 				'external_game_id' => '906505',
		// 			),
		// 			array(
		// 				'game_name' => 'Lucky Leprechaun',
		// 				'english_name' => 'Lucky Leprechaun',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '896557',
		// 				'external_game_id' => '896557',
		// 			),
		// 			array(
		// 				'game_name' => 'Luxury Rome',
		// 				'english_name' => 'Luxury Rome',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '996548',
		// 				'external_game_id' => '996548',
		// 			),
		// 			array(
		// 				'game_name' => 'Mona Lisa Jewels',
		// 				'english_name' => 'Mona Lisa Jewels',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '906520',
		// 				'external_game_id' => '906520',
		// 			),
		// 			array(
		// 				'game_name' => 'Musketeer Slot',
		// 				'english_name' => 'Musketeer Slot',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '896543',
		// 				'external_game_id' => '896543',
		// 			),
		// 			array(
		// 				'game_name' => 'Neon Reels',
		// 				'english_name' => 'Neon Reels',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '896552',
		// 				'external_game_id' => '896552',
		// 			),
		// 			array(
		// 				'game_name' => 'Ninja Chef',
		// 				'english_name' => 'Ninja Chef',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '906503',
		// 				'external_game_id' => '906503',
		// 			),
		// 			array(
		// 				'game_name' => 'Red Dragon Wild',
		// 				'english_name' => 'Red Dragon Wild',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '906514',
		// 				'external_game_id' => '906514',
		// 			),
		// 			array(
		// 				'game_name' => 'Royal Cash',
		// 				'english_name' => 'Royal Cash',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '896530',
		// 				'external_game_id' => '896530',
		// 			),
		// 			array(
		// 				'game_name' => 'Scrolls of Ra HD',
		// 				'english_name' => 'Scrolls of Ra HD',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '906536',
		// 				'external_game_id' => '906536',
		// 			),
		// 			array(
		// 				'game_name' => 'Shaolin Spin',
		// 				'english_name' => 'Shaolin Spin',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '896539',
		// 				'external_game_id' => '896539',
		// 			),
		// 			array(
		// 				'game_name' => 'Spooky Family',
		// 				'english_name' => 'Spooky Family',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '896526',
		// 				'external_game_id' => '896526',
		// 			),
		// 			array(
		// 				'game_name' => 'The Best Witch',
		// 				'english_name' => 'The Best Witch',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '896538',
		// 				'external_game_id' => '896538',
		// 			),
		// 			array(
		// 				'game_name' => 'Wisps',
		// 				'english_name' => 'Wisps',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '896547',
		// 				'external_game_id' => '896547',
		// 			),
		// 		),
		// 	),
		// 	array(
		// 		'game_type' => 'Isoftbet Mechanical Slots Html5 Game',
		// 		'game_type_lang' => 'isb_mechanical_slots_html5_game',
		// 		'status' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'game_description_list' => array(
		// 			array(
		// 				'game_name' => 'Super Multitimes Progressive HD',
		// 				'english_name' => 'Super Multitimes Progressive HD',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '906515',
		// 				'external_game_id' => '906515',
		// 			),
		// 			array(
		// 				'game_name' => 'Spin or Reel HD',
		// 				'english_name' => 'Spin or Reel HD',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '896553',
		// 				'external_game_id' => '896553',
		// 			),
		// 			array(
		// 				'game_name' => 'Absolute Super Reels',
		// 				'english_name' => 'Absolute Super Reels',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '906500',
		// 				'external_game_id' => '906500',
		// 			),
		// 			array(
		// 				'game_name' => 'Diamond Wild',
		// 				'english_name' => 'Diamond Wild',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '906508',
		// 				'external_game_id' => '906508',
		// 			),
		// 			array(
		// 				'game_name' => 'Lucky Clover',
		// 				'english_name' => 'Lucky Clover',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '896556',
		// 				'external_game_id' => '896556',
		// 			),
		// 			array(
		// 				'game_name' => 'Million Cents',
		// 				'english_name' => 'Million Cents',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '906512',
		// 				'external_game_id' => '906512',
		// 			),
		// 			array(
		// 				'game_name' => 'Super Fast Hot Hot',
		// 				'english_name' => 'Super Fast Hot Hot',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '906516',
		// 				'external_game_id' => '906516',
		// 			),
		// 			array(
		// 				'game_name' => 'Super Lucky Reels',
		// 				'english_name' => 'Super Lucky Reels',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '906501',
		// 				'external_game_id' => '906501',
		// 			),
		// 			array(
		// 				'game_name' => 'Super Multitimes Progressive',
		// 				'english_name' => 'Super Multitimes Progressive',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '906515',
		// 				'external_game_id' => '906515',
		// 			),
		// 			array(
		// 				'game_name' => 'Ultimate Super Reels',
		// 				'english_name' => 'Ultimate Super Reels',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '906513',
		// 				'external_game_id' => '906513',
		// 			),
		// 		),
		// 	),
		// 	array(
		// 		'game_type' => 'Isoftbet Branded Slots Html5 Game',
		// 		'game_type_lang' => 'isb_branded_slots_html5_game',
		// 		'status' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'game_description_list' => array(
		// 			array(
		// 				'game_name' => 'Platoon Wild™Progressive',
		// 				'english_name' => 'Platoon Wild™Progressive',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '906555',
		// 				'external_game_id' => '906555',
		// 			),
		// 			array(
		// 				'game_name' => 'Platoon Wild™',
		// 				'english_name' => 'Platoon Wild™',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '906559',
		// 				'external_game_id' => '906559',
		// 			),
		// 			array(
		// 				'game_name' => '24™',
		// 				'english_name' => '24™',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '906546',
		// 				'external_game_id' => '906546',
		// 			),
		// 			array(
		// 				'game_name' => 'Basic Instinct™',
		// 				'english_name' => 'Basic Instinct™',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '906507',
		// 				'external_game_id' => '906507',
		// 			),
		// 			array(
		// 				'game_name' => 'Beverly Hills 90210™',
		// 				'english_name' => 'Beverly Hills 90210™',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '906523',
		// 				'external_game_id' => '906523',
		// 			),
		// 			array(
		// 				'game_name' => 'Hansel & Gretel: Witch Hunters™',
		// 				'english_name' => 'Hansel & Gretel: Witch Hunters™',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '906545',
		// 				'external_game_id' => '906545',
		// 			),
		// 			array(
		// 				'game_name' => 'Heavy Metal: Warriors™',
		// 				'english_name' => 'Heavy Metal: Warriors™',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '896529',
		// 				'external_game_id' => '896529',
		// 			),
		// 			array(
		// 				'game_name' => 'Jackpot Rango™',
		// 				'english_name' => 'Jackpot Rango™',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '906502',
		// 				'external_game_id' => '906502',
		// 			),
		// 			array(
		// 				'game_name' => 'Kobushi™',
		// 				'english_name' => 'Kobushi™',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '906509',
		// 				'external_game_id' => '906509',
		// 			),
		// 			array(
		// 				'game_name' => 'Nacho Libre™',
		// 				'english_name' => 'Nacho Libre™',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '896535',
		// 				'external_game_id' => '896535',
		// 			),
		// 			array(
		// 				'game_name' => 'Platoon™',
		// 				'english_name' => 'Platoon™',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '906510',
		// 				'external_game_id' => '906510',
		// 			),
		// 			array(
		// 				'game_name' => 'Rambo™',
		// 				'english_name' => 'Rambo™',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '896511',
		// 				'external_game_id' => '896511',
		// 			),
		// 			array(
		// 				'game_name' => 'The Love Guru™',
		// 				'english_name' => 'The Love Guru™',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '896531',
		// 				'external_game_id' => '896531',
		// 			),
		// 			array(
		// 				'game_name' => 'The Warriors™',
		// 				'english_name' => 'The Warriors™',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '886537',
		// 				'external_game_id' => '886537',
		// 			),
		// 		),
		// 	),
		// 	array(
		// 		'game_type' => 'Isoftbet Table Html5 Game',
		// 		'game_type_lang' => 'isb_table_html5_game',
		// 		'status' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'game_description_list' => array(
		// 			array(
		// 				'game_name' => 'European Roulette',
		// 				'english_name' => 'European Roulette',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '896521',
		// 				'external_game_id' => '896521',
		// 			),
		// 			array(
		// 				'game_name' => 'Blackjack',
		// 				'english_name' => 'Blackjack',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '896522',
		// 				'external_game_id' => '896522',
		// 			),
		// 		),
		// 	),
		// 	array(
		// 		'game_type' => 'Isoftbet Video Poker Html5 Game',
		// 		'game_type_lang' => 'isb_video_poker_html5_game',
		// 		'status' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_TRUE,
		// 		'game_description_list' => array(
		// 			array(
		// 				'game_name' => 'Joker Poker',
		// 				'english_name' => 'Joker Poker',
		// 				'flash_enabled' => self::FLAG_FALSE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'html_five_enabled' => self::FLAG_TRUE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => '896521',
		// 				'external_game_id' => '896521',
		// 			),
		// 		),
		// 	),
		// 	array(
		// 		'game_type' => 'unknown',
		// 		'game_type_lang' => 'isb.unknown',
		// 		'status' => self::FLAG_TRUE,
		// 		'flag_show_in_site' => self::FLAG_FALSE,
		// 		'game_description_list' => array(
		// 			array(
		// 				'game_name' => 'isb.unknown',
		// 				'english_name' => 'isb.unknown',
		// 				'html_five_enabled' => self::FLAG_FALSE,
		// 				'flash_enabled' => self::FLAG_TRUE,
		// 				'mobile_enabled' => self::FLAG_FALSE,
		// 				'flag_show_in_site' => self::FLAG_TRUE,
		// 				'game_code' => 'unknown',
		// 				'external_game_id' => 'unknown',
		// 			),
		// 		),
		// 	),
		// );

		// $game_description_list = array();
		// foreach ($data as $game_type) {

		// 	$this->db->insert('game_type', array(
		// 		'game_platform_id' => ISB_API,
		// 		'game_type' => $game_type['game_type'],
		// 		'game_type_lang' => $game_type['game_type_lang'],
		// 		'status' => $game_type['status'],
		// 		'flag_show_in_site' => $game_type['flag_show_in_site'],
		// 	));

		// 	$game_type_id = $this->db->insert_id();
		// 	foreach ($game_type['game_description_list'] as $game_description) {
		// 		$game_description_list[] = array_merge(array(
		// 			'game_platform_id' => ISB_API,
		// 			'game_type_id' => $game_type_id,
		// 		), $game_description);
		// 	}

		// }

		// $this->db->insert_batch('game_description', $game_description_list);
		// $this->db->trans_complete();
	}

	public function down() {
		// $this->db->trans_start();
		// $this->db->delete('game_type', array('game_platform_id' => ISB_API));
		// $this->db->delete('game_description', array('game_platform_id' => ISB_API));
		// $this->db->trans_complete();
	}
}