<?php

defined('BASEPATH') OR exit('No direct script access allowed');

class Migration_add_oneworks_to_game_type_and_game_description_201607270143 extends CI_Migration {

	const FLAG_TRUE = 1;
	const FLAG_FALSE = 0;

	public function up() {
		$this->db->trans_start();
		$data = array(
			array(
				'game_type' => 'Oneworks Sportsbook Games',
				'game_type_lang' => 'oneworks_sportsbook_games',
				'status' => self::FLAG_TRUE,
				'flag_show_in_site' => self::FLAG_TRUE,
				'game_description_list' => array(
					array(
						'game_name' => 'Soccer',
						'english_name' => 'Soccer',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '1',
						'external_game_id' => '1',
					),
					array(
						'game_name' => 'Basketball',
						'english_name' => 'Basketball',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '2',
						'external_game_id' => '2',
					),
					array(
						'game_name' => 'Football',
						'english_name' => 'Football',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '3',
						'external_game_id' => '3',
					),
					array(
						'game_name' => 'Ice Hockey',
						'english_name' => 'Ice Hockey',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '4',
						'external_game_id' => '4',
					),
					array(
						'game_name' => 'Tennis',
						'english_name' => 'Tennis',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '5',
						'external_game_id' => '5',
					),
					array(
						'game_name' => 'Volleyball',
						'english_name' => 'Volleyball',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '6',
						'external_game_id' => '6',
					),
					array(
						'game_name' => 'Billiards',
						'english_name' => 'Billiards',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '7',
						'external_game_id' => '7',
					),
					array(
						'game_name' => 'Baseball',
						'english_name' => 'Baseball',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '8',
						'external_game_id' => '8',
					),
					array(
						'game_name' => 'Badminton',
						'english_name' => 'Badminton',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '9',
						'external_game_id' => '9',
					),
					array(
						'game_name' => 'Golf',
						'english_name' => 'Golf',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '10',
						'external_game_id' => '10',
					), array(
						'game_name' => 'Motorsports',
						'english_name' => 'Motorsports',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '11',
						'external_game_id' => '11',
					),
					array(
						'game_name' => 'Swimming',
						'english_name' => 'Swimming',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '12',
						'external_game_id' => '12',
					),
					array(
						'game_name' => 'Politics',
						'english_name' => 'Politics',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '13',
						'external_game_id' => '13',
					),
					array(
						'game_name' => 'Water Polo',
						'english_name' => 'Water Polo',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '14',
						'external_game_id' => '14',
					),
					array(
						'game_name' => 'Diving',
						'english_name' => 'Diving',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '15',
						'external_game_id' => '15',
					),
					array(
						'game_name' => 'Boxing',
						'english_name' => 'Boxing',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '16',
						'external_game_id' => '16',
					),
					array(
						'game_name' => 'Archery',
						'english_name' => 'Archery',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '17',
						'external_game_id' => '17',
					),
					array(
						'game_name' => 'Table Tennis',
						'english_name' => 'Table Tennis',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '18',
						'external_game_id' => '18',
					),
					array(
						'game_name' => 'Weightlifting',
						'english_name' => 'Weightlifting',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '19',
						'external_game_id' => '19',
					),
					array(
						'game_name' => 'Canoeing',
						'english_name' => 'Canoeing',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '20',
						'external_game_id' => '20',
					),
					array(
						'game_name' => 'Gymnastics',
						'english_name' => 'Gymnastics',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '21',
						'external_game_id' => '21',
					),
					array(
						'game_name' => 'Athletics',
						'english_name' => 'Athletics',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '22',
						'external_game_id' => '22',
					),
					array(
						'game_name' => 'Equestrian',
						'english_name' => 'Equestrian',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '23',
						'external_game_id' => '23',
					),
					array(
						'game_name' => 'Handball',
						'english_name' => 'Handball',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '24',
						'external_game_id' => '24',
					),
					array(
						'game_name' => 'Darts',
						'english_name' => 'Darts',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '25',
						'external_game_id' => '25',
					),
					array(
						'game_name' => 'Rugby',
						'english_name' => 'Rugby',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '26',
						'external_game_id' => '26',
					),
					array(
						'game_name' => 'Field Hockey',
						'english_name' => 'Field Hockey',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '28',
						'external_game_id' => '28',
					), array(
						'game_name' => 'Winter Sport',
						'english_name' => 'Winter Sport',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '29',
						'external_game_id' => '29',
					),
					array(
						'game_name' => 'Squash',
						'english_name' => 'Squash',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '30',
						'external_game_id' => '30',
					),
					array(
						'game_name' => 'Entertainment',
						'english_name' => 'Entertainment',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '31',
						'external_game_id' => '31',
					),
					array(
						'game_name' => 'Net Ball',
						'english_name' => 'Net Ball',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '32',
						'external_game_id' => '32',
					),
					array(
						'game_name' => 'Cycling',
						'english_name' => 'Cycling',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '33',
						'external_game_id' => '33',
					),
					array(
						'game_name' => 'Fencing',
						'english_name' => 'Fencing',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '34',
						'external_game_id' => '34',
					),
					array(
						'game_name' => 'Judo',
						'english_name' => 'Judo',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '35',
						'external_game_id' => '35',
					),
					array(
						'game_name' => 'M. Pentathlon',
						'english_name' => 'M. Pentathlon',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '36',
						'external_game_id' => '36',
					),
					array(
						'game_name' => 'Rowing',
						'english_name' => 'Rowing',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '37',
						'external_game_id' => '37',
					),
					array(
						'game_name' => 'Sailing',
						'english_name' => 'Sailing',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '38',
						'external_game_id' => '38',
					),
					array(
						'game_name' => 'Shooting',
						'english_name' => 'Shooting',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '39',
						'external_game_id' => '39',
					),
					array(
						'game_name' => 'Taekwondo',
						'english_name' => 'Taekwondo',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '40',
						'external_game_id' => '40',
					),
					array(
						'game_name' => 'Triathlon',
						'english_name' => 'Triathlon',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '41',
						'external_game_id' => '41',
					),
					array(
						'game_name' => 'Wrestling',
						'english_name' => 'Wrestling',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '42',
						'external_game_id' => '42',
					),
					array(
						'game_name' => 'E Sports',
						'english_name' => 'E Sports',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '43',
						'external_game_id' => '43',
					),
					array(
						'game_name' => 'Muay Thai',
						'english_name' => 'Muay Thai',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '44',
						'external_game_id' => '44',
					),
					array(
						'game_name' => 'Cricket',
						'english_name' => 'Cricket',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '50',
						'external_game_id' => '50',
					),
					array(
						'game_name' => 'Other Sports',
						'english_name' => 'Other Sports',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '99',
						'external_game_id' => '99',
					),
				),
			),
			array(
				'game_type' => 'Oneworks Number Game',
				'game_type_lang' => 'oneworks_number_game',
				'status' => self::FLAG_TRUE,
				'flag_show_in_site' => self::FLAG_TRUE,
				'game_description_list' => array(
					array(
						'game_name' => 'Number Game',
						'english_name' => 'Number Game',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '161',
						'external_game_id' => '161',
					),
				),
			),
			array(
				'game_type' => 'Oneworks Virtual Sport Game',
				'game_type_lang' => 'oneworks_virtual_sport_game',
				'status' => self::FLAG_TRUE,
				'flag_show_in_site' => self::FLAG_TRUE,
				'game_description_list' => array(
					array(
						'game_name' => 'Virtual Soccer',
						'english_name' => 'Virtual Soccer',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '180',
						'external_game_id' => '180',
					),
					array(
						'game_name' => 'Virtual Horse Racing',
						'english_name' => 'Virtual Horse Racing',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '181',
						'external_game_id' => '181',
					),
					array(
						'game_name' => 'Virtual Greyhound',
						'english_name' => 'Virtual Greyhound',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '182',
						'external_game_id' => '182',
					),
					array(
						'game_name' => 'Virtual Speedway',
						'english_name' => 'Virtual Speedway',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '183',
						'external_game_id' => '183',
					),
					array(
						'game_name' => 'Virtual F1',
						'english_name' => 'Virtual F1',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '184',
						'external_game_id' => '184',
					),
					array(
						'game_name' => 'Virtual Cycling',
						'english_name' => 'Virtual Cycling',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '185',
						'external_game_id' => '185',
					),
				),
			),
			array(
				'game_type' => 'Oneworks Mobile Game',
				'game_type_lang' => 'oneworks_mobile_game',
				'status' => self::FLAG_TRUE,
				'flag_show_in_site' => self::FLAG_TRUE,
				'game_description_list' => array(
					array(
						'game_name' => 'Mobile',
						'english_name' => 'Mobile',
						'flash_enabled' => self::FLAG_TRUE,
						'html_five_enabled' => self::FLAG_FALSE,
						'mobile_enabled' => self::FLAG_FALSE,
						'game_code' => '210',
						'external_game_id' => '210',
					),
				),
			),
		);

		$game_description_list = array();
		foreach ($data as $game_type) {

			$this->db->insert('game_type', array(
				'game_platform_id' => ONEWORKS_API,
				'game_type' => $game_type['game_type'],
				'game_type_lang' => $game_type['game_type_lang'],
				'status' => $game_type['status'],
				'flag_show_in_site' => $game_type['flag_show_in_site'],
			));

			$game_type_id = $this->db->insert_id();
			foreach ($game_type['game_description_list'] as $game_description) {
				$game_description_list[] = array_merge(array(
					'game_platform_id' => ONEWORKS_API,
					'game_type_id' => $game_type_id,
				), $game_description);
			}

		}

		$this->db->insert_batch('game_description', $game_description_list);
		$this->db->trans_complete();
	}

	public function down() {
		$this->db->trans_start();
		$this->db->delete('game_type', array('game_platform_id' => ONEWORKS_API));
		$this->db->delete('game_description', array('game_platform_id' => ONEWORKS_API));
		$this->db->trans_complete();
	}
}