<?php

defined('BASEPATH') OR exit('No direct script access allowed');

class Migration_update_isb_game_externa_game_id_201609080431 extends CI_Migration {

	const FLAG_TRUE = 1;
	const FLAG_FALSE = 0;

	public function up() {
		$this->db->trans_start();
		$this->db->query("UPDATE game_description SET external_game_id = '1597' where game_code = '881597'");
		$this->db->query("UPDATE game_description SET external_game_id = '1589' where game_code = '881589'");
		$this->db->query("UPDATE game_description SET external_game_id = '1525' where game_code = '881525'");
		$this->db->query("UPDATE game_description SET external_game_id = '1565' where game_code = '881565'");
		$this->db->query("UPDATE game_description SET external_game_id = '1578' where game_code = '881578'");
		$this->db->query("UPDATE game_description SET external_game_id = '1591' where game_code = '881591'");
		$this->db->query("UPDATE game_description SET external_game_id = '1573' where game_code = '881573'");
		$this->db->query("UPDATE game_description SET external_game_id = '1508' where game_code = '881508'");
		$this->db->query("UPDATE game_description SET external_game_id = '1270' where game_code = '881270'");
		$this->db->query("UPDATE game_description SET external_game_id = '1586' where game_code = '881586'");
		$this->db->query("UPDATE game_description SET external_game_id = '1527' where game_code = '881527'");
		$this->db->query("UPDATE game_description SET external_game_id = '1556' where game_code = '881556'");
		$this->db->query("UPDATE game_description SET external_game_id = '1572' where game_code = '881572'");
		$this->db->query("UPDATE game_description SET external_game_id = '1526' where game_code = '881526'");
		$this->db->query("UPDATE game_description SET external_game_id = '1537' where game_code = '881537'");
		$this->db->query("UPDATE game_description SET external_game_id = '1595' where game_code = '881595'");
		$this->db->query("UPDATE game_description SET external_game_id = '1511' where game_code = '881511'");
		$this->db->query("UPDATE game_description SET external_game_id = '1250' where game_code = '881250'");
		$this->db->query("UPDATE game_description SET external_game_id = '1592' where game_code = '881592'");
		$this->db->query("UPDATE game_description SET external_game_id = '1516' where game_code = '881516'");
		$this->db->query("UPDATE game_description SET external_game_id = '1280' where game_code = '881280'");
		$this->db->query("UPDATE game_description SET external_game_id = '1559' where game_code = '881559'");
		$this->db->query("UPDATE game_description SET external_game_id = '1550' where game_code = '881550'");
		$this->db->query("UPDATE game_description SET external_game_id = '1549' where game_code = '881549'");
		$this->db->query("UPDATE game_description SET external_game_id = '1585' where game_code = '881585'");
		$this->db->query("UPDATE game_description SET external_game_id = '1593' where game_code = '881593'");
		$this->db->query("UPDATE game_description SET external_game_id = '1521' where game_code = '881521'");
		$this->db->query("UPDATE game_description SET external_game_id = '1581' where game_code = '881581'");
		$this->db->query("UPDATE game_description SET external_game_id = '1538' where game_code = '881538'");
		$this->db->query("UPDATE game_description SET external_game_id = '1557' where game_code = '881557'");
		$this->db->query("UPDATE game_description SET external_game_id = '1588' where game_code = '881588'");
		$this->db->query("UPDATE game_description SET external_game_id = '1563' where game_code = '881563'");
		$this->db->query("UPDATE game_description SET external_game_id = '1501' where game_code = '881501'");
		$this->db->query("UPDATE game_description SET external_game_id = '1539' where game_code = '881539'");
		$this->db->query("UPDATE game_description SET external_game_id = '1500' where game_code = '881500'");
		$this->db->query("UPDATE game_description SET external_game_id = '1507' where game_code = '881507'");
		$this->db->query("UPDATE game_description SET external_game_id = '1505' where game_code = '881505'");
		$this->db->query("UPDATE game_description SET external_game_id = '1547' where game_code = '881547'");
		$this->db->query("UPDATE game_description SET external_game_id = '1504' where game_code = '881504'");
		$this->db->query("UPDATE game_description SET external_game_id = '1503' where game_code = '881503'");
		$this->db->query("UPDATE game_description SET external_game_id = '1580' where game_code = '881580'");
		$this->db->query("UPDATE game_description SET external_game_id = '1506' where game_code = '881506'");
		$this->db->query("UPDATE game_description SET external_game_id = '1535' where game_code = '881535'");
		$this->db->query("UPDATE game_description SET external_game_id = '1501' where game_code = '881501'");
		$this->db->query("UPDATE game_description SET external_game_id = '1502' where game_code = '881502'");
		$this->db->query("UPDATE game_description SET external_game_id = '1536' where game_code = '881536'");
		$this->db->query("UPDATE game_description SET external_game_id = '1605' where game_code = '881605'");
		$this->db->query("UPDATE game_description SET external_game_id = '1606' where game_code = '881606'");
		$this->db->query("UPDATE game_description SET external_game_id = '1594' where game_code = '881594'");
		$this->db->query("UPDATE game_description SET external_game_id = '1513' where game_code = '881513'");
		$this->db->query("UPDATE game_description SET external_game_id = '1570' where game_code = '881570'");
		$this->db->query("UPDATE game_description SET external_game_id = '1590' where game_code = '881590'");
		$this->db->query("UPDATE game_description SET external_game_id = '1582' where game_code = '881582'");
		$this->db->query("UPDATE game_description SET external_game_id = '1510' where game_code = '881510'");
		$this->db->query("UPDATE game_description SET external_game_id = '1517' where game_code = '881517'");
		$this->db->query("UPDATE game_description SET external_game_id = '1576' where game_code = '881576'");
		$this->db->query("UPDATE game_description SET external_game_id = '1575' where game_code = '881575'");
		$this->db->query("UPDATE game_description SET external_game_id = '1568' where game_code = '881568'");
		$this->db->query("UPDATE game_description SET external_game_id = '1512' where game_code = '881512'");
		$this->db->query("UPDATE game_description SET external_game_id = '1577' where game_code = '881577'");
		$this->db->query("UPDATE game_description SET external_game_id = '3014' where game_code = '883014'");
		$this->db->query("UPDATE game_description SET external_game_id = '3044' where game_code = '883044'");
		$this->db->query("UPDATE game_description SET external_game_id = '3020' where game_code = '883020'");
		$this->db->query("UPDATE game_description SET external_game_id = '3017' where game_code = '883017'");
		$this->db->query("UPDATE game_description SET external_game_id = '3021' where game_code = '883021'");
		$this->db->query("UPDATE game_description SET external_game_id = '3012' where game_code = '883012'");
		$this->db->query("UPDATE game_description SET external_game_id = '3032' where game_code = '883032'");
		$this->db->query("UPDATE game_description SET external_game_id = '3028' where game_code = '883028'");
		$this->db->query("UPDATE game_description SET external_game_id = '3027' where game_code = '883027'");
		$this->db->query("UPDATE game_description SET external_game_id = '3007' where game_code = '883007'");
		$this->db->query("UPDATE game_description SET external_game_id = '3023' where game_code = '883023'");
		$this->db->query("UPDATE game_description SET external_game_id = '3033' where game_code = '883033'");
		$this->db->query("UPDATE game_description SET external_game_id = '3048' where game_code = '883048'");
		$this->db->query("UPDATE game_description SET external_game_id = '3016' where game_code = '883016'");
		$this->db->query("UPDATE game_description SET external_game_id = '3037' where game_code = '883037'");
		$this->db->query("UPDATE game_description SET external_game_id = '3034' where game_code = '883034'");
		$this->db->query("UPDATE game_description SET external_game_id = '3039' where game_code = '883039'");
		$this->db->query("UPDATE game_description SET external_game_id = '3029' where game_code = '883029'");
		$this->db->query("UPDATE game_description SET external_game_id = '3006' where game_code = '883006'");
		$this->db->query("UPDATE game_description SET external_game_id = '3008' where game_code = '883008'");
		$this->db->query("UPDATE game_description SET external_game_id = '3011' where game_code = '883011'");
		$this->db->query("UPDATE game_description SET external_game_id = '3024' where game_code = '883024'");
		$this->db->query("UPDATE game_description SET external_game_id = '3038' where game_code = '883038'");
		$this->db->query("UPDATE game_description SET external_game_id = '3045' where game_code = '883045'");
		$this->db->query("UPDATE game_description SET external_game_id = '3049' where game_code = '883049'");
		$this->db->query("UPDATE game_description SET external_game_id = '2026' where game_code = '882026'");
		$this->db->query("UPDATE game_description SET external_game_id = '2022' where game_code = '882022'");
		$this->db->query("UPDATE game_description SET external_game_id = '2001' where game_code = '882001'");
		$this->db->query("UPDATE game_description SET external_game_id = '2002' where game_code = '882002'");
		$this->db->query("UPDATE game_description SET external_game_id = '2023' where game_code = '882023'");
		$this->db->query("UPDATE game_description SET external_game_id = '2003' where game_code = '882003'");
		$this->db->query("UPDATE game_description SET external_game_id = '2021' where game_code = '882021'");
		$this->db->query("UPDATE game_description SET external_game_id = '2004' where game_code = '882004'");
		$this->db->query("UPDATE game_description SET external_game_id = '2005' where game_code = '882005'");
		$this->db->query("UPDATE game_description SET external_game_id = '2006' where game_code = '882006'");
		$this->db->query("UPDATE game_description SET external_game_id = '2034' where game_code = '882034'");
		$this->db->query("UPDATE game_description SET external_game_id = '2033' where game_code = '882033'");
		$this->db->query("UPDATE game_description SET external_game_id = '2028' where game_code = '882028'");
		$this->db->query("UPDATE game_description SET external_game_id = '2020' where game_code = '882020'");
		$this->db->query("UPDATE game_description SET external_game_id = '2032' where game_code = '882032'");
		$this->db->query("UPDATE game_description SET external_game_id = '2027' where game_code = '882027'");
		$this->db->query("UPDATE game_description SET external_game_id = '2039' where game_code = '882039'");
		$this->db->query("UPDATE game_description SET external_game_id = '2019' where game_code = '882019'");
		$this->db->query("UPDATE game_description SET external_game_id = '2007' where game_code = '882007'");
		$this->db->query("UPDATE game_description SET external_game_id = '2008' where game_code = '882008'");
		$this->db->query("UPDATE game_description SET external_game_id = '2009' where game_code = '882009'");
		$this->db->query("UPDATE game_description SET external_game_id = '2015' where game_code = '882015'");
		$this->db->query("UPDATE game_description SET external_game_id = '2010' where game_code = '882010'");
		$this->db->query("UPDATE game_description SET external_game_id = '2030' where game_code = '882030'");
		$this->db->query("UPDATE game_description SET external_game_id = '2029' where game_code = '882029'");
		$this->db->query("UPDATE game_description SET external_game_id = '2012' where game_code = '882012'");
		$this->db->query("UPDATE game_description SET external_game_id = '2013' where game_code = '882013'");
		$this->db->query("UPDATE game_description SET external_game_id = '2014' where game_code = '882014'");
		$this->db->query("UPDATE game_description SET external_game_id = '2011' where game_code = '882011'");
		$this->db->query("UPDATE game_description SET external_game_id = '2018' where game_code = '882018'");
		$this->db->query("UPDATE game_description SET external_game_id = '2031' where game_code = '882031'");
		$this->db->query("UPDATE game_description SET external_game_id = '2016' where game_code = '882016'");
		$this->db->query("UPDATE game_description SET external_game_id = '2017' where game_code = '882017'");
		$this->db->query("UPDATE game_description SET external_game_id = '6551' where game_code = '896551'");
		$this->db->query("UPDATE game_description SET external_game_id = '6550' where game_code = '896550'");
		$this->db->query("UPDATE game_description SET external_game_id = '6504' where game_code = '906504'");
		$this->db->query("UPDATE game_description SET external_game_id = '6527' where game_code = '896527'");
		$this->db->query("UPDATE game_description SET external_game_id = '6544' where game_code = '906544'");
		$this->db->query("UPDATE game_description SET external_game_id = '6528' where game_code = '896528'");
		$this->db->query("UPDATE game_description SET external_game_id = '6517' where game_code = '906517'");
		$this->db->query("UPDATE game_description SET external_game_id = '6542' where game_code = '896542'");
		$this->db->query("UPDATE game_description SET external_game_id = '6525' where game_code = '906525'");
		$this->db->query("UPDATE game_description SET external_game_id = '6505' where game_code = '906505'");
		$this->db->query("UPDATE game_description SET external_game_id = '6557' where game_code = '896557'");
		$this->db->query("UPDATE game_description SET external_game_id = '6548' where game_code = '996548'");
		$this->db->query("UPDATE game_description SET external_game_id = '6520' where game_code = '906520'");
		$this->db->query("UPDATE game_description SET external_game_id = '6543' where game_code = '896543'");
		$this->db->query("UPDATE game_description SET external_game_id = '6552' where game_code = '896552'");
		$this->db->query("UPDATE game_description SET external_game_id = '6503' where game_code = '906503'");
		$this->db->query("UPDATE game_description SET external_game_id = '6514' where game_code = '906514'");
		$this->db->query("UPDATE game_description SET external_game_id = '6530' where game_code = '896530'");
		$this->db->query("UPDATE game_description SET external_game_id = '6536' where game_code = '906536'");
		$this->db->query("UPDATE game_description SET external_game_id = '6539' where game_code = '896539'");
		$this->db->query("UPDATE game_description SET external_game_id = '6526' where game_code = '896526'");
		$this->db->query("UPDATE game_description SET external_game_id = '6538' where game_code = '896538'");
		$this->db->query("UPDATE game_description SET external_game_id = '6547' where game_code = '896547'");
		$this->db->query("UPDATE game_description SET external_game_id = '6515' where game_code = '906515'");
		$this->db->query("UPDATE game_description SET external_game_id = '6553' where game_code = '896553'");
		$this->db->query("UPDATE game_description SET external_game_id = '6500' where game_code = '906500'");
		$this->db->query("UPDATE game_description SET external_game_id = '6508' where game_code = '906508'");
		$this->db->query("UPDATE game_description SET external_game_id = '6556' where game_code = '896556'");
		$this->db->query("UPDATE game_description SET external_game_id = '6512' where game_code = '906512'");
		$this->db->query("UPDATE game_description SET external_game_id = '6516' where game_code = '906516'");
		$this->db->query("UPDATE game_description SET external_game_id = '6501' where game_code = '906501'");
		$this->db->query("UPDATE game_description SET external_game_id = '6515' where game_code = '906515'");
		$this->db->query("UPDATE game_description SET external_game_id = '6513' where game_code = '906513'");
		$this->db->query("UPDATE game_description SET external_game_id = '6555' where game_code = '906555'");
		$this->db->query("UPDATE game_description SET external_game_id = '6559' where game_code = '906559'");
		$this->db->query("UPDATE game_description SET external_game_id = '6546' where game_code = '906546'");
		$this->db->query("UPDATE game_description SET external_game_id = '6507' where game_code = '906507'");
		$this->db->query("UPDATE game_description SET external_game_id = '6523' where game_code = '906523'");
		$this->db->query("UPDATE game_description SET external_game_id = '6545' where game_code = '906545'");
		$this->db->query("UPDATE game_description SET external_game_id = '6529' where game_code = '896529'");
		$this->db->query("UPDATE game_description SET external_game_id = '6502' where game_code = '906502'");
		$this->db->query("UPDATE game_description SET external_game_id = '6509' where game_code = '906509'");
		$this->db->query("UPDATE game_description SET external_game_id = '6535' where game_code = '896535'");
		$this->db->query("UPDATE game_description SET external_game_id = '6510' where game_code = '906510'");
		$this->db->query("UPDATE game_description SET external_game_id = '6511' where game_code = '896511'");
		$this->db->query("UPDATE game_description SET external_game_id = '6531' where game_code = '896531'");
		$this->db->query("UPDATE game_description SET external_game_id = '6537' where game_code = '886537'");
		$this->db->query("UPDATE game_description SET external_game_id = '6521' where game_code = '896521'");
		$this->db->query("UPDATE game_description SET external_game_id = '6522' where game_code = '896522'");
		$this->db->query("UPDATE game_description SET external_game_id = '6521' where game_code = '896521'");

		$this->db->trans_complete();
	}

	public function down() {
	}
}
