<?php

defined('BASEPATH') OR exit('No direct script access allowed');

class Migration_update_seven_game_type_and_game_description_201609270515 extends CI_Migration {
    const FLAG_TRUE = 1;
    const FLAG_FALSE = 0;

    public function up() {

        $this->db->trans_start();

        $data = array(
            array(
                'game_type' => 'Slot',
                'game_type_lang' => 'slot',
                'status' => self::FLAG_TRUE,
                'flag_show_in_site' => self::FLAG_TRUE,
                'game_description_list' => array(
                    array( 'game_name' => 'Sweetie',
                        'english_name' => 'Sweetie',
                        'external_game_id' => 207,
                        'game_code' => 207,
                        'attributes' => 'adult_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'W XXX',
                        'english_name' => 'W XXX',
                        'external_game_id' => 212,
                        'game_code' => 212,
                        'attributes' => 'adult_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Baby Heart',
                        'english_name' => 'Baby Heart',
                        'external_game_id' => 229,
                        'game_code' => 229,
                        'attributes' => 'adult_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_TRUE,
                    ),
                    array( 'game_name' => 'City Night',
                        'english_name' => 'City Night',
                        'external_game_id' => 230,
                        'game_code' => 230,
                        'attributes' => 'adult_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_TRUE,
                    ),
                    array( 'game_name' => 'Rose and beauty',
                        'english_name' => 'Rose and beauty',
                        'external_game_id' => 231,
                        'game_code' => 231,
                        'attributes' => 'adult_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_TRUE,
                    ),
                    array( 'game_name' => 'Sexy XXX',
                        'english_name' => 'Sexy XXX',
                        'external_game_id' => 3,
                        'game_code' => 3,
                        'attributes' => 'adult_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Sexy Girl',
                        'english_name' => 'Sexy Girl',
                        'external_game_id' => 426,
                        'game_code' => 426,
                        'attributes' => 'adult_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_TRUE,
                    ),
                    array( 'game_name' => 'Holiday Bikini',
                        'english_name' => 'Holiday Bikini',
                        'external_game_id' => 427,
                        'game_code' => 427,
                        'attributes' => 'adult_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_TRUE,
                    ),
                    array( 'game_name' => 'Pink Lady',
                        'english_name' => 'Pink Lady',
                        'external_game_id' => 43,
                        'game_code' => 43,
                        'attributes' => 'adult_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_TRUE,
                    ),
                    array( 'game_name' => 'Hotel day',
                        'english_name' => 'Hotel day',
                        'external_game_id' => 44,
                        'game_code' => 44,
                        'attributes' => 'adult_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_TRUE,
                    ),
                    array( 'game_name' => 'Beauty in bed',
                        'english_name' => 'Beauty in bed',
                        'external_game_id' => 45,
                        'game_code' => 45,
                        'attributes' => 'adult_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_TRUE,
                    ),
                    array( 'game_name' => 'Night Dancers',
                        'english_name' => 'Night Dancers',
                        'external_game_id' => 606,
                        'game_code' => 606,
                        'attributes' => 'adult_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_TRUE,
                    ),
                    array( 'game_name' => 'Christmas Girl',
                        'english_name' => 'Christmas Girl',
                        'external_game_id' => 607,
                        'game_code' => 607,
                        'attributes' => 'adult_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_TRUE,
                    ),
                    array( 'game_name' => 'Sex and zen',
                        'english_name' => 'Sex and zen',
                        'external_game_id' => 608,
                        'game_code' => 608,
                        'attributes' => 'adult_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_TRUE,
                    ),
                    array( 'game_name' => 'Jinping mei',
                        'english_name' => 'Jinping mei',
                        'external_game_id' => 609,
                        'game_code' => 609,
                        'attributes' => 'adult_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_TRUE,
                    ),
                    array( 'game_name' => 'Due west',
                        'english_name' => 'Due west',
                        'external_game_id' => 610,
                        'game_code' => 610,
                        'attributes' => 'adult_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Money', // Classic slots
                        'english_name' => 'Money',
                        'external_game_id' => 1,
                        'game_code' => 1,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Spiderman',
                        'english_name' => 'Spiderman',
                        'external_game_id' => 10,
                        'game_code' => 10,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Starwars',
                        'english_name' => 'Starwars',
                        'external_game_id' => 11,
                        'game_code' => 11,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'FIFA',
                        'english_name' => 'FIFA',
                        'external_game_id' => 12,
                        'game_code' => 12,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Aladdin',
                        'english_name' => 'Aladdin',
                        'external_game_id' => 13,
                        'game_code' => 13,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Jackpot',
                        'english_name' => 'Jackpot',
                        'external_game_id' => 15,
                        'game_code' => 15,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Silent Samurai',
                        'english_name' => 'Silent Samurai',
                        'external_game_id' => 15,
                        'game_code' => 15,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Wealth Treasure',
                        'english_name' => 'Wealth Treasure',
                        'external_game_id' => 16,
                        'game_code' => 16,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Mystic Dragon',
                        'english_name' => 'Mystic Dragon',
                        'external_game_id' => 17,
                        'game_code' => 17,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Egyptian Treasure',
                        'english_name' => 'Egyptian Treasure',
                        'external_game_id' => 18,
                        'game_code' => 18,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Snow',
                        'english_name' => 'Snow',
                        'external_game_id' => 19,
                        'game_code' => 19,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Black Final',
                        'english_name' => 'Black Final',
                        'external_game_id' => 2,
                        'game_code' => 2,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Wild West Slots',
                        'english_name' => 'Wild West Slots',
                        'external_game_id' => 200,
                        'game_code' => 200,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Egypt Treasures',
                        'english_name' => 'Egypt Treasures',
                        'external_game_id' => 201,
                        'game_code' => 201,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Diamond',
                        'english_name' => 'Diamond',
                        'external_game_id' => 202,
                        'game_code' => 202,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Pharoh',
                        'english_name' => 'Pharoh',
                        'external_game_id' => 203,
                        'game_code' => 203,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Zombie Head',
                        'english_name' => 'Zombie Head',
                        'external_game_id' => 204,
                        'game_code' => 204,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Dragon Eye',
                        'english_name' => 'Dragon Eye',
                        'external_game_id' => 205,
                        'game_code' => 205,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Army God',
                        'english_name' => 'Army God',
                        'external_game_id' => 2206,
                        'game_code' => 206,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Aliens',
                        'english_name' => 'Aliens',
                        'external_game_id' => 208,
                        'game_code' => 208,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Horoscope',
                        'english_name' => 'Horoscope',
                        'external_game_id' => 209,
                        'game_code' => 209,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Lucky Shamrocks',
                        'english_name' => 'Lucky Shamrocs',
                        'external_game_id' => 21,
                        'game_code' => 21,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Hot G',
                        'english_name' => 'Hot G',
                        'external_game_id' => 210,
                        'game_code' => 210,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Rome',
                        'english_name' => 'Rome',
                        'external_game_id' => 213,
                        'game_code' => 213,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Sparta',
                        'english_name' => 'Sparta',
                        'external_game_id' => 214,
                        'game_code' => 214,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Victory',
                        'english_name' => 'Victory',
                        'external_game_id' => 215,
                        'game_code' => 215,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Gold Miner',
                        'english_name' => 'Gold Miner',
                        'external_game_id' => 216,
                        'game_code' => 216,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Golden Lotus',
                        'english_name' => 'Golden Lotus',
                        'external_game_id' => 217,
                        'game_code' => 217,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Triple Twister',
                        'english_name' => 'Triple Twister',
                        'external_game_id' => 218,
                        'game_code' => 218,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Pirate Treasure',
                        'english_name' => 'Pirate Treasure',
                        'external_game_id' => 219,
                        'game_code' => 219,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Duck',
                        'english_name' => 'Duck',
                        'external_game_id' => 22,
                        'game_code' => 22,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Million mixers',
                        'english_name' => 'Million mixers',
                        'external_game_id' => 220,
                        'game_code' => 220,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Barnyard blitz',
                        'english_name' => 'Barnyard blitz',
                        'external_game_id' => 221,
                        'game_code' => 221,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Summer days',
                        'english_name' => 'Summer days',
                        'external_game_id' => 222,
                        'game_code' => 222,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Pyramid',
                        'english_name' => 'Pyramid',
                        'external_game_id' => 4,
                        'game_code' => 4,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Alibaba',
                        'english_name' => 'Alibaba',
                        'external_game_id' => 400,
                        'game_code' => 400,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Skull',
                        'english_name' => 'Skull',
                        'external_game_id' => 401,
                        'game_code' => 401,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Robo Cyber X',
                        'english_name' => 'Robo Cyber X',
                        'external_game_id' => 402,
                        'game_code' => 402,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Robo Cyber Blue',
                        'english_name' => 'Robo Cyber Blue',
                        'external_game_id' => 403,
                        'game_code' => 403,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Tiger Titan',
                        'english_name' => 'Tiger Titan',
                        'external_game_id' => 404,
                        'game_code' => 404,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Robo',
                        'english_name' => 'Robo',
                        'external_game_id' => 406,
                        'game_code' => 406,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),

                    array( 'game_name' => 'Titan Titans',
                        'english_name' => 'Titan Titans',
                        'external_game_id' => 406,
                        'game_code' => 406,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Vampire',
                        'english_name' => 'Vampire',
                        'external_game_id' => 408,
                        'game_code' => 408,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Penqunin Vacation',
                        'english_name' => 'Pengunin Vacation',
                        'external_game_id' => 409,
                        'game_code' => 409,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Egyptian Cobra',
                        'english_name' => 'Egyptian Cobra',
                        'external_game_id' => 410,
                        'game_code' => 410,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Big Prosperity',
                        'english_name' => 'Big Prosperity',
                        'external_game_id' => 411,
                        'game_code' => 411,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Bigshot',
                        'english_name' => 'Bigshot',
                        'external_game_id' => 412,
                        'game_code' => 412,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Playboy',
                        'english_name' => 'Playboy',
                        'external_game_id' => 413,
                        'game_code' => 413,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Striper Night',
                        'english_name' => 'Striper Night',
                        'external_game_id' => 414,
                        'game_code' => 414,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Chinayear',
                        'english_name' => 'Chinayear',
                        'external_game_id' => 415,
                        'game_code' => 415,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Gold Rush',
                        'english_name' => 'Gold Rush',
                        'external_game_id' => 416,
                        'game_code' => 416,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Jewels',
                        'english_name' => 'Jewels',
                        'external_game_id' => 417,
                        'game_code' => 417,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Red Gothic',
                        'english_name' => 'Red Gothic',
                        'external_game_id' => 5,
                        'game_code' => 5,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Alien Ozone',
                        'english_name' => 'Alien Ozone',
                        'external_game_id' => 6,
                        'game_code' => 6,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Red Hot Wild',
                        'english_name' => 'Red Hot Wild',
                        'external_game_id' => 600,
                        'game_code' => 600,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),

                    array( 'game_name' => 'Magic Candy',
                        'english_name' => 'Magic Candy',
                        'external_game_id' => 601,
                        'game_code' => 601,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'The Great Wall',
                        'english_name' => 'The Great Wall',
                        'external_game_id' => 602,
                        'game_code' => 602,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'G Warrior',
                        'english_name' => 'G Warrior',
                        'external_game_id' => 8,
                        'game_code' => 8,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Baby G',     // End of Classic Slots
                        'english_name' => 'Baby G',
                        'external_game_id' => 9,
                        'game_code' => 9,
                        'attributes' => 'classic_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Zombie World',   // HD Slots
                        'english_name' => 'Zombie World',
                        'external_game_id' => 227,
                        'game_code' => 227,
                        'attributes' => 'hd_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Dragons',
                        'english_name' => 'Dragons',
                        'external_game_id' => 228,
                        'game_code' => 228,
                        'attributes' => 'hd_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'China Style',
                        'english_name' => 'China Style',
                        'external_game_id' => 23,
                        'game_code' => 23,
                        'attributes' => 'hd_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Constellation',
                        'english_name' => 'Constellation',
                        'external_game_id' => 232,
                        'game_code' => 232,
                        'attributes' => 'hd_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_TRUE,
                    ),
                    array( 'game_name' => 'Naval Battle',
                        'english_name' => 'Naval Battle',
                        'external_game_id' => 238,
                        'game_code' => 238,
                        'attributes' => 'hd_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Gold Mountain',
                        'english_name' => 'Gold Mountain',
                        'external_game_id' => 239,
                        'game_code' => 239,
                        'attributes' => 'hd_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'The Vikings',
                        'english_name' => 'The Vikings',
                        'external_game_id' => 242,
                        'game_code' => 242,
                        'attributes' => 'hd_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_TRUE,
                    ),
                    array( 'game_name' => 'Happy Farm',
                        'english_name' => 'Happy Farm',
                        'external_game_id' => 244,
                        'game_code' => 244,
                        'attributes' => 'hd_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_TRUE,
                    ),
                    array( 'game_name' => 'Egypt Style',
                        'english_name' => 'Egypt Style',
                        'external_game_id' => 26,
                        'game_code' => 26,
                        'attributes' => 'hd_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_TRUE,
                    ),
                    array( 'game_name' => 'Astrospace',
                        'english_name' => 'Astrospace',
                        'external_game_id' => 32,
                        'game_code' => 32,
                        'attributes' => 'hd_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Football',
                        'english_name' => 'Football',
                        'external_game_id' => 33,
                        'game_code' => 33,
                        'attributes' => 'hd_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_TRUE,
                    ),
                    array( 'game_name' => 'Mammon',
                        'english_name' => 'Mammon',
                        'external_game_id' => 35,
                        'game_code' => 35,
                        'attributes' => 'hd_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Icy World',
                        'english_name' => 'Icy World',
                        'external_game_id' => 40,
                        'game_code' => 40,
                        'attributes' => 'hd_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Aladdin Treasure',
                        'english_name' => 'Aladdin Treasure',
                        'external_game_id' => 418,
                        'game_code' => 418,
                        'attributes' => 'hd_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_TRUE,
                    ),
                    array( 'game_name' => 'Green Jungle',
                        'english_name' => 'Green Jungle',
                        'external_game_id' => 42,
                        'game_code' => 42,
                        'attributes' => 'hd_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Hunting',
                        'english_name' => 'Hunting',
                        'external_game_id' => 422,
                        'game_code' => 423,
                        'attributes' => 'hd_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Robo Punk',
                        'english_name' => 'Robo Punk',
                        'external_game_id' => 423,
                        'game_code' => 423,
                        'attributes' => 'hd_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),

                    // VAMPIRE
                    array( 'game_name' => 'Vampire Castle',
                        'english_name' => 'Vampire Castle',
                        'external_game_id' => 425,
                        'game_code' => 425,
                        'attributes' => 'hd_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_TRUE,
                    ),
                    array( 'game_name' => 'Bigshow',
                        'english_name' => 'Bigshow',
                        'external_game_id' => 429,
                        'game_code' => 429,
                        'attributes' => 'hd_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_TRUE,
                    ),
                    array( 'game_name' => 'Candy Shop',     // End of HD Slot
                        'english_name' => 'Candy Shop',
                        'external_game_id' => 604,
                        'game_code' => 604,
                        'attributes' => 'hd_slots','flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Keno HD',    // Table Game
                        'english_name' => 'Keno HD',
                        'external_game_id' => 2255,
                        'game_code' => 2255,
                        'attributes' => 'table_game', 'flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Roulette',
                        'english_name' => 'Roulette',
                        'external_game_id' => 2615,
                        'game_code' => 2615,
                        'attributes' => 'table_game', 'flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Deuces Wild HD 1 hands',
                        'english_name' => 'Deuces Wild HD 1 hands',
                        'external_game_id' => 2617,
                        'game_code' => 2617,
                        'attributes' => 'table_game', 'flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Deuces Wild HD 3 hands',
                        'english_name' => 'Deuces Wild HD 3 hands',
                        'external_game_id' => 2618,
                        'game_code' => 2618,
                        'attributes' => 'table_game', 'flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Deuces Wild HD 10 hands',
                        'english_name' => 'Deuces Wild HD 10 hands',
                        'external_game_id' => 2619,
                        'game_code' => 2619,
                        'attributes' => 'table_game', 'flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Deuces Wild HD 50 hands',
                        'english_name' => 'Deuces Wild HD 50 hands',
                        'external_game_id' => 2620,
                        'game_code' => 2620,
                        'attributes' => 'table_game', 'flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Jacks or Better HD 1 hands',
                        'english_name' => 'Jacks or Better HD 1 hands',
                        'external_game_id' => 2621,
                        'game_code' => 2621,
                        'attributes' => 'table_game', 'flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Jacks or Better HD 3 hands',
                        'english_name' => 'Jacks or Better HD 3 hands',
                        'external_game_id' => 2622,
                        'game_code' => 2622,
                        'attributes' => 'table_game', 'flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Jacks or Better HD 10 hands',
                        'english_name' => 'Jacks or Better HD 10 hands',
                        'external_game_id' => 2623,
                        'game_code' => 2623,
                        'attributes' => 'table_game', 'flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Jacks or Better HD 50 hands',
                        'english_name' => 'Jacks or Better HD 50 hands',
                        'external_game_id' => 2624,
                        'game_code' => 2624,
                        'attributes' => 'table_game', 'flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Joker Poker HD 1 hands',
                        'english_name' => 'Joker Poker HD 1 hands',
                        'external_game_id' => 2625,
                        'game_code' => 2625,
                        'attributes' => 'table_game', 'flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Joker Poker HD 3 hands',
                        'english_name' => 'Joker Poker HD 3 hands',
                        'external_game_id' => 2626,
                        'game_code' => 2626,
                        'attributes' => 'table_game', 'flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Joker Poker HD 10 hands',
                        'english_name' => 'Joker Poker HD 10 hands',
                        'external_game_id' => 2627,
                        'game_code' => 2627,
                        'attributes' => 'table_game', 'flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Joker Poker HD 50 hands',
                        'english_name' => 'Joker Poker HD 50 hands',
                        'external_game_id' => 2628,
                        'game_code' => 2628,
                        'attributes' => 'table_game', 'flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Baccarat HD',
                        'english_name' => 'Baccarat HD',
                        'external_game_id' => 2700,
                        'game_code' => 2700,
                        'attributes' => 'table_game', 'flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Caribbean HD',
                        'english_name' => 'Caribbean HD',
                        'external_game_id' => 2800,
                        'game_code' => 2800,
                        'attributes' => 'table_game', 'flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Monkey Game',
                        'english_name' => 'Monkey Game',
                        'external_game_id' => 3100,
                        'game_code' => 3100,
                        'attributes' => 'table_game', 'flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                    array( 'game_name' => 'Sicbo',
                        'english_name' => 'Sicbo',
                        'external_game_id' => 3200,
                        'game_code' => 3200,
                        'attributes' => 'table_game', 'flash_enabled' => self::FLAG_TRUE,
                        'html_five_enabled' => self::FLAG_FALSE,
                    ),
                ),
            ),
        );

        $game_description_list = array();
        foreach ($data as $game_type) {
            $this->db->insert('game_type', array(
                'game_platform_id' => SEVEN77_API,
                'game_type' => $game_type['game_type'],
                'game_type_lang' => $game_type['game_type_lang'],
                'status' => $game_type['status'],
                'flag_show_in_site' => $game_type['flag_show_in_site'],
            ));

            $game_type_id = $this->db->insert_id();
            foreach ($game_type['game_description_list'] as $game_description) {

                $game_description_list[] = array_merge(array(
                    'game_platform_id' => SEVEN77_API,
                    'game_type_id' => $game_type_id,
                ), $game_description);
            }
        }

        $this->db->insert_batch('game_description', $game_description_list);
        $this->db->trans_complete();

    }

    public function down() {
        $this->db->trans_start();
        $this->db->delete('game_type', array('game_platform_id' =>  SEVEN77_API, 'game_type' => 'Slot' ));
        $this->db->delete('game_description', array('game_platform_id' =>  SEVEN77_API ));
        $this->db->trans_complete();
    }
}