<div class="dashboard text-center">
    <div class="banner-container clearfix">
        <?=$this->CI->load->widget('banner', null, [
            'category' => CMSBANNER_CATEGORY_HOME
        ]);?>
    </div>

    <div class="home-games">
        <div class="row game-list">
            <div class="col-md-3 col-sm-4"><div class="games"><span class="top-color g-c-1"></span><img src="/ispc/images/lotterys/chongqing.png"><p>重庆时时彩</p><a class="btn g-c-1" href="/player_center/embed/player/player_center/goto_t1lottery/1/official/" data-lottery-id="official-1" data-embedded="1" data-target="lottery">立即投注</a></div></div>
            <div class="col-md-3 col-sm-4"><div class="games"><span class="top-color g-c-2"></span><img src="/ispc/images/lotterys/bei_jing.png"><p>北京赛车</p><a class="btn g-c-2" href="/player_center/embed/player/player_center/goto_t1lottery/10/official/" data-lottery-id="official-10" data-embedded="1" data-target="lottery">立即投注</a></div></div>
            <div class="col-md-3 col-sm-4"><div class="games"><span class="top-color g-c-4"></span><img src="/ispc/images/lotterys/hongkong.png"><p>香港六合彩</p><a class="btn g-c-4" href="/player_center/embed/player/player_center/goto_t1lottery/4/official/" data-lottery-id="official-4" data-embedded="1" data-target="lottery">立即投注</a></div></div>
            <div class="col-md-3 col-sm-4"><div class="games"><span class="top-color g-c-4"></span><img src="/images/game_icon/platform/ag-logo.png"><p>AG娱乐</p><a class="btn g-c-4" href="/iframe_module/goto_t1games/1013/null/real/0/null/2/newtab" target="_blank">立即投注</a></div></div>

<!--            <div class="col-md-3 col-sm-4"><div class="games"><span class="top-color g-c-1"></span><img src="/ispc/images/lotterys/chongqing.png"><p>重庆时时彩</p><a class="btn g-c-1" href="/player_center/embed/player/player_center/goto_t1lottery/1/official/" data-lottery-id="official-1" data-embedded="1" data-target="lottery">立即投注</a></div></div>-->
<!--            <div class="col-md-3 col-sm-4"><div class="games"><span class="top-color g-c-2"></span><img src="/ispc/images/lotterys/xinjiang.png"><p>新疆时时彩</p><a class="btn g-c-2" href="/player_center/embed/player/player_center/goto_t1lottery/2/official/" data-lottery-id="official-2" data-embedded="1" data-target="lottery">立即投注</a></div></div>-->
<!--            <div class="col-md-3 col-sm-4"><div class="games"><span class="top-color g-c-3"></span><img src="/ispc/images/lotterys/tianjin.png"><p>天津时时彩</p><a class="btn g-c-3" href="/player_center/embed/player/player_center/goto_t1lottery/3/official/" data-lottery-id="official-3" data-embedded="1" data-target="lottery">立即投注</a></div></div>-->
<!--            <div class="col-md-3 col-sm-4"><div class="games"><span class="top-color g-c-4"></span><img src="/ispc/images/lotterys/hongkong.png"><p>香港六合彩</p><a class="btn g-c-4" href="/player_center/embed/player/player_center/goto_t1lottery/4/official/" data-lottery-id="official-4" data-embedded="1" data-target="lottery">立即投注</a></div></div>-->
<!--            <div class="col-md-3 col-sm-4"><div class="games"><span class="top-color g-c-5"></span><img src="/ispc/images/lotterys/shandong.png"><p>山东11选5</p><a class="btn g-c-5" href="/player_center/embed/player/player_center/goto_t1lottery/5/official/" data-lottery-id="official-5" data-embedded="1" data-target="lottery">立即投注</a></div></div>-->
<!--            <div class="col-md-3 col-sm-4"><div class="games"><span class="top-color g-c-6"></span><img src="/ispc/images/lotterys/jiangxi.png"><p>江西11选5</p><a class="btn g-c-6" href="/player_center/embed/player/player_center/goto_t1lottery/6/official/" data-lottery-id="official-6" data-embedded="1" data-target="lottery">立即投注</a></div></div>-->
<!--            <div class="col-md-3 col-sm-4"><div class="games"><span class="top-color g-c-7"></span><img src="/ispc/images/lotterys/guangdong.png"><p>广东11选5</p><a class="btn g-c-7" href="/player_center/embed/player/player_center/goto_t1lottery/7/official/" data-lottery-id="official-7" data-embedded="1" data-target="lottery">立即投注</a></div></div>-->
<!--            <div class="col-md-3 col-sm-4"><div class="games"><span class="top-color g-c-8"></span><img src="/ispc/images/lotterys/jiang_su.png"><p>江苏快3</p><a class="btn g-c-8" href="/player_center/embed/player/player_center/goto_t1lottery/8/official/" data-lottery-id="official-8" data-embedded="1" data-target="lottery">立即投注</a></div></div>-->
<!--            <div class="col-md-3 col-sm-4"><div class="games"><span class="top-color g-c-1"></span><img src="/ispc/images/lotterys/an_hui.png"><p>安徽快3</p><a class="btn g-c-1" href="/player_center/embed/player/player_center/goto_t1lottery/9/official/" data-lottery-id="official-9" data-embedded="1" data-target="lottery">立即投注</a></div></div>-->
<!--            <div class="col-md-3 col-sm-4"><div class="games"><span class="top-color g-c-2"></span><img src="/ispc/images/lotterys/bei_jing.png"><p>北京赛车</p><a class="btn g-c-2" href="/player_center/embed/player/player_center/goto_t1lottery/10/official/" data-lottery-id="official-10" data-embedded="1" data-target="lottery">立即投注</a></div></div>-->
<!--            <div class="col-md-3 col-sm-4"><div class="games"><span class="top-color g-c-3"></span><img src="/ispc/images/lotterys/fu_cai.png"><p>福彩3D</p><a class="btn g-c-3" href="/player_center/embed/player/player_center/goto_t1lottery/11/official/" data-lottery-id="official-11" data-embedded="1" data-target="lottery">立即投注</a></div></div>-->
<!--            <div class="col-md-3 col-sm-4"><div class="games"><span class="top-color g-c-4"></span><img src="/ispc/images/lotterys/pai_lie.png"><p>排列3</p><a class="btn g-c-4" href="/player_center/embed/player/player_center/goto_t1lottery/12/official/" data-lottery-id="official-12" data-embedded="1" data-target="lottery">立即投注</a></div></div>-->
<!--            <div class="col-md-3 col-sm-4"><div class="games"><span class="top-color g-c-5"></span><img src="/ispc/images/lotterys/pai_lie.png"><p>排列5</p><a class="btn g-c-5" href="/player_center/embed/player/player_center/goto_t1lottery/13/official/" data-lottery-id="official-13" data-embedded="1" data-target="lottery">立即投注</a></div></div>-->
<!--            <div class="col-md-3 col-sm-4"><div class="games"><span class="top-color g-c-6"></span><img src="/ispc/images/lotterys/chaojida_letou.png"><p>重庆快乐十分</p><a class="btn g-c-6" href="/player_center/embed/player/player_center/goto_t1lottery/14/official/" data-lottery-id="official-14" data-embedded="1" data-target="lottery">立即投注</a></div></div>-->
<!--            <div class="col-md-3 col-sm-4"><div class="games"><span class="top-color g-c-7"></span><img src="/ispc/images/lotterys/kuaileshi.png"><p>广东快乐十分</p><a class="btn g-c-7" href="/player_center/embed/player/player_center/goto_t1lottery/15/official/" data-lottery-id="official-15" data-embedded="1" data-target="lottery">立即投注</a></div></div>-->
<!--            <div class="col-md-3 col-sm-4"><div class="games"><span class="top-color g-c-8"></span><img src="/ispc/images/lotterys/chaojida_letou.png"><p>超级大乐透</p><a class="btn g-c-8" href="/player_center/embed/player/player_center/goto_t1lottery/16/official/" data-lottery-id="official-16" data-embedded="1" data-target="lottery">立即投注</a></div></div>-->
<!--            <div class="col-md-3 col-sm-4"><div class="games"><span class="top-color g-c-1"></span><img src="/ispc/images/lotterys/shuang_seqiu.png"><p>双色球</p><a class="btn g-c-1" href="/player_center/embed/player/player_center/goto_t1lottery/17/official/" data-lottery-id="official-17" data-embedded="1" data-target="lottery">立即投注</a></div></div>-->
<!--            <div class="col-md-3 col-sm-4"><div class="games"><span class="top-color g-c-2"></span><img src="/ispc/images/lotterys/fenfen.png"><p>自营分分彩</p><a class="btn g-c-2" href="/player_center/embed/player/player_center/goto_t1lottery/18/official/" data-lottery-id="official-18" data-embedded="1" data-target="lottery">立即投注</a></div></div>-->
<!--            <div class="col-md-3 col-sm-4"><div class="games"><span class="top-color g-c-3"></span><img src="/ispc/images/lotterys/miaomiao.png"><p>自营秒秒彩</p><a class="btn g-c-3" href="/player_center/embed/player/player_center/goto_t1lottery/19/official/" data-lottery-id="official-19" data-embedded="1" data-target="lottery">立即投注</a></div></div>-->
<!--            <div class="col-md-3 col-sm-4"><div class="games"><span class="top-color g-c-4"></span><img src="/images/game_icon/platform/ag-logo.png"><p>AG娱乐</p><a class="btn g-c-4" href="/iframe_module/goto_t1games/1013/null/real/0/null/2/newtab" target="_blank">立即投注</a></div></div>-->
        </div>
    </div>
</div>