
INSERT INTO roles (roleName, createTime, createPerson, status, isAdmin) values('QA',NOW(),'admin (super admin)','0','0');

set @roleId=LAST_INSERT_ID();

insert into rolefunctions (roleId, funcId) values(@roleId,'1');
insert into rolefunctions (roleId, funcId) values(@roleId,'2');
insert into rolefunctions (roleId, funcId) values(@roleId,'3');
insert into rolefunctions (roleId, funcId) values(@roleId,'4');
insert into rolefunctions (roleId, funcId) values(@roleId,'5');
insert into rolefunctions (roleId, funcId) values(@roleId,'6');
insert into rolefunctions (roleId, funcId) values(@roleId,'8');
insert into rolefunctions (roleId, funcId) values(@roleId,'9');
insert into rolefunctions (roleId, funcId) values(@roleId,'10');
insert into rolefunctions (roleId, funcId) values(@roleId,'11');
insert into rolefunctions (roleId, funcId) values(@roleId,'12');
insert into rolefunctions (roleId, funcId) values(@roleId,'13');
insert into rolefunctions (roleId, funcId) values(@roleId,'14');
insert into rolefunctions (roleId, funcId) values(@roleId,'15');
insert into rolefunctions (roleId, funcId) values(@roleId,'16');
insert into rolefunctions (roleId, funcId) values(@roleId,'17');
insert into rolefunctions (roleId, funcId) values(@roleId,'18');
insert into rolefunctions (roleId, funcId) values(@roleId,'19');
insert into rolefunctions (roleId, funcId) values(@roleId,'20');
insert into rolefunctions (roleId, funcId) values(@roleId,'21');
insert into rolefunctions (roleId, funcId) values(@roleId,'22');
insert into rolefunctions (roleId, funcId) values(@roleId,'23');
insert into rolefunctions (roleId, funcId) values(@roleId,'24');
insert into rolefunctions (roleId, funcId) values(@roleId,'25');
insert into rolefunctions (roleId, funcId) values(@roleId,'26');
insert into rolefunctions (roleId, funcId) values(@roleId,'27');
insert into rolefunctions (roleId, funcId) values(@roleId,'31');
insert into rolefunctions (roleId, funcId) values(@roleId,'32');
insert into rolefunctions (roleId, funcId) values(@roleId,'33');
insert into rolefunctions (roleId, funcId) values(@roleId,'36');
insert into rolefunctions (roleId, funcId) values(@roleId,'37');
insert into rolefunctions (roleId, funcId) values(@roleId,'38');
insert into rolefunctions (roleId, funcId) values(@roleId,'39');
insert into rolefunctions (roleId, funcId) values(@roleId,'40');
insert into rolefunctions (roleId, funcId) values(@roleId,'41');
insert into rolefunctions (roleId, funcId) values(@roleId,'42');
insert into rolefunctions (roleId, funcId) values(@roleId,'43');
insert into rolefunctions (roleId, funcId) values(@roleId,'44');
insert into rolefunctions (roleId, funcId) values(@roleId,'45');
insert into rolefunctions (roleId, funcId) values(@roleId,'46');
insert into rolefunctions (roleId, funcId) values(@roleId,'48');
insert into rolefunctions (roleId, funcId) values(@roleId,'49');
insert into rolefunctions (roleId, funcId) values(@roleId,'50');
insert into rolefunctions (roleId, funcId) values(@roleId,'51');
insert into rolefunctions (roleId, funcId) values(@roleId,'52');
insert into rolefunctions (roleId, funcId) values(@roleId,'53');
insert into rolefunctions (roleId, funcId) values(@roleId,'54');
insert into rolefunctions (roleId, funcId) values(@roleId,'55');
insert into rolefunctions (roleId, funcId) values(@roleId,'56');
insert into rolefunctions (roleId, funcId) values(@roleId,'57');
insert into rolefunctions (roleId, funcId) values(@roleId,'58');
insert into rolefunctions (roleId, funcId) values(@roleId,'59');
insert into rolefunctions (roleId, funcId) values(@roleId,'60');
insert into rolefunctions (roleId, funcId) values(@roleId,'61');
insert into rolefunctions (roleId, funcId) values(@roleId,'62');
insert into rolefunctions (roleId, funcId) values(@roleId,'65');
insert into rolefunctions (roleId, funcId) values(@roleId,'66');
insert into rolefunctions (roleId, funcId) values(@roleId,'67');
insert into rolefunctions (roleId, funcId) values(@roleId,'68');
insert into rolefunctions (roleId, funcId) values(@roleId,'69');
insert into rolefunctions (roleId, funcId) values(@roleId,'70');
insert into rolefunctions (roleId, funcId) values(@roleId,'71');
insert into rolefunctions (roleId, funcId) values(@roleId,'72');
insert into rolefunctions (roleId, funcId) values(@roleId,'73');
insert into rolefunctions (roleId, funcId) values(@roleId,'74');
insert into rolefunctions (roleId, funcId) values(@roleId,'77');
insert into rolefunctions (roleId, funcId) values(@roleId,'78');
insert into rolefunctions (roleId, funcId) values(@roleId,'79');
insert into rolefunctions (roleId, funcId) values(@roleId,'80');
insert into rolefunctions (roleId, funcId) values(@roleId,'81');
insert into rolefunctions (roleId, funcId) values(@roleId,'82');
insert into rolefunctions (roleId, funcId) values(@roleId,'83');
insert into rolefunctions (roleId, funcId) values(@roleId,'84');
insert into rolefunctions (roleId, funcId) values(@roleId,'85');
insert into rolefunctions (roleId, funcId) values(@roleId,'86');
insert into rolefunctions (roleId, funcId) values(@roleId,'88');
insert into rolefunctions (roleId, funcId) values(@roleId,'89');
insert into rolefunctions (roleId, funcId) values(@roleId,'90');
insert into rolefunctions (roleId, funcId) values(@roleId,'91');
insert into rolefunctions (roleId, funcId) values(@roleId,'92');
insert into rolefunctions (roleId, funcId) values(@roleId,'93');
insert into rolefunctions (roleId, funcId) values(@roleId,'94');
insert into rolefunctions (roleId, funcId) values(@roleId,'95');
insert into rolefunctions (roleId, funcId) values(@roleId,'96');
insert into rolefunctions (roleId, funcId) values(@roleId,'97');
insert into rolefunctions (roleId, funcId) values(@roleId,'98');
insert into rolefunctions (roleId, funcId) values(@roleId,'100');
insert into rolefunctions (roleId, funcId) values(@roleId,'101');
insert into rolefunctions (roleId, funcId) values(@roleId,'102');
insert into rolefunctions (roleId, funcId) values(@roleId,'103');
insert into rolefunctions (roleId, funcId) values(@roleId,'104');
insert into rolefunctions (roleId, funcId) values(@roleId,'105');
insert into rolefunctions (roleId, funcId) values(@roleId,'106');
insert into rolefunctions (roleId, funcId) values(@roleId,'107');
insert into rolefunctions (roleId, funcId) values(@roleId,'108');
insert into rolefunctions (roleId, funcId) values(@roleId,'109');
insert into rolefunctions (roleId, funcId) values(@roleId,'110');
insert into rolefunctions (roleId, funcId) values(@roleId,'111');
insert into rolefunctions (roleId, funcId) values(@roleId,'112');
insert into rolefunctions (roleId, funcId) values(@roleId,'113');
insert into rolefunctions (roleId, funcId) values(@roleId,'115');
insert into rolefunctions (roleId, funcId) values(@roleId,'116');
insert into rolefunctions (roleId, funcId) values(@roleId,'117');
insert into rolefunctions (roleId, funcId) values(@roleId,'118');
insert into rolefunctions (roleId, funcId) values(@roleId,'119');
insert into rolefunctions (roleId, funcId) values(@roleId,'120');
insert into rolefunctions (roleId, funcId) values(@roleId,'121');
insert into rolefunctions (roleId, funcId) values(@roleId,'122');
insert into rolefunctions (roleId, funcId) values(@roleId,'123');
insert into rolefunctions (roleId, funcId) values(@roleId,'124');
insert into rolefunctions (roleId, funcId) values(@roleId,'125');
insert into rolefunctions (roleId, funcId) values(@roleId,'126');
insert into rolefunctions (roleId, funcId) values(@roleId,'127');
insert into rolefunctions (roleId, funcId) values(@roleId,'128');
insert into rolefunctions (roleId, funcId) values(@roleId,'129');
insert into rolefunctions (roleId, funcId) values(@roleId,'130');
insert into rolefunctions (roleId, funcId) values(@roleId,'131');
insert into rolefunctions (roleId, funcId) values(@roleId,'132');
insert into rolefunctions (roleId, funcId) values(@roleId,'133');
insert into rolefunctions (roleId, funcId) values(@roleId,'134');
insert into rolefunctions (roleId, funcId) values(@roleId,'135');
insert into rolefunctions (roleId, funcId) values(@roleId,'136');
insert into rolefunctions (roleId, funcId) values(@roleId,'137');
insert into rolefunctions (roleId, funcId) values(@roleId,'138');
insert into rolefunctions (roleId, funcId) values(@roleId,'139');
insert into rolefunctions (roleId, funcId) values(@roleId,'140');
insert into rolefunctions (roleId, funcId) values(@roleId,'141');
insert into rolefunctions (roleId, funcId) values(@roleId,'142');
insert into rolefunctions (roleId, funcId) values(@roleId,'143');
insert into rolefunctions (roleId, funcId) values(@roleId,'144');
insert into rolefunctions (roleId, funcId) values(@roleId,'145');
insert into rolefunctions (roleId, funcId) values(@roleId,'146');
insert into rolefunctions (roleId, funcId) values(@roleId,'147');
insert into rolefunctions (roleId, funcId) values(@roleId,'148');
insert into rolefunctions (roleId, funcId) values(@roleId,'149');
insert into rolefunctions (roleId, funcId) values(@roleId,'150');
insert into rolefunctions (roleId, funcId) values(@roleId,'151');
insert into rolefunctions (roleId, funcId) values(@roleId,'152');
insert into rolefunctions (roleId, funcId) values(@roleId,'153');
insert into rolefunctions (roleId, funcId) values(@roleId,'154');
insert into rolefunctions (roleId, funcId) values(@roleId,'155');
insert into rolefunctions (roleId, funcId) values(@roleId,'156');
insert into rolefunctions (roleId, funcId) values(@roleId,'157');
insert into rolefunctions (roleId, funcId) values(@roleId,'158');
insert into rolefunctions (roleId, funcId) values(@roleId,'159');
insert into rolefunctions (roleId, funcId) values(@roleId,'160');
insert into rolefunctions (roleId, funcId) values(@roleId,'161');
insert into rolefunctions (roleId, funcId) values(@roleId,'162');
insert into rolefunctions (roleId, funcId) values(@roleId,'163');
insert into rolefunctions (roleId, funcId) values(@roleId,'164');
insert into rolefunctions (roleId, funcId) values(@roleId,'165');
insert into rolefunctions (roleId, funcId) values(@roleId,'166');
insert into rolefunctions (roleId, funcId) values(@roleId,'167');
insert into rolefunctions (roleId, funcId) values(@roleId,'168');
insert into rolefunctions (roleId, funcId) values(@roleId,'169');
insert into rolefunctions (roleId, funcId) values(@roleId,'170');
insert into rolefunctions (roleId, funcId) values(@roleId,'171');
insert into rolefunctions (roleId, funcId) values(@roleId,'172');
insert into rolefunctions (roleId, funcId) values(@roleId,'181');
insert into rolefunctions (roleId, funcId) values(@roleId,'182');

INSERT INTO adminusers (
  username, password, realname, department, position, email, safetyQuestion, answer, lastLoginIp, lastLoginTime, lastLogoutTime, createTime, createPerson, status, note, session, maxWidAmt, approvedWidAmt, session_id, deleted, singleWidAmt)
 values('qatest','$P$BRYWcXD7hE.lDX81cFC3/uomojhuCs/','qatest','qatest','qatest','qatest@test.com','','', NULL ,'0000-00-00 00:00:00','0000-00-00 00:00:00',NOW(),'1','1','','','10000','0','','0',NULL);


INSERT INTO userroles (userId, roleId)
     VALUES (LAST_INSERT_ID(), @roleId);

INSERT INTO genealogy (generation, gene,  roleId)
     VALUES ('2','1', @roleId);


 