                    <th><?=lang('system.word38');?></th>
                    <th><?=lang('player.ug01');?></th>
                    <th><?=lang('cms.gameprovider');?></th>
                    <th><?=lang('cms.gametype');?></th>
                    <th><?=lang('cms.gamename');?></th>
                    <th><?=lang('Round No');?></th>
                    <th><?=lang('cms.betAmount');?></th>
                    <th><?=lang('mark.resultAmount');?></th>
                    <th><?=lang('lang.bet.plus.result');?></th>
                    <th><?=lang('Game Rolling Comm');?></th>
                    <th><?=lang('Rolling Comm Amt');?></th>
