<link rel="stylesheet" href="<?= site_url() . 'resources/third_party/json-editor/2.9.1/html.min.css' ?>"></link>
<script type="text/javascript" src="<?= site_url() . 'resources/third_party/json-editor/2.9.1/jsoneditor.min.js' ?>"></script>

<script type="text/javascript">
JSONEditor.defaults.languages.en = {
    error_notset: `<?php echo lang('json-editor.error_notset'); ?>`,
    error_notempty: `<?php echo lang('json-editor.error_notempty'); ?>`,
    error_enum: `<?php echo lang('json-editor.error_enum'); ?>`,
    error_anyOf: `<?php echo lang('json-editor.error_anyOf'); ?>`,
    error_oneOf: `<?php echo lang('json-editor.error_oneOf'); ?>`,
    error_not: `<?php echo lang('json-editor.error_not'); ?>`,
    error_type_union: `<?php echo lang('json-editor.error_type_union'); ?>`,
    error_type: `<?php echo lang('json-editor.error_type'); ?>`,
    error_disallow_union: `<?php echo lang('json-editor.error_disallow_union'); ?>`,
    error_disallow: `<?php echo lang('json-editor.error_disallow'); ?>`,
    error_multipleOf: `<?php echo lang('json-editor.error_multipleOf'); ?>`,
    error_maximum_excl: `<?php echo lang('json-editor.error_maximum_excl'); ?>`,
    error_maximum_incl: `<?php echo lang('json-editor.error_maximum_incl'); ?>`,
    error_minimum_excl: `<?php echo lang('json-editor.error_minimum_excl'); ?>`,
    error_minimum_incl: `<?php echo lang('json-editor.error_minimum_incl'); ?>`,
    error_maxLength: `<?php echo lang('json-editor.error_maxLength'); ?>`,
    error_minLength: `<?php echo lang('json-editor.error_minLength'); ?>`,
    error_pattern: `<?php echo lang('json-editor.error_pattern'); ?>`,
    error_additionalItems: `<?php echo lang('json-editor.error_additionalItems'); ?>`,
    error_maxItems: `<?php echo lang('json-editor.error_maxItems'); ?>`,
    error_minItems: `<?php echo lang('json-editor.error_minItems'); ?>`,
    error_uniqueItems: `<?php echo lang('json-editor.error_uniqueItems'); ?>`,
    error_maxProperties: `<?php echo lang('json-editor.error_maxProperties'); ?>`,
    error_minProperties: `<?php echo lang('json-editor.error_minProperties'); ?>`,
    error_required: `<?php echo lang('json-editor.error_required'); ?>`,
    error_additional_properties: `<?php echo lang('json-editor.error_additional_properties'); ?>`,
    error_dependency: `<?php echo lang('json-editor.error_dependency'); ?>`,
    button_edit_json: `<?php echo lang('json-editor.button_edit_json'); ?>`,
    button_object_properties: `<?php echo lang('json-editor.button_object_properties'); ?>`,
    button_delete_all: `<?php echo lang('json-editor.button_delete_all'); ?>`,
    button_delete_all_title: `<?php echo lang('json-editor.button_delete_all_title'); ?>`,
    button_delete_last: `<?php echo lang('json-editor.button_delete_last'); ?>`,
    button_delete_last_title: `<?php echo lang('json-editor.button_delete_last_title'); ?>`,
    button_add_row_title: `<?php echo lang('json-editor.button_add_row_title'); ?>`,
    button_move_down_title: `<?php echo lang('json-editor.button_move_down_title'); ?>`,
    button_move_up_title: `<?php echo lang('json-editor.button_move_up_title'); ?>`,
    button_delete_row_title: `<?php echo lang('json-editor.button_delete_row_title'); ?>`,
    button_delete_row_title_short: `<?php echo lang('json-editor.button_delete_row_title_short'); ?>`,
    button_collapse: `<?php echo lang('json-editor.button_collapse'); ?>`,
    button_expand: `<?php echo lang('json-editor.button_expand'); ?>`,
    button_save: `<?php echo lang('json-editor.button_save'); ?>`,
    button_copy: `<?php echo lang('json-editor.button_copy'); ?>`,
    button_cancel: `<?php echo lang('json-editor.button_cancel'); ?>`,
};
</script>